----------------------------------------------------------
-- EMR Compatibility
UPDATE Language_ko_KR
SET Text = '[ICON_RES_BEER] 맥주, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TRADER_SIDS', 'TXT_KEY_BUILDING_TRADER_SIDS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_CHEESE] 치즈, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CENTAURUS_EXTRACTORS', 'TXT_KEY_BUILDING_CENTAURUS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_OBSIDIAN] 흑요석, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_HEXXON_REFINERY', 'TXT_KEY_BUILDING_HEXXON_REFINERY_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_CHAMPAGNE] 샴페인, [ICON_RES_LAVENDER] 라벤더, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_TIN] 주석, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_FIRAXITE_MATERIALS', 'TXT_KEY_BUILDING_FIRAXITE_MATERIALS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_HONEY] 꿀, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_MANUSCRIPTS] 원고, [ICON_RES_PLATINUM] 백금, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CIVILIZED_JEWELERS', 'TXT_KEY_BUILDING_CIVILIZED_JEWELERS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_BIRDS_NEST] {TXT_KEY_RESOURCE_BIRDS_NEST}, [ICON_RES_POPPY] 양귀비, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_POPULI_MEDICINE', 'TXT_KEY_BUILDING_POPULI_MEDICINE_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

---------------------------------------------------
-- now some custom civs
UPDATE Language_ko_KR
SET Text = '[ICON_RES_JAR_WILDLIFE] 야생 동물, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_POPULI_MEDICINE', 'TXT_KEY_BUILDING_POPULI_MEDICINE_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_WILDLIFE');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_JAR_YAK] 야크, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_YAK');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_JAR_BUCCHERO] 부케로, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BUCCHERO');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_SHRIMP] 새우, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CENTAURUS_EXTRACTORS', 'TXT_KEY_BUILDING_CENTAURUS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_SHRIMP');

-------------------------------------------------------
-- camels, feathers, quartz, alpacas
UPDATE Language_ko_KR
SET Text = '[ICON_RES_FEATHERS] 깃털, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_FEATHERS');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_CAMEL] 낙타, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_CAMEL');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_QUARTZ] 석영, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_FIRAXITE_MATERIALS', 'TXT_KEY_BUILDING_FIRAXITE_MATERIALS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_QUARTZ');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_ALPACA] 알파카, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_ALPACA');