INSERT OR REPLACE INTO Audio_Sounds (SoundID, Filename, LoadType)
SELECT 'SND_EVENT_EBANK', 'EBankCashCash', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECROWDCHEER', 'ECrowdCheer', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECULTUREEXPANDS', 'ECultureExpands', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EDISCOVERY', 'EDiscovery', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EGOLDENAGE', 'EGoldenAge', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EGREATPEOPLE', 'EGreatPeople', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EREVOLUTIONSTART', 'ERevolutionStart', 'DynamicResident';

INSERT OR REPLACE INTO Audio_2DSounds (ScriptID, SoundID, SoundType, DontTriggerDuplicates, DontPlayMoreThan, TaperSoundtrackVolume, MinVolume, MaxVolume)
SELECT 'AS2D_EVENT_EBANK', 'SND_EVENT_EBANK', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECROWDCHEER', 'SND_EVENT_ECROWDCHEER', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECULTUREEXPANDS', 'SND_EVENT_ECULTUREEXPANDS', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EDISCOVERY', 'SND_EVENT_EDISCOVERY', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EGOLDENAGE', 'SND_EVENT_EGOLDENAGE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EGREATPEOPLE', 'SND_EVENT_EGREATPEOPLE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EREVOLUTIONSTART', 'SND_EVENT_EREVOLUTIONSTART', 'GAME_SFX', 1, 1, -1.0, 100, 100;

UPDATE Events SET EventAudio = 'AS2D_EVENT_ECULTUREEXPANDS' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC';
UPDATE Events SET EventAudio = 'AS2D_EVENT_EDISCOVERY' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC';
UPDATE Events SET EventAudio = 'AS2D_EVENT_EGREATPEOPLE' WHERE Type = 'PLAYER_EVENT_LABORCIVIC';
UPDATE Events SET EventAudio = 'AS2D_EVENT_EBANK' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC';
UPDATE Events SET EventAudio = 'AS2D_EVENT_EGOLDENAGE' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_ECROWDCHEER' WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_ECROWDCHEER' WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_8';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_1';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_2';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_3';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_4';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_5';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_6';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_7';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_ECROWDCHEER' WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_8';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_ECROWDCHEER' WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_EREVOLUTIONSTART' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7';
UPDATE EventChoices SET EventChoiceAudio = 'AS2D_EVENT_ECROWDCHEER' WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8';