UPDATE CustomModOptions SET Value = 1 WHERE Name = 'ROUTE_PLANNER';

INSERT INTO InterfaceModes("Type", "Description", "CursorType")
VALUES ("INTERFACEMODE_ROUTE_PLANNER_DRAW", "TXT_KEY_INTERFACEMODE_ROUTE_PLANNER_DRAW", "CURSOR_DEFAULT");