INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	('ko_KR', 'TXT_KEY_BUILDING_ATASH', '아타쉬'),
	('ko_KR', 'TXT_KEY_BUILDING_AUL', '아울'),
	--('ko_KR', 'TXT_KEY_BUILDING_GURDWARABN', '구루드와라'),
	('ko_KR', 'TXT_KEY_BUILDING_XUEMIAO', '공자묘'),
	('ko_KR', 'TXT_KEY_BUILDING_JINJA', '신사'),
	('ko_KR', 'TXT_KEY_BUILDING_ATASH_STRATEGY', '아타쉬 신앙을 따르는 종교의 도시에서만 건설할 수 있습니다. [ICON_PEACE] 신앙으로 구매하여 이 건물을 건설하세요. 아타쉬를 건설하면 신앙과 문화를 얻을 수 있고, 신앙이 어느 정도 쌓이면 도시에 과학이 생깁니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_AUL_STRATEGY', '아울 신앙을 따르는 종교 도시에서만 건설할 수 있습니다. [ICON_PEACE] 신앙으로 구매하여 이 건물을 건설하세요. 아울을 건설하면 신앙, 위대한 장군 점수, 군사 보급을 얻을 수 있습니다.'),
	--('ko_KR', 'TXT_KEY_BUILDING_GURDWARABN_STRATEGY', '구루드와라 신앙을 따르는 종교 도시에서만 건설할 수 있습니다. [ICON_PEACE] 신앙으로 구매하여 이 건물을 건설하세요. 구루드와라를 건설하면 신앙과 걸작 슬롯을 얻고 무료, 피로, 문맹, 빈곤을 줄일 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_XUEMIAO_STRATEGY', '공자묘 신앙을 따르는 도시에서만 건설할 수 있습니다.[ICON_PEACE] 신앙으로 구매하여 이 건물을 건설하세요. 공자묘를 건설하면 위인을 더 빨리 얻을 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_JINJA_STRATEGY', '신사 신앙을 따르는 종교 도시에서만 건설할 수 있습니다.[ICON_PEACE] 신앙으로 구매하여 이 건물을 건설하세요. 신사를 건설하면 신앙과 위대한 제독 점수를 얻을 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_ATASH_TEXT', '조로아스터교의 예배 장소입니다. 그 안에는 깨끗한 물과 불이 있는데, 이 두 가지를 섞으면 삶의 순수함이 생겨납니다. 조로아스터교에서는 재가 삶과 종교의 상징을 만드는 데 중요한 역할을 합니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_AUL_TEXT', '텡그리 신앙의 사실상 예배 장소에 해당하는 곳입니다. 이 마을들은 거대한 나무에 기도를 올리는 예배 장소로 사용되었다고 합니다. 하지만 텡그리 신앙의 추종자들은 대부분 자연 그 자체에서 예배 장소를 찾았습니다.'),
	--('ko_KR', 'TXT_KEY_BUILDING_GURDWARABN_TEXT', '시크교의 예배 장소입니다. 이러한 구루드와라에서는 신앙이 있든 없든 모든 사람을 환영하며, 그곳에서 그들은 구루 또는 전능한 지식에 이르는 길을 찾을 수 있습니다.내부에서는 모든 신앙이 존중받는 환영과 다양성의 장소를 찾을 수 있으며, 모든 신앙은 결국 시크교의 평화와 지식에 대한 믿음으로 이어져야 합니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_XUEMIAO_TEXT', '유교에서 이 곳은 예배 장소가 아니라 공부의 장소에 가깝습니다. 현자와 철학자들은 이 장소에서 위안을 얻었을 것입니다. 이곳은 공부하고 배우고자 하는 모든 이에게 학습과 연구의 사원이었기 때문입니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_JINJA_TEXT', '신토의 예배 장소입니다. 이러한 신사의 내부는 주로 예배 장소로 사용되기보다는 영혼에게 바칠 문화적 가치 있는 물건을 보관하는 장소로 사용되었습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_ATASH_HELP', '이 도시에서 나오는 [ICON_RELIGION] 다수 종교의 압력이 25% 증가합니다. 이 도시의 [ICON_PEACE] 신앙 15%가 매 턴 [ICON_RESEARCH] 과학으로 전환됩니다. 도시 국가 친구에게서 [ICON_PEACE] 신앙 +1, 도시 국가 동맹에게서 [ICON_PEACE] 신앙 +1 를 추가로 획득합니다.[NEWLINE][NEWLINE][ICON_CULTURE] 무료로 인한 [ICON_HAPPINESS_3] 불행이 -1 감소합니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_AUL_HELP', '이 도시에서 나오는 [ICON_RELIGION] 다수 종교의 압력이 25% 증가합니다. 도시에서 작업하는 초원 타일 3개 또는 평야 타일 3개마다 [ICON_FOOD] 식량 +1과 [ICON_PRODUCTION] 생산력 +1이 추가로 생성됩니다.[NEWLINE][NEWLINE]빈곤으로 인한 [ICON_HAPPINESS_3] 불행이 -1 감소합니다.'),
	--('ko_KR', 'TXT_KEY_BUILDING_GURDWARABN_HELP', '모든 욕구에 대한 [ICON_HAPPINESS_3] 불행 수정치를 -10% 조정합니다. 이 도시에서 나오는 [ICON_RELIGION] 다수 종교의 압력이 10% 증가합니다. 추가 도시 생명력과 [ICON_STRENGTH] 전투력을 부여합니다.[NEWLINE][NEWLINE][ICON_RELIGION] 종교적 불안으로 인한 [ICON_HAPPINESS_3] 불행이 -1 감소합니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_XUEMIAO_HELP', '이 도시에서 나오는 [ICON_RELIGION] 다수 종교의 압력이 25% 증가합니다. [ICON_GREAT_PEOPLE] 위인 생성률이 +25% 증가합니다.[NEWLINE][NEWLINE]이 도시의 전문가 1명은 더 이상 [ICON_URBANIZATION] 도시화로 인한 [ICON_HAPPINESS_3] 불행을 생성하지 않습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_JINJA_HELP', '이 도시에서 나오는 [ICON_RELIGION] 다수 종교의 압력이 25% 증가합니다. 이 도시에서 작업하는 해양 자원으로부터 [ICON_PEACE] 신앙 +2, [ICON_CULTURE] 문화 +2를 획득합니다.[NEWLINE][NEWLINE][ICON_RESEARCH] 문맹으로 인한 [ICON_HAPPINESS_3] 불행이 -1 감소합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_ATASH', '신앙을 사용해 [ICON_PEACE] 아타쉬를 구매합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_AUL', '신앙을 사용해 [ICON_PEACE] 아울을구매합니다.'),
	--('ko_KR', 'TXT_KEY_BELIEF_GURDWARABN', '신앙을 사용해 [ICON_PEACE] 구루드와라를 구매합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_XUEMIAO', '신앙을 사용해 [ICON_PEACE] 공자묘를 구매합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_JINJA', '신앙을 사용해 [ICON_PEACE] 신사를 구매합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_ATASH_SHORT', '아타쉬'),
	('ko_KR', 'TXT_KEY_BELIEF_AUL_SHORT', '아울'),
	--('ko_KR', 'TXT_KEY_BELIEF_GURDWARABN_SHORT', '구루드와라'),
	('ko_KR', 'TXT_KEY_BELIEF_XUEMIAO_SHORT', '공자묘'),
	('ko_KR', 'TXT_KEY_BELIEF_JINJA_SHORT', '신사'),
	('ko_KR', 'TXT_KEY_BUILDING_ATASH_TOOLTIP', '[ICON_PEACE] 신앙 +2[NEWLINE][ICON_CULTURE] 문화 +2[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_ATASH_HELP}'),
	('ko_KR', 'TXT_KEY_BUILDING_AUL_TOOLTIP', '[ICON_PEACE] 신앙 +3[NEWLINE][ICON_GREAT_GENERAL] 위대한 장군 점수 +1[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_AUL_HELP}'),
	--('ko_KR', 'TXT_KEY_BUILDING_GURDWARABN_TOOLTIP', '[ICON_PEACE] 신앙 +3[NEWLINE][ICON_GREAT_WORK] 위대한 음악 슬롯 +1[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_GURDWARABN_HELP}'),
	('ko_KR', 'TXT_KEY_BUILDING_XUEMIAO_TOOLTIP', '[ICON_PEACE] 신앙 +2[NEWLINE][ICON_RESEARCH] 과학 +3[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_XUEMIAO_HELP}'),
	('ko_KR', 'TXT_KEY_BUILDING_JINJA_TOOLTIP', '[ICON_PEACE] 신앙 +2[NEWLINE][ICON_GREAT_ADMIRAL] 위대한 제독 점수 +1[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_JINJA_HELP}'),
	('ko_KR', 'TXT_KEY_BELIEF_FOT', '[ICON_PEACE] 신앙으로 송수로, 식료품점, 병원, 의학 연구소를 건설할 수 있습니다. 이 건물들은 [ICON_FOOD] 식량을 +3 생산합니다. 국왕 경축일에 도시의 [ICON_FOOD] 식량 생산량이 10% 증가합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_FOT_SHORT', '생각할 거리'),
	('ko_KR', 'TXT_KEY_BELIEF_EV', '[ICON_PEACE] 신앙으로 대상 숙소, 세관, 은행, 증권 거래소를 건설할 수 있습니다. 이 건물들은 [ICON_GOLDEN_AGE] 황금기 점수를 +1 생성합니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_EV_SHORT', '계몽된 가치'),
	('ko_KR', 'TXT_KEY_BELIEF_MARITIME_SPIRIT', '[ICON_PEACE] 신앙으로 등대, 항만, 항구를 건설할 수 있습니다. 이 건물들은 [ICON_GREAT_ADMIRAL] 위대한 제독 점수를 +1 생성합니다. 도시에서 바다 타일을 작업하는 [ICON_CITIZEN] 시민 2명당 [ICON_PRODUCTION] 생산력 +1, [ICON_PEACE] 신앙 +1을 얻습니다.'),
	('ko_KR', 'TXT_KEY_BELIEF_MARITIME_SPIRIT_SHORT', '바다의 영혼');

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_ATASH', 'BUILDING_ATASH', 'TXT_KEY_BUILDING_ATASH' UNION ALL
SELECT 'BUILDINGCLASS_AUL', 'BUILDING_AUL', 'TXT_KEY_BUILDING_AUL' UNION ALL
--SELECT 'BUILDINGCLASS_GURDWARABN', 'BUILDING_GURDWARABN', 'TXT_KEY_BUILDING_GURDWARABN' WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
SELECT 'BUILDINGCLASS_XUEMIAO', 'BUILDING_XUEMIAO', 'TXT_KEY_BUILDING_XUEMIAO' UNION ALL
SELECT 'BUILDINGCLASS_JINJA', 'BUILDING_JINJA', 'TXT_KEY_BUILDING_JINJA';

INSERT INTO Beliefs (Type, Description, ShortDescription, Follower, Tooltip)
SELECT 'BELIEF_ATASH', 'TXT_KEY_BELIEF_ATASH', 'TXT_KEY_BELIEF_ATASH_SHORT', 1, 'TXT_KEY_BUILDING_ATASH_TOOLTIP' UNION ALL
SELECT 'BELIEF_AUL', 'TXT_KEY_BELIEF_AUL', 'TXT_KEY_BELIEF_AUL_SHORT', 1, 'TXT_KEY_BUILDING_AUL_TOOLTIP' UNION ALL
--SELECT 'BELIEF_GURDWARABN', 'TXT_KEY_BELIEF_GURDWARABN', 'TXT_KEY_BELIEF_GURDWARABN_SHORT', 1, 'TXT_KEY_BUILDING_GURDWARABN_TOOLTIP' WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
SELECT 'BELIEF_XUEMIAO', 'TXT_KEY_BELIEF_XUEMIAO', 'TXT_KEY_BELIEF_XUEMIAO_SHORT', 1, 'TXT_KEY_BUILDING_XUEMIAO_TOOLTIP' UNION ALL
SELECT 'BELIEF_JINJA', 'TXT_KEY_BELIEF_JINJA', 'TXT_KEY_BELIEF_JINJA_SHORT', 1, 'TXT_KEY_BUILDING_JINJA_TOOLTIP';

INSERT INTO Buildings (Type, BuildingClass, Description, Civilopedia, Strategy, Help, ConquestProb, ReligiousPressureModifier, Cost, UnlockedByBelief, FaithCost, ArtDefineTag, MinAreaSize, IconAtlas, PortraitIndex)
SELECT 'BUILDING_ATASH', 'BUILDINGCLASS_ATASH', 'TXT_KEY_BUILDING_ATASH', 'TXT_KEY_BUILDING_ATASH_TEXT', 'TXT_KEY_BUILDING_ATASH_STRATEGY', 'TXT_KEY_BUILDING_ATASH_HELP', 100, 25, -1, 1, 200, 'TEMPLE', -1, 'TECHPRIEST_ATLAS', 3 UNION ALL
SELECT 'BUILDING_AUL', 'BUILDINGCLASS_AUL', 'TXT_KEY_BUILDING_AUL', 'TXT_KEY_BUILDING_AUL_TEXT', 'TXT_KEY_BUILDING_AUL_STRATEGY', 'TXT_KEY_BUILDING_AUL_HELP', 100, 25, -1, 1, 200, 'TEMPLE', -1, 'TECHPRIEST_ATLAS', 4 UNION ALL
--SELECT 'BUILDING_GURDWARABN', 'BUILDINGCLASS_GURDWARABN', 'TXT_KEY_BUILDING_GURDWARABN', 'TXT_KEY_BUILDING_GURDWARABN_TEXT', 'TXT_KEY_BUILDING_GURDWARABN_STRATEGY', 'TXT_KEY_BUILDING_GURDWARABN_HELP', 100, 10, -1, 1, 200, 'TEMPLE', -1, 'TECHPRIEST_ATLAS', 5 WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
SELECT 'BUILDING_XUEMIAO', 'BUILDINGCLASS_XUEMIAO', 'TXT_KEY_BUILDING_XUEMIAO', 'TXT_KEY_BUILDING_XUEMIAO_TEXT', 'TXT_KEY_BUILDING_XUEMIAO_STRATEGY', 'TXT_KEY_BUILDING_XUEMIAO_HELP', 100, 25, -1, 1, 200, 'TEMPLE', -1, 'TECHPRIEST_ATLAS', 7 UNION ALL
SELECT 'BUILDING_JINJA', 'BUILDINGCLASS_JINJA', 'TXT_KEY_BUILDING_JINJA', 'TXT_KEY_BUILDING_JINJA_TEXT', 'TXT_KEY_BUILDING_JINJA_STRATEGY', 'TXT_KEY_BUILDING_JINJA_HELP', 100, 25, -1, 1, 200, 'TEMPLE', -1, 'TECHPRIEST_ATLAS', 6;

--UPDATE Buildings
--SET EmpireSizeModifierReduction = -10
--WHERE Type = 'BUILDING_AUL';

--UPDATE Buildings
--SET GoldMedianModifier  = -10, BasicNeedsMedianModifier = -10, ScienceMedianModifier = -10, CultureMedianModifier = -10, ReligiousUnrestModifier = -10, Defense = 200, ExtraCityHitPoints = 25, ReligiousUnrestFlatReduction = 1
--WHERE Type = 'BUILDING_GURDWARABN' AND NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA');

/* -- VP 3.0 removed this table
INSERT INTO Building_UnhappinessNeedsFlatReduction (BuildingType, YieldType, Yield)
SELECT 'BUILDING_JINJA', 'YIELD_PRODUCTION', 1 UNION ALL
SELECT 'BUILDING_XUEMIAO', 'YIELD_SCIENCE', 1 UNION ALL
SELECT 'BUILDING_AUL', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_ATASH', 'YIELD_CULTURE', 1;
*/
UPDATE Buildings
SET IlliteracyFlatReduction = 1
WHERE Type = 'BUILDING_JINJA';

UPDATE Buildings
SET NoUnhappfromXSpecialists = 1, GreatPeopleRateModifier = 25
WHERE Type = 'BUILDING_XUEMIAO';

UPDATE Buildings
SET PovertyFlatReduction = 1
WHERE Type = 'BUILDING_AUL';

UPDATE Buildings
SET BoredomFlatReduction = 1
WHERE Type = 'BUILDING_ATASH';

INSERT INTO Building_YieldPerXTerrainTimes100 (BuildingType, TerrainType, YieldType, Yield)
SELECT 'BUILDING_AUL', 'TERRAIN_GRASS', 'YIELD_FOOD', 34 UNION ALL
SELECT 'BUILDING_AUL', 'TERRAIN_GRASS', 'YIELD_PRODUCTION', 34 UNION ALL
SELECT 'BUILDING_AUL', 'TERRAIN_PLAINS', 'YIELD_FOOD', 34 UNION ALL
SELECT 'BUILDING_AUL', 'TERRAIN_PLAINS', 'YIELD_PRODUCTION', 34;

INSERT INTO Building_YieldFromYieldPercent (BuildingType, YieldOut, YieldIn, Value)
SELECT 'BUILDING_ATASH', 'YIELD_SCIENCE', 'YIELD_FAITH', 10; 

INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ATASH', 'YIELD_FAITH', 2;

INSERT INTO Building_YieldPerFriend (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ATASH', 'YIELD_FAITH', 1;

INSERT INTO Building_SeaResourceYieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_JINJA', 'YIELD_FAITH', 2 UNION ALL
SELECT 'BUILDING_JINJA', 'YIELD_CULTURE', 2;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ATASH', 'YIELD_FAITH', 2 UNION ALL
SELECT 'BUILDING_ATASH', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'BUILDING_AUL', 'YIELD_FAITH', 3 UNION ALL
SELECT 'BUILDING_AUL', 'YIELD_GREAT_GENERAL_POINTS', 1 UNION ALL
--SELECT 'BUILDING_GURDWARABN', 'YIELD_FAITH', 3 WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
SELECT 'BUILDING_XUEMIAO', 'YIELD_FAITH', 2 UNION ALL
SELECT 'BUILDING_XUEMIAO', 'YIELD_SCIENCE', 3 UNION ALL
SELECT 'BUILDING_JINJA', 'YIELD_FAITH', 2 UNION ALL
SELECT 'BUILDING_JINJA', 'YIELD_GREAT_ADMIRAL_POINTS', 1;

INSERT INTO Belief_BuildingClassFaithPurchase (BeliefType, BuildingClassType)
SELECT 'BELIEF_ATASH', 'BUILDINGCLASS_ATASH' UNION ALL
SELECT 'BELIEF_AUL', 'BUILDINGCLASS_AUL' UNION ALL
--SELECT 'BELIEF_GURDWARABN', 'BUILDINGCLASS_GURDWARABN' WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
SELECT 'BELIEF_XUEMIAO', 'BUILDINGCLASS_XUEMIAO' UNION ALL
SELECT 'BELIEF_JINJA', 'BUILDINGCLASS_JINJA';

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_ATASH', 'FLAVOR_RELIGION', 20 UNION ALL
SELECT 'BUILDING_ATASH', 'FLAVOR_CULTURE', 5 UNION ALL
SELECT 'BUILDING_ATASH', 'FLAVOR_SCIENCE', 2 UNION ALL
SELECT 'BUILDING_ATASH', 'FLAVOR_DIPLOMACY', 1 UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_RELIGION', 20 UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_OFFENSE', 5 UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_GREAT_PEOPLE', 5 UNION ALL
--SELECT 'BUILDING_GURDWARABN', 'FLAVOR_RELIGION', 5 WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
--SELECT 'BUILDING_GURDWARABN', 'FLAVOR_HAPPINESS', 4 WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
--SELECT 'BUILDING_GURDWARABN', 'FLAVOR_CITY_DEFENSE', 4 WHERE NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_GURDWARA') UNION ALL
SELECT 'BUILDING_XUEMIAO', 'FLAVOR_RELIGION', 20 UNION ALL
SELECT 'BUILDING_XUEMIAO', 'FLAVOR_GREAT_PEOPLE', 15 UNION ALL
SELECT 'BUILDING_XUEMIAO', 'FLAVOR_SCIENCE', 5 UNION ALL
SELECT 'BUILDING_JINJA', 'FLAVOR_RELIGION', 20 UNION ALL
SELECT 'BUILDING_JINJA', 'FLAVOR_NAVAL_TILE_IMPROVEMENT', 15;

INSERT INTO Beliefs (Type, Description, ShortDescription, Reformation, Tooltip)
SELECT 'BELIEF_FOT', 'TXT_KEY_BELIEF_FOT', 'TXT_KEY_BELIEF_FOT_SHORT', 1, 'TXT_KEY_BELIEF_FOT' UNION ALL
SELECT 'BELIEF_EV', 'TXT_KEY_BELIEF_EV', 'TXT_KEY_BELIEF_EV_SHORT', 1, 'TXT_KEY_BELIEF_EV' UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'TXT_KEY_BELIEF_MARITIME_SPIRIT', 'TXT_KEY_BELIEF_MARITIME_SPIRIT_SHORT', 1, 'TXT_KEY_BELIEF_MARITIME_SPIRIT';

INSERT INTO Belief_YieldFromWLTKD (BeliefType, YieldType, Yield)
SELECT 'BELIEF_FOT', 'YIELD_FOOD', 10;

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 300
WHERE BuildingClass = 'BUILDINGCLASS_AQUEDUCT';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 400
WHERE BuildingClass = 'BUILDINGCLASS_GROCER';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 500
WHERE BuildingClass = 'BUILDINGCLASS_HOSPITAL';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 800
WHERE BuildingClass = 'BUILDINGCLASS_MEDICAL_LAB';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 300
WHERE BuildingClass = 'BUILDINGCLASS_CARAVANSARY';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 400
WHERE BuildingClass = 'BUILDINGCLASS_MINT';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 500
WHERE BuildingClass = 'BUILDINGCLASS_BANK';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 800
WHERE BuildingClass = 'BUILDINGCLASS_STOCK_EXCHANGE';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 300
WHERE BuildingClass = 'BUILDINGCLASS_LIGHTHOUSE';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 400
WHERE BuildingClass = 'BUILDINGCLASS_HARBOR';

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 600
WHERE BuildingClass = 'BUILDINGCLASS_SEAPORT';

INSERT INTO Belief_BuildingClassYieldChanges (BeliefType, BuildingClassType, YieldType, YieldChange)
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_AQUEDUCT', 'YIELD_FOOD', 3 UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_GROCER', 'YIELD_FOOD', 3 UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_HOSPITAL', 'YIELD_FOOD', 3 UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_MEDICAL_LAB', 'YIELD_FOOD', 3 UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_CARAVANSARY', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_MINT', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_BANK', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_STOCK_EXCHANGE', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'BUILDINGCLASS_LIGHTHOUSE', 'YIELD_GREAT_ADMIRAL_POINTS', 1 UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'BUILDINGCLASS_HARBOR', 'YIELD_GREAT_ADMIRAL_POINTS', 1 UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'BUILDINGCLASS_SEAPORT', 'YIELD_GREAT_ADMIRAL_POINTS', 1;

INSERT INTO Belief_CityYieldPerXTerrainTimes100 (BeliefType, TerrainType, YieldType, Yield)
SELECT 'BELIEF_MARITIME_SPIRIT', 'TERRAIN_OCEAN', 'YIELD_PRODUCTION', 50 UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'TERRAIN_OCEAN', 'YIELD_FAITH', 50 UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'TERRAIN_COAST', 'YIELD_PRODUCTION', 50 UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'TERRAIN_COAST', 'YIELD_FAITH', 50;

INSERT INTO Belief_BuildingClassFaithPurchase (BeliefType, BuildingClassType)
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_AQUEDUCT' UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_GROCER' UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_HOSPITAL' UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_MEDICAL_LAB' UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_CARAVANSARY' UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_MINT' UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_BANK' UNION ALL
SELECT 'BELIEF_EV', 'BUILDINGCLASS_STOCK_EXCHANGE' UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'BUILDINGCLASS_LIGHTHOUSE' UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'BUILDINGCLASS_HARBOR' UNION ALL
SELECT 'BELIEF_MARITIME_SPIRIT', 'BUILDINGCLASS_SEAPORT';