UPDATE Buildings
SET Cost = 65, HurryCostModifier = 5
WHERE Type = 'BUILDING_CORRAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings
SET Cost = 200, HurryCostModifier = 5
WHERE Type = 'BUILDING_FOUNDRY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings
SET Cost = 1000, HurryCostModifier = 5
WHERE Type = 'BUILDING_DEEP_MINE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings
SET Cost = 2000, HurryCostModifier = 5
WHERE Type = 'BUILDING_BIOFUEL_REFINERY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings
SET Cost = 2750, HurryCostModifier = 5
WHERE Type = 'BUILDING_ENRICHMENT_FACILITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);
