-- levatine gets changed after this in Reassignments.sql
--==========================================================================================================================
--========================================================================================================================== 

CREATE TABLE IF NOT EXISTS CD_Compatibility (
	ID  	integer 	primary key autoincrement,
	CivilizationType text default null,
 	CultureType text default null,
	UnitDialogueTag text default null
);

INSERT INTO CD_Compatibility
	(CivilizationType, CultureType, UnitDialogueTag)
VALUES
 	('CIVILIZATION_LS_VIETNAM','CULTURE_JFD_INDOCHINA',	null),
 	('CIVILIZATION_CLINUIT',	'CULTURE_JFD_POLAR',	null),
	('CIVILIZATION_JFD_PHILIPPINES', 'CULTURE_JFD_EAST_INDIES', 	null),
	('CIVILIZATION_CL_TLINGIT', 'CULTURE_JFD_PACIFIC',		null),
	('CIVILIZATION_LEUGI_ISRAEL', 'CULTURE_JFD_LEVANTINE', 	null),  -- new levantine
	('CIVILIZATION_AKKADIAN_MOD', 'CULTURE_JFD_MESOPOTAMIC',	null),
	('CIVILIZATION_VISIGOTHS_MOD', 'CULTURE_JFD_NORTHERN', 	null),
	('CIVILIZATION_TOMATEKH_BENIN', 'CULTURE_JFD_CENTRAL_AFRICAN',	null),
	('CIVILIZATION_TIMURIDS_MOD', 'CULTURE_JFD_STEPPE', null),
 	('CIVILIZATION_PHOENICIA',	'CULTURE_JFD_LEVANTINE',null), -- new levantine
	('CIVILIZATION_VP_CHOLA', 'CULTURE_JFD_BHARATA',	null),
	('CIVILIZATION_MC_LITE_NUBIA', 'CULTURE_JFD_MESOPOTAMIC',null),
	('CIVILIZATION_IA_KUSHAN', 'CULTURE_JFD_STEPPE', null),
	('CIVILIZATION_HININ_HISATSINOM', 'CULTURE_JFD_GREAT_PLAINS',	null),
	('CIVILIZATION_COLONIALCANADA',	'CULTURE_JFD_COLONIAL',	'AS2D_SOUND_JFD_AMERICAN'),
	('CIVILIZATION_HININ_AINU', 'CULTURE_JFD_POLAR', null),
	('CIVILIZATION_HININ_IMAZIGHEN', 'CULTURE_JFD_WEST_AFRICAN', null);  -- saharan

INSERT OR REPLACE INTO Civilization_JFD_CultureTypes
 	(CivilizationType,	CultureType,	SubCultureType, SplashScreenTag, UnitDialogueTag)
SELECT	
 	CivilizationType,	CultureType, null,	null,	UnitDialogueTag
FROM CD_Compatibility WHERE EXISTS (SELECT 1 FROM Civilizations WHERE Type = CivilizationType);

CREATE TRIGGER CD_CustomCiv_Compatibility
AFTER INSERT ON Civilizations
BEGIN
	INSERT OR REPLACE INTO Civilization_JFD_CultureTypes
 		(CivilizationType,	CultureType,	SubCultureType, SplashScreenTag, UnitDialogueTag)
	SELECT	
	 	CivilizationType,	CultureType, null,	null,	UnitDialogueTag
	FROM CD_Compatibility WHERE NEW.Type = CivilizationType;
END;
	
--==========================================================================================================================
-- old table. some names out of date. kept for reference.
--==========================================================================================================================
/*
	('CIVILIZATION_AUSTRALIA_LS_MOD', 	'CULTURE_JFD_ABORIGINAL',null,	null,	null),
 	('CIVILIZATION_KULINNATION','CULTURE_JFD_ABORIGINAL',null,	null,	null),
 	('CIVILIZATION_TUPI','CULTURE_JFD_AMAZONIAN',null,	null,	null),
 	('CIVILIZATION_CARIB','CULTURE_JFD_AMAZONIAN',null,	null,	null),
 	('CIVILIZATION_KUHIKUGU',	'CULTURE_JFD_AMAZONIAN',null,	null,	null),
 	('CIVILIZATION_AYMARA','CULTURE_JFD_ANDEAN',	null,	null,	null),
 	('CIVILIZATION_CHIMOR','CULTURE_JFD_ANDEAN',	null,	null,	null),
 	('CIVILIZATION_CHIMU_MOD',	'CULTURE_JFD_ANDEAN',	null,	null,	null),
 	('CIVILIZATION_MAPUCHE',	'CULTURE_CD_PATAGONIAN',	null,	null,	null),  --patagonian
 	('CIVILIZATION_MUISCA','CULTURE_JFD_ANDEAN',	null,	null,	null),
 	('CIVILIZATION_TIWANAKU',	'CULTURE_JFD_ANDEAN',	null,	null,	null),
 	('CIVILIZATION_MAASAI','CULTURE_JFD_BANTU',	null,	null,	null),
 	('CIVILIZATION_MONOMOTAPA',	'CULTURE_JFD_BANTU',	null,	null,	null),
 	('CIVILIZATION_ZIMBABWE_LS_MOD', 	'CULTURE_JFD_BANTU',	null,	null,	null),
 	('CIVILIZATION_HARAPPAN',	'CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_MARATHA',	'CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_MAURYA_LS_MOD','CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_MAURYA','CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_SIKH','CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_SRI_LANKA',	'CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_VIJAYANAGAR','CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_MC_MUGHAL',	'CULTURE_JFD_BHARATA',	null,	null,	null),
 	('CIVILIZATION_BOHEMIA',	'CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_CROATIA',	'CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_FRANKS_LS_MOD','CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_HUNGARY_LS_MOD','CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_LITHUANIA_LS_MOD', 	'CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_POLAND_LS_MOD','CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_SWITZERLAND','CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_SWITZERLAND_LS_MOD', 	'CULTURE_JFD_CENTRAL',	null,	null,	null),
 	('CIVILIZATION_ASHANTI_LS_MOD','CULTURE_JFD_CENTRAL_AFRICAN', 	null,	null,	null),
 	('CIVILIZATION_KANEM','CULTURE_JFD_CENTRAL_AFRICAN', 	null,	null,	null),
 	('CIVILIZATION_NDONGO_LS_MOD','CULTURE_JFD_CENTRAL_AFRICAN', 	null,	null,	null),
 	('CIVILIZATION_MINOAN_LS_MOD','CULTURE_JFD_CLASSICAL',null,	null,	null),
 	('CIVILIZATION_MINOAN','CULTURE_JFD_CLASSICAL',null,	null,	null),
 	('CIVILIZATION_SELEUCID',	'CULTURE_JFD_CLASSICAL',null,	null,	null),
 	('CIVILIZATION_SPARTA_LS_MOD','CULTURE_JFD_CLASSICAL',null,	null,	null),
 	('CIVILIZATION_TCM_BACTRIA','CULTURE_JFD_CLASSICAL',null,	null,	null),
 	('CIVILIZATION_TCM_PTOLEMAIC','CULTURE_JFD_CLASSICAL',null,	null,	null),
 	('CIVILIZATION_BOER','CULTURE_JFD_COLONIAL',	null,	null,	null),
 	('CIVILIZATION_CARIBBEAN_LS_MOD', 	'CULTURE_JFD_COLONIAL',	null,	null,	null),
 	('CIVILIZATION_COLONIALCANADA','CULTURE_JFD_COLONIAL',	null,	null,	null),
 	('CIVILIZATION_CSA','CULTURE_JFD_COLONIAL',	null,	null,	null),
 	('CIVILIZATION_PIRATE','CULTURE_JFD_COLONIAL',	null,	null,	null),
 	('CIVILIZATION_RHODESIA',	'CULTURE_JFD_COLONIAL',	null,	null,	null),
 	('CIVILIZATION_ARGENTINA',	'CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_BOLIVIA',	'CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_CHILE','CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_GRANCOLOMBIA','CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_LEUGI_CUBA',	'CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_MEXICO','CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_MEXICOREPUBLIC','CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_PARAGUAY',	'CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_PERU','CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_VENEZUELA',	'CULTURE_JFD_COLONIAL',	'SUBCULTURE_JFD_COLONIAL_LATIN',null,	null),
 	('CIVILIZATION_ALBANIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_ARMENIA',	'CULTURE_JFD_EASTERN',	null,	'JFD_EasternByzantine', 	'JFD_EasternByzantine'),
 	('CIVILIZATION_AZERBAIJAN',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_BOSNIA','CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_BULGARIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_BULGARIA_LS_MOD', 	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_CROATIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_GE_SLAVS',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_HETMANATE_LS_MOD', 	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_KDMBOSNIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_LATVIA','CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_MACEDONIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_MOLDAVIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_MONTENEGRO',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_ROMANIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_ROMANIA_LS_MOD','CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_WALLACHIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_YUGOSLAVIA',	'CULTURE_JFD_EASTERN',	null,	null,	null),
 	('CIVILIZATION_PAPUA','CULTURE_JFD_EAST_INDIES',null,	null,	null),
 	('CIVILIZATION_QIN_LS_MOD',	'CULTURE_JFD_FAR_EASTERN',null,	null,	null),
 	('CIVILIZATION_VIETNAM',	'CULTURE_JFD_FAR_EASTERN',null,	null,	null),
 	('CIVILIZATION_RYUKYU','CULTURE_JFD_FAR_EASTERN',null,	null,	null),
 	('CIVILIZATION_ALTJAPAN',	'CULTURE_JFD_FAR_EASTERN','SUBCULTURE_JFD_FAR_EASTERN_JAPANESE', 	null,	null),
 	('CIVILIZATION_BLACKFOOTFIRSTNATION',	'CULTURE_JFD_GREAT_PLAINS',null,	null,	null),
 	('CIVILIZATION_NIITSITAPI_LS_MOD', 	'CULTURE_JFD_GREAT_PLAINS',null,	null,	null),
 	('CIVILIZATION_SIOUX','CULTURE_JFD_GREAT_PLAINS',null,	null,	null),
 	('CIVILIZATION_SIOUX_LS_MOD','CULTURE_JFD_GREAT_PLAINS',null,	null,	null),
 	('CIVILIZATION_NEPAL','CULTURE_JFD_HIMALAYAN',null,	null,	null),
 	('CIVILIZATION_NEPAL_LS_MOD','CULTURE_JFD_HIMALAYAN',null,	null,	null),
 	('CIVILIZATION_TIBET_LS_MOD','CULTURE_JFD_HIMALAYAN',null,	null,	null),
 	('CIVILIZATION_BANE_TIBET',	'CULTURE_JFD_HIMALAYAN',null,	null,	null),
 	('CIVILIZATION_BURMA','CULTURE_JFD_INDOCHINA',null,	null,	null),
 	('CIVILIZATION_CAMBODIA',	'CULTURE_JFD_INDOCHINA',null,	null,	null),
 	('CIVILIZATION_KHMER','CULTURE_JFD_INDOCHINA',null,	null,	null),
 	('CIVILIZATION_KHMER_LS_MOD','CULTURE_JFD_INDOCHINA',null,	null,	null),
 	('CIVLIZATION_LAOS','CULTURE_JFD_INDOCHINA',null,	null,	null),
 	('CIVILIZATION_ISRAEL','CULTURE_JFD_LEVANTINE',null,	null,	null), --levantine
 	('CIVILIZATION_ISRAEL_LS_MOD','CULTURE_JFD_LEVANTINE',null,	null,	null), --levantine
 	('CIVILIZATION_LEUGI_PHILISTINE', 	'CULTURE_JFD_LEVANTINE',null,	null,	null), --levantine
 	('CIVILIZATION_NABATAEA',	'CULTURE_JFD_LEVANTINE',null,	null,	null), --levantine
 	('CIVILIZATION_PHOENICIA_LS_MOD', 	'CULTURE_JFD_LEVANTINE',null,	null,	null), --levantine
 	('CIVILIZATION_SABA','CULTURE_JFD_LEVANTINE',null,	null,	null),
 	('CIVILIZATION_OLMEC_LS_MOD','CULTURE_JFD_MESOAMERICAN',null,	null,	null),
 	('CIVILIZATION_ZAPOTEC',	'CULTURE_JFD_MESOAMERICAN',null,	null,	null),
 	('CIVILIZATION_AKKADIA',	'CULTURE_JFD_MESOPOTAMIC',null,	null,	null),
 	('CIVILIZATION_HITTITE_LS_MOD','CULTURE_JFD_MESOPOTAMIC',null,	null,	null),
 	('CIVILIZATION_MITANNI',	'CULTURE_JFD_MESOPOTAMIC',null,	null,	null),
 	('CIVILIZATION_NUBIA','CULTURE_JFD_MESOPOTAMIC',null,	null,	null),
 	('CIVILIZATION_NUMIDIA_LS_MOD','CULTURE_JFD_MESOPOTAMIC',null,	null,	null),
 	('CIVILIZATION_SUMERIA_LS_MOD','CULTURE_JFD_MESOPOTAMIC',null,	null,	null),
 	('CIVILIZATION_PARTHIA',	'CULTURE_JFD_MESOPOTAMIC','SUBCULTURE_JFD_MESOPOTAMIC_PERSIAN', 	null,	null),
 	('CIVILIZATION_SASANIAN',	'CULTURE_JFD_MESOPOTAMIC','SUBCULTURE_JFD_MESOPOTAMIC_PERSIAN', 	null,	null),
 	('CIVILIZATION_ALGERIA',	'CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_BERBER','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_CORDOBA',	'CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_DURANNI_LS_MOD','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_HAFEZ_SYRIA','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_IRAN','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_KUWAIT','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_LIBYA','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_SADAT_EGYPT','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_UAE','CULTURE_JFD_MID_EASTERN',null,	null,	null),
 	('CIVILIZATION_DJSH_AFSHARID','CULTURE_JFD_MID_EASTERN','SUBCULTURE_JFD_MID_EASTERN_OTTOMAN', 	null,	null),
 	('CIVILIZATION_SAFAVIDS',	'CULTURE_JFD_MID_EASTERN','SUBCULTURE_JFD_MID_EASTERN_OTTOMAN', 	null,	null),
 	('CIVILIZATION_TCM_WW1_OTTOMAN', 	'CULTURE_JFD_MID_EASTERN','SUBCULTURE_JFD_MID_EASTERN_OTTOMAN', 	null,	null),
 	('CIVILIZATION_UC_TURKEY',	'CULTURE_JFD_MID_EASTERN','SUBCULTURE_JFD_MID_EASTERN_OTTOMAN', 	null,	null),
 	('CIVILIZATION_FINLAND',	'CULTURE_JFD_NORTHERN',	null,	null,	null),
 	('CIVILIZATION_KDMLITHUANIA','CULTURE_JFD_NORTHERN',	null,	null,	null),
 	('CIVILIZATION_TCM_SUEBI',	'CULTURE_JFD_NORTHERN',	null,	null,	null),
 	('CIVILIZATION_VIKING_LS_MOD','CULTURE_JFD_NORTHERN',	null,	null,	null),
 	('CIVILIZATION_CALC_MANX',	'CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_CORNWALL',	'CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_DALRIATA',	'CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_GALLIA_LS_MOD','CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_GE_PICTS',	'CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_ICENI','CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_IRELAND',	'CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_NORTHUMBRIA','CULTURE_JFD_NORTHERN',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),
 	('CIVILIZATION_PICTS','CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_WALES','CULTURE_CD_CELTIC',	'SUBCULTURE_JFD_NORTHERN_CELTIC',null,	null),  --celtic
 	('CIVILIZATION_TAHITI_LS_MOD','CULTURE_JFD_OCEANIC',	null,	null,	null),
 	('CIVILIZATION_MC_CHINOOK',	'CULTURE_JFD_PACIFIC',	null,	null,	null),
 	('CIVILIZATION_HAIDA_LS_MOD','CULTURE_JFD_PACIFIC',	null,	null,	null),
 	('CIVILIZATION_SIBIR','CULTURE_JFD_POLAR',	null,	null,	null),
 	('CIVILIZATION_SAMI','CULTURE_JFD_POLAR',	null,	null,	null),
 	('CIVILIZATION_INUIT','CULTURE_JFD_POLAR',	null,	null,	null),
 	('CIVILIZATION_YUPIK','CULTURE_JFD_POLAR',	null,	null,	null),
 	('CIVILIZATION_BANE_RCC',	'CULTURE_JFD_SOUTHERN',	null,	null,	null),
 	('CIVILIZATION_GENOA_LS_MOD','CULTURE_JFD_SOUTHERN',	null,	null,	null),
 	('CIVILIZATION_JERUSALEM_LS_MOD', 	'CULTURE_JFD_SOUTHERN',	null,	null,	null),
 	('CIVILIZATION_TCM_SICILY',	'CULTURE_JFD_SOUTHERN',	null,	null,	null),
 	('CIVILIZATION_PAPAL_STATES_LS_MOD',	'CULTURE_JFD_SOUTHERN',	'SUBCULTURE_JFD_SOUTHERN_PAPAL',null,	null),
 	('CIVILIZATION_KAZAKH','CULTURE_JFD_STEPPE',	'SUBCULTURE_JFD_STEPPE_TURKIC',	null,	null),
 	('CIVILIZATION_KHAZARIA',	'CULTURE_JFD_STEPPE',	'SUBCULTURE_JFD_STEPPE_TURKIC',	null,	null),
 	('CIVILIZATION_SCYTHIA_LS_MOD','CULTURE_JFD_STEPPE',	null,	null,	null),
 	('CIVILIZATION_TCM_ALAN',	'CULTURE_JFD_STEPPE',	null,	null,	null),
 	('CIVILIZATION_TIMURIDES',	'CULTURE_JFD_STEPPE',	null,	null,	null),
 	('CIVILIZATION_TIMURIDS_LS_MOD', 	'CULTURE_JFD_STEPPE',	null,	null,	null),
 	('CIVILIZATION_UYGHUR','CULTURE_JFD_STEPPE',	null,	null,	null),
 	('CIVILIZATION_YAKUTIA',	'CULTURE_JFD_STEPPE',	null,	null,	null),
 	--('CIVILIZATION_NORTH_KOREA','CULTURE_JFD_TOTALITARIAN',null,	null,	null),
 	--('CIVILIZATION_USSR','CULTURE_JFD_TOTALITARIAN',null,	null,	null),
 	('CIVILIZATION_MALI_LS_MOD','CULTURE_JFD_WEST_AFRICAN',null,	null,	null),
 	('CIVILIZATION_FLANDERS',	'CULTURE_JFD_WESTERN',	null,	null,	null),
 	('CIVILIZATION_FLANDERS_LS_MOD', 	'CULTURE_JFD_WESTERN',	null,	null,	null),
 	('CIVILIZATION_SCOTLAND_LS_MOD', 	'CULTURE_JFD_WESTERN',	null,	null,	null),
 	('CIVILIZATION_UK',	'CULTURE_JFD_WESTERN',	'SUBCULTURE_JFD_WESTERN_BRITISH',null,	null),
 	('CIVILIZATION_CHEROKEE_LS_MOD', 	'CULTURE_JFD_WOODLANDS',null,	null,	null),
 	('CIVILIZATION_MC_CALUSA',	'CULTURE_JFD_WOODLANDS',null,	null,	null),
 	('CIVILIZATION_CLANISHINAABE','CULTURE_JFD_WOODLANDS',null,	null,	null),
 	('CIVILIZATION_CLWABANAKI',	'CULTURE_JFD_WOODLANDS',null,	null,	null);
*/
--==========================================================================================================================
--==========================================================================================================================