UPDATE Units
SET CanChangePort = 1
WHERE CombatClass = 'UNITCOMBAT_RECON' AND Combat < (SELECT Combat FROM Units WHERE Type='UNIT_PARATROOPER') AND NOT Class='UNITCLASS_PARATROOPER';

UPDATE CustomModOptions	SET Value = 1 WHERE Name = 'GLOBAL_SEPARATE_GREAT_ADMIRAL';