--======================================================================================================================
-- Language_en_US
--======================================================================================================================
INSERT OR REPLACE INTO Language_en_US (Tag, Text) VALUES
-- Keldur Hall
('TXT_KEY_BUILDING_KELDUR_HALL', 'Keldur Hall'),
('TXT_KEY_BUILDING_KELDUR_HALL_HELP', 'Terrain: [COLOR_CYAN]Tundra[ENDCOLOR]; [COLOR_NEGATIVE_TEXT]Plains[ENDCOLOR]. [NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, [ICON_PRODUCTION] Production on nearby Tundra tiles. [NEWLINE]+1 [ICON_FOOD] Food, [ICON_PRODUCTION] Production in City for each Snow tile nearby. [NEWLINE]+2 [ICON_FOOD] Food to Villages in the Empire. [NEWLINE]10% of [ICON_RESEARCH] Science output in all Cities is added as [ICON_FOOD] Food Per Turn.'),
('TXT_KEY_BUILDING_KELDUR_HALL_PEDIA', 'Keldur Hall is a historic turf house located in southern Iceland, renowned for its unique architecture and deep cultural significance. Dating back to the 12th century, it is one of the oldest surviving farmsteads in the country. Built using traditional Icelandic methods, Keldur features turf walls and a wooden frame, designed to withstand harsh weather conditions. The hall was once home to influential chieftains and is believed to be associated with the powerful Oddi clan. Its underground passageways, which were likely used for escape or storage, add to its mystique and historical intrigue. [NEWLINE][NEWLINE]Throughout its long history, Keldur has been a witness to Iceland''s medieval past, including the era of the Sagas. It has undergone careful preservation efforts to maintain its authenticity, allowing visitors to experience a glimpse of early Icelandic rural life. Today, Keldur Hall is managed by the National Museum of Iceland and serves as a cultural heritage site. Tourists and history enthusiasts visit to admire its rustic charm, learn about its past inhabitants, and explore the surrounding landscape that has remained largely unchanged for centuries.'),
('TXT_KEY_BUILDING_KELDUR_HALL_QUOTE', '[NEWLINE]"The heart can get really cold if all you''ve known is winter."[NEWLINE] - Benjamin Alire Saenz[NEWLINE]'),
--======================================================================================================================
-- Nipisat
--======================================================================================================================
('TXT_KEY_BUILDING_NIPISAT', 'Nipisat'),
('TXT_KEY_BUILDING_NIPISAT_HELP', 'Terrain: [COLOR_CYAN]Tundra[ENDCOLOR]; [COLOR_CYAN]Coast[ENDCOLOR]. [NEWLINE][NEWLINE]+1 [ICON_GOLD] Gold on nearby Tundra tiles. [NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold on nearby Snow tiles. [NEWLINE]+1 [ICON_PRODUCTION] Production, [ICON_CULTURE_LOCAL] Border Growth to Fishing Boats in the Empire. [NEWLINE]+6 [ICON_CULTURE] Culture with [COLOR_CYAN]Archaeology[ENDCOLOR].[NEWLINE][NEWLINE]All [ICON_RES_DEER] Deer: +1 [ICON_PRODUCTION] Production, +1 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_NIPISAT_PEDIA', 'Nipisat, located off the west coast of Greenland near Sisimiut, is a significant archaeological area that offers insights into the prehistoric cultures of the Arctic. Nipisat is known for its extensive remains from the Saqqaq culture, which dates back to around 4,000 years ago. This site is one of the most well-preserved and comprehensive Saqqaq culture sites, providing valuable information on the lifestyle, subsistence, and technologies of these early Arctic inhabitants. Excavations at Nipisat have uncovered a variety of artifacts, including stone tools, bones, and remnants of dwellings, which illustrate the adaptation of the Saqqaq people to the harsh Arctic environment. [NEWLINE][NEWLINE]In addition to the Saqqaq culture, Nipisat also holds evidence of later Thule culture occupation, which succeeded the Saqqaq culture around 1,000 years ago. The Thule people were ancestors of the modern Inuit, and their presence at Nipisat indicates a continuity of human habitation and adaptation in the region. The findings at Nipisat contribute to our understanding of the cultural transitions and interactions between different prehistoric Arctic groups. The site''s importance is underscored by its inclusion in the List of UNESCO World Heritage Sites in 2018, highlighting its value in understanding human history and prehistoric life in the Arctic.'),
('TXT_KEY_BUILDING_NIPISAT_QUOTE', '[NEWLINE]"The caribou feeds the wolf, but it is the wolf who keeps the caribou strong."[NEWLINE] - Inuit proverb[NEWLINE]'),
--======================================================================================================================
-- Temple of Heracles Akragatos
--======================================================================================================================
('TXT_KEY_BUILDING_AKRAGATOS', 'Temple of Heracles Akragatos'),
('TXT_KEY_BUILDING_AKRAGATOS_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Settler. [NEWLINE]City''s [ICON_PEACE] Faith is added as [ICON_PRODUCTION] Production when training Settling Units, in every City. [NEWLINE]All Shrines gain +1 [ICON_FOOD] Food, +1 [ICON_CULTURE] Culture, +1 [ICON_GOLDEN_AGE] Golden Age Point. [NEWLINE]+3 [ICON_TOURISM] Tourism with [COLOR_CYAN]Archaeology[ENDCOLOR].'),
('TXT_KEY_BUILDING_AKRAGATOS_PEDIA', 'The Temple of Heracles in Agrigento, located in the Valley of the Temples in Sicily, Italy, is one of the oldest and most revered structures of the ancient Greek colony of Akragas. Constructed in the late 6th century BCE, this Doric temple was dedicated to Heracles, the divine hero of Greek mythology. Despite suffering significant damage over the centuries due to natural disasters and human activity, the temple''s remaining columns still stand as a testament to the grandeur of ancient Greek architecture. The structure originally featured a peristyle with 38 columns, each approximately 10 meters high, and a central cella where the statue of Heracles would have been housed. [NEWLINE][NEWLINE]The Temple of Heracles is notable not only for its historical and architectural significance but also for its connection to local religious practices and myths. According to legend, the temple housed a famous statue of Heracles, which was highly venerated by the inhabitants of Akragas. The site has undergone various restoration efforts, particularly in the 1920s, to preserve its remaining columns and stabilize the ruins. Today, the Temple of Heracles is part of the UNESCO World Heritage-listed Valley of the Temples, attracting visitors from around the world who come to admire its ancient splendor and explore the rich history of one of the most significant archaeological sites in the Mediterranean.'),
('TXT_KEY_BUILDING_AKRAGATOS_QUOTE', '[NEWLINE]"On the other side there was a Hercules, beautifully made of brass; that was said to be the work of Myron, as I believe, and it undoubtedly was so. Also before those gods there were little altars, which might indicate to any one the holiness of the chapel.".[NEWLINE] - Cicero[NEWLINE]'),
--======================================================================================================================
-- Piscina Mirabilis
--======================================================================================================================
('TXT_KEY_BUILDING_PISCINA_MIR', 'Piscina Mirabilis'),
('TXT_KEY_BUILDING_PISCINA_MIR_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]; Building: [COLOR_CYAN]Aqueduct[ENDCOLOR]. [NEWLINE][NEWLINE]Naval Units adjacent to this City always heal 10 HP every turn. [NEWLINE]10% of [ICON_FOOD] Food output in all Cities is added as [ICON_GREAT_ADMIRAL] Great Admiral Points. [NEWLINE]All Aqueducts gain +2 [ICON_PRODUCTION] Production.'),
('TXT_KEY_BUILDING_PISCINA_MIR_PEDIA', 'Piscina Mirabilis, located in Bacoli near Naples, Italy, is a remarkable example of Roman engineering and one of the largest ancient cisterns in the world. Constructed during the Augustan period in the 1st century BCE, this grand subterranean structure served as the main water reservoir for the Roman fleet stationed at the nearby port of Misenum. The cistern could hold an estimated 12,600 cubic meters of water, sourced from the Aqua Augusta aqueduct, which transported water from springs in the Apennines to the densely populated region of Campania. The Piscina Mirabilis features a vast network of vaulted chambers, supported by 48 massive columns arranged in a symmetrical grid, showcasing the advanced hydraulic and architectural skills of the Romans. [NEWLINE][NEWLINE]The impressive scale and construction of Piscina Mirabilis highlight the importance of water management in ancient Rome and the sophisticated infrastructure that supported daily life and military operations. The interior of the cistern, with its high vaulted ceilings and imposing columns, resembles a grand subterranean cathedral, creating an awe-inspiring sight for visitors. Over the centuries, the Piscina Mirabilis has fascinated historians, architects, and tourists alike, serving as a testament to the ingenuity and resourcefulness of Roman engineering. Today, it stands as a protected historical monument, offering a glimpse into the technological prowess and cultural priorities of ancient Rome.'),
('TXT_KEY_BUILDING_PISCINA_MIR_QUOTE', '[NEWLINE]"The church is no more religion than the masonry of the aqueduct is the water that flows through it."[NEWLINE] - Henry Ward Beecher[NEWLINE]'),
--======================================================================================================================
-- Banaue Rice Terraces
--======================================================================================================================
('TXT_KEY_BUILDING_BANAUE', 'Banaue Rice Terraces'),
('TXT_KEY_BUILDING_BANAUE_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR]; Improvement: [COLOR_CYAN]Farm[ENDCOLOR]. [NEWLINE][NEWLINE]Spawns 3 [ICON_RES_RICE] Rice resources on nearby Hills. [NEWLINE]All Granaries gain +2 [ICON_FOOD] Food. [NEWLINE][NEWLINE]All [ICON_RES_RICE] Rice: +1 [ICON_FOOD] Food, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_BANAUE_PEDIA', '5000 feet above the sea, covering approximately 4000 square miles of Ifagao mountainside, sits the Banaue Rice Terraces. The terraces are about 2000 years old, built by the ancient indigenous Ifugao, and is still fed today by an ancient irrigation system using the rainforests above. It is common belief that the ancient terraces were built with minimal equipment and mostly by hand. It is said that putting the steps to travel the terraces end to end, they would encircle half the Equator of our Earth. The Ifugao culture is dominated by the use of rice, introducing the many rice culture feasts to the young and agricultural rites from the cultivation to consumption of rice.[NEWLINE][NEWLINE]Today the terraces are still in use, farming rice and vegetables to the Ifugao. However, more of the Ifugao find farming unappealing to other industries. This has resulted in a slow erosion of the site - the steps having been most affected - and the greater need for care of the site. In 2010 a greater problem emerged - drought - which caused the terraces to dry up entirely by March.'),
('TXT_KEY_BUILDING_BANAUE_QUOTE', '[NEWLINE]"Every grain of rice is a drop of sweat from a farmer''s brow"[NEWLINE] - Chinese proverb[NEWLINE]'),
--======================================================================================================================
-- Saint Catherine's Monastery
--======================================================================================================================
('TXT_KEY_BUILDING_ST_CATHERINE', 'St. Catherine''s Monastery'),
('TXT_KEY_BUILDING_ST_CATHERINE_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR].[NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Monastery in the City in which it is built. [NEWLINE][ICON_GREAT_WORK] Great Works in the City produce +2 [ICON_CULTURE] Culture and [ICON_PEACE] Faith. [NEWLINE]Has 2 slots for [ICON_VP_GREATWRITING] Great Works of Literature. +4 [ICON_FOOD] Food and [ICON_PEACE] Faith if [COLOR_POSITIVE_TEXT]Themed[ENDCOLOR].'),
('TXT_KEY_BUILDING_ST_CATHERINE_PEDIA', 'St. Catherine''s Monastery, located at the foot of Mount Sinai in Egypt''s Sinai Peninsula, is one of the world''s oldest continuously functioning Christian monasteries. It was established in the 6th century by Byzantine Emperor Justinian I and is named after St. Catherine of Alexandria, a Christian martyr whose relics were miraculously transported to the site. The monastery is renowned for its historic and religious significance, housing a rich collection of ancient manuscripts, icons, and art that date back to early Christianity. It is also home to the burning bush, where tradition holds that Moses spoke to God, making it a sacred site for both Christians and Jews. [NEWLINE][NEWLINE]Architecturally, St. Catherine''s Monastery is a fortress-like complex, designed to protect its inhabitants and treasures from invaders. Its walls enclose a basilica, a mosque, a library with an extensive collection of early manuscripts, and living quarters for monks. The monastery''s library is second only to the Vatican in terms of the significance and antiquity of its manuscripts. As a UNESCO World Heritage Site, St. Catherine''s Monastery continues to be a center of pilgrimage, scholarly study, and spiritual devotion, attracting visitors from around the globe who are interested in its rich history and religious importance.'),
('TXT_KEY_BUILDING_ST_CATHERINE_QUOTE', '[NEWLINE]"To keep a faith pure, man had better retire to a monastery."[NEWLINE] - Walter Lippmann[NEWLINE]'),
('TXT_KEY_THEMING_BONUS_ST_CATHERINE', 'Codex Sinaiticus'),
('TXT_KEY_THEMING_BONUS_ST_CATHERINE_HELP', 'To maximize your bonus, make sure all the Great Work Slots are all filled with Literature created by You.'),
--======================================================================================================================
-- Songyue Pagoda 
--======================================================================================================================
('TXT_KEY_UNIT_JAR_HESHANG', 'Héshàng'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA', 'Songyue Pagoda'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Pagoda in the City in which it is built. [NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] {TXT_KEY_UNIT_JAR_HESHANG}, a Civilian Unit that may be expended to construct a Holy Site. [NEWLINE]+2 [ICON_PEACE] Faith from all [ICON_VP_SCIENTIST] Scientist Specialists in your Empire. [NEWLINE]+3 [ICON_RESEARCH] Science from all Holy Sites in your Empire.'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_PEDIA', 'The Songyue Pagoda, located on Mount Song in Henan Province, China, is the earliest known brick brick pagoda in the country, dating back to the Northern Wei Dynasty around 523 AD. This ancient structure stands as a testament to early Buddhist architecture in China, reflecting a blend of Han Chinese and Central Asian influences. The pagoda is notable for its circular plan, a departure from the more common square-shaped pagodas of the time, and its twelve-story structure tapers gracefully, with each successive level marked by a distinctive cornice. The Songyue Pagoda''s intricate brickwork and the use of arches and brackets demonstrate advanced engineering techniques of the period, showcasing the early development of Chinese architecture. [NEWLINE][NEWLINE]Architecturally, the Songyue Pagoda is significant for its elegant and innovative design, which has influenced the construction of subsequent pagodas throughout China. The interior of the pagoda features a central pillar surrounded by a narrow passageway, allowing worshippers to circumambulate while paying homage. This design also provides structural stability, enabling the pagoda to withstand centuries of natural wear and seismic activity. As an enduring symbol of the spread of Buddhism in China, the Songyue Pagoda remains an important cultural and historical monument, attracting scholars, architects, and tourists who seek to understand its historical context and architectural significance. In 2010, the pagoda was inscribed on the UNESCO World Heritage List along with other nearby monuments as part of the "Historic Monuments of Dengfeng in The Centre of Heaven and Earth" site.'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_QUOTE', '[NEWLINE]"The temple is a point of intersection between heaven and earth."[NEWLINE] - David A. Bednar[NEWLINE]'),
--======================================================================================================================
-- Horyu-ji
--======================================================================================================================
('TXT_KEY_BUILDING_HORYUJI', 'Horyu-ji'),
('TXT_KEY_BUILDING_HORYUJI_HELP', 'Plot: [COLOR_CYAN]Flat[ENDCOLOR]; Feature: [COLOR_CYAN]River[ENDCOLOR]. [NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Pagoda in the City in which it is built. [NEWLINE]Earn [ICON_CULTURE] Culture when purchasing a Missionary or Inquisitor class unit, scaling with Era.[NEWLINE]+2 [ICON_PEACE] Faith from all [ICON_VP_WRITER] Writer Specialists in your Empire.'),
('TXT_KEY_BUILDING_HORYUJI_PEDIA', 'Horyu-ji is one of Japan''s most important and historic Buddhist temples, located in Nara Prefecture. Founded in 607 CE by Prince Shotoku, a key figure in early Japanese Buddhism, the temple was built to promote the teachings of Buddhism in Japan. The original structure was damaged by fire in 670, but it was quickly rebuilt, and many of its buildings have remained intact for over 1,300 years. The temple complex is home to some of the oldest surviving wooden structures in the world, including the Five-Story Pagoda and the Kondo (Golden Hall), which house priceless Buddhist statues and artifacts from the Asuka period. [NEWLINE][NEWLINE]Horyu-ji was designated a UNESCO World Heritage Site in 1993 due to its historical, cultural, and architectural significance. The temple complex is divided into two main areas: the Sai-in Garan (Western Precinct), where the oldest structures are located, and the To-in Garan (Eastern Precinct), which includes the Hall of Dreams (Yumedono). As a center of Buddhist learning and art, Horyu-ji remains an active place of worship and an enduring symbol of Japan''s deep spiritual and architectural heritage.'),
('TXT_KEY_BUILDING_HORYUJI_QUOTE', '[NEWLINE]"Sincerely revere the three treasures: the Buddha, his Teaching, and the ordained Community."[NEWLINE] - Prince Shotoku[NEWLINE]'),
('TXT_KEY_GRAND_HORYUJI_BONUS_HEADER', 'Horyu-ji [ICON_CULTURE]'),
('TXT_KEY_GRAND_HORYUJI_BONUS_BODY', '+{@1_num} [ICON_CULTURE] Culture from {@2_unitName} unit.'),
--======================================================================================================================
-- Kyz Kala
--======================================================================================================================
('TXT_KEY_BUILDING_KYZ_KALA', 'Great Kyz Kala'),
('TXT_KEY_BUILDING_KYZ_KALA_HELP', 'Terrain: [COLOR_NEGATIVE_TEXT]Coast[ENDCOLOR], [COLOR_NEGATIVE_TEXT]Lake[ENDCOLOR]; Feature: [COLOR_CYAN]Oasis[ENDCOLOR]. [NEWLINE][NEWLINE]+2 [ICON_GREAT_GENERAL] Great General points. [NEWLINE]Provides a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Castle in the City in which it is built. [NEWLINE]+1 [ICON_PRODUCTION] Production, [ICON_CULTURE] Culture, [ICON_GOLDEN_AGE] Golden Age Point from Oases across the Empire. [NEWLINE]+25 [ICON_FOOD] Food when constructing a Building in this City, scaling with Era.'),
('TXT_KEY_BUILDING_KYZ_KALA_PEDIA', 'The Great Kyz Kala is a monumental mudbrick, fortified-building, one of a number of similar structures known as köshks, within the UNESCO World Heritage Site of Merv, Turkmenistan.  The monument''s construction date and use are currently a matter of some speculation; it is thought to have been built somewhere between the 6th and 8th century CE, in the late Sassanian or early Islamic period, and to have continued in use until the Mongol sack of Merv in 1221 CE.  Located just outside the city walls, it seems likely to have functioned as a fortified residence, with recent excavations identifying a number of internal divisions, with distinct rooms, floor surfaces and staircases.'),
('TXT_KEY_BUILDING_KYZ_KALA_QUOTE', '[NEWLINE]"But all this world is like a tale we hear. Men''s evil, and their glory, disappear."[NEWLINE] - Abul-Qasem Ferdowsi[NEWLINE]'),
--======================================================================================================================
-- Shaolin Temple
--======================================================================================================================
('TXT_KEY_BUILDING_SHAOLIN', 'Shaolin Temple'),
('TXT_KEY_BUILDING_SHAOLIN_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR]; City: [COLOR_CYAN]Has adopted Player''s Majority Religion[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Order in the City in which it is built. [NEWLINE]+20 XP for all Units in every City. [NEWLINE]10% of [ICON_PEACE] Faith output in all Cities is added as [ICON_GREAT_GENERAL] Great General points.'),
('TXT_KEY_BUILDING_SHAOLIN_PEDIA', 'The Shaolin Monastery has a rich history spanning over 1,500 years, beginning with its founding in 495 AD during the Northern Wei Dynasty when Emperor Xiaowen granted permission to the Indian monk Batuo (also known as Buddhabhadra) to build a temple at the foot of Shaoshi Mountain in Henan Province. Batuo established Shaolin as an important center for Buddhist study and practice, laying the foundation for what would become one of China''s most famous monasteries. Thirty-two years later, another significant figure arrived: the Indian monk Bodhidharma (known as Da Mo in Chinese), who became the first patriarch to preach Chan (Zen) Buddhism at the temple, fundamentally shaping the monastery''s spiritual character and establishing its reputation as the birthplace of Chan Buddhism. [NEWLINE][NEWLINE]While Shaolin is globally renowned for its martial arts tradition, the historical development of its fighting systems is more complex than popular legend suggests. Modern martial arts historians have shown that the widespread belief that Bodhidharma founded martial arts at Shaolin actually stems from a 17th-century qigong manual and was popularized in the 20th century. Bodhidharma''s actual contribution was developing exercises based on Qigong to help monks maintain their health, which were more similar to yoga than combative techniques. The monastery''s martial arts traditions likely evolved gradually over centuries, incorporating various fighting systems and becoming systematized much later than the legendary accounts suggest. Despite these historical clarifications, Shaolin remains deeply significant both as a center of Buddhist learning and as a symbol of Chinese martial arts culture.'),
('TXT_KEY_BUILDING_SHAOLIN_QUOTE', '[NEWLINE]"Faith makes it possible to achieve that which man''s mind can conceive and believe."[NEWLINE] - Bruce Lee[NEWLINE]'),
--======================================================================================================================
-- Basilica of Saint Francis of Assisi
--======================================================================================================================
('TXT_KEY_BUILDING_ASSISI', 'San Francesco d''Assisi'),
('TXT_KEY_BUILDING_ASSISI_HELP', 'Terrain: [COLOR_NEGATIVE_TEXT]Coast[ENDCOLOR]; Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Cathedral in the City in which it is built. [NEWLINE]All Buildings yielding [ICON_PEACE] Faith in the Empire gain +1 [ICON_GOLD] Gold.'),
('TXT_KEY_BUILDING_ASSISI_PEDIA', 'The Basilica of Saint Francis of Assisi, located in the town of Assisi in central Italy, is one of the most significant and revered sites in the Christian world. Constructed between 1228 and 1253, soon after the canonization of Saint Francis, the basilica consists of two distinct churches: the Upper Basilica (Basilica Superiore) and the Lower Basilica (Basilica Inferiore). The Upper Basilica, with its soaring Gothic architecture, features large stained glass windows and is renowned for its extensive cycle of frescoes attributed to Giotto and his workshop, which depict the life of Saint Francis and are considered masterpieces of Italian art. The Lower Basilica, characterized by its Romanesque style, is more austere and houses the tomb of Saint Francis, making it a place of pilgrimage for millions of faithful from around the world. [NEWLINE][NEWLINE]The Basilica of Saint Francis of Assisi not only serves as a major religious site but also as a cultural and artistic treasure. The frescoes in both the Upper and Lower Basilicas are among the most important in the history of Western art, illustrating pivotal scenes from the Bible and the life of Saint Francis with vivid detail and emotional depth. These artworks played a crucial role in the development of Italian Renaissance art. The basilica complex, which also includes a friary, has been designated a UNESCO World Heritage Site due to its historical, spiritual, and artistic significance. It remains a vital center for the Franciscan order and continues to inspire visitors with its profound beauty and spiritual legacy.'),
('TXT_KEY_BUILDING_ASSISI_QUOTE', '[NEWLINE]"Start by doing what''s necessary; then do what''s possible; and suddenly you are doing the impossible."[NEWLINE] - Saint Francis of Assisi[NEWLINE]'),
--======================================================================================================================
-- Church of the Nativity
--======================================================================================================================
('TXT_KEY_BUILDING_CHURCH_NATIVITY', 'Church of the Nativity'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]; Player: [COLOR_CYAN]Founded Religion[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Church in the City in which it is built. [NEWLINE]In all Cities +2 [ICON_PEACE] Faith, +2 [ICON_PRODUCTION] Production for every World Religion that has at least one Follower in the respective City.'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_PEDIA', 'The Church of the Nativity, located in Bethlehem, is one of Christianity''s holiest sites, traditionally believed to be the birthplace of Jesus Christ. Built over a cave known as the Grotto of the Nativity, the church was originally commissioned by Emperor Constantine and his mother, Helena, in the 4th century. The basilica was later rebuilt by Emperor Justinian in the 6th century after being damaged. Over the centuries, the church has undergone numerous renovations and additions, including elements from the Crusader period, Greek Orthodox, Armenian, and Roman Catholic influences. The structure is marked by its ancient columns, mosaics, and the silver star in the grotto, which signifies the exact spot of Christ''s birth. [NEWLINE][NEWLINE]Despite its turbulent history, including invasions, fires, and political conflicts, the Church of the Nativity remains a major pilgrimage destination. It is jointly managed by the Greek Orthodox, Armenian Apostolic, and Roman Catholic churches, each controlling different sections. In 2012, UNESCO recognized it as a World Heritage Site, highlighting its historical and spiritual significance. Today, it continues to attract millions of visitors annually, serving as a powerful symbol of faith and endurance in the heart of Bethlehem.'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_QUOTE', '[NEWLINE]"You must look at the Child in the manger. He is our Love. Look at him, realizing that the whole thing is a mystery."[NEWLINE] - Saint Josemaria Escriva[NEWLINE]'),
--======================================================================================================================
-- Hospital of Saint John
--======================================================================================================================
('TXT_KEY_BUILDING_HOSPITAL_STJOHN', 'Hospital of St. John'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Order in the City in which it is built. [NEWLINE]Land Units in this City heal 10 points per turn whether or not they take an action. [NEWLINE][NEWLINE]15% of [ICON_PEACE] Faith created by all Cities in the Empire counts as [ICON_FOOD] Food Per Turn.'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_PEDIA', 'The Order of the Hospital of St. John of Jerusalem, commonly known as the Knights Hospitaller, was a medieval Catholic military order founded in the 11th century to provide care for sick, poor, and injured pilgrims in the Holy Land. Established around 1023 by a group of merchants from Amalfi, the order initially focused on running a hospital in Jerusalem dedicated to St. John the Baptist. After the First Crusade and the establishment of the Kingdom of Jerusalem, the order gained military functions to protect pilgrims and the territories acquired by the Crusaders. The Knights Hospitaller became one of the most powerful and influential military orders of the medieval period, playing a significant role in the defense of Christian territories in the Holy Land and the Mediterranean. [NEWLINE][NEWLINE]Throughout the centuries, the order adapted to changing political and military landscapes. After the fall of Jerusalem in 1187, the Knights relocated their headquarters several times, eventually settling on the island of Rhodes in 1309 and later Malta in 1530, where they became known as the Knights of Malta. Their presence on these islands fortified them against Ottoman expansion and piracy, turning them into a formidable naval power. Even after losing Malta to Napoleon in 1798, the order continued its charitable work. Today, the Sovereign Military Order of Malta remains a humanitarian organization with a presence worldwide, continuing its founding mission of aiding the sick and poor, while maintaining its status as a sovereign entity with diplomatic relations with numerous countries.'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_QUOTE', '[NEWLINE]"For Faith, For Service to Humanity."[NEWLINE] - Knights Hospitaller Motto[NEWLINE]'),
--======================================================================================================================
-- Tlachihualtepetl
--======================================================================================================================
('TXT_KEY_BUILDING_TLACHIHUALTEPETL', 'Tlachihualtepetl'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Teocalli in the City in which it is built. [NEWLINE]All Cities earn +10 [ICON_PEACE] Faith, +5 [ICON_GOLDEN_AGE] Golden Age Points and +5 [ICON_GREAT_GENERAL] Great General points when they construct Buildings, scaling with Era.'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_PEDIA', 'Tlachihualtepetl, also known as the Great Pyramid of Cholula, is an ancient Mesoamerican structure located in Cholula, Mexico. It is considered the largest pyramid by volume in the world, surpassing even the Great Pyramid of Giza. Built in multiple phases beginning around the 3rd century BCE by the indigenous inhabitants of Cholula, the pyramid was expanded over centuries, reaching a base of approximately 450 by 450 meters (1,480 by 1,480 feet) and a height of around 66 meters (217 feet). Its name, Tlachihualtepetl, means "man-made mountain" in Nahuatl, reflecting its layered construction as each civilization built upon the previous one. The pyramid was an important religious and ceremonial center dedicated to the god Quetzalcoatl, playing a significant role in pre-Columbian culture. [NEWLINE][NEWLINE]By the time of the Spanish conquest in the 16th century, the pyramid had been largely abandoned and overgrown, resembling a natural hill. The Spanish, unaware of the structure beneath, built the Church of Our Lady of Remedies on top, symbolizing the imposition of Christianity over indigenous beliefs. Today, Tlachihualtepetl is an important archaeological site, with a network of tunnels excavated inside the pyramid revealing its layered history. It remains a significant cultural and tourist attraction, blending pre-Hispanic and colonial heritage, and stands as a testament to the architectural and religious traditions of ancient Mesoamerican civilizations.'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_QUOTE', '[NEWLINE]"Quetzalcoatl is a primal idea of the duality of human nature. The serpent is the embodiment of Heaven and Earth. It scares people in many ways."[NEWLINE] - Robert Graham[NEWLINE]'),
--======================================================================================================================
-- Old New Synagogue of Prague
--======================================================================================================================
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE', 'Old New Synagogue of Prague'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_HELP', ' Feature: [COLOR_CYAN]River[ENDCOLOR];  City: [COLOR_CYAN]Minority Religion with at least 4 Followers[ENDCOLOR].[NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Synagogue in the City in which it is built. [NEWLINE]Starts 15 turns of "[COLOR_POSITIVE_TEXT]We Love the King Day[ENDCOLOR]" in the City. [NEWLINE]In all Cities +10% [ICON_GOLD] Gold, [ICON_CULTURE] Culture, [ICON_PEACE] Faith during "[COLOR_POSITIVE_TEXT]We Love the King Day[ENDCOLOR]".'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_PEDIA', 'The Old New Synagogue, located in the heart of Prague''s Jewish Quarter, is one of the most historic and culturally significant synagogues in Europe. Built in the 1270s during the reign of King Ottokar II of Bohemia, it is the oldest active synagogue in Europe. The synagogue''s name, "Old New", reflects its history; it was once the "New Synagogue" when it was built, but as newer synagogues were constructed, it became known as the "Old New" to distinguish it from them. Architecturally, the synagogue is a masterpiece of Gothic style, featuring a distinctive gabled roof and a striking façade. Its interior is adorned with intricate stone carvings and a vaulted ceiling, creating a sense of solemnity and reverence. [NEWLINE][NEWLINE]Throughout its history, the Old New Synagogue has played a pivotal role in Jewish life in Prague. It has been a center of worship, learning, and community for centuries, surviving numerous challenges, including fires, floods, and periods of persecution. The synagogue is also famous for its association with the legend of the Golem of Prague, a mythical creature said to have been created by Rabbi Judah Loew ben Bezalel, a prominent rabbi who prayed at the synagogue in the 16th century. Today, the Old New Synagogue continues to serve as an active place of worship and is a major tourist attraction, offering visitors a glimpse into the rich history and traditions of Prague''s Jewish community. Its enduring presence is a testament to the resilience and cultural heritage of Jewish life in Europe.'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_QUOTE', '[NEWLINE]"Judaism is something more than a badge, something more than a birth-mark; it is a life."[NEWLINE] - Morris David Joseph[NEWLINE]'),
--======================================================================================================================
-- Jetavanaramaya
--======================================================================================================================
('TXT_KEY_BUILDING_JETAVANARAMAYA', 'Jetavanaramaya'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_HELP', 'Feature: [COLOR_CYAN]Forest/Jungle[ENDCOLOR]; Improvement: [COLOR_CYAN]Village[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Stupa in the City in which it is built. [NEWLINE]10% of [ICON_FOOD] Food is carried over after a new [ICON_CITIZEN] Citizen is born in all Cities, and additional 10% in the City in which it is built. [NEWLINE]+2 [ICON_PEACE] Faith to Villages in the Empire.'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_PEDIA', 'The Jetavanaramaya is an ancient stupa located in Anuradhapura, Sri Lanka, and is one of the tallest and most significant Buddhist monuments in the world. Constructed during the 3rd century CE by King Mahasena (r. 277–304 CE), it was part of the Jetavana Monastery, which became an important center for Theravada and Mahayana Buddhism. At its peak, the stupa stood approximately 122 meters (400 feet) high, making it one of the tallest structures of the ancient world. Built primarily of brick, Jetavanaramaya remains one of the largest brick structures ever created, showcasing the engineering prowess of ancient Sri Lankan civilization. [NEWLINE][NEWLINE]Over the centuries, the stupa suffered damage due to invasions and neglect, but it remained a revered site for Buddhist worshippers. Restoration efforts in modern times have helped preserve its grandeur, and today, it remains an important pilgrimage destination. The stupa is surrounded by ruins of monastic buildings and intricate carvings, reflecting the architectural and artistic achievements of the Anuradhapura period. Jetavanaramaya continues to be a symbol of Sri Lanka’s Buddhist heritage and a testament to the historical significance of the ancient city of Anuradhapura.'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_QUOTE', '[NEWLINE]"The monk who is calm in body, calm in speech, calm in thought, well-composed and who has spewn out worldliness — he, truly, is called serene."[NEWLINE] - Dhammapada, verse 378[NEWLINE]'),
--======================================================================================================================
-- Harmandir Sahib
--======================================================================================================================
('TXT_KEY_BUILDING_HARMANDIR_SAHIB', 'Harmandir Sahib'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Gurdwara in the City in which it is built. [NEWLINE]All Baths and Buildings yielding [ICON_PEACE] Faith in the Empire gain +2 [ICON_FOOD] Food. [NEWLINE][NEWLINE]-1 [ICON_HAPPINESS_3] Unhappiness from Religious Unrest in all Cities.'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_PEDIA', 'Harmandir Sahib, also known as the Golden Temple, is the holiest shrine of Sikhism, located in Amritsar, Punjab, India. It was founded in 1581 by Guru Ram Das, the fourth Sikh Guru, and completed by his successor, Guru Arjan Dev, in 1604. The temple was built as a place of spiritual worship open to all, regardless of caste or religion. Guru Arjan Dev installed the Guru Granth Sahib, the central holy scripture of Sikhism, inside the temple, making it the spiritual and cultural heart of the Sikh faith. Over centuries, the temple endured attacks and was rebuilt multiple times, including its gold-plated renovation under Maharaja Ranjit Singh in the early 19th century, which gave it its iconic appearance. [NEWLINE][NEWLINE]The Golden Temple is a stunning architectural masterpiece, blending Hindu and Islamic styles with a distinctive Sikh identity. Surrounded by the Amrit Sarovar (Pool of Nectar), the temple''s shimmering gold-covered façade and marble inlays create a breathtaking spectacle. It has four entrances, symbolizing openness and inclusivity, and a causeway leading to the sanctum, where continuous recitation of the Guru Granth Sahib takes place. The temple complex also houses the Akal Takht, the highest seat of Sikh religious authority, and the world’s largest free community kitchen (Langar), serving meals to thousands daily. Harmandir Sahib remains a symbol of Sikh devotion, resilience, and universal brotherhood.'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_QUOTE', '[NEWLINE]"The Giver of peace is eternally blissful."[NEWLINE] - Sri Guru Granth Sahib[NEWLINE]'),
--======================================================================================================================
-- Larabanga
--======================================================================================================================
('TXT_KEY_BUILDING_LARABANGA', 'Larabanga Mosque'),
('TXT_KEY_BUILDING_LARABANGA_HELP', 'Terrain: [COLOR_CYAN]Plains[ENDCOLOR]; Building: [COLOR_CYAN]Customs House[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Mosque in the City in which it is built. [NEWLINE]+100% Religious Pressure towards Cities connected by Trade Routes. [NEWLINE]All [ICON_INTERNATIONAL_TRADE] International Trade Routes provide +3 [ICON_GOLD] Gold, +3 [ICON_PEACE] Faith.'),
('TXT_KEY_BUILDING_LARABANGA_PEDIA', 'The Larabanga Mosque, located in northern Ghana, is one of West Africa''s oldest and most revered Islamic sites. Built in the 15th century, it is believed to have been founded by an Islamic trader named Ayuba, who, according to legend, was guided by divine intervention to construct the mosque. The mosque played a crucial role in spreading Islam in the region and remains a center of Islamic learning and worship. Its historical significance and connection to early trans-Saharan trade routes make it a key cultural and religious landmark in Ghana. Despite facing structural challenges over the centuries, including weather damage and restoration efforts, it continues to serve as an active place of prayer and pilgrimage. [NEWLINE][NEWLINE]Architecturally, the Larabanga Mosque is a striking example of Sudano-Sahelian design, characterized by its whitewashed mud walls and timber-reinforced framework. It features two prominent towers—one serving as a minaret and the other as a mihrab (prayer niche facing Mecca). The mosque''s compact, rectangular shape and buttressed walls give it a distinctive, fortress-like appearance. Wooden beams protrude from the structure, not only for aesthetic value but also to provide support and aid in maintenance. The mosque''s simple yet elegant design reflects the adaptation of Islamic architecture to the local environment and materials. Today, it remains a revered spiritual site and a significant symbol of Ghana''s Islamic heritage.'),
('TXT_KEY_BUILDING_LARABANGA_QUOTE', '[NEWLINE]"Whatever you have will perish, but what Allah has will remain."[NEWLINE]- The Quran[NEWLINE]'),
--======================================================================================================================
-- Botanical Garden of Padua
--======================================================================================================================
('TXT_KEY_BUILDING_PADUA_GARDEN', 'Botanical Garden of Padua'),
('TXT_KEY_BUILDING_PADUA_GARDEN_HELP', 'Improved Resource: [COLOR_CYAN]Plant Resources[ENDCOLOR]; Building: [COLOR_CYAN]Garden[ENDCOLOR]. [NEWLINE][NEWLINE]All Gardens gain +2 [ICON_FOOD] Food, +2 [ICON_RESEARCH] Science. [NEWLINE]All Plant Resources: +1 [ICON_RESEARCH] Science. [NEWLINE]+3 [ICON_FOOD] Food from all Academies in your Empire.'),
('TXT_KEY_BUILDING_PADUA_GARDEN_PEDIA', 'The Botanical Garden of Padua, established in 1545, is the world''s oldest academic botanical garden still in its original location. Located in Padua, Italy, it was created for the study of medicinal plants, a reflection of the Renaissance''s growing interest in natural sciences and the medicinal properties of plants. Initially, the garden focused on the cultivation and classification of plants used for medical purposes, providing an essential resource for medical students at the University of Padua. Its design, with a circular central plot symbolizing the world and smaller, geometrically arranged beds around it, has influenced the layout of botanical gardens worldwide. [NEWLINE][NEWLINE]Over the centuries, the Botanical Garden of Padua has expanded its collection to include a vast array of plant species from around the globe, showcasing an impressive diversity of flora. It houses over 6,000 species, including rare and endangered plants, and features several themed sections such as the Garden of Biodiversity, which highlights the planet''s diverse ecosystems. The garden has played a pivotal role in botanical research and education, contributing significantly to the study of plant sciences. In recognition of its historical and scientific importance, it was designated a UNESCO World Heritage Site in 1997. Today, it continues to serve as a vital center for research, conservation, and public education, attracting scholars, students, and nature enthusiasts from around the world.'),
('TXT_KEY_BUILDING_PADUA_GARDEN_QUOTE', '[NEWLINE]"If you have a garden and a library, you have everything you need."[NEWLINE] - Marcus Tullius Cicero[NEWLINE]'),
--======================================================================================================================
-- Changdeokgung
--======================================================================================================================
('TXT_KEY_BUILDING_CHANGDEOKGUNG', 'Changdeokgung'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_PEOPLE] Great Person of your choice. [NEWLINE]All Baths and Gardens gain +1 [ICON_HAPPINESS_1] Happiness. [NEWLINE]+2 [ICON_PRODUCTION] Production, +2 [ICON_GOLDEN_AGE] Golden Age Points from all [ICON_CSD_CIVIL_SERVANT] Civil Servant Specialists in your Empire.'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_PEDIA', 'Changdeokgung, located in Seoul, South Korea, is one of the "Five Grand Palaces" built during the Joseon Dynasty and is renowned for its harmonious integration with the natural landscape. Constructed in 1405, the palace served as the principal residence for many Joseon kings and was favored for its serene, beautiful surroundings. Unlike other palaces that follow strict geometric layouts, Changdeokgung is designed to blend seamlessly with the topography of the site, featuring a series of pavilions, courtyards, and gardens that follow the contours of the terrain. This approach reflects the traditional Korean philosophy of living in harmony with nature. [NEWLINE][NEWLINE]One of the most notable features of Changdeokgung is the Huwon, or "Secret Garden," a 78-acre garden that was used by the royal family for leisure and retreat. The garden is meticulously landscaped with ponds, pavilions, and a variety of trees and flowers, offering a tranquil escape from the stresses of court life. Changdeokgung''s unique design and historical significance led to its designation as a UNESCO World Heritage Site in 1997. The palace complex not only exemplifies the aesthetic and philosophical values of the Joseon Dynasty but also serves as a cultural and architectural treasure, attracting numerous visitors who come to appreciate its timeless beauty and historical importance.'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_QUOTE', '[NEWLINE]"Genius without religion is only a lamp on the outer gate of a palace."[NEWLINE] - Hannah More[NEWLINE]'),
--======================================================================================================================
-- Damnoen Saduak
--======================================================================================================================
('TXT_KEY_BUILDING_DAMNOEN_SADUAK', 'Damnoen Saduak'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_HELP', 'Feature: [COLOR_CYAN]River[ENDCOLOR]; Building: [COLOR_CYAN]Grocer[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_MERCHANT] Great Merchant. [NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold, +1 [ICON_CULTURE] Culture from nearby River tiles. [NEWLINE]+2 [ICON_FOOD] Food, +2 [ICON_CULTURE] Culture from all [ICON_VP_MERCHANT] Merchant Specialists in your Empire. [NEWLINE]All Markets and Grocers gain +2 [ICON_GOLD] Gold, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_PEDIA', 'Damnoen Saduak Floating Market, located in Ratchaburi Province, Thailand, about 100 kilometers southwest of Bangkok, is one of the most famous and vibrant floating markets in the country. Established in the 19th century during the reign of King Rama IV, the market has become a quintessential representation of traditional Thai commerce and culture. Vendors, primarily women wearing wide-brimmed straw hats, paddle small wooden boats laden with fresh produce, local delicacies, and handicrafts through a network of canals. This lively waterborne marketplace offers visitors a glimpse into the traditional way of life in Thailand, where waterways were once the primary means of transportation and trade. [NEWLINE][NEWLINE]The bustling atmosphere of Damnoen Saduak Floating Market attracts numerous tourists who come to experience the unique shopping environment and enjoy the array of sights, sounds, and flavors. Visitors can sample an assortment of Thai street foods directly from the boats, such as pad thai, mango sticky rice, and freshly squeezed coconut juice, while exploring stalls selling souvenirs and handmade goods along the canal banks. The market''s picturesque setting and dynamic activity provide ample opportunities for photography and cultural immersion. Despite its popularity with tourists, Damnoen Saduak remains a working market for locals, maintaining its authenticity and charm as a vibrant hub of daily life and commerce in rural Thailand.'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_QUOTE', '[NEWLINE]"Ideas, like large rivers, never have just one source."[NEWLINE] - Willy Ley[NEWLINE]'),
--======================================================================================================================
-- Paro Taktsang
--======================================================================================================================
('TXT_KEY_BUILDING_TAKTSANG', 'Paro Taktsang'),
('TXT_KEY_BUILDING_TAKTSANG_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR].[NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Monastery in the City in which it is built. [NEWLINE]Place a Holy Site on a nearby mountain that yields additional +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production.'),
('TXT_KEY_BUILDING_TAKTSANG_PEDIA', 'Paro Taktsang, also known as the Tiger''s Nest Monastery, is a sacred Buddhist site perched dramatically on a cliffside in Bhutan''s Paro Valley. Built in 1692, the monastery is said to mark the meditation site of Guru Padmasambhava, the legendary 8th-century Buddhist master who introduced Vajrayana Buddhism to Bhutan. According to legend, Padmasambhava flew to the site on the back of a tigress, giving the monastery its famous name. The complex consists of multiple temples and meditation caves, blending seamlessly with the rugged cliffs at an elevation of about 3,120 meters (10,240 feet). The monastery is a major pilgrimage site and an iconic symbol of Bhutanese culture and spirituality. [NEWLINE][NEWLINE]Despite its remote location, Paro Taktsang has been carefully preserved and rebuilt after suffering significant damage from a fire in 1998. Accessible only by a steep mountain trail, the monastery remains a place of deep spiritual significance and offers breathtaking views of the surrounding valley. The site is visited by thousands of pilgrims and tourists each year, drawn by its mystical history, stunning architecture, and serene atmosphere. Paro Taktsang stands as a testament to Bhutan’s strong Buddhist traditions and its commitment to preserving sacred heritage in harmony with nature.'),
('TXT_KEY_BUILDING_TAKTSANG_QUOTE', '[NEWLINE]"There are many paths to the top of the mountain, yet the view is always the same"[NEWLINE] - Chinese Proverb[NEWLINE]'),
--======================================================================================================================
-- Keshgarh Qila
--======================================================================================================================
('TXT_KEY_BUILDING_KESHGARH_QILA', 'Keshgarh Qila'),
('TXT_KEY_BUILDING_KESHGARH_QILA_HELP', 'Terrain: [COLOR_CYAN]Grassland[ENDCOLOR]; Improvement: [COLOR_CYAN]Fort[ENDCOLOR]. [NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Gurdwara in the City in which it is built. [NEWLINE]+25% [ICON_PRODUCTION] Production of Land Melee Units in all Cities. [NEWLINE]Increases [ICON_SILVER_FIST] Military Unit Supply Cap by 5.'),
('TXT_KEY_BUILDING_KESHGARH_QILA_PEDIA', 'Takht Keshgarh Sahib or Keshgarh Qila is one of the five Takhts (temporal seats) of Sikhism and is located in Anandpur Sahib, Punjab, India. It holds immense historical and religious significance as the birthplace of the Khalsa, the Sikh warrior community, which was founded by Guru Gobind Singh Ji on Vaisakhi in 1699. During this event, Guru Gobind Singh initiated the first Panj Pyare (Five Beloved Ones) and introduced the Amrit Sanchar (Sikh baptism ceremony), establishing the Khalsa''s distinct identity. The Kesgarh Fort, which once stood on this site, was a crucial defense post during battles between the Sikhs and Mughal forces. The Takht Sahib houses many relics of Guru Gobind Singh, including weapons used by him and the Khalsa warriors. [NEWLINE][NEWLINE]Today, Takht Kesgarh Sahib is a major pilgrimage site for Sikhs and a symbol of their martial and spiritual heritage. The Gurdwara is built on a hilltop, offering a panoramic view of Anandpur Sahib and the surrounding Shivalik hills. The main shrine features a grand Darbar Hall, where daily prayers and kirtans (devotional songs) take place. Sikhs from around the world visit the Takht, especially during Vaisakhi celebrations, to honor the legacy of Guru Gobind Singh and the founding of the Khalsa. It remains a center of Sikh faith, resilience, and unity.'),
('TXT_KEY_BUILDING_KESHGARH_QILA_QUOTE', '[NEWLINE]"He who has no faith in himself can never have faith in God."[NEWLINE] - Guru Nanak[NEWLINE]'),
--======================================================================================================================
-- Citadelle Laferrière
--======================================================================================================================
('TXT_KEY_BUILDING_LAFERRIERE', 'Citadelle Laferrière'),
('TXT_KEY_BUILDING_LAFERRIERE_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]; Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_GENERAL] Great General.  [NEWLINE]All Siege Units in the Empire get [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_LAFERRIERE}[ENDCOLOR] promotion. [NEWLINE]All Forts, Citadels and unique improvements replacing them in the Empire receive +2 [ICON_FOOD] Food, +2 [ICON_PRODUCTION] Production, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_LAFERRIERE_PEDIA', 'Citadelle Laferrière, located in northern Haiti atop the Bonnet à l''Évêque mountain, is a monumental fortress and a symbol of Haitian independence and resilience. Constructed between 1805 and 1820 under the leadership of Henri Christophe, a key figure in the Haitian Revolution who later became king of northern Haiti, the citadel was built to defend against potential French invasions after Haiti won its independence in 1804. The fortress is an architectural marvel, featuring massive walls, impressive battlements, and an array of cannons and artillery, many of which remain in place today. Its strategic location, perched 900 meters above sea level, offers sweeping views of the surrounding landscape and the Atlantic Ocean, making it a formidable defensive structure. [NEWLINE][NEWLINE]The Citadelle Laferrière, along with the nearby Sans-Souci Palace, is a UNESCO World Heritage Site, recognized for its historical significance and outstanding representation of early 19th-century military architecture. The fortress is not only a testament to the ingenuity and determination of the Haitian people but also a poignant reminder of their struggle for freedom and self-determination. Today, it stands as a major cultural and tourist attraction, drawing visitors from around the world who come to explore its vast corridors, storerooms, and dungeons, and to learn about Haiti''s rich history. The Citadelle Laferrière remains a potent symbol of national pride and a powerful monument to the enduring spirit of independence.'),
('TXT_KEY_BUILDING_LAFERRIERE_QUOTE', '[NEWLINE]"Those who make peaceful revolution impossible will make violent revolution inevitable."[NEWLINE] - John F. Kennedy[NEWLINE]'),
('TXT_KEY_PROMOTION_LAFERRIERE', 'Unity is Strength'),
('TXT_KEY_PROMOTION_LAFERRIERE_HELP', '+25%[ICON_STRENGTH] Combat Strength. +1 [ICON_MOVES]Movement. Can Move After Attacking. [NEWLINE]+25%[ICON_STRENGTH] Combat Strength against Naval Units.'),
--======================================================================================================================
-- Victoria Terminus / Chhatrapati Shivaji Terminus
--======================================================================================================================
('TXT_KEY_BUILDING_VICTORIA_TERMINUS', 'Chhatrapati Shivaji Terminus'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_HELP', 'Special: [COLOR_YIELD_FOOD]Industrial City Connection[ENDCOLOR]; City: [COLOR_CYAN]18 Citizens[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Coaling Station in the City in which it is built and 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_RES_COAL] Coal. [NEWLINE]+15% [ICON_GOLD] Gold from [ICON_CONNECTED] City Connections and +15% [ICON_PRODUCTION] Production from [ICON_INDUSTRIAL_CONNECTED] Industrial City Connections. [NEWLINE][ICON_CONNECTED] City connections generate +5 [ICON_CULTURE] Culture. [NEWLINE]+100% [ICON_FOOD] Food or [ICON_PRODUCTION] Production from Internal Trade Routes.'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_PEDIA', 'Chhatrapati Shivaji Terminus (CST), formerly known as Victoria Terminus, is a historic railway station in Mumbai, India. Designed by British architect Frederick William Stevens, it was completed in 1887 to commemorate Queen Victoria’s Golden Jubilee. The station became a symbol of Mumbai’s rapid industrialization and was a key hub for the Great Indian Peninsula Railway. Over the years, it played a crucial role in the city’s economic and social growth, serving as a gateway for trade and migration. In 2004, CST was designated a UNESCO World Heritage Site, recognizing its architectural splendor and historical significance. [NEWLINE][NEWLINE]Architecturally, Chhatrapati Shivaji Terminus is a stunning blend of Victorian Gothic Revival and traditional Indian styles. The station features intricate stone carvings, domes, turrets, and pointed arches, inspired by medieval European cathedrals. A striking central dome with ribbed vaulting and a towering spire dominates the skyline, while the interior boasts a grand staircase, stained glass windows, and decorative ironwork. The station remains one of India’s busiest railway hubs, handling millions of passengers daily. Despite modern developments, CST retains its historic charm, standing as a testament to Mumbai’s colonial past and enduring vibrancy.'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_QUOTE', '[NEWLINE]"Railway termini are our gates to the glorious and the unknown. Through them we pass out into adventure and sunshine, to them, alas! we return."[NEWLINE] - Edward Morgan Forster[NEWLINE]'),
--======================================================================================================================
-- Capitoline Museums
--======================================================================================================================
('TXT_KEY_BUILDING_CAPITOLINE', 'Capitoline Museums'),
('TXT_KEY_BUILDING_CAPITOLINE_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Museum in the City in which it is built. [NEWLINE]+2 [ICON_CULTURE] Culture, [ICON_GOLDEN_AGE] Golden Age points from nearby Hills. [NEWLINE]Archaeologists can be purchased with [ICON_GOLD] Gold, gain +1 [ICON_MOVES] Movement, and have double Work rate. [NEWLINE]+4 [ICON_CULTURE] Culture, [ICON_RESEARCH] Science, and [ICON_TOURISM] Tourism if [COLOR_POSITIVE_TEXT]Themed[ENDCOLOR].'),
('TXT_KEY_BUILDING_CAPITOLINE_PEDIA', 'The Capitoline Museums, located on Rome''s Capitoline Hill, are the oldest public museums in the world, tracing their origins to 1471 when Pope Sixtus IV donated a collection of important bronze statues to the people of Rome. This act laid the foundation for the museums, which were officially opened to the public in 1734 by Pope Clement XII. The museums comprise three main buildings: the Palazzo dei Conservatori, the Palazzo Nuovo, and the Centrale Montemartini. These buildings house an extensive collection of classical sculptures, ancient Roman artifacts, Renaissance and Baroque art, and other historical pieces that reflect Rome''s rich cultural heritage. [NEWLINE][NEWLINE]Among the most notable exhibits in the Capitoline Museums are the iconic statue of the she-wolf suckling Romulus and Remus, the symbol of Rome; the colossal statue of Emperor Constantine; and the Dying Gaul, a celebrated ancient Roman sculpture. The museums also feature works by renowned artists such as Caravaggio, Titian, and Rubens. Additionally, the Capitoline Museums offer breathtaking views of the Roman Forum and surrounding areas from the Piazza del Campidoglio, designed by Michelangelo. The blend of art, history, and stunning architecture makes the Capitoline Museums a vital cultural and historical institution, attracting visitors from around the globe who seek to immerse themselves in the legacy of ancient Rome and the evolution of Western art.'),
('TXT_KEY_BUILDING_CAPITOLINE_QUOTE', '[NEWLINE]"Rome is not like any other city. It''s a big museum, a living room that shall be crossed on one''s toes."[NEWLINE] - Alberto Sordi[NEWLINE]'),
('TXT_KEY_THEMING_BONUS_CAPITOLINE', 'Wonders of Rome'),
('TXT_KEY_THEMING_BONUS_CAPITOLINE_HELP', 'To maximize your bonus, make sure all the Great Work Slots are filled.'),
--======================================================================================================================
-- Muzibu Azaala Mpanga
--======================================================================================================================
('TXT_KEY_BUILDING_KASUBI_TOMBS', 'Muzibu Azaala Mpanga'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_HELP', 'Feature: [COLOR_CYAN]Lake[ENDCOLOR]. [NEWLINE][NEWLINE]+75 [ICON_PEACE] Faith when you expend a [ICON_GREAT_PEOPLE] Great Person, scaling with Era. [NEWLINE]+2 [ICON_TOURISM] Tourism on Lakes worked by this City.[NEWLINE]All Lakes in the Empire receive +2 [ICON_FOOD] Food, +2 [ICON_GOLDEN_AGE] Golden Age Points, +2 [ICON_GREAT_GENERAL] Great General points.'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_PEDIA', 'The Muzibu Azaala Mpanga is a magnificent royal tomb located at the Kasubi Tombs complex in Kampala, Uganda. Built in 1882, it serves as the burial site for four Kabakas (kings) of Buganda: Mutesa I, Mwanga II, Daudi Chwa II, and Edward Mutesa II. The structure is renowned for its extraordinary architectural design, featuring a massive circular thatched dome that reaches over 30 feet high. As a masterpiece of Ganda architecture and craftsmanship, it was designated a UNESCO World Heritage Site in 2001, recognizing its cultural significance and unique construction techniques. [NEWLINE][NEWLINE]The tomb''s interior is divided by a series of bark cloth curtains, creating sacred spaces where the kings'' remains are housed in separate chambers alongside royal regalia. Despite suffering a devastating fire in 2010 that destroyed much of the original structure, extensive restoration efforts were undertaken to rebuild it according to traditional methods, using materials like reeds, grass, and wood without nails. The Muzibu Azaala Mpanga continues to function as both a spiritual center for the Baganda people and a powerful symbol of indigenous knowledge, cultural identity, and the enduring legacy of the Buganda Kingdom.'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_QUOTE', '[NEWLINE]"Princes are like pythons. They swallow each other."[NEWLINE] - Ugandan Proverb[NEWLINE]'),
--======================================================================================================================
-- Golden Gate Bridge
--======================================================================================================================
('TXT_KEY_BUILDING_GOLDEN_GATE', 'Golden Gate Bridge'),
('TXT_KEY_BUILDING_GOLDEN_GATE_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_ENGINEER] Great Engineer. [NEWLINE]+10% [ICON_PRODUCTION] Production in all Cities. [NEWLINE]All International Trade Routes provide +5 [ICON_GOLDEN_AGE] Golden Age Points. [NEWLINE]+10 [ICON_INFLUENCE] Influence with all known City-States when you expend [ICON_GREAT_PEOPLE] Great People.'),
('TXT_KEY_BUILDING_GOLDEN_GATE_PEDIA', 'The Golden Gate Bridge, an iconic symbol of San Francisco, was completed in 1937 after four years of construction. Spanning the Golden Gate Strait, the 1.7-mile (2.7 km) bridge connects San Francisco to Marin County. Designed by Joseph Strauss, with significant contributions from engineers Leon Moisseiff and Irving Morrow, it was the longest and tallest suspension bridge in the world at the time of its completion. The bridge’s construction faced numerous challenges, including strong ocean currents, deep waters, and frequent fog, but advancements in safety measures—such as the use of a safety net—helped reduce worker fatalities. [NEWLINE][NEWLINE]The Golden Gate Bridge is famous for its Art Deco design and distinctive International Orange color, chosen for visibility in fog and aesthetic appeal. Today, it remains one of the most photographed landmarks in the world, carrying millions of vehicles annually and serving as both a critical transportation link and a tourist attraction. The bridge also plays a vital role in engineering history, inspiring modern bridge design. Despite the harsh marine environment, ongoing maintenance ensures its longevity. Whether admired from afar or walked across for stunning views of the San Francisco Bay, the Golden Gate Bridge remains a testament to human ingenuity and ambition.'),
('TXT_KEY_BUILDING_GOLDEN_GATE_QUOTE', '[NEWLINE]"To reach a port, we must sail. Sail, not tie at anchor. Sail, not drift."[NEWLINE] - Franklin D. Roosevelt[NEWLINE]'),
--======================================================================================================================
-- Te Tii Marae
--======================================================================================================================
('TXT_KEY_BUILDING_TE_TII_MARAE', 'Te Tii Marae'),
('TXT_KEY_BUILDING_TE_TII_MARAE_HELP', 'Building anywhere: [COLOR_CYAN]Courthouse[ENDCOLOR]. [NEWLINE][NEWLINE]All Courthouses gain +3 [ICON_PRODUCTION] Production, 1 [ICON_HAPPINESS_1] Happiness. [NEWLINE]Has 1 slot for [ICON_VP_GREATWRITING] Great Work of Writing, and starts with [ICON_VP_GREATWRITING] [COLOR_CULTURE_STORED]Treaty of Watangi[ENDCOLOR]. [NEWLINE]Every [ICON_VP_GREATWRITING] Great Work of Writing in this City grants +5 XP to all created Units (maximum of 45 XP).'),
('TXT_KEY_BUILDING_TE_TII_MARAE_PEDIA', 'Te Tii Marae is a unique meeting center. Like other marae in the Pacific, it served as both a sacred place for religion and a social meeting place in Polynesian culture. The term "marae" - mala''e in Tongan and malae in Samoan and Hawaiian - means "cleared, free of weeds and trees". In the Maori society the marae is where the culture flourishes; obligations between tribes are met there, families would hold certain occasions there, and important ceremonies are held there.[NEWLINE][NEWLINE]Te Tii Marae is more than that, however. The site is still in use today as part of Waitangi Day, the New Zealand holiday to commemorate the signing of the Treaty of Waitangi. On February 6 1840 the treaty was signed in a marquee at the grounds of James Busby''s house - now known as the Treaty House, making New Zealand part of the British Empire and ensuring the right of the Maori to their land and their rights as British subjects. However this had led to disagreements between the Europeans and Maori. The Maori view the treaty as a sacred pact, while the Pakeha - Maori for European New Zealanders - have taken disregard to it for many years. Chief Justice James Prendergast declared the treaty a "legal nullity" in 1877, displaying the European disconcern of the treaty until the Treaty of Waitangi Act in 1975 - almost a century later.[NEWLINE][NEWLINE]Today Te Tii Marae hosts the annual celebrations the day before Waitangi Day - Feburary 5 - where the New Zealander Prime Minister and other political figures are invited to the site and hears the speeches of the iwi - the large social group of Maori society. With celebration comes tensions between the two peoples as Waidangi Day is also a hotspot for Maori rights; as far back as 1971 Waitangi and the day have been marred by protests and activism concerning the treaty.'),
('TXT_KEY_BUILDING_TE_TII_MARAE_QUOTE', '[NEWLINE]"When what is not Maori is Pakeha and what is not Pakeha is Maori, I occupy the gap between the two, that black hole in which nothing can be seen and from which nothing can be heard."[NEWLINE] - Annamarie Jagose[NEWLINE]'),
('TXT_KEY_GREAT_WORK_TREATY_WATANGI', 'Treaty of Watangi'),
('TXT_KEY_GREAT_WORK_TREATY_WATANGI_QUOTE', '[NEWLINE]"Her Majesty the Queen of England extends to the Natives of New Zealand Her royal protection and imparts to them all the Rights and Privileges of British Subjects."[NEWLINE] - Treaty of Watangi[NEWLINE]'),
--======================================================================================================================
-- Changi Airport
--======================================================================================================================
('TXT_KEY_BUILDING_CHANGI_AIRPORT', 'Changi Airport'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_HELP', 'Special: [COLOR_YIELD_GOLD]Capital[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Airport in the City in which it is built. [NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_MERCHANT] Great Merchant. [NEWLINE]All Airports gain +2 [ICON_PRODUCTION] Production, +2 [ICON_GOLD] Gold, +2 [ICON_TOURISM] Tourism, +2 [ICON_GOLDEN_AGE] Golden Age points. [NEWLINE]All cities get +1 Air Unit Slot.'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_PEDIA', 'Singapore Changi Airport, often regarded as one of the world''s best airports, opened on 1 July 1981 to replace Paya Lebar Airport as Singapore''s main international gateway. The airport was built on reclaimed land in Changi, on the eastern tip of the island, and has since expanded into a global aviation hub. Over the years, it has undergone multiple expansions, growing from a single terminal to four main terminals, with the addition of Jewel Changi Airport in 2019—a lifestyle complex featuring gardens, retail, and the world''s tallest indoor waterfall. Changi Airport is known for its efficiency, top-tier passenger services, and extensive connectivity, serving over 100 airlines and linking Singapore to more than 400 cities worldwide. [NEWLINE][NEWLINE]Beyond being a transit hub, Changi Airport is an iconic destination offering world-class amenities, including themed gardens, movie theaters, free rest zones, and luxury shopping. It consistently ranks as one of the world''s busiest and most awarded airports, handling over 68 million passengers annually before the pandemic. The airport is also a key economic driver for Singapore, supporting its tourism and logistics industries. With future expansions, including the upcoming Terminal 5, Changi Airport aims to reinforce its position as a premier global air travel hub while embracing sustainability and innovation.'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_QUOTE', '[NEWLINE]"There was nowhere to go but everywhere, so just keep on rolling under the stars."[NEWLINE] - Jack Kerouac[NEWLINE]'),
--======================================================================================================================
-- Watson Research Center
--======================================================================================================================
('TXT_KEY_BUILDING_WATSON_RC', 'Watson Research Center'),
('TXT_KEY_BUILDING_WATSON_RC_HELP', 'Plot: [COLOR_CYAN]Flat[ENDCOLOR]; Building: [COLOR_CYAN]Research Lab[ENDCOLOR]. [NEWLINE][NEWLINE]+10% [ICON_RESEARCH] Science in your Empire. [NEWLINE]10% of [ICON_RESEARCH] Science created by all Cities on Empire counts as [ICON_PRODUCTION] Production Per Turn. [NEWLINE]All Manufactories and Towns in the Empire receive +4 [ICON_RESEARCH] Science.'),
('TXT_KEY_BUILDING_WATSON_RC_PEDIA', 'The Thomas J. Watson Research Center is IBM''s principal research facility, named after the company''s former CEO, Thomas J. Watson, Sr. Established in 1961, the center serves as the heart of IBM Research, focusing on cutting-edge advancements in computing, artificial intelligence, quantum computing, and semiconductor technology. The main campus, located in Yorktown Heights, New York, was designed by renowned architect Eero Saarinen, featuring a futuristic, wave-like structure that symbolizes innovation. Additional IBM research labs associated with the center are in Cambridge, Massachusetts, and Almaden, California. Over the decades, the Watson Research Center has contributed to groundbreaking developments, including IBM''s Deep Blue, which famously defeated chess champion Garry Kasparov in 1997, and Watson AI, which won Jeopardy! in 2011. [NEWLINE][NEWLINE]As a global leader in scientific and technological research, the Watson Research Center continues to drive advancements in cloud computing, cybersecurity, AI ethics, and quantum computing. The facility collaborates with universities, governments, and enterprises to push the boundaries of innovation. IBM''s quantum computing research, headquartered at Watson, is pioneering quantum processors that could revolutionize fields such as cryptography and materials science. With a strong emphasis on fundamental and applied research, the Watson Research Center remains at the forefront of technological breakthroughs, shaping the future of computing and artificial intelligence.'),
('TXT_KEY_BUILDING_WATSON_RC_QUOTE', '[NEWLINE]"If we knew what we were doing, it wouldn''t be called research."[NEWLINE] - Albert Einstein[NEWLINE]');
--======================================================================================================================
INSERT INTO Language_en_US 
				(Tag,										Text) 
SELECT DISTINCT	'TXT_KEY_BUILDING_'||b.WType||'_HELP_CUT',	Text
FROM Language_en_US a, JHWfVPConfig b WHERE a.Tag = 'TXT_KEY_BUILDING_'||b.WType||'_HELP';
--======================================================================================================================
--======================================================================================================================