--=======================================================================================================================
-- BUILDINGCLASSES
--=======================================================================================================================
-- BuildingClasses
------------------------------
INSERT OR REPLACE INTO BuildingClasses 
(DefaultBuilding, 				Type, 								Description) VALUES
('BUILDING_JAR_DUMMY_FOOD',		'BUILDINGCLASS_JAR_DUMMY_FOOD',		'TXT_KEY_BUILDING_JAR_DUMMY_FOOD'),
('BUILDING_JAR_DUMMY_PROD',		'BUILDINGCLASS_JAR_DUMMY_PROD',		'TXT_KEY_BUILDING_JAR_DUMMY_PROD'),
('BUILDING_JAR_DUMMY_GOLD',		'BUILDINGCLASS_JAR_DUMMY_GOLD',		'TXT_KEY_BUILDING_JAR_DUMMY_GOLD'),
('BUILDING_JAR_DUMMY_SCIENCE',	'BUILDINGCLASS_JAR_DUMMY_SCIENCE',	'TXT_KEY_BUILDING_JAR_DUMMY_SCIENCE'),
('BUILDING_JAR_DUMMY_CULTURE',	'BUILDINGCLASS_JAR_DUMMY_CULTURE',	'TXT_KEY_BUILDING_JAR_DUMMY_CULTURE'),
('BUILDING_JAR_DUMMY_FAITH',	'BUILDINGCLASS_JAR_DUMMY_FAITH',	'TXT_KEY_BUILDING_JAR_DUMMY_FAITH'),
('BUILDING_JAR_DUMMY_TOURISM',	'BUILDINGCLASS_JAR_DUMMY_TOURISM',	'TXT_KEY_BUILDING_JAR_DUMMY_TOURISM'),
('BUILDING_JAR_DUMMY_GAP',		'BUILDINGCLASS_JAR_DUMMY_GAP',		'TXT_KEY_BUILDING_JAR_DUMMY_GAP'),
('BUILDING_JAR_DUMMY_GENERAL',	'BUILDINGCLASS_JAR_DUMMY_GENERAL',	'TXT_KEY_BUILDING_JAR_DUMMY_GENERAL'),
('BUILDING_JAR_DUMMY_ADMIRAL',	'BUILDINGCLASS_JAR_DUMMY_ADMIRAL',	'TXT_KEY_BUILDING_JAR_DUMMY_ADMIRAL'),
('BUILDING_JAR_DUMMY_BORDER',	'BUILDINGCLASS_JAR_DUMMY_BORDER',	'TXT_KEY_BUILDING_JAR_DUMMY_BORDER');
------------------------------
-- Buildings
------------------------------	
INSERT OR REPLACE INTO Buildings
(Type, 						 	BuildingClass, 						IsDummy,	Cost,	FaithCost,	GreatWorkCount,	PrereqTech,	MinAreaSize,	NeverCapture,	Description, 							Help) VALUES	
('BUILDING_JAR_DUMMY_FOOD', 	'BUILDINGCLASS_JAR_DUMMY_FOOD',		1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_FOOD',		'TXT_KEY_BUILDING_JAR_DUMMY_FOOD'),
('BUILDING_JAR_DUMMY_PROD', 	'BUILDINGCLASS_JAR_DUMMY_PROD',		1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_PROD',		'TXT_KEY_BUILDING_JAR_DUMMY_PROD'),
('BUILDING_JAR_DUMMY_GOLD', 	'BUILDINGCLASS_JAR_DUMMY_GOLD',		1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_GOLD',		'TXT_KEY_BUILDING_JAR_DUMMY_GOLD'),
('BUILDING_JAR_DUMMY_SCIENCE', 	'BUILDINGCLASS_JAR_DUMMY_SCIENCE',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_SCIENCE',	'TXT_KEY_BUILDING_JAR_DUMMY_SCIENCE'),
('BUILDING_JAR_DUMMY_CULTURE', 	'BUILDINGCLASS_JAR_DUMMY_CULTURE',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_CULTURE',	'TXT_KEY_BUILDING_JAR_DUMMY_CULTURE'),
('BUILDING_JAR_DUMMY_FAITH', 	'BUILDINGCLASS_JAR_DUMMY_FAITH',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_FAITH',		'TXT_KEY_BUILDING_JAR_DUMMY_FAITH'),
('BUILDING_JAR_DUMMY_TOURISM', 	'BUILDINGCLASS_JAR_DUMMY_TOURISM',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_TOURISM',	'TXT_KEY_BUILDING_JAR_DUMMY_TOURISM'),
('BUILDING_JAR_DUMMY_GAP',	 	'BUILDINGCLASS_JAR_DUMMY_GAP',		1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_GAP',		'TXT_KEY_BUILDING_JAR_DUMMY_GAP'),
('BUILDING_JAR_DUMMY_GENERAL', 	'BUILDINGCLASS_JAR_DUMMY_GENERAL',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_GENERAL',	'TXT_KEY_BUILDING_JAR_DUMMY_GENERAL'),
('BUILDING_JAR_DUMMY_ADMIRAL', 	'BUILDINGCLASS_JAR_DUMMY_ADMIRAL',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_ADMIRAL',	'TXT_KEY_BUILDING_JAR_DUMMY_ADMIRAL'),
('BUILDING_JAR_DUMMY_BORDER', 	'BUILDINGCLASS_JAR_DUMMY_BORDER',	1,			-1,		-1,			-1,				null,		-1,				1,				'TXT_KEY_BUILDING_JAR_DUMMY_BORDER',	'TXT_KEY_BUILDING_JAR_DUMMY_BORDER');
------------------------------	
-- Building_YieldChanges
------------------------------		
INSERT OR REPLACE INTO Building_YieldChanges 
(BuildingType, 					YieldType,		Yield) VALUES
('BUILDING_JAR_DUMMY_FOOD',		'YIELD_FOOD',		1),
('BUILDING_JAR_DUMMY_PROD',		'YIELD_PRODUCTION',	1),
('BUILDING_JAR_DUMMY_GOLD',		'YIELD_GOLD',		1),
('BUILDING_JAR_DUMMY_SCIENCE',	'YIELD_SCIENCE',	1),
('BUILDING_JAR_DUMMY_CULTURE',	'YIELD_CULTURE',	1),
('BUILDING_JAR_DUMMY_FAITH',	'YIELD_FAITH',		1),
('BUILDING_JAR_DUMMY_TOURISM',	'YIELD_TOURISM',	1),
('BUILDING_JAR_DUMMY_GAP',		'YIELD_GOLDEN_AGE_POINTS',		1),
('BUILDING_JAR_DUMMY_GENERAL',	'YIELD_GREAT_GENERAL_POINTS',	1),
('BUILDING_JAR_DUMMY_ADMIRAL',	'YIELD_GREAT_ADMIRAL_POINTS',	1),
('BUILDING_JAR_DUMMY_BORDER',	'YIELD_CULTURE_LOCAL',			1);
--=======================================================================================================================
-- Language_en_US
--=======================================================================================================================
INSERT OR REPLACE INTO Language_en_US 
(Tag,									Text) VALUES
('TXT_KEY_BUILDING_JAR_DUMMY_FOOD',		'JarFix +1 [ICON_FOOD]'),
('TXT_KEY_BUILDING_JAR_DUMMY_PROD',		'JarFix +1 [ICON_PRODUCTION]'),
('TXT_KEY_BUILDING_JAR_DUMMY_GOLD',		'JarFix +1 [ICON_GOLD]'),
('TXT_KEY_BUILDING_JAR_DUMMY_SCIENCE',	'JarFix +1 [ICON_RESEARCH]'),
('TXT_KEY_BUILDING_JAR_DUMMY_CULTURE',	'JarFix +1 [ICON_CULTURE]'),
('TXT_KEY_BUILDING_JAR_DUMMY_FAITH',	'JarFix +1 [ICON_PEACE]'),
('TXT_KEY_BUILDING_JAR_DUMMY_TOURISM',	'JarFix +1 [ICON_TOURISM]'),
('TXT_KEY_BUILDING_JAR_DUMMY_GAP',		'JarFix +1 [ICON_GOLDEN_AGE]'),
('TXT_KEY_BUILDING_JAR_DUMMY_GENERAL',	'JarFix +1 [ICON_GREAT_GENERAL]'),
('TXT_KEY_BUILDING_JAR_DUMMY_ADMIRAL',	'JarFix +1 [ICON_GREAT_ADMIRAL]'),
('TXT_KEY_BUILDING_JAR_DUMMY_BORDER',	'JarFix +1 [ICON_CULTURE_LOCAL]');
--=======================================================================================================================
--=======================================================================================================================