--------------------------------------------------------------
-- Dummies for Natural Wonders
-- May 11, 2020: Created, adan_eslavo
--============================================--
-- TEMPORARY FIXES
--============================================--
-- because multi-tile NWs cannot be balanced without new table, this Resolution must be deleted until it will be added
DELETE FROM Resolutions WHERE Type = 'RESOLUTION_NATURAL_HERITAGE_SITES';
--============================================--
-- PROMOTIONS
--============================================--
INSERT INTO Language_en_US 
			(Tag,										Text) 
VALUES		('TXT_KEY_PROMOTION_KAILASH',				'Mahaprasthanika Parva'),
			('TXT_KEY_PROMOTION_KAILASH_HELP',			'Double[ICON_MOVES]Movement [COLOR:255:230:85:255]on Hills[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_ULURU',					'Old Tribes'),
			('TXT_KEY_PROMOTION_ULURU_HELP',			'+10 [ICON_INFLUENCE] Influence [COLOR:255:230:85:255]after Diplomatic Mission[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_SOLOMONS_MINES',		'For the King!'),
			('TXT_KEY_PROMOTION_SOLOMONS_MINES_HELP',	'+25% [ICON_WORKER] Work Rate.'),	
			('TXT_KEY_PROMOTION_BERMUDA_TRIANGLE',		'Lost in Time and Space'),
			('TXT_KEY_PROMOTION_BERMUDA_TRIANGLE_HELP',	'-3[ICON_MOVES]Movement Points. [COLOR_NEGATIVE_TEXT]Promotion lasts 3 turns[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_DALLOL',				'Explosive Mixture'),
			('TXT_KEY_PROMOTION_DALLOL_HELP',			'+10%[ICON_RANGE_STRENGTH]Offensive RCS.'),
			('TXT_KEY_PROMOTION_CAUSEWAY',				'Curiosity'),
			('TXT_KEY_PROMOTION_CAUSEWAY_HELP',			'+1[ICON_MOVES]Movement Point. +20% [ICON_WORKER] Work Rate.'),
			('TXT_KEY_PROMOTION_MT_EVEREST',			'Roof of the World'),
			('TXT_KEY_PROMOTION_MT_EVEREST_HELP',		'Unit gains [ICON_TOURISM] [COLOR:255:230:85:255]for revealing tiles[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_HA_LONG',				'Descending Dragon'),
			('TXT_KEY_PROMOTION_HA_LONG_HELP',			'Gain 80% of an Enemy Unit''s [ICON_STRENGTH]CS as a [ICON_CULTURE] [COLOR:255:230:85:255]on Kill[ENDCOLOR]. +20%[ICON_STRENGTH]Defensive CS'),
			('TXT_KEY_PROMOTION_AURORA',				'Revontulet'),
			('TXT_KEY_PROMOTION_AURORA_HELP',			'Double[ICON_MOVES]Movement [COLOR:255:230:85:255]on Snow[ENDCOLOR].');
			
INSERT INTO UnitPromotions 
			(Type,							Description,							Help,										Sound,				CannotBeChosen, LostWithUpgrade,	PortraitIndex,	IconAtlas,						PediaType,			PediaEntry) 
VALUES		('PROMOTION_KAILASH',			'TXT_KEY_PROMOTION_KAILASH',			'TXT_KEY_PROMOTION_KAILASH_HELP',			'AS2D_IF_LEVELUP',	1,				0,					12,				'PROMOTION_ATLAS_VP_03',		'PEDIA_CIVILIAN',	'TXT_KEY_PROMOTION_KAILASH'),
			('PROMOTION_ULURU',				'TXT_KEY_PROMOTION_ULURU',				'TXT_KEY_PROMOTION_ULURU_HELP',				'AS2D_IF_LEVELUP',	1,				0,					8,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_DIPLO',		'TXT_KEY_PROMOTION_ULURU'),
			('PROMOTION_SOLOMONS_MINES',	'TXT_KEY_PROMOTION_SOLOMONS_MINES',		'TXT_KEY_PROMOTION_SOLOMONS_MINES_HELP',	'AS2D_IF_LEVELUP',	1,				0,					4,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_CIVILIAN',	'TXT_KEY_PROMOTION_SOLOMONS_MINES'),
			('PROMOTION_BERMUDA_TRIANGLE',	'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE',	'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE_HELP',	'AS2D_IF_LEVELUP',	1,				0,					9,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SHARED',		'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE'),
			('PROMOTION_DALLOL',			'TXT_KEY_PROMOTION_DALLOL',				'TXT_KEY_PROMOTION_DALLOL_HELP',			'AS2D_IF_LEVELUP',	1,				0,					10,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SIEGE',		'TXT_KEY_PROMOTION_DALLOL'),
			('PROMOTION_CAUSEWAY',			'TXT_KEY_PROMOTION_CAUSEWAY',			'TXT_KEY_PROMOTION_CAUSEWAY_HELP',			'AS2D_IF_LEVELUP',	1,				0,					17,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_CIVILIAN',	'TXT_KEY_PROMOTION_CAUSEWAY'),
			('PROMOTION_MT_EVEREST',		'TXT_KEY_PROMOTION_MT_EVEREST',			'TXT_KEY_PROMOTION_MT_EVEREST_HELP',		'AS2D_IF_LEVELUP',	1,				0,					19,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SCOUTING',	'TXT_KEY_PROMOTION_MT_EVEREST'),
			('PROMOTION_HA_LONG',			'TXT_KEY_PROMOTION_HA_LONG',			'TXT_KEY_PROMOTION_HA_LONG_HELP',			'AS2D_IF_LEVELUP',	1,				0,					18,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_NAVAL',		'TXT_KEY_PROMOTION_HA_LONG'),
			('PROMOTION_AURORA',			'TXT_KEY_PROMOTION_AURORA',				'TXT_KEY_PROMOTION_AURORA_HELP',			'AS2D_IF_LEVELUP',	1,				0,					21,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SHARED',		'TXT_KEY_PROMOTION_AURORA');

UPDATE UnitPromotions SET DiploMissionInfluence = 10 WHERE Type = 'PROMOTION_ULURU';
UPDATE UnitPromotions SET WorkRateMod = 25 WHERE Type = 'PROMOTION_SOLOMONS_MINES';
UPDATE UnitPromotions SET ExtraNavalMovement = -3, PromotionDuration = 3 WHERE Type = 'PROMOTION_BERMUDA_TRIANGLE';
UPDATE UnitPromotions SET RangedAttackModifier = 10 WHERE Type = 'PROMOTION_DALLOL';
UPDATE UnitPromotions SET WorkRateMod = 20, MovesChange = 1 WHERE Type = 'PROMOTION_CAUSEWAY';
UPDATE UnitPromotions SET OpenDefense = 20, RoughDefense = 20 WHERE Type = 'PROMOTION_HA_LONG';

INSERT INTO UnitPromotions_Terrains
			(PromotionType,			TerrainType,	DoubleMove)
VALUES		('PROMOTION_KAILASH',	'TERRAIN_HILL',	1),
			('PROMOTION_AURORA',	'TERRAIN_SNOW',	1);

INSERT INTO UnitPromotions_YieldFromScouting
			(PromotionType,				YieldType,			Yield)
VALUES		('PROMOTION_MT_EVEREST',	'YIELD_TOURISM',	1);

INSERT INTO UnitPromotions_YieldFromKills
			(PromotionType,			YieldType,			Yield)
VALUES		('PROMOTION_HA_LONG',	'YIELD_CULTURE',	80);

DELETE FROM UnitPromotions_CivilianUnitType WHERE PromotionType = 'PROMOTION_SACRED_STEPS';

UPDATE UnitPromotions SET VisibilityChange = 1 WHERE Type = 'PROMOTION_ALTITUDE_TRAINING';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SCOUTING' WHERE type = 'PROMOTION_ALTITUDE_TRAINING';
UPDATE Language_en_US SET Text = '+1[ICON_VIEW_CITY]Sight. '||Text WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_ALTITUDE_TRAINING';

INSERT INTO UnitPromotions_UnitCombats
			(PromotionType,					UnitCombatType)
VALUES		('PROMOTION_KAILASH',			'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_ULURU',				'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_SOLOMONS_MINES',	'UNITCOMBAT_WORKER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_NAVALMELEE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_NAVALRANGED'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SUBMARINE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_CARRIER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_CARGO'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_WORKBOAT'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_MELEE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_RECON'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_ARCHER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_MOUNTED'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SIEGE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_GUN'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_ARMOR'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_INQUISITOR'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SETTLER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_WORKER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SPECIAL_PEOPLE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SPACESHIP_PART'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_ARCHAEOLOGIST'),
			('PROMOTION_DALLOL',			'UNITCOMBAT_SIEGE'),
			('PROMOTION_ALTITUDE_TRAINING',	'UNITCOMBAT_RECON'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_WORKER'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_WORKBOAT'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_SETTLER'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_SPECIAL_PEOPLE'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_SPACESHIP_PART'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_INQUISITOR'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_ARCHAEOLOGIST'),
			('PROMOTION_CAUSEWAY',			'UNITCOMBAT_ARCHAEOLOGIST'),
			('PROMOTION_MT_EVEREST',		'UNITCOMBAT_RECON'),
			('PROMOTION_HA_LONG',			'UNITCOMBAT_NAVALMELEE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_MELEE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_RECON'),
			('PROMOTION_AURORA',			'UNITCOMBAT_ARCHER'),
			('PROMOTION_AURORA',			'UNITCOMBAT_MOUNTED'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SIEGE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_GUN'),
			('PROMOTION_AURORA',			'UNITCOMBAT_ARMOR'),
			('PROMOTION_AURORA',			'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_AURORA',			'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_AURORA',			'UNITCOMBAT_INQUISITOR'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SETTLER'),
			('PROMOTION_AURORA',			'UNITCOMBAT_WORKER'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SPECIAL_PEOPLE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SPACESHIP_PART'),
			('PROMOTION_AURORA',			'UNITCOMBAT_ARCHAEOLOGIST');

UPDATE UnitPromotions SET FlagPromoOrder = 4, OrderPriority = 4 WHERE Type = 'PROMOTION_BERMUDA_TRIANGLE';
			
UPDATE UnitPromotions SET FlagPromoOrder = 70, OrderPriority = 70 WHERE Type = 'PROMOTION_EVERLASTING_YOUTH';
UPDATE UnitPromotions SET FlagPromoOrder = 71, OrderPriority = 71 WHERE Type = 'PROMOTION_HA_LONG';
UPDATE UnitPromotions SET FlagPromoOrder = 72, OrderPriority = 72 WHERE Type = 'PROMOTION_SOLOMONS_MINES';
UPDATE UnitPromotions SET FlagPromoOrder = 73, OrderPriority = 73 WHERE Type = 'PROMOTION_AURORA';

UPDATE UnitPromotions SET FlagPromoOrder = 250, OrderPriority = 250 WHERE Type = 'PROMOTION_DALLOL';
UPDATE UnitPromotions SET FlagPromoOrder = 251, OrderPriority = 251 WHERE Type = 'PROMOTION_ALTITUDE_TRAINING';

UPDATE UnitPromotions SET FlagPromoOrder = 252, OrderPriority = 252 WHERE Type = 'PROMOTION_SACRED_STEPS';
UPDATE UnitPromotions SET FlagPromoOrder = 253, OrderPriority = 253 WHERE Type = 'PROMOTION_KAILASH';
UPDATE UnitPromotions SET FlagPromoOrder = 254, OrderPriority = 254 WHERE Type = 'PROMOTION_ULURU';
UPDATE UnitPromotions SET FlagPromoOrder = 255, OrderPriority = 255 WHERE Type = 'PROMOTION_CAUSEWAY';
UPDATE UnitPromotions SET FlagPromoOrder = 256, OrderPriority = 256 WHERE Type = 'PROMOTION_MT_EVEREST';
--============================================--
-- GREAT_WORKS
--============================================--
INSERT INTO GreatWorks
			(Type,						Description,					GreatWorkClassType,	Audio,							Image,						Quote) 
VALUES		('GREAT_WORK_MT_PAEKTU',	'TXT_KEY_GREAT_WORK_MT_PAEKTU',	'GREAT_WORK_ART',	'AS2D_GREAT_ARTIST_ARTWORK',	'Great_Work_Mt_Paektu.dds',	NULL);

INSERT INTO Language_en_US 
			(Tag,									Text) 
VALUES		('TXT_KEY_GREAT_WORK_MT_PAEKTU',		'Kim Il-sung and Kim Jong-il standing at the peak of Mount Paektu');
--============================================--
-- BUILDINGS
--============================================--
INSERT INTO BuildingClasses 
			(Type,								Description,						DefaultBuilding)
VALUES		('BUILDINGCLASS_MT_PAEKTU',			'TXT_KEY_BUILDING_MT_PAEKTU',		'BUILDING_MT_PAEKTU'),
			('BUILDINGCLASS_SCUBA_RESORT',		'TXT_KEY_BUILDING_SCUBA_RESORT',	'BUILDING_SCUBA_RESORT'),
			('BUILDINGCLASS_BATHYSCAPHE_BAY',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY',	'BUILDING_BATHYSCAPHE_BAY'),
			('BUILDINGCLASS_OCEAN_FACILITY',	'TXT_KEY_BUILDING_OCEAN_FACILITY',	'BUILDING_OCEAN_FACILITY');

INSERT INTO Buildings
			(Type,							BuildingClass,						Description,						Civilopedia,								Help,										IconAtlas,							PortraitIndex,	PrereqTech,				Cost,	FaithCost,	NukeImmune, ConquestProb,	IsDummy)
VALUES		('BUILDING_MT_PAEKTU',			'BUILDINGCLASS_MT_PAEKTU',			'TXT_KEY_BUILDING_MT_PAEKTU',		'TXT_KEY_BUILDING_MT_PAEKTU_PEDIA',			'TXT_KEY_BUILDING_MT_PAEKTU_HELP',			'NATURAL_WONDERS_BUILDINGS_ATLAS',	0,				NULL,					-1,		0,			1,          100,			0),
			('BUILDING_SCUBA_RESORT',		'BUILDINGCLASS_SCUBA_RESORT',		'TXT_KEY_BUILDING_SCUBA_RESORT',	'TXT_KEY_BUILDING_SCUBA_RESORT_PEDIA',		'TXT_KEY_BUILDING_SCUBA_RESORT_HELP',		'NATURAL_WONDERS_BUILDINGS_ATLAS',	1,				'TECH_PLASTIC',			1000,	0,			0,          66,				0),
			('BUILDING_BATHYSCAPHE_BAY',	'BUILDINGCLASS_BATHYSCAPHE_BAY',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY_PEDIA',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY_HELP',	'NATURAL_WONDERS_BUILDINGS_ATLAS',	2,				'TECH_REFRIGERATION',   1000,	0,			0,          66,				0),
			('BUILDING_OCEAN_FACILITY',		'BUILDINGCLASS_OCEAN_FACILITY',		'TXT_KEY_BUILDING_OCEAN_FACILITY',	'TXT_KEY_BUILDING_OCEAN_FACILITY_PEDIA',	'TXT_KEY_BUILDING_OCEAN_FACILITY_HELP',		'NATURAL_WONDERS_BUILDINGS_ATLAS',	3,				'TECH_BIOLOGY',			1000,	0,			0,          66,				0);

UPDATE Buildings SET GreatWorkSlotType = 'GREAT_WORK_SLOT_ART_ARTIFACT', GreatWorkCount = 1, FreeGreatWork = 'GREAT_WORK_MT_PAEKTU', SpecialistType = 'SPECIALIST_MUSICIAN', GreatPeopleRateChange = 1 WHERE Type = 'BUILDING_MT_PAEKTU';
UPDATE Buildings SET Water = 1, MinAreaSize = 10, MutuallyExclusiveGroup = 137 WHERE Type = 'BUILDING_SCUBA_RESORT';
UPDATE Buildings SET Water = 1, MinAreaSize = 10, MutuallyExclusiveGroup = 137 WHERE Type = 'BUILDING_BATHYSCAPHE_BAY';
UPDATE Buildings SET Water = 1, MinAreaSize = 10, MutuallyExclusiveGroup = 137 WHERE Type = 'BUILDING_OCEAN_FACILITY';

INSERT INTO Language_en_US 
			(Tag,										Text) 
VALUES		('TXT_KEY_BUILDING_MT_PAEKTU',				'Altar of the Born under the Mountain'),
			('TXT_KEY_BUILDING_MT_PAEKTU_PEDIA',		'TODO'),
			('TXT_KEY_BUILDING_MT_PAEKTU_HELP',			''),
			('TXT_KEY_BUILDING_SCUBA_RESORT',			'Scuba Diving Resort'),
			('TXT_KEY_BUILDING_SCUBA_RESORT_PEDIA',		'TODO'),
			('TXT_KEY_BUILDING_SCUBA_RESORT_HELP',		''),
			('TXT_KEY_BUILDING_BATHYSCAPHE_BAY',		'Bathyscaphe Docking Bay'),
			('TXT_KEY_BUILDING_BATHYSCAPHE_BAY_PEDIA',	'TODO'),
			('TXT_KEY_BUILDING_BATHYSCAPHE_BAY_HELP',	''),
			('TXT_KEY_BUILDING_OCEAN_FACILITY',			'Deep Ocean Research Facility'),
			('TXT_KEY_BUILDING_OCEAN_FACILITY_PEDIA',	'TODO'),
			('TXT_KEY_BUILDING_OCEAN_FACILITY_HELP',	'');

INSERT INTO Building_YieldChanges 
			(BuildingType,					YieldType,					Yield) 
VALUES		('BUILDING_MT_PAEKTU',			'YIELD_FAITH',				3),
			('BUILDING_MT_PAEKTU',			'YIELD_GOLDEN_AGE_POINTS',	3),
			('BUILDING_SCUBA_RESORT',		'YIELD_GOLD',				2),
			('BUILDING_SCUBA_RESORT',		'YIELD_SCIENCE',			1),
			('BUILDING_SCUBA_RESORT',		'YIELD_TOURISM',			1),
			('BUILDING_BATHYSCAPHE_BAY',	'YIELD_PRODUCTION',			2),
			('BUILDING_BATHYSCAPHE_BAY',	'YIELD_SCIENCE',			2),
			('BUILDING_OCEAN_FACILITY',		'YIELD_SCIENCE',			5);

INSERT INTO Building_FeatureYieldChanges
			(BuildingType,				FeatureType,		YieldType,			Yield) 
VALUES		('BUILDING_SCUBA_RESORT',	'FEATURE_ATOLL',	'YIELD_GOLD',		1),
			('BUILDING_SCUBA_RESORT',	'FEATURE_ATOLL',	'YIELD_TOURISM',	1);

INSERT INTO Building_TerrainYieldChanges
			(BuildingType,				TerrainType,		YieldType,			Yield) 
VALUES		('BUILDING_SCUBA_RESORT',	'TERRAIN_OCEAN',	'YIELD_GOLD',		1),
			('BUILDING_SCUBA_RESORT',	'TERRAIN_OCEAN',	'YIELD_SCIENCE',	1),
			('BUILDING_OCEAN_FACILITY',	'TERRAIN_OCEAN',	'YIELD_FOOD',		1),
			('BUILDING_OCEAN_FACILITY',	'TERRAIN_OCEAN',	'YIELD_SCIENCE',	1);

INSERT INTO Building_UnitCombatProductionModifiers
			(BuildingType,					UnitCombatType,				Modifier) 
VALUES		('BUILDING_BATHYSCAPHE_BAY',	'UNITCOMBAT_SUBMARINE',		50);

INSERT INTO Building_ResourceYieldChanges	(BuildingType,				ResourceType,	YieldType,		Yield)
SELECT DISTINCT								'BUILDING_OCEAN_FACILITY',	Type,			'YIELD_FOOD',	1
FROM Resources WHERE SeaResource = 1 AND AnimalResource = 1;
--============================================--
-- DUMMY BUILDINGS
--============================================--
INSERT INTO BuildingClasses 
			(Type,									Description,								DefaultBuilding)
VALUES		('BUILDINGCLASS_DUMMY_JEJU_DO',			'TXT_KEY_BUILDING_DUMMY_JEJU_DO',			'BUILDING_DUMMY_JEJU_DO'),
			('BUILDINGCLASS_DUMMY_SALAR_A',			'TXT_KEY_BUILDING_DUMMY_SALAR_A',			'BUILDING_DUMMY_SALAR_A'),
			('BUILDINGCLASS_DUMMY_SALAR_B',			'TXT_KEY_BUILDING_DUMMY_SALAR_B',			'BUILDING_DUMMY_SALAR_B'),
			('BUILDINGCLASS_DUMMY_EL_DORADO',		'TXT_KEY_BUILDING_DUMMY_EL_DORADO',			'BUILDING_DUMMY_EL_DORADO'),
			('BUILDINGCLASS_DUMMY_POTOSI',			'TXT_KEY_BUILDING_DUMMY_POTOSI',			'BUILDING_DUMMY_POTOSI'),
			('BUILDINGCLASS_DUMMY_CRATER',			'TXT_KEY_BUILDING_DUMMY_CRATER',			'BUILDING_DUMMY_CRATER'),
			('BUILDINGCLASS_DUMMY_MESA',			'TXT_KEY_BUILDING_DUMMY_MESA',				'BUILDING_DUMMY_MESA'),
			('BUILDINGCLASS_DUMMY_SOLOMONS_MINES',	'TXT_KEY_BUILDING_DUMMY_SOLOMONS_MINES',	'BUILDING_DUMMY_SOLOMONS_MINES'),
			('BUILDINGCLASS_DUMMY_VOLCANO',			'TXT_KEY_BUILDING_DUMMY_VOLCANO',			'BUILDING_DUMMY_VOLCANO'),
			('BUILDINGCLASS_DUMMY_FUJI_1',			'TXT_KEY_BUILDING_DUMMY_FUJI',				'BUILDING_DUMMY_FUJI_1'),
			('BUILDINGCLASS_DUMMY_FUJI_2',			'TXT_KEY_BUILDING_DUMMY_FUJI',				'BUILDING_DUMMY_FUJI_2'),
			('BUILDINGCLASS_DUMMY_FUJI_3',			'TXT_KEY_BUILDING_DUMMY_FUJI',				'BUILDING_DUMMY_FUJI_3'),
			('BUILDINGCLASS_DUMMY_MT_SINAI',		'TXT_KEY_BUILDING_DUMMY_MT_SINAI',			'BUILDING_DUMMY_MT_SINAI'),
			('BUILDINGCLASS_DUMMY_GEYSER',			'TXT_KEY_BUILDING_DUMMY_GEYSER',			'BUILDING_DUMMY_GEYSER'),
			('BUILDINGCLASS_DUMMY_MT_EVEREST',		'TXT_KEY_BUILDING_DUMMY_MT_EVEREST',		'BUILDING_DUMMY_MT_EVEREST'),
			('BUILDINGCLASS_DUMMY_NEW_REEF_A',		'TXT_KEY_BUILDING_DUMMY_REEF',				'BUILDING_DUMMY_NEW_REEF_A'),
			('BUILDINGCLASS_DUMMY_NEW_REEF_B',		'TXT_KEY_BUILDING_DUMMY_REEF',				'BUILDING_DUMMY_NEW_REEF_B'),
			('BUILDINGCLASS_DUMMY_NEW_REEF_C',		'TXT_KEY_BUILDING_DUMMY_REEF',				'BUILDING_DUMMY_NEW_REEF_C'),
			('BUILDINGCLASS_DUMMY_GIBRALTAR',		'TXT_KEY_BUILDING_DUMMY_GIBRALTAR',			'BUILDING_DUMMY_GIBRALTAR'),
			('BUILDINGCLASS_DUMMY_LAKE_VICTORIA',	'TXT_KEY_BUILDING_DUMMY_LAKE_VICTORIA',		'BUILDING_DUMMY_LAKE_VICTORIA'),
			('BUILDINGCLASS_DUMMY_CAUSEWAY_A',		'TXT_KEY_BUILDING_DUMMY_CAUSEWAY_A',		'BUILDING_DUMMY_CAUSEWAY_A'),
			('BUILDINGCLASS_DUMMY_CAUSEWAY_B',		'TXT_KEY_BUILDING_DUMMY_CAUSEWAY_B',		'BUILDING_DUMMY_CAUSEWAY_B'),
			('BUILDINGCLASS_DUMMY_RETBA',			'TXT_KEY_BUILDING_DUMMY_RETBA',				'BUILDING_DUMMY_RETBA'),
			('BUILDINGCLASS_DUMMY_LUMI_BAY',		'TXT_KEY_BUILDING_DUMMY_LUMI_BAY',			'BUILDING_DUMMY_LUMI_BAY'),
			('BUILDINGCLASS_DUMMY_DALLOL',			'TXT_KEY_BUILDING_DUMMY_DALLOL',			'BUILDING_DUMMY_DALLOL'),
			('BUILDINGCLASS_DUMMY_EYE_OF_SAHARA_A',	'TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',		'BUILDING_DUMMY_EYE_OF_SAHARA_A'),
			('BUILDINGCLASS_DUMMY_EYE_OF_SAHARA_B',	'TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',		'BUILDING_DUMMY_EYE_OF_SAHARA_B'),
			('BUILDINGCLASS_DUMMY_EYE_OF_SAHARA_C',	'TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',		'BUILDING_DUMMY_EYE_OF_SAHARA_C'),
			('BUILDINGCLASS_DUMMY_MT_KAILASH',		'TXT_KEY_BUILDING_DUMMY_MT_KAILASH',		'BUILDING_DUMMY_MT_KAILASH'),
			('BUILDINGCLASS_DUMMY_KILIMANJARO',		'TXT_KEY_BUILDING_DUMMY_KILIMANJARO',		'BUILDING_DUMMY_KILIMANJARO'),
			('BUILDINGCLASS_DUMMY_BLUE_HOLE',		'TXT_KEY_BUILDING_DUMMY_BLUE_HOLE',			'BUILDING_DUMMY_BLUE_HOLE'),
			('BUILDINGCLASS_DUMMY_GALAPAGOS_A',		'TXT_KEY_BUILDING_DUMMY_GALAPAGOS_A',		'BUILDING_DUMMY_GALAPAGOS_A'),
			('BUILDINGCLASS_DUMMY_GALAPAGOS_B',		'TXT_KEY_BUILDING_DUMMY_GALAPAGOS_B',		'BUILDING_DUMMY_GALAPAGOS_B'),
			('BUILDINGCLASS_DUMMY_HA_LONG_A',		'TXT_KEY_BUILDING_DUMMY_HA_LONG_A',			'BUILDING_DUMMY_HA_LONG_A'),
			('BUILDINGCLASS_DUMMY_HA_LONG_B',		'TXT_KEY_BUILDING_DUMMY_HA_LONG_B',			'BUILDING_DUMMY_HA_LONG_B'),
			('BUILDINGCLASS_DUMMY_AURORA_A',		'TXT_KEY_BUILDING_DUMMY_AURORA',			'BUILDING_DUMMY_AURORA_A'),
			('BUILDINGCLASS_DUMMY_AURORA_B',		'TXT_KEY_BUILDING_DUMMY_AURORA',			'BUILDING_DUMMY_AURORA_B'),
			('BUILDINGCLASS_DUMMY_AURORA_C',		'TXT_KEY_BUILDING_DUMMY_AURORA',			'BUILDING_DUMMY_AURORA_C'),
			('BUILDINGCLASS_DUMMY_ARCH',			'TXT_KEY_BUILDING_DUMMY_ARCH',				'BUILDING_DUMMY_ARCH'),
			('BUILDINGCLASS_DUMMY_MARIANA_A',		'TXT_KEY_BUILDING_DUMMY_MARIANA',			'BUILDING_DUMMY_MARIANA_A'),
			('BUILDINGCLASS_DUMMY_MARIANA_B',		'TXT_KEY_BUILDING_DUMMY_MARIANA',			'BUILDING_DUMMY_MARIANA_B'),
			('BUILDINGCLASS_DUMMY_MARIANA_C',		'TXT_KEY_BUILDING_DUMMY_MARIANA',			'BUILDING_DUMMY_MARIANA_C');

INSERT INTO Buildings
			(Type,								BuildingClass,							Description,								PrereqTech, Cost, FaithCost, GreatWorkCount , NukeImmune, ConquestProb, IsDummy)
VALUES		-- dummy building with direct placement
			('BUILDING_DUMMY_MESA',				'BUILDINGCLASS_DUMMY_MESA',				'TXT_KEY_BUILDING_DUMMY_MESA',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_FUJI_1',			'BUILDINGCLASS_DUMMY_FUJI_1',			'TXT_KEY_BUILDING_DUMMY_FUJI',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_FUJI_2',			'BUILDINGCLASS_DUMMY_FUJI_2',			'TXT_KEY_BUILDING_DUMMY_FUJI',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_FUJI_3',			'BUILDINGCLASS_DUMMY_FUJI_3',			'TXT_KEY_BUILDING_DUMMY_FUJI',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_JEJU_DO',			'BUILDINGCLASS_DUMMY_JEJU_DO',			'TXT_KEY_BUILDING_DUMMY_JEJU_DO',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_ARCH',				'BUILDINGCLASS_DUMMY_ARCH',				'TXT_KEY_BUILDING_DUMMY_ARCH',				NULL,       -1,   -1,        -1,              1,          0,			1),
			-- dummy buildings in capital
			('BUILDING_DUMMY_CRATER',			'BUILDINGCLASS_DUMMY_CRATER',			'TXT_KEY_BUILDING_DUMMY_CRATER',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_DUMMY_SALAR_A',			'TXT_KEY_BUILDING_DUMMY_SALAR_A',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_DUMMY_SALAR_B',			'TXT_KEY_BUILDING_DUMMY_SALAR_B',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_EL_DORADO',		'BUILDINGCLASS_DUMMY_EL_DORADO',		'TXT_KEY_BUILDING_DUMMY_EL_DORADO',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_POTOSI',			'BUILDINGCLASS_DUMMY_POTOSI',			'TXT_KEY_BUILDING_DUMMY_POTOSI',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_SOLOMONS_MINES',	'BUILDINGCLASS_DUMMY_SOLOMONS_MINES',	'TXT_KEY_BUILDING_DUMMY_SOLOMONS_MINES',	NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_VOLCANO',			'BUILDINGCLASS_DUMMY_VOLCANO',			'TXT_KEY_BUILDING_DUMMY_VOLCANO',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_MT_SINAI',			'BUILDINGCLASS_DUMMY_MT_SINAI',			'TXT_KEY_BUILDING_DUMMY_MT_SINAI',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_GEYSER',			'BUILDINGCLASS_DUMMY_GEYSER',			'TXT_KEY_BUILDING_DUMMY_GEYSER',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_MT_EVEREST',		'BUILDINGCLASS_DUMMY_MT_EVEREST',		'TXT_KEY_BUILDING_DUMMY_MT_EVEREST',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_NEW_REEF_A',		'BUILDINGCLASS_DUMMY_NEW_REEF_A',		'TXT_KEY_BUILDING_DUMMY_REEF',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_NEW_REEF_B',		'BUILDINGCLASS_DUMMY_NEW_REEF_B',		'TXT_KEY_BUILDING_DUMMY_REEF',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_NEW_REEF_C',		'BUILDINGCLASS_DUMMY_NEW_REEF_C',		'TXT_KEY_BUILDING_DUMMY_REEF',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_GIBRALTAR',		'BUILDINGCLASS_DUMMY_GIBRALTAR',		'TXT_KEY_BUILDING_DUMMY_GIBRALTAR',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_LAKE_VICTORIA',	'BUILDINGCLASS_DUMMY_LAKE_VICTORIA',	'TXT_KEY_BUILDING_DUMMY_LAKE_VICTORIA',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_CAUSEWAY_A',		'BUILDINGCLASS_DUMMY_CAUSEWAY_A',		'TXT_KEY_BUILDING_DUMMY_CAUSEWAY_A',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_CAUSEWAY_B',		'BUILDINGCLASS_DUMMY_CAUSEWAY_B',		'TXT_KEY_BUILDING_DUMMY_CAUSEWAY_B',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_RETBA',			'BUILDINGCLASS_DUMMY_RETBA',			'TXT_KEY_BUILDING_DUMMY_RETBA',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_LUMI_BAY',			'BUILDINGCLASS_DUMMY_LUMI_BAY',			'TXT_KEY_BUILDING_DUMMY_LUMI_BAY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_DALLOL',			'BUILDINGCLASS_DUMMY_DALLOL',			'TXT_KEY_BUILDING_DUMMY_DALLOL',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_EYE_OF_SAHARA_A',	'BUILDINGCLASS_DUMMY_EYE_OF_SAHARA_A',	'TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_EYE_OF_SAHARA_B',	'BUILDINGCLASS_DUMMY_EYE_OF_SAHARA_B',	'TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_EYE_OF_SAHARA_C',	'BUILDINGCLASS_DUMMY_EYE_OF_SAHARA_C',	'TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_MT_KAILASH',		'BUILDINGCLASS_DUMMY_MT_KAILASH',		'TXT_KEY_BUILDING_DUMMY_MT_KAILASH',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_KILIMANJARO',		'BUILDINGCLASS_DUMMY_KILIMANJARO',		'TXT_KEY_BUILDING_DUMMY_KILIMANJARO',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_BLUE_HOLE',		'BUILDINGCLASS_DUMMY_BLUE_HOLE',		'TXT_KEY_BUILDING_DUMMY_BLUE_HOLE',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_GALAPAGOS_A',		'BUILDINGCLASS_DUMMY_GALAPAGOS_A',		'TXT_KEY_BUILDING_DUMMY_GALAPAGOS_A',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_GALAPAGOS_B',		'BUILDINGCLASS_DUMMY_GALAPAGOS_B',		'TXT_KEY_BUILDING_DUMMY_GALAPAGOS_B',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_HA_LONG_A',		'BUILDINGCLASS_DUMMY_HA_LONG_A',		'TXT_KEY_BUILDING_DUMMY_HA_LONG_A',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_HA_LONG_B',		'BUILDINGCLASS_DUMMY_HA_LONG_B',		'TXT_KEY_BUILDING_DUMMY_HA_LONG_B',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_AURORA_A',			'BUILDINGCLASS_DUMMY_AURORA_A',			'TXT_KEY_BUILDING_DUMMY_AURORA',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_AURORA_B',			'BUILDINGCLASS_DUMMY_AURORA_B',			'TXT_KEY_BUILDING_DUMMY_AURORA',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_AURORA_C',			'BUILDINGCLASS_DUMMY_AURORA_C',			'TXT_KEY_BUILDING_DUMMY_AURORA',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_MARIANA_A',		'BUILDINGCLASS_DUMMY_MARIANA_A',		'TXT_KEY_BUILDING_DUMMY_MARIANA',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_MARIANA_B',		'BUILDINGCLASS_DUMMY_MARIANA_B',		'TXT_KEY_BUILDING_DUMMY_MARIANA',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DUMMY_MARIANA_C',		'BUILDINGCLASS_DUMMY_MARIANA_C',		'TXT_KEY_BUILDING_DUMMY_MARIANA',			NULL,       -1,   -1,        -1,              1,          0,			1);
			
INSERT INTO Language_en_US 
			(Tag,										Text) 
VALUES		('TXT_KEY_BUILDING_DUMMY_SALAR_A',			'MW-NW Salar de Uyuni A'),
			('TXT_KEY_BUILDING_DUMMY_SALAR_B',			'MW-NW Salar de Uyuni B'),
			('TXT_KEY_BUILDING_DUMMY_EL_DORADO',		'MW-NW El Dorado'),
			('TXT_KEY_BUILDING_DUMMY_POTOSI',			'MW-NW Cerro de Potosi'),
			('TXT_KEY_BUILDING_DUMMY_CRATER',			'MW-NW Barringer Crater'),
			('TXT_KEY_BUILDING_DUMMY_MESA',				'MW-NW Grand Mesa'),
			('TXT_KEY_BUILDING_DUMMY_SOLOMONS_MINES',	'MW-NW King Solomon''s Mines'),
			('TXT_KEY_BUILDING_DUMMY_VOLCANO',			'MW-NW Krakatoa'),
			('TXT_KEY_BUILDING_DUMMY_FUJI',				'MW-NW Mt. Fuji'),
			('TXT_KEY_BUILDING_DUMMY_MT_SINAI',			'MW-NW Mt. Sinai'),
			('TXT_KEY_BUILDING_DUMMY_GEYSER',			'MW-NW Old Faithful'),
			('TXT_KEY_BUILDING_DUMMY_MT_EVEREST',		'MW-NW Mt. Everest'),
			('TXT_KEY_BUILDING_DUMMY_REEF',				'MW-NW Great Barrier Reef'),
			('TXT_KEY_BUILDING_DUMMY_GIBRALTAR',		'MW-NW Rock of Gibraltar'),
			('TXT_KEY_BUILDING_DUMMY_LAKE_VICTORIA',	'MW-NW Lake Victoria'),
			('TXT_KEY_BUILDING_DUMMY_CAUSEWAY_A',		'MW-NW Giant''s Causeway A'),
			('TXT_KEY_BUILDING_DUMMY_CAUSEWAY_B',		'MW-NW Giant''s Causeway B'),
			('TXT_KEY_BUILDING_DUMMY_RETBA',			'MW-NW Lake Retba'),
			('TXT_KEY_BUILDING_DUMMY_LUMI_BAY',			'MW-NW Bioluminescent Bay'),
			('TXT_KEY_BUILDING_DUMMY_DALLOL',			'MW-NW Dallol'),
			('TXT_KEY_BUILDING_DUMMY_EYE_OF_SAHARA',	'MW-NW Eye of the Sahara'),
			('TXT_KEY_BUILDING_DUMMY_MT_KAILASH',		'MW-NW Mt. Kailash'),
			('TXT_KEY_BUILDING_DUMMY_KILIMANJARO',		'MW-NW Mt. Kilimanjaro'),
			('TXT_KEY_BUILDING_DUMMY_BLUE_HOLE',		'MW-NW Great Blue Hole'),
			('TXT_KEY_BUILDING_DUMMY_GALAPAGOS_A',		'MW-NW Galapagos A'),
			('TXT_KEY_BUILDING_DUMMY_GALAPAGOS_B',		'MW-NW Galapagos B'),
			('TXT_KEY_BUILDING_DUMMY_HA_LONG_A',		'MW-NW Ha Long Bay A'),
			('TXT_KEY_BUILDING_DUMMY_HA_LONG_B',		'MW-NW Ha Long Bay B'),
			('TXT_KEY_BUILDING_DUMMY_AURORA',			'MW-NW Aurora'),
			('TXT_KEY_BUILDING_DUMMY_JEJU_DO',			'MW-NW Seongsan Ilchulbong'),
			('TXT_KEY_BUILDING_DUMMY_ARCH',				'MW-NW Delicate Arch'),
			('TXT_KEY_BUILDING_DUMMY_MARIANA',			'MW-NW Mariana Trench');

UPDATE Buildings SET SpecialistType = 'SPECIALIST_ARTIST', GreatPeopleRateChange = 3 WHERE Type = 'BUILDING_DUMMY_FUJI_1';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_WRITER', GreatPeopleRateChange = 2 WHERE Type = 'BUILDING_DUMMY_FUJI_2';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_MUSICIAN', GreatPeopleRateChange = 1 WHERE Type = 'BUILDING_DUMMY_FUJI_3';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_ARTIST', GreatPeopleRateChange = 2 WHERE Type = 'BUILDING_DUMMY_JEJU_DO';
UPDATE Buildings SET EmpireSizeModifierReductionGlobal = -10 WHERE Type = 'BUILDING_DUMMY_GEYSER';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_SCIENTIST', GreatPeopleRateChange = 2 WHERE Type = 'BUILDING_DUMMY_VOLCANO';
UPDATE Buildings SET GlobalSpaceProductionModifier = 20 WHERE Type = 'BUILDING_DUMMY_CRATER';
UPDATE Buildings SET NumTradeRouteBonus = 1 WHERE Type = 'BUILDING_DUMMY_POTOSI';
UPDATE Buildings SET GlobalDefenseMod = 5, ExtraLeagueVotes = 8 WHERE Type = 'BUILDING_DUMMY_GIBRALTAR';
UPDATE Buildings SET CitySupplyFlatGlobal = 1 WHERE Type = 'BUILDING_DUMMY_MESA';
UPDATE Buildings SET AllowsFoodTradeRoutesGlobal = 1 WHERE Type = 'BUILDING_DUMMY_LAKE_VICTORIA';
UPDATE Buildings SET GlobalLandmarksTourismPercent = 6 WHERE Type = 'BUILDING_DUMMY_CAUSEWAY_A';
UPDATE Buildings SET GlobalLandmarksTourismPercent = 14 WHERE Type = 'BUILDING_DUMMY_CAUSEWAY_B';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_CONSTRUCTION' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_A';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_A';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_SATELLITES' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_A';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_CONSTRUCTION' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_B';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_B';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_SATELLITES' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_B';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_CONSTRUCTION' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_C';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_C';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_SATELLITES' WHERE Type = 'BUILDING_DUMMY_EYE_OF_SAHARA_C';
UPDATE Buildings SET CityConnectionTradeRouteModifier = 20 WHERE Type = 'BUILDING_DUMMY_ARCH';


INSERT INTO Building_ResourceQuantity
			(BuildingType,				ResourceType,			Quantity) 
VALUES		('BUILDING_DUMMY_DALLOL',	'RESOURCE_SYLVITE',		1);

INSERT INTO Building_GreatWorkYieldChanges
			(BuildingType,				YieldType,					Yield) 
VALUES		('BUILDING_DUMMY_MT_SINAI',	'YIELD_FAITH',				1),
			('BUILDING_DUMMY_MT_SINAI',	'YIELD_GOLDEN_AGE_POINTS',	1);

INSERT INTO Building_ImprovementYieldChangesGlobal
			(BuildingType,						ImprovementType,				YieldType,						Yield) 
VALUES		('BUILDING_DUMMY_MT_SINAI',			'IMPROVEMENT_HOLY_SITE',		'YIELD_FAITH',					1),
			('BUILDING_DUMMY_MT_SINAI',			'IMPROVEMENT_HOLY_SITE',		'YIELD_GOLDEN_AGE_POINTS',		1),
			('BUILDING_DUMMY_NEW_REEF_B',		'IMPROVEMENT_FISHING_BOATS',	'YIELD_FOOD',					1),
			('BUILDING_DUMMY_NEW_REEF_C',		'IMPROVEMENT_FISHING_BOATS',	'YIELD_FOOD',					1),
			('BUILDING_DUMMY_SOLOMONS_MINES',	'IMPROVEMENT_MINE',				'YIELD_GOLDEN_AGE_POINTS',		1);
			
INSERT INTO Building_ResourceYieldChangesGlobal
			(BuildingType,					ResourceType,				YieldType,			Yield) 
VALUES		('BUILDING_DUMMY_EL_DORADO',	'RESOURCE_GOLD',			'YIELD_FAITH',		1),
			('BUILDING_DUMMY_KILIMANJARO',	'RESOURCE_IVORY',			'YIELD_CULTURE',	1),
			('BUILDING_DUMMY_LUMI_BAY',		'RESOURCE_FISH',			'YIELD_SCIENCE',	1),
			('BUILDING_DUMMY_LUMI_BAY',		'RESOURCE_TROPICAL_FISH',	'YIELD_SCIENCE',	1),
			('BUILDING_DUMMY_POTOSI',		'RESOURCE_SILVER',			'YIELD_SCIENCE',	1);

INSERT INTO Building_ResourceYieldChangesGlobal (BuildingType,					ResourceType,	YieldType,			Yield)
SELECT DISTINCT									'BUILDING_DUMMY_NEW_REEF_A',	Type,			'YIELD_SCIENCE',	1
FROM Resources WHERE ResourceClassType = 'RESOURCECLASS_LUXURY' and SeaResource = 1;

INSERT INTO Building_TechEnhancedYieldChanges
			(BuildingType,						YieldType,			Yield) 
VALUES		('BUILDING_DUMMY_EYE_OF_SAHARA_A',	'YIELD_CULTURE',	1),
			('BUILDING_DUMMY_EYE_OF_SAHARA_A',	'YIELD_TOURISM',	2),
			('BUILDING_DUMMY_EYE_OF_SAHARA_A',	'YIELD_TOURISM',	5),
			('BUILDING_DUMMY_EYE_OF_SAHARA_B',	'YIELD_CULTURE',	1),
			('BUILDING_DUMMY_EYE_OF_SAHARA_B',	'YIELD_TOURISM',	2),
			('BUILDING_DUMMY_EYE_OF_SAHARA_B',	'YIELD_TOURISM',	5),
			('BUILDING_DUMMY_EYE_OF_SAHARA_C',	'YIELD_CULTURE',	1),
			('BUILDING_DUMMY_EYE_OF_SAHARA_C',	'YIELD_TOURISM',	2),
			('BUILDING_DUMMY_EYE_OF_SAHARA_C',	'YIELD_TOURISM',	5);

INSERT INTO Building_SpecialistYieldChanges
			(BuildingType,				SpecialistType,			YieldType,			Yield) 
VALUES		('BUILDING_DUMMY_VOLCANO',	'SPECIALIST_SCIENTIST',	'YIELD_FOOD',		1),
			('BUILDING_DUMMY_VOLCANO',	'SPECIALIST_SCIENTIST',	'YIELD_SCIENCE',	1),
			('BUILDING_DUMMY_GEYSER',	'SPECIALIST_ENGINEER',	'YIELD_SCIENCE',	1);

INSERT INTO Building_BuildingClassYieldChanges
			(BuildingType,						BuildingClassType,				YieldType,			YieldChange) 
VALUES		('BUILDING_DUMMY_MT_KAILASH',		'BUILDINGCLASS_MONUMENT',		'YIELD_FAITH',		1),
			('BUILDING_DUMMY_MT_KAILASH',		'BUILDINGCLASS_TEMPLE',			'YIELD_FAITH',		1),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_FACTORY',		'YIELD_PRODUCTION',	2),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_SOLAR_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_NUCLEAR_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_WIND_PLANT',		'YIELD_PRODUCTION',	2),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_HYDRO_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_DUMMY_SALAR_A',			'BUILDINGCLASS_TIDAL_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_FACTORY',		'YIELD_PRODUCTION',	1),
			('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_SOLAR_PLANT',	'YIELD_PRODUCTION',	1),
			('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_NUCLEAR_PLANT',	'YIELD_PRODUCTION',	1),
			('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_WIND_PLANT',		'YIELD_PRODUCTION',	1),
			('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_HYDRO_PLANT',	'YIELD_PRODUCTION',	1),
            ('BUILDING_DUMMY_SALAR_B',			'BUILDINGCLASS_TIDAL_PLANT',	'YIELD_PRODUCTION',	1),
			('BUILDING_DUMMY_GALAPAGOS_A',		'BUILDINGCLASS_WRITERS_GUILD',	'YIELD_SCIENCE',	4),
			('BUILDING_DUMMY_GALAPAGOS_B',		'BUILDINGCLASS_WRITERS_GUILD',	'YIELD_SCIENCE',	2);

INSERT INTO Building_HurryModifiers
			(BuildingType,						HurryType,		HurryCostModifier) 
VALUES		('BUILDING_DUMMY_LAKE_VICTORIA',	'HURRY_GOLD',	-10);

INSERT INTO Building_GlobalYieldModifiers
			(BuildingType,						YieldType,			Yield) 
VALUES		('BUILDING_DUMMY_MT_EVEREST',		'YIELD_TOURISM',	5),
			('BUILDING_DUMMY_VOLCANO',			'YIELD_SCIENCE',	5),
			('BUILDING_DUMMY_RETBA',			'YIELD_FOOD',		5);
			
INSERT INTO Building_InstantYield
			(BuildingType,				YieldType,		Yield) 
VALUES		('BUILDING_DUMMY_MT_SINAI',	'YIELD_FAITH',	50);

INSERT INTO Building_YieldFromTech
			(BuildingType,				YieldType,					Yield) 
VALUES		('BUILDING_DUMMY_CRATER',	'YIELD_GOLDEN_AGE_POINTS',	10);

INSERT INTO Building_YieldFromGoldenAgeStart
			(BuildingType,					YieldType,			Yield) 
VALUES		('BUILDING_DUMMY_MARIANA_A',	'YIELD_SCIENCE',	10),
			('BUILDING_DUMMY_MARIANA_B',	'YIELD_SCIENCE',	10),
			('BUILDING_DUMMY_MARIANA_C',	'YIELD_SCIENCE',	10);

INSERT INTO Building_YieldFromDeath
			(BuildingType,				YieldType,		Yield) 
VALUES		('BUILDING_DUMMY_AURORA_A',	'YIELD_FAITH',	2),
			('BUILDING_DUMMY_AURORA_B',	'YIELD_FAITH',	2),
			('BUILDING_DUMMY_AURORA_C',	'YIELD_FAITH',	2);

INSERT INTO Building_YieldFromYieldPercentGlobal
			(BuildingType,				YieldOut,			YieldIn,		Value) 
VALUES		('BUILDING_DUMMY_AURORA_A',	'YIELD_SCIENCE',	'YIELD_FAITH',	3),
			('BUILDING_DUMMY_AURORA_B',	'YIELD_SCIENCE',	'YIELD_FAITH',	3),
			('BUILDING_DUMMY_AURORA_C',	'YIELD_SCIENCE',	'YIELD_FAITH',	3);

INSERT INTO Building_YieldFromInternalTREnd
			(BuildingType,				YieldType,				Yield) 
VALUES		('BUILDING_DUMMY_ARCH',		'YIELD_GOLD',			40),
			('BUILDING_DUMMY_ARCH',		'YIELD_CULTURE',		15);

INSERT INTO Building_YieldFromGPBirthScaledWithArtistBulb
			(BuildingType,				YieldType,		Yield) 
VALUES		('BUILDING_DUMMY_JEJU_DO',	'YIELD_GOLD',	25);
--============================================--
-- POLICIES
--============================================--
INSERT INTO Policies 
			(Type,							Description)
VALUES		('POLICY_DUMMY_RETBA', 			'TXT_KEY_POLICY_DUMMY_RETBA'),
			('POLICY_DUMMY_LUMI_BAY', 		'TXT_KEY_POLICY_DUMMY_LUMI_BAY'),
			('POLICY_DUMMY_MESA',			'TXT_KEY_POLICY_DUMMY_MESA'),
			('POLICY_DUMMY_HA_LONG_A', 		'TXT_KEY_POLICY_DUMMY_HA_LONG_A'),
			('POLICY_DUMMY_HA_LONG_B', 		'TXT_KEY_POLICY_DUMMY_HA_LONG_B'),
			('POLICY_DUMMY_ZHANGJIAJIE', 	'TXT_KEY_POLICY_DUMMY_ZHANGJIAJIE'),
			('POLICY_DUMMY_ULURU', 			'TXT_KEY_POLICY_DUMMY_ULURU'),
			('POLICY_DUMMY_MARIANA_A', 		'TXT_KEY_POLICY_DUMMY_MARIANA'),
			('POLICY_DUMMY_MARIANA_B', 		'TXT_KEY_POLICY_DUMMY_MARIANA'),
			('POLICY_DUMMY_MARIANA_C', 		'TXT_KEY_POLICY_DUMMY_MARIANA'),
			('POLICY_DUMMY_DANXIA_A', 		'TXT_KEY_POLICY_DUMMY_DANXIA'),
			('POLICY_DUMMY_DANXIA_B', 		'TXT_KEY_POLICY_DUMMY_DANXIA');
			
INSERT INTO Language_en_US 
			(Tag,									Text) 
VALUES		('TXT_KEY_POLICY_DUMMY_RETBA',			'Lake Retba'),
			('TXT_KEY_POLICY_DUMMY_LUMI_BAY',		'Bioluminescent Bay'),
			('TXT_KEY_POLICY_DUMMY_MESA',			'Grand Mesa'),
			('TXT_KEY_POLICY_DUMMY_HA_LONG_A',		'Ha Long Bay A'),
			('TXT_KEY_POLICY_DUMMY_HA_LONG_B',		'Ha Long Bay B'),
			('TXT_KEY_POLICY_DUMMY_ZHANGJIAJIE',	'Zhangjiajie'),
			('TXT_KEY_POLICY_DUMMY_ULURU',			'Uluru'),
			('TXT_KEY_POLICY_DUMMY_MARIANA',		'Mariana Trench'),
			('TXT_KEY_POLICY_DUMMY_DANXIA',			'Zhangye Danxia');

INSERT INTO Policy_WLTKDYieldMod 
			(PolicyType, 			YieldType, 		Yield)
VALUES 		('POLICY_DUMMY_RETBA', 	'YIELD_FOOD', 	10);

INSERT INTO Policy_YieldFromBirth 
			(PolicyType, 			YieldType, 			Yield)
VALUES 		('POLICY_DUMMY_RETBA', 	'YIELD_TOURISM', 	15);

INSERT INTO Policy_UnitCombatProductionModifiers
			(PolicyType, 				UnitCombatType, 			ProductionModifier)
VALUES 		('POLICY_DUMMY_MESA', 		'UNITCOMBAT_MOUNTED', 		20),
			('POLICY_DUMMY_HA_LONG_A', 	'UNITCOMBAT_NAVALMELEE', 	5),
			('POLICY_DUMMY_HA_LONG_B', 	'UNITCOMBAT_NAVALMELEE', 	5),
			('POLICY_DUMMY_ULURU',		'UNITCOMBAT_DIPLOMACY',		20);

INSERT INTO Policy_ArtifactYieldChanges
			(PolicyType, 				YieldType, 			Yield)
VALUES 		('POLICY_DUMMY_HA_LONG_B', 	'YIELD_CULTURE', 	1);

INSERT INTO Policy_YieldGPExpend
			(PolicyType, 					YieldType, 			Yield)
VALUES 		('POLICY_DUMMY_ZHANGJIAJIE', 	'YIELD_TOURISM', 	50);

INSERT INTO Policy_ArtYieldChanges
			(PolicyType, 					YieldType, 					Yield)
VALUES 		('POLICY_DUMMY_ZHANGJIAJIE', 	'YIELD_GOLDEN_AGE_POINTS', 	2),
			('POLICY_DUMMY_DANXIA_A', 		'YIELD_FAITH', 				2),
			('POLICY_DUMMY_DANXIA_B', 		'YIELD_FAITH', 				2);

INSERT INTO Policy_LitYieldChanges
			(PolicyType, 					YieldType, 					Yield)
VALUES 		('POLICY_DUMMY_ZHANGJIAJIE', 	'YIELD_GOLDEN_AGE_POINTS', 	2);

INSERT INTO Policy_MusicYieldChanges
			(PolicyType, 					YieldType, 					Yield)
VALUES 		('POLICY_DUMMY_ZHANGJIAJIE', 	'YIELD_GOLDEN_AGE_POINTS', 	2);

INSERT INTO Policy_GoldenAgeGreatPersonRateModifier
			(PolicyType, 					GreatPersonType, 			Modifier)
VALUES 		('POLICY_DUMMY_DANXIA_A', 		'GREATPERSON_ARTIST', 		3),
			('POLICY_DUMMY_DANXIA_A', 		'GREATPERSON_SCIENTIST', 	3),
			('POLICY_DUMMY_DANXIA_B', 		'GREATPERSON_ARTIST', 		3),
			('POLICY_DUMMY_DANXIA_B', 		'GREATPERSON_SCIENTIST', 	3);

INSERT INTO Policy_UnitCombatFreeExperiences
			(PolicyType, 					UnitCombatType, 			FreeExperience)
VALUES 		('POLICY_DUMMY_MARIANA_A', 		'UNITCOMBAT_SUBMARINE', 	7),
	 		('POLICY_DUMMY_MARIANA_B', 		'UNITCOMBAT_SUBMARINE', 	7),
	 		('POLICY_DUMMY_MARIANA_C', 		'UNITCOMBAT_SUBMARINE', 	7);

INSERT INTO Policy_TourismOnUnitCreation	(PolicyType,				UnitClassType,	Tourism)
SELECT DISTINCT								'POLICY_DUMMY_LUMI_BAY',	Class,			25
FROM Units WHERE CombatClass in ('UNITCOMBAT_SETTLER', 'UNITCOMBAT_WORKER', 'UNITCOMBAT_WORKBOAT', 'UNITCOMBAT_CARGO', 'UNITCOMBAT_CARAVAN', 'UNITCOMBAT_INQUISITOR', 'UNITCOMBAT_MISSIONARY', 'UNITCOMBAT_DIPLOMACY', 'UNITCOMBAT_SPECIAL_PEOPLE', 'UNITCOMBAT_SPACESHIP_PART', 'UNITCOMBAT_ARCHAEOLOGIST');
--============================================--
-- IMPROVEMENTS
--============================================--
INSERT INTO Improvement_Yields 
			(ImprovementType,							YieldType,			Yield)
SELECT		'IMPROVEMENT_FISHING_BOATS_GBH', 			YieldType,			Yield
FROM Improvement_Yields WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Belief_ImprovementYieldChanges 
			(BeliefType,	ImprovementType,					YieldType,		Yield)
SELECT		BeliefType,		'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Belief_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Building_ImprovementYieldChanges 
			(BuildingType,	ImprovementType,					YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Building_ImprovementYieldChangesGlobal
			(BuildingType,	ImprovementType,					YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChangesGlobal WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO EventChoice_ImprovementYieldChange
			(EventChoiceType,	ImprovementType,					YieldType,		YieldChange)
SELECT		EventChoiceType,	'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		YieldChange
FROM EventChoice_ImprovementYieldChange WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Improvement_YieldPerXAdjacentImprovement
			(ImprovementType,					OtherImprovementType,	YieldType,		Yield,	NumRequired)
SELECT		'IMPROVEMENT_FISHING_BOATS_GBH',	OtherImprovementType, 	YieldType,		Yield,	NumRequired
FROM Improvement_YieldPerXAdjacentImprovement WHERE OtherImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Policy_ImprovementYieldChanges 
			(PolicyType,	ImprovementType,					YieldType,		Yield)
SELECT		PolicyType,		'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Policy_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Trait_ImprovementYieldChanges 
			(TraitType,		ImprovementType,					YieldType,		Yield)
SELECT		TraitType,		'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Trait_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';



INSERT INTO Improvement_Yields 
			(ImprovementType,							YieldType,			Yield)
SELECT		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 		YieldType,			Yield
FROM Improvement_Yields WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Belief_ImprovementYieldChanges 
			(BeliefType,	ImprovementType,						YieldType,		Yield)
SELECT		BeliefType,		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Belief_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Building_ImprovementYieldChanges 
			(BuildingType,	ImprovementType,						YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Building_ImprovementYieldChangesGlobal
			(BuildingType,	ImprovementType,						YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChangesGlobal WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO EventChoice_ImprovementYieldChange
			(EventChoiceType,	ImprovementType,						YieldType,		YieldChange)
SELECT		EventChoiceType,	'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		YieldChange
FROM EventChoice_ImprovementYieldChange WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Improvement_YieldPerXAdjacentImprovement
			(ImprovementType,						OtherImprovementType,	YieldType,		Yield,	NumRequired)
SELECT		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH',	OtherImprovementType, 	YieldType,		Yield,	NumRequired
FROM Improvement_YieldPerXAdjacentImprovement WHERE OtherImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Policy_ImprovementYieldChanges 
			(PolicyType,	ImprovementType,						YieldType,		Yield)
SELECT		PolicyType,		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Policy_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Trait_ImprovementYieldChanges 
			(TraitType,		ImprovementType,						YieldType,		Yield)
SELECT		TraitType,		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Trait_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';



CREATE TRIGGER GBH_IY
AFTER INSERT ON Improvement_Yields
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield)
    SELECT DISTINCT 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield)
    SELECT DISTINCT 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Belief_IYC
AFTER INSERT ON Belief_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Belief_ImprovementYieldChanges (BeliefType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BeliefType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Belief_ImprovementYieldChanges (BeliefType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BeliefType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Building_IYC
AFTER INSERT ON Building_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Building_IYCG
AFTER INSERT ON Building_ImprovementYieldChangesGlobal
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Building_ImprovementYieldChangesGlobal (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Building_ImprovementYieldChangesGlobal (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_EventChoice_IYC
AFTER INSERT ON EventChoice_ImprovementYieldChange
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO EventChoice_ImprovementYieldChange (EventChoiceType, ImprovementType, YieldType, YieldChange)
    SELECT DISTINCT NEW.EventChoiceType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.YieldChange
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO EventChoice_ImprovementYieldChange (EventChoiceType, ImprovementType, YieldType, YieldChange)
    SELECT DISTINCT NEW.EventChoiceType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.YieldChange
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Improvement_AIYC
AFTER INSERT ON Improvement_YieldPerXAdjacentImprovement
WHEN NEW.OtherImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Improvement_YieldPerXAdjacentImprovement (ImprovementType, OtherImprovementType, YieldType, Yield, NumRequired)
    SELECT DISTINCT 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.OtherImprovementType, NEW.YieldType, NEW.Yield, NEW.NumRequired
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Improvement_YieldPerXAdjacentImprovement (ImprovementType, OtherImprovementType, YieldType, Yield, NumRequired)
    SELECT DISTINCT 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.OtherImprovementType, NEW.YieldType, NEW.Yield, NEW.NumRequired
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Policy_IYC
AFTER INSERT ON Policy_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.PolicyType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.PolicyType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Trait_IYC
AFTER INSERT ON Trait_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Trait_ImprovementYieldChanges (TraitType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.TraitType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Trait_ImprovementYieldChanges (TraitType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.TraitType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;
--------------------------------------------------------------
--------------------------------------------------------------
