UPDATE Buildings
SET Cost = -1, PrereqTech = NULL, GreatWorkCount = -1, IsDummy = 1
WHERE Type IN 
('BUILDING_MECCA_HOTEL', 
'BUILDING_VARANASI_TEMPLE', 
'BUILDING_UBUDIAH_MOSQUE',
'BUILDING_CADET',
'BUILDING_RIO_CATHEDRAL',
'BUILDING_WOODSTOCK',
'BUILDING_GALATHEA') 
AND NOT EXISTS (SELECT * FROM Buildings WHERE Type = 'BUILDING_SIKU_QUANSHU');
