-- re add these to fix the ordering
DELETE FROM CityEventChoices WHERE Type IN 
('ESPIONAGE_EVENT_CHOICE_STEAL_FAITH', 'ESPIONAGE_EVENT_CHOICE_STEAL_GW', 'ESPIONAGE_EVENT_CHOICE_SABOTAGE_PRODUCTION', 'ESPIONAGE_EVENT_CHOICE_SCIENTIFIC_GREATPEOPLE', 'ESPIONAGE_EVENT_CHOICE_STEAL_FROM_TREASURY',  'ESPIONAGE_EVENT_CHOICE_STEAL_TECH', 'ESPIONAGE_EVENT_CHOICE_ECONOMIC_TILES', 'ESPIONAGE_EVENT_CHOICE_URBAN_UNREST', 'ESPIONAGE_EVENT_CHOICE_CITY_DEFENSES');

DELETE FROM CityEvent_ParentEvents WHERE CityEventChoiceType IN 
('ESPIONAGE_EVENT_CHOICE_STEAL_FAITH', 'ESPIONAGE_EVENT_CHOICE_STEAL_GW', 'ESPIONAGE_EVENT_CHOICE_SABOTAGE_PRODUCTION', 'ESPIONAGE_EVENT_CHOICE_SCIENTIFIC_GREATPEOPLE', 'ESPIONAGE_EVENT_CHOICE_STEAL_FROM_TREASURY',  'ESPIONAGE_EVENT_CHOICE_STEAL_TECH', 'ESPIONAGE_EVENT_CHOICE_ECONOMIC_TILES', 'ESPIONAGE_EVENT_CHOICE_URBAN_UNREST', 'ESPIONAGE_EVENT_CHOICE_CITY_DEFENSES');

UPDATE SpyPassiveBonuses SET
NetworkPointsNeeded = 2000
WHERE Type = 'SPY_PASSIVE_5';

INSERT INTO CityEventChoice_EventCostYield
	(CityEventChoiceType, YieldType, Yield)
VALUES
	('ESPIONAGE_EVENT_CHOICE_DIRTY_BOMB', 'YIELD_POPULATION', 5);

INSERT INTO CityEventChoice_BuildingClassYieldModifier
	(CityEventChoiceType, BuildingClassType, YieldType, Modifier)
VALUES
	('ESPIONAGE_EVENT_CHOICE_CITY_POISON', 'BUILDINGCLASS_WELL', 'YIELD_FOOD', -33),
	('ESPIONAGE_EVENT_CHOICE_CITY_POISON', 'BUILDINGCLASS_AQUEDUCT', 'YIELD_FOOD', -33);

-- this dictates the order in the UI
INSERT INTO CityEvent_ParentEvents
	(CityEventChoiceType, CityEventType)
VALUES
	('ESPIONAGE_EVENT_CHOICE_CITY_POISON', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_STEAL_FAITH', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_LEAFLETS', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_CITY_BOMBING', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_STOP_OIL', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_STEAL_GW', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_SABOTAGE_PRODUCTION', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_HIJACK', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_SCIENTIFIC_GREATPEOPLE', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_ECONOMIC_TILES', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_STEAL_FROM_TREASURY', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_CITY_INFILTRATE', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_HIRE_MERCS', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_URBAN_UNREST', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_CITY_DEFENSES', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_STEAL_TECH', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_DIRTY_BOMB', 'ESPIONAGE_EVENT_CHOICE_SELECT_FOCUS'),
	-- Counterspy
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_FOCUS'),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_FOCUS');

INSERT INTO CityEventChoice_YieldSiphon
	(CityEventChoiceType, YieldType, Yield)
VALUES
	('ESPIONAGE_EVENT_CHOICE_CITY_INFILTRATE', 'YIELD_GOLD', 20),
	('ESPIONAGE_EVENT_CHOICE_CITY_INFILTRATE', 'YIELD_SCIENCE', 20),
	('ESPIONAGE_EVENT_CHOICE_CITY_INFILTRATE', 'YIELD_CULTURE', 20);

INSERT INTO Event_ParentEvents
	(EventChoiceType, EventType)
VALUES
	('ESPIONAGE_EVENT_MERCENARIES', 'ESPIONAGE_EVENT_MERCENARIES_PARENT');

INSERT INTO CityEventChoice_ImprovementDestructionRandom
	(CityEventChoiceType, ImprovementType, Number)
VALUES
	('ESPIONAGE_EVENT_CHOICE_STOP_OIL', 'IMPROVEMENT_WELL', 9),
	('ESPIONAGE_EVENT_CHOICE_STOP_OIL', 'IMPROVEMENT_OFFSHORE_PLATFORM', 9);

UPDATE Language_en_US
SET Text = Text || ' Blocks the {TXT_KEY_ESPIONAGE_EVENT_CHOICE_CITY_POISON} [ICON_SPY] Spy Mission in this City.'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass IN ('BUILDINGCLASS_MEDICAL_LAB'));

UPDATE Language_en_US
SET Text = Text || ' Blocks the {TXT_KEY_ESPIONAGE_EVENT_CHOICE_DIRTY_BOMB} [ICON_SPY] Spy Mission in this City.'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass IN ('BUILDINGCLASS_BOMB_SHELTER'));

INSERT INTO CityEventChoice_YieldOnSpyIdentified
	(CityEventChoiceType, YieldType, Yield)
VALUES
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 'YIELD_TOURISM', 50),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 'YIELD_CULTURE', 50),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 'YIELD_FAITH', 50),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 'YIELD_CULTURE', 50);

UPDATE CityEventChoice_YieldOnSpyIdentified SET YieldType = 'YIELD_PRODUCTION' WHERE CityEventChoiceType = 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE' AND YieldType = 'YIELD_SCIENCE';

INSERT INTO CityEventChoice_YieldOnSpyKilled
	(CityEventChoiceType, YieldType, Yield)
VALUES
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 'YIELD_TOURISM', 150),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 'YIELD_CULTURE', 150),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 'YIELD_FAITH', 150),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 'YIELD_CULTURE', 150);

UPDATE CityEventChoice_YieldOnSpyKilled SET YieldType = 'YIELD_PRODUCTION' WHERE CityEventChoiceType = 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE' AND YieldType = 'YIELD_SCIENCE';

-- counterspies block specific missions
INSERT INTO CityEventChoice_EventLinks
	(CityEventChoiceType, Event, EventChoice, CityEvent, CityEventChoiceLinker, 
		CheckKnownPlayers, CheckOnlyEventCity, CheckForActive)
VALUES
	('ESPIONAGE_EVENT_CHOICE_SCIENTIFIC_GREATPEOPLE', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_NETWORK', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_STEAL_FROM_TREASURY', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_NETWORK', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_ECONOMIC_TILES', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_NETWORK', 
		0, 1, 0),

	('ESPIONAGE_EVENT_CHOICE_CITY_DEFENSES', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_CITY_POISON', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_SABOTAGE_PRODUCTION', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE', 
		0, 1, 0),

	('ESPIONAGE_EVENT_CHOICE_HIJACK', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_CITY_BOMBING', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_URBAN_UNREST', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 
		0, 1, 0),

	('ESPIONAGE_EVENT_CHOICE_STEAL_FAITH', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_STEAL_GW', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 
		0, 1, 0),
	('ESPIONAGE_EVENT_CHOICE_LEAFLETS', NULL, NULL, NULL, 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_RELIGION', 
		0, 1, 0);
-- dont need this anymore and china ua mission shouldnt be blockable
UPDATE CityEventChoices SET
CounterspyBlockSapCity = 0
WHERE Type = 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE';

INSERT INTO CityEventChoice_CityYieldModifier
	(CityEventChoiceType, YieldType, Yield)
VALUES
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_TOURISM', 'YIELD_TOURISM', -15);

INSERT INTO CityEventChoice_SpecialistYieldChange
	(CityEventChoiceType, SpecialistType, YieldType, YieldChange)
VALUES
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_NETWORK', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_NETWORK', 'SPECIALIST_SCIENTIST', 'YIELD_SCIENCE', 1),
	('ESPIONAGE_EVENT_CHOICE_COUNTERSPY_NETWORK', 'SPECIALIST_ENGINEER', 'YIELD_PRODUCTION', 1);

UPDATE CityEventChoices SET 
PrereqTech = 'TECH_GUNPOWDER'
WHERE Type = 'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE';

INSERT INTO CityEventChoice_ImprovementYieldChange
	(CityEventChoiceType, ImprovementType, YieldType, YieldChange)
SELECT
	'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE', Type, 'YIELD_PRODUCTION', 2
FROM Improvements WHERE NoFollowUp = 1 UNION ALL
SELECT
	'ESPIONAGE_EVENT_CHOICE_COUNTERSPY_DEFENSE', Type, 'YIELD_CULTURE_LOCAL', 2
FROM Improvements WHERE NoFollowUp = 1;






