--==========================================================================================================================
-- CONTRACTS
--==========================================================================================================================
-- JFD_Contracts
------------------------
INSERT INTO JFD_Contracts 
		(Type, 										Category,						PrereqEra,				ObsoleteEra,			IsSlavery,	Maintenance,	Rating, DisbandChance,  MutinyChance,	Turns,	YieldCost,		Description, 									Adjective, 										Civilopedia,										PolicyType,										PromotionType)
VALUES	('CONTRACT_JFD_AIRSCAN', 					'CONTRACT_JFD_MERCENARY',		'ERA_MODERN',			null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_AIRSCAN_DESC',			'TXT_KEY_CONTRACT_JFD_AIRSCAN_ADJ',				'TXT_KEY_CONTRACT_JFD_AIRSCAN_TEXT',				'POLICY_CONTRACT_JFD_AIRSCAN', 					'PROMOTION_JFD_AIRSCAN'),
		('CONTRACT_JFD_AL_TARSUSI', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_AL_TARSUSI_DESC',			'TXT_KEY_CONTRACT_JFD_AL_TARSUSI_ADJ',			'TXT_KEY_CONTRACT_JFD_AL_TARSUSI_TEXT',				'POLICY_CONTRACT_JFD_AL_TARSUSI', 				'PROMOTION_JFD_AL_TARSUSI'),
		('CONTRACT_JFD_AMSAIG', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_RENAISSANCE',		0,			1,				5,		0,				100,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_AMSAIG_DESC',				'TXT_KEY_CONTRACT_JFD_AMSAIG_ADJ',				'TXT_KEY_CONTRACT_JFD_AMSAIG_TEXT',					'POLICY_CONTRACT_JFD_AMSAIG', 					'PROMOTION_JFD_AMSAIG'),
		('CONTRACT_JFD_ARCHIMEDES', 				'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			1,				5,		100,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_ARCHIMEDES_DESC',			'TXT_KEY_CONTRACT_JFD_ARCHIMEDES_ADJ',			'TXT_KEY_CONTRACT_JFD_ARCHIMEDES_TEXT',				'POLICY_CONTRACT_JFD_ARCHIMEDES', 				'PROMOTION_JFD_ARCHIMEDES'),
		('CONTRACT_JFD_ATHOLL', 					'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_MODERN',			0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_ATHOLL_DESC',				'TXT_KEY_CONTRACT_JFD_ATHOLL_ADJ',				'TXT_KEY_CONTRACT_JFD_ATHOLL_TEXT',					'POLICY_CONTRACT_JFD_ATHOLL', 					'PROMOTION_JFD_ATHOLL'),
		('CONTRACT_JFD_ATTACOTTI', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_ATTACOTTI_DESC',			'TXT_KEY_CONTRACT_JFD_ATTACOTTI_ADJ',			'TXT_KEY_CONTRACT_JFD_ATTACOTTI_TEXT',				'POLICY_CONTRACT_JFD_ATTACOTTI', 				'PROMOTION_JFD_ATTACOTTI'),
		('CONTRACT_JFD_BAE_SYSTEMS', 				'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BAE_SYSTEMS_DESC',		'TXT_KEY_CONTRACT_JFD_BAE_SYSTEMS_ADJ',			'TXT_KEY_CONTRACT_JFD_BAE_SYSTEMS_TEXT',			'POLICY_CONTRACT_JFD_BAE_SYSTEMS', 				'PROMOTION_JFD_BAE_SYSTEMS'),
		('CONTRACT_JFD_BARBARY_CORSAIRS', 			'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BARBARY_CORSAIRS_DESC',	'TXT_KEY_CONTRACT_JFD_BARBARY_CORSAIRS_ADJ',	'TXT_KEY_CONTRACT_JFD_BARBARY_CORSAIRS_TEXT',		'POLICY_CONTRACT_JFD_BARBARY_CORSAIRS', 		'PROMOTION_JFD_BARBARY_CORSAIRS'),
		('CONTRACT_JFD_BASHI_BAZOUK', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BASHI_BAZOUK_DESC',		'TXT_KEY_CONTRACT_JFD_BASHI_BAZOUK_ADJ',		'TXT_KEY_CONTRACT_JFD_BASHI_BAZOUK_TEXT',			'POLICY_CONTRACT_JFD_BASHI_BAZOUK', 			'PROMOTION_JFD_BASHI_BAZOUK'),
		('CONTRACT_JFD_BELEARIC', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BELEARIC_DESC',			'TXT_KEY_CONTRACT_JFD_BELEARIC_ADJ',			'TXT_KEY_CONTRACT_JFD_BELEARIC_TEXT',				'POLICY_CONTRACT_JFD_BELEARIC', 				'PROMOTION_JFD_BELEARIC'),
		('CONTRACT_JFD_BERDAN', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MEDIEVAL',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BERDAN_DESC',				'TXT_KEY_CONTRACT_JFD_BERDAN_ADJ',				'TXT_KEY_CONTRACT_JFD_BERDAN_TEXT',					'POLICY_CONTRACT_JFD_BERDAN', 					'PROMOTION_JFD_BERDAN'),
		('CONTRACT_JFD_BESSI', 						'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			4,				2,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BESSI_DESC',				'TXT_KEY_CONTRACT_JFD_BESSI_ADJ',				'TXT_KEY_CONTRACT_JFD_BESSI_TEXT',					'POLICY_CONTRACT_JFD_BESSI', 					'PROMOTION_JFD_BESSI'),
		('CONTRACT_JFD_BLACK_BANDS', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BLACK_BANDS_DESC',		'TXT_KEY_CONTRACT_JFD_BLACK_BANDS_ADJ',			'TXT_KEY_CONTRACT_JFD_BLACK_BANDS_TEXT',			'POLICY_CONTRACT_JFD_BLACK_BANDS', 				'PROMOTION_JFD_BLACK_BANDS'),
		('CONTRACT_JFD_BLACKWATER', 				'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BLACKWATER_DESC',			'TXT_KEY_CONTRACT_JFD_BLACKWATER_ADJ',			'TXT_KEY_CONTRACT_JFD_BLACKWATER_TEXT',				'POLICY_CONTRACT_JFD_BLACKWATER', 				'PROMOTION_JFD_BLACKWATER'),
		('CONTRACT_JFD_BLUE_GUARDS', 				'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BLUE_GUARDS_DESC',		'TXT_KEY_CONTRACT_JFD_BLUE_GUARDS_ADJ',			'TXT_KEY_CONTRACT_JFD_BLUE_GUARDS_TEXT',			'POLICY_CONTRACT_JFD_BLUE_GUARDS', 				'PROMOTION_JFD_BLUE_GUARDS'),
		('CONTRACT_JFD_BOEING', 					'CONTRACT_JFD_MERCENARY',		'ERA_MODERN',			null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BOEING_DESC',				'TXT_KEY_CONTRACT_JFD_BOEING_ADJ',				'TXT_KEY_CONTRACT_JFD_BOEING_TEXT',					'POLICY_CONTRACT_JFD_BOEING', 					'PROMOTION_JFD_BOEING'),
		('CONTRACT_JFD_BOFORS', 					'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		null,					0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BOFORS_DESC',				'TXT_KEY_CONTRACT_JFD_BOFORS_ADJ',				'TXT_KEY_CONTRACT_JFD_BOFORS_TEXT',					'POLICY_CONTRACT_JFD_BOFORS', 					'PROMOTION_JFD_BOFORS'),
		('CONTRACT_JFD_CATALAN_COMPANY', 			'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CATALAN_COMPANY_DESC',	'TXT_KEY_CONTRACT_JFD_CATALAN_COMPANY_ADJ',		'TXT_KEY_CONTRACT_JFD_CATALAN_COMPANY_TEXT',		'POLICY_CONTRACT_JFD_CATALAN_COMPANY', 			'PROMOTION_JFD_CATALAN_COMPANY'),
		('CONTRACT_JFD_CEBEILLE', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		null,					0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CEBEILLE_DESC',			'TXT_KEY_CONTRACT_JFD_CEBEILLE_ADJ',			'TXT_KEY_CONTRACT_JFD_CEBEILLE_TEXT',				'POLICY_CONTRACT_JFD_CEBEILLE', 				'PROMOTION_JFD_CEBEILLE'),
		('CONTRACT_JFD_CINQUE', 					'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CINQUE_DESC',				'TXT_KEY_CONTRACT_JFD_CINQUE_ADJ',				'TXT_KEY_CONTRACT_JFD_CINQUE_TEXT',					'POLICY_CONTRACT_JFD_CINQUE', 					'PROMOTION_JFD_CINQUE'),
		('CONTRACT_JFD_CHELA', 						'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		1,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CHELA_DESC',				'TXT_KEY_CONTRACT_JFD_CHELA_ADJ',				'TXT_KEY_CONTRACT_JFD_CHELA_TEXT',					'POLICY_CONTRACT_JFD_CHELA', 					'PROMOTION_JFD_CHELA'),
		('CONTRACT_JFD_CLAN_SWEENY', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CLAN_SWEENY_DESC',		'TXT_KEY_CONTRACT_JFD_CLAN_SWEENY_ADJ',			'TXT_KEY_CONTRACT_JFD_CLAN_SWEENY_TEXT',			'POLICY_CONTRACT_JFD_CLAN_SWEENY', 				'PROMOTION_JFD_CLAN_SWEENY'),
		('CONTRACT_JFD_COLONIAL_MARINES', 			'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_POSTMODERN',		0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_COLONIAL_MARINES_DESC',	'TXT_KEY_CONTRACT_JFD_COLONIAL_MARINES_ADJ',	'TXT_KEY_CONTRACT_JFD_COLONIAL_MARINES_TEXT',		'POLICY_CONTRACT_JFD_COLONIAL_MARINES', 		'PROMOTION_JFD_COLONIAL_MARINES'),
		('CONTRACT_JFD_COMPANY_ADVENTURERS', 		'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_POSTMODERN',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_COMPANY_ADVENTURERS_DESC','TXT_KEY_CONTRACT_JFD_COMPANY_ADVENTURERS_ADJ',	'TXT_KEY_CONTRACT_JFD_COMPANY_ADVENTURERS_TEXT',	'POLICY_CONTRACT_JFD_COMPANY_ADVENTURERS', 		'PROMOTION_JFD_COMPANY_ADVENTURERS'),
		('CONTRACT_JFD_COMPANY_HAT', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_COMPANY_HAT_DESC',		'TXT_KEY_CONTRACT_JFD_COMPANY_HAT_ADJ',			'TXT_KEY_CONTRACT_JFD_COMPANY_HAT_TEXT',			'POLICY_CONTRACT_JFD_COMPANY_HAT', 				'PROMOTION_JFD_COMPANY_HAT'),
		('CONTRACT_JFD_CORP_ENGINEER', 				'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CORP_ENGINEER_DESC',		'TXT_KEY_CONTRACT_JFD_CORP_ENGINEER_ADJ',		'TXT_KEY_CONTRACT_JFD_CORP_ENGINEER_TEXT',			'POLICY_CONTRACT_JFD_CORP_ENGINEER', 			'PROMOTION_JFD_CORP_ENGINEER'),
		('CONTRACT_JFD_DE_MEURON', 					'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_DE_MEURON_DESC',			'TXT_KEY_CONTRACT_JFD_DE_MEURON_ADJ',			'TXT_KEY_CONTRACT_JFD_DE_MEURON_TEXT',				'POLICY_CONTRACT_JFD_DE_MEURON', 				'PROMOTION_JFD_DE_MEURON'),
		('CONTRACT_JFD_DE_WATTEVILLE', 				'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_DE_WATTEVILLE_DESC',		'TXT_KEY_CONTRACT_JFD_DE_WATTEVILLE_ADJ',		'TXT_KEY_CONTRACT_JFD_DE_WATTEVILLE_TEXT',			'POLICY_CONTRACT_JFD_DE_WATTEVILLE', 			'PROMOTION_JFD_DE_WATTEVILLE'),
		('CONTRACT_JFD_DIAMOND_DOGS', 				'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_DIAMOND_DOGS_DESC',		'TXT_KEY_CONTRACT_JFD_DIAMOND_DOGS_ADJ',		'TXT_KEY_CONTRACT_JFD_DIAMOND_DOGS_TEXT',			'POLICY_CONTRACT_JFD_DIAMOND_DOGS', 			'PROMOTION_JFD_DIAMOND_DOGS'),
		('CONTRACT_JFD_DYNCORP', 					'CONTRACT_JFD_MERCENARY',		'ERA_POSTMODERN',		null,					0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_DYNCORP_DESC',			'TXT_KEY_CONTRACT_JFD_DYNCORP_ADJ',				'TXT_KEY_CONTRACT_JFD_DYNCORP_TEXT',				'POLICY_CONTRACT_JFD_DYNCORP', 					'PROMOTION_JFD_DYNCORP'),
		--('CONTRACT_JFD_EAGLE_WARRIORS', 			'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_EAGLE_WARRIORS_DESC',		'TXT_KEY_CONTRACT_JFD_EAGLE_WARRIORS_ADJ',		'TXT_KEY_CONTRACT_JFD_EAGLE_WARRIORS_TEXT',			-('CONTRACT_JFD_EAGLE_WARRIORS', 		'PROMOTION_JFD_EAGLE_WARRIORS'),
		('CONTRACT_JFD_ELSWICK', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_POSTMODERN',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_ELSWICK_DESC',			'TXT_KEY_CONTRACT_JFD_ELSWICK_ADJ',				'TXT_KEY_CONTRACT_JFD_ELSWICK_TEXT',				'POLICY_CONTRACT_JFD_ELSWICK', 					'PROMOTION_JFD_ELSWICK'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_EXECUTIVE_OUTCOMES_DESC',	'TXT_KEY_CONTRACT_JFD_EXECUTIVE_OUTCOMES_ADJ',	'TXT_KEY_CONTRACT_JFD_EXECUTIVE_OUTCOMES_TEXT',		'POLICY_CONTRACT_JFD_EXECUTIVE_OUTCOMES',		'PROMOTION_JFD_EXECUTIVE_OUTCOMES'),
		('CONTRACT_JFD_FLYING_TIGERS', 				'CONTRACT_JFD_MERCENARY',		'ERA_MODERN',			'ERA_FUTURE',			0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_FLYING_TIGERS_DESC',		'TXT_KEY_CONTRACT_JFD_FLYING_TIGERS_ADJ',		'TXT_KEY_CONTRACT_JFD_FLYING_TIGERS_TEXT',			'POLICY_CONTRACT_JFD_FLYING_TIGERS', 			'PROMOTION_JFD_FLYING_TIGERS'),
		('CONTRACT_JFD_FORTIT_INDUSTRIES', 			'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_FUTURE',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_FORTIT_INDUSTRIES_DESC',	'TXT_KEY_CONTRACT_JFD_FORTIT_INDUSTRIES_ADJ',	'TXT_KEY_CONTRACT_JFD_FORTIT_INDUSTRIES_TEXT',		'POLICY_CONTRACT_JFD_FORTIT_INDUSTRIES', 		'PROMOTION_JFD_FORTIT_INDUSTRIES'),
		('CONTRACT_JFD_FOREIGN_LEGION', 			'CONTRACT_JFD_MERCENARY',		'ERA_MODERN',			null,					0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_FOREIGN_LEGION_DESC',		'TXT_KEY_CONTRACT_JFD_FOREIGN_LEGION_ADJ',		'TXT_KEY_CONTRACT_JFD_FOREIGN_LEGION_TEXT',			'POLICY_CONTRACT_JFD_FOREIGN_LEGION', 			'PROMOTION_JFD_FOREIGN_LEGION'),
		('CONTRACT_JFD_FULTON', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MODERN',			0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_FULTON_DESC',				'TXT_KEY_CONTRACT_JFD_FULTON_ADJ',				'TXT_KEY_CONTRACT_JFD_FULTON_TEXT',					'POLICY_CONTRACT_JFD_FULTON', 					'PROMOTION_JFD_FULTON'),
		('CONTRACT_JFD_GAESATAE', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_GAESATAE_DESC',			'TXT_KEY_CONTRACT_JFD_GAESATAE_ADJ',			'TXT_KEY_CONTRACT_JFD_GAESATAE_TEXT',				'POLICY_CONTRACT_JFD_GAESATAE', 				'PROMOTION_JFD_GAESATAE'),
		('CONTRACT_JFD_GASMOULOI', 					'CONTRACT_JFD_MERCENARY',		'ERA_CLASSICAL',		'ERA_MEDIEVAL',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_GASMOULOI_DESC',			'TXT_KEY_CONTRACT_JFD_GASMOULOI_ADJ',			'TXT_KEY_CONTRACT_JFD_GASMOULOI_TEXT',				'POLICY_CONTRACT_JFD_GASMOULOI', 				'PROMOTION_JFD_GASMOULOI'),
		('CONTRACT_JFD_GHILMAN', 					'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		1,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_GHILMAN_DESC',			'TXT_KEY_CONTRACT_JFD_GHILMAN_ADJ',				'TXT_KEY_CONTRACT_JFD_GHILMAN_TEXT',				'POLICY_CONTRACT_JFD_GHILMAN', 					'PROMOTION_JFD_GHILMAN'),
		('CONTRACT_JFD_GLENN_MARINE', 				'CONTRACT_JFD_MERCENARY',		'ERA_POSTMODERN',		null,					0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_GLENN_MARINE_DESC',		'TXT_KEY_CONTRACT_JFD_GLENN_MARINE_ADJ',		'TXT_KEY_CONTRACT_JFD_GLENN_MARINE_TEXT',			'POLICY_CONTRACT_JFD_GLENN_MARINE', 			'PROMOTION_JFD_GLENN_MARINE'),
		('CONTRACT_JFD_GURKHA', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		null,					0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_GURKHA_DESC',				'TXT_KEY_CONTRACT_JFD_GURKHA_ADJ',				'TXT_KEY_CONTRACT_JFD_GURKHA_TEXT',					'POLICY_CONTRACT_JFD_GURKHA', 					'PROMOTION_JFD_GURKHA'),
		('CONTRACT_JFD_HABIRU', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			1,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HABIRU_DESC',				'TXT_KEY_CONTRACT_JFD_HABIRU_ADJ',				'TXT_KEY_CONTRACT_JFD_HABIRU_TEXT',					'POLICY_CONTRACT_JFD_HABIRU', 					'PROMOTION_JFD_HABIRU'),
		('CONTRACT_JFD_HACKAPELL', 					'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_MODERN',			0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HACKAPELL_DESC',			'TXT_KEY_CONTRACT_JFD_HACKAPELL_ADJ',			'TXT_KEY_CONTRACT_JFD_HACKAPELL_TEXT',				'POLICY_CONTRACT_JFD_HACKAPELL', 				'PROMOTION_JFD_HACKAPELL'),
		('CONTRACT_JFD_HASHSHASHINS', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_RENAISSANCE',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HASHSHASHINS_DESC',		'TXT_KEY_CONTRACT_JFD_HASHSHASHINS_ADJ',		'TXT_KEY_CONTRACT_JFD_HASHSHASHINS_TEXT',			'POLICY_CONTRACT_JFD_HASHSHASHINS', 			'PROMOTION_JFD_HASHSHASHINS'),
		('CONTRACT_JFD_HARLAND_WOLFF', 				'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		null,					0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HARLAND_WOLFF_DESC',		'TXT_KEY_CONTRACT_JFD_HARLAND_WOLFF_ADJ',		'TXT_KEY_CONTRACT_JFD_HARLAND_WOLFF_TEXT',			'POLICY_CONTRACT_JFD_HARLAND_WOLFF', 			'PROMOTION_JFD_HARLAND_WOLFF'),
		('CONTRACT_JFD_HAVEDIC', 					'CONTRACT_JFD_MERCENARY',		'ERA_CLASSICAL',		'ERA_INDUSTRIAL',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HAVEDIC_DESC',			'TXT_KEY_CONTRACT_JFD_HAVEDIC_ADJ',				'TXT_KEY_CONTRACT_JFD_HAVEDIC_TEXT',				'POLICY_CONTRACT_JFD_HAVEDIC', 					'PROMOTION_JFD_HAVEDIC'),
		('CONTRACT_JFD_HELMSCHMIED', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HELMSCHMIED_DESC',		'TXT_KEY_CONTRACT_JFD_HELMSCHMIED_ADJ',			'TXT_KEY_CONTRACT_JFD_HELMSCHMIED_TEXT',			'POLICY_CONTRACT_JFD_HELMSCHMIED', 				'PROMOTION_JFD_HELMSCHMIED'),
		('CONTRACT_JFD_HESSIANS', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MODERN',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HESSIANS_DESC',			'TXT_KEY_CONTRACT_JFD_HESSIANS_ADJ',			'TXT_KEY_CONTRACT_JFD_HESSIANS_TEXT',				'POLICY_CONTRACT_JFD_HESSIANS', 				'PROMOTION_JFD_HESSIANS'),
		('CONTRACT_JFD_HETAIREIA', 					'CONTRACT_JFD_MERCENARY',		'ERA_CLASSICAL',		'ERA_MEDIEVAL',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HETAIREIA_DESC',			'TXT_KEY_CONTRACT_JFD_HETAIREIA_ADJ',			'TXT_KEY_CONTRACT_JFD_HETAIREIA_TEXT',				'POLICY_CONTRACT_JFD_HETAIREIA', 				'PROMOTION_JFD_HETAIREIA'),
		('CONTRACT_JFD_HYUNDAI', 					'CONTRACT_JFD_MERCENARY',		'ERA_POSTMODERN',		null,					0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_HYUNDAI_DESC',			'TXT_KEY_CONTRACT_JFD_HYUNDAI_ADJ',				'TXT_KEY_CONTRACT_JFD_HYUNDAI_TEXT',				'POLICY_CONTRACT_JFD_HYUNDAI', 					'PROMOTION_JFD_HYUNDAI'),
		('CONTRACT_JFD_JANISSARIES', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_MODERN',			1,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_JANISSARIES_DESC',		'TXT_KEY_CONTRACT_JFD_JANISSARIES_ADJ',			'TXT_KEY_CONTRACT_JFD_JANISSARIES_TEXT',			'POLICY_CONTRACT_JFD_JANISSARIES', 				'PROMOTION_JFD_JANISSARIES'),
		('CONTRACT_JFD_JOMSVIKINGS', 				'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_RENAISSANCE',		0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_JOMSVIKINGS_DESC',		'TXT_KEY_CONTRACT_JFD_JOMSVIKINGS_ADJ',			'TXT_KEY_CONTRACT_JFD_JOMSVIKINGS_TEXT',			'POLICY_CONTRACT_JFD_JOMSVIKINGS', 				'PROMOTION_JFD_JOMSVIKINGS'),
		('CONTRACT_JFD_MAMLUKES', 					'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		1,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_MAMLUKES_DESC',			'TXT_KEY_CONTRACT_JFD_MAMLUKES_ADJ',			'TXT_KEY_CONTRACT_JFD_MAMLUKES_TEXT',				'POLICY_CONTRACT_JFD_MAMLUKES', 				'PROMOTION_JFD_MAMLUKES'),
		('CONTRACT_JFD_MEDJAY', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			1,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_MEDJAY_DESC',				'TXT_KEY_CONTRACT_JFD_MEDJAY_ADJ',				'TXT_KEY_CONTRACT_JFD_MEDJAY_TEXT',					'POLICY_CONTRACT_JFD_MEDJAY', 					'PROMOTION_JFD_MEDJAY'),
		('CONTRACT_JFD_MITSUBISHI', 				'CONTRACT_JFD_MERCENARY',		'ERA_POSTMODERN',		null,					0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_MITSUBISHI_DESC',			'TXT_KEY_CONTRACT_JFD_MITSUBISHI_ADJ',			'TXT_KEY_CONTRACT_JFD_MITSUBISHI_TEXT',				'POLICY_CONTRACT_JFD_MITSUBISHI', 				'PROMOTION_JFD_MITSUBISHI'),
		('CONTRACT_JFD_NEWCOMEN', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MODERN',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_NEWCOMEN_DESC',			'TXT_KEY_CONTRACT_JFD_NEWCOMEN_ADJ',			'TXT_KEY_CONTRACT_JFD_NEWCOMEN_TEXT',				'POLICY_CONTRACT_JFD_NEWCOMEN', 				'PROMOTION_JFD_NEWCOMEN'),
		('CONTRACT_JFD_NEGROLI', 					'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_NEGROLI_DESC',			'TXT_KEY_CONTRACT_JFD_NEGROLI_ADJ',				'TXT_KEY_CONTRACT_JFD_NEGROLI_TEXT',				'POLICY_CONTRACT_JFD_NEGROLI', 					'PROMOTION_JFD_NEGROLI'),
		('CONTRACT_JFD_OUTLAWS', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MODERN',			0,			5,				1,		30,				15,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_OUTLAWS_DESC',			'TXT_KEY_CONTRACT_JFD_OUTLAWS_ADJ',				'TXT_KEY_CONTRACT_JFD_OUTLAWS_TEXT',				'POLICY_CONTRACT_JFD_OUTLAWS', 					'PROMOTION_JFD_OUTLAWS'),
		('CONTRACT_JFD_POTSDAM_GIANTS', 			'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MODERN',			0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_POTSDAM_GIANTS_DESC',		'TXT_KEY_CONTRACT_JFD_POTSDAM_GIANTS_ADJ',		'TXT_KEY_CONTRACT_JFD_POTSDAM_GIANTS_TEXT',			'POLICY_CONTRACT_JFD_POTSDAM_GIANTS', 			'PROMOTION_JFD_POTSDAM_GIANTS'),
		('CONTRACT_JFD_ROBCO', 						'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_ROBCO_DESC',				'TXT_KEY_CONTRACT_JFD_ROBCO_ADJ',				'TXT_KEY_CONTRACT_JFD_ROBCO_TEXT',					'POLICY_CONTRACT_JFD_ROBCO', 					'PROMOTION_JFD_ROBCO'),
		('CONTRACT_JFD_SAIKASHUU', 					'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SAIKASHUU_DESC',			'TXT_KEY_CONTRACT_JFD_SAIKASHUU_ADJ',			'TXT_KEY_CONTRACT_JFD_SAIKASHUU_TEXT',				'POLICY_CONTRACT_JFD_SAIKASHUU', 				'PROMOTION_JFD_SAIKASHUU'),
		('CONTRACT_JFD_SALERAIOI', 					'CONTRACT_JFD_MERCENARY',		'ERA_CLASSICAL',		'ERA_MEDIEVAL',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SALERAIOI_DESC',			'TXT_KEY_CONTRACT_JFD_SALERAIOI_ADJ',			'TXT_KEY_CONTRACT_JFD_SALERAIOI_TEXT',				'POLICY_CONTRACT_JFD_SALERAIOI', 				'PROMOTION_JFD_SALERAIOI'),
		('CONTRACT_JFD_SANDLINE', 					'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SANDLINE_DESC',			'TXT_KEY_CONTRACT_JFD_SANDLINE_ADJ',			'TXT_KEY_CONTRACT_JFD_SANDLINE_TEXT',				'POLICY_CONTRACT_JFD_SANDLINE', 				'PROMOTION_JFD_SANDLINE'),
		('CONTRACT_JFD_SAQALIBA', 					'CONTRACT_JFD_MERCENARY',		'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		1,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SAQALIBA_DESC',			'TXT_KEY_CONTRACT_JFD_SAQALIBA_ADJ',			'TXT_KEY_CONTRACT_JFD_SAQALIBA_TEXT',				'POLICY_CONTRACT_JFD_SAQALIBA', 				'PROMOTION_JFD_SAQALIBA'),
		('CONTRACT_JFD_SERBIAN_FREE_CORPS',			'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_MODERN',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SERBIAN_FREE_CORPS_DESC',	'TXT_KEY_CONTRACT_JFD_SERBIAN_FREE_CORPS_ADJ',	'TXT_KEY_CONTRACT_JFD_SERBIAN_FREE_CORPS_TEXT',		'POLICY_CONTRACT_JFD_SERBIAN_FREE_CORPS',		'PROMOTION_JFD_SERBIAN_FREE_CORPS'),
		('CONTRACT_JFD_SONS_MARS', 					'CONTRACT_JFD_MERCENARY',		'ERA_CLASSICAL',		'ERA_MEDIEVAL',			0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SONS_MARS_DESC',			'TXT_KEY_CONTRACT_JFD_SONS_MARS_ADJ',			'TXT_KEY_CONTRACT_JFD_SONS_MARS_TEXT',				'POLICY_CONTRACT_JFD_SONS_MARS', 				'PROMOTION_JFD_SONS_MARS'),
		('CONTRACT_JFD_SONS_MIL', 					'CONTRACT_JFD_MERCENARY',		'ERA_CLASSICAL',		'ERA_RENAISSANCE',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_SONS_MIL_DESC',			'TXT_KEY_CONTRACT_JFD_SONS_MIL_ADJ',			'TXT_KEY_CONTRACT_JFD_SONS_MIL_TEXT',				'POLICY_CONTRACT_JFD_SONS_MIL', 				'PROMOTION_JFD_SONS_MIL'),
		('CONTRACT_JFD_STRADIOT', 					'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_STRADIOT_DESC',			'TXT_KEY_CONTRACT_JFD_STRADIOT_ADJ',			'TXT_KEY_CONTRACT_JFD_STRADIOT_TEXT',				'POLICY_CONTRACT_JFD_STRADIOT', 				'PROMOTION_JFD_STRADIOT'),
		('CONTRACT_JFD_TEN_THOUSAND', 				'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_MEDIEVAL',			0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_TEN_THOUSAND_DESC',		'TXT_KEY_CONTRACT_JFD_TEN_THOUSAND_ADJ',		'TXT_KEY_CONTRACT_JFD_TEN_THOUSAND_TEXT',			'POLICY_CONTRACT_JFD_TEN_THOUSAND', 			'PROMOTION_JFD_TEN_THOUSAND'),
		('CONTRACT_JFD_OUTER_HEAVEN', 				'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_OUTER_HEAVEN_DESC',		'TXT_KEY_CONTRACT_JFD_OUTER_HEAVEN_ADJ',		'TXT_KEY_CONTRACT_JFD_OUTER_HEAVEN_TEXT',			'POLICY_CONTRACT_JFD_OUTER_HEAVEN', 			'PROMOTION_JFD_OUTER_HEAVEN'),
		('CONTRACT_JFD_VERNY', 						'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_POSTMODERN',		0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_VERNY_DESC',				'TXT_KEY_CONTRACT_JFD_VERNY_ADJ',				'TXT_KEY_CONTRACT_JFD_VERNY_TEXT',					'POLICY_CONTRACT_JFD_VERNY', 					'PROMOTION_JFD_VERNY'),
		('CONTRACT_JFD_VITRUVIUS', 					'CONTRACT_JFD_MERCENARY',		'ERA_ANCIENT',			'ERA_RENAISSANCE',		0,			2,				4,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_VITRUVIUS_DESC',			'TXT_KEY_CONTRACT_JFD_VITRUVIUS_ADJ',			'TXT_KEY_CONTRACT_JFD_VITRUVIUS_TEXT',				'POLICY_CONTRACT_JFD_VITRUVIUS', 				'PROMOTION_JFD_VITRUVIUS'),
		('CONTRACT_JFD_WEYLAND_YUTANI', 			'CONTRACT_JFD_MERCENARY',		'ERA_FUTURE',			null,					0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_WEYLAND_YUTANI_DESC',		'TXT_KEY_CONTRACT_JFD_WEYLAND_YUTANI_ADJ',		'TXT_KEY_CONTRACT_JFD_WEYLAND_YUTANI_TEXT',			'POLICY_CONTRACT_JFD_WEYLAND_YUTANI', 			'PROMOTION_JFD_WEYLAND_YUTANI'),
		('CONTRACT_JFD_WHITE_COMPANY', 				'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		0,			1,				5,		0,				0,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_WHITE_COMPANY_DESC',		'TXT_KEY_CONTRACT_JFD_WHITE_COMPANY_ADJ',		'TXT_KEY_CONTRACT_JFD_WHITE_COMPANY_TEXT',			'POLICY_CONTRACT_JFD_WHITE_COMPANY', 			'PROMOTION_JFD_WHITE_COMPANY'),
		('CONTRACT_JFD_WILD_GEESE', 				'CONTRACT_JFD_MERCENARY',		'ERA_RENAISSANCE',		'ERA_MODERN',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_WILD_GEESE_DESC',			'TXT_KEY_CONTRACT_JFD_WILD_GEESE_ADJ',			'TXT_KEY_CONTRACT_JFD_WILD_GEESE_TEXT',				'POLICY_CONTRACT_JFD_WILD_GEESE', 				'PROMOTION_JFD_WILD_GEESE'),
		('CONTRACT_JFD_WHITE_LEGION', 				'CONTRACT_JFD_MERCENARY',		'ERA_POSTMODERN',		null,					0,			4,				2,		20,				10,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_WHITE_LEGION_DESC',		'TXT_KEY_CONTRACT_JFD_WHITE_LEGION_ADJ',		'TXT_KEY_CONTRACT_JFD_WHITE_LEGION_TEXT',			'POLICY_CONTRACT_JFD_WHITE_LEGION', 			'PROMOTION_JFD_WHITE_LEGION'),
		('CONTRACT_JFD_ZOUAVES', 					'CONTRACT_JFD_MERCENARY',		'ERA_INDUSTRIAL',		'ERA_MODERN',			0,			3,				3,		10,				5,				25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_ZOUAVES_DESC',			'TXT_KEY_CONTRACT_JFD_ZOUAVES_ADJ',				'TXT_KEY_CONTRACT_JFD_ZOUAVES_TEXT',				'POLICY_CONTRACT_JFD_ZOUAVES', 					'PROMOTION_JFD_ZOUAVES');

UPDATE JFD_Contracts
SET PrereqEra = 'ERA_ENLIGHTENMENT'
WHERE Type IN ('CONTRACT_JFD_HESSIANS', 'CONTRACT_JFD_POTSDAM_GIANTS', 'CONTRACT_JFD_ZOUAVES')
AND EXISTS (SELECT * FROM Technologies WHERE Type = 'TECH_EE_FLINTLOCK');

INSERT INTO JFD_Contracts
		(Type, 										Category,					PrereqEra,				ObsoleteEra,			Maintenance,	Rating, Turns,	YieldCost,		Description, 									Adjective, 										Civilopedia,										PromotionType)
SELECT	'CONTRACT_JFD_BLACK_RIDERS', 				'CONTRACT_JFD_MERCENARY',	'ERA_RENAISSANCE',		'ERA_INDUSTRIAL',		3,				3,		25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_BLACK_RIDERS_DESC',		'TXT_KEY_CONTRACT_JFD_BLACK_RIDERS_ADJ',		'TXT_KEY_CONTRACT_JFD_BLACK_RIDERS_TEXT',			'PROMOTION_JFD_BLACK_RIDERS'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_ADDITIONS_BLACK_RIDERS' AND Value = 1);

INSERT INTO JFD_Contracts
		(Type, 										Category,					PrereqEra,				ObsoleteEra,			Maintenance,	Rating, Turns,	YieldCost,		Description, 									Adjective, 										Civilopedia,										PromotionType,						PrereqCivilization)
SELECT	'CONTRACT_JFD_CORSAIRS', 					'CONTRACT_JFD_MERCENARY',	'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		2,				4,		25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_CORSAIRS_DESC',			'TXT_KEY_CONTRACT_JFD_CORSAIRS_ADJ',			'TXT_KEY_CONTRACT_JFD_CORSAIRS_TEXT',				'PROMOTION_JFD_CORSAIRS',			Type
FROM Civilizations WHERE Type IN ('CIVILIZATION_MC_BUCCANEERS', 'CIVILIZATION_LS_CARRIBBEAN')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_CHANGES_PRIVATEER' AND Value = 1);

INSERT INTO JFD_Contracts
		(Type, 										Category,					PrereqEra,				ObsoleteEra,			Maintenance,	Rating, Turns,	YieldCost,		Description, 									Adjective, 										Civilopedia,										PromotionType)
SELECT	'CONTRACT_JFD_VARANGIAN', 					'CONTRACT_JFD_MERCENARY',	'ERA_CLASSICAL',		'ERA_RENAISSANCE',		1,				5,		25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_VARANGIAN_DESC',			'TXT_KEY_CONTRACT_JFD_VARANGIAN_ADJ',			'TXT_KEY_CONTRACT_JFD_VARANGIAN_TEXT',				'PROMOTION_JFD_VARANGIAN'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_ADDITIONS_VARANGIAN' AND Value = 1);

INSERT INTO JFD_Contracts
		(Type, 										Category,					PrereqEra,				ObsoleteEra,			Maintenance,	Rating, Turns,	YieldCost,		Description, 									Adjective, 										Civilopedia,										PromotionType)
SELECT	'CONTRACT_JFD_VICTUAL_BROTHERS', 			'CONTRACT_JFD_MERCENARY',	'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		3,				3,		25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_VICTUAL_BROTHERS_DESC',	'TXT_KEY_CONTRACT_JFD_VICTUAL_BROTHERS_ADJ',	'TXT_KEY_CONTRACT_JFD_VICTUAL_BROTHERS_TEXT',		'PROMOTION_JFD_VICTUAL_BROTHERS'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_CHANGES_PRIVATEER' AND Value = 1);

INSERT INTO JFD_Contracts
		(Type, 										Category,					PrereqEra,				ObsoleteEra,			Maintenance,	Rating, Turns,	YieldCost,		Description, 									Adjective, 										Civilopedia,										PromotionType,						PrereqCivilization)
SELECT	'CONTRACT_JFD_WATERGUEZEN', 				'CONTRACT_JFD_MERCENARY',	'ERA_MEDIEVAL',			'ERA_INDUSTRIAL',		2,				4,		25,		'[ICON_GOLD]',	'TXT_KEY_CONTRACT_JFD_WATERGUEZEN_DESC',		'TXT_KEY_CONTRACT_JFD_WATERGUEZEN_ADJ',			'TXT_KEY_CONTRACT_JFD_WATERGUEZEN_TEXT',			'PROMOTION_JFD_WATERGUEZEN',		'CIVILIZATION_NETHERLANDS'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_CHANGES_PRIVATEER' AND Value = 1);
-------------------------------------
-- JFD_Contract_Units
-------------------------------------
INSERT INTO JFD_Contract_Units 
		(ContractType, 								UnitType,						UseUniqueIfAvailable)
VALUES	('CONTRACT_JFD_BARBARY_CORSAIRS', 			'UNIT_PRIVATEER',				0),
		('CONTRACT_JFD_BLACK_BANDS', 				'UNIT_GERMAN_LANDSKNECHT',		0),
		('CONTRACT_JFD_FOREIGN_LEGION', 			'UNIT_FRENCH_FOREIGNLEGION',	0),
		('CONTRACT_JFD_GAESATAE', 					'UNIT_JFD_GAESATAE',			0),
		('CONTRACT_JFD_HESSIANS', 					'UNIT_JFD_HESSIAN',				0),
		('CONTRACT_JFD_POTSDAM_GIANTS', 			'UNIT_JFD_POTSDAM_GIANT',		0),
		('CONTRACT_JFD_VARANGIAN', 					'UNIT_JFD_VARANGIAN',			0),
		('CONTRACT_JFD_VICTUAL_BROTHERS', 			'UNIT_PRIVATEER',				0),
		('CONTRACT_JFD_WEYLAND_YUTANI', 			'UNIT_MECH',					0);	

INSERT INTO JFD_Contract_Units
		(ContractType, 								UnitType)
SELECT	'CONTRACT_JFD_BLACK_RIDERS', 				'UNIT_JFD_BLACK_RIDER'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_ADDITIONS_BLACK_RIDERS' AND Value = 1);

INSERT INTO JFD_Contract_Units
		(ContractType, 								UnitType)
SELECT	'CONTRACT_JFD_CORSAIRS', 					'UNIT_PRIVATEER'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_CHANGES_PRIVATEER' AND Value = 1);

INSERT INTO JFD_Contract_Units
		(ContractType, 								UnitType)
SELECT	'CONTRACT_JFD_VARANGIAN', 					'UNIT_JFD_VARANGIAN'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_ADDITIONS_VARANGIAN' AND Value = 1);

INSERT INTO JFD_Contract_Units
		(ContractType, 								UnitType)
SELECT	'CONTRACT_JFD_VICTUAL_BROTHERS', 			'UNIT_PRIVATEER'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_CHANGES_PRIVATEER' AND Value = 1);

INSERT INTO JFD_Contract_Units
		(ContractType, 								UnitType)
SELECT	'CONTRACT_JFD_WATERGUEZEN', 				'UNIT_DUTCH_SEA_BEGGAR'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_MERCENARIES_UNITS_CHANGES_PRIVATEER' AND Value = 1);
-------------------------------------
-- JFD_Contract_UnitCombats
-------------------------------------
INSERT INTO JFD_Contract_UnitClasses
		(ContractType, 								CultureType,		UseOnlyCultureType,	UnitClassType)
VALUES	('CONTRACT_JFD_ATTACOTTI',					'JFD_Northern',		0,					'UNITCLASS_SPEARMAN'),
		('CONTRACT_JFD_ATTACOTTI',					'JFD_Northern',		0,					'UNITCLASS_WARRIOR'),
		('CONTRACT_JFD_BESSI',						'JFD_Classical',	0,					'UNITCLASS_SPEARMAN'),
		('CONTRACT_JFD_BESSI',						'JFD_Classical',	0,					'UNITCLASS_WARRIOR'),
		('CONTRACT_JFD_BESSI',						'JFD_Classical',	0,					'UNITCLASS_COMPOSITE_BOWMAN'),
		('CONTRACT_JFD_BESSI',						'JFD_Classical',	0,					'UNITCLASS_ARCHER'),
		('CONTRACT_JFD_SONS_MARS',					'JFD_Classical',	0,					'UNITCLASS_SWORDSMAN'),
		('CONTRACT_JFD_SONS_MARS',					'JFD_Classical',	0,					'UNITCLASS_TRIREME'),
		('CONTRACT_JFD_SONS_MARS',					'JFD_Classical',	0,					'UNITCLASS_LONGSWORDSMAN'),
		('CONTRACT_JFD_TEN_THOUSAND',				'JFD_Classical',	0,					'UNITCLASS_SPEARMAN'),
		('CONTRACT_JFD_TEN_THOUSAND',				'JFD_Classical',	0,					'UNITCLASS_PIKEMAN');
	
INSERT INTO JFD_Contract_UnitCombats 
		(ContractType, 								CultureType,		UseOnlyCultureType,	UnitCombatType)
VALUES	('CONTRACT_JFD_AIRSCAN',					null,				0,					'UNITCOMBAT_BOMBER'),
		('CONTRACT_JFD_AIRSCAN',					null,				0,					'UNITCOMBAT_FIGHTER'),
		('CONTRACT_JFD_AL_TARSUSI',					'JFD_Islamic',		0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_AMSAIG',						'JFD_Northern',		1,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_AMSAIG',						'JFD_Northern',		1,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_ARCHIMEDES',					'JFD_Classical',	0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_ARCHIMEDES',					'JFD_Classical',	0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_ATHOLL',						'JFD_Northern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_ATHOLL',						'JFD_Northern',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_BAE_SYSTEMS',				null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_BAE_SYSTEMS',				null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_BAE_SYSTEMS',				null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_BAE_SYSTEMS',				null,				0,					'UNITCOMBAT_CARRIER'),
		('CONTRACT_JFD_BASHI_BAZOUK',				'JFD_Islamic',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_BASHI_BAZOUK',				'JFD_Islamic',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_BELEARIC',					'JFD_Classical',	0,					'UNITCOMBAT_RECON'),
		('CONTRACT_JFD_BLACKWATER',					null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_BLACKWATER',					null,				0,					'UNITCOMBAT_ARMOR'),
		('CONTRACT_JFD_BLACKWATER',					null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_BLACKWATER',					null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_BLACKWATER',					null,				0,					'UNITCOMBAT_SUBMARINE'),
		('CONTRACT_JFD_BLUE_GUARDS',				'JFD_Western',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_BERDAN',						null,				0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_BERDAN',						null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_BOEING',						null,				0,					'UNITCOMBAT_HELICOPTER'),
		('CONTRACT_JFD_BOEING',						null,				0,					'UNITCOMBAT_BOMBER'),
		('CONTRACT_JFD_BOEING',						null,				0,					'UNITCOMBAT_FIGHTER'),
		('CONTRACT_JFD_BOFORS',						null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_CATALAN_COMPANY',			'JFD_Southern',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_CATALAN_COMPANY',			'JFD_Southern',		0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_CATALAN_COMPANY',			'JFD_Southern',		0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_CATALAN_COMPANY',			'JFD_Western',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_CATALAN_COMPANY',			'JFD_Western',		0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_CATALAN_COMPANY',			'JFD_Western',		0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_CEBEILLE',					null,				0,					'UNITCOMBAT_BOMBER'),
		('CONTRACT_JFD_CHELA',						'JFD_Bharata',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_CHELA',						'JFD_Bharata',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_CHELA',						'JFD_Bharata',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_CINQUE',						'JFD_Western',		0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_CINQUE',						'JFD_Western',		0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_CLAN_SWEENY',				'JFD_Northern',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_COLONIAL_MARINES',			'JFD_Bantu',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_COLONIAL_MARINES',			'JFD_WestAfrican',	0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_COMPANY_HAT',				'JFD_Southern',		0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_COMPANY_HAT',				'JFD_Southern',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_COMPANY_HAT',				'JFD_Southern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_COMPANY_ADVENTURERS',		null,				0,					'UNITCOMBAT_RECON'),
		('CONTRACT_JFD_CORP_ENGINEER', 				null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_DE_MEURON',					'JFD_Western',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_DE_MEURON',					'JFD_Western',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_DE_WATTEVILLE',				'JFD_Central',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_DE_WATTEVILLE',				'JFD_Central',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_DIAMOND_DOGS',				null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_DYNACORP',					null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_DYNACORP',					null,				0,					'UNITCOMBAT_ARMOR'),
		('CONTRACT_JFD_DYNACORP',					null,				0,					'UNITCOMBAT_HELICOPTER'),
		('CONTRACT_JFD_DYNACORP',					null,				0,					'UNITCOMBAT_BOMBER'),
		('CONTRACT_JFD_DYNACORP',					null,				0,					'UNITCOMBAT_FIGHTER'),
		('CONTRACT_JFD_ELSWICK',					null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_ELSWICK',					null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_ARMOR'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_HELICOPTER'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_BOMBER'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_FIGHTER'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_EXECUTIVE_OUTCOMES',			null,				0,					'UNITCOMBAT_SUBMARINE'),
		('CONTRACT_JFD_HELMSCHMIED',				null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_FLYING_TIGERS', 				null,				0,					'UNITCOMBAT_FIGHTER'),
		('CONTRACT_JFD_FORTIT_INDUSTRIES', 			null,				0,					'UNITCOMBAT_ARMOR'),
		('CONTRACT_JFD_FULTON',						null,				0,					'UNITCOMBAT_SUBMARINE'),
		('CONTRACT_JFD_FULTON',						null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_FULTON',						null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_GASMOULOI',					'JFD_Classical',	0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_GASMOULOI',					'JFD_Classical',	0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_GLENN_MARNIE', 				null,				0,					'UNITCOMBAT_CARRIER'),
		('CONTRACT_JFD_GLENN_MARNIE', 				null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_GLENN_MARNIE', 				null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_GLENN_MARNIE', 				null,				0,					'UNITCOMBAT_SUBMARINE'),
		('CONTRACT_JFD_GHILMAN',					'JFD_Steppe',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_GHILMAN',					'JFD_Steppe',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_GHILMAN',					'JFD_Steppe',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_GURKHA',						'JFD_Bharata',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_HABIRU',						'JFD_Mesopotamic',	0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_HABIRU',						'JFD_Mesopotamic',	0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_HABIRU',						'JFD_Mesopotamic',	0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_HASHSHASHINS',				'JFD_Islamic',		1,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_HASHSHASHINS',				'JFD_Islamic',		1,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_HASHSHASHINS',				'JFD_Islamic',		1,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_HETAIREIA',					'JFD_Classical',	0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_HACKAPELL',					'JFD_Western',		0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_HARLAND_WOLFF', 				null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_HARLAND_WOLFF', 				null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_HAVEDIC', 					null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_HYUNDAI',					null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_HYUNDAI',					null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_HYUNDAI',					null,				0,					'UNITCOMBAT_CARRIER'),
		('CONTRACT_JFD_HYUNDAI',					null,				0,					'UNITCOMBAT_SUBMARINE'),
		('CONTRACT_JFD_JANISSARIES',				'JFD_Islamic',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_JOMSVIKINGS',				'JFD_Northern',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_JOMSVIKINGS',				'JFD_Northern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_MAMLUKES',					'JFD_Islamic',		0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_MEDJAY',						'JFD_Mesopotamic',	0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_MITSUBISHI',					null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_NEGROLI',					'JFD_Southern',		0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_NEWCOMEN',					null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_NEWCOMEN',					null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_OUTLAWS',					'JFD_Colonial',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_ROBCO', 						null,				0,					'UNITCOMBAT_ARMOR'),
		('CONTRACT_JFD_ROBCO', 						null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_SANDLINE', 					null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_SANDLINE', 					null,				0,					'UNITCOMBAT_ARMOR'),
		('CONTRACT_JFD_SAIKASHUU',					'JFD_Oriental',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_SAIKASHUU',					'JFD_Oriental',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_SALERAIOI',					'JFD_Classical',	0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_SALERAIOI',					'JFD_Classical',	0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_SALERAIOI',					'JFD_Classical',	0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_SAQALIBA',					'JFD_Eastern',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_SAQALIBA',					'JFD_Eastern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_SAQALIBA',					'JFD_Eastern',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_SERBIAN_FREE_CORPS',			'JFD_Eastern',		0,					'UNITCOMBAT_ARCHER'),
		('CONTRACT_JFD_SERBIAN_FREE_CORPS',			'JFD_Eastern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_SERBIAN_FREE_CORPS',			'JFD_Eastern',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_SONS_MIL',					'JFD_Northern',		0,					'UNITCOMBAT_MELEE'),
		('CONTRACT_JFD_STRADIOT',					'JFD_Eastern',		0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_OUTER_HEAVEN',				null,				0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_VERNY',						null,				0,					'UNITCOMBAT_NAVALRANGED'),
		('CONTRACT_JFD_VERNY',						null,				0,					'UNITCOMBAT_NAVALMELEE'),
		('CONTRACT_JFD_VITRUVIUS',					null,				0,					'UNITCOMBAT_SIEGE'),
		('CONTRACT_JFD_WHITE_COMPANY',				'JFD_Southern',		0,					'UNITCOMBAT_MOUNTED'),
		('CONTRACT_JFD_WHITE_LEGION',				'JFD_Eastern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_WILD_GEESE',					'JFD_Northern',		0,					'UNITCOMBAT_GUN'),
		('CONTRACT_JFD_ZOUAVES',					'JFD_Central',		0,					'UNITCOMBAT_GUN');			
--==========================================================================================================================
-- POLICIES
--==========================================================================================================================
-- Policies
------------------------
INSERT INTO Policies 
		(Type, 											Description)
VALUES	('POLICY_CONTRACT_JFD_AIRSCAN', 				'TXT_KEY_CONTRACT_JFD_AIRSCAN_DESC'),
		('POLICY_CONTRACT_JFD_AL_TARSUSI', 				'TXT_KEY_CONTRACT_JFD_AL_TARSUSI_DESC'),
		('POLICY_CONTRACT_JFD_AMSAIG', 					'TXT_KEY_CONTRACT_JFD_AMSAIG_DESC'),
		('POLICY_CONTRACT_JFD_ARCHIMEDES', 				'TXT_KEY_CONTRACT_JFD_ARCHIMEDES_DESC'),
		('POLICY_CONTRACT_JFD_ATHOLL', 					'TXT_KEY_CONTRACT_JFD_ATHOLL_DESC'),
		('POLICY_CONTRACT_JFD_ATTACOTTI', 				'TXT_KEY_CONTRACT_JFD_ATTACOTTI_DESC'),
		('POLICY_CONTRACT_JFD_BAE_SYSTEMS', 			'TXT_KEY_CONTRACT_JFD_BAE_SYSTEMS_DESC'),
		('POLICY_CONTRACT_JFD_BARBARY_CORSAIRS', 		'TXT_KEY_CONTRACT_JFD_BARBARY_CORSAIRS_DESC'),
		('POLICY_CONTRACT_JFD_BASHI_BAZOUK', 			'TXT_KEY_CONTRACT_JFD_BASHI_BAZOUK_DESC'),
		('POLICY_CONTRACT_JFD_BELEARIC', 				'TXT_KEY_CONTRACT_JFD_BELEARIC_DESC'),
		('POLICY_CONTRACT_JFD_BERDAN', 					'TXT_KEY_CONTRACT_JFD_BERDAN_DESC'),
		('POLICY_CONTRACT_JFD_BESSI', 					'TXT_KEY_CONTRACT_JFD_BESSI_DESC'),
		('POLICY_CONTRACT_JFD_BLACK_BANDS', 			'TXT_KEY_CONTRACT_JFD_BLACK_BANDS_DESC'),
		('POLICY_CONTRACT_JFD_BLACKWATER', 				'TXT_KEY_CONTRACT_JFD_BLACKWATER_DESC'),
		('POLICY_CONTRACT_JFD_BLUE_GUARDS', 			'TXT_KEY_CONTRACT_JFD_BLUE_GUARDS_DESC'),
		('POLICY_CONTRACT_JFD_BOEING', 					'TXT_KEY_CONTRACT_JFD_BOEING_DESC'),
		('POLICY_CONTRACT_JFD_BOFORS', 					'TXT_KEY_CONTRACT_JFD_BOFORS_DESC'),
		('POLICY_CONTRACT_JFD_CATALAN_COMPANY', 		'TXT_KEY_CONTRACT_JFD_CATALAN_COMPANY_DESC'),
		('POLICY_CONTRACT_JFD_CEBEILLE', 				'TXT_KEY_CONTRACT_JFD_CEBEILLE_DESC'),
		('POLICY_CONTRACT_JFD_CINQUE', 					'TXT_KEY_CONTRACT_JFD_CINQUE_DESC'),
		('POLICY_CONTRACT_JFD_CHELA', 					'TXT_KEY_CONTRACT_JFD_CHELA_DESC'),
		('POLICY_CONTRACT_JFD_CLAN_SWEENY', 			'TXT_KEY_CONTRACT_JFD_CLAN_SWEENY_DESC'),
		('POLICY_CONTRACT_JFD_COLONIAL_MARINES', 		'TXT_KEY_CONTRACT_JFD_COLONIAL_MARINES_DESC'),
		('POLICY_CONTRACT_JFD_COMPANY_ADVENTURERS', 	'TXT_KEY_CONTRACT_JFD_COMPANY_ADVENTURERS_DESC'),
		('POLICY_CONTRACT_JFD_COMPANY_HAT', 			'TXT_KEY_CONTRACT_JFD_COMPANY_HAT_DESC'),
		('POLICY_CONTRACT_JFD_CORP_ENGINEER', 			'TXT_KEY_CONTRACT_JFD_CORP_ENGINEER_DESC'),
		('POLICY_CONTRACT_JFD_DE_MEURON', 				'TXT_KEY_CONTRACT_JFD_DE_MEURON_DESC'),
		('POLICY_CONTRACT_JFD_DE_WATTEVILLE', 			'TXT_KEY_CONTRACT_JFD_DE_WATTEVILLE_DESC'),
		('POLICY_CONTRACT_JFD_DIAMOND_DOGS', 			'TXT_KEY_CONTRACT_JFD_DIAMOND_DOGS_DESC'),
		('POLICY_CONTRACT_JFD_DYNCORP', 				'TXT_KEY_CONTRACT_JFD_DYNCORP_DESC'),
		('POLICY_CONTRACT_JFD_ELSWICK', 				'TXT_KEY_CONTRACT_JFD_ELSWICK_DESC'),
		('POLICY_CONTRACT_JFD_EXECUTIVE_OUTCOMES',		'TXT_KEY_CONTRACT_JFD_EXECUTIVE_OUTCOMES_DESC'),
		('POLICY_CONTRACT_JFD_FLYING_TIGERS', 			'TXT_KEY_CONTRACT_JFD_FLYING_TIGERS_DESC'),
		('POLICY_CONTRACT_JFD_FORTIT_INDUSTRIES', 		'TXT_KEY_CONTRACT_JFD_FORTIT_INDUSTRIES_DESC'),
		('POLICY_CONTRACT_JFD_FOREIGN_LEGION', 			'TXT_KEY_CONTRACT_JFD_FOREIGN_LEGION_DESC'),
		('POLICY_CONTRACT_JFD_FULTON', 					'TXT_KEY_CONTRACT_JFD_FULTON_DESC'),
		('POLICY_CONTRACT_JFD_GAESATAE', 				'TXT_KEY_CONTRACT_JFD_GAESATAE_DESC'),
		('POLICY_CONTRACT_JFD_GASMOULOI', 				'TXT_KEY_CONTRACT_JFD_GASMOULOI_DESC'),
		('POLICY_CONTRACT_JFD_GHILMAN', 				'TXT_KEY_CONTRACT_JFD_GHILMAN_DESC'),
		('POLICY_CONTRACT_JFD_GLENN_MARINE', 			'TXT_KEY_CONTRACT_JFD_GLENN_MARINE_DESC'),
		('POLICY_CONTRACT_JFD_GURKHA', 					'TXT_KEY_CONTRACT_JFD_GURKHA_DESC'),
		('POLICY_CONTRACT_JFD_HABIRU', 					'TXT_KEY_CONTRACT_JFD_HABIRU_DESC'),
		('POLICY_CONTRACT_JFD_HACKAPELL', 				'TXT_KEY_CONTRACT_JFD_HACKAPELL_DESC'),
		('POLICY_CONTRACT_JFD_HASHSHASHINS', 			'TXT_KEY_CONTRACT_JFD_HASHSHASHINS_DESC'),
		('POLICY_CONTRACT_JFD_HARLAND_WOLFF', 			'TXT_KEY_CONTRACT_JFD_HARLAND_WOLFF_DESC'),
		('POLICY_CONTRACT_JFD_HAVEDIC', 				'TXT_KEY_CONTRACT_JFD_HAVEDIC_DESC'),
		('POLICY_CONTRACT_JFD_HELMSCHMIED', 			'TXT_KEY_CONTRACT_JFD_HELMSCHMIED_DESC'),
		('POLICY_CONTRACT_JFD_HESSIANS', 				'TXT_KEY_CONTRACT_JFD_HESSIANS_DESC'),
		('POLICY_CONTRACT_JFD_HETAIREIA', 				'TXT_KEY_CONTRACT_JFD_HETAIREIA_DESC'),
		('POLICY_CONTRACT_JFD_HYUNDAI', 				'TXT_KEY_CONTRACT_JFD_HYUNDAI_DESC'),
		('POLICY_CONTRACT_JFD_JANISSARIES', 			'TXT_KEY_CONTRACT_JFD_JANISSARIES_DESC'),
		('POLICY_CONTRACT_JFD_JOMSVIKINGS', 			'TXT_KEY_CONTRACT_JFD_JOMSVIKINGS_DESC'),
		('POLICY_CONTRACT_JFD_MAMLUKES', 				'TXT_KEY_CONTRACT_JFD_MAMLUKES_DESC'),
		('POLICY_CONTRACT_JFD_MEDJAY', 					'TXT_KEY_CONTRACT_JFD_MEDJAY_DESC'),
		('POLICY_CONTRACT_JFD_MITSUBISHI', 				'TXT_KEY_CONTRACT_JFD_MITSUBISHI_DESC'),
		('POLICY_CONTRACT_JFD_NEWCOMEN', 				'TXT_KEY_CONTRACT_JFD_NEWCOMEN_DESC'),
		('POLICY_CONTRACT_JFD_NEGROLI', 				'TXT_KEY_CONTRACT_JFD_NEGROLI_DESC'),
		('POLICY_CONTRACT_JFD_OUTLAWS', 				'TXT_KEY_CONTRACT_JFD_OUTLAWS_DESC'),
		('POLICY_CONTRACT_JFD_POTSDAM_GIANTS', 			'TXT_KEY_CONTRACT_JFD_POTSDAM_GIANTS_DESC'),
		('POLICY_CONTRACT_JFD_ROBCO', 					'TXT_KEY_CONTRACT_JFD_ROBCO_DESC'),
		('POLICY_CONTRACT_JFD_SAIKASHUU', 				'TXT_KEY_CONTRACT_JFD_SAIKASHUU_DESC'),
		('POLICY_CONTRACT_JFD_SALERAIOI', 				'TXT_KEY_CONTRACT_JFD_SALERAIOI_DESC'),
		('POLICY_CONTRACT_JFD_SANDLINE', 				'TXT_KEY_CONTRACT_JFD_SANDLINE_DESC'),
		('POLICY_CONTRACT_JFD_SAQALIBA', 				'TXT_KEY_CONTRACT_JFD_SAQALIBA_DESC'),
		('POLICY_CONTRACT_JFD_SERBIAN_FREE_CORPS',		'TXT_KEY_CONTRACT_JFD_SERBIAN_FREE_CORPS_DESC'),
		('POLICY_CONTRACT_JFD_SONS_MARS', 				'TXT_KEY_CONTRACT_JFD_SONS_MARS_DESC'),
		('POLICY_CONTRACT_JFD_SONS_MIL', 				'TXT_KEY_CONTRACT_JFD_SONS_MIL_DESC'),
		('POLICY_CONTRACT_JFD_STRADIOT', 				'TXT_KEY_CONTRACT_JFD_STRADIOT_DESC'),
		('POLICY_CONTRACT_JFD_TEN_THOUSAND', 			'TXT_KEY_CONTRACT_JFD_TEN_THOUSAND_DESC'),
		('POLICY_CONTRACT_JFD_OUTER_HEAVEN', 			'TXT_KEY_CONTRACT_JFD_OUTER_HEAVEN_DESC'),
		('POLICY_CONTRACT_JFD_VERNY', 					'TXT_KEY_CONTRACT_JFD_VERNY_DESC'),
		('POLICY_CONTRACT_JFD_VITRUVIUS', 				'TXT_KEY_CONTRACT_JFD_VITRUVIUS_DESC'),
		('POLICY_CONTRACT_JFD_WEYLAND_YUTANI', 			'TXT_KEY_CONTRACT_JFD_WEYLAND_YUTANI_DESC'),
		('POLICY_CONTRACT_JFD_WHITE_COMPANY', 			'TXT_KEY_CONTRACT_JFD_WHITE_COMPANY_DESC'),
		('POLICY_CONTRACT_JFD_WILD_GEESE', 				'TXT_KEY_CONTRACT_JFD_WILD_GEESE_DESC'),
		('POLICY_CONTRACT_JFD_WHITE_LEGION', 			'TXT_KEY_CONTRACT_JFD_WHITE_LEGION_DESC'),
		('POLICY_CONTRACT_JFD_ZOUAVES', 				'TXT_KEY_CONTRACT_JFD_ZOUAVES_DESC');
--==========================================================================================================================
--==========================================================================================================================