--======================================================================================================================
-- Language_ko_KR
--======================================================================================================================
INSERT OR REPLACE INTO Language_ko_KR (Tag, Text) VALUES
-- 켈두르 홀
('TXT_KEY_BUILDING_KELDUR_HALL', '켈두르 홀'),
('TXT_KEY_BUILDING_KELDUR_HALL_HELP', '지형: [COLOR_CYAN]툰드라[ENDCOLOR]; [COLOR_NEGATIVE_TEXT]평원[ENDCOLOR] [NEWLINE][NEWLINE][ICON_FOOD]인접한 툰드라 타일마다 식량 +1, [ICON_PRODUCTION] 생산력 +1[NEWLINE]인접한 눈 타일마다 도시 내 [ICON_FOOD] 식량 +1, [ICON_PRODUCTION] 생산력 +1[NEWLINE]문명 내 모든 마을에[ICON_FOOD] 식량 +2[NEWLINE]모든 도시의 [ICON_RESEARCH] 과학 산출량의 10%가 턴당 [ICON_FOOD] 식량으로 추가됩니다.'),
('TXT_KEY_BUILDING_KELDUR_HALL_PEDIA', '켈두르 홀은 아이슬란드 남부에 위치한 유서 깊은 잔디집으로, 독특한 건축 양식과 깊은 문화적 의미로 유명합니다. 12세기로 거슬러 올라가는 이 건물은 아이슬란드에서 현존하는 가장 오래된 농가 중 하나입니다. 전통적인 아이슬란드 방식으로 지어진 이 건물은 잔디 벽과 목재 구조로 이루어져 있어 혹독한 날씨를 견딜 수 있도록 설계되었습니다. 이 홀은 한때 유력한 족장들이 거주하던 곳으로, 강력한 오디 씨족과 관련이 있는 것으로 여겨집니다. 탈출 또는 저장 용도로 사용되었을 가능성이 있는 지하 통로는 이곳의 신비로움과 역사적 매력을 더해줍니다.[NEWLINE][NEWLINE]오랜 역사 속에서 켈두르는 사가 시대를 포함한 아이슬란드 중세의 산증인이었습니다. 고유의 모습 유지를 위한 신중한 보존 작업이 이루어졌으며, 이를 통해 방문객들은 초기 아이슬란드 농촌 생활을 엿볼 수 있습니다. 현재는 아이슬란드 국립박물관이 관리하며, 문화유산지로 지정되어 있습니다. 관광객들과 역사 애호가들은 이곳의 소박한 매력에 매료되어 과거 주민들의 이야기를 접하고 수세기 동안 거의 변하지 않은 주변 풍경을 탐방합니다.'),
('TXT_KEY_BUILDING_KELDUR_HALL_QUOTE', '[NEWLINE]"겨울밖에 모르고 살아온 사람의 마음은 정말 차가워질 수 있다."[NEWLINE] - 벤자민 알리레 사엔스[NEWLINE]'),
--======================================================================================================================
-- 니피사트
--======================================================================================================================
('TXT_KEY_BUILDING_NIPISAT', '니피사트'),
('TXT_KEY_BUILDING_NIPISAT_HELP', '지형: [COLOR_CYAN]툰드라[ENDCOLOR], [COLOR_CYAN]해안[ENDCOLOR][NEWLINE][NEWLINE]인접한 툰드라 타일마다 [ICON_GOLD] 골드 +1[NEWLINE]인접한 눈 타일마다 [ICON_FOOD] 식량  +1, [ICON_GOLD] 골드 +1[NEWLINE]문명 내 모든 어선에 [ICON_PRODUCTION] 생산력 +1, [ICON_CULTURE_LOCAL] 국경 확장 +1[NEWLINE][COLOR_CYAN]고고학[ENDCOLOR] 발견 시 [ICON_CULTURE] 문화 +6[NEWLINE][NEWLINE]모든 [ICON_RES_DEER] 사슴 자원: [ICON_PRODUCTION] 생산력 +1, [ICON_CULTURE] 문화 +1'),
('TXT_KEY_BUILDING_NIPISAT_PEDIA', '그린란드 서해안 시시미우트 근처에 위치한 니피사트는 북극 선사 문화에 대한 통찰을 제공하는 중요한 고고학 유적지입니다. 약 4,000년 전으로 거슬러 올라가는 사카크(Saqqaq) 문화의 유적이 광범위하게 남아 있는 곳으로, 북극 초기 거주민들의 생활 방식, 생계 수단, 기술 등을 잘 보여주는 가장 보존 상태가 뛰어난 사카크 문화 유적지 중 하나입니다. 니피삿에서의 발굴을 통해 석기, 뼈, 주거지의 흔적 등 다양한 유물이 발견되었으며, 이는 사카크 사람들이 북극의 혹독한 환경에 어떻게 적응했는지를 보여줍니다.[NEWLINE][NEWLINE]사카크 문화 외에도, 약 1,000년 전 사카크 문화를 계승한 툴레(Thule) 문화의 흔적도 발견되었습니다. 툴레인들은 현대 이누이트의 조상으로, 니피사트에서의 이들의 존재는 이 지역에서의 인간 거주와 적응의 연속성을 나타냅니다. 니피사트에서의 발견은 선사시대 북극 지역 집단 간의 문화적 전환과 상호작용을 이해하는 데 기여하며, 2018년 유네스코 세계문화유산으로 등재되어 그 역사적 가치를 인정받았습니다.'),
('TXT_KEY_BUILDING_NIPISAT_QUOTE', '[NEWLINE]"카리부는 늑대를 먹여 살리지만, 늑대가 카리부를 강하게 만든다."[NEWLINE] - 이누이트 속담[NEWLINE]'),
--======================================================================================================================
-- 아크라가스의 헤라클레스 신전
--======================================================================================================================
('TXT_KEY_BUILDING_AKRAGATOS', '아크라가스의 헤라클레스 신전'),
('TXT_KEY_BUILDING_AKRAGATOS_HELP', '지형: [COLOR_CYAN]언덕[ENDCOLOR][NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 개척자 1명을 받습니다.[NEWLINE]도시의 [ICON_PEACE] 신앙은 모든 도시에서 개척자 유닛을 훈련할 때 [ICON_PRODUCTION] 생산력으로 추가됩니다.[NEWLINE]모든 신전은 [ICON_FOOD] 식량 +1, [ICON_CULTURE] 문화 +1, [ICON_GOLDEN_AGE] 황금기 점수 +1을 얻습니다.[NEWLINE][COLOR_CYAN]고고학[ENDCOLOR] 발견 시 [ICON_TOURISM] 관광이 +3 증가합니다.'),
('TXT_KEY_BUILDING_AKRAGATOS_PEDIA', '이탈리아 시칠리아의 신전 계곡에 위치한 아그리젠토의 헤라클레스 신전은 고대 그리스 식민지 아크라가스의 가장 오래되고 존경받는 건축물 중 하나입니다. 기원전 6세기 후반에 건설된 이 도리아 양식 신전은 그리스 신화의 신성한 영웅 헤라클레스에게 바쳐졌습니다. 자연재해와 인위적 훼손으로 인해 수세기 동안 상당한 피해를 입었지만, 신전의 남아 있는 기둥들은 고대 그리스 건축의 웅장함을 증명합니다. 원래 이 건축물은 약 10미터 높이의 기둥 38개가 둘러싸는 주랑과, 헤라클레스의 상이 놓였을 중앙 신실을 갖추고 있었습니다.[NEWLINE][NEWLINE]헤라클레스 신전은 역사적, 건축적 중요성뿐 아니라 지역 종교 관습과 신화와도 연관되어 있습니다. 전설에 따르면, 이 신전에는 아크라가스 주민들이 매우 숭배했던 유명한 헤라클레스 상이 있었다고 합니다. 1920년대에 남은 기둥을 보존하고 유적을 안정화하기 위한 여러 복원 작업이 이루어졌습니다. 오늘날 헤라클레스 신전은 유네스코 세계문화유산인 신전 계곡의 일부로, 고대의 웅장함을 감상하고 지중해에서 가장 중요한 고고학 유적 중 하나의 풍부한 역사를 탐험하기 위해 전 세계 방문객이 찾고 있습니다.'),
('TXT_KEY_BUILDING_AKRAGATOS_QUOTE', '[NEWLINE]"반대편에는 미론의 작품으로 알려진 아름다운 황동으로 만든 헤라클레스가 있었다고 하는데, 확실히 그 작품이었다고 믿어진다. 또한 그 신들 앞에는 작은 제단들이 있어 예배당의 신성함을 누구에게나 알렸을 것이다.".[NEWLINE] - 키케로[NEWLINE]'),
--======================================================================================================================
-- 피쉬나 미라빌리스
--======================================================================================================================
('TXT_KEY_BUILDING_PISCINA_MIR', '피쉬나 미라빌리스'),
('TXT_KEY_BUILDING_PISCINA_MIR_HELP', '지형: [COLOR_CYAN]해안[ENDCOLOR], 건물: [COLOR_CYAN]송수로[ENDCOLOR]. [NEWLINE][NEWLINE]이 도시에 인접한 해상 전투 유닛은 턴마다 항상 10의 체력을 회복합니다.[NEWLINE]모든 도시의 [ICON_FOOD] 식량 산출량의 10%가 [ICON_GREAT_ADMIRAL] 위대한 제독 포인트로 추가됩니다.[NEWLINE]모든 송수로의 [ICON_PRODUCTION] 생산력이 +2만큼 증가합니다.'),
('TXT_KEY_BUILDING_PISCINA_MIR_PEDIA', '피쉬나 미라빌리스는 이탈리아 나폴리 근처 바콜리에 위치한 로마 공학의 뛰어난 예이자 세계에서 가장 큰 고대 저수조 중 하나입니다. 기원전 1세기 아우구스투스 시대에 건설된 이 거대한 지하 구조물은 인근 미세눔 항구에 주둔한 로마 함대를 위한 주요 물 저장고 역할을 했습니다. 이 저수조는 약 12,600 입방미터의 물을 저장할 수 있었으며, 아펜니노 산맥의 샘에서 캄파니아의 인구 밀집 지역으로 물을 운반하는 나폴리 아우구스타 수도교에서 공급받았습니다. 피쉬나 미라빌리스는 48개의 거대한 기둥이 대칭된 격자로 배치된 광대한 아치형 방들의 네트워크를 특징으로 하며, 로마인들의 고도의 수리 및 건축 기술을 보여줍니다.[NEWLINE][NEWLINE]피쉬나 미라빌리스의 인상적인 규모와 건축은 고대 로마에서 물 관리의 중요성과 일상 생활과 군사 작전을 지원한 정교한 인프라를 강조합니다. 저수조 내부는 높은 아치형 천장과 웅장한 기둥들로 이루어져 있어 거대한 지하 대성당과 같아 방문객들에게 경외감을 줍니다. 수세기 동안 피쉬나 미라빌리스는 역사가, 건축가, 관광객들에게 매혹의 대상이 되었으며, 로마 공학의 독창성과 기지의 증거로 남아 있습니다. 오늘날 이곳은 보호받는 역사적 기념물로서 고대 로마의 기술력과 문화적 우선순위를 엿볼 수 있게 합니다.'),
('TXT_KEY_BUILDING_PISCINA_MIR_QUOTE', '[NEWLINE]"교회가 종교인 것이 수로의 벽돌이 그 안을 흐르는 물인 것과 같지 않다."[NEWLINE] - 헨리 워드 비처[NEWLINE]'),
--======================================================================================================================
-- 바나웨 라이스 테라스
--======================================================================================================================
('TXT_KEY_BUILDING_BANAUE', '바나웨 라이스 테라스'),
('TXT_KEY_BUILDING_BANAUE_HELP', '지형: [COLOR_CYAN]산[ENDCOLOR]; 시설: [COLOR_CYAN]농장[ENDCOLOR]. [NEWLINE][NEWLINE]근처 언덕에 쌀 자원 3개를 생성합니다. 근처 언덕에 [ICON_RES_RICE] 쌀 자원 3개를 생성합니다.[NEWLINE]모든 곡물 창고의 [ICON_FOOD] 식량이 +2 증가합니다.[NEWLINE][NEWLINE]모든 [ICON_RES_RICE] 쌀: [ICON_FOOD] 식량 +1, [ICON_CULTURE] 문화 +2'),
('TXT_KEY_BUILDING_BANAUE_PEDIA', '해발 5,000피트 높이, 이파가오 산비탈 약 4,000제곱마일에 걸쳐 바나웨 라이스 테라스가 자리 잡고 있습니다. 이 계단식 밭은 약 2000년 전에 건설되었으며, 고대 원주민 이푸가오족이 건설했습니다. 오늘날에도 위쪽의 열대우림을 이용한 고대 관개 시스템을 통해 물이 공급됩니다. 고대 계단식 논은 최소한의 장비와 대부분 수작업으로 건설되었다는 것이 일반적인 통념입니다. 계단식 논을 따라 이어지는 계단을 끝에서 끝까지 쌓으면 지구 적도의 절반을 둘러쌀 수 있다고 합니다. 이푸가오 문화는 쌀을 주로 사용하며, 젊은이들에게 다양한 쌀 문화 축제를 소개하고, 쌀 재배부터 소비에 이르기까지 농업 의례를 실시했습니다.[NEWLINE][NEWLINE]오늘날에도 계단식 밭은 이푸가오족의 쌀과 채소를 재배하는 데 사용되고 있습니다. 그러나 이푸가오족의 대부분은 농업이 다른 산업에 비해 매력적이지 않다고 생각합니다. 이로 인해 부지는 천천히 침식되었고(계단이 가장 큰 영향을 받았음) 부지 관리의 필요성이 커졌습니다. 2010년에는 더 큰 문제인 가뭄이 발생하여 3월에는 계단식 밭이 완전히 말라 버렸습니다.'),
('TXT_KEY_BUILDING_BANAUE_QUOTE', '[NEWLINE]"모든 쌀알은 농부의 이마에서 떨어지는 땀방울이다."[NEWLINE] - 중국 속담[NEWLINE]'),
--======================================================================================================================
-- 성 카타리나 수도원
--======================================================================================================================
('TXT_KEY_BUILDING_ST_CATHERINE', '성 카타리나 수도원'),
('TXT_KEY_BUILDING_ST_CATHERINE_HELP', '특수: [COLOR_YIELD_PRODUCTION]성도[ENDCOLOR].[NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 수도원을 제공합니다.[NEWLINE]도시에 있는 [ICON_GREAT_WORK]걸작으로 인해 [ICON_CULTURE] 문화와 [ICON_PEACE] 신앙이 +2 증가합니다. [NEWLINE][ICON_VP_GREATWRITING] 걸작 문학을 위한 슬롯을 2개 가집니다. [COLOR_POSITIVE_TEXT]테마[ENDCOLOR]가 있는 경우 [ICON_FOOD] 식량과 [ICON_PEACE] 신앙이 +4 증가합니다.'),
('TXT_KEY_BUILDING_ST_CATHERINE_PEDIA', '이집트 시나이 반도의 시나이산 기슭에 위치한 성 카타리나 수도원은 세계에서 가장 오래도록 운영되어 온 기독교 수도원 중 하나입니다. 6세기에 비잔틴 황제 유스티니아누스 1세에 의해 설립되었으며, 기독교 순교자인 알렉산드리아의 성 카타리나의 유물이 기적적으로 이곳으로 옮겨진 데서 이름이 유래했습니다. 이 수도원은 초기 기독교 시대의 고대 필사본, 성상, 예술품 등 풍부한 역사적, 종교적 유산을 보유하고 있습니다. 또한 모세가 신과 대화했다고 전해지는 불타는 떨기나무가 있어 기독교인과 유대인 모두에게 신성한 장소로 여겨집니다.[NEWLINE][NEWLINE]건축적으로 성 카타리나 수도원은 침입자로부터 주민과 보물을 보호하기 위해 요새처럼 설계된 복합 건축물입니다. 성당, 모스크, 방대한 초기 필사본을 소장한 도서관, 수도사들의 생활 공간 등이 담긴 성벽으로 둘러싸여 있습니다. 이 수도원 도서관은 바티칸에 이어 필사본의 중요성과 고대성에서 두 번째로 꼽힙니다. 유네스코 세계문화유산으로 지정된 성 카타리나 수도원은 순례, 학술 연구, 영적 헌신의 중심지로서 전 세계 방문객들이 그 풍부한 역사와 종교적 중요성에 관심을 가지고 방문합니다.'),
('TXT_KEY_BUILDING_ST_CATHERINE_QUOTE', '[NEWLINE]"신앙을 순수하게 지키려면 사람은 수도원으로 은퇴하는 게 낫다."[NEWLINE] - 월터 리프먼[NEWLINE]'),
('TXT_KEY_THEMING_BONUS_ST_CATHERINE', '시나이 사본'),
('TXT_KEY_THEMING_BONUS_ST_CATHERINE_HELP', '보너스를 최대화하려면, 모든 위대한 작품 슬롯을 당신이 창작한 문학 작품으로 채우십시오.'),
--======================================================================================================================
-- 숭악사 탑
--======================================================================================================================
('TXT_KEY_UNIT_JAR_HESHANG', '화상'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA', '숭악사 탑'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_HELP', '특수: [COLOR_YIELD_PRODUCTION]성도[ENDCOLOR][NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 파고다를 제공합니다.[NEWLINE]성지를 건설하는 데 사용할 수 있는 비전투 유닛인  {TXT_KEY_UNIT_JAR_HESHANG}을 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR]로 받습니다.[NEWLINE]문명 내 모든 [ICON_VP_SCIENTIST] 과학자 전문가로부터 신앙이 [ICON_PEACE] +2 증가합니다.[NEWLINE]문명 내 모든 성지에서 [ICON_RESEARCH] 과학이 +3 증가합니다.'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_PEDIA', '중국 허난성 송산에 위치한 숭악사 탑은 중국에서 알려진 가장 오래된 벽돌 탑으로, 북위 시대인 서기 523년경에 지어졌습니다. 이 고대 구조물은 중국 초기 불교 건축의 증거로서, 한족과 중앙아시아의 영향을 혼합한 양식을 반영합니다. 탑은 당시 흔했던 사각형 탑과 달리 원형 평면을 가지며, 12층으로 우아하게 점점 가늘어지는 형태이고 각 층은 독특한 처마로 구분되어 있습니다. 숭악사 탑의 정교한 벽돌 공예와 아치 및 받침대의 사용은 당대 고급 기술을 보여주며, 중국 건축의 초기 발전 단계를 나타냅니다.[NEWLINE][NEWLINE]건축적으로 숭악사 탑은 우아하고 혁신적인 디자인으로 중요하며, 이후 중국 전역의 탑 건축에 영향을 주었습니다. 탑 내부에는 중앙 기둥과 좁은 회랑이 있어 신도들이 탑을 돌며 예배할 수 있게 합니다. 이 설계는 구조적 안정성을 제공하여 수세기 동안 자연적 마모와 지진을 견딜 수 있게 했습니다. 불교가 중국에 전파된 상징으로서 숭악사 탑은 문화적, 역사적 중요성을 지닌 기념물이자, 그 역사적 맥락과 건축적 의미를 이해하려는 학자, 건축가, 관광객들을 끌어들입니다. 2010년에는 ‘천지 중심에 있는 덩펑의 역사적 기념물’의 일부로 유네스코 세계문화유산에 등재되었습니다.'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_QUOTE', '[NEWLINE]"사원은 하늘과 땅이 만나는 지점이다."[NEWLINE] -데이비드 A. 베드나[NEWLINE]'),
--======================================================================================================================
-- 호류지
--======================================================================================================================
('TXT_KEY_BUILDING_HORYUJI', '호류지'),
('TXT_KEY_BUILDING_HORYUJI_HELP', '지형: [COLOR_CYAN]평지[ENDCOLOR] 특성: [COLOR_CYAN]강[ENDCOLOR] [NEWLINE][NEWLINE]이 도시에서 나오는 [ICON_RELIGION] 종교적 다수파의 압력이 25% 증가합니다.[NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 파고다를 제공합니다.[NEWLINE]선교사나 종교재판관과 같은 유닛을 구매하면 [ICON_CULTURE] 문화를 획득할 수 있습니다. (시대에 따라 보정[NEWLINE]문명 내 모든 [ICON_VP_WRITER] 작가 전문가로부터 [ICON_PEACE] 신앙이 +2 증가합니다.'),
('TXT_KEY_BUILDING_HORYUJI_PEDIA', '호류지는 일본 나라 현에 위치한 일본에서 가장 중요하고 역사적인 불교 사원 중 하나입니다. 607년 초기 일본 불교의 핵심 인물인 쇼토쿠 태자가 창건했으며, 일본에 불교 교리를 전파하기 위해 세워졌습니다. 원래 건물은 670년에 화재로 손상되었으나 신속히 재건되었고, 많은 건물들이 1,300년 이상 보존되어 왔습니다. 사원 단지에는 세계에서 가장 오래된 목조 건축물 중 일부가 있으며, 오층 목탑과 콘도(금당)에는 아스카 시대의 귀중한 불상과 유물이 보관되어 있습니다.[NEWLINE][NEWLINE]호류지는 그 역사적, 문화적, 건축적 중요성으로 1993년에 유네스코 세계문화유산으로 지정되었습니다. 사원 단지는 두 개의 주요 구역으로 나뉘는데, 가장 오래된 건물이 위치한 사이인 가람(서원)과 몽전(유메도노)이 위치한 토인 가람(동원)입니다. 불교 학문과 예술의 중심지로서 호류지는 여전히 활발한 예배 장소이며 일본의 깊은 영적, 건축 유산의 상징으로 남아 있습니다.'),
('TXT_KEY_BUILDING_HORYUJI_QUOTE', '[NEWLINE]"세 보배인 부처님, 가르침, 그리고 승가를 진심으로 공경하라."[NEWLINE] - 쇼토쿠 태자[NEWLINE]'),
('TXT_KEY_GRAND_HORYUJI_BONUS_HEADER', '호류지 [ICON_CULTURE]'),
('TXT_KEY_GRAND_HORYUJI_BONUS_BODY', '{@2_unitName} 유닛으로부터 [ICON_CULTURE] 문화를 +{@1_num} 획득합니다.'),
--======================================================================================================================
-- 키즈 칼라
--======================================================================================================================
('TXT_KEY_BUILDING_KYZ_KALA', '그레이트 키즈 칼라'),
('TXT_KEY_BUILDING_KYZ_KALA_HELP', '지형: [COLOR_NEGATIVE_TEXT]해안[ENDCOLOR], [COLOR_NEGATIVE_TEXT]호수[ENDCOLOR]; 특성: [COLOR_CYAN]오아시스[ENDCOLOR]. [NEWLINE][NEWLINE]+2 [ICON_GREAT_GENERAL] 위대한 장군 점수. [NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 성을 제공합니다.[NEWLINE]문명 전역의 오아시스에서 [ICON_PRODUCTION] 생산력, [ICON_CULTURE] 문화, [ICON_GOLDEN_AGE] 황금기 포인트가 +1 증가합니다.[NEWLINE]이 도시에 건물을 건설하면 [ICON_FOOD] 식량이 25 증가합니다. (시대에 따라 보정)'),
('TXT_KEY_BUILDING_KYZ_KALA_PEDIA', '위대한 키즈 칼라는 투르크메니스탄의 메르브에 위치한 유네스코 세계문화유산 내 여러 유사 구조물인 쾨슈크 중 하나인 거대한 진흙 벽돌로 된 요새 건축물입니다. 이 기념물의 건축 시기와 용도는 아직 논란이 있으며, 서기 6세기에서 8세기 사이인 사산 왕조 말기 또는 초기 이슬람 시대에 건축되었고, 1221년 몽골군의 메르브 약탈 때까지 사용된 것으로 추정됩니다. 도시 성벽 바로 외곽에 위치하며, 요새화된 거주지로 기능했을 가능성이 크며, 최근 발굴에서는 여러 내부 구획과 구별되는 방, 바닥, 계단 등이 확인되었습니다.'),
('TXT_KEY_BUILDING_KYZ_KALA_QUOTE', '[NEWLINE]"그러나 이 모든 세상은 우리가 듣는 이야기와 같다. 인간의 악행과 영광은 사라진다."[NEWLINE] - 아불카셈 페르도시[NEWLINE]'),
--======================================================================================================================
-- 소림사
--======================================================================================================================
('TXT_KEY_BUILDING_SHAOLIN', '소림사'),
('TXT_KEY_BUILDING_SHAOLIN_HELP', '지형: [COLOR_CYAN]산[ENDCOLOR], 도시: [COLOR_CYAN]플레이어의 대중 종교를 채택합니다.[ENDCOLOR]. [NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR]로 수도회를 제공합니다.[NEWLINE]모든 도시의 모든 유닛에 경험치 +20이 부여됩니다.[NEWLINE]모든 도시의 [ICON_PEACE] 신앙 생산량의 10%가 [ICON_GREAT_GENERAL] 위대한 장군 점수로 추가됩니다.'),
('TXT_KEY_BUILDING_SHAOLIN_PEDIA', '소림사는 1,500년이 넘는 풍부한 역사를 가지고 있으며, 그 시작은 북위나라 효문제 황제가 인도의 승려 발타(또는 부다바드라(불타발타라)라고도 함)선사에게 허난성의 소실산 기슭에 사원을 짓도록 허가한 서기 495년입니다. 발타는 소림사를 불교 연구와 수행의 중요한 중심지로 만들었고, 중국에서 가장 유명한 사원 중 하나가 될 토대를 마련했습니다. 32년 후, 또 다른 중요한 인물이 도착했습니다. 바로 인도 승려 보디다르마(중국어로 다모, 한자로 달마)대사입니다. 그는 이 사원에서 불교 선종(선불교)을 전파한 창시자로, 사원의 정신적 성격을 근본적으로 형성하고 불교 선종의 발상지라는 명성을 확립했습니다. [NEWLINE][NEWLINE]소림사는 무술 전통으로 전 세계적으로 유명하지만, 그 무술 체계의 역사적 발전은 대중적인 전설에서 암시하는 것보다 훨씬 더 복잡합니다. 현대 무술 역사가들은 보디다르마가 소림사에서 무술을 창시했다는 널리 퍼진 믿음이 실제로는 17세기 기공 매뉴얼에서 유래되었으며 20세기에 대중화되었다는 것을 보여주었습니다. 보디다르마의 실제 공헌은 승려들이 건강을 유지하는 데 도움이 되는 기공에 기반한 운동을 개발한 것이었는데, 이는 전투 기술이라기보다는 요가에 더 가깝습니다. 수도원의 무술 전통은 수 세기에 걸쳐 점진적으로 발전해 다양한 전투 시스템을 통합하고 전설적인 기록에서 암시하는 것보다 훨씬 늦게 체계화되었을 가능성이 있습니다. 이러한 역사적 설명에도 불구하고, 소림사는 불교 학문의 중심지이자 중국 무술 문화의 상징으로서 여전히 깊은 의미를 지니고 있습니다.'),
('TXT_KEY_BUILDING_SHAOLIN_QUOTE', '[NEWLINE]"신앙은 인간의 마음이 상상하고 믿을 수 있는 것을 성취할 수 있게 해준다."[NEWLINE] - 이소룡[NEWLINE]'),
--======================================================================================================================
-- 아시시의 성 프란치스코 대성당
--======================================================================================================================
('TXT_KEY_BUILDING_ASSISI', '아시시의 성 프란치스코 대성당'),
('TXT_KEY_BUILDING_ASSISI_HELP', '지형: [COLOR_NEGATIVE_TEXT]해안[ENDCOLOR], 구성: [COLOR_CYAN]언덕[ENDCOLOR]. [NEWLINE][NEWLINE]이 건물이 지어진 도시에 예배당을 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR]로 제공합니다.[NEWLINE]문명에 [ICON_PEACE] 신앙을 제공하는 모든 건물이 [ICON_GOLD] 골드 +1을 얻습니다.'),
('TXT_KEY_BUILDING_ASSISI_PEDIA', '이탈리아 중부의 아시시에 위치한 성 프란치스코 대성당은 기독교 세계에서 가장 중요하고 존경받는 성지 중 하나입니다. 성 프란치스코의 시성 직후인 1228년에서 1253년 사이에 지어진 이 대성당은 두 개의 서로 다른 교회: 상부 성당(Basilica Superiore)과 하부 성당(Basilica Inferiore)으로 구성되어 있습니다. 높이 솟은 고딕 양식의 상부 성당은 커다란 스테인드글라스 창문을 특징으로 하며, 조토 디 본도네와 그의 작업장에서 그린 것으로 알려진 방대한 프레스코 벽화로 유명합니다. 이 프레스코 벽화는 성 프란치스코의 삶을 묘사하고 있으며 이는 이탈리아 미술의 걸작으로 여겨집니다. 로마네스크 양식인 하부 성당은 보다 엄숙한 분위기를 지니며, 성 프란체스코의 무덤이 있어 전 세계 수백만 신자들의 순례지로 자리잡고 있습니다. [NEWLINE][NEWLINE]아시시의 성 프란치스코 대성당은 주요 종교 유적지일 뿐만 아니라 문화적, 예술적 보물이기도 합니다. 상부 및 하부 성당의 프레스코 벽화는 서양 미술사에서 가장 중요한 작품 중 하나로, 성경과 성 프란치스코의 삶에서 중요한 장면을 생생한 세부 묘사와 감정적 깊이로 묘사하고 있습니다. 이러한 예술 작품은 이탈리아 르네상스 예술의 발전에 중요한 역할을 했습니다. 수도원을 포함한 이 성당 단지는 역사적, 정신적, 예술적 중요성으로 인해 유네스코 세계문화유산으로 지정되었습니다. 이곳은 프란치스코회의 중요한 중심지로 남아 있으며, 그 깊은 아름다움과 영적인 유산으로 방문객들에게 계속 영감을 주고 있습니다.'),
('TXT_KEY_BUILDING_ASSISI_QUOTE', '[NEWLINE]"해야 하는 일부터 하라. 그런 다음 할 수 있는 일을 하라. 그러면 어느새 불가능한 일을 하고 있을 것이다."[NEWLINE] - 아시시의 성 프란치스코[NEWLINE]'),
--======================================================================================================================
-- 예수 탄생 교회
--======================================================================================================================
('TXT_KEY_BUILDING_CHURCH_NATIVITY', '예수 탄생 교회'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_HELP', '지형: [COLOR_CYAN]언덕[ENDCOLOR], 플레이어: [COLOR_CYAN]창시한 종교[ENDCOLOR] [NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 교회를 제공합니다.[NEWLINE]모든 도시에서 [ICON_PEACE] 신앙 +2, 각 도시에 신도 한 명 이상이 있는 모든 세계 종교에 대해 [ICON_PRODUCTION] 생산력 +2를 제공합니다.'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_PEDIA', '베들레헴에 위치한 예수 탄생 교회는 기독교에서 가장 신성한 장소 중 하나로, 전통적으로 예수 그리스도의 탄생지로 여겨집니다. 예수 탄생 동굴(Grotto of the Nativity)로 알려진 동굴 위에 세워졌으며, 4세기에 콘스탄티누스 황제와 그의 어머니 헬레나에 의뢰로 지어졌습니다. 이 성당은 손상을 입은 후 6세기에 유스티니아누스 황제에 의해 재건되었습니다.수세기에 걸쳐 이 교회는 십자군 시대, 그리스 정교회, 아르메니아, 로마 가톨릭의 영향을 받은 요소를 포함하여 수많은 개조와 증축을 거쳤습니다. 이 건물은 고대 기둥, 모자이크, 그리고 예수 탄생 지점을 나타내는 은빛 별이 있는 것으로 유명합니다.[NEWLINE][NEWLINE]침략, 화재, 정치적 분쟁 등 격동의 역사를 겪었음에도 불구하고 예수 탄생 교회는 주요 순례지로 남아 있습니다. 그리스 정교회, 아르메니아 사도교회, 로마 가톨릭 교회가 공동으로 관리하며 각기 다른 구역을 담당하고 있습니다. 2012년에 유네스코 세계문화유산으로 지정되어 역사적, 영적 중요성을 인정 받았습니다. 오늘날에도 매년 수백만 명의 방문객을 끌어들이며 베들레헴의 중심에서 신앙과 인내의 강력한 상징으로 자리 잡고 있습니다.'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_QUOTE', '[NEWLINE]"구유 속 아기를 꼭 보라. 그는 우리의 사랑이다. 그를 바라보며, 이 모든 것이 신비임을 깨달으라."[NEWLINE] - 성 호세마리아 에스크리바[NEWLINE]'),
--======================================================================================================================
-- 성 요한 수도회
--======================================================================================================================
('TXT_KEY_BUILDING_HOSPITAL_STJOHN', '성 요한 수도회'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_HELP', '특수: [COLOR_YIELD_PRODUCTION]성도[ENDCOLOR][NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 수도회를 제공합니다.[NEWLINE]이 도시의 지상 전투 유닛은 행동 여부와 상관없이 턴당 10씩 회복됩니다.[NEWLINE][NEWLINE]문명 내 모든 도시에서 생성된 [ICON_PEACE] 신앙의 15%가 턴당 [ICON_FOOD] 식량으로 계산됩니다.'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_PEDIA', '예루살렘 성 요한 구호 기사단은 흔히 구호 기사단으로 알려진 이 단체는 11세기에 설립된 중세 가톨릭 군사 기사단으로, 성지에서 병든 순례자와 가난한 이들, 부상자를 돌보는 것을 목적으로 했습니다. 1023년경 아말피 상인들이 조직하여 예루살렘의 세례 요한에게 봉헌된 구호소를 운영하는 데 집중했습니다. 제1차 십자군 전쟁 이후 예루살렘 왕국이 세워지면서, 이 단체는 순례자와 십자군이 획득한 영토를 보호하는 군사적 역할도 갖게 되었습니다. 성 요한 기사단은 중세 시대 가장 강력하고 영향력 있는 군사 기사단 중 하나로, 성지와 지중해의 기독교 영토 방어에 중요한 역할을 했습니다.[NEWLINE][NEWLINE]세월이 흐르면서 정치적, 군사적 상황 변화에 적응했습니다. 1187년 예루살렘이 함락된 후 여러 차례 본부를 옮기다 1309년 로도스 섬에, 1530년에는 몰타 섬에 정착하여 몰타 기사단으로 알려지게 되었습니다. 이 섬에 주둔한 덕분에 오스만 제국의 확장과 해적 행위에 맞서 요새를 강화할 수 있었고, 강력한 해군력을 보유하게 되었습니다. 1798년 나폴레옹에게 몰타를 빼앗긴 후에도 기사단은 자선 활동을 이어갔습니다. 오늘날 몰타 주권 군사 기사단은 전 세계에 지부를 두고 활동하는 인도주의 단체로서, 병든 이와 가난한 이를 돕는 설립 목적을 계속 이어가며 많은 국가와 외교 관계를 맺은 주권 기관으로서의 지위를 유지하고 있습니다.'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_QUOTE', '[NEWLINE]"신앙의 수호와 가난한 이들에 대한 원조"[NEWLINE] - 구호 기사단 모토[NEWLINE]'),
--======================================================================================================================
-- 틀라치우알테페틀
--======================================================================================================================
('TXT_KEY_BUILDING_TLACHIHUALTEPETL', '틀라치우알테페틀'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_HELP', '특수: [COLOR_YIELD_PRODUCTION]성도[ENDCOLOR]. [NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR]로 테오칼리를 제공합니다.[NEWLINE]All Cities earn +10 [ICON_PEACE] Faith, +5 [ICON_GOLDEN_AGE] Golden Age Points and +5 [ICON_GREAT_GENERAL] Great General points when they construct Buildings, scaling with Era.'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_PEDIA', '틀라치우알테페틀은 촐룰라의 대 피라미드로도 알려져 있으며, 멕시코 촐룰라에 위치한 고대 메소아메리카 구조물입니다. 이 피라미드는 세계에서 부피 기준으로 가장 큰 피라미드로 여겨지며, 기자의 대 피라미드보다 더 큽니다. 기원전 3세기경 촐룰라의 원주민들에 의해 여러 단계로 건설되기 시작해 수세기에 걸쳐 확장되었으며, 약 450m x 450m(1,480피트 x 1,480피트)의 기반과 약 66m(217피트)의 높이를 지닙니다. 틀라치우알테페틀이라는 이름은 나와틀어로 "인공 산"을 뜻하는데, 각 문명이 이전 문명 위에 세워지면서 여러 겹의 구조가 형성되었다는 것을 반영합니다. 이 피라미드는 신 케찰코아틀에게 헌정된 중요한 종교적, 의식적 중심지로 아메리카 대륙 콜럼버스 이전 문화에서 중요한 역할을 했습니다.[NEWLINE][NEWLINE]16세기 스페인 정복 당시에는 대부분 버려지고 잡초가 무성해져 자연적인 언덕처럼 덮여 있었습니다. 스페인 사람들은 그 아래의 구조를 알지 못한 채 토착 신앙보다 기독교를 강요하는 상징으로 그 위에 레메디오스 성모마리아 성당을 세웠습니다. 오늘날 틀라치우알테페틀은 고고학적 유적으로 중요한 위치를 차지하며, 피라미드 내부의 터널망을 통해 그 층층이 쌓인 역사를 보여줍니다. 이곳은 히스패닉 이전 시대와 식민지 시대의 유산이 어우러진 문화, 관광 명소로 남아 있으며, 고대 메소아메리카 문명의 건축과 종교적 전통을 증명합니다.'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_QUOTE', '[NEWLINE]"케찰코아틀은 인간 본성의 이중성에 대한 원초적 개념이다. 뱀은 하늘과 땅의 화신이며, 여러모로 사람들을 두렵게 한다."[NEWLINE] - 로버트 그레이엄[NEWLINE]'),
--======================================================================================================================
-- 스타로나바 유대교 회당(프라하의 올드 뉴 시나고그)
--======================================================================================================================
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE', '스타로나바 유대교 회당'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_HELP', ' 특성: [COLOR_CYAN]강[ENDCOLOR], 도시: [COLOR_CYAN]최소 4명의 추종자를 둔 소수 종교[ENDCOLOR][NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 회당을 제공합니다.[NEWLINE]도시에서 15턴의 "[COLOR_POSITIVE_TEXT]국왕 경축일[ENDCOLOR]"을 시작합니다.[NEWLINE]모든 도시에서 "[COLOR_POSITIVE_TEXT]국왕 경축일[ENDCOLOR]" 동안 [ICON_GOLD] 골드, [ICON_CULTURE] 문화, [ICON_PEACE] 신앙이 +10% 증가합니다.'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_PEDIA', '프라하 유대인 지구 중심에 위치한 스타로나바 유대교 회당은 유럽에서 가장 역사적이고 문화적으로 중요한 회당 중 하나입니다. 보헤미아의 오타카르 2세 치세인 1270년대에 지어진 이곳은 유럽에서 가장 오래된 현존하는 회당입니다. 회당의 이름인 "스타로나바(올드 뉴)"는 역사를 반영합니다. 처음 지어졌을 때는 "나바(뉴) 회당"이었지만, 새로운 회당이 지어지면서 새로운 회당과 구별하기 위해 "스타로나바(올드 뉴)"로 알려지게 되었습니다.건축학적으로 이 회당은 고딕 양식의 걸작으로, 독특한 박공지붕과 눈길을 끄는 정면을 특징으로 합니다. 내부는 정교한 석조 조각과 아치형 천장으로 장식되어 엄숙함과 경건함을 자아냅니다.[NEWLINE][NEWLINE]역사적으로 스타로나바 회당은 프라하 유대인 삶에 중추적인 역할을 해왔습니다. 이곳은 수세기 동안 예배, 학습, 공동체의 중심지였으며, 화재, 홍수, 박해 등 수많은 어려움을 겪으면서도 살아남았습니다. 16세기 회당에서 기도했던 유명한 랍비 유다 뢰브 벤 베자렐이 만든 것으로 전해지는 프라하 골렘 전설로도 유명합니다. 오늘날, 스타로나바 회당은 여전히 활발한 예배 장소로 활용되고 있으며, 주요 관광 명소로서 방문객에게 프라하 유대인 공동체의 풍부한 역사와 전통을 엿볼 수 있는 기회를 제공합니다. 이 지속적인 존재는 유럽 내 유대인 삶의 회복력과 문화적 유산을 증명합니다.'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_QUOTE', '[NEWLINE]"유대교는 단순한 표식이나 출생의 흔적이 아니다. 삶이다."[NEWLINE] - 모리스 데이비드 조셉[NEWLINE]'),
--======================================================================================================================
-- 제타바나 승원(제타바나라마야)
--======================================================================================================================
('TXT_KEY_BUILDING_JETAVANARAMAYA', '제타바나 승원'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_HELP', '특성: [COLOR_CYAN]숲/정글[ENDCOLOR], 시설: [COLOR_CYAN]마을[ENDCOLOR] [NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR]로 스투파를 제공합니다.[NEWLINE]모든 도시에서 새로운 [ICON_CITIZEN] 시민이 태어나면 [ICON_FOOD] 식량의 10%가 이월되고, 이 건물이 지어진 도시에서는 추가로 10%가 이월됩니다.[NEWLINE]문명 내 마을의 [ICON_PEACE] 신앙이 +2 증가합니다.'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_PEDIA', '제타바나 승원은 스리랑카 아누라다푸라에 위치한 고대 스투파로, 세계에서 가장 높고 중요한 불교 기념물 중 하나입니다. 서기 3세기 마하세나 왕(재위 277–304년)에 의해 지어졌으며, 상좌부(테라와다) 불교와 대승(마하야나) 불교의 중요한 중심지인 제타바나 승원의 일부였습니다. 한 때 이 스투파는 약 122미터(400피트) 높이로 고대 세계에서 가장 높은 건축물 중 하나였습니다. 주로 벽돌로 만들어진 제타바나 승원은 고대 스리랑카 문명의 뛰어난 공학 기술을 보여주는 지금까지 만들어진 가장 큰 벽돌 구조물 중 하나로 남아 있습니다.[NEWLINE][NEWLINE]수 세기 동안 침략과 방치로 손상되었으나 불교 신자들에게 존경받는 장소로 남아 있습니다. 현대에 이루어진 복원 작업으로 그 웅장함이 보존되었으며, 오늘날에도 중요한 순례지로서 기능합니다. 이 스투파는 승원 건물과 정교한 조각들의 폐허에 둘러싸여 있으며, 아누라다푸라 시대의 건축적, 예술적 성취를 반영합니다.  제타바나 승원은 스리랑카 불교 유산의 상징이자 고대 아누라다푸라 도시의 역사적 중요성의 증명입니다.'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_QUOTE', '[NEWLINE]"행동이 진지하고 말씨가 조용하며 마음이 안정되고 세상의 쾌락을 버린 수행자를 "대자유에 이른 사람" 이라 부른다."[NEWLINE] - 법구경(담마파다), 378절[NEWLINE]'),
--======================================================================================================================
-- 하르만디르 사히브
--======================================================================================================================
('TXT_KEY_BUILDING_HARMANDIR_SAHIB', '하르만디르 사히브'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_HELP', '특수: [COLOR_YIELD_PRODUCTION]성도[ENDCOLOR][NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR]로 구루드와라를 제공합니다.[NEWLINE]문명에서 [ICON_PEACE] 신앙을 제공하는 모든 목욕탕과 건물은 [ICON_FOOD] 식량 +2를 얻습니다.[NEWLINE][NEWLINE]모든 도시에서 종교적 불안으로 인한 [ICON_HAPPINESS_3] 불행이 -1 감소합니다.'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_PEDIA', '하르만디르 사히브는 황금 사원으로도 알려져 있으며, 인도 펀자브 주 암리차르에 위치한 시크교의 가장 신성한 성지입니다. 1581년 네 번째 시크교 구루인 구루 람 다스가 건립했으며, 그의 후계자인 구루 아르잔 데브가 1604년에 완공했습니다. 이 사원은 카스트나 종교에 상관없이 모두에게 열린 영적 예배 장소로 건립되었습니다. 구루 아르잔 데브는 시크교의 중심 경전인 구루 그란트 사히브를 사원 내에 안치하여 시크교 신앙의 영적, 문화적 중심지가 되었습니다. 수 세기 동안 공격을 받았으나 여러 차례 재건되었으며, 19세기 초 마하라자 란지트 싱의 금도금 개조를 거쳐 현재의 상징적인 모습을 갖추었습니다.[NEWLINE][NEWLINE]황금사원은 힌두교와 이슬람 양식이 독특한 시크교 정체성과 융합된 아름다운 건축 걸작입니다. 암리트 사로바르(꿀의 연못)에 둘러싸인 이 사원은 반짝이는 금박으로 덮인 정면과 대리석 장식이 숨 막힐 듯한 광경을 선사합니다. 사원에는 개방성과 포용성을 상징하는 4개의 입구가 있으며, 성소(하르 키 파우리)로 이어지는 보도가 있는데, 성소에서는 구루 그란트 사히브를 계속해서 낭송합니다. 사원 단지에는 시크교 종교 권위의 최고 기관인 아칼 타흐트와 세계 최대 무료 공동 주방인 구루 카 랑가르가 있어 매일 수천 명에게 식사를 제공합니다. 하르만디르 사히브는 시크교의 헌신, 회복력, 보편적 형제애의 상징으로 남아 있습니다.'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_QUOTE', '[NEWLINE]"평화를 주는 이는 영원히 행복하다."[NEWLINE] - 스리 구루 그란트 사히브[NEWLINE]'),
--======================================================================================================================
-- 라라방가
--======================================================================================================================
('TXT_KEY_BUILDING_LARABANGA', '라라방가 모스크'),
('TXT_KEY_BUILDING_LARABANGA_HELP', '지형: [COLOR_CYAN]평원[ENDCOLOR], 건물: [COLOR_CYAN]세관[ENDCOLOR][NEWLINE][NEWLINE]이 건물이 지어진 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 모스크를 제공합니다.[NEWLINE]교역로로 연결된 도시에 대한 종교적 압력이 +100% 증가합니다.[NEWLINE]모든 [ICON_INTERNATIONAL_TRADE] 국제 교역로에서 [ICON_GOLD] 금 +3, [ICON_PEACE] 신앙 +3이 제공됩니다.'),
('TXT_KEY_BUILDING_LARABANGA_PEDIA', '가나 북부에 위치한 라라방가 모스크는 서아프리카에서 가장 오래되고 존경받는 이슬람 유적 중 하나입니다. 15세기에 세워졌으며, 전설에 따르면 이슬람 상인 아유바가 신의 인도로 이 모스크를 건립했다고 전해집니다. 이 모스크는 지역 내 이슬람 전파에 중요한 역할을 했으며, 오늘날에도 이슬람 학문과 예배의 중심지로 남아 있습니다. 역사적 중요성과 사하라 사막을 횡단하는 초기 무역로와의 연관성으로 인해 이곳은 가나의 주요 문화적, 종교적 명소가 되었습니다. 수세기 동안 날씨 피해와 복원 작업 등 구조적 어려움을 겪었으나, 여전히 활발한 기도와 순례 장소로 기능합니다.[NEWLINE][NEWLINE]건축학적으로 라라방가 모스크는 수단-사하라 양식의 눈에 띄는 사례로, 하얗게 칠해진 진흙 벽과 목재로 보강된 틀이 특징입니다.두 개의 눈에 띄는 탑이 있는데, 하나는 미나레트(탑), 다른 하나는 미흐랍(메카를 향한 기도 공간)입니다. 모스크는 단단한 직사각형 형태와 버팀벽으로 요새 같은 독특한 외관을 갖추고 있습니다. 나무 들보는 구조물에서 튀어나와 있는데, 이는 미적인 가치뿐만 아니라 유지 보수에 도움이 되고 지지력을 제공하기도 합니다. 단순하면서도 우아한 디자인은 이슬람 건축이 지역 환경과 재료에 적응한 모습을 반영합니다. 오늘날 라라방가 모스크는 존경받는 영적 장소이자 가나 이슬람 유산의 중요한 상징으로 남아 있습니다.'),
('TXT_KEY_BUILDING_LARABANGA_QUOTE', '[NEWLINE]"너희에게 있는 것은 사라지나 하나님께 있는 것은 영원하노라."[NEWLINE]- 꾸란(16:96)[NEWLINE]'),
--======================================================================================================================
-- 파도바 식물원(Orto botanico di Padova)
--======================================================================================================================
('TXT_KEY_BUILDING_PADUA_GARDEN', '파도바 식물원'),
('TXT_KEY_BUILDING_PADUA_GARDEN_HELP', '시설 자원: [COLOR_CYAN]재배지 자원[ENDCOLOR], 건물: [COLOR_CYAN]정원[ENDCOLOR]. [NEWLINE][NEWLINE]모든 정원의 [ICON_FOOD] 식량이 +2 증가하고, [ICON_RESEARCH] 과학도 +2 증가합니다.[NEWLINE]모든 재배지 자원: [ICON_RESEARCH] 과학 +1[NEWLINE]문명 내 모든 아카데미의 [ICON_FOOD] 식량이 +3 증가합니다.'),
('TXT_KEY_BUILDING_PADUA_GARDEN_PEDIA', '파도바 식물원은 1545년에 설립된 세계에서 가장 오래된 학술 식물원으로, 설립 당시 위치를 그대로 유지하고 있습니다. 이탈리아 파도바에 위치하며, 르네상스 시대 자연과학과 약용 식물에 대한 관심이 커짐에 따라 약용 식물 연구를 위해 만들어졌습니다. 처음에는 의료 목적으로 사용되는 식물의 재배와 분류에 집중하여, 파도바 대학의 의대생에게 필수적인 자료를 제공했습니다. 세계를 상징하는 원형 중앙 구획과 그 주위에 기하학적으로 배치된 작은 화단 디자인은 전 세계 식물원 배치에 영향을 주었습니다.[NEWLINE][NEWLINE]수세기에 걸쳐 파도바 식물원은 전 세계 식물 종을 폭넓게 수집하며 뛰어난 식물 다양성을 보여주고 있습니다. 6,000종 이상의 식물이 살고 있으며 희귀 및 멸종 위기 식물도 포함되어 있습니다. 지구의 다양한 생태계를 강조하는 생물다양성 정원 등 여러 주제별로 구역이 나뉘어 있습니다. 이 식물원은 식물학 연구와 교육에 중추적인 역할을 하였으며 식물학 연구에 크게 기여했습니다. 1997년에 그 역사적, 과학적 중요성으로 유네스코 세계문화유산으로 지정되었습니다. 오늘날에도 연구, 보전, 대중교육의 중요한 중심지로서 전 세계의 학자, 학생, 자연 애호가들을 끌어 모으고 있습니다.'),
('TXT_KEY_BUILDING_PADUA_GARDEN_QUOTE', '[NEWLINE]"정원과 도서관이 있으면 필요한 모든 것을 가진 것이다."[NEWLINE] - 마르쿠스 툴리우스 키케로[NEWLINE]'),
--======================================================================================================================
-- 창덕궁
--======================================================================================================================
('TXT_KEY_BUILDING_CHANGDEOKGUNG', '창덕궁'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_HELP', '지형: [COLOR_CYAN]언덕[ENDCOLOR][NEWLINE][NEWLINE]선택 가능한 무료 [ICON_GREAT_PEOPLE] [COLOR_POSITIVE_TEXT]위인[ENDCOLOR]을 1명 받습니다. [NEWLINE]모든 목욕탕과 정원의 [ICON_HAPPINESS_1] 행복도가 +1 증가합니다.[NEWLINE]문명 내 모든 [ICON_CSD_CIVIL_SERVANT] 공무원 전문가로부터 [ICON_PRODUCTION] 생산력 +2, [ICON_GOLDEN_AGE] 황금기 점수 +2를 받습니다.'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_PEDIA', '창덕궁은 대한민국 서울에 위치한 조선 시대 "5대 궁궐" 중 하나로, 자연 경관과 조화를 이루는 아름다움으로 유명합니다. 1405년에 건립된 후 많은 조선 왕들의 주요 거처였으며, 고요하고 아름다운 주변 환경 덕분에 많은 사람의 사랑을 받았습니다. 다른 궁궐들이 엄격한 기하학적 배치를 따르는 반면, 창덕궁은 부지의 지형과 자연스럽게 어우러지도록 설계되어 여러 정자, 안뜰, 정원이 지형의 윤곽을 따라 배치되어 있습니다. 이는 자연과의 조화를 중시하는 한국 전통 철학을 반영합니다.[NEWLINE][NEWLINE]창덕궁의 가장 주목할 만한 특징 중 하나는 후원, 즉 "비원"으로 왕실 가족이 여가와 휴식을 위해 사용한 78 에이커(약 31.5만 제곱미터) 규모의 정원입니다. 연못, 정자, 다양한 나무와 꽃들로 정교하게 조경되어 궁중 생활의 스트레스에서 벗어나 평온한 휴식을 취할 수 있는 공간을 제공합니다.  창덕궁의 독특한 설계와 역사적 중요성으로 인해 1997년에 유네스코 세계문화유산으로 지정되었습니다. 이 궁궐 단지는 조선 시대의 미학과 철학적 가치를 대표할 뿐 아니라 문화적, 건축적 보물로서 수많은 방문객이 그 시대를 뛰어넘는 아름다움과 역사적 중요성을 알고자 찾고 있습니다.'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_QUOTE', '[NEWLINE]"종교 없는 천재성은 궁전의 바깥문에 놓인 등불일 뿐이다."[NEWLINE] - 한나 모어[NEWLINE]'),
--======================================================================================================================
-- 담넌 사두악
--======================================================================================================================
('TXT_KEY_BUILDING_DAMNOEN_SADUAK', '담넌 사두악'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_HELP', '특성: [COLOR_CYAN]강[ENDCOLOR], 건물: [COLOR_CYAN]식료품점[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_MERCHANT] Great Merchant. [NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold, +1 [ICON_CULTURE] Culture from nearby River tiles. [NEWLINE]+2 [ICON_FOOD] Food, +2 [ICON_CULTURE] Culture from all [ICON_VP_MERCHANT] Merchant Specialists in your Empire. [NEWLINE]All Markets and Grocers gain +2 [ICON_GOLD] Gold, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_PEDIA', 'Damnoen Saduak Floating Market, located in Ratchaburi Province, Thailand, about 100 kilometers southwest of Bangkok, is one of the most famous and vibrant floating markets in the country. Established in the 19th century during the reign of King Rama IV, the market has become a quintessential representation of traditional Thai commerce and culture. Vendors, primarily women wearing wide-brimmed straw hats, paddle small wooden boats laden with fresh produce, local delicacies, and handicrafts through a network of canals. This lively waterborne marketplace offers visitors a glimpse into the traditional way of life in Thailand, where waterways were once the primary means of transportation and trade. [NEWLINE][NEWLINE]The bustling atmosphere of Damnoen Saduak Floating Market attracts numerous tourists who come to experience the unique shopping environment and enjoy the array of sights, sounds, and flavors. Visitors can sample an assortment of Thai street foods directly from the boats, such as pad thai, mango sticky rice, and freshly squeezed coconut juice, while exploring stalls selling souvenirs and handmade goods along the canal banks. The market''s picturesque setting and dynamic activity provide ample opportunities for photography and cultural immersion. Despite its popularity with tourists, Damnoen Saduak remains a working market for locals, maintaining its authenticity and charm as a vibrant hub of daily life and commerce in rural Thailand.'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_QUOTE', '[NEWLINE]"Ideas, like large rivers, never have just one source."[NEWLINE] - Willy Ley[NEWLINE]'),
--======================================================================================================================
-- Paro Taktsang
--======================================================================================================================
('TXT_KEY_BUILDING_TAKTSANG', 'Paro Taktsang'),
('TXT_KEY_BUILDING_TAKTSANG_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR].[NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Monastery in the City in which it is built. [NEWLINE]Place a Holy Site on a nearby mountain that yields additional +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production.'),
('TXT_KEY_BUILDING_TAKTSANG_PEDIA', 'Paro Taktsang, also known as the Tiger''s Nest Monastery, is a sacred Buddhist site perched dramatically on a cliffside in Bhutan''s Paro Valley. Built in 1692, the monastery is said to mark the meditation site of Guru Padmasambhava, the legendary 8th-century Buddhist master who introduced Vajrayana Buddhism to Bhutan. According to legend, Padmasambhava flew to the site on the back of a tigress, giving the monastery its famous name. The complex consists of multiple temples and meditation caves, blending seamlessly with the rugged cliffs at an elevation of about 3,120 meters (10,240 feet). The monastery is a major pilgrimage site and an iconic symbol of Bhutanese culture and spirituality. [NEWLINE][NEWLINE]Despite its remote location, Paro Taktsang has been carefully preserved and rebuilt after suffering significant damage from a fire in 1998. Accessible only by a steep mountain trail, the monastery remains a place of deep spiritual significance and offers breathtaking views of the surrounding valley. The site is visited by thousands of pilgrims and tourists each year, drawn by its mystical history, stunning architecture, and serene atmosphere. Paro Taktsang stands as a testament to Bhutan’s strong Buddhist traditions and its commitment to preserving sacred heritage in harmony with nature.'),
('TXT_KEY_BUILDING_TAKTSANG_QUOTE', '[NEWLINE]"There are many paths to the top of the mountain, yet the view is always the same"[NEWLINE] - Chinese Proverb[NEWLINE]'),
--======================================================================================================================
-- Keshgarh Qila
--======================================================================================================================
('TXT_KEY_BUILDING_KESHGARH_QILA', 'Keshgarh Qila'),
('TXT_KEY_BUILDING_KESHGARH_QILA_HELP', 'Terrain: [COLOR_CYAN]Grassland[ENDCOLOR]; Improvement: [COLOR_CYAN]Fort[ENDCOLOR]. [NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Gurdwara in the City in which it is built. [NEWLINE]+25% [ICON_PRODUCTION] Production of Land Melee Units in all Cities. [NEWLINE]Increases [ICON_SILVER_FIST] Military Unit Supply Cap by 5.'),
('TXT_KEY_BUILDING_KESHGARH_QILA_PEDIA', 'Takht Keshgarh Sahib or Keshgarh Qila is one of the five Takhts (temporal seats) of Sikhism and is located in Anandpur Sahib, Punjab, India. It holds immense historical and religious significance as the birthplace of the Khalsa, the Sikh warrior community, which was founded by Guru Gobind Singh Ji on Vaisakhi in 1699. During this event, Guru Gobind Singh initiated the first Panj Pyare (Five Beloved Ones) and introduced the Amrit Sanchar (Sikh baptism ceremony), establishing the Khalsa''s distinct identity. The Kesgarh Fort, which once stood on this site, was a crucial defense post during battles between the Sikhs and Mughal forces. The Takht Sahib houses many relics of Guru Gobind Singh, including weapons used by him and the Khalsa warriors. [NEWLINE][NEWLINE]Today, Takht Kesgarh Sahib is a major pilgrimage site for Sikhs and a symbol of their martial and spiritual heritage. The Gurdwara is built on a hilltop, offering a panoramic view of Anandpur Sahib and the surrounding Shivalik hills. The main shrine features a grand Darbar Hall, where daily prayers and kirtans (devotional songs) take place. Sikhs from around the world visit the Takht, especially during Vaisakhi celebrations, to honor the legacy of Guru Gobind Singh and the founding of the Khalsa. It remains a center of Sikh faith, resilience, and unity.'),
('TXT_KEY_BUILDING_KESHGARH_QILA_QUOTE', '[NEWLINE]"He who has no faith in himself can never have faith in God."[NEWLINE] - Guru Nanak[NEWLINE]'),
--======================================================================================================================
-- Citadelle Laferrière
--======================================================================================================================
('TXT_KEY_BUILDING_LAFERRIERE', 'Citadelle Laferrière'),
('TXT_KEY_BUILDING_LAFERRIERE_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]; Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_GENERAL] Great General.  [NEWLINE]All Siege Units in the Empire get [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_LAFERRIERE}[ENDCOLOR] promotion. [NEWLINE]All Forts, Citadels and unique improvements replacing them in the Empire receive +2 [ICON_FOOD] Food, +2 [ICON_PRODUCTION] Production, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_LAFERRIERE_PEDIA', 'Citadelle Laferrière, located in northern Haiti atop the Bonnet à l''Évêque mountain, is a monumental fortress and a symbol of Haitian independence and resilience. Constructed between 1805 and 1820 under the leadership of Henri Christophe, a key figure in the Haitian Revolution who later became king of northern Haiti, the citadel was built to defend against potential French invasions after Haiti won its independence in 1804. The fortress is an architectural marvel, featuring massive walls, impressive battlements, and an array of cannons and artillery, many of which remain in place today. Its strategic location, perched 900 meters above sea level, offers sweeping views of the surrounding landscape and the Atlantic Ocean, making it a formidable defensive structure. [NEWLINE][NEWLINE]The Citadelle Laferrière, along with the nearby Sans-Souci Palace, is a UNESCO World Heritage Site, recognized for its historical significance and outstanding representation of early 19th-century military architecture. The fortress is not only a testament to the ingenuity and determination of the Haitian people but also a poignant reminder of their struggle for freedom and self-determination. Today, it stands as a major cultural and tourist attraction, drawing visitors from around the world who come to explore its vast corridors, storerooms, and dungeons, and to learn about Haiti''s rich history. The Citadelle Laferrière remains a potent symbol of national pride and a powerful monument to the enduring spirit of independence.'),
('TXT_KEY_BUILDING_LAFERRIERE_QUOTE', '[NEWLINE]"Those who make peaceful revolution impossible will make violent revolution inevitable."[NEWLINE] - John F. Kennedy[NEWLINE]'),
('TXT_KEY_PROMOTION_LAFERRIERE', 'Unity is Strength'),
('TXT_KEY_PROMOTION_LAFERRIERE_HELP', '+25%[ICON_STRENGTH] Combat Strength. +1 [ICON_MOVES]Movement. Can Move After Attacking. [NEWLINE]+25%[ICON_STRENGTH] Combat Strength against Naval Units.'),
--======================================================================================================================
-- Victoria Terminus / Chhatrapati Shivaji Terminus
--======================================================================================================================
('TXT_KEY_BUILDING_VICTORIA_TERMINUS', 'Chhatrapati Shivaji Terminus'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_HELP', 'Special: [COLOR_YIELD_FOOD]Industrial City Connection[ENDCOLOR]; City: [COLOR_CYAN]18 Citizens[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Coaling Station in the City in which it is built and 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_RES_COAL] Coal. [NEWLINE]+15% [ICON_GOLD] Gold from [ICON_CONNECTED] City Connections and +15% [ICON_PRODUCTION] Production from [ICON_INDUSTRIAL_CONNECTED] Industrial City Connections. [NEWLINE][ICON_CONNECTED] City connections generate +5 [ICON_CULTURE] Culture. [NEWLINE]+100% [ICON_FOOD] Food or [ICON_PRODUCTION] Production from Internal Trade Routes.'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_PEDIA', 'Chhatrapati Shivaji Terminus (CST), formerly known as Victoria Terminus, is a historic railway station in Mumbai, India. Designed by British architect Frederick William Stevens, it was completed in 1887 to commemorate Queen Victoria’s Golden Jubilee. The station became a symbol of Mumbai’s rapid industrialization and was a key hub for the Great Indian Peninsula Railway. Over the years, it played a crucial role in the city’s economic and social growth, serving as a gateway for trade and migration. In 2004, CST was designated a UNESCO World Heritage Site, recognizing its architectural splendor and historical significance. [NEWLINE][NEWLINE]Architecturally, Chhatrapati Shivaji Terminus is a stunning blend of Victorian Gothic Revival and traditional Indian styles. The station features intricate stone carvings, domes, turrets, and pointed arches, inspired by medieval European cathedrals. A striking central dome with ribbed vaulting and a towering spire dominates the skyline, while the interior boasts a grand staircase, stained glass windows, and decorative ironwork. The station remains one of India’s busiest railway hubs, handling millions of passengers daily. Despite modern developments, CST retains its historic charm, standing as a testament to Mumbai’s colonial past and enduring vibrancy.'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_QUOTE', '[NEWLINE]"Railway termini are our gates to the glorious and the unknown. Through them we pass out into adventure and sunshine, to them, alas! we return."[NEWLINE] - Edward Morgan Forster[NEWLINE]'),
--======================================================================================================================
-- Capitoline Museums
--======================================================================================================================
('TXT_KEY_BUILDING_CAPITOLINE', 'Capitoline Museums'),
('TXT_KEY_BUILDING_CAPITOLINE_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Museum in the City in which it is built. [NEWLINE]+2 [ICON_CULTURE] Culture, [ICON_GOLDEN_AGE] Golden Age points from nearby Hills. [NEWLINE]Archaeologists can be purchased with [ICON_GOLD] Gold, gain +1 [ICON_MOVES] Movement, and have double Work rate. [NEWLINE]+4 [ICON_CULTURE] Culture, [ICON_RESEARCH] Science, and [ICON_TOURISM] Tourism if [COLOR_POSITIVE_TEXT]Themed[ENDCOLOR].'),
('TXT_KEY_BUILDING_CAPITOLINE_PEDIA', 'The Capitoline Museums, located on Rome''s Capitoline Hill, are the oldest public museums in the world, tracing their origins to 1471 when Pope Sixtus IV donated a collection of important bronze statues to the people of Rome. This act laid the foundation for the museums, which were officially opened to the public in 1734 by Pope Clement XII. The museums comprise three main buildings: the Palazzo dei Conservatori, the Palazzo Nuovo, and the Centrale Montemartini. These buildings house an extensive collection of classical sculptures, ancient Roman artifacts, Renaissance and Baroque art, and other historical pieces that reflect Rome''s rich cultural heritage. [NEWLINE][NEWLINE]Among the most notable exhibits in the Capitoline Museums are the iconic statue of the she-wolf suckling Romulus and Remus, the symbol of Rome; the colossal statue of Emperor Constantine; and the Dying Gaul, a celebrated ancient Roman sculpture. The museums also feature works by renowned artists such as Caravaggio, Titian, and Rubens. Additionally, the Capitoline Museums offer breathtaking views of the Roman Forum and surrounding areas from the Piazza del Campidoglio, designed by Michelangelo. The blend of art, history, and stunning architecture makes the Capitoline Museums a vital cultural and historical institution, attracting visitors from around the globe who seek to immerse themselves in the legacy of ancient Rome and the evolution of Western art.'),
('TXT_KEY_BUILDING_CAPITOLINE_QUOTE', '[NEWLINE]"Rome is not like any other city. It''s a big museum, a living room that shall be crossed on one''s toes."[NEWLINE] - Alberto Sordi[NEWLINE]'),
('TXT_KEY_THEMING_BONUS_CAPITOLINE', 'Wonders of Rome'),
('TXT_KEY_THEMING_BONUS_CAPITOLINE_HELP', 'To maximize your bonus, make sure all the Great Work Slots are filled.'),
--======================================================================================================================
-- Muzibu Azaala Mpanga
--======================================================================================================================
('TXT_KEY_BUILDING_KASUBI_TOMBS', 'Muzibu Azaala Mpanga'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_HELP', 'Feature: [COLOR_CYAN]Lake[ENDCOLOR]. [NEWLINE][NEWLINE]+75 [ICON_PEACE] Faith when you expend a [ICON_GREAT_PEOPLE] Great Person, scaling with Era. [NEWLINE]+2 [ICON_TOURISM] Tourism on Lakes worked by this City.[NEWLINE]All Lakes in the Empire receive +2 [ICON_FOOD] Food, +2 [ICON_GOLDEN_AGE] Golden Age Points, +2 [ICON_GREAT_GENERAL] Great General points.'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_PEDIA', 'The Muzibu Azaala Mpanga is a magnificent royal tomb located at the Kasubi Tombs complex in Kampala, Uganda. Built in 1882, it serves as the burial site for four Kabakas (kings) of Buganda: Mutesa I, Mwanga II, Daudi Chwa II, and Edward Mutesa II. The structure is renowned for its extraordinary architectural design, featuring a massive circular thatched dome that reaches over 30 feet high. As a masterpiece of Ganda architecture and craftsmanship, it was designated a UNESCO World Heritage Site in 2001, recognizing its cultural significance and unique construction techniques. [NEWLINE][NEWLINE]The tomb''s interior is divided by a series of bark cloth curtains, creating sacred spaces where the kings'' remains are housed in separate chambers alongside royal regalia. Despite suffering a devastating fire in 2010 that destroyed much of the original structure, extensive restoration efforts were undertaken to rebuild it according to traditional methods, using materials like reeds, grass, and wood without nails. The Muzibu Azaala Mpanga continues to function as both a spiritual center for the Baganda people and a powerful symbol of indigenous knowledge, cultural identity, and the enduring legacy of the Buganda Kingdom.'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_QUOTE', '[NEWLINE]"Princes are like pythons. They swallow each other."[NEWLINE] - Ugandan Proverb[NEWLINE]'),
--======================================================================================================================
-- Golden Gate Bridge
--======================================================================================================================
('TXT_KEY_BUILDING_GOLDEN_GATE', 'Golden Gate Bridge'),
('TXT_KEY_BUILDING_GOLDEN_GATE_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_ENGINEER] Great Engineer. [NEWLINE]+10% [ICON_PRODUCTION] Production in all Cities. [NEWLINE]All International Trade Routes provide +5 [ICON_GOLDEN_AGE] Golden Age Points. [NEWLINE]+10 [ICON_INFLUENCE] Influence with all known City-States when you expend [ICON_GREAT_PEOPLE] Great People.'),
('TXT_KEY_BUILDING_GOLDEN_GATE_PEDIA', 'The Golden Gate Bridge, an iconic symbol of San Francisco, was completed in 1937 after four years of construction. Spanning the Golden Gate Strait, the 1.7-mile (2.7 km) bridge connects San Francisco to Marin County. Designed by Joseph Strauss, with significant contributions from engineers Leon Moisseiff and Irving Morrow, it was the longest and tallest suspension bridge in the world at the time of its completion. The bridge’s construction faced numerous challenges, including strong ocean currents, deep waters, and frequent fog, but advancements in safety measures—such as the use of a safety net—helped reduce worker fatalities. [NEWLINE][NEWLINE]The Golden Gate Bridge is famous for its Art Deco design and distinctive International Orange color, chosen for visibility in fog and aesthetic appeal. Today, it remains one of the most photographed landmarks in the world, carrying millions of vehicles annually and serving as both a critical transportation link and a tourist attraction. The bridge also plays a vital role in engineering history, inspiring modern bridge design. Despite the harsh marine environment, ongoing maintenance ensures its longevity. Whether admired from afar or walked across for stunning views of the San Francisco Bay, the Golden Gate Bridge remains a testament to human ingenuity and ambition.'),
('TXT_KEY_BUILDING_GOLDEN_GATE_QUOTE', '[NEWLINE]"To reach a port, we must sail. Sail, not tie at anchor. Sail, not drift."[NEWLINE] - Franklin D. Roosevelt[NEWLINE]'),
--======================================================================================================================
-- Te Tii Marae
--======================================================================================================================
('TXT_KEY_BUILDING_TE_TII_MARAE', 'Te Tii Marae'),
('TXT_KEY_BUILDING_TE_TII_MARAE_HELP', 'Building anywhere: [COLOR_CYAN]Courthouse[ENDCOLOR]. [NEWLINE][NEWLINE]All Courthouses gain +3 [ICON_PRODUCTION] Production, 1 [ICON_HAPPINESS_1] Happiness. [NEWLINE]Has 1 slot for [ICON_VP_GREATWRITING] Great Work of Writing, and starts with [ICON_VP_GREATWRITING] [COLOR_CULTURE_STORED]Treaty of Watangi[ENDCOLOR]. [NEWLINE]Every [ICON_VP_GREATWRITING] Great Work of Writing in this City grants +5 XP to all created Units (maximum of 45 XP).'),
('TXT_KEY_BUILDING_TE_TII_MARAE_PEDIA', 'Te Tii Marae is a unique meeting center. Like other marae in the Pacific, it served as both a sacred place for religion and a social meeting place in Polynesian culture. The term "marae" - mala''e in Tongan and malae in Samoan and Hawaiian - means "cleared, free of weeds and trees". In the Maori society the marae is where the culture flourishes; obligations between tribes are met there, families would hold certain occasions there, and important ceremonies are held there.[NEWLINE][NEWLINE]Te Tii Marae is more than that, however. The site is still in use today as part of Waitangi Day, the New Zealand holiday to commemorate the signing of the Treaty of Waitangi. On February 6 1840 the treaty was signed in a marquee at the grounds of James Busby''s house - now known as the Treaty House, making New Zealand part of the British Empire and ensuring the right of the Maori to their land and their rights as British subjects. However this had led to disagreements between the Europeans and Maori. The Maori view the treaty as a sacred pact, while the Pakeha - Maori for European New Zealanders - have taken disregard to it for many years. Chief Justice James Prendergast declared the treaty a "legal nullity" in 1877, displaying the European disconcern of the treaty until the Treaty of Waitangi Act in 1975 - almost a century later.[NEWLINE][NEWLINE]Today Te Tii Marae hosts the annual celebrations the day before Waitangi Day - Feburary 5 - where the New Zealander Prime Minister and other political figures are invited to the site and hears the speeches of the iwi - the large social group of Maori society. With celebration comes tensions between the two peoples as Waidangi Day is also a hotspot for Maori rights; as far back as 1971 Waitangi and the day have been marred by protests and activism concerning the treaty.'),
('TXT_KEY_BUILDING_TE_TII_MARAE_QUOTE', '[NEWLINE]"When what is not Maori is Pakeha and what is not Pakeha is Maori, I occupy the gap between the two, that black hole in which nothing can be seen and from which nothing can be heard."[NEWLINE] - Annamarie Jagose[NEWLINE]'),
('TXT_KEY_GREAT_WORK_TREATY_WATANGI', 'Treaty of Watangi'),
('TXT_KEY_GREAT_WORK_TREATY_WATANGI_QUOTE', '[NEWLINE]"Her Majesty the Queen of England extends to the Natives of New Zealand Her royal protection and imparts to them all the Rights and Privileges of British Subjects."[NEWLINE] - Treaty of Watangi[NEWLINE]'),
--======================================================================================================================
-- Changi Airport
--======================================================================================================================
('TXT_KEY_BUILDING_CHANGI_AIRPORT', 'Changi Airport'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_HELP', 'Special: [COLOR_YIELD_GOLD]Capital[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Airport in the City in which it is built. [NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_MERCHANT] Great Merchant. [NEWLINE]All Airports gain +2 [ICON_PRODUCTION] Production, +2 [ICON_GOLD] Gold, +2 [ICON_TOURISM] Tourism, +2 [ICON_GOLDEN_AGE] Golden Age points. [NEWLINE]All cities get +1 Air Unit Slot.'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_PEDIA', 'Singapore Changi Airport, often regarded as one of the world''s best airports, opened on 1 July 1981 to replace Paya Lebar Airport as Singapore''s main international gateway. The airport was built on reclaimed land in Changi, on the eastern tip of the island, and has since expanded into a global aviation hub. Over the years, it has undergone multiple expansions, growing from a single terminal to four main terminals, with the addition of Jewel Changi Airport in 2019—a lifestyle complex featuring gardens, retail, and the world''s tallest indoor waterfall. Changi Airport is known for its efficiency, top-tier passenger services, and extensive connectivity, serving over 100 airlines and linking Singapore to more than 400 cities worldwide. [NEWLINE][NEWLINE]Beyond being a transit hub, Changi Airport is an iconic destination offering world-class amenities, including themed gardens, movie theaters, free rest zones, and luxury shopping. It consistently ranks as one of the world''s busiest and most awarded airports, handling over 68 million passengers annually before the pandemic. The airport is also a key economic driver for Singapore, supporting its tourism and logistics industries. With future expansions, including the upcoming Terminal 5, Changi Airport aims to reinforce its position as a premier global air travel hub while embracing sustainability and innovation.'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_QUOTE', '[NEWLINE]"There was nowhere to go but everywhere, so just keep on rolling under the stars."[NEWLINE] - Jack Kerouac[NEWLINE]'),
--======================================================================================================================
-- Watson Research Center
--======================================================================================================================
('TXT_KEY_BUILDING_WATSON_RC', 'Watson Research Center'),
('TXT_KEY_BUILDING_WATSON_RC_HELP', 'Plot: [COLOR_CYAN]Flat[ENDCOLOR]; Building: [COLOR_CYAN]Research Lab[ENDCOLOR]. [NEWLINE][NEWLINE]+10% [ICON_RESEARCH] Science in your Empire. [NEWLINE]10% of [ICON_RESEARCH] Science created by all Cities on Empire counts as [ICON_PRODUCTION] Production Per Turn. [NEWLINE]All Manufactories and Towns in the Empire receive +4 [ICON_RESEARCH] Science.'),
('TXT_KEY_BUILDING_WATSON_RC_PEDIA', 'The Thomas J. Watson Research Center is IBM''s principal research facility, named after the company''s former CEO, Thomas J. Watson, Sr. Established in 1961, the center serves as the heart of IBM Research, focusing on cutting-edge advancements in computing, artificial intelligence, quantum computing, and semiconductor technology. The main campus, located in Yorktown Heights, New York, was designed by renowned architect Eero Saarinen, featuring a futuristic, wave-like structure that symbolizes innovation. Additional IBM research labs associated with the center are in Cambridge, Massachusetts, and Almaden, California. Over the decades, the Watson Research Center has contributed to groundbreaking developments, including IBM''s Deep Blue, which famously defeated chess champion Garry Kasparov in 1997, and Watson AI, which won Jeopardy! in 2011. [NEWLINE][NEWLINE]As a global leader in scientific and technological research, the Watson Research Center continues to drive advancements in cloud computing, cybersecurity, AI ethics, and quantum computing. The facility collaborates with universities, governments, and enterprises to push the boundaries of innovation. IBM''s quantum computing research, headquartered at Watson, is pioneering quantum processors that could revolutionize fields such as cryptography and materials science. With a strong emphasis on fundamental and applied research, the Watson Research Center remains at the forefront of technological breakthroughs, shaping the future of computing and artificial intelligence.'),
('TXT_KEY_BUILDING_WATSON_RC_QUOTE', '[NEWLINE]"If we knew what we were doing, it wouldn''t be called research."[NEWLINE] - Albert Einstein[NEWLINE]');
--======================================================================================================================
INSERT INTO Language_ko_KR 
				(Tag,										Text) 
SELECT DISTINCT	'TXT_KEY_BUILDING_'||b.WType||'_HELP_CUT',	Text
FROM Language_ko_KR a, JHWfVPConfig b WHERE a.Tag = 'TXT_KEY_BUILDING_'||b.WType||'_HELP';
--======================================================================================================================
--======================================================================================================================