--======================================================================================================================
-- Language_ko_KR
--======================================================================================================================
INSERT OR REPLACE INTO Language_ko_KR (Tag, Text) VALUES
-- 켈두르 홀
('TXT_KEY_BUILDING_KELDUR_HALL', '켈두르 홀'),
('TXT_KEY_BUILDING_KELDUR_HALL_HELP', '지형: [COLOR_CYAN]툰드라[ENDCOLOR]; [COLOR_NEGATIVE_TEXT]평원[ENDCOLOR] [NEWLINE][NEWLINE][ICON_FOOD]인접한 툰드라 타일마다 식량 +1, [ICON_PRODUCTION] 생산력 +1[NEWLINE]인접한 눈 타일마다 도시 내 [ICON_FOOD] 식량 +1, [ICON_PRODUCTION] 생산력 +1[NEWLINE]문명 내 모든 마을에[ICON_FOOD] 식량 +2[NEWLINE]모든 도시의 [ICON_RESEARCH] 과학 산출량의 10%가 턴당 [ICON_FOOD] 식량으로 추가됩니다.'),
('TXT_KEY_BUILDING_KELDUR_HALL_PEDIA', '켈두르 홀은 아이슬란드 남부에 위치한 유서 깊은 잔디집으로, 독특한 건축 양식과 깊은 문화적 의미로 유명합니다. 12세기로 거슬러 올라가는 이 건물은 아이슬란드에서 현존하는 가장 오래된 농가 중 하나입니다. 전통적인 아이슬란드 방식으로 지어진 이 건물은 잔디 벽과 목재 구조로 이루어져 있어 혹독한 날씨를 견딜 수 있도록 설계되었습니다. 이 홀은 한때 유력한 족장들이 거주하던 곳으로, 강력한 오디 씨족과 관련이 있는 것으로 여겨집니다. 탈출 또는 저장 용도로 사용되었을 가능성이 있는 지하 통로는 이곳의 신비로움과 역사적 매력을 더해줍니다.[NEWLINE][NEWLINE]오랜 역사 속에서 켈두르는 사가 시대를 포함한 아이슬란드 중세의 산증인이었습니다. 고유의 모습 유지를 위한 신중한 보존 작업이 이루어졌으며, 이를 통해 방문객들은 초기 아이슬란드 농촌 생활을 엿볼 수 있습니다. 현재는 아이슬란드 국립박물관이 관리하며, 문화유산지로 지정되어 있습니다. 관광객들과 역사 애호가들은 이곳의 소박한 매력에 매료되어 과거 주민들의 이야기를 접하고 수세기 동안 거의 변하지 않은 주변 풍경을 탐방합니다.'),
('TXT_KEY_BUILDING_KELDUR_HALL_QUOTE', '[NEWLINE]"겨울밖에 모르고 살아온 사람의 마음은 정말 차가워질 수 있다."[NEWLINE] - 벤자민 알리레 사엔스[NEWLINE]'),
--======================================================================================================================
-- 니피사트
--======================================================================================================================
('TXT_KEY_BUILDING_NIPISAT', '니피사트'),
('TXT_KEY_BUILDING_NIPISAT_HELP', '지형: [COLOR_CYAN]툰드라[ENDCOLOR]; [COLOR_CYAN]해안[ENDCOLOR][NEWLINE][NEWLINE]인접한 툰드라 타일마다 [ICON_GOLD] 골드 +1[NEWLINE]인접한 눈 타일마다 [ICON_FOOD] 식량  +1, [ICON_GOLD] 골드 +1[NEWLINE]문명 내 모든 어선에 [ICON_PRODUCTION] 생산력 +1, [ICON_CULTURE_LOCAL] 국경 확장 +1[NEWLINE][COLOR_CYAN]고고학[ENDCOLOR] 발견 시 [ICON_CULTURE] 문화 +6[NEWLINE][NEWLINE]모든 [ICON_RES_DEER] 사슴 자원: [ICON_PRODUCTION] 생산력 +1, [ICON_CULTURE] 문화 +1'),
('TXT_KEY_BUILDING_NIPISAT_PEDIA', '그린란드 서해안 시시미우트 근처에 위치한 니피사트는 북극 선사 문화에 대한 통찰을 제공하는 중요한 고고학 유적지입니다. 약 4,000년 전으로 거슬러 올라가는 사카크(Saqqaq) 문화의 유적이 광범위하게 남아 있는 곳으로, 북극 초기 거주민들의 생활 방식, 생계 수단, 기술 등을 잘 보여주는 가장 보존 상태가 뛰어난 사카크 문화 유적지 중 하나입니다. 니피삿에서의 발굴을 통해 석기, 뼈, 주거지의 흔적 등 다양한 유물이 발견되었으며, 이는 사카크 사람들이 북극의 혹독한 환경에 어떻게 적응했는지를 보여줍니다.[NEWLINE][NEWLINE]사카크 문화 외에도, 약 1,000년 전 사카크 문화를 계승한 툴레(Thule) 문화의 흔적도 발견되었습니다. 툴레인들은 현대 이누이트의 조상으로, 니피사트에서의 이들의 존재는 이 지역에서의 인간 거주와 적응의 연속성을 나타냅니다. 니피사트에서의 발견은 선사시대 북극 지역 집단 간의 문화적 전환과 상호작용을 이해하는 데 기여하며, 2018년 유네스코 세계문화유산으로 등재되어 그 역사적 가치를 인정받았습니다.'),
('TXT_KEY_BUILDING_NIPISAT_QUOTE', '[NEWLINE]"카리부는 늑대를 먹여 살리지만, 늑대가 카리부를 강하게 만든다."[NEWLINE] - 이누이트 속담[NEWLINE]'),
--======================================================================================================================
-- 아크라가스의 헤라클레스 신전
--======================================================================================================================
('TXT_KEY_BUILDING_AKRAGATOS', '아크라가스의 헤라클레스 신전'),
('TXT_KEY_BUILDING_AKRAGATOS_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Settler. [NEWLINE]City''s [ICON_PEACE] Faith is added as [ICON_PRODUCTION] Production when training Settling Units, in every City. [NEWLINE]All Shrines gain +1 [ICON_FOOD] Food, +1 [ICON_CULTURE] Culture, +1 [ICON_GOLDEN_AGE] Golden Age Point. [NEWLINE]+3 [ICON_TOURISM] Tourism with [COLOR_CYAN]Archaeology[ENDCOLOR].'),
('TXT_KEY_BUILDING_AKRAGATOS_PEDIA', '이탈리아 시칠리아의 신전 계곡에 위치한 아그리젠토의 헤라클레스 신전은 고대 그리스 식민지 아크라가스의 가장 오래되고 존경받는 건축물 중 하나입니다. 기원전 6세기 후반에 건설된 이 도리아 양식 신전은 그리스 신화의 신성한 영웅 헤라클레스에게 바쳐졌습니다. 자연재해와 인위적 훼손으로 인해 수세기 동안 상당한 피해를 입었지만, 신전의 남아 있는 기둥들은 고대 그리스 건축의 웅장함을 증명합니다. 원래 이 건축물은 약 10미터 높이의 기둥 38개가 둘러싸는 주랑과, 헤라클레스의 상이 놓였을 중앙 신실을 갖추고 있었습니다.[NEWLINE][NEWLINE]헤라클레스 신전은 역사적, 건축적 중요성뿐 아니라 지역 종교 관습과 신화와도 연관되어 있습니다. 전설에 따르면, 이 신전에는 아크라가스 주민들이 매우 숭배했던 유명한 헤라클레스 상이 있었다고 합니다. 1920년대에 남은 기둥을 보존하고 유적을 안정화하기 위한 여러 복원 작업이 이루어졌습니다. 오늘날 헤라클레스 신전은 유네스코 세계문화유산인 신전 계곡의 일부로, 고대의 웅장함을 감상하고 지중해에서 가장 중요한 고고학 유적 중 하나의 풍부한 역사를 탐험하기 위해 전 세계 방문객이 찾고 있습니다.'),
('TXT_KEY_BUILDING_AKRAGATOS_QUOTE', '[NEWLINE]"반대편에는 미론의 작품으로 알려진 아름다운 황동으로 만든 헤라클레스가 있었다고 하는데, 확실히 그 작품이었다고 믿어진다. 또한 그 신들 앞에는 작은 제단들이 있어 예배당의 신성함을 누구에게나 알렸을 것이다.".[NEWLINE] - 키케로[NEWLINE]'),
--======================================================================================================================
-- 피쉬나 미라빌리스
--======================================================================================================================
('TXT_KEY_BUILDING_PISCINA_MIR', '피쉬나 미라빌리스'),
('TXT_KEY_BUILDING_PISCINA_MIR_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]; Building: [COLOR_CYAN]Aqueduct[ENDCOLOR]. [NEWLINE][NEWLINE]Naval Units adjacent to this City always heal 10 HP every turn. [NEWLINE]10% of [ICON_FOOD] Food output in all Cities is added as [ICON_GREAT_ADMIRAL] Great Admiral Points. [NEWLINE]All Aqueducts gain +2 [ICON_PRODUCTION] Production.'),
('TXT_KEY_BUILDING_PISCINA_MIR_PEDIA', '피쉬나 미라빌리스는 이탈리아 나폴리 근처 바콜리에 위치한 로마 공학의 뛰어난 예이자 세계에서 가장 큰 고대 저수조 중 하나입니다. 기원전 1세기 아우구스투스 시대에 건설된 이 거대한 지하 구조물은 인근 미세눔 항구에 주둔한 로마 함대를 위한 주요 물 저장고 역할을 했습니다. 이 저수조는 약 12,600 입방미터의 물을 저장할 수 있었으며, 아펜니노 산맥의 샘에서 캄파니아의 인구 밀집 지역으로 물을 운반하는 나폴리 아우구스타 수도교에서 공급받았습니다. 피쉬나 미라빌리스는 48개의 거대한 기둥이 대칭된 격자로 배치된 광대한 아치형 방들의 네트워크를 특징으로 하며, 로마인들의 고도의 수리 및 건축 기술을 보여줍니다.[NEWLINE][NEWLINE]피쉬나 미라빌리스의 인상적인 규모와 건축은 고대 로마에서 물 관리의 중요성과 일상 생활과 군사 작전을 지원한 정교한 인프라를 강조합니다. 저수조 내부는 높은 아치형 천장과 웅장한 기둥들로 이루어져 있어 거대한 지하 대성당과 같아 방문객들에게 경외감을 줍니다. 수세기 동안 피쉬나 미라빌리스는 역사가, 건축가, 관광객들에게 매혹의 대상이 되었으며, 로마 공학의 독창성과 기지의 증거로 남아 있습니다. 오늘날 이곳은 보호받는 역사적 기념물로서 고대 로마의 기술력과 문화적 우선순위를 엿볼 수 있게 합니다.'),
('TXT_KEY_BUILDING_PISCINA_MIR_QUOTE', '[NEWLINE]"교회가 종교인 것이 수로의 벽돌이 그 안을 흐르는 물인 것과 같지 않다."[NEWLINE] - 헨리 워드 비처[NEWLINE]'),
--======================================================================================================================
-- 바나웨 라이스 테라스
--======================================================================================================================
('TXT_KEY_BUILDING_BANAUE', '바나웨 라이스 테라스'),
('TXT_KEY_BUILDING_BANAUE_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR]; Improvement: [COLOR_CYAN]Farm[ENDCOLOR]. [NEWLINE][NEWLINE]Spawns 3 [ICON_RES_RICE] Rice resources on nearby Hills. [NEWLINE]All Granaries gain +2 [ICON_FOOD] Food. [NEWLINE][NEWLINE]All [ICON_RES_RICE] Rice: +1 [ICON_FOOD] Food, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_BANAUE_PEDIA', '해발 5,000피트 높이, 이파가오 산비탈 약 4,000제곱마일에 걸쳐 바나웨 라이스 테라스가 자리 잡고 있습니다. 이 계단식 밭은 약 2000년 전에 건설되었으며, 고대 원주민 이푸가오족이 건설했습니다. 오늘날에도 위쪽의 열대우림을 이용한 고대 관개 시스템을 통해 물이 공급됩니다. 고대 계단식 논은 최소한의 장비와 대부분 수작업으로 건설되었다는 것이 일반적인 통념입니다. 계단식 논을 따라 이어지는 계단을 끝에서 끝까지 쌓으면 지구 적도의 절반을 둘러쌀 수 있다고 합니다. 이푸가오 문화는 쌀을 주로 사용하며, 젊은이들에게 다양한 쌀 문화 축제를 소개하고, 쌀 재배부터 소비에 이르기까지 농업 의례를 실시했습니다.[NEWLINE][NEWLINE]오늘날에도 계단식 밭은 이푸가오족의 쌀과 채소를 재배하는 데 사용되고 있습니다. 그러나 이푸가오족의 대부분은 농업이 다른 산업에 비해 매력적이지 않다고 생각합니다. 이로 인해 부지는 천천히 침식되었고(계단이 가장 큰 영향을 받았음) 부지 관리의 필요성이 커졌습니다. 2010년에는 더 큰 문제인 가뭄이 발생하여 3월에는 계단식 밭이 완전히 말라 버렸습니다.'),
('TXT_KEY_BUILDING_BANAUE_QUOTE', '[NEWLINE]"모든 쌀알은 농부의 이마에서 떨어지는 땀방울이다."[NEWLINE] - 중국 속담[NEWLINE]'),
--======================================================================================================================
-- 성 카타리나 수도원
--======================================================================================================================
('TXT_KEY_BUILDING_ST_CATHERINE', '성 카타리나 수도원'),
('TXT_KEY_BUILDING_ST_CATHERINE_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR].[NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Monastery in the City in which it is built. [NEWLINE][ICON_GREAT_WORK] Great Works in the City produce +2 [ICON_CULTURE] Culture and [ICON_PEACE] Faith. [NEWLINE]Has 2 slots for [ICON_VP_GREATWRITING] Great Works of Literature. +4 [ICON_FOOD] Food and [ICON_PEACE] Faith if [COLOR_POSITIVE_TEXT]Themed[ENDCOLOR].'),
('TXT_KEY_BUILDING_ST_CATHERINE_PEDIA', '이집트 시나이 반도의 시나이산 기슭에 위치한 성 카타리나 수도원은 세계에서 가장 오래도록 운영되어 온 기독교 수도원 중 하나입니다. 6세기에 비잔틴 황제 유스티니아누스 1세에 의해 설립되었으며, 기독교 순교자인 알렉산드리아의 성 카타리나의 유물이 기적적으로 이곳으로 옮겨진 데서 이름이 유래했습니다. 이 수도원은 초기 기독교 시대의 고대 필사본, 성상, 예술품 등 풍부한 역사적, 종교적 유산을 보유하고 있습니다. 또한 모세가 신과 대화했다고 전해지는 불타는 떨기나무가 있어 기독교인과 유대인 모두에게 신성한 장소로 여겨집니다.[NEWLINE][NEWLINE]건축적으로 성 카타리나 수도원은 침입자로부터 주민과 보물을 보호하기 위해 요새처럼 설계된 복합 건축물입니다. 성당, 모스크, 방대한 초기 필사본을 소장한 도서관, 수도사들의 생활 공간 등이 담긴 성벽으로 둘러싸여 있습니다. 이 수도원 도서관은 바티칸에 이어 필사본의 중요성과 고대성에서 두 번째로 꼽힙니다. 유네스코 세계문화유산으로 지정된 성 카타리나 수도원은 순례, 학술 연구, 영적 헌신의 중심지로서 전 세계 방문객들이 그 풍부한 역사와 종교적 중요성에 관심을 가지고 방문합니다.'),
('TXT_KEY_BUILDING_ST_CATHERINE_QUOTE', '[NEWLINE]"신앙을 순수하게 지키려면 사람은 수도원으로 은퇴하는 게 낫다."[NEWLINE] - 월터 리프먼[NEWLINE]'),
('TXT_KEY_THEMING_BONUS_ST_CATHERINE', '시나이 사본'),
('TXT_KEY_THEMING_BONUS_ST_CATHERINE_HELP', '보너스를 최대화하려면, 모든 위대한 작품 슬롯을 당신이 창작한 문학 작품으로 채우십시오.'),
--======================================================================================================================
-- 숭악사 탑
--======================================================================================================================
('TXT_KEY_UNIT_JAR_HESHANG', '화상'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA', '숭악사 탑'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Pagoda in the City in which it is built. [NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] {TXT_KEY_UNIT_JAR_HESHANG}, a Civilian Unit that may be expended to construct a Holy Site. [NEWLINE]+2 [ICON_PEACE] Faith from all [ICON_VP_SCIENTIST] Scientist Specialists in your Empire. [NEWLINE]+3 [ICON_RESEARCH] Science from all Holy Sites in your Empire.'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_PEDIA', '중국 허난성 송산에 위치한 숭악사 탑은 중국에서 알려진 가장 오래된 벽돌 탑으로, 북위 시대인 서기 523년경에 지어졌습니다. 이 고대 구조물은 중국 초기 불교 건축의 증거로서, 한족과 중앙아시아의 영향을 혼합한 양식을 반영합니다. 탑은 당시 흔했던 사각형 탑과 달리 원형 평면을 가지며, 12층으로 우아하게 점점 가늘어지는 형태이고 각 층은 독특한 처마로 구분되어 있습니다. 숭악사 탑의 정교한 벽돌 공예와 아치 및 받침대의 사용은 당대 고급 기술을 보여주며, 중국 건축의 초기 발전 단계를 나타냅니다.[NEWLINE][NEWLINE]건축적으로 숭악사 탑은 우아하고 혁신적인 디자인으로 중요하며, 이후 중국 전역의 탑 건축에 영향을 주었습니다. 탑 내부에는 중앙 기둥과 좁은 회랑이 있어 신도들이 탑을 돌며 예배할 수 있게 합니다. 이 설계는 구조적 안정성을 제공하여 수세기 동안 자연적 마모와 지진을 견딜 수 있게 했습니다. 불교가 중국에 전파된 상징으로서 숭악사 탑은 문화적, 역사적 중요성을 지닌 기념물이자, 그 역사적 맥락과 건축적 의미를 이해하려는 학자, 건축가, 관광객들을 끌어들입니다. 2010년에는 ‘천지 중심에 있는 덩펑의 역사적 기념물’의 일부로 유네스코 세계문화유산에 등재되었습니다.'),
('TXT_KEY_BUILDING_SONGYUE_PAGODA_QUOTE', '[NEWLINE]"사원은 하늘과 땅이 만나는 지점이다."[NEWLINE] -데이비드 A. 베드나[NEWLINE]'),
--======================================================================================================================
-- 호류지
--======================================================================================================================
('TXT_KEY_BUILDING_HORYUJI', '호류지'),
('TXT_KEY_BUILDING_HORYUJI_HELP', 'Plot: [COLOR_CYAN]Flat[ENDCOLOR]; Feature: [COLOR_CYAN]River[ENDCOLOR]. [NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Pagoda in the City in which it is built. [NEWLINE]Earn [ICON_CULTURE] Culture when purchasing a Missionary or Inquisitor class unit, scaling with Era.[NEWLINE]+2 [ICON_PEACE] Faith from all [ICON_VP_WRITER] Writer Specialists in your Empire.'),
('TXT_KEY_BUILDING_HORYUJI_PEDIA', '호류지는 일본 나라 현에 위치한 일본에서 가장 중요하고 역사적인 불교 사원 중 하나입니다. 607년 초기 일본 불교의 핵심 인물인 쇼토쿠 태자가 창건했으며, 일본에 불교 교리를 전파하기 위해 세워졌습니다. 원래 건물은 670년에 화재로 손상되었으나 신속히 재건되었고, 많은 건물들이 1,300년 이상 보존되어 왔습니다. 사원 단지에는 세계에서 가장 오래된 목조 건축물 중 일부가 있으며, 오층 목탑과 콘도(금당)에는 아스카 시대의 귀중한 불상과 유물이 보관되어 있습니다.[NEWLINE][NEWLINE]호류지는 그 역사적, 문화적, 건축적 중요성으로 1993년에 유네스코 세계문화유산으로 지정되었습니다. 사원 단지는 두 개의 주요 구역으로 나뉘는데, 가장 오래된 건물이 위치한 사이인 가람(서원)과 몽전(유메도노)이 위치한 토인 가람(동원)입니다. 불교 학문과 예술의 중심지로서 호류지는 여전히 활발한 예배 장소이며 일본의 깊은 영적, 건축 유산의 상징으로 남아 있습니다.'),
('TXT_KEY_BUILDING_HORYUJI_QUOTE', '[NEWLINE]"세 보배인 부처님, 가르침, 그리고 승가를 진심으로 공경하라."[NEWLINE] - 쇼토쿠 태자[NEWLINE]'),
('TXT_KEY_GRAND_HORYUJI_BONUS_HEADER', '호류지 [ICON_CULTURE]'),
('TXT_KEY_GRAND_HORYUJI_BONUS_BODY', '{@2_unitName} 유닛으로부터 [ICON_CULTURE] 문화를 +{@1_num} 획득합니다.'),
--======================================================================================================================
-- Kyz Kala
--======================================================================================================================
('TXT_KEY_BUILDING_KYZ_KALA', '그레이트 키즈 칼라'),
('TXT_KEY_BUILDING_KYZ_KALA_HELP', '지형: [COLOR_NEGATIVE_TEXT]해안[ENDCOLOR], [COLOR_NEGATIVE_TEXT]호수[ENDCOLOR]; 특성: [COLOR_CYAN]오아시스[ENDCOLOR]. [NEWLINE][NEWLINE]+2 [ICON_GREAT_GENERAL] 위대한 장군 점수. [NEWLINE]건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] 성을 제공합니다.[NEWLINE]문명 전역의 오아시스에서 [ICON_PRODUCTION] 생산력, [ICON_CULTURE] 문화, [ICON_GOLDEN_AGE] 황금기 포인트가 +1 증가합니다.[NEWLINE]이 도시에 건물을 건설하면 [ICON_FOOD] 식량이 25 증가합니다. (시대에 따라 보정)'),
('TXT_KEY_BUILDING_KYZ_KALA_PEDIA', '위대한 키즈 칼라는 투르크메니스탄의 메르브에 위치한 유네스코 세계문화유산 내 여러 유사 구조물인 쾨슈크 중 하나인 거대한 진흙 벽돌로 된 요새 건축물입니다. 이 기념물의 건축 시기와 용도는 아직 논란이 있으며, 서기 6세기에서 8세기 사이인 사산 왕조 말기 또는 초기 이슬람 시대에 건축되었고, 1221년 몽골군의 메르브 약탈 때까지 사용된 것으로 추정됩니다. 도시 성벽 바로 외곽에 위치하며, 요새화된 거주지로 기능했을 가능성이 크며, 최근 발굴에서는 여러 내부 구획과 구별되는 방, 바닥, 계단 등이 확인되었습니다.'),
('TXT_KEY_BUILDING_KYZ_KALA_QUOTE', '[NEWLINE]"그러나 이 모든 세상은 우리가 듣는 이야기와 같다. 인간의 악행과 영광은 사라진다."[NEWLINE] - 아불카셈 페르도시[NEWLINE]'),
--======================================================================================================================
-- 소림사
--======================================================================================================================
('TXT_KEY_BUILDING_SHAOLIN', '소림사'),
('TXT_KEY_BUILDING_SHAOLIN_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR]; City: [COLOR_CYAN]Has adopted Player''s Majority Religion[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Order in the City in which it is built. [NEWLINE]+20 XP for all Units in every City. [NEWLINE]10% of [ICON_PEACE] Faith output in all Cities is added as [ICON_GREAT_GENERAL] Great General points.'),
('TXT_KEY_BUILDING_SHAOLIN_PEDIA', '소림사는 1,500년이 넘는 풍부한 역사를 가지고 있으며, 그 시작은 북위나라 효문제 황제가 인도의 승려 발타(또는 부다바드라(불타발타라)라고도 함)선사에게 허난성의 소실산 기슭에 사원을 짓도록 허가한 서기 495년입니다. 발타는 소림사를 불교 연구와 수행의 중요한 중심지로 만들었고, 중국에서 가장 유명한 사원 중 하나가 될 토대를 마련했습니다. 32년 후, 또 다른 중요한 인물이 도착했습니다. 바로 인도 승려 보디다르마(중국어로 다모, 한자로 달마)대사입니다. 그는 이 사원에서 불교 선종(선불교)을 전파한 창시자로, 사원의 정신적 성격을 근본적으로 형성하고 불교 선종의 발상지라는 명성을 확립했습니다. [NEWLINE][NEWLINE]소림사는 무술 전통으로 전 세계적으로 유명하지만, 그 무술 체계의 역사적 발전은 대중적인 전설에서 암시하는 것보다 훨씬 더 복잡합니다. 현대 무술 역사가들은 보디다르마가 소림사에서 무술을 창시했다는 널리 퍼진 믿음이 실제로는 17세기 기공 매뉴얼에서 유래되었으며 20세기에 대중화되었다는 것을 보여주었습니다. 보디다르마의 실제 공헌은 승려들이 건강을 유지하는 데 도움이 되는 기공에 기반한 운동을 개발한 것이었는데, 이는 전투 기술이라기보다는 요가에 더 가깝습니다. 수도원의 무술 전통은 수 세기에 걸쳐 점진적으로 발전해 다양한 전투 시스템을 통합하고 전설적인 기록에서 암시하는 것보다 훨씬 늦게 체계화되었을 가능성이 있습니다. 이러한 역사적 설명에도 불구하고, 소림사는 불교 학문의 중심지이자 중국 무술 문화의 상징으로서 여전히 깊은 의미를 지니고 있습니다.'),
('TXT_KEY_BUILDING_SHAOLIN_QUOTE', '[NEWLINE]"신앙은 인간의 마음이 상상하고 믿을 수 있는 것을 성취할 수 있게 해준다."[NEWLINE] - 이소룡[NEWLINE]'),
--======================================================================================================================
-- Basilica of Saint Francis of Assisi
--======================================================================================================================
('TXT_KEY_BUILDING_ASSISI', 'San Francesco d''Assisi'),
('TXT_KEY_BUILDING_ASSISI_HELP', 'Terrain: [COLOR_NEGATIVE_TEXT]Coast[ENDCOLOR]; Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Cathedral in the City in which it is built. [NEWLINE]All Buildings yielding [ICON_PEACE] Faith in the Empire gain +1 [ICON_GOLD] Gold.'),
('TXT_KEY_BUILDING_ASSISI_PEDIA', 'The Basilica of Saint Francis of Assisi, located in the town of Assisi in central Italy, is one of the most significant and revered sites in the Christian world. Constructed between 1228 and 1253, soon after the canonization of Saint Francis, the basilica consists of two distinct churches: the Upper Basilica (Basilica Superiore) and the Lower Basilica (Basilica Inferiore). The Upper Basilica, with its soaring Gothic architecture, features large stained glass windows and is renowned for its extensive cycle of frescoes attributed to Giotto and his workshop, which depict the life of Saint Francis and are considered masterpieces of Italian art. The Lower Basilica, characterized by its Romanesque style, is more austere and houses the tomb of Saint Francis, making it a place of pilgrimage for millions of faithful from around the world. [NEWLINE][NEWLINE]The Basilica of Saint Francis of Assisi not only serves as a major religious site but also as a cultural and artistic treasure. The frescoes in both the Upper and Lower Basilicas are among the most important in the history of Western art, illustrating pivotal scenes from the Bible and the life of Saint Francis with vivid detail and emotional depth. These artworks played a crucial role in the development of Italian Renaissance art. The basilica complex, which also includes a friary, has been designated a UNESCO World Heritage Site due to its historical, spiritual, and artistic significance. It remains a vital center for the Franciscan order and continues to inspire visitors with its profound beauty and spiritual legacy.'),
('TXT_KEY_BUILDING_ASSISI_QUOTE', '[NEWLINE]"Start by doing what''s necessary; then do what''s possible; and suddenly you are doing the impossible."[NEWLINE] - Saint Francis of Assisi[NEWLINE]'),
--======================================================================================================================
-- Church of the Nativity
--======================================================================================================================
('TXT_KEY_BUILDING_CHURCH_NATIVITY', 'Church of the Nativity'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]; Player: [COLOR_CYAN]Founded Religion[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Church in the City in which it is built. [NEWLINE]In all Cities +2 [ICON_PEACE] Faith, +2 [ICON_PRODUCTION] Production for every World Religion that has at least one Follower in the respective City.'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_PEDIA', 'The Church of the Nativity, located in Bethlehem, is one of Christianity''s holiest sites, traditionally believed to be the birthplace of Jesus Christ. Built over a cave known as the Grotto of the Nativity, the church was originally commissioned by Emperor Constantine and his mother, Helena, in the 4th century. The basilica was later rebuilt by Emperor Justinian in the 6th century after being damaged. Over the centuries, the church has undergone numerous renovations and additions, including elements from the Crusader period, Greek Orthodox, Armenian, and Roman Catholic influences. The structure is marked by its ancient columns, mosaics, and the silver star in the grotto, which signifies the exact spot of Christ''s birth. [NEWLINE][NEWLINE]Despite its turbulent history, including invasions, fires, and political conflicts, the Church of the Nativity remains a major pilgrimage destination. It is jointly managed by the Greek Orthodox, Armenian Apostolic, and Roman Catholic churches, each controlling different sections. In 2012, UNESCO recognized it as a World Heritage Site, highlighting its historical and spiritual significance. Today, it continues to attract millions of visitors annually, serving as a powerful symbol of faith and endurance in the heart of Bethlehem.'),
('TXT_KEY_BUILDING_CHURCH_NATIVITY_QUOTE', '[NEWLINE]"You must look at the Child in the manger. He is our Love. Look at him, realizing that the whole thing is a mystery."[NEWLINE] - Saint Josemaria Escriva[NEWLINE]'),
--======================================================================================================================
-- Hospital of Saint John
--======================================================================================================================
('TXT_KEY_BUILDING_HOSPITAL_STJOHN', 'Hospital of St. John'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Order in the City in which it is built. [NEWLINE]Land Units in this City heal 10 points per turn whether or not they take an action. [NEWLINE][NEWLINE]15% of [ICON_PEACE] Faith created by all Cities in the Empire counts as [ICON_FOOD] Food Per Turn.'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_PEDIA', 'The Order of the Hospital of St. John of Jerusalem, commonly known as the Knights Hospitaller, was a medieval Catholic military order founded in the 11th century to provide care for sick, poor, and injured pilgrims in the Holy Land. Established around 1023 by a group of merchants from Amalfi, the order initially focused on running a hospital in Jerusalem dedicated to St. John the Baptist. After the First Crusade and the establishment of the Kingdom of Jerusalem, the order gained military functions to protect pilgrims and the territories acquired by the Crusaders. The Knights Hospitaller became one of the most powerful and influential military orders of the medieval period, playing a significant role in the defense of Christian territories in the Holy Land and the Mediterranean. [NEWLINE][NEWLINE]Throughout the centuries, the order adapted to changing political and military landscapes. After the fall of Jerusalem in 1187, the Knights relocated their headquarters several times, eventually settling on the island of Rhodes in 1309 and later Malta in 1530, where they became known as the Knights of Malta. Their presence on these islands fortified them against Ottoman expansion and piracy, turning them into a formidable naval power. Even after losing Malta to Napoleon in 1798, the order continued its charitable work. Today, the Sovereign Military Order of Malta remains a humanitarian organization with a presence worldwide, continuing its founding mission of aiding the sick and poor, while maintaining its status as a sovereign entity with diplomatic relations with numerous countries.'),
('TXT_KEY_BUILDING_HOSPITAL_STJOHN_QUOTE', '[NEWLINE]"For Faith, For Service to Humanity."[NEWLINE] - Knights Hospitaller Motto[NEWLINE]'),
--======================================================================================================================
-- Tlachihualtepetl
--======================================================================================================================
('TXT_KEY_BUILDING_TLACHIHUALTEPETL', 'Tlachihualtepetl'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Teocalli in the City in which it is built. [NEWLINE]All Cities earn +10 [ICON_PEACE] Faith, +5 [ICON_GOLDEN_AGE] Golden Age Points and +5 [ICON_GREAT_GENERAL] Great General points when they construct Buildings, scaling with Era.'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_PEDIA', 'Tlachihualtepetl, also known as the Great Pyramid of Cholula, is an ancient Mesoamerican structure located in Cholula, Mexico. It is considered the largest pyramid by volume in the world, surpassing even the Great Pyramid of Giza. Built in multiple phases beginning around the 3rd century BCE by the indigenous inhabitants of Cholula, the pyramid was expanded over centuries, reaching a base of approximately 450 by 450 meters (1,480 by 1,480 feet) and a height of around 66 meters (217 feet). Its name, Tlachihualtepetl, means "man-made mountain" in Nahuatl, reflecting its layered construction as each civilization built upon the previous one. The pyramid was an important religious and ceremonial center dedicated to the god Quetzalcoatl, playing a significant role in pre-Columbian culture. [NEWLINE][NEWLINE]By the time of the Spanish conquest in the 16th century, the pyramid had been largely abandoned and overgrown, resembling a natural hill. The Spanish, unaware of the structure beneath, built the Church of Our Lady of Remedies on top, symbolizing the imposition of Christianity over indigenous beliefs. Today, Tlachihualtepetl is an important archaeological site, with a network of tunnels excavated inside the pyramid revealing its layered history. It remains a significant cultural and tourist attraction, blending pre-Hispanic and colonial heritage, and stands as a testament to the architectural and religious traditions of ancient Mesoamerican civilizations.'),
('TXT_KEY_BUILDING_TLACHIHUALTEPETL_QUOTE', '[NEWLINE]"Quetzalcoatl is a primal idea of the duality of human nature. The serpent is the embodiment of Heaven and Earth. It scares people in many ways."[NEWLINE] - Robert Graham[NEWLINE]'),
--======================================================================================================================
-- Old New Synagogue of Prague
--======================================================================================================================
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE', 'Old New Synagogue of Prague'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_HELP', ' Feature: [COLOR_CYAN]River[ENDCOLOR];  City: [COLOR_CYAN]Minority Religion with at least 4 Followers[ENDCOLOR].[NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Synagogue in the City in which it is built. [NEWLINE]Starts 15 turns of "[COLOR_POSITIVE_TEXT]We Love the King Day[ENDCOLOR]" in the City. [NEWLINE]In all Cities +10% [ICON_GOLD] Gold, [ICON_CULTURE] Culture, [ICON_PEACE] Faith during "[COLOR_POSITIVE_TEXT]We Love the King Day[ENDCOLOR]".'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_PEDIA', 'The Old New Synagogue, located in the heart of Prague''s Jewish Quarter, is one of the most historic and culturally significant synagogues in Europe. Built in the 1270s during the reign of King Ottokar II of Bohemia, it is the oldest active synagogue in Europe. The synagogue''s name, "Old New", reflects its history; it was once the "New Synagogue" when it was built, but as newer synagogues were constructed, it became known as the "Old New" to distinguish it from them. Architecturally, the synagogue is a masterpiece of Gothic style, featuring a distinctive gabled roof and a striking façade. Its interior is adorned with intricate stone carvings and a vaulted ceiling, creating a sense of solemnity and reverence. [NEWLINE][NEWLINE]Throughout its history, the Old New Synagogue has played a pivotal role in Jewish life in Prague. It has been a center of worship, learning, and community for centuries, surviving numerous challenges, including fires, floods, and periods of persecution. The synagogue is also famous for its association with the legend of the Golem of Prague, a mythical creature said to have been created by Rabbi Judah Loew ben Bezalel, a prominent rabbi who prayed at the synagogue in the 16th century. Today, the Old New Synagogue continues to serve as an active place of worship and is a major tourist attraction, offering visitors a glimpse into the rich history and traditions of Prague''s Jewish community. Its enduring presence is a testament to the resilience and cultural heritage of Jewish life in Europe.'),
('TXT_KEY_BUILDING_OLD_NEW_SYNAGOGUE_QUOTE', '[NEWLINE]"Judaism is something more than a badge, something more than a birth-mark; it is a life."[NEWLINE] - Morris David Joseph[NEWLINE]'),
--======================================================================================================================
-- Jetavanaramaya
--======================================================================================================================
('TXT_KEY_BUILDING_JETAVANARAMAYA', 'Jetavanaramaya'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_HELP', 'Feature: [COLOR_CYAN]Forest/Jungle[ENDCOLOR]; Improvement: [COLOR_CYAN]Village[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Stupa in the City in which it is built. [NEWLINE]10% of [ICON_FOOD] Food is carried over after a new [ICON_CITIZEN] Citizen is born in all Cities, and additional 10% in the City in which it is built. [NEWLINE]+2 [ICON_PEACE] Faith to Villages in the Empire.'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_PEDIA', 'The Jetavanaramaya is an ancient stupa located in Anuradhapura, Sri Lanka, and is one of the tallest and most significant Buddhist monuments in the world. Constructed during the 3rd century CE by King Mahasena (r. 277–304 CE), it was part of the Jetavana Monastery, which became an important center for Theravada and Mahayana Buddhism. At its peak, the stupa stood approximately 122 meters (400 feet) high, making it one of the tallest structures of the ancient world. Built primarily of brick, Jetavanaramaya remains one of the largest brick structures ever created, showcasing the engineering prowess of ancient Sri Lankan civilization. [NEWLINE][NEWLINE]Over the centuries, the stupa suffered damage due to invasions and neglect, but it remained a revered site for Buddhist worshippers. Restoration efforts in modern times have helped preserve its grandeur, and today, it remains an important pilgrimage destination. The stupa is surrounded by ruins of monastic buildings and intricate carvings, reflecting the architectural and artistic achievements of the Anuradhapura period. Jetavanaramaya continues to be a symbol of Sri Lanka’s Buddhist heritage and a testament to the historical significance of the ancient city of Anuradhapura.'),
('TXT_KEY_BUILDING_JETAVANARAMAYA_QUOTE', '[NEWLINE]"The monk who is calm in body, calm in speech, calm in thought, well-composed and who has spewn out worldliness — he, truly, is called serene."[NEWLINE] - Dhammapada, verse 378[NEWLINE]'),
--======================================================================================================================
-- Harmandir Sahib
--======================================================================================================================
('TXT_KEY_BUILDING_HARMANDIR_SAHIB', 'Harmandir Sahib'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_HELP', 'Special: [COLOR_YIELD_PRODUCTION]Holy City[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Gurdwara in the City in which it is built. [NEWLINE]All Baths and Buildings yielding [ICON_PEACE] Faith in the Empire gain +2 [ICON_FOOD] Food. [NEWLINE][NEWLINE]-1 [ICON_HAPPINESS_3] Unhappiness from Religious Unrest in all Cities.'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_PEDIA', 'Harmandir Sahib, also known as the Golden Temple, is the holiest shrine of Sikhism, located in Amritsar, Punjab, India. It was founded in 1581 by Guru Ram Das, the fourth Sikh Guru, and completed by his successor, Guru Arjan Dev, in 1604. The temple was built as a place of spiritual worship open to all, regardless of caste or religion. Guru Arjan Dev installed the Guru Granth Sahib, the central holy scripture of Sikhism, inside the temple, making it the spiritual and cultural heart of the Sikh faith. Over centuries, the temple endured attacks and was rebuilt multiple times, including its gold-plated renovation under Maharaja Ranjit Singh in the early 19th century, which gave it its iconic appearance. [NEWLINE][NEWLINE]The Golden Temple is a stunning architectural masterpiece, blending Hindu and Islamic styles with a distinctive Sikh identity. Surrounded by the Amrit Sarovar (Pool of Nectar), the temple''s shimmering gold-covered façade and marble inlays create a breathtaking spectacle. It has four entrances, symbolizing openness and inclusivity, and a causeway leading to the sanctum, where continuous recitation of the Guru Granth Sahib takes place. The temple complex also houses the Akal Takht, the highest seat of Sikh religious authority, and the world’s largest free community kitchen (Langar), serving meals to thousands daily. Harmandir Sahib remains a symbol of Sikh devotion, resilience, and universal brotherhood.'),
('TXT_KEY_BUILDING_HARMANDIR_SAHIB_QUOTE', '[NEWLINE]"The Giver of peace is eternally blissful."[NEWLINE] - Sri Guru Granth Sahib[NEWLINE]'),
--======================================================================================================================
-- Larabanga
--======================================================================================================================
('TXT_KEY_BUILDING_LARABANGA', 'Larabanga Mosque'),
('TXT_KEY_BUILDING_LARABANGA_HELP', 'Terrain: [COLOR_CYAN]Plains[ENDCOLOR]; Building: [COLOR_CYAN]Customs House[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Mosque in the City in which it is built. [NEWLINE]+100% Religious Pressure towards Cities connected by Trade Routes. [NEWLINE]All [ICON_INTERNATIONAL_TRADE] International Trade Routes provide +3 [ICON_GOLD] Gold, +3 [ICON_PEACE] Faith.'),
('TXT_KEY_BUILDING_LARABANGA_PEDIA', 'The Larabanga Mosque, located in northern Ghana, is one of West Africa''s oldest and most revered Islamic sites. Built in the 15th century, it is believed to have been founded by an Islamic trader named Ayuba, who, according to legend, was guided by divine intervention to construct the mosque. The mosque played a crucial role in spreading Islam in the region and remains a center of Islamic learning and worship. Its historical significance and connection to early trans-Saharan trade routes make it a key cultural and religious landmark in Ghana. Despite facing structural challenges over the centuries, including weather damage and restoration efforts, it continues to serve as an active place of prayer and pilgrimage. [NEWLINE][NEWLINE]Architecturally, the Larabanga Mosque is a striking example of Sudano-Sahelian design, characterized by its whitewashed mud walls and timber-reinforced framework. It features two prominent towers—one serving as a minaret and the other as a mihrab (prayer niche facing Mecca). The mosque''s compact, rectangular shape and buttressed walls give it a distinctive, fortress-like appearance. Wooden beams protrude from the structure, not only for aesthetic value but also to provide support and aid in maintenance. The mosque''s simple yet elegant design reflects the adaptation of Islamic architecture to the local environment and materials. Today, it remains a revered spiritual site and a significant symbol of Ghana''s Islamic heritage.'),
('TXT_KEY_BUILDING_LARABANGA_QUOTE', '[NEWLINE]"Whatever you have will perish, but what Allah has will remain."[NEWLINE]- The Quran[NEWLINE]'),
--======================================================================================================================
-- Botanical Garden of Padua
--======================================================================================================================
('TXT_KEY_BUILDING_PADUA_GARDEN', 'Botanical Garden of Padua'),
('TXT_KEY_BUILDING_PADUA_GARDEN_HELP', 'Improved Resource: [COLOR_CYAN]Plant Resources[ENDCOLOR]; Building: [COLOR_CYAN]Garden[ENDCOLOR]. [NEWLINE][NEWLINE]All Gardens gain +2 [ICON_FOOD] Food, +2 [ICON_RESEARCH] Science. [NEWLINE]All Plant Resources: +1 [ICON_RESEARCH] Science. [NEWLINE]+3 [ICON_FOOD] Food from all Academies in your Empire.'),
('TXT_KEY_BUILDING_PADUA_GARDEN_PEDIA', 'The Botanical Garden of Padua, established in 1545, is the world''s oldest academic botanical garden still in its original location. Located in Padua, Italy, it was created for the study of medicinal plants, a reflection of the Renaissance''s growing interest in natural sciences and the medicinal properties of plants. Initially, the garden focused on the cultivation and classification of plants used for medical purposes, providing an essential resource for medical students at the University of Padua. Its design, with a circular central plot symbolizing the world and smaller, geometrically arranged beds around it, has influenced the layout of botanical gardens worldwide. [NEWLINE][NEWLINE]Over the centuries, the Botanical Garden of Padua has expanded its collection to include a vast array of plant species from around the globe, showcasing an impressive diversity of flora. It houses over 6,000 species, including rare and endangered plants, and features several themed sections such as the Garden of Biodiversity, which highlights the planet''s diverse ecosystems. The garden has played a pivotal role in botanical research and education, contributing significantly to the study of plant sciences. In recognition of its historical and scientific importance, it was designated a UNESCO World Heritage Site in 1997. Today, it continues to serve as a vital center for research, conservation, and public education, attracting scholars, students, and nature enthusiasts from around the world.'),
('TXT_KEY_BUILDING_PADUA_GARDEN_QUOTE', '[NEWLINE]"If you have a garden and a library, you have everything you need."[NEWLINE] - Marcus Tullius Cicero[NEWLINE]'),
--======================================================================================================================
-- Changdeokgung
--======================================================================================================================
('TXT_KEY_BUILDING_CHANGDEOKGUNG', 'Changdeokgung'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_PEOPLE] Great Person of your choice. [NEWLINE]All Baths and Gardens gain +1 [ICON_HAPPINESS_1] Happiness. [NEWLINE]+2 [ICON_PRODUCTION] Production, +2 [ICON_GOLDEN_AGE] Golden Age Points from all [ICON_CSD_CIVIL_SERVANT] Civil Servant Specialists in your Empire.'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_PEDIA', 'Changdeokgung, located in Seoul, South Korea, is one of the "Five Grand Palaces" built during the Joseon Dynasty and is renowned for its harmonious integration with the natural landscape. Constructed in 1405, the palace served as the principal residence for many Joseon kings and was favored for its serene, beautiful surroundings. Unlike other palaces that follow strict geometric layouts, Changdeokgung is designed to blend seamlessly with the topography of the site, featuring a series of pavilions, courtyards, and gardens that follow the contours of the terrain. This approach reflects the traditional Korean philosophy of living in harmony with nature. [NEWLINE][NEWLINE]One of the most notable features of Changdeokgung is the Huwon, or "Secret Garden," a 78-acre garden that was used by the royal family for leisure and retreat. The garden is meticulously landscaped with ponds, pavilions, and a variety of trees and flowers, offering a tranquil escape from the stresses of court life. Changdeokgung''s unique design and historical significance led to its designation as a UNESCO World Heritage Site in 1997. The palace complex not only exemplifies the aesthetic and philosophical values of the Joseon Dynasty but also serves as a cultural and architectural treasure, attracting numerous visitors who come to appreciate its timeless beauty and historical importance.'),
('TXT_KEY_BUILDING_CHANGDEOKGUNG_QUOTE', '[NEWLINE]"Genius without religion is only a lamp on the outer gate of a palace."[NEWLINE] - Hannah More[NEWLINE]'),
--======================================================================================================================
-- Damnoen Saduak
--======================================================================================================================
('TXT_KEY_BUILDING_DAMNOEN_SADUAK', 'Damnoen Saduak'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_HELP', 'Feature: [COLOR_CYAN]River[ENDCOLOR]; Building: [COLOR_CYAN]Grocer[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_MERCHANT] Great Merchant. [NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold, +1 [ICON_CULTURE] Culture from nearby River tiles. [NEWLINE]+2 [ICON_FOOD] Food, +2 [ICON_CULTURE] Culture from all [ICON_VP_MERCHANT] Merchant Specialists in your Empire. [NEWLINE]All Markets and Grocers gain +2 [ICON_GOLD] Gold, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_PEDIA', 'Damnoen Saduak Floating Market, located in Ratchaburi Province, Thailand, about 100 kilometers southwest of Bangkok, is one of the most famous and vibrant floating markets in the country. Established in the 19th century during the reign of King Rama IV, the market has become a quintessential representation of traditional Thai commerce and culture. Vendors, primarily women wearing wide-brimmed straw hats, paddle small wooden boats laden with fresh produce, local delicacies, and handicrafts through a network of canals. This lively waterborne marketplace offers visitors a glimpse into the traditional way of life in Thailand, where waterways were once the primary means of transportation and trade. [NEWLINE][NEWLINE]The bustling atmosphere of Damnoen Saduak Floating Market attracts numerous tourists who come to experience the unique shopping environment and enjoy the array of sights, sounds, and flavors. Visitors can sample an assortment of Thai street foods directly from the boats, such as pad thai, mango sticky rice, and freshly squeezed coconut juice, while exploring stalls selling souvenirs and handmade goods along the canal banks. The market''s picturesque setting and dynamic activity provide ample opportunities for photography and cultural immersion. Despite its popularity with tourists, Damnoen Saduak remains a working market for locals, maintaining its authenticity and charm as a vibrant hub of daily life and commerce in rural Thailand.'),
('TXT_KEY_BUILDING_DAMNOEN_SADUAK_QUOTE', '[NEWLINE]"Ideas, like large rivers, never have just one source."[NEWLINE] - Willy Ley[NEWLINE]'),
--======================================================================================================================
-- Paro Taktsang
--======================================================================================================================
('TXT_KEY_BUILDING_TAKTSANG', 'Paro Taktsang'),
('TXT_KEY_BUILDING_TAKTSANG_HELP', 'Terrain: [COLOR_CYAN]Mountain[ENDCOLOR].[NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Monastery in the City in which it is built. [NEWLINE]Place a Holy Site on a nearby mountain that yields additional +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production.'),
('TXT_KEY_BUILDING_TAKTSANG_PEDIA', 'Paro Taktsang, also known as the Tiger''s Nest Monastery, is a sacred Buddhist site perched dramatically on a cliffside in Bhutan''s Paro Valley. Built in 1692, the monastery is said to mark the meditation site of Guru Padmasambhava, the legendary 8th-century Buddhist master who introduced Vajrayana Buddhism to Bhutan. According to legend, Padmasambhava flew to the site on the back of a tigress, giving the monastery its famous name. The complex consists of multiple temples and meditation caves, blending seamlessly with the rugged cliffs at an elevation of about 3,120 meters (10,240 feet). The monastery is a major pilgrimage site and an iconic symbol of Bhutanese culture and spirituality. [NEWLINE][NEWLINE]Despite its remote location, Paro Taktsang has been carefully preserved and rebuilt after suffering significant damage from a fire in 1998. Accessible only by a steep mountain trail, the monastery remains a place of deep spiritual significance and offers breathtaking views of the surrounding valley. The site is visited by thousands of pilgrims and tourists each year, drawn by its mystical history, stunning architecture, and serene atmosphere. Paro Taktsang stands as a testament to Bhutan’s strong Buddhist traditions and its commitment to preserving sacred heritage in harmony with nature.'),
('TXT_KEY_BUILDING_TAKTSANG_QUOTE', '[NEWLINE]"There are many paths to the top of the mountain, yet the view is always the same"[NEWLINE] - Chinese Proverb[NEWLINE]'),
--======================================================================================================================
-- Keshgarh Qila
--======================================================================================================================
('TXT_KEY_BUILDING_KESHGARH_QILA', 'Keshgarh Qila'),
('TXT_KEY_BUILDING_KESHGARH_QILA_HELP', 'Terrain: [COLOR_CYAN]Grassland[ENDCOLOR]; Improvement: [COLOR_CYAN]Fort[ENDCOLOR]. [NEWLINE][NEWLINE]Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%.[NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Gurdwara in the City in which it is built. [NEWLINE]+25% [ICON_PRODUCTION] Production of Land Melee Units in all Cities. [NEWLINE]Increases [ICON_SILVER_FIST] Military Unit Supply Cap by 5.'),
('TXT_KEY_BUILDING_KESHGARH_QILA_PEDIA', 'Takht Keshgarh Sahib or Keshgarh Qila is one of the five Takhts (temporal seats) of Sikhism and is located in Anandpur Sahib, Punjab, India. It holds immense historical and religious significance as the birthplace of the Khalsa, the Sikh warrior community, which was founded by Guru Gobind Singh Ji on Vaisakhi in 1699. During this event, Guru Gobind Singh initiated the first Panj Pyare (Five Beloved Ones) and introduced the Amrit Sanchar (Sikh baptism ceremony), establishing the Khalsa''s distinct identity. The Kesgarh Fort, which once stood on this site, was a crucial defense post during battles between the Sikhs and Mughal forces. The Takht Sahib houses many relics of Guru Gobind Singh, including weapons used by him and the Khalsa warriors. [NEWLINE][NEWLINE]Today, Takht Kesgarh Sahib is a major pilgrimage site for Sikhs and a symbol of their martial and spiritual heritage. The Gurdwara is built on a hilltop, offering a panoramic view of Anandpur Sahib and the surrounding Shivalik hills. The main shrine features a grand Darbar Hall, where daily prayers and kirtans (devotional songs) take place. Sikhs from around the world visit the Takht, especially during Vaisakhi celebrations, to honor the legacy of Guru Gobind Singh and the founding of the Khalsa. It remains a center of Sikh faith, resilience, and unity.'),
('TXT_KEY_BUILDING_KESHGARH_QILA_QUOTE', '[NEWLINE]"He who has no faith in himself can never have faith in God."[NEWLINE] - Guru Nanak[NEWLINE]'),
--======================================================================================================================
-- Citadelle Laferrière
--======================================================================================================================
('TXT_KEY_BUILDING_LAFERRIERE', 'Citadelle Laferrière'),
('TXT_KEY_BUILDING_LAFERRIERE_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]; Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_GENERAL] Great General.  [NEWLINE]All Siege Units in the Empire get [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_LAFERRIERE}[ENDCOLOR] promotion. [NEWLINE]All Forts, Citadels and unique improvements replacing them in the Empire receive +2 [ICON_FOOD] Food, +2 [ICON_PRODUCTION] Production, +2 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_LAFERRIERE_PEDIA', 'Citadelle Laferrière, located in northern Haiti atop the Bonnet à l''Évêque mountain, is a monumental fortress and a symbol of Haitian independence and resilience. Constructed between 1805 and 1820 under the leadership of Henri Christophe, a key figure in the Haitian Revolution who later became king of northern Haiti, the citadel was built to defend against potential French invasions after Haiti won its independence in 1804. The fortress is an architectural marvel, featuring massive walls, impressive battlements, and an array of cannons and artillery, many of which remain in place today. Its strategic location, perched 900 meters above sea level, offers sweeping views of the surrounding landscape and the Atlantic Ocean, making it a formidable defensive structure. [NEWLINE][NEWLINE]The Citadelle Laferrière, along with the nearby Sans-Souci Palace, is a UNESCO World Heritage Site, recognized for its historical significance and outstanding representation of early 19th-century military architecture. The fortress is not only a testament to the ingenuity and determination of the Haitian people but also a poignant reminder of their struggle for freedom and self-determination. Today, it stands as a major cultural and tourist attraction, drawing visitors from around the world who come to explore its vast corridors, storerooms, and dungeons, and to learn about Haiti''s rich history. The Citadelle Laferrière remains a potent symbol of national pride and a powerful monument to the enduring spirit of independence.'),
('TXT_KEY_BUILDING_LAFERRIERE_QUOTE', '[NEWLINE]"Those who make peaceful revolution impossible will make violent revolution inevitable."[NEWLINE] - John F. Kennedy[NEWLINE]'),
('TXT_KEY_PROMOTION_LAFERRIERE', 'Unity is Strength'),
('TXT_KEY_PROMOTION_LAFERRIERE_HELP', '+25%[ICON_STRENGTH] Combat Strength. +1 [ICON_MOVES]Movement. Can Move After Attacking. [NEWLINE]+25%[ICON_STRENGTH] Combat Strength against Naval Units.'),
--======================================================================================================================
-- Victoria Terminus / Chhatrapati Shivaji Terminus
--======================================================================================================================
('TXT_KEY_BUILDING_VICTORIA_TERMINUS', 'Chhatrapati Shivaji Terminus'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_HELP', 'Special: [COLOR_YIELD_FOOD]Industrial City Connection[ENDCOLOR]; City: [COLOR_CYAN]18 Citizens[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Coaling Station in the City in which it is built and 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_RES_COAL] Coal. [NEWLINE]+15% [ICON_GOLD] Gold from [ICON_CONNECTED] City Connections and +15% [ICON_PRODUCTION] Production from [ICON_INDUSTRIAL_CONNECTED] Industrial City Connections. [NEWLINE][ICON_CONNECTED] City connections generate +5 [ICON_CULTURE] Culture. [NEWLINE]+100% [ICON_FOOD] Food or [ICON_PRODUCTION] Production from Internal Trade Routes.'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_PEDIA', 'Chhatrapati Shivaji Terminus (CST), formerly known as Victoria Terminus, is a historic railway station in Mumbai, India. Designed by British architect Frederick William Stevens, it was completed in 1887 to commemorate Queen Victoria’s Golden Jubilee. The station became a symbol of Mumbai’s rapid industrialization and was a key hub for the Great Indian Peninsula Railway. Over the years, it played a crucial role in the city’s economic and social growth, serving as a gateway for trade and migration. In 2004, CST was designated a UNESCO World Heritage Site, recognizing its architectural splendor and historical significance. [NEWLINE][NEWLINE]Architecturally, Chhatrapati Shivaji Terminus is a stunning blend of Victorian Gothic Revival and traditional Indian styles. The station features intricate stone carvings, domes, turrets, and pointed arches, inspired by medieval European cathedrals. A striking central dome with ribbed vaulting and a towering spire dominates the skyline, while the interior boasts a grand staircase, stained glass windows, and decorative ironwork. The station remains one of India’s busiest railway hubs, handling millions of passengers daily. Despite modern developments, CST retains its historic charm, standing as a testament to Mumbai’s colonial past and enduring vibrancy.'),
('TXT_KEY_BUILDING_VICTORIA_TERMINUS_QUOTE', '[NEWLINE]"Railway termini are our gates to the glorious and the unknown. Through them we pass out into adventure and sunshine, to them, alas! we return."[NEWLINE] - Edward Morgan Forster[NEWLINE]'),
--======================================================================================================================
-- Capitoline Museums
--======================================================================================================================
('TXT_KEY_BUILDING_CAPITOLINE', 'Capitoline Museums'),
('TXT_KEY_BUILDING_CAPITOLINE_HELP', 'Plot: [COLOR_CYAN]Hill[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Museum in the City in which it is built. [NEWLINE]+2 [ICON_CULTURE] Culture, [ICON_GOLDEN_AGE] Golden Age points from nearby Hills. [NEWLINE]Archaeologists can be purchased with [ICON_GOLD] Gold, gain +1 [ICON_MOVES] Movement, and have double Work rate. [NEWLINE]+4 [ICON_CULTURE] Culture, [ICON_RESEARCH] Science, and [ICON_TOURISM] Tourism if [COLOR_POSITIVE_TEXT]Themed[ENDCOLOR].'),
('TXT_KEY_BUILDING_CAPITOLINE_PEDIA', 'The Capitoline Museums, located on Rome''s Capitoline Hill, are the oldest public museums in the world, tracing their origins to 1471 when Pope Sixtus IV donated a collection of important bronze statues to the people of Rome. This act laid the foundation for the museums, which were officially opened to the public in 1734 by Pope Clement XII. The museums comprise three main buildings: the Palazzo dei Conservatori, the Palazzo Nuovo, and the Centrale Montemartini. These buildings house an extensive collection of classical sculptures, ancient Roman artifacts, Renaissance and Baroque art, and other historical pieces that reflect Rome''s rich cultural heritage. [NEWLINE][NEWLINE]Among the most notable exhibits in the Capitoline Museums are the iconic statue of the she-wolf suckling Romulus and Remus, the symbol of Rome; the colossal statue of Emperor Constantine; and the Dying Gaul, a celebrated ancient Roman sculpture. The museums also feature works by renowned artists such as Caravaggio, Titian, and Rubens. Additionally, the Capitoline Museums offer breathtaking views of the Roman Forum and surrounding areas from the Piazza del Campidoglio, designed by Michelangelo. The blend of art, history, and stunning architecture makes the Capitoline Museums a vital cultural and historical institution, attracting visitors from around the globe who seek to immerse themselves in the legacy of ancient Rome and the evolution of Western art.'),
('TXT_KEY_BUILDING_CAPITOLINE_QUOTE', '[NEWLINE]"Rome is not like any other city. It''s a big museum, a living room that shall be crossed on one''s toes."[NEWLINE] - Alberto Sordi[NEWLINE]'),
('TXT_KEY_THEMING_BONUS_CAPITOLINE', 'Wonders of Rome'),
('TXT_KEY_THEMING_BONUS_CAPITOLINE_HELP', 'To maximize your bonus, make sure all the Great Work Slots are filled.'),
--======================================================================================================================
-- Muzibu Azaala Mpanga
--======================================================================================================================
('TXT_KEY_BUILDING_KASUBI_TOMBS', 'Muzibu Azaala Mpanga'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_HELP', 'Feature: [COLOR_CYAN]Lake[ENDCOLOR]. [NEWLINE][NEWLINE]+75 [ICON_PEACE] Faith when you expend a [ICON_GREAT_PEOPLE] Great Person, scaling with Era. [NEWLINE]+2 [ICON_TOURISM] Tourism on Lakes worked by this City.[NEWLINE]All Lakes in the Empire receive +2 [ICON_FOOD] Food, +2 [ICON_GOLDEN_AGE] Golden Age Points, +2 [ICON_GREAT_GENERAL] Great General points.'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_PEDIA', 'The Muzibu Azaala Mpanga is a magnificent royal tomb located at the Kasubi Tombs complex in Kampala, Uganda. Built in 1882, it serves as the burial site for four Kabakas (kings) of Buganda: Mutesa I, Mwanga II, Daudi Chwa II, and Edward Mutesa II. The structure is renowned for its extraordinary architectural design, featuring a massive circular thatched dome that reaches over 30 feet high. As a masterpiece of Ganda architecture and craftsmanship, it was designated a UNESCO World Heritage Site in 2001, recognizing its cultural significance and unique construction techniques. [NEWLINE][NEWLINE]The tomb''s interior is divided by a series of bark cloth curtains, creating sacred spaces where the kings'' remains are housed in separate chambers alongside royal regalia. Despite suffering a devastating fire in 2010 that destroyed much of the original structure, extensive restoration efforts were undertaken to rebuild it according to traditional methods, using materials like reeds, grass, and wood without nails. The Muzibu Azaala Mpanga continues to function as both a spiritual center for the Baganda people and a powerful symbol of indigenous knowledge, cultural identity, and the enduring legacy of the Buganda Kingdom.'),
('TXT_KEY_BUILDING_KASUBI_TOMBS_QUOTE', '[NEWLINE]"Princes are like pythons. They swallow each other."[NEWLINE] - Ugandan Proverb[NEWLINE]'),
--======================================================================================================================
-- Golden Gate Bridge
--======================================================================================================================
('TXT_KEY_BUILDING_GOLDEN_GATE', 'Golden Gate Bridge'),
('TXT_KEY_BUILDING_GOLDEN_GATE_HELP', 'Terrain: [COLOR_CYAN]Coast[ENDCOLOR]. [NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_ENGINEER] Great Engineer. [NEWLINE]+10% [ICON_PRODUCTION] Production in all Cities. [NEWLINE]All International Trade Routes provide +5 [ICON_GOLDEN_AGE] Golden Age Points. [NEWLINE]+10 [ICON_INFLUENCE] Influence with all known City-States when you expend [ICON_GREAT_PEOPLE] Great People.'),
('TXT_KEY_BUILDING_GOLDEN_GATE_PEDIA', 'The Golden Gate Bridge, an iconic symbol of San Francisco, was completed in 1937 after four years of construction. Spanning the Golden Gate Strait, the 1.7-mile (2.7 km) bridge connects San Francisco to Marin County. Designed by Joseph Strauss, with significant contributions from engineers Leon Moisseiff and Irving Morrow, it was the longest and tallest suspension bridge in the world at the time of its completion. The bridge’s construction faced numerous challenges, including strong ocean currents, deep waters, and frequent fog, but advancements in safety measures—such as the use of a safety net—helped reduce worker fatalities. [NEWLINE][NEWLINE]The Golden Gate Bridge is famous for its Art Deco design and distinctive International Orange color, chosen for visibility in fog and aesthetic appeal. Today, it remains one of the most photographed landmarks in the world, carrying millions of vehicles annually and serving as both a critical transportation link and a tourist attraction. The bridge also plays a vital role in engineering history, inspiring modern bridge design. Despite the harsh marine environment, ongoing maintenance ensures its longevity. Whether admired from afar or walked across for stunning views of the San Francisco Bay, the Golden Gate Bridge remains a testament to human ingenuity and ambition.'),
('TXT_KEY_BUILDING_GOLDEN_GATE_QUOTE', '[NEWLINE]"To reach a port, we must sail. Sail, not tie at anchor. Sail, not drift."[NEWLINE] - Franklin D. Roosevelt[NEWLINE]'),
--======================================================================================================================
-- Te Tii Marae
--======================================================================================================================
('TXT_KEY_BUILDING_TE_TII_MARAE', 'Te Tii Marae'),
('TXT_KEY_BUILDING_TE_TII_MARAE_HELP', 'Building anywhere: [COLOR_CYAN]Courthouse[ENDCOLOR]. [NEWLINE][NEWLINE]All Courthouses gain +3 [ICON_PRODUCTION] Production, 1 [ICON_HAPPINESS_1] Happiness. [NEWLINE]Has 1 slot for [ICON_VP_GREATWRITING] Great Work of Writing, and starts with [ICON_VP_GREATWRITING] [COLOR_CULTURE_STORED]Treaty of Watangi[ENDCOLOR]. [NEWLINE]Every [ICON_VP_GREATWRITING] Great Work of Writing in this City grants +5 XP to all created Units (maximum of 45 XP).'),
('TXT_KEY_BUILDING_TE_TII_MARAE_PEDIA', 'Te Tii Marae is a unique meeting center. Like other marae in the Pacific, it served as both a sacred place for religion and a social meeting place in Polynesian culture. The term "marae" - mala''e in Tongan and malae in Samoan and Hawaiian - means "cleared, free of weeds and trees". In the Maori society the marae is where the culture flourishes; obligations between tribes are met there, families would hold certain occasions there, and important ceremonies are held there.[NEWLINE][NEWLINE]Te Tii Marae is more than that, however. The site is still in use today as part of Waitangi Day, the New Zealand holiday to commemorate the signing of the Treaty of Waitangi. On February 6 1840 the treaty was signed in a marquee at the grounds of James Busby''s house - now known as the Treaty House, making New Zealand part of the British Empire and ensuring the right of the Maori to their land and their rights as British subjects. However this had led to disagreements between the Europeans and Maori. The Maori view the treaty as a sacred pact, while the Pakeha - Maori for European New Zealanders - have taken disregard to it for many years. Chief Justice James Prendergast declared the treaty a "legal nullity" in 1877, displaying the European disconcern of the treaty until the Treaty of Waitangi Act in 1975 - almost a century later.[NEWLINE][NEWLINE]Today Te Tii Marae hosts the annual celebrations the day before Waitangi Day - Feburary 5 - where the New Zealander Prime Minister and other political figures are invited to the site and hears the speeches of the iwi - the large social group of Maori society. With celebration comes tensions between the two peoples as Waidangi Day is also a hotspot for Maori rights; as far back as 1971 Waitangi and the day have been marred by protests and activism concerning the treaty.'),
('TXT_KEY_BUILDING_TE_TII_MARAE_QUOTE', '[NEWLINE]"When what is not Maori is Pakeha and what is not Pakeha is Maori, I occupy the gap between the two, that black hole in which nothing can be seen and from which nothing can be heard."[NEWLINE] - Annamarie Jagose[NEWLINE]'),
('TXT_KEY_GREAT_WORK_TREATY_WATANGI', 'Treaty of Watangi'),
('TXT_KEY_GREAT_WORK_TREATY_WATANGI_QUOTE', '[NEWLINE]"Her Majesty the Queen of England extends to the Natives of New Zealand Her royal protection and imparts to them all the Rights and Privileges of British Subjects."[NEWLINE] - Treaty of Watangi[NEWLINE]'),
--======================================================================================================================
-- Changi Airport
--======================================================================================================================
('TXT_KEY_BUILDING_CHANGI_AIRPORT', 'Changi Airport'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_HELP', 'Special: [COLOR_YIELD_GOLD]Capital[ENDCOLOR]. [NEWLINE][NEWLINE]Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Airport in the City in which it is built. [NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_MERCHANT] Great Merchant. [NEWLINE]All Airports gain +2 [ICON_PRODUCTION] Production, +2 [ICON_GOLD] Gold, +2 [ICON_TOURISM] Tourism, +2 [ICON_GOLDEN_AGE] Golden Age points. [NEWLINE]All cities get +1 Air Unit Slot.'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_PEDIA', 'Singapore Changi Airport, often regarded as one of the world''s best airports, opened on 1 July 1981 to replace Paya Lebar Airport as Singapore''s main international gateway. The airport was built on reclaimed land in Changi, on the eastern tip of the island, and has since expanded into a global aviation hub. Over the years, it has undergone multiple expansions, growing from a single terminal to four main terminals, with the addition of Jewel Changi Airport in 2019—a lifestyle complex featuring gardens, retail, and the world''s tallest indoor waterfall. Changi Airport is known for its efficiency, top-tier passenger services, and extensive connectivity, serving over 100 airlines and linking Singapore to more than 400 cities worldwide. [NEWLINE][NEWLINE]Beyond being a transit hub, Changi Airport is an iconic destination offering world-class amenities, including themed gardens, movie theaters, free rest zones, and luxury shopping. It consistently ranks as one of the world''s busiest and most awarded airports, handling over 68 million passengers annually before the pandemic. The airport is also a key economic driver for Singapore, supporting its tourism and logistics industries. With future expansions, including the upcoming Terminal 5, Changi Airport aims to reinforce its position as a premier global air travel hub while embracing sustainability and innovation.'),
('TXT_KEY_BUILDING_CHANGI_AIRPORT_QUOTE', '[NEWLINE]"There was nowhere to go but everywhere, so just keep on rolling under the stars."[NEWLINE] - Jack Kerouac[NEWLINE]'),
--======================================================================================================================
-- Watson Research Center
--======================================================================================================================
('TXT_KEY_BUILDING_WATSON_RC', 'Watson Research Center'),
('TXT_KEY_BUILDING_WATSON_RC_HELP', 'Plot: [COLOR_CYAN]Flat[ENDCOLOR]; Building: [COLOR_CYAN]Research Lab[ENDCOLOR]. [NEWLINE][NEWLINE]+10% [ICON_RESEARCH] Science in your Empire. [NEWLINE]10% of [ICON_RESEARCH] Science created by all Cities on Empire counts as [ICON_PRODUCTION] Production Per Turn. [NEWLINE]All Manufactories and Towns in the Empire receive +4 [ICON_RESEARCH] Science.'),
('TXT_KEY_BUILDING_WATSON_RC_PEDIA', 'The Thomas J. Watson Research Center is IBM''s principal research facility, named after the company''s former CEO, Thomas J. Watson, Sr. Established in 1961, the center serves as the heart of IBM Research, focusing on cutting-edge advancements in computing, artificial intelligence, quantum computing, and semiconductor technology. The main campus, located in Yorktown Heights, New York, was designed by renowned architect Eero Saarinen, featuring a futuristic, wave-like structure that symbolizes innovation. Additional IBM research labs associated with the center are in Cambridge, Massachusetts, and Almaden, California. Over the decades, the Watson Research Center has contributed to groundbreaking developments, including IBM''s Deep Blue, which famously defeated chess champion Garry Kasparov in 1997, and Watson AI, which won Jeopardy! in 2011. [NEWLINE][NEWLINE]As a global leader in scientific and technological research, the Watson Research Center continues to drive advancements in cloud computing, cybersecurity, AI ethics, and quantum computing. The facility collaborates with universities, governments, and enterprises to push the boundaries of innovation. IBM''s quantum computing research, headquartered at Watson, is pioneering quantum processors that could revolutionize fields such as cryptography and materials science. With a strong emphasis on fundamental and applied research, the Watson Research Center remains at the forefront of technological breakthroughs, shaping the future of computing and artificial intelligence.'),
('TXT_KEY_BUILDING_WATSON_RC_QUOTE', '[NEWLINE]"If we knew what we were doing, it wouldn''t be called research."[NEWLINE] - Albert Einstein[NEWLINE]');
--======================================================================================================================
INSERT INTO Language_ko_KR 
				(Tag,										Text) 
SELECT DISTINCT	'TXT_KEY_BUILDING_'||b.WType||'_HELP_CUT',	Text
FROM Language_ko_KR a, JHWfVPConfig b WHERE a.Tag = 'TXT_KEY_BUILDING_'||b.WType||'_HELP';
--======================================================================================================================
--======================================================================================================================