----------------------------------------------
-- Pantheons
----------------------------------------------

-- Ancestor Worship
UPDATE Language_ko_KR
SET Text = '[ICON_CITIZEN]시민 4명마다 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 자문회의 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR], [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_ANCESTOR_WORSHIP';

UPDATE Language_ko_KR
SET Text = '불의 신'
WHERE Tag = 'TXT_KEY_BELIEF_EARTH_MOTHER_SHORT';

UPDATE Language_ko_KR
SET Text = '광산이 건설된 자원 타일의 [ICON_CULTURE]문화, [ICON_PRODUCTION] 생산 및 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 대장간의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_EARTH_MOTHER';

UPDATE Language_ko_KR
SET Text = '만물의 창조주'
WHERE Tag = 'TXT_KEY_BELIEF_TEARS_OF_GODS_SHORT';

UPDATE Language_ko_KR
SET Text = '기념비의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가하고 [ICON_CAPITAL]수도의 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 창시된 종교관 2개마다 [ICON_CAPITAL]수도/성도의 [ICON_RESEARCH]과학, [ICON_GOLD]골드, [ICON_PRODUCTION]생산, [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. (최대 8 종교관)'
WHERE Tag = 'TXT_KEY_BELIEF_TEARS_OF_GODS';

UPDATE Language_ko_KR
SET Text = '상업의 신'
WHERE Tag = 'TXT_KEY_BELIEF_MESSENGER_GODS_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_CONNECTED]도시 연결 및 활성화된 교역로마다 [ICON_GOLD] 골드 및 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 수도/성도의 [ICON_GREAT_MERCHANT]위대한 상인 점수가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가하고, 두번째 도시를 개척하면 수도/성도의 [ICON_PEACE]신앙 및 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_MESSENGER_GODS';

UPDATE Language_ko_KR
SET Text = '장인의 신'
WHERE Tag = 'TXT_KEY_BELIEF_STONE_CIRCLES_SHORT';

UPDATE Language_ko_KR
SET Text = '채석장의 [ICON_PEACE] 신앙 및 [ICON_PRODUCTION] 생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 궁전의 [ICON_PEACE]신앙 및 [ICON_RESEARCH]과학이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 석재 공장의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_STONE_CIRCLES';

UPDATE Language_ko_KR
SET Text = '확장의 신'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_SETTLEMENTS_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_CULTURE_LOCAL] 국경 확장 속도가 [COLOR_POSITIVE_TEXT] 25%[ENDCOLOR] 증가합니다. 국경이 확장될 때 [ICON_PEACE]신앙을 [COLOR_POSITIVE_TEXT]25[ENDCOLOR], [ICON_PRODUCTION]생산을 [COLOR_POSITIVE_TEXT]15[ENDCOLOR] 제공합니다. [COLOR:110:110:110:255](게임 속도별 보정)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_SETTLEMENTS';

-- God of the Open Sky
UPDATE Language_ko_KR
SET Text = '언덕 등 다른 지형 특징이 없는 작업 중인 평지 평원 또는 초원 타일 2개마다 [ICON_CULTURE]문화 및 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 목장의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_OPEN_SKY';

-- God of the Sea
UPDATE Language_ko_KR
SET Text = '어선 및 산호초의 [ICON_PEACE]신앙 및 [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 해안 도시의 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GOD_SEA';

UPDATE Language_ko_KR
SET Text = '별과 하늘의 신'
WHERE Tag = 'TXT_KEY_BELIEF_DANCE_AURORA_SHORT';

UPDATE Language_ko_KR
SET Text = '툰드라 또는 설원 위 자원 타일의 [ICON_PEACE]신앙, [ICON_FOOD]식량, [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_DANCE_AURORA';

UPDATE Language_ko_KR
SET Text = '태양의 신'
WHERE Tag = 'TXT_KEY_BELIEF_SUN_GOD_SHORT';

UPDATE Language_ko_KR
SET Text = '곡창의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 농장이 건설된 자원 타일의 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] [ICON_RESEARCH] 과학이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] [ICON_FOOD] 식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_SUN_GOD';

-- God of War
UPDATE Language_ko_KR
SET Text = '전투 유닛을 처치 시 유닛 [ICON_STRENGTH] 전투력의 175%만큼 [ICON_PEACE]신앙을 획득합니다. 병영의 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GOD_WAR';

-- God-King
UPDATE Language_ko_KR
SET Text = '궁전의 [ICON_PEACE]신앙 및 [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 당신 문명의 종교관을 따르는 신도 5명마다 [ICON_CAPITAL]수도/성도의 [ICON_CULTURE]문화, [ICON_GOLDEN_AGE]황금기 점수, [ICON_PEACE]신앙, [ICON_GOLD]골드, [ICON_RESEARCH]과학이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GOD_KING';

UPDATE Language_ko_KR
SET Text = '미의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_MONUMENT_GODS_SHORT';

UPDATE Language_ko_KR
SET Text = '궁전 및 세계 불가사의의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가하고 [ICON_GREAT_WORK]걸작에서 오는 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [ICON_CAPITAL]수도/성도의 [ICON_GREAT_ARTIST] 위대한 예술가 및 [ICON_GREAT_ENGINEER] 위대한 기술자 점수가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_MONUMENT_GODS';

-- Goddess of Festivals
UPDATE Language_ko_KR
SET Text = '궁전의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 소유 또는 수입한 모든 고유 사치 자원 1개마다 [ICON_CAPITAL] 수도/성도의 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]3[ENDCOLOR], [ICON_PEACE]신앙 및 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GOD_FESTIVALS';

UPDATE Language_ko_KR
SET Text = '자연의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_ONE_WITH_NATURE_SHORT';

UPDATE Language_ko_KR
SET Text = '도시 주변 3타일 이내의 산 2개마다 [ICON_FOOD] 식량, [ICON_GOLD] 골드, [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [COLOR:110:110:110:255](한도: 도시 인구)[ENDCOLOR] 자연 경관의 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]3[ENDCOLOR], [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_ONE_WITH_NATURE';

-- Goddess of Protection
UPDATE Language_ko_KR
SET Text = '우호 영토 내에서 매 턴 체력을 [COLOR_POSITIVE_TEXT]10[ENDCOLOR] 회복합니다. 궁전의 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 증가하고, 성벽의 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_CULTURE] 문화가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_STRATEGY';

UPDATE Language_ko_KR
SET Text = '순수의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_SACRED_WATERS_SHORT';

UPDATE Language_ko_KR
SET Text = '호수 타일의 [ICON_PEACE] 신앙 및 [ICON_FOOD] 식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가하고 습지 타일의 [ICON_PEACE] 신앙, [ICON_FOOD] 식량, [ICON_PRODUCTION] 생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 강과 인접한 도시의 [ICON_HAPPINESS_1]행복이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_SACRED_WATERS';

UPDATE Language_ko_KR
SET Text = '부활의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_SACRED_PATH_SHORT';

UPDATE Language_ko_KR
SET Text = '숲 또는 정글 타일 2개마다 [ICON_PEACE] 신앙, [ICON_CULTURE] 문화, [ICON_RESEARCH] 과학이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 시장의 [ICON_FOOD] 식량 및 [ICON_RESEARCH] 과학이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_SACRED_PATH';

UPDATE Language_ko_KR
SET Text = '봄의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_ORAL_TRADITION_SHORT';

UPDATE Language_ko_KR
SET Text = '재배지의 [ICON_PEACE] 신앙, [ICON_FOOD] 식량, [ICON_GOLD] 골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 모든 약초상의 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_RESEARCH] 과학이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_ORAL_TRADITION';

UPDATE Language_ko_KR
SET Text = '가정의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_FERTILITY_RITES_SHORT';

UPDATE Language_ko_KR
SET Text = '성소의 [ICON_PEACE]신앙 및 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 건물의 건설을 완료하면 [ICON_PEACE]신앙 및 [ICON_FOOD]식량을 [COLOR_POSITIVE_TEXT]8[ENDCOLOR] [COLOR:110:110:110:255](시대별 보정)[ENDCOLOR] 제공합니다. 도시의 [ICON_FOOD]성장률이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_FERTILITY_RITES';

-- Goddess of the Hunt
UPDATE Language_ko_KR
SET Text = '야영지의 [ICON_PEACE]신앙, [ICON_CULTURE]문화, [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 훈제실의 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_HUNT';

UPDATE Language_ko_KR
SET Text = '지혜의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_FORMAL_LITURGY_SHORT';

UPDATE Language_ko_KR
SET Text = '모든 도시의 [ICON_PEACE]신앙 및 [ICON_RESEARCH]과학이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가하고 수도/성도의 [ICON_GREAT_SCIENTIST]위대한 과학자 점수가 [COLOR_POSITIVE_TEXT]2 [ENDCOLOR]증가합니다. 전문가가 있는 도시의 [ICON_PEACE]신앙 및 [ICON_RESEARCH]과학이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_FORMAL_LITURGY';

UPDATE Language_ko_KR
SET Text = '사막의 영혼'
WHERE Tag = 'TXT_KEY_BELIEF_DESERT_FOLKLORE_SHORT';

UPDATE Language_ko_KR
SET Text = '사막 위 자원 타일의 [ICON_PEACE]신앙, [ICON_PRODUCTION]생산, [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 오아시스 타일의 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_DESERT_FOLKLORE';

UPDATE Language_ko_KR
SET Text = '수호신'
WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_LOVE_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_CITIZEN]시민이 3명 이상인 도시의 [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 모든 기술자 전문가의 [ICON_PEACE]신앙 및 [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.' 
WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_LOVE';

----------------------------------------------
-- Founders
----------------------------------------------
UPDATE Language_ko_KR
SET Text = '복음 전도'
WHERE Tag = 'TXT_KEY_BELIEF_PILGRIMAGE_SHORT';

UPDATE Language_ko_KR
SET Text = '외국 도시에 당신 문명의 [ICON_RELIGION]종교를 전파할 때 +15 [ICON_FOOD]식량을 성도에 제공하고, [COLOR:110:110:110:255](새로운 신도 수에 따라 보정)[ENDCOLOR] [ICON_TOURISM]관광을 [COLOR_POSITIVE_TEXT]15[ENDCOLOR] [COLOR:110:110:110:255](다른 종교의 신도 수에 따라 보정) [ENDCOLOR]제공합니다. [NEWLINE][COLOR_YELLOW]사도 궁전 [ENDCOLOR] 불가사의를 건설할 수 있습니다. (+4 [ICON_PEACE] 신앙, +4 [ICON_GOLDEN_AGE] 황금기 점수;  [ICON_RELIGION]성지에서 +5 [ICON_TOURISM] 관광; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_PILGRIMAGE';

-- Ceremonial Burial
UPDATE Language_ko_KR
SET Text = '[ICON_GREAT_PEOPLE]위인을 소모할 때 당신의 [ICON_RELIGION]종교를 따르는 도시에 [COLOR:110:110:110:255](한도: 25도시)[ENDCOLOR] [ICON_PEACE]신앙 및 [ICON_CULTURE]문화를 [COLOR_POSITIVE_TEXT]10[ENDCOLOR] 제공합니다. [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR][NEWLINE][COLOR_YELLOW]마우솔레움[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. (+5 [ICON_PEACE] 신앙, 전투로 인해 유닛이 사망 시 [ICON_PEACE] 신앙, [ICON_RELIGION]성지에서 +5 [ICON_PEACE] 신앙; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_CEREMONIAL_BURIAL';

UPDATE Language_ko_KR
SET Text = '원로회'
WHERE Tag = 'TXT_KEY_BELIEF_PAPAL_PRIMACY_SHORT';

UPDATE Language_ko_KR
SET Text = '당신 문명의 종교를 처음 채택한 도시는 [COLOR:110:110:110:255](한도: 25도시)[ENDCOLOR] 당신의 성도에 [ICON_RESEARCH]과학 및 [ICON_PRODUCTION]생산을 [COLOR_POSITIVE_TEXT]20[ENDCOLOR] [COLOR:110:110:110:255](종교를 따르는 도시의 수에 따라 보정)[ENDCOLOR] 제공합니다. [NEWLINE][COLOR_YELLOW]종교 공의회[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. (+4 [ICON_PEACE] 신앙, +5 [ICON_FOOD] 식량;  [ICON_RELIGION]성지에서 +5 [ICON_RESEARCH] 과학; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_PAPAL_PRIMACY';

UPDATE Language_ko_KR
SET Text = '신성한 유산'
WHERE Tag = 'TXT_KEY_BELIEF_PEACE_LOVING_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_GOLDEN_AGE]황금기 동안 성도의 산출량이 [COLOR_POSITIVE_TEXT]20%[ENDCOLOR] 증가합니다. [NEWLINE][COLOR_YELLOW]천상의 옥좌[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다.(+2 [ICON_PEACE] 신앙, [ICON_CULTURE] 문화, [ICON_FOOD] 식량, [ICON_RESEARCH] 과학, [ICON_GOLD] 골드, [ICON_PRODUCTION] 생산; [ICON_RELIGION]성지에서 +5 [ICON_GOLDEN_AGE] 황금기 점수; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_PEACE_LOVING';

UPDATE Language_ko_KR
SET Text = '영웅 숭배'
WHERE Tag = 'TXT_KEY_BELIEF_INTERFAITH_DIALOGUE_SHORT';

UPDATE Language_ko_KR
SET Text = '도시를 정복했을 때 [ICON_GOLDEN_AGE]황금기 점수, [ICON_PEACE]신앙을 100, [ICON_GREAT_GENERAL] 위대한 장군 점수 [COLOR:110:110:110:255](내륙 도시)[ENDCOLOR] 위대한 제독 점수 [COLOR:110:110:110:255](해안 도시)[ENDCOLOR]를 25 제공합니다. [COLOR:110:110:110:255](시대 및 시민 수에 따라 보정)[ENDCOLOR][NEWLINE][COLOR_YELLOW]위대한 제단[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. (+5 [ICON_PEACE] 신앙, 군사 유닛 [ICON_PRODUCTION]생산 +15%; [ICON_RELIGION]성지에서 +5 [ICON_PRODUCTION] 생산; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_INTERFAITH_DIALOGUE';

UPDATE Language_ko_KR
SET Text = '신성한 법'
WHERE Tag = 'TXT_KEY_BELIEF_CHURCH_PROPERTY_SHORT';

UPDATE Language_ko_KR
SET Text = '정책을 채택할 때 당신 문명의 [ICON_RELIGION]종교를 따르는 신도 1명마다 [COLOR:110:110:110:255](한도: 250명)[ENDCOLOR] [ICON_PEACE]신앙, [ICON_RESEARCH]과학, [ICON_GOLD]골드를 [COLOR_POSITIVE_TEXT]5[ENDCOLOR] 제공합니다. [NEWLINE][COLOR_YELLOW]성스러운 법정[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. (+4 [ICON_PEACE] 신앙, +6 [ICON_GOLD] 골드;  [ICON_RELIGION]성지에서 +5 [ICON_CULTURE] 문화; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_CHURCH_PROPERTY';

UPDATE Language_ko_KR
SET Text = '신권정치'
WHERE Tag = 'TXT_KEY_BELIEF_WORLD_CHURCH_SHORT';

UPDATE Language_ko_KR
SET Text = '"국왕 경축일"이 열리는 동안 [ICON_PEACE]신앙, [ICON_CULTURE]문화, [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]15%[ENDCOLOR] 증가합니다. [NEWLINE][COLOR_YELLOW]대 납골당[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. (+10 [ICON_PEACE] 신앙;  [ICON_RELIGION]성지에서 +5 [ICON_GOLD] 골드; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_WORLD_CHURCH';

UPDATE Language_ko_KR
SET Text = '초월적인 판단'
WHERE Tag = 'TXT_KEY_BELIEF_INITIATION_RITES_SHORT';

UPDATE Language_ko_KR
SET Text = '새로운 시대로 진입할 때 당신 문명의 [ICON_RELIGION]종교를 따르는 도시 1개마다 [COLOR:110:110:110:255](한도: 25도시)[ENDCOLOR] 각 산출량을 [COLOR_POSITIVE_TEXT]12[ENDCOLOR] [COLOR:110:110:110:255](시대별 보정)[ENDCOLOR] 제공합니다. [NEWLINE][COLOR_YELLOW]신성한 정원[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. (+3 [ICON_PEACE] 신앙, +5 [ICON_CULTURE] 문화;  [ICON_RELIGION]성지에서 +5 [ICON_FOOD] 식량; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_INITIATION_RITES';

UPDATE Language_ko_KR
SET Text = '시현'
WHERE Tag = 'TXT_KEY_BELIEF_TITHE_SHORT';

UPDATE Language_ko_KR
SET Text = '새로운 [ICON_RESEARCH]기술을 연구하면, [ICON_RELIGION]종교의 신도마다 [ICON_GOLDEN_AGE] 황금기 점수, [ICON_PEACE]신앙, [ICON_CULTURE] 문화를 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 제공합니다. [COLOR:105:105:105:255](한도: 250명)[ENDCOLOR] [NEWLINE][COLOR_YELLOW]기록저장소[ENDCOLOR] 국가 불가사의를 건설할 수 있습니다. ([ICON_RELIGION]성지에서 +5 [ICON_RESEARCH] 과학; [COLOR_POSITIVE_TEXT]개혁 교리[ENDCOLOR]를 선택할 수 있습니다.)'
WHERE Tag = 'TXT_KEY_BELIEF_TITHE';

----------------------------------------------
-- Followers
----------------------------------------------

-- Asceticism
UPDATE Language_ko_KR
SET Text = '신도 1명마다 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] [COLOR:110:110:110:255](한도: [ICON_FOOD]15)[ENDCOLOR]증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_ASCETISM';

-- Cathedrals
UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 대성당을 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_CATHEDRALS';

UPDATE Language_ko_KR
SET Text = '교회'
WHERE Tag = 'TXT_KEY_BELIEF_SWORD_PLOWSHARES_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 교회를 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_SWORD_PLOWSHARES';

UPDATE Language_ko_KR
SET Text = '면죄부'
WHERE Tag = 'TXT_KEY_BELIEF_PEACE_GARDENS_SHORT';

UPDATE Language_ko_KR
SET Text = '도시의 턴 당 [ICON_GOLD] 골드 [COLOR_POSITIVE_TEXT]10[ENDCOLOR]마다 [ICON_PEACE] 신앙을 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 얻습니다. [COLOR:110:110:110:255](한도: 도시 내 신도 수의 절반)[ENDCOLOR] 신앙 구매의 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR]가 [ICON_GOLD] 골드와 [ICON_PRODUCTION] 생산으로 전환됩니다.'
WHERE Tag = 'TXT_KEY_BELIEF_PEACE_GARDENS';

UPDATE Language_ko_KR
SET Text = '영감'
WHERE Tag = 'TXT_KEY_BELIEF_DIVINE_INSPIRATION_SHORT';

UPDATE Language_ko_KR
SET Text = '신도 3명마다 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] [COLOR:105:105:105:255](한도: [ICON_CULTURE]6)[ENDCOLOR] 증가합니다. 전문가가 있는 도시의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_DIVINE_INSPIRATION';

UPDATE Language_ko_KR
SET Text = '근면'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_COMMUNITY_SHORT';

UPDATE Language_ko_KR
SET Text = '신도 2명마다 [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [COLOR:110:110:110:255](한도: [ICON_PRODUCTION]15)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_COMMUNITY';

UPDATE Language_ko_KR
SET Text = '만디르'
WHERE Tag = 'TXT_KEY_BELIEF_GURUSHIP_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 만디르를 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_GURUSHIP';

UPDATE Language_ko_KR
SET Text = '통달'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_ART_SHORT';

UPDATE Language_ko_KR
SET Text =  '전문가의 [ICON_GOLDEN_AGE]황금기 점수 및 주요 산출량이 ([ICON_RESEARCH] 과학자, [ICON_GOLD] 상인/공무원, [ICON_PRODUCTION] 기술자, [ICON_CULTURE] 작가/예술가/음악가) [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_ART';

-- Mosques
UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 모스크를 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_MOSQUES';

UPDATE Language_ko_KR
SET Text = '기사단'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_CENTER_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 기사단을 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_CENTER';

-- Pagodas
UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 파고다를 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_PAGODAS';

UPDATE Language_ko_KR
SET Text = '학식'
WHERE Tag = 'TXT_KEY_BELIEF_CHORAL_MUSIC_SHORT';

UPDATE Language_ko_KR
SET Text = '신도 2명마다 [ICON_RESEARCH]과학이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] [COLOR:110:110:110:255](한도: [ICON_RESEARCH]15)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_BELIEF_CHORAL_MUSIC';

UPDATE Language_ko_KR
SET Text = '사리탑'
WHERE Tag = 'TXT_KEY_BELIEF_MONASTERIES_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 사리탑을 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_MONASTERIES';

UPDATE Language_ko_KR
SET Text = '회당'
WHERE Tag = 'TXT_KEY_BELIEF_HOLY_WARRIORS_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 회당을 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_HOLY_WARRIORS';

UPDATE Language_ko_KR
SET Text = '절약'
WHERE Tag = 'TXT_KEY_BELIEF_FEED_WORLD_SHORT';

UPDATE Language_ko_KR
SET Text = '신도 1명마다 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [COLOR:105:105:105:255](한도: [ICON_GOLD]10)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_BELIEF_FEED_WORLD';

UPDATE Language_ko_KR
SET Text = '구루쿨람'
WHERE Tag = 'TXT_KEY_BELIEF_LITURGICAL_DRAMA_SHORT';

UPDATE Language_ko_KR
SET Text = '도시의 턴 당 [ICON_RESEARCH] 과학 [COLOR_POSITIVE_TEXT]5[ENDCOLOR]마다 [ICON_PEACE] 신앙을 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 얻습니다. [COLOR:110:110:110:255](한도: 도시 내 신도 수의 절반)[ENDCOLOR] [ICON_PEACE] 신앙 구매의 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR]를 [ICON_CULTURE] 문화와 [ICON_FOOD] 식량으로 전환합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_LITURGICAL_DRAMA';

----------------------------------------------
-- Enhancers
----------------------------------------------
UPDATE Language_ko_KR
SET Text = '평화의 거주지'
WHERE Tag = 'TXT_KEY_BELIEF_JUST_WAR_SHORT';

UPDATE Language_ko_KR
SET Text = '우호적인 [ICON_CITY_STATE]도시 국가의 종교 압력이 +100% 증가합니다. 이 [ICON_RELIGION]종교를 따르는 도시 국가의 신도 2명마다 성도의 [ICON_PEACE]신앙 및 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 당신의 종교를 따르는 도시 국가 [ICON_INFLUENCE]영향력 정지점이 [COLOR_POSITIVE_TEXT]35[ENDCOLOR]로 증가하며 도시 국가의 퀘스트 보상이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_JUST_WAR';

UPDATE Language_ko_KR
SET Text = '종교 재판'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_TEXTS_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_INQUISITOR]이단심문관의 구매 [ICON_PEACE]비용이 [COLOR_POSITIVE_TEXT]33%[ENDCOLOR] 감소합니다. 이단 제거 시 개종된 [ICON_CITIZEN]시민 1명마다 [ICON_GOLD]골드를 [COLOR_POSITIVE_TEXT]25[ENDCOLOR] 제공합니다. 당신 문명의 [ICON_SPY]스파이가 배치된 도시에 종교 압력을 [COLOR_POSITIVE_TEXT]52[ENDCOLOR] [COLOR:110:110:110:255](표준 속도)[ENDCOLOR] 행사하고 외국 도시에 주둔하면 [ICON_HAPPINESS_1]행복이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_TEXTS';

UPDATE Language_ko_KR
SET Text = '탁발'
WHERE Tag = 'TXT_KEY_BELIEF_RELIQUARY_SHORT';

UPDATE Language_ko_KR
SET Text = '이 [ICON_RELIGION]종교를 따르는 모든 도시의 [ICON_CULTURE]문화 및 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. [ICON_MISSIONARY]선교사가 종교를 전파할 때 다른 종교의 종교 압력을 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 감소시킵니다.'
WHERE Tag = 'TXT_KEY_BELIEF_RELIQUARY';

UPDATE Language_ko_KR
SET Text = '정교'
WHERE Tag = 'TXT_KEY_BELIEF_HOLY_ORDER_SHORT';

UPDATE Language_ko_KR
SET Text = '전파 거리가 [COLOR_POSITIVE_TEXT]40%[ENDCOLOR] 증가합니다. [ICON_INTERNATIONAL_TRADE]교역로가 연결된 다른 문명에 대한 종교 압력이 [COLOR_POSITIVE_TEXT]200%[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_HOLY_ORDER';

UPDATE Language_ko_KR
SET Text = '예언'
WHERE Tag = 'TXT_KEY_BELIEF_MESSIAH_SHORT';

UPDATE Language_ko_KR
SET Text = '불가사의 건설에 필요한 정책 수가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 감소합니다. [ICON_PROPHET]위대한 선지자의 전도력이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 증가하고 생산에 필요한 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 감소합니다. 성지의 산출량이 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 증가합니다. 만약 대중 종교라면 적[ICON_INQUISITOR]이단심문관 및 [ICON_PROPHET]위대한 선지자로 인한 신도의 감소가 [COLOR_POSITIVE_TEXT]절반[ENDCOLOR]으로 줄어듭니다.'
WHERE Tag = 'TXT_KEY_BELIEF_MESSIAH';

UPDATE Language_ko_KR
SET Text = '교회력'
WHERE Tag = 'TXT_KEY_BELIEF_MISSIONARY_ZEAL_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_GOLDEN_AGE]황금기 동안 성도의 [ICON_GREAT_PEOPLE]위인 출현율이 [COLOR_POSITIVE_TEXT]33%[ENDCOLOR] 증가합니다. 이 종교를 따르는 외국 도시 1개마다 성도의 [ICON_GOLD]골드 및 [ICON_GOLDEN_AGE]황금기 점수가 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 증가합니다. [ICON_MISSIONARY]선교사의 전도력이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_MISSIONARY_ZEAL';

UPDATE Language_ko_KR
SET Text = '상징주의'
WHERE Tag = 'TXT_KEY_BELIEF_ITINERANT_PREACHERS_SHORT';

UPDATE Language_ko_KR
SET Text = '성도의 [ICON_GOLDEN_AGE]황금기 점수가 [COLOR_POSITIVE_TEXT]5[ENDCOLOR] 증가하고 매 턴 모든 [ICON_GREAT_PEOPLE]위인 점수가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_ITINERANT_PREACHERS';

UPDATE Language_ko_KR
SET Text = '보편주의'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_UNITY_SHORT';

UPDATE Language_ko_KR
SET Text = '소유한 도시에서 다른 종교를 믿는 신도 5명마다 성도의 [ICON_RESEARCH]과학, [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 외국 도시의 신도 10명마다 성도의 [ICON_GOLD] 골드와 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_UNITY';

UPDATE Language_ko_KR
SET Text = '광신'
WHERE Tag = 'TXT_KEY_BELIEF_HEATHEN_CONVERSION_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 지상 유닛을 구매할 수 있습니다. 종교를 따르는 도시 1개마다 전략 자원의 양이 [COLOR_POSITIVE_TEXT]1%[ENDCOLOR] [COLOR:110:110:110:255](한도: 25%)[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_HEATHEN_CONVERSION';

----------------------------------------------
-- Reformations
----------------------------------------------
UPDATE Language_ko_KR
SET Text = '십자군 정신'
WHERE Tag = 'TXT_KEY_BELIEF_EVANGELISM_SHORT';

UPDATE Language_ko_KR
SET Text = '적 영토 내 지상 유닛과 전투 시 지상 유닛의 [ICON_STRENGTH] 전투력 보너스가 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다. 추가로 당신 문명의 종교를 따르지 않는 적 지상 유닛과 전투 시 [ICON_STRENGTH] 전투력 보너스가 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다. 도시를 정복했을 때 [ICON_CULTURE] 문화 및 [ICON_GOLD]골드를 [COLOR_POSITIVE_TEXT]50[ENDCOLOR] 제공합니다. [COLOR:105:105:105:255](시대와 도시의 인구수에 따라 보정)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_BELIEF_EVANGELISM';

-- Defender of the Faith
UPDATE Language_ko_KR
SET Text = '우호 영토 내 지상 유닛과 전투 시 지상 유닛의 [ICON_STRENGTH] 전투력 보너스가 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다. 추가로 당신 문명의 종교를 따르지 않는 적 지상 유닛과 전투 시 [ICON_STRENGTH] 전투력 보너스가 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다.  모든 방어 건물의 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR], [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_DEFENDER_FAITH';

UPDATE Language_ko_KR
SET Text = '신성한 가르침'
WHERE Tag = 'TXT_KEY_BELIEF_JESUIT_EDUCATION_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 도서관, 대학, 공립학교, 연구소를 구매할 수 있고 해당 건물의 [ICON_RESEARCH]과학이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 성도에서 [ICON_GREAT_PEOPLE]위인을 소모할 때 [ICON_PEACE]신앙을 [COLOR_POSITIVE_TEXT]20[ENDCOLOR] [COLOR:110:110:110:255](시대별 보정)[ENDCOLOR] 제공합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_JESUIT_EDUCATION';

UPDATE Language_ko_KR
SET Text = '대중의 신앙'
WHERE Tag = 'TXT_KEY_BELIEF_UNDERGROUND_SECT_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_PEACE]신앙으로 원형극장, 오페라 극장, 박물관, 방송탑을 구매할 수 있고, 해당 건물의 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 이 종교를 따르는 도시 2개마다 성도의 [ICON_HAPPINESS_1]행복이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_UNDERGROUND_SECT';

UPDATE Language_ko_KR
SET Text = '범인류적 계명'
WHERE Tag = 'TXT_KEY_BELIEF_CHARITABLE_MISSIONS_SHORT';

UPDATE Language_ko_KR
SET Text = '종교 전파 속도가 [COLOR_POSITIVE_TEXT]15%[ENDCOLOR] 증가하고 ([COLOR_RESEARCH_STORED]인쇄술[ENDCOLOR] 연구 시 [COLOR_POSITIVE_TEXT]30%[ENDCOLOR]), 세계 대회 또는 유엔에서 결의안이 통과되면 [ICON_RESEARCH]과학, [ICON_CULTURE]문화, [ICON_GOLD]골드, [ICON_PEACE]신앙, [ICON_GOLDEN_AGE]황금기 점수가 [COLOR_POSITIVE_TEXT]350[ENDCOLOR] [COLOR:110:110:110:255](시대별 보정)[ENDCOLOR] 제공합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_CHARITABLE_MISSIONS';

UPDATE Language_ko_KR
SET Text = '성역'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_FERVOR_SHORT';

UPDATE Language_ko_KR
SET Text = '[ICON_RELIGION] 성지 또는 [ICON_TOURISM] 랜드마크 2개마다 세계 대회 추가 [ICON_DIPLOMAT] 대표단을 1명 확보합니다. 이 종교를 따르는 우호적/동맹인 [ICON_CITY_STATE]도시 국가에서 오는 산출량이 [COLOR_POSITIVE_TEXT]50%[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_FERVOR';

UPDATE Language_ko_KR
SET Text = '영감을 받은 작품'
WHERE Tag = 'TXT_KEY_BELIEF_UNITY_OF_PROPHETS_SHORT';

UPDATE Language_ko_KR
SET Text = '랜드마크 및 위인 시설의 [ICON_PEACE] 신앙 및 [ICON_RESEARCH] 과학이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. [ICON_GREAT_WORK] 걸작에서 오는 [ICON_CULTURE] 문화가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가하고 [ICON_PEACE] 신앙으로 고고학자를 구매할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_UNITY_OF_PROPHETS';

-- Sacred Sites
UPDATE Language_ko_KR
SET Text = '호텔 및 [ICON_PEACE] 신앙으로 구매하는 모든 건물의 [ICON_TOURISM] 관광이 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 증가합니다. 세계 불가사의 및 자연 경관의 [ICON_TOURISM] 관광이 [COLOR_POSITIVE_TEXT]4[ENDCOLOR] 증가합니다. 왕실 컬렉션의 [ICON_CULTURE] 문화 및 [ICON_TOURISM] 관광이 [COLOR_POSITIVE_TEXT]10[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_BELIEF_SACRED_SITES';

-- To the Glory of God
UPDATE Language_ko_KR
SET Text = '산업 시대부터 [ICON_PEACE]신앙으로 [ICON_GREAT_PEOPLE]위인을 구매할 수 있습니다. [ICON_GREAT_PEOPLE]위인을 소모할 때 당신 문명의 종교를 따르는 도시 1개마다 [COLOR:110:110:110:255](한도: 20도시)[ENDCOLOR] [ICON_CULTURE]문화, [ICON_RESEARCH]과학, [ICON_GOLD]골드를 [COLOR_POSITIVE_TEXT]3[ENDCOLOR] 얻습니다.'
WHERE Tag = 'TXT_KEY_BELIEF_TO_GLORY_OF_GOD';
