INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
SELECT 'MORE_SPECIALIST_ATLAS', 256, 'SpecialistAtlas256.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 128, 'SpecialistAtlas128.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 80, 'SpecialistAtlas80.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 64, 'SpecialistAtlas64.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 45, 'SpecialistAtlas45.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 32, 'SpecialistAtlas32.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 256, 'c&r_PI_256.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 64, 'c&r_PI_064.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 45, 'c&r_PI_045.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 32, 'c&r_PI_032.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 16, 'c&r_PI_016.dds', 2, 1;

INSERT INTO Language_ko_KR (Tag, Text)
SELECT 'TXT_KEY_BUILDING_ENGINEERS_GUILD', '노동 조합' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCHANTS_GUILD', '신용 조합' UNION ALL
SELECT 'TXT_KEY_BUILDING_SCIENTISTS_GUILD', '학술 기관' UNION ALL
SELECT 'TXT_KEY_BUILDING_DIPLOMATS_GUILD', '외교공관' UNION ALL
SELECT 'TXT_KEY_BUILDING_PUBLICAN_OFFICE', '세리 세무서' UNION ALL
SELECT 'TXT_KEY_BUILDING_ENGINEERS_GUILD_HELP', '[ICON_GREAT_ENGINEER] 위대한 기술자에게 [ICON_GREAT_PEOPLE] 위인 점수를 5 제공합니다. 모든 작업장의 [ICON_GOLD] 골드 생산이 +1 늘어납니다.[NEWLINE][NEWLINE][ICON_CITY_STATE] 모든 도시에서 문명 크기 수정치가 3% 감소합니다.[NEWLINE][NEWLINE]당신의 문명에는 이러한 건물이 최대 3개까지 있을 수 있습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCHANTS_GUILD_HELP', '[ICON_GREAT_MERCHANT] 위대한 상인에게 [ICON_GREAT_PEOPLE] 위인 점수를 5 제공합니다. 모든 은행의 [ICON_GOLD] 골드 생산이 +1 늘어납니다.[NEWLINE][NEWLINE]모든 도시의 [ICON_GOLD] 기본 건물 유지비가 -4% 감소합니다.[NEWLINE][NEWLINE]당신의 문명에는 이러한 건물이 최대 3개까지 있을 수 있습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_SCIENTISTS_GUILD_HELP', '[ICON_GREAT_SCIENTIST] 위대한 과학자에게 [ICON_GREAT_PEOPLE] 위인 점수를 5 제공합니다. 모든 연구소의 [ICON_GOLD] 골드 생산이 +1 늘어납니다.[NEWLINE][NEWLINE][ICON_GREAT_SCIENTIST] 위대한 과학자를 새로운 기술을 발견하는 데 사용할 경우 [ICON_RESEARCH] 과학을 +5% 더 많이 제공합니다.[NEWLINE][NEWLINE]당신의 문명에는 이러한 건물이 최대 3개까지 있을 수 있습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_DIPLOMATS_GUILD_HELP', '[ICON_GREAT_DIPLOMAT] 위대한 외교관에게 [ICON_GREAT_PEOPLE] 위인 점수를 5 제공합니다. 모든 통신사의 [ICON_GOLD] 골드 생산이 +1 늘어납니다.[NEWLINE][NEWLINE]세계 의회에서 [COLOR_POSITIVE_TEXT]추가[ENDCOLOR] [ICON_DIPLOMAT] 대표 1명을 받습니다.[NEWLINE][NEWLINE]당신의 문명에는 이러한 건물이 최대 3개까지 있을 수 있습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_HELP', '모든 도시에서 [ICON_GOLD] 기본 건물 유지비가 -10% 감소합니다.[NEWLINE][NEWLINE]요구하는 [ICON_PRODUCTION] 생산력과 [ICON_CITIZEN] 인구의 수는 소유한 도시의 수에 따라 늘어납니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_PEDIA', '세리들은 고대 로마의 공공 계약자였습니다. 그들은 군대와 군인들에게 물자를 공급하고, 세금을 관리하고, 공공 사업을 감독했습니다. 이들 세리들의 유산은 현대 정부가 운영되는 방식에 영감을 주었는데, 이들은 광대한 영토와 인구를 관리하는 데 따르는 어려움을 처음으로 목격한 사람들이었기 때문입니다.';

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description, MaxPlayerInstances)
SELECT 'BUILDINGCLASS_ENGINEERS_GUILD', 'BUILDING_ENGINEERS_GUILD', 'TXT_KEY_BUILDING_ENGINEERS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_MERCHANTS_GUILD', 'BUILDING_MERCHANTS_GUILD', 'TXT_KEY_BUILDING_MERCHANTS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_SCIENTISTS_GUILD', 'BUILDING_SCIENTISTS_GUILD', 'TXT_KEY_BUILDING_SCIENTISTS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_DIPLOMATS_GUILD', 'BUILDING_DIPLOMATS_GUILD', 'TXT_KEY_BUILDING_DIPLOMATS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_PUBLICAN_OFFICE', 'BUILDING_PUBLICAN_OFFICE', 'TXT_KEY_BUILDING_PUBLICAN_OFFICE', 1;

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_ENGINEERS_GUILD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_MERCHANTS_GUILD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_SCIENTISTS_GUILD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_DIPLOMATS_GUILD';

INSERT INTO Buildings (Type, BuildingClass, Cost, Description, Help, GoldMaintenance, HurryCostModifier, MinAreaSize, ArtDefineTag, PrereqTech, SpecialistType, SpecialistCount, GreatPeopleRateChange, IconAtlas, PortraitIndex, NumCityCostMod)
SELECT 'BUILDING_ENGINEERS_GUILD', 'BUILDINGCLASS_ENGINEERS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'TXT_KEY_BUILDING_ENGINEERS_GUILD', 'TXT_KEY_BUILDING_ENGINEERS_GUILD_HELP', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'ART_DEF_BUILDING_FORGE', 'TECH_STEAM_POWER', 'SPECIALIST_ENGINEER', 0, 5, 'MORE_SPECIALIST_ATLAS', 0, 0 UNION ALL
SELECT 'BUILDING_MERCHANTS_GUILD', 'BUILDINGCLASS_MERCHANTS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_WIRE_SERVICE'), 'TXT_KEY_BUILDING_MERCHANTS_GUILD', 'TXT_KEY_BUILDING_MERCHANTS_GUILD_HELP', 0, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'ART_DEF_BUILDING_BANK', 'TECH_REPLACEABLE_PARTS', 'SPECIALIST_MERCHANT', 0, 5, 'MORE_SPECIALIST_ATLAS', 1, 0 UNION ALL
SELECT 'BUILDING_SCIENTISTS_GUILD', 'BUILDINGCLASS_SCIENTISTS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_STADIUM'), 'TXT_KEY_BUILDING_SCIENTISTS_GUILD', 'TXT_KEY_BUILDING_SCIENTISTS_GUILD_HELP', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_STADIUM'), (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'ART_DEF_BUILDING_UNIVERSITY', 'TECH_ATOMIC_THEORY', 'SPECIALIST_SCIENTIST', 0, 5, 'MORE_SPECIALIST_ATLAS', 2, 0 UNION ALL
SELECT 'BUILDING_DIPLOMATS_GUILD', 'BUILDINGCLASS_DIPLOMATS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_INTERPRETIVE_CENTER'), 'TXT_KEY_BUILDING_DIPLOMATS_GUILD', 'TXT_KEY_BUILDING_DIPLOMATS_GUILD_HELP', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_INTERPRETIVE_CENTER'), (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'COURTHOUSE', 'TECH_TELECOM', 'SPECIALIST_CIVIL_SERVANT', 0, 5, 'MORE_SPECIALIST_ATLAS', 3, 0;


INSERT INTO Buildings (Type, BuildingClass, Cost, Description, Help, Civilopedia, GoldMaintenance, HurryCostModifier, MinAreaSize, ArtDefineTag, PrereqTech, IconAtlas, PortraitIndex, NumCityCostMod)
SELECT 'BUILDING_PUBLICAN_OFFICE', 'BUILDINGCLASS_PUBLICAN_OFFICE', 125, 'TXT_KEY_BUILDING_PUBLICAN_OFFICE', 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_HELP', 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_PEDIA', 0, -20, -1, 'ART_DEF_BUILDING_BANK', 'TECH_CURRENCY', 'NEW_BLDG_ATLAS_DLC', 1, (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_NATIONAL_COLLEGE');

UPDATE Buildings
SET EmpireSizeModifierReductionGlobal = -3, NeverCapture = 1
WHERE Type = 'BUILDING_ENGINEERS_GUILD';

UPDATE Buildings
SET GlobalBuildingGoldMaintenanceMod = -4, NeverCapture = 1
WHERE Type = 'BUILDING_MERCHANTS_GUILD';

UPDATE Buildings
SET GreatScientistBeakerModifier = 5, NeverCapture = 1
WHERE Type = 'BUILDING_SCIENTISTS_GUILD';

UPDATE Buildings
SET SingleLeagueVotes = 1
WHERE Type = 'BUILDING_DIPLOMATS_GUILD';

UPDATE Buildings
SET GlobalBuildingGoldMaintenanceMod = -10, Civilopedia = 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_PEDIA', NeverCapture = 1, NukeImmune = 1, NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_NATIONAL_COLLEGE'), SpecialistType = 'SPECIALIST_CIVIL_SERVANT', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_PUBLICAN_OFFICE';

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_ENGINEERS_GUILD', 'FLAVOR_PRODUCTION', 60 UNION ALL
SELECT 'BUILDING_MERCHANTS_GUILD', 'FLAVOR_GOLD', 60 UNION ALL
SELECT 'BUILDING_SCIENTISTS_GUILD', 'FLAVOR_SCIENCE', 60 UNION ALL
SELECT 'BUILDING_DIPLOMATS_GUILD', 'FLAVOR_DIPLOMACY', 60 UNION ALL
SELECT 'BUILDING_PUBLICAN_OFFICE', 'FLAVOR_GOLD', 45;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PUBLICAN_OFFICE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'BUILDING_PUBLICAN_OFFICE', 'YIELD_GOLD', 1;

INSERT INTO Building_BuildingClassYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange)
SELECT 'BUILDING_ENGINEERS_GUILD', 'BUILDINGCLASS_WORKSHOP', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_MERCHANTS_GUILD', 'BUILDINGCLASS_BANK', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_SCIENTISTS_GUILD', 'BUILDINGCLASS_LABORATORY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_DIPLOMATS_GUILD', 'BUILDINGCLASS_WIRE_SERVICE', 'YIELD_GOLD', 1;

INSERT INTO Civilization_BuildingClassOverrides  (CivilizationType, BuildingClassType, BuildingType)
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_ENGINEERS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_MERCHANTS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_SCIENTISTS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_DIPLOMATS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_PUBLICAN_OFFICE', NULL;

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT 'BUILDING_PUBLICAN_OFFICE', 'BUILDINGCLASS_CARAVANSARY';

INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_PUBLICAN_OFFICE', 1;

INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_PUBLICAN_OFFICE', 25;