INSERT INTO Improvement_AdjacentImprovementYieldChanges
	(ImprovementType, OtherImprovementType, YieldType, Yield)
VALUES
	('IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 	'IMPROVEMENT_MANUFACTORY', 			'YIELD_PRODUCTION', 3),
	('IMPROVEMENT_FW_HERC', 				'IMPROVEMENT_ACADEMY', 				'YIELD_SCIENCE', 	3),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_CUSTOMS_HOUSE', 		'YIELD_GOLD',   	1),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX','YIELD_GOLD',       1),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_FW_HERC', 	            'YIELD_GOLD',       1),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_FW_WATER_GENOCENTRE', 	'YIELD_GOLD',   	1),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_FW_GENOCENTRE', 		'YIELD_GOLD',   	1),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_FW_WATER_ARCOLOGY',    'YIELD_GOLD',       1),
	('IMPROVEMENT_FW_GENERATOR', 			'IMPROVEMENT_FW_ARCOLOGY', 		    'YIELD_GOLD',       1),

	('IMPROVEMENT_FW_BIOWELL', 				'IMPROVEMENT_FARM', 				'YIELD_FOOD', 	    1),
	('IMPROVEMENT_FW_BIOWELL', 				'IMPROVEMENT_TERRACE_FARM', 		'YIELD_FOOD',   	1),
	('IMPROVEMENT_FW_WATER_HYDROPONICS_DOME','IMPROVEMENT_FISHING_BOATS', 	    'YIELD_SCIENCE', 	1),
	('IMPROVEMENT_FW_HYDROPONICS_DOME', 	'IMPROVEMENT_FARM', 				'YIELD_SCIENCE', 	1),
	('IMPROVEMENT_FW_HYDROPONICS_DOME', 	'IMPROVEMENT_TERRACE_FARM', 		'YIELD_SCIENCE', 	1),
	('IMPROVEMENT_FW_PRESERVE', 			'IMPROVEMENT_FW_BIOWELL', 	    	'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_PRESERVE', 			'IMPROVEMENT_CAMP', 	        	'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_PRESERVE', 			'IMPROVEMENT_POLDER', 	    	    'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_PRESERVE', 			'IMPROVEMENT_FW_PRESERVE', 	    	'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_PRESERVE', 			'IMPROVEMENT_BRAZILWOOD_CAMP', 	    'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_HOLY_SITE', 	        'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_LANDMARK', 	        'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_TRADING_POST', 	    'YIELD_CULTURE', 	1),

	('IMPROVEMENT_FW_WATER_GENOCENTRE', 	'IMPROVEMENT_FISHING_BOATS', 		'YIELD_FOOD', 		2),
	('IMPROVEMENT_FW_GENOCENTRE', 			'IMPROVEMENT_CAMP', 	        	'YIELD_GOLD', 		2),
	('IMPROVEMENT_FW_GENOCENTRE', 			'IMPROVEMENT_PASTURE', 				'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_FW_GENOCENTRE', 			'IMPROVEMENT_PLANTATION', 			'YIELD_GOLD',       2),
	('IMPROVEMENT_FW_GENOCENTRE', 			'IMPROVEMENT_ROME_LATIFUNDIUM',     'YIELD_GOLD',       2),


	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_MOAI', 				'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_KUNA', 				'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_KASBAH', 				'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_ENCAMPMENT_SHOSHONE', 	'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_FEITORIA', 	        'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_SPAIN_HACIENDA', 	    'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_SIHEYUAN', 		    'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_IMPROVEMENT_OTTOMAN_TERSANE', 'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_ETHIOPIA_MONOLITHIC_CHURCH',  'YIELD_TOURISM',    1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_INDONESIA_KAMPONG', 	'YIELD_TOURISM', 	1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_MONGOLIA_ORDO', 		'YIELD_TOURISM', 	1),
	('IMPROVEMENT_FW_COMM_ARRAY', 			'IMPROVEMENT_ZULU_KRAAL', 			'YIELD_TOURISM', 	1);

-- Policies
INSERT INTO Policy_ImprovementYieldChanges
	(PolicyType, ImprovementType, YieldType, Yield)
VALUES
-- Freedom
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_BIOWELL', 					'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_HYDROPONICS_DOME', 			'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME', 	'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_GENOCENTRE', 				'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_WATER_GENOCENTRE', 			'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_ARCOLOGY', 					'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 			'IMPROVEMENT_FW_WATER_ARCOLOGY', 			'YIELD_FOOD', 		4),
	('POLICY_CIVIL_SOCIETY', 		    'IMPROVEMENT_FW_PRESERVE', 		            'YIELD_FOOD',       4),
	-- ('POLICY_CIVIL_SOCIETY', 		    'IMPROVEMENT_FW_COMM_ARRAY', 		        'YIELD_FOOD',       4),
	('POLICY_CIVIL_SOCIETY', 		    'IMPROVEMENT_FW_FUNGAL_GROWTH', 		    'YIELD_FOOD',       4),
	('POLICY_NEW_DEAL', 			    'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'YIELD_TOURISM',    2),
	('POLICY_NEW_DEAL', 			    'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'YIELD_PRODUCTION', 2),
	('POLICY_NEW_DEAL', 			    'IMPROVEMENT_FW_HERC', 	                 	'YIELD_TOURISM',    2),
	('POLICY_NEW_DEAL', 			    'IMPROVEMENT_FW_HERC', 			            'YIELD_SCIENCE', 	2),
--Order
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_GENERATOR', 				'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 		    'IMPROVEMENT_FW_PRESERVE', 		            'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 		    'IMPROVEMENT_FW_COMM_ARRAY', 		        'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_HERC', 		                'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_FUNGAL_GROWTH', 			'YIELD_PRODUCTION', 3),
	-- ('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_CORE', 						'YIELD_PRODUCTION', 3),
	-- ('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_WATER_CORE', 				'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_GENOCENTRE', 				'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_WATER_GENOCENTRE', 			'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_ARCOLOGY', 					'YIELD_PRODUCTION', 3),
	('POLICY_FIVE_YEAR_PLAN', 			'IMPROVEMENT_FW_WATER_ARCOLOGY', 			'YIELD_PRODUCTION', 3),
-- Autocracy
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_FUNGAL_GROWTH', 			'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_HERC', 		                'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_CORE', 						'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_WATER_CORE', 				'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_VAULT', 					'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_GENOCENTRE', 				'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_WATER_GENOCENTRE', 			'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_ARCOLOGY', 					'YIELD_SCIENCE', 	3),
	('POLICY_MOBILIZATION', 			'IMPROVEMENT_FW_WATER_ARCOLOGY', 			'YIELD_SCIENCE', 	3),
--Exploration,
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_CORE', 					    'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_CORE', 					    'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_WATER_CORE', 			    'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_WATER_CORE', 			    'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_VAULT', 			    	'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_VAULT', 			    	'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_GENOCENTRE', 			    'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_GENOCENTRE', 			    'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_WATER_GENOCENTRE', 		    'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_WATER_GENOCENTRE', 			'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_ARCOLOGY', 		            'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_ARCOLOGY', 		         	'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_WATER_ARCOLOGY', 		    'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_WATER_ARCOLOGY', 		    'YIELD_CULTURE', 	1),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_FUNGAL_GROWTH', 			'YIELD_SCIENCE', 	2),
	('POLICY_NAVAL_TRADITION', 			'IMPROVEMENT_FW_FUNGAL_GROWTH', 			'YIELD_CULTURE', 	1),
	('POLICY_MERCHANT_NAVY', 			'IMPROVEMENT_FW_BIOWELL', 					'YIELD_FOOD', 		2),
	('POLICY_MERCHANT_NAVY', 			'IMPROVEMENT_FW_BIOWELL', 					'YIELD_PRODUCTION', 1),
	('POLICY_MERCHANT_NAVY', 		    'IMPROVEMENT_FW_HYDROPONICS_DOME', 		    'YIELD_FOOD', 	    2),
	('POLICY_MERCHANT_NAVY', 		    'IMPROVEMENT_FW_HYDROPONICS_DOME', 			'YIELD_PRODUCTION', 1),
	('POLICY_MERCHANT_NAVY', 		    'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME',    'YIELD_FOOD',       2),
	('POLICY_MERCHANT_NAVY', 			'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME',    'YIELD_PRODUCTION', 1),
--Rationalism 
	('POLICY_SOVEREIGNTY', 	            'IMPROVEMENT_FW_PRESERVE', 					'YIELD_PRODUCTION', 2),
	('POLICY_SOVEREIGNTY', 	            'IMPROVEMENT_FW_PRESERVE', 					'YIELD_GOLD',       2),
	('POLICY_SOVEREIGNTY', 		        'IMPROVEMENT_FW_COMM_ARRAY', 				'YIELD_PRODUCTION', 2),
	('POLICY_SOVEREIGNTY', 	            'IMPROVEMENT_FW_COMM_ARRAY', 				'YIELD_GOLD', 		2),
--Commerce
	('POLICY_ENTREPRENEURSHIP',         'IMPROVEMENT_FW_HERC', 						'YIELD_PRODUCTION', 2),
	('POLICY_ENTREPRENEURSHIP',         'IMPROVEMENT_FW_HERC', 						'YIELD_GOLD', 		1),
	('POLICY_ENTREPRENEURSHIP', 		'IMPROVEMENT_FW_GENERATOR', 				'YIELD_PRODUCTION', 2),
	('POLICY_ENTREPRENEURSHIP', 		'IMPROVEMENT_FW_GENERATOR', 				'YIELD_GOLD', 		1),
	('POLICY_ENTREPRENEURSHIP', 		'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'YIELD_PRODUCTION', 2),
	('POLICY_ENTREPRENEURSHIP', 		'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'YIELD_GOLD', 		1);

INSERT INTO Improvement_TechYieldChanges
	(ImprovementType, TechType, YieldType, Yield)
VALUES
	('IMPROVEMENT_POLDER', 						'TECH_FW_ECOTHEORY', 			'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_PRESERVE', 				'TECH_FW_ECOTHEORY', 			'YIELD_CULTURE', 	1),
	('IMPROVEMENT_LUMBERMILL', 					'TECH_FW_ECOTHEORY', 			'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_LUMBERMILL', 		        	'TECH_FW_ECOTHEORY', 			'YIELD_GOLD', 		1),
	('IMPROVEMENT_LANDMARK', 					'TECH_GLOBALIZATION', 	    	'YIELD_GOLD',       1),

	('IMPROVEMENT_TRADING_POST', 				'TECH_GRID_COMPUTING',		    'YIELD_PRODUCTION', 1),
	
	('IMPROVEMENT_FW_COMM_ARRAY', 				'TECH_MEMETICS', 		    'YIELD_CULTURE', 	1),

	('IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 		'TECH_NANOTECHNOLOGY', 		    'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_FW_HERC', 				    'TECH_PARTICLE_PHYSICS',		'YIELD_SCIENCE', 	1),
	('IMPROVEMENT_WELL', 				        'TECH_QUANTUM_COMPUTERS',		'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_WELL', 				        'TECH_QUANTUM_COMPUTERS',		'YIELD_GOLD', 		1),
	('IMPROVEMENT_OFFSHORE_PLATFORM', 			'TECH_QUANTUM_COMPUTERS',		'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_OFFSHORE_PLATFORM', 			'TECH_QUANTUM_COMPUTERS',		'YIELD_GOLD', 		1),

	('IMPROVEMENT_MANUFACTORY', 			    'TECH_MECHATRONICS',            'YIELD_SCIENCE',    3),

	('IMPROVEMENT_PLANTATION', 					'TECH_TRANSGENICS', 	    	'YIELD_GOLD', 		1),
	('IMPROVEMENT_PASTURE', 					'TECH_TRANSGENICS', 	    	'YIELD_GOLD', 		1),
	('IMPROVEMENT_FISHING_BOATS', 				'TECH_TRANSGENICS', 	        'YIELD_GOLD', 		1),
	('IMPROVEMENT_CAMP', 						'TECH_TRANSGENICS',             'YIELD_GOLD', 		1),

	('IMPROVEMENT_FISHING_BOATS', 				'TECH_AUTONOMOUS_SYSTEMS', 	    'YIELD_FOOD', 		1),
	('IMPROVEMENT_TERRACE_FARM', 				'TECH_AUTONOMOUS_SYSTEMS', 	    'YIELD_FOOD', 		1),
	('IMPROVEMENT_POLDER', 						'TECH_AUTONOMOUS_SYSTEMS', 		'YIELD_FOOD',   	1),
	('IMPROVEMENT_ROME_LATIFUNDIUM', 			'TECH_AUTONOMOUS_SYSTEMS', 		'YIELD_FOOD',   	1),
	('IMPROVEMENT_PLANTATION', 					'TECH_AUTONOMOUS_SYSTEMS', 		'YIELD_FOOD', 		1),
	('IMPROVEMENT_PASTURE', 					'TECH_AUTONOMOUS_SYSTEMS',   	'YIELD_FOOD',   	1),

	('IMPROVEMENT_QUARRY', 						'TECH_ARCOLOGIES', 		        'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_MINE', 						'TECH_ARCOLOGIES', 		        'YIELD_PRODUCTION', 1),

	('IMPROVEMENT_FW_BIOWELL', 					'TECH_GENGINEERING', 	    	'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_FUNGAL_GROWTH', 			'TECH_GENGINEERING', 	        'YIELD_GOLD', 	    3),

	('IMPROVEMENT_FW_GENERATOR', 				'TECH_AI', 		                'YIELD_GOLD', 	    1),
	('IMPROVEMENT_CUSTOMS_HOUSE', 			    'TECH_AI',                      'YIELD_PRODUCTION', 3),

	('IMPROVEMENT_FW_WATER_HYDROPONICS_DOME', 	'TECH_ADAMANTIUM', 	        	'YIELD_SCIENCE', 	1),
	('IMPROVEMENT_FW_HYDROPONICS_DOME', 		'TECH_ADAMANTIUM', 	        	'YIELD_SCIENCE', 	1),
	('IMPROVEMENT_ACADEMY', 			        'TECH_ADAMANTIUM', 			    'YIELD_FOOD',   	3),

	('IMPROVEMENT_EMBASSY', 			        'TECH_NUCLEAR_FUSION', 		    'YIELD_CULTURE',   	3),

	('IMPROVEMENT_FW_WATER_CORE', 				'TECH_DIGITAL_SOCIETY', 		'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_CORE', 			    	'TECH_DIGITAL_SOCIETY', 		'YIELD_CULTURE', 	1),

	('IMPROVEMENT_FW_GENOCENTRE', 				'TECH_TERRAFORMING', 			'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_WATER_GENOCENTRE', 		'TECH_TERRAFORMING', 			'YIELD_CULTURE', 	1),

	('IMPROVEMENT_FW_ARCOLOGY', 				'TECH_HYPERSTRUCTURES', 		'YIELD_CULTURE', 	1),
	('IMPROVEMENT_FW_WATER_ARCOLOGY', 			'TECH_HYPERSTRUCTURES', 		'YIELD_CULTURE', 	1);

-- INSERT INTO Improvement_YieldAdjacentSameType
-- 	(ImprovementType, YieldType, Yield)
-- VALUES
-- 	('IMPROVEMENT_FW_PRESERVE', 'YIELD_CULTURE', 1);


INSERT INTO Building_ImprovementYieldChanges
	(BuildingType, ImprovementType, YieldType, Yield)
VALUES
	('BUILDING_STOCKYARD', 'IMPROVEMENT_FW_BIOWELL', 				'YIELD_PRODUCTION', 2),
	('BUILDING_STOCKYARD', 'IMPROVEMENT_FW_BIOWELL', 				'YIELD_GOLD', 		2),
	('BUILDING_STOCKYARD', 'IMPROVEMENT_FW_HYDROPONICS_DOME', 		'YIELD_PRODUCTION', 2),
	('BUILDING_STOCKYARD', 'IMPROVEMENT_FW_HYDROPONICS_DOME', 		'YIELD_GOLD', 		2),
	('BUILDING_STOCKYARD', 'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME', 'YIELD_PRODUCTION', 2),
	('BUILDING_STOCKYARD', 'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME', 'YIELD_GOLD', 		2);

INSERT INTO Building_ImprovementYieldChanges
	(BuildingType, ImprovementType, YieldType, Yield)
VALUES
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_BIOWELL', 				'YIELD_PRODUCTION', 2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_BIOWELL', 				'YIELD_FOOD', 		2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_BIOWELL', 				'YIELD_GOLD', 		2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_HYDROPONICS_DOME', 		'YIELD_PRODUCTION', 2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_HYDROPONICS_DOME', 		'YIELD_FOOD',       2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_HYDROPONICS_DOME', 		'YIELD_GOLD', 		2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME',  'YIELD_PRODUCTION', 2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME',  'YIELD_FOOD',       2),
	('BUILDING_DENMARK_ANDELSBEVAEGELSE', 'IMPROVEMENT_FW_WATER_HYDROPONICS_DOME',  'YIELD_GOLD', 		2);


INSERT INTO Route_TechMovementChanges
	(RouteType, TechType, MovementChange)
VALUES
	('ROUTE_RAILROAD', 'TECH_SUPERCONDUCTIVITY', -10);

UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_ACADEMY';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_MANUFACTORY';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_CUSTOMS_HOUSE';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_HOLY_SITE';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_CHATEAU';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_FEITORIA';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_OTTOMAN_TERSANE';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_CELTS_OPPIDUM';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_KASBAH';
UPDATE Improvements
SET MakesPassable = 1
WHERE Type = 'IMPROVEMENT_EMBASSY';
