INSERT INTO Policies (Type, Description, BuildingGoldMaintenanceMod)
SELECT 'POLICY_CIVIC_DEPOTISM', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1', 10 UNION ALL
SELECT 'POLICY_CIVIC_HEREDITARY_RULE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2', 10 UNION ALL
SELECT 'POLICY_CIVIC_CONFEDERATION', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7', 10 UNION ALL
SELECT 'POLICY_CIVIC_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 15 UNION ALL
SELECT 'POLICY_CIVIC_REPRESENTATION', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4', 15 UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5', 25 UNION ALL
SELECT 'POLICY_CIVIC_UNIVERSAL_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 25 UNION ALL

SELECT 'POLICY_CIVIC_BARBARISM', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1', 9 UNION ALL
SELECT 'POLICY_CIVIC_CIVIL_LAW', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2', 9 UNION ALL
SELECT 'POLICY_CIVIC_VASSALAGE', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3', 24 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4', 24 UNION ALL
SELECT 'POLICY_CIVIC_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 0 UNION ALL
SELECT 'POLICY_CIVIC_FREE_SPEECH', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6', 14 UNION ALL
SELECT 'POLICY_CIVIC_CONSTIUTIONALISM', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7', 24 UNION ALL

SELECT 'POLICY_CIVIC_TRIBALISM', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1', 8 UNION ALL
SELECT 'POLICY_CIVIC_SLAVERY', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2', 13 UNION ALL
SELECT 'POLICY_CIVIC_SERFDOM', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3', 8 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4', 13 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5', 23 UNION ALL
SELECT 'POLICY_CIVIC_EMANCIPATION', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6', 8 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7', 23 UNION ALL

SELECT 'POLICY_CIVIC_DECENTRALIZATION', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1', 7 UNION ALL
SELECT 'POLICY_CIVIC_INGENIUSCRAFT', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7', 7 UNION ALL
SELECT 'POLICY_CIVIC_MERCANTILISM', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2', 12 UNION ALL
SELECT 'POLICY_CIVIC_FREE_MARKET', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3', 12 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4', 12 UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5', 22 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6', 22 UNION ALL

SELECT 'POLICY_CIVIC_PAGANISM', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1', 6 UNION ALL
SELECT 'POLICY_CIVIC_ANCESTOR_WORSHIP', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7', 6 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2', 21 UNION ALL
SELECT 'POLICY_CIVIC_THEOCRACY', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3', 11 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4', 0 UNION ALL
SELECT 'POLICY_CIVIC_STATE_ATHEISM', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5', 11 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6', 11;

UPDATE Policies
SET ScienceMedianModifierGlobal = -10
WHERE Type = 'POLICY_CIVIC_DEPOTISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET WonderProductionModifier = 5, HappinessPerGarrisonedUnit = 1
WHERE Type = 'POLICY_CIVIC_HEREDITARY_RULE';

UPDATE Policies
SET BasicNeedsMedianModifierGlobal = 10, ScienceMedianModifierGlobal = 10, CultureMedianModifierGlobal = 10, GoldMedianModifierGlobal = 10, ReligiousUnrestModifierGlobal = 10, BasicNeedsMedianModifierCapital = -10, GoldMedianModifierCapital = -10, ScienceMedianModifierCapital = -10, CultureMedianModifierCapital = -10, ReligiousUnrestModifierCapital = -10
WHERE Type = 'POLICY_CIVIC_CONFEDERATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET HappinessPerXPopulationGlobal = 15
WHERE Type = 'POLICY_CIVIC_REPRESENTATION';

UPDATE Policies
SET MinorFriendshipMinimum = 15, MilitaryUnitGiftExtraInfluence = 5 --MinorFriendshipDecayMod = -25
WHERE Type = 'POLICY_CIVIC_PATRONAGE';

UPDATE Policies
SET WarWearinessModifier = 25 --, StealGWSlowerModifier = -25
WHERE Type = 'POLICY_CIVIC_POLICE_STATE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET GreatGeneralExtraBonus = 10 --, StealTechSlowerModifier = -25
WHERE Type = 'POLICY_CIVIC_POLICE_STATE';

UPDATE Policies
SET UnitUpgradeCostMod = -10
WHERE Type = 'POLICY_CIVIC_UNIVERSAL_SUFFRAGE';

UPDATE Policies
SET BasicNeedsMedianModifierGlobal = -10
WHERE Type = 'POLICY_CIVIC_BARBARISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET NoUnhappfromXSpecialists = 1
WHERE Type = 'POLICY_CIVIC_CIVIL_LAW' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET CulturePerWonder = 1
WHERE Type = 'POLICY_CIVIC_CIVIL_LAW';

UPDATE Policies
SET FreeExperience = 15, UnitGoldMaintenanceMod = -35, CSYieldBonusModifier = 20, VassalYieldBonusModifier = 10, PuppetYieldPenaltyMod = 10
WHERE Type = 'POLICY_CIVIC_VASSALAGE';

UPDATE Policies
SET NoUnhappfromXSpecialistsCapital = 7
WHERE Type = 'POLICY_CIVIC_BUREAUCRACY';

/*UPDATE Policies
SET CatchSpiesModifier = 33, StealTechFasterModifier = 33, RiggingElectionModifier = 17
WHERE Type = 'POLICY_CIVIC_NATIONHOOD';*/

UPDATE Policies
SET ExtraSupplyPerPopulation = 10 --StealGWFasterModifier = 33
WHERE Type = 'POLICY_CIVIC_NATIONHOOD';

UPDATE Policies
SET GoldenAgeDurationMod = 25
WHERE Type = 'POLICY_CIVIC_CONSTIUTIONALISM';

UPDATE Policies
SET CultureMedianModifierGlobal = -10
WHERE Type = 'POLICY_CIVIC_TRIBALISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET CityAutomatonWorkersChange = 1, CityGrowthMod = -10
WHERE Type = 'POLICY_CIVIC_SLAVERY';

UPDATE Policies
SET WorkerSpeedModifier = 25
WHERE Type = 'POLICY_CIVIC_SERFDOM';

--UPDATE Policies
--SET BasicNeedsMedianModifierGlobal = 10, ScienceMedianModifierGlobal = 10, CultureMedianModifierGlobal = 10, GoldMedianModifierGlobal = 10, ReligiousUnrestModifierGlobal = 10
--WHERE Type = 'POLICY_CIVIC_CASTE_SYSTEM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET CityGrowthMod = 10
WHERE Type = 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE';

UPDATE Policies
SET LessHappyTourismModifier = 25, HappinessToCulture = 25
WHERE Type = 'POLICY_CIVIC_EMANCIPATION';

UPDATE Policies
SET GoldMedianModifierGlobal = -10
WHERE Type = 'POLICY_CIVIC_DECENTRALIZATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE Policies
SET LandTradeRouteGoldChange = 200, SeaTradeRouteGoldChange = 200, ProtectedMinorPerTurnInfluence = 75 --,RouteGoldMaintenanceMod = -20
WHERE Type = 'POLICY_CIVIC_INGENIUSCRAFT';

UPDATE Policies
SET InternalTradeRouteYieldModifier = 33 --, CityConnectionTradeRouteGoldModifier = 20
WHERE Type = 'POLICY_CIVIC_MERCANTILISM';

UPDATE Policies
SET FreeTradeRoute = 1, TradeRouteTourismModifier = 12
WHERE Type = 'POLICY_CIVIC_FREE_MARKET';

UPDATE Policies
SET MonopolyModFlat = 2, MonopolyModPercent = 5
WHERE Type = 'POLICY_CIVIC_CORPORATISM';

UPDATE Policies
SET ReligiousUnrestModifierGlobal = -10
WHERE Type = 'POLICY_CIVIC_PAGANISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1);

UPDATE Policies
SET UnitGoldMaintenanceMod = 100, GreatPeopleRateModifier = 25
WHERE Type = 'POLICY_CIVIC_PACIFISM';

UPDATE Policies
SET WarWearinessModifier = -50
WHERE Type = 'POLICY_CIVIC_PACIFISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1);

/*UPDATE Policies
SET HappinessToCulture = 50
WHERE Type = 'POLICY_CIVIC_STATE_ATHEISM';*/

UPDATE Policies
SET ExtraHappinessPerCity = 1
WHERE Type = 'POLICY_CIVIC_FREE_RELIGION';

--INSERT INTO Policy_UnitCombatProductionModifiers (PolicyType, UnitCombatType, ProductionModifier)
--SELECT 'POLICY_CIVIC_PATRONAGE', 'UNITCOMBAT_DIPLOMACY', 15;

INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
--SELECT 'POLICY_CIVIC_PATRONAGE', 'IMPROVEMENT_EMBASSY', 'YIELD_GOLD', 4 UNION ALL
--SELECT 'POLICY_CIVIC_PATRONAGE', 'IMPROVEMENT_EMBASSY', 'YIELD_TOURISM', 4 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'IMPROVEMENT_FARM', 'YIELD_FOOD', 1 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'IMPROVEMENT_FORT', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'IMPROVEMENT_MINE', 'YIELD_PRODUCTION', 1 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'IMPROVEMENT_LUMBERMILL', 'YIELD_PRODUCTION', 1 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'IMPROVEMENT_TRADING_POST', 'YIELD_GOLD', 1 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'IMPROVEMENT_TRADING_POST', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'IMPROVEMENT_MINE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'IMPROVEMENT_LUMBERMILL', 'YIELD_FOOD', 1 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'IMPROVEMENT_QUARRY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'IMPROVEMENT_MANUFACTORY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'IMPROVEMENT_QUARRY', 'YIELD_PRODUCTION', -3 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'IMPROVEMENT_MANUFACTORY', 'YIELD_PRODUCTION', -3 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'IMPROVEMENT_MINE', 'YIELD_PRODUCTION', -3 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'IMPROVEMENT_LUMBERMILL', 'YIELD_PRODUCTION', -3 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'IMPROVEMENT_LANDMARK', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'IMPROVEMENT_HOLY_SITE', 'YIELD_PRODUCTION', 3 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'IMPROVEMENT_LANDMARK', 'YIELD_PRODUCTION', 3 UNION ALL
SELECT 'POLICY_CIVIC_THEOCRACY', 'IMPROVEMENT_HOLY_SITE', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_THEOCRACY', 'IMPROVEMENT_LANDMARK', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_STATE_ATHEISM', 'IMPROVEMENT_HOLY_SITE', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_STATE_ATHEISM', 'IMPROVEMENT_LANDMARK', 'YIELD_CULTURE', 2;

INSERT INTO Policy_YieldFromNonSpecialistCitizens (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_SERFDOM', 'YIELD_FOOD', 20 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'YIELD_PRODUCTION', 25 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'YIELD_GOLD', 25;

INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
SELECT 'POLICY_CIVIC_PATRONAGE', 'BUILDINGCLASS_CHANCERY', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_CHANCERY') UNION ALL
SELECT 'POLICY_CIVIC_PATRONAGE', 'BUILDINGCLASS_WIRE_SERVICE', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_WIRE_SERVICE') UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'BUILDINGCLASS_HARBOR', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_HARBOR') UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'BUILDINGCLASS_SEAPORT', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_SEAPORT') UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'BUILDINGCLASS_BARRACKS', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_BARRACKS') UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'BUILDINGCLASS_ARMORY', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_ARMORY') UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'BUILDINGCLASS_MILITARY_ACADEMY', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_MILITARY_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_POLICE_STATE', 'BUILDINGCLASS_STABLE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PALACE', 'YIELD_PRODUCTION', 3 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PALACE', 'YIELD_GOLD', 5 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PALACE', 'YIELD_SCIENCE', 6 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PALACE', 'YIELD_CULTURE', 1 UNION ALL
/*SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_CIRCUS_MAXIMUS', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_HEROIC_EPIC', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_EPIC', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_COLLEGE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_COLLEGE', 'YIELD_SCIENCE', 5 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PUBLICAN_OFFICE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PUBLICAN_OFFICE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_TREASURY', 'YIELD_GOLD', 4 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_GRAND_TEMPLE', 'YIELD_FAITH', 6 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_IRONWORKS', 'YIELD_PRODUCTION', 10 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_OXFORD_UNIVERSITY', 'YIELD_CULTURE', 3 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_OXFORD_UNIVERSITY', 'YIELD_SCIENCE', 3 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_COURT_SCRIBE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PRINTING_PRESS', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FOREIGN_OFFICE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_EHRENHALLE', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_CENTRAL_STATION', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_CENTRAL_BANK', 'YIELD_GOLD', 8 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_CENTRAL_BANK', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_ELECTRIC_CO', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_ELECTRIC_POWER') UNION ALL*/
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_WRITERS_GUILD', 'YIELD_CULTURE', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_ARTISTS_GUILD', 'YIELD_GOLDEN_AGE_POINTS', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_MUSICIANS_GUILD', 'YIELD_TOURISM', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_ENGINEERS_GUILD', 'YIELD_PRODUCTION', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_MERCHANTS_GUILD', 'YIELD_GOLD', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_SCIENTISTS_GUILD', 'YIELD_SCIENCE', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_DIPLOMATS_GUILD', 'YIELD_SCIENCE', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_DIPLOMATS_GUILD', 'YIELD_GOLD', 4 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_DIPLOMATS_GUILD', 'YIELD_CULTURE', 4 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TRADER_SIDS', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_LANDSEA_EXTRACTORS', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_HEXXON_REFINERY', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_GIORGIO_ARMEIER', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_FIRAXITE_MATERIALS', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TWOKAY_FOODS', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_CIVILIZED_JEWELERS', 'YIELD_FOOD', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TRADER_SIDS', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_LANDSEA_EXTRACTORS', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_HEXXON_REFINERY', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_GIORGIO_ARMEIER', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_FIRAXITE_MATERIALS', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TWOKAY_FOODS', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_CIVILIZED_JEWELERS', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TRADER_SIDS', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_TRADER_SIDS') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_LANDSEA_EXTRACTORS', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_LANDSEA_EXTRACTORS') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_HEXXON_REFINERY', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_HEXXON_REFINERY') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_GIORGIO_ARMEIER', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GIORGIO_ARMEIER') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_FIRAXITE_MATERIALS', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_FIRAXITE_MATERIALS') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TWOKAY_FOODS', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_TWOKAY_FOODS') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_CIVILIZED_JEWELERS', 'YIELD_GOLD', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_CIVILIZED_JEWELERS') WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_TRADER_SIDS_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_LANDSEA_EXTRACTORS_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_HEXXON_REFINERY_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_GIORGIO_ARMEIER_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_FIRAXITE_MATERIALS_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_TWOKAY_FOODS_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'BUILDINGCLASS_CIVILIZED_JEWELERS_FRANCHISE', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_TEMPLE', 'YIELD_PRODUCTION', 3 UNION ALL
SELECT 'POLICY_CIVIC_THEOCRACY', 'BUILDINGCLASS_TEMPLE', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_STATE_ATHEISM', 'BUILDINGCLASS_STATE_ATHEISM', 'YIELD_CULTURE', 3 UNION ALL
SELECT 'POLICY_CIVIC_STATE_ATHEISM', 'BUILDINGCLASS_STATE_ATHEISM', 'YIELD_TOURISM', 2;

--@N.Core assisted me!
INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
SELECT 'POLICY_CIVIC_BUREAUCRACY', bc.Type, b1.YieldType, b1.Yield
FROM Building_YieldChanges b1, BuildingClasses bc
WHERE bc.DefaultBuilding = b1.BuildingType
AND EXISTS (    SELECT * FROM Policy_BuildingClassHappiness p
                WHERE p.PolicyType = 'POLICY_LEGALISM'
                AND p.BuildingClassType = bc.Type
                AND bc.DefaultBuilding = b1.BuildingType
                AND p.Happiness = 1
                );
                
INSERT INTO Policy_BuildingClassYieldModifiers (PolicyType, BuildingClassType, YieldType, YieldMod)
SELECT 'POLICY_CIVIC_BUREAUCRACY', bc.Type, b1.YieldType, b1.Yield
FROM Building_YieldModifiers b1, BuildingClasses bc
WHERE bc.DefaultBuilding = b1.BuildingType
AND EXISTS (    SELECT * FROM Policy_BuildingClassHappiness p
                WHERE p.PolicyType = 'POLICY_LEGALISM'
                AND p.BuildingClassType = bc.Type
                AND bc.DefaultBuilding = b1.BuildingType
                AND p.Happiness = 1
                );

CREATE TRIGGER BureaucracyBonus
AFTER INSERT ON Policy_BuildingClassHappiness
WHEN EXISTS (SELECT * FROM Policy_BuildingClassHappiness WHERE NEW.PolicyType = 'POLICY_LEGALISM' AND NEW.Happiness = 1)
BEGIN
	INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
	SELECT 'POLICY_CIVIC_BUREAUCRACY', NEW.BuildingClassType, b1.YieldType, b1.Yield
	FROM Building_YieldChanges b1, BuildingClasses bc
	WHERE NEW.BuildingClassType = bc.Type AND bc.DefaultBuilding = b1.BuildingType
	AND EXISTS (    SELECT * FROM Policy_BuildingClassHappiness p
					WHERE p.PolicyType = 'POLICY_LEGALISM'
					AND p.BuildingClassType = NEW.BuildingClassType
					AND bc.DefaultBuilding = b1.BuildingType
					AND p.Happiness = 1
					);

	INSERT INTO Policy_BuildingClassYieldModifiers (PolicyType, BuildingClassType, YieldType, YieldMod)
	SELECT 'POLICY_CIVIC_BUREAUCRACY', NEW.BuildingClassType, b1.YieldType, b1.Yield
	FROM Building_YieldModifiers b1, BuildingClasses bc
	WHERE NEW.BuildingClassType = bc.Type AND bc.DefaultBuilding = b1.BuildingType
	AND EXISTS (    SELECT * FROM Policy_BuildingClassHappiness p
					WHERE p.PolicyType = 'POLICY_LEGALISM'
					AND p.BuildingClassType = NEW.BuildingClassType
					AND bc.DefaultBuilding = b1.BuildingType
					AND p.Happiness = 1
					);
END;
				
INSERT INTO Policy_HurryModifiers (PolicyType, HurryType, HurryCostModifier)
SELECT 'POLICY_CIVIC_UNIVERSAL_SUFFRAGE', 'HURRY_GOLD', -10;

INSERT INTO Policy_ReligionYieldMod (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_ANCESTOR_WORSHIP', 'YIELD_FAITH', 2 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_THEOCRACY', 'YIELD_SCIENCE', 2;

INSERT INTO Policy_BuildingClassYieldModifiers (PolicyType, BuildingClassType, YieldType, YieldMod)
SELECT 'POLICY_CIVIC_CONFEDERATION', 'BUILDINGCLASS_TAX', 'YIELD_GOLD', 10 UNION ALL
SELECT 'POLICY_CIVIC_CONFEDERATION', 'BUILDINGCLASS_PALACE', 'YIELD_GOLD', -10 UNION ALL
/*SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_CIRCUS_MAXIMUS', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_HEROIC_EPIC', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_EPIC', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_COLLEGE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_COLLEGE', 'YIELD_SCIENCE', 5 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PUBLICAN_OFFICE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PUBLICAN_OFFICE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_NATIONAL_TREASURY', 'YIELD_GOLD', 4 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_GRAND_TEMPLE', 'YIELD_FAITH', 6 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_IRONWORKS', 'YIELD_PRODUCTION', 10 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_OXFORD_UNIVERSITY', 'YIELD_CULTURE', 3 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_OXFORD_UNIVERSITY', 'YIELD_SCIENCE', 3 UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_COURT_SCRIBE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_PRINTING_PRESS', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FOREIGN_OFFICE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_EHRENHALLE', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_CENTRAL_STATION', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_CENTRAL_BANK', 'YIELD_GOLD', 8 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_CENTRAL_BANK', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_CIVIC_BUREAUCRACY', 'BUILDINGCLASS_FA_ELECTRIC_CO', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_FA_ELECTRIC_POWER') UNION ALL*/
SELECT 'POLICY_CIVIC_FREE_SPEECH', 'BUILDINGCLASS_TAX', 'YIELD_CULTURE', 10 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TRADER_SIDS_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_LANDSEA_EXTRACTORS_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_HEXXON_REFINERY_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_GIORGIO_ARMEIER_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_FIRAXITE_MATERIALS_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TWOKAY_FOODS_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_CIVILIZED_JEWELERS_HQ', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TRADER_SIDS_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_LANDSEA_EXTRACTORS_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_HEXXON_REFINERY_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_GIORGIO_ARMEIER_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_FIRAXITE_MATERIALS_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_TWOKAY_FOODS_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_CIVILIZED_JEWELERS_HQ', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_WORKSHOP', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'BUILDINGCLASS_WORKSHOP', 'YIELD_PRODUCTION', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TRADER_SIDS_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_LANDSEA_EXTRACTORS_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_HEXXON_REFINERY_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_GIORGIO_ARMEIER_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_FIRAXITE_MATERIALS_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TWOKAY_FOODS_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_CIVILIZED_JEWELERS_HQ', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TRADER_SIDS_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_LANDSEA_EXTRACTORS_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_HEXXON_REFINERY_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_GIORGIO_ARMEIER_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_FIRAXITE_MATERIALS_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TWOKAY_FOODS_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_CIVILIZED_JEWELERS_HQ', 'YIELD_TOURISM', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_MARKET', 'YIELD_PRODUCTION', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_BANK', 'YIELD_PRODUCTION', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_BANK', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_MARKET', 'YIELD_GOLD', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT 'POLICY_CIVIC_ANCESTOR_WORSHIP', 'BUILDINGCLASS_ANCESTOR_WORSHIP', 'YIELD_FAITH', 10 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'BUILDINGCLASS_TAX', 'YIELD_SCIENCE', 10;

INSERT INTO Policy_YieldChangesPerReligion (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'YIELD_FOOD', 100 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'YIELD_GOLD', 100 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'YIELD_CULTURE', 100 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'YIELD_SCIENCE', 100 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'YIELD_FAITH', 100 UNION ALL
SELECT 'POLICY_CIVIC_FREE_RELIGION', 'YIELD_PRODUCTION', 100;

INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
SELECT 'POLICY_CIVIC_UNIVERSAL_SUFFRAGE', (p.ImprovementType), 'YIELD_FOOD', 5 FROM Policy_ImprovementYieldChanges p WHERE p.PolicyType = 'POLICY_TRADITION_FINISHER' AND p.YieldType = 'YIELD_FOOD' UNION ALL
SELECT 'POLICY_CIVIC_FREE_SPEECH', (p.ImprovementType), 'YIELD_CULTURE', 2 FROM Policy_ImprovementYieldChanges p WHERE p.PolicyType = 'POLICY_TRADITION_FINISHER' AND p.YieldType = 'YIELD_FOOD';

CREATE TRIGGER NationalSuffrageBonusAndFreeSpeechBonus
AFTER INSERT ON Policy_ImprovementYieldChanges
WHEN EXISTS (SELECT * FROM Policy_ImprovementYieldChanges WHERE NEW.PolicyType = 'POLICY_TRADITION_FINISHER' AND NEW.YieldType = 'YIELD_FOOD')
BEGIN
  INSERT INTO Policy_ImprovementYieldChanges(PolicyType, ImprovementType, YieldType, Yield) 
	SELECT 'POLICY_CIVIC_UNIVERSAL_SUFFRAGE', NEW.ImprovementType, 'YIELD_FOOD', 5 UNION ALL
	SELECT 'POLICY_CIVIC_FREE_SPEECH', NEW.ImprovementType, 'YIELD_CULTURE', 2;
END;

INSERT INTO Policy_BuildingClassYieldModifiers (PolicyType, BuildingClassType, YieldType, YieldMod)
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', (b.BuildingClass), 'YIELD_FOOD', 5 FROM Buildings b WHERE b.IsReformation = 1 AND b.UnlockedByBelief = 1 AND b.HolyCity = 1 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', (b.BuildingClass), 'YIELD_PRODUCTION', 5 FROM Buildings b WHERE b.IsReformation = 1 AND b.UnlockedByBelief = 1 AND b.HolyCity = 1 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', (b.BuildingClass), 'YIELD_GOLD', 5 FROM Buildings b WHERE b.IsReformation = 1 AND b.UnlockedByBelief = 1 AND b.HolyCity = 1 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', (b.BuildingClass), 'YIELD_CULTURE', 5 FROM Buildings b WHERE b.IsReformation = 1 AND b.UnlockedByBelief = 1 AND b.HolyCity = 1 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', (b.BuildingClass), 'YIELD_SCIENCE', 5 FROM Buildings b WHERE b.IsReformation = 1 AND b.UnlockedByBelief = 1 AND b.HolyCity = 1 UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', (b.BuildingClass), 'YIELD_FAITH', 5 FROM Buildings b WHERE b.IsReformation = 1 AND b.UnlockedByBelief = 1 AND b.HolyCity = 1;

CREATE TRIGGER OrganizedReligionFounderBonus
AFTER INSERT ON Buildings
WHEN EXISTS (SELECT * FROM Buildings WHERE NEW.IsReformation = 1 AND NEW.UnlockedByBelief = 1 AND NEW.HolyCity = 1)
BEGIN
  INSERT INTO Policy_BuildingClassYieldModifiers (PolicyType, BuildingClassType, YieldType, YieldMod) 
	SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', NEW.BuildingClass, 'YIELD_FOOD', 5 UNION ALL
	SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', NEW.BuildingClass, 'YIELD_PRODUCTION', 5 UNION ALL
	SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', NEW.BuildingClass, 'YIELD_GOLD', 5 UNION ALL
	SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', NEW.BuildingClass, 'YIELD_CULTURE', 5 UNION ALL
	SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', NEW.BuildingClass, 'YIELD_SCIENCE', 5 UNION ALL
	SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', NEW.BuildingClass, 'YIELD_FAITH', 5;
END;

/* UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_MAUSOLEUM', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_MAUSOLEUM', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_MAUSOLEUM', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_MAUSOLEUM', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_MAUSOLEUM', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_MAUSOLEUM', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HEAVENLY_THRONE', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HEAVENLY_THRONE', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HEAVENLY_THRONE', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HEAVENLY_THRONE', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HEAVENLY_THRONE', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HEAVENLY_THRONE', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GREAT_ALTAR', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GREAT_ALTAR', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GREAT_ALTAR', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GREAT_ALTAR', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GREAT_ALTAR', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GREAT_ALTAR', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_RELIQUARY', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_RELIQUARY', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_RELIQUARY', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_RELIQUARY', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_RELIQUARY', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_RELIQUARY', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_DIVINE_COURT', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_DIVINE_COURT', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_DIVINE_COURT', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_DIVINE_COURT', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_DIVINE_COURT', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_DIVINE_COURT', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_SACRED_GARDEN', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_SACRED_GARDEN', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_SACRED_GARDEN', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_SACRED_GARDEN', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_SACRED_GARDEN', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_SACRED_GARDEN', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HOLY_COUNCIL', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HOLY_COUNCIL', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HOLY_COUNCIL', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HOLY_COUNCIL', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HOLY_COUNCIL', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_HOLY_COUNCIL', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_APOSTOLIC_PALACE', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_APOSTOLIC_PALACE', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_APOSTOLIC_PALACE', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_APOSTOLIC_PALACE', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_APOSTOLIC_PALACE', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_APOSTOLIC_PALACE', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GRAND_OSSUARY', 'YIELD_FOOD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GRAND_OSSUARY', 'YIELD_PRODUCTION', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GRAND_OSSUARY', 'YIELD_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GRAND_OSSUARY', 'YIELD_CULTURE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GRAND_OSSUARY', 'YIELD_SCIENCE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_ORGANIZED_RELIGION', 'BUILDINGCLASS_GRAND_OSSUARY', 'YIELD_FAITH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );*/


/*INSERT INTO Policy_ResourceYieldChanges (PolicyType, ResourceType, YieldType, Yield)
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_HORSE', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_HORSE', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_IRON', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_IRON', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_COAL', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_COAL', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_OIL', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_OIL', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_ALUMINUM', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_ALUMINUM', 'YIELD_GOLD', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_URANIUM', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'POLICY_CIVIC_INDUSTRIALIZED_SERVITUDE', 'RESOURCE_URANIUM', 'YIELD_GOLD', 2;*/

/*INSERT INTO Policy_YieldFromBorderGrowth (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_CIVIL_LAW', 'YIELD_GOLD', 5 UNION ALL
SELECT 'POLICY_CIVIC_CIVIL_LAW', 'YIELD_GOLDEN_AGE_POINTS', 2;*/

--INSERT INTO Policy_GreatWorkYieldChanges (PolicyType, YieldType, Yield)
--SELECT 'POLICY_CIVIC_FREE_SPEECH', 'YIELD_GOLD', 2;

INSERT INTO Policy_GoldenAgeYieldMod (PolicyType, YieldType, Yield)
--SELECT 'POLICY_CIVIC_REPRESENTATION', 'YIELD_TOURISM', 10 UNION ALL
--SELECT 'POLICY_CIVIC_REPRESENTATION', 'YIELD_FAITH', 10 UNION ALL
--SELECT 'POLICY_CIVIC_CIVIL_LAW', 'YIELD_FOOD', 5 UNION ALL
SELECT 'POLICY_CIVIC_CONSTIUTIONALISM', 'YIELD_FOOD', 20 UNION ALL
SELECT 'POLICY_CIVIC_CONSTIUTIONALISM', 'YIELD_SCIENCE', 20 UNION ALL
SELECT 'POLICY_CIVIC_CONSTIUTIONALISM', 'YIELD_FAITH', 20;

INSERT INTO Policy_GoldenAgeGreatPersonRateModifier (PolicyType, GreatPersonType, Modifier)
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_ENGINEER', 25 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_SCIENTIST', 25 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_MERCHANT', 25 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_ARTIST', 25 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_MUSICIAN', 25 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_WRITER', 25 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'GREATPERSON_DIPLOMAT', 25;

--INSERT INTO Policy_CapitalYieldPerPopChanges (PolicyType, YieldType, Yield)
--SELECT 'POLICY_CIVIC_BUREAUCRACY', 'YIELD_PRODUCTION', 150 UNION ALL
--SELECT 'POLICY_CIVIC_BUREAUCRACY', 'YIELD_GOLD', 150;

INSERT INTO Policy_CapitalYieldPerPopChangeEmpire (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'YIELD_GREAT_GENERAL_POINTS', 40 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'YIELD_GREAT_ADMIRAL_POINTS', 40 UNION ALL
SELECT 'POLICY_CIVIC_CONSTIUTIONALISM', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'YIELD_GOLD', 2;

--INSERT INTO Policy_WLTKDYieldMod (PolicyType, YieldType, Yield)
--SELECT 'POLICY_CIVIC_CONFEDERATION', 'YIELD_GOLD', 10;
--SELECT 'POLICY_CIVIC_CIVIL_LAW', 'YIELD_FOOD', 5;

INSERT INTO Policy_YieldChangeTradeRoute (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_MERCANTILISM', 'YIELD_FOOD', 3 UNION ALL
SELECT 'POLICY_CIVIC_MERCANTILISM', 'YIELD_PRODUCTION', 3;

INSERT INTO Policy_YieldChangesNaturalWonder (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_ANCESTOR_WORSHIP', 'YIELD_FAITH', 2 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'YIELD_CULTURE', 2;

INSERT INTO Policy_UnitClassProductionModifiers (PolicyType, UnitClassType, ProductionModifier)
SELECT 'POLICY_CIVIC_FREE_MARKET', 'UNITCLASS_CARGO_SHIP', 25 UNION ALL
SELECT 'POLICY_CIVIC_FREE_MARKET', 'UNITCLASS_CARAVAN', 25;

INSERT INTO Policy_FeatureYieldChanges (PolicyType, FeatureType, YieldType, Yield)
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'FEATURE_FOREST', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'FEATURE_OASIS', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'FEATURE_JUNGLE', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'FEATURE_FLOOD_PLAINS', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'FEATURE_MARSH', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'POLICY_CIVIC_ENVIRONMENTALISM', 'FEATURE_ATOLL', 'YIELD_CULTURE', 2;

INSERT INTO Policy_SpecialistExtraYields (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_REPRESENTATION', 'YIELD_SCIENCE', 1 UNION ALL
SELECT 'POLICY_CIVIC_PACIFISM', 'YIELD_GOLDEN_AGE_POINTS', 1;

INSERT INTO Policy_SpecialistYieldChanges (PolicyType, SpecialistType, YieldType, Yield)
--SELECT 'POLICY_CIVIC_PATRONAGE', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLD', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_ARTIST', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_MUSICIAN', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_WRITER', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_ENGINEER', 'YIELD_PRODUCTION', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_SCIENTIST', 'YIELD_SCIENCE', 1 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
SELECT 'POLICY_CIVIC_STATE_PROPERTY', 'SPECIALIST_ENGINEER', 'YIELD_FOOD', 1;

INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_CIVIC_CONFEDERATION', 'BUILDINGCLASS_TAX', -3 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value = 0) UNION ALL
SELECT 'POLICY_CIVIC_CONFEDERATION', 'BUILDINGCLASS_PALACE', 4 UNION ALL
SELECT 'POLICY_CIVIC_SLAVERY', 'BUILDINGCLASS_TAX', -1 UNION ALL
SELECT 'POLICY_CIVIC_SLAVERY', 'BUILDINGCLASS_COURTHOUSE', 1 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_WRITERS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_ARTISTS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_MUSICIANS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_ENGINEERS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_MERCHANTS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_SCIENTISTS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_DIPLOMATS_GUILD', 2 UNION ALL
SELECT 'POLICY_CIVIC_STATE_ATHEISM', 'BUILDINGCLASS_STATE_ATHEISM', 1;

INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_WRITERS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_ARTISTS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_MUSICIANS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_ENGINEERS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_MERCHANTS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_SCIENTISTS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_MECHANIZATION', 'BUILDINGCLASS_DIPLOMATS_GUILD', 100 UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TRADER_SIDS', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_LANDSEA_EXTRACTORS', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_HEXXON_REFINERY', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_GIORGIO_ARMEIER', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_FIRAXITE_MATERIALS', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_TWOKAY_FOODS', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT 'POLICY_CIVIC_CORPORATISM', 'BUILDINGCLASS_CIVILIZED_JEWELERS', 100 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );