UPDATE Language_ko_KR
SET Text = Text||' [COLOR_CYAN]연안[ENDCOLOR]에서  [ICON_MOVES] 이동력이 2배가 됩니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE Language_ko_KR
SET Text = Text||' [COLOR_CYAN]승선[ENDCOLOR]시 [ICON_MOVES] 이동 비용 1이 듭니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_1_HELP';

UPDATE Language_ko_KR
SET Text = Text||'[NEWLINE][ICON_MOVES] 승선 이동력이 +1 증가합니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_FROGMAN_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '승선 그리고 ', '')
WHERE Tag = 'TXT_KEY_PROMOTION_FROGMAN_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, ' 그리고 승선 이동', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[ICON_MOVES] 승선 이동력이 +1 증가합니다.[NEWLINE]', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, ' 그리고 승선 이동', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[ICON_MOVES] 승선 이동력이 +1 증가합니다.[NEWLINE]', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '승선 그리고 ', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '승선, ', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, ' 그리고 승선 이동', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[ICON_MOVES] 승선 이동력이 +1 증가합니다.[NEWLINE]', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';