INSERT INTO Language_ko_KR (Text, Tag)
SELECT  '아니요. 지금은 바꾸고 싶지 않아요.',
		'TXT_KEY_EVENT_CIVIC_NOPE' UNION ALL
SELECT  '구관이 명관이죠.[NEWLINE][NEWLINE]같은 턴에 이 설정을 두 번 이상 사용하지 마세요!',
		'TXT_KEY_EVENT_CIVIC_NOPE_HELP' UNION ALL		
SELECT  '정부 정책',
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION' UNION ALL
SELECT  '"우리는 신의 권리로 정부를 인정하지 않는다. 통치할 수 있는 유일한 합법적 권리는 피지배자로부터의 명시적 권한 부여뿐이다."[NEWLINE]-- 윌리엄 헨리 해리슨', 
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP' UNION ALL
SELECT 	'전제정치',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]문맹으로 [ICON_HAPPINESS_3] 불행 -10% [ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] 저항  가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 0%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '세습 통치',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]군사 이론 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]주둔군에서 [ICON_HAPPINESS_1] 행복 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]아군 도시 근처에서 군사 유닛의 [ICON_STRENGTH] 전투력이 +10% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER]불가사의를 향한 [ICON_PRODUCTION] 생산력 +5%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE] [NEWLINE]의교 의견: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  '연방', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]문자 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+4 [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_GOLD] Gold in non-Capital Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+10% [ICON_HAPPINESS_3] Unhappiness Modifier for all Needs in all non-Capital Cities
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[NEWLINE][ICON_BULLET]문자 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+4 [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_GOLD] Gold in Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cities generate 3 [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '후원', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]교육 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15 [ICON_INFLUENCE] City-State Resting Point[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Military gifts to [ICON_CITY_STATE] City-States yield an additional +5 [ICON_INFLUENCE] Influence[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]100% of Base Gold Maintenance from {TXT_KEY_BUILDING_CHANCERY} and {TXT_KEY_BUILDING_WIRE_SERVICE} is added as a Gold Bonus[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP' UNION ALL
 --[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold and [ICON_TOURISM] Tourism in the [ICON_CAPITAL] Capital for every City-State Friendship (tripled if City-State Ally)[ENDCOLOR] 
SELECT  '대의권', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]인쇄기 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness for every 15 [ICON_CITIZEN] Citizens in a City[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_RESEARCH] Science from Specialists[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  '전체주의', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]강선 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_GREAT_GENERAL][ICON_GREAT_ADMIRAL] Great General/Admiral''s Leadership[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-25% [ICON_HAPPINESS_3] from [ICON_WAR] War Weariness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]100% of Base Gold Maintenance from {TXT_KEY_BUILDING_BARRACKS}, {TXT_KEY_BUILDING_ARMORY}, {TXT_KEY_BUILDING_STABLE}, {TXT_KEY_BUILDING_HARBOR}, {TXT_KEY_BUILDING_SEAPORT}, and {TXT_KEY_BUILDING_MILITARY_ACADEMY} is added as a Gold Bonus[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]강선 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_GENERAL] Great General''s Combat Bonus increased by +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15% Military Unit Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Foreign Spies are +33% ineffective at stealing [ICON_RESEARCH] Technologies from your Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold from Barracks, Armories, and Military Academies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness from Police Station[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '국민 참정권', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]원자론 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% Cost of [ICON_INVEST] Gold Investments in all Cities and Unit Upgrades[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] Citizens generate +0.25 [ICON_FOOD] Food, [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+5 [ICON_FOOD] Food from [ICON_GREAT_PEOPLE] Great People Improvements and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]원자론 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Citizens generate +0.25 [ICON_FOOD] Food [ICON_PRODUCTION] Production, and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] Great People Improvements generates +4 [ICON_FOOD] Food[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cost of [ICON_INVEST] Gold Investments in all cities reduced by -8%[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '법률 정책',
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION' UNION ALL
SELECT  '"어떤 사람이든 국가를 세우고 법을 주기를 원하는 사람은, 모든 사람이 나쁘다고 가정하고, 기회가 있을 때마다 그들의 악랄한 본성을 드러낼 준비가 되어 있다고 가정하는 것으로 시작해야 한다."[NEWLINE]-- 니콜로 마키아벨리의 로마사 논고', 
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP' UNION ALL
SELECT 	'무정부주의',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Distress[ENDCOLOR]
[NEWLINE][ICON_BULLET]No [ICON_RESISTANCE] Resistance when chosen
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance} [ICON_GOLD])
[NEWLINE][ICON_BULLET]No [ICON_RESISTANCE] Resistance when chosen
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '성문화된 법률',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]수학 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_CULTURE] Culture from [ICON_WONDER] World Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]1 Specialist in every City no longer produces [ICON_HAPPINESS_3] Unhappiness from [ICON_URBANIZATION] Urbanization[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  '봉건제', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]기사도 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-35% Unit Maintenance (+{2_Gold}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Units trained gain an additional +15 XP[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+20% Yield from City-States, Vassals tribute an additional 10% of their yields, -10% Yield penalties from [ICON_PUPPET] Puppeted Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  '관료제', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]물리학 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+7 [ICON_CITIZEN_RED] Laborer in the [ICON_CAPITAL] Capital that can work an additional tile or a specialist slot[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]7 Specialists in the [ICON_CAPITAL] Capital no longer produces [ICON_HAPPINESS_3] Unhappiness from [ICON_URBANIZATION] Urbanization[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+100% Base Yields and Yield Modifiers of the Palace and National Wonders that have a building requirement[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  '국가주의', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]군사 과학 필요
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Gain 25 [ICON_CULTURE] Culture and [ICON_GOLDEN_AGE] Golden Age Points when you succeed in an [ICON_SPY] Espionage action in a foreign City, scaling with Era[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_SILVER_FIST] Unit Supply generated by [ICON_CITIZEN] Population[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  '표현의 자유', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]라디오 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]+10% [ICON_CULTURE] Culture in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_CULTURE] Culture from [ICON_GREAT_PEOPLE] Great People Improvements and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  '입헌주의', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]전기 통신 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_GOLDEN_AGE] Golden Age Length[ENDCOLOR]
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]+20% [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith during a [ICON_GOLDEN_AGE] Golden Age[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] Citizens generate +1 [ICON_GOLDEN_AGE] Golden Age Point[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  '노동 정책',
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION' UNION ALL
SELECT  '"밤이 거의 새어 낮이 가까웠습니다. 그러니 어둠의 행실을 벗어버리고 빛의 갑옷을 입읍시다."[NEWLINE]-- 신약 성경: 로마인들에게 보낸 편지, 13:12', 
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP' UNION ALL
SELECT 	'Tribalism',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Boredom[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Slavery',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Bronze Working
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_CITIZEN_RED] Laborer in all Cities that can work an additional tile or a specialist slot[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-10% [ICON_FOOD] Growth in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+1 [ICON_HAPPINESS_4] Unhappiness in all Cities with no Courthouses[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Manorialism', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Civil Service
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% Tile improvement rate[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food in Cities for every 5 non-Specialist [ICON_CITIZEN] Citizens[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Caste System', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Guilds
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GREAT_GENERAL] Great General Point and [ICON_GREAT_ADMIRAL] Great Admiral Point in your [ICON_CAPITAL] Capital for every 40 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Specialists produce an additional +1 of their base yield (Exception: Civil Servants produce +1 [ICON_GOLDEN_AGE])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Guilds
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GREAT_GENERAL] Great General Point and [ICON_GREAT_ADMIRAL] Great Admiral Point in your [ICON_CAPITAL] Capital for every 25 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Specialists produce an additional +1 of their base yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cities produce 1 more [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Industrial Servitude', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Industrialization
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_FOOD] Growth in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_PRODUCTION] Production and [ICON_GOLD] in Cities for every 4 non-Specialist [ICON_CITIZEN] Citizens[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Farms, Forts, Mines, Lumbermills, and Villages produce an additional +1 of their base yields[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Unionism', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Electricity
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Guilds, Labor Associations, Credit Unions, Science Institutions, and Civil Departments produce +4 of their respective yields, +2 [ICON_HAPPINESS_1] Happiness, and build 100% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Emancipation', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Globalization
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]25% of [ICON_HAPPINESS_1] Happiness produced in each City is added to the City''s [ICON_CULTURE] Culture per Turn[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_TOURISM] Tourism to civilizations that have less [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Economy Civics', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION' UNION ALL
SELECT  '"마음이 행복할 때의 빵 한 조각이 불행할 때의 부보다 낫다."[NEWLINE]-- 아메네모페', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP' UNION ALL
SELECT 	'Bartering',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Poverty[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Decentralization',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Trade
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_GOLD] Gold from [ICON_INTERNATIONAL_TRADE] International Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_INTERNATIONAL_TRADE] Trade Routes to City-States generate +0.75 [ICON_INFLUENCE] Influence per turn (with the target City-State) per each owned City-State Trade Route (up to +3.75)[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Commercialism',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Currency
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_FOOD] Food and [ICON_PRODUCTION] Production from [ICON_CONNECTED] City Connections[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+33% [ICON_FOOD] Food and [ICON_PRODUCTION] Production from Internal [ICON_INTERNATIONAL_TRADE] Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Can only create International [ICON_INTERNATIONAL_TRADE] Trade Routes to Allied City-States, Vassals, and Masters[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Free Market', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Economics
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_INTERNATIONAL_TRADE] Trade Route[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+12% [ICON_TOURISM] Tourism modifier for [COLOR_POSITIVE_TEXT]Trade Routes[ENDCOLOR][ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Train Trade Units 25% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'State Property', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]You are missing a Corporate Headquarter', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Corporation
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Corporation
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] Corporate Headquarter produces +10% [ICON_FOOD] Food and [ICON_CULTURE] Culture [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_OFFICE] Corporate Offices produce +4 [ICON_FOOD] Food and +2 [ICON_RESEARCH] Science [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food from [ICON_VP_ENGINEER] Engineers, Mines, Quarries, Lumbermills, and Manufactories[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Scientific Theory
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food to Mine, Quarry, Lumbermill, and Manufactory[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities with a Workshop produce +10% [ICON_FOOD] Food and [ICON_PRODUCTION] Production
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Corporatism', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]You are missing a Corporate Headquarter', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Corporation
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Corporation
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] Corporate Headquarter produces +15% [ICON_GOLD] Gold and [ICON_TOURISM] Tourism[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]100% of Base Gold Maintenance from [ICON_VP_OFFICE] Corporate Offices is added as a Gold Bonus[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Each unique [ICON_VP_MONOPOLY] Global Monopoly modifier is increased by an additional 5% if it is percentage-based, or +2 otherwise.[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Industrialization
[NEWLINE][ICON_BULLET]높은 유지비
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Markets and Banks produce +15% more [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Environmentalism', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Alternative Energy
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold in your [ICON_CAPITAL] Capital for every 2 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_FRANCHISE] Corporate Franchises produce +10 [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_CULTURE] Culture from [ICON_RES_ARTIFACTS] Landmarks, Forests, Jungles, Marshes, Flood Plains, Oases, Atolls, and Natural Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-1 [ICON_FOOD] Food from Farms[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-3 [ICON_PRODUCTION] Production from Mines, Quarries, Lumbermills, and Manufactories[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Religion Civics', 
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION' UNION ALL
SELECT  '"인간의 구원에는 세 가지가 필요하다. 믿을 것을 아는 것, 추구할 것을 아는 것, 해야 할 것을 아는 것이다."[NEWLINE]-- 성 토마스 아퀴나스',
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP' UNION ALL
SELECT 	'Paganism',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Religious Unrest[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Ancestor Veneration', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Calendar
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_PEACE] Faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Unlocks the faith purchases of Altars (50 [ICON_PEACE] Faith cost, +1 [ICON_PEACE] Faith, +1 [ICON_CULTURE_LOCAL] Border Growth Point)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Altars generate +10% [ICON_PEACE] Faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_PEACE] Faith from Natural Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Organized Faith',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]Your Majority Religion (if present) does not have an Enhancer or a Reformation Belief.',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Philosophy
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Majority Religion that has an Enhancer or Reformation Belief
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Religious Founder building produce +5% of all yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_PRODUCTION] Production from Temples, Holy Sites, and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 )  UNION ALL
SELECT  '[ICON_BULLET]Requires Philosophy
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +1 [ICON_PRODUCTION] Production and [ICON_PEACE] faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Temple, Holy Sites, and Landmarks generate +3 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 )  UNION ALL
SELECT  'Theocracy', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]You are missing a Majority Religion.',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Theology
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Majority Religion
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Military Units heal 5 additional HP per turn in non-hostile territory and gain [ICON_PEACE] Faith from defeated enemy units[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_RESEARCH] Science[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_GOLD] Gold from Temple, Holy Sites, and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Pacifism', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Biology
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_GREAT_PEOPLE] Great People Generation Rate (doubled during [ICON_GOLDEN_AGE] Golden Ages)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLDEN_AGE] Golden Age Point to Specialists[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+50% [ICON_HAPPINESS_3] from [ICON_WAR] War Weariness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+100% Unit Maintenance (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Biology
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_GREAT_PEOPLE] Great People Generation Rate (doubled during [ICON_GOLDEN_AGE] Golden Ages)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_CULTURE] Culture[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+100% Base Unit Maintenance (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Celebrity Worship', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Flight
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Unlocks the construction of Idols (+1 [ICON_GOLDEN_AGE] Golden Age Point)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Idols generate +3 [ICON_CULTURE] Culture, +2 [ICON_TOURISM] Tourism, and +1 [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_CULTURE] Culture from Holy Sites and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Free Religion', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Penicilin
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness and +10% [ICON_RESEARCH] Science in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 to all City Yields for every World Religion that has at least one Follower in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Penicilin
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Taxes',
		'TXT_KEY_TAX' UNION ALL
SELECT  'Altar',
		'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT  'Can only be faith purchased if you adopt [COLOR_MAGENTA]{TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7}[ENDCOLOR].',
		'TXT_KEY_ANCESTOR_WORSHIP_HELP' UNION ALL
SELECT  'Idol',
		'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT  'Might Makes Right',
		'TXT_KEY_PROMOTION_HEREDITARYRULE' UNION ALL
SELECT  '+10% [ICON_STRENGTH] Combat Strength when [COLOR_POSITIVE_TEXT]adjacent to or stationed in a friendly City[ENDCOLOR].',
		'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP' UNION ALL
SELECT  'Theocratic Warrior',
		'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL
SELECT  '[COLOR_POSITIVE_TEXT]Heal +5 HP[ENDCOLOR] per turn in non-enemy territory.[NEWLINE][NEWLINE]Gain 50% of the [ICON_STRENGTH] Combat Strength of defeated Enemy Unit as [ICON_PEACE] Faith',
		'TXT_KEY_PROMOTION_DEUSVULT_HELP'; --UNION ALL
--SELECT  '정책이란 무엇입니까?',
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q1_DESC' UNION ALL
--SELECT  '유지, 혁명, 외교?', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q2_DESC' UNION ALL
--SELECT  '혁명의 기회?',
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q3_DESC' UNION ALL
--SELECT  '정책과 개혁이 설치되었습니다!', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_DESC' UNION ALL
--SELECT  '축하합니다. 정책과 개혁이 성공적으로 활성화되었습니다. 이 모드는 Civilization IV의 정책에서 상당한 영향을 받았다는 것을 알 수 있습니다. 이것이 여러분의 문명을 관리하는 방법에 대한 정부의 결정에 영향을 미치기를 바랍니다! 다양하게 실험해 보고 즐겨보세요! 게임에서 이벤트 시스템이 활성화되어 있지 않으면 이 모드는 제대로 작동하지 않습니다.', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_HELP' UNION ALL
--SELECT  'Hereditary Rule Unlocked[NEWLINE][NEWLINE]세습 통치는 통치권이 가족 구성원 간에 물려지는 정부 형태입니다. 세습 통치의 장점은 보통 왕위 계승이 명확하기 때문에 현 군주가 죽었을 때 권력 다툼이 덜할 수 있다는 것입니다. 그러나 세습 통치는 모든 비선출 통치자와 마찬가지로 다음과 같은 약점을 안고 있습니다. 지도자는 국민에게 책임을 질 필요가 없으며, 나쁜 지도자를 제거하는 것은 매우 어려울 수 있습니다.',
--		'TXT_KEY_TUTORIAL_HEREDITARY_RULE_HELP';
--------------------------------------------------------------------------------------------------------------------------