INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
SELECT 'MORE_SPECIALIST_ATLAS', 256, 'SpecialistAtlas256.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 128, 'SpecialistAtlas128.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 80, 'SpecialistAtlas80.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 64, 'SpecialistAtlas64.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 45, 'SpecialistAtlas45.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS', 32, 'SpecialistAtlas32.dds', 4, 2 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 256, 'c&r_PI_256.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 64, 'c&r_PI_064.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 45, 'c&r_PI_045.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 32, 'c&r_PI_032.dds', 2, 1 UNION ALL
SELECT 'MORE_SPECIALIST_ATLAS2', 16, 'c&r_PI_016.dds', 2, 1;

INSERT INTO Language_en_US (Tag, Text)
SELECT 'TXT_KEY_BUILDING_ENGINEERS_GUILD', 'Labor Association' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCHANTS_GUILD', 'Credit Union' UNION ALL
SELECT 'TXT_KEY_BUILDING_SCIENTISTS_GUILD', 'Science Institution' UNION ALL
SELECT 'TXT_KEY_BUILDING_DIPLOMATS_GUILD', 'Civil Department' UNION ALL
SELECT 'TXT_KEY_BUILDING_PUBLICAN_OFFICE', 'Publican''s Office' UNION ALL
SELECT 'TXT_KEY_BUILDING_ENGINEERS_GUILD_HELP', 'Provides 5 [ICON_GREAT_PEOPLE] Great Person Points (GPP) towards a [ICON_GREAT_ENGINEER] Great Engineer. All Workshops produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE][ICON_CITY_STATE] Empire Size Modifier is reduced by 3% in all Cities.[NEWLINE][NEWLINE]Maximum of 3 of these buildings in your Empire.' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCHANTS_GUILD_HELP', 'Provides 5 [ICON_GREAT_PEOPLE] Great Person Points (GPP) towards a [ICON_GREAT_MERCHANT] Great Merchant. All Banks produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE]-4% [ICON_GOLD] Base Building Maintenance in all Cities.[NEWLINE][NEWLINE]Maximum of 3 of these buildings in your Empire.' UNION ALL
SELECT 'TXT_KEY_BUILDING_SCIENTISTS_GUILD_HELP', 'Provides 5 [ICON_GREAT_PEOPLE] Great Person Points (GPP) towards a [ICON_GREAT_SCIENTIST] Great Scientist. All Research Labs produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE][ICON_GREAT_SCIENTIST] Great Scientists provide +5% more [ICON_RESEARCH] Science when used to discover new Technologies.[NEWLINE][NEWLINE]Maximum of 3 of these buildings in your Empire.' UNION ALL
SELECT 'TXT_KEY_BUILDING_DIPLOMATS_GUILD_HELP', 'Provides 5 [ICON_GREAT_PEOPLE] Great Person Points (GPP) towards a [ICON_GREAT_DIPLOMAT] Great Diplomat. All Wire Services produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE]Receive 1 [COLOR_POSITIVE_TEXT]Additional[ENDCOLOR] [ICON_DIPLOMAT] Delegate in the World Congress.[NEWLINE][NEWLINE]Maximum of 3 of these buildings in your Empire.' UNION ALL
SELECT 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_HELP', '-10% [ICON_GOLD] Base Building Maintenance in all Cities.[NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.' UNION ALL
SELECT 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_PEDIA', 'Publicans were public contractors during antiquity Rome. They supplied the army and military, managed taxes, and oversaw public projects. The legacy of these publicans would inspire how modern government would operate since these people were the first witness to the challenges with managing large territories and population.';

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description, MaxPlayerInstances)
SELECT 'BUILDINGCLASS_ENGINEERS_GUILD', 'BUILDING_ENGINEERS_GUILD', 'TXT_KEY_BUILDING_ENGINEERS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_MERCHANTS_GUILD', 'BUILDING_MERCHANTS_GUILD', 'TXT_KEY_BUILDING_MERCHANTS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_SCIENTISTS_GUILD', 'BUILDING_SCIENTISTS_GUILD', 'TXT_KEY_BUILDING_SCIENTISTS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_DIPLOMATS_GUILD', 'BUILDING_DIPLOMATS_GUILD', 'TXT_KEY_BUILDING_DIPLOMATS_GUILD', 1 UNION ALL
SELECT 'BUILDINGCLASS_PUBLICAN_OFFICE', 'BUILDING_PUBLICAN_OFFICE', 'TXT_KEY_BUILDING_PUBLICAN_OFFICE', 1;

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_ENGINEERS_GUILD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_MERCHANTS_GUILD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_SCIENTISTS_GUILD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE BuildingClasses
SET MaxPlayerInstances = 3
WHERE Type = 'BUILDINGCLASS_DIPLOMATS_GUILD';

INSERT INTO Buildings (Type, BuildingClass, Cost, Description, Help, GoldMaintenance, HurryCostModifier, MinAreaSize, ArtDefineTag, PrereqTech, SpecialistType, SpecialistCount, GreatPeopleRateChange, IconAtlas, PortraitIndex, NumCityCostMod)
SELECT 'BUILDING_ENGINEERS_GUILD', 'BUILDINGCLASS_ENGINEERS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'TXT_KEY_BUILDING_ENGINEERS_GUILD', 'TXT_KEY_BUILDING_ENGINEERS_GUILD_HELP', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'ART_DEF_BUILDING_FORGE', 'TECH_STEAM_POWER', 'SPECIALIST_ENGINEER', 0, 5, 'MORE_SPECIALIST_ATLAS', 0, 0 UNION ALL
SELECT 'BUILDING_MERCHANTS_GUILD', 'BUILDINGCLASS_MERCHANTS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_WIRE_SERVICE'), 'TXT_KEY_BUILDING_MERCHANTS_GUILD', 'TXT_KEY_BUILDING_MERCHANTS_GUILD_HELP', 0, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'ART_DEF_BUILDING_BANK', 'TECH_REPLACEABLE_PARTS', 'SPECIALIST_MERCHANT', 0, 5, 'MORE_SPECIALIST_ATLAS', 1, 0 UNION ALL
SELECT 'BUILDING_SCIENTISTS_GUILD', 'BUILDINGCLASS_SCIENTISTS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_STADIUM'), 'TXT_KEY_BUILDING_SCIENTISTS_GUILD', 'TXT_KEY_BUILDING_SCIENTISTS_GUILD_HELP', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_STADIUM'), (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'ART_DEF_BUILDING_UNIVERSITY', 'TECH_ATOMIC_THEORY', 'SPECIALIST_SCIENTIST', 0, 5, 'MORE_SPECIALIST_ATLAS', 2, 0 UNION ALL
SELECT 'BUILDING_DIPLOMATS_GUILD', 'BUILDINGCLASS_DIPLOMATS_GUILD', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_INTERPRETIVE_CENTER'), 'TXT_KEY_BUILDING_DIPLOMATS_GUILD', 'TXT_KEY_BUILDING_DIPLOMATS_GUILD_HELP', (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_INTERPRETIVE_CENTER'), (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WRITERS_GUILD'), -1, 'COURTHOUSE', 'TECH_TELECOM', 'SPECIALIST_CIVIL_SERVANT', 0, 5, 'MORE_SPECIALIST_ATLAS', 3, 0;


INSERT INTO Buildings (Type, BuildingClass, Cost, Description, Help, Civilopedia, GoldMaintenance, HurryCostModifier, MinAreaSize, ArtDefineTag, PrereqTech, IconAtlas, PortraitIndex, NumCityCostMod)
SELECT 'BUILDING_PUBLICAN_OFFICE', 'BUILDINGCLASS_PUBLICAN_OFFICE', 125, 'TXT_KEY_BUILDING_PUBLICAN_OFFICE', 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_HELP', 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_PEDIA', 0, -20, -1, 'ART_DEF_BUILDING_BANK', 'TECH_CURRENCY', 'NEW_BLDG_ATLAS_DLC', 1, (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_NATIONAL_COLLEGE');

UPDATE Buildings
SET EmpireSizeModifierReductionGlobal = -3, NeverCapture = 1
WHERE Type = 'BUILDING_ENGINEERS_GUILD';

UPDATE Buildings
SET GlobalBuildingGoldMaintenanceMod = -4, NeverCapture = 1
WHERE Type = 'BUILDING_MERCHANTS_GUILD';

UPDATE Buildings
SET GreatScientistBeakerModifier = 5, NeverCapture = 1
WHERE Type = 'BUILDING_SCIENTISTS_GUILD';

UPDATE Buildings
SET SingleLeagueVotes = 1
WHERE Type = 'BUILDING_DIPLOMATS_GUILD';

UPDATE Buildings
SET GlobalBuildingGoldMaintenanceMod = -10, Civilopedia = 'TXT_KEY_BUILDING_PUBLICAN_OFFICE_PEDIA', NeverCapture = 1, NukeImmune = 1, NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_NATIONAL_COLLEGE'), SpecialistType = 'SPECIALIST_CIVIL_SERVANT', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_PUBLICAN_OFFICE';

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_ENGINEERS_GUILD', 'FLAVOR_PRODUCTION', 60 UNION ALL
SELECT 'BUILDING_MERCHANTS_GUILD', 'FLAVOR_GOLD', 60 UNION ALL
SELECT 'BUILDING_SCIENTISTS_GUILD', 'FLAVOR_SCIENCE', 60 UNION ALL
SELECT 'BUILDING_DIPLOMATS_GUILD', 'FLAVOR_DIPLOMACY', 60 UNION ALL
SELECT 'BUILDING_PUBLICAN_OFFICE', 'FLAVOR_GOLD', 45;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PUBLICAN_OFFICE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'BUILDING_PUBLICAN_OFFICE', 'YIELD_GOLD', 1;

INSERT INTO Building_BuildingClassYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange)
SELECT 'BUILDING_ENGINEERS_GUILD', 'BUILDINGCLASS_WORKSHOP', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_MERCHANTS_GUILD', 'BUILDINGCLASS_BANK', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_SCIENTISTS_GUILD', 'BUILDINGCLASS_LABORATORY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'BUILDING_DIPLOMATS_GUILD', 'BUILDINGCLASS_WIRE_SERVICE', 'YIELD_GOLD', 1;

INSERT INTO Civilization_BuildingClassOverrides  (CivilizationType, BuildingClassType, BuildingType)
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_ENGINEERS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_MERCHANTS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_SCIENTISTS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_DIPLOMATS_GUILD', NULL UNION ALL
SELECT 'CIVILIZATION_MINOR', 'BUILDINGCLASS_PUBLICAN_OFFICE', NULL;

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT 'BUILDING_PUBLICAN_OFFICE', 'BUILDINGCLASS_CARAVANSARY';

INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_PUBLICAN_OFFICE', 1;

INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_PUBLICAN_OFFICE', 25;