INSERT OR REPLACE INTO Audio_Sounds (SoundID, Filename, LoadType)
SELECT 'SND_EVENT_EAIRCRAFT', 'EAircraft', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EBANK', 'EBankCashCash', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECITYCAPTURE', 'ECityCapture', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECITYREVOLT', 'ECityRevolt', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECIV', 'ECiv', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECROWDCHEER', 'ECrowdCheer', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ECULTUREEXPANDS', 'ECultureExpands', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EDECLAREWAR', 'EDeclareWar', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EDISCOVERY', 'EDiscovery', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EECONOMIC', 'EEconomic', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EFEATUREGROWTH', 'EFeatureGrowth', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EFIRSTTOSOMETHING', 'EFirstToSomething', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EFOREIGN', 'EForeign', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EGHAST', 'EGhast', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EGOLDENAGE', 'EGoldenAge', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EGREATPEOPLE', 'EGreatPeople', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EMILITARY', 'EMilitary', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EPLAGUE', 'EPlague', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ERELIC', 'ERelic', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EREVOLUTIONEND', 'ERevolutionEnd', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_EREVOLUTIONSTART', 'ERevolutionStart', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ESCIENCE', 'EScience', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ESTRIKE', 'EStrike', 'DynamicResident' UNION ALL
SELECT 'SND_EVENT_ETROOPS', 'ETroops', 'DynamicResident';

INSERT OR REPLACE INTO Audio_2DSounds (ScriptID, SoundID, SoundType, DontTriggerDuplicates, DontPlayMoreThan, TaperSoundtrackVolume, MinVolume, MaxVolume)
SELECT 'AS2D_EVENT_EAIRCRAFT', 'SND_EVENT_EAIRCRAFT', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EBANK', 'SND_EVENT_EBANK', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECITYCAPTURE', 'SND_EVENT_ECITYCAPTURE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECITYREVOLT', 'SND_EVENT_ECITYREVOLT', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECIV', 'SND_EVENT_ECIV', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECROWDCHEER', 'SND_EVENT_ECROWDCHEER', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ECULTUREEXPANDS', 'SND_EVENT_ECULTUREEXPANDS', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EDECLAREWAR', 'SND_EVENT_EDECLAREWAR', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EDISCOVERY', 'SND_EVENT_EDISCOVERY', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EECONOMIC', 'SND_EVENT_EECONOMIC', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EFEATUREGROWTH', 'SND_EVENT_EFEATUREGROWTH', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EFIRSTTOSOMETHING', 'SND_EVENT_EFIRSTTOSOMETHING', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EFOREIGN', 'SND_EVENT_EFOREIGN', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EGHAST', 'SND_EVENT_EGHAST', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EGOLDENAGE', 'SND_EVENT_EGOLDENAGE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EGREATPEOPLE', 'SND_EVENT_EGREATPEOPLE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EMILITARY', 'SND_EVENT_EMILITARY', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EPLAGUE', 'SND_EVENT_EPLAGUE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ERELIC', 'SND_EVENT_ERELIC', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EREVOLUTIONEND', 'SND_EVENT_EREVOLUTIONEND', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_EREVOLUTIONSTART', 'SND_EVENT_EREVOLUTIONSTART', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ESCIENCE', 'SND_EVENT_ESCIENCE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ESTRIKE', 'SND_EVENT_ESTRIKE', 'GAME_SFX', 1, 1, -1.0, 100, 100 UNION ALL
SELECT 'AS2D_EVENT_ETROOPS', 'SND_EVENT_ETROOPS', 'GAME_SFX', 1, 1, -1.0, 100, 100;