DELETE From Building_ResourceQuantityRequirements WHERE BuildingType = 'BUILDING_BLACKSMITH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1 );
DELETE From Building_UnitCombatProductionModifiers WHERE BuildingType = 'BUILDING_BLACKSMITH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1 );
	
UPDATE Building_YieldModifiers
SET Yield = 0
WHERE BuildingType = 'BUILDING_APOTHECARY' AND YieldType = 'YIELD_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_YieldModifiers
SET Yield = 0
WHERE BuildingType = 'BUILDING_BLACKSMITH' AND YieldType = 'YIELD_PRODUCTION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_YieldModifiers
SET Yield = 0
WHERE BuildingType = 'BUILDING_PRINTER' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_YieldModifiers
SET Yield = 0
WHERE BuildingType = 'BUILDING_PRINTER' AND YieldType = 'YIELD_SCIENCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Buildings
SET PrereqTech = 'TECH_PHYSICS', Cost = 225, HurryCostModifier = 5
WHERE Type = 'BUILDING_APOTHECARY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Buildings
SET GoldMaintenance = 1, Cost = 175, HurryCostModifier = 5
WHERE Type = 'BUILDING_BLACKSMITH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Buildings
SET Cost = 175, GoldMaintenance = 0, HurryCostModifier = 5
WHERE Type = 'BUILDING_ALCHEMIST' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_ResourceYieldChanges
SET Yield = 1
WHERE BuildingType = 'BUILDING_ALCHEMIST' AND ResourceType = 'RESOURCE_GOLD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield)
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_AMBER' , 'YIELD_SCIENCE' , 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_JADE' , 'YIELD_SCIENCE' , 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_LAPIS' , 'YIELD_SCIENCE' , 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_LocalResourceOrs (BuildingType, ResourceType)
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_JADE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_AMBER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_LAPIS' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Buildings
SET Cost = 400, Happiness = 1, FoodKept = 0, GoldMaintenance = 1, HurryCostModifier = 5
WHERE Type = 'BUILDING_SEWER_SYSTEM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_GrowthExtraYield (BuildingType, YieldType, Yield)
SELECT 'BUILDING_SEWER_SYSTEM', 'YIELD_FOOD', 60 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_APOTHECARY', 'YIELD_SCIENCE', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Buildings
SET Cost = 375, GoldMaintenance = 3, SpecialistCount = 0, GreatPeopleRateChange = 3, HurryCostModifier = 5
WHERE Type = 'BUILDING_PRINTER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_Flavors
SET Flavor = 0
WHERE BuildingType = 'BUILDING_SEWER_SYSTEM' AND FlavorType = 'FLAVOR_HAPPINESS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

DELETE FROM Building_ClassesNeededInCity
WHERE BuildingType = 'BUILDING_PRINTER' AND BuildingClassType = 'BUILDINGCLASS_UNIVERSITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PRINTER', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_TOURISM', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PRINTER', 'YIELD_SCIENCE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_TOURISM', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_APOTHECARY', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_BLACKSMITH', 'YIELD_PRODUCTION', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_FOOD] Food and +1 [ICON_RESEARCH] Science. +1 [ICON_FOOD] Food for every 10 [ICON_CITIZEN] Population. +20% of the [ICON_RESEARCH] Research of the City is added to the current [ICON_RESEARCH] Research total every time the city gains a [ICON_CITIZEN] Citizen.'
WHERE Tag = 'TXT_KEY_BUILDING_APOTHECARY_HELP';

UPDATE Language_en_US
SET Text = '+1 [ICON_PRODUCTION] Production. +1 [ICON_PRODUCTION] Production for every 6 [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_BUILDING_BLACKSMITH_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_RESEARCH] Science on various luxury resources.'
WHERE Tag = 'TXT_KEY_BUILDING_ALCHEMIST_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_CULTURE] Culture, [ICON_TOURISM] Tourism [ICON_RESEARCH] Science and for +1 bonus for every 10 [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_BUILDING_PRINTER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+60% of the [ICON_FOOD] Food of the City is added to the current [ICON_FOOD] Food total every time the city gains a [ICON_CITIZEN] Citizen and increases the health of the city.'
WHERE Tag = 'TXT_KEY_BUILDING_SEWER_SYSTEM_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);