---------------------------------------
-- reallocate some resources to new corp first
---------------------------------------

DELETE FROM Corporation_ResourceMonopolyOrs;

INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
VALUES
	('CORPORATION_TRADER_SIDS', 'RESOURCE_COCOA'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_SALT'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_SPICES'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_SUGAR'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_TOBACCO'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_CLOVES'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_NUTMEG'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_PEPPER'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_HORSE'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_WHALE'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_CRAB'),
	--('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_FISH'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_IVORY'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_CORAL'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_COAL'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_OIL'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_URANIUM'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_INCENSE'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_PERFUME'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_GLASS'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_BRAZILWOOD'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_SILK'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_COTTON'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_DYE'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_FUR'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_LAPIS'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_IRON'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_ALUMINUM'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_MARBLE'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_COPPER'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_JADE'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_PORCELAIN'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_WINE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_TRUFFLES'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_CITRUS'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_OLIVE'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_COFFEE'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_TEA'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_GOLD'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_SILVER'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_GEMS'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_PEARLS'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_AMBER'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_JEWELRY');

----------------------------------------------------------
-- EMR Compatibility
INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_TRADER_SIDS', Type
FROM Resources
WHERE Type IN ('RESOURCE_BEER') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_BEER] Beer, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TRADER_SIDS', 'TXT_KEY_BUILDING_TRADER_SIDS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_CENTAURUS_EXTRACTORS', Type
FROM Resources
WHERE Type IN ('RESOURCE_CHEESE') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_CHEESE] Cheese, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CENTAURUS_EXTRACTORS', 'TXT_KEY_BUILDING_CENTAURUS_EXTRACTORS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_HEXXON_REFINERY', Type
FROM Resources
WHERE Type IN ('RESOURCE_OBSIDIAN') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_OBSIDIAN] Obsidian, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_HEXXON_REFINERY', 'TXT_KEY_BUILDING_HEXXON_REFINERY_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_GIORGIO_ARMEIER', Type
FROM Resources
WHERE Type IN ('RESOURCE_CHAMPAGNE', 'RESOURCE_LAVENDER') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_CHAMPAGNE] Champagne, [ICON_RES_LAVENDER] Lavender, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_FIRAXITE_MATERIALS', Type
FROM Resources
WHERE Type IN ('RESOURCE_TIN') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_TIN] Tin, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_FIRAXITE_MATERIALS', 'TXT_KEY_BUILDING_FIRAXITE_MATERIALS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_TWOKAY_FOODS', Type
FROM Resources
WHERE Type IN ('RESOURCE_HONEY') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER') ;

UPDATE Language_en_US
SET Text = '[ICON_RES_HONEY] Honey, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_CIVILIZED_JEWELERS', Type
FROM Resources
WHERE Type IN ('RESOURCE_MANUSCRIPTS', 'RESOURCE_PLATINUM') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_MANUSCRIPTS] Manuscripts, [ICON_RES_PLATINUM] Platinum, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CIVILIZED_JEWELERS', 'TXT_KEY_BUILDING_CIVILIZED_JEWELERS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_POPULI_MEDICINE', Type
FROM Resources
WHERE Type IN ('RESOURCE_BIRDS_NEST', 'RESOURCE_POPPY') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_en_US
SET Text = '[ICON_RES_BIRDS_NEST] {TXT_KEY_RESOURCE_BIRDS_NEST}, [ICON_RES_POPPY] Poppy, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_POPULI_MEDICINE', 'TXT_KEY_BUILDING_POPULI_MEDICINE_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

---------------------------------------------------
-- now some custom civs

INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_POPULI_MEDICINE', Type
FROM Resources
WHERE Type IN ('RESOURCE_JAR_WILDLIFE') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_WILDLIFE');

UPDATE Language_en_US
SET Text = '[ICON_RES_JAR_WILDLIFE] Wildlife, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_POPULI_MEDICINE', 'TXT_KEY_BUILDING_POPULI_MEDICINE_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_WILDLIFE');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_TWOKAY_FOODS', Type
FROM Resources
WHERE Type IN ('RESOURCE_JAR_YAK') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_YAK');

UPDATE Language_en_US
SET Text = '[ICON_RES_JAR_YAK] Yak, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_YAK');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_GIORGIO_ARMEIER', Type
FROM Resources
WHERE Type IN ('RESOURCE_BUCCHERO') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BUCCHERO');

UPDATE Language_en_US
SET Text = '[ICON_RES_JAR_BUCCHERO] Bucchero, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BUCCHERO');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_CENTAURUS_EXTRACTORS', Type
FROM Resources
WHERE Type IN ('RESOURCE_SHRIMP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_SHRIMP');

UPDATE Language_en_US
SET Text = '[ICON_RES_SHRIMP] Shrimp, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CENTAURUS_EXTRACTORS', 'TXT_KEY_BUILDING_CENTAURUS_EXTRACTORS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_SHRIMP');

-------------------------------------------------------
-- camels, feathers, quartz, alpacas

INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_GIORGIO_ARMEIER', Type
FROM Resources
WHERE Type IN ('RESOURCE_FEATHERS') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_FEATHERS');

UPDATE Language_en_US
SET Text = '[ICON_RES_FEATHERS] Feathers, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_FEATHERS');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_TWOKAY_FOODS', Type
FROM Resources
WHERE Type IN ('RESOURCE_CAMEL') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_CAMEL');

UPDATE Language_en_US
SET Text = '[ICON_RES_CAMEL] Camel, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_CAMEL');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_FIRAXITE_MATERIALS', Type
FROM Resources
WHERE Type IN ('RESOURCE_QUARTZ') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_QUARTZ');

UPDATE Language_en_US
SET Text = '[ICON_RES_QUARTZ] Quartz, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_FIRAXITE_MATERIALS', 'TXT_KEY_BUILDING_FIRAXITE_MATERIALS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_QUARTZ');


INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
SELECT
	'CORPORATION_GIORGIO_ARMEIER', Type
FROM Resources
WHERE Type IN ('RESOURCE_ALPACA') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_ALPACA');

UPDATE Language_en_US
SET Text = '[ICON_RES_ALPACA] Alpaca, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_ALPACA');


--------------------------------------------------------------
-- compatibility section end
--------------------------------------------------------------

DELETE FROM Corporation_ResourceYieldChanges;

-- need to insert this so populi medicine populates as faith, bit inelegant but w.e.
INSERT INTO Corporation_BuildingClassYieldChanges
	(CorporationType, BuildingClassType, YieldType, YieldChange)
VALUES
	('CORPORATION_POPULI_MEDICINE', 'BUILDINGCLASS_LABORATORY', 'YIELD_FAITH', 4);

INSERT INTO Corporation_ResourceYieldChanges
	(CorporationType, ResourceType, YieldType, Yield)
SELECT DISTINCT
	a.CorporationType, a.ResourceType, b.YieldType, 5
FROM Corporation_ResourceMonopolyOrs a
INNER JOIN Corporation_BuildingClassYieldChanges b
ON a.CorporationType = b.CorporationType;

---------------------------------------
-- do general changes including most of the nerfs
---------------------------------------
-- start with the flavors

DELETE FROM Building_Flavors WHERE BuildingType = 'BUILDING_CIVILIZED_JEWELERS';
DELETE FROM Building_Flavors WHERE BuildingType = 'BUILDING_CIVILIZED_JEWELERS_HQ';

INSERT INTO Building_Flavors
	(BuildingType, FlavorType, Flavor) 
VALUES
('BUILDING_CENTAURUS_EXTRACTORS', 'FLAVOR_CULTURE', 30), 
('BUILDING_CENTAURUS_EXTRACTORS_HQ', 'FLAVOR_CULTURE', 60),

('BUILDING_CIVILIZED_JEWELERS', 'FLAVOR_GOLD', 40),
('BUILDING_CIVILIZED_JEWELERS', 'FLAVOR_CULTURE', 20),
('BUILDING_CIVILIZED_JEWELERS', 'FLAVOR_DIPLOMACY', 40),
('BUILDING_CIVILIZED_JEWELERS_HQ', 'FLAVOR_GOLD', 80),
('BUILDING_CIVILIZED_JEWELERS_HQ', 'FLAVOR_CULTURE', 40),
('BUILDING_CIVILIZED_JEWELERS_HQ', 'FLAVOR_DIPLOMACY', 80),

('BUILDING_GIORGIO_ARMEIER', 'FLAVOR_GREAT_PEOPLE', 50),
('BUILDING_GIORGIO_ARMEIER_HQ', 'FLAVOR_GREAT_PEOPLE', 100),

('BUILDING_HEXXON_REFINERY', 'FLAVOR_EXPANSION', 20),
('BUILDING_HEXXON_REFINERY_HQ', 'FLAVOR_EXPANSION', 40),

('BUILDING_TRADER_SIDS', 'FLAVOR_DIPLOMACY', 50),
('BUILDING_TRADER_SIDS_HQ', 'FLAVOR_DIPLOMACY', 100),

('BUILDING_POPULI_MEDICINE', 'FLAVOR_RELIGION', 50),
('BUILDING_POPULI_MEDICINE', 'FLAVOR_DIPLOMACY', 25),
('BUILDING_POPULI_MEDICINE', 'FLAVOR_HAPPINESS', 40),
('BUILDING_POPULI_MEDICINE_HQ', 'FLAVOR_RELIGION', 100),
('BUILDING_POPULI_MEDICINE_HQ', 'FLAVOR_DIPLOMACY', 50),
('BUILDING_POPULI_MEDICINE_HQ', 'FLAVOR_HAPPINESS', 80);

-- franchises cost money

UPDATE Buildings
SET GoldMaintenance = 6
WHERE BuildingClass IN (
	SELECT FranchiseBuildingClass FROM Corporations
);

-- remove the monopoly restriction, instead local on HQ

INSERT INTO Building_LocalResourceOrs 
	(BuildingType, ResourceType)
SELECT
	b.Type, a.ResourceType
FROM Corporation_ResourceMonopolyOrs a
INNER JOIN Corporations c ON a.CorporationType = c.Type
INNER JOIN BuildingClasses bc ON c.HeadquartersBuildingClass = bc.Type
INNER JOIN Buildings b ON bc.DefaultBuilding = b.Type;

DELETE FROM Corporation_ResourceMonopolyOrs;

-- franchise bonus increase, and also on offices

UPDATE Corporation_ResourceYieldChanges SET Yield = 3 WHERE YieldType IN ('YIELD_CULTURE', 'YIELD_SCIENCE', 'YIELD_FAITH');
UPDATE Corporation_ResourceYieldChanges SET Yield = 5 WHERE YieldType IN ('YIELD_FOOD', 'YIELD_PRODUCTION', 'YIELD_GOLD', 'YIELD_GOLDEN_AGE_POINTS');

INSERT INTO Building_ResourceYieldChanges
	(BuildingType, ResourceType, YieldType, Yield)
SELECT
	b.Type, a.ResourceType, a.YieldType, a.Yield
FROM Corporation_ResourceYieldChanges a
INNER JOIN Corporations c ON a.CorporationType = c.Type
INNER JOIN BuildingClasses bc ON c.OfficeBuildingClass = bc.Type
INNER JOIN Buildings b ON bc.DefaultBuilding = b.Type;

-- nerf all trade route yield modifiers to 3%

UPDATE Corporation_TradeRouteCityYield SET Yield = 3;

INSERT INTO Corporation_TradeRouteCityYield 
	(CorporationType, YieldType, Yield)
VALUES
	('CORPORATION_POPULI_MEDICINE', 'YIELD_FAITH', 3);

-- nerf all stacking office bonuses 

UPDATE Building_YieldPerFranchise SET Yield = 1;

-- +2 on gold and food
UPDATE Building_YieldPerFranchise SET Yield = 2 WHERE YieldType IN ('YIELD_FOOD', 'YIELD_GOLD');

-- assign the missing 2
INSERT INTO Building_YieldPerFranchise
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_POPULI_MEDICINE', 'YIELD_FAITH', 1),
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_GOLDEN_AGE_POINTS', 2),
	('BUILDING_HEXXON_REFINERY', 'YIELD_CULTURE_LOCAL', 3);

UPDATE Buildings SET 
	GPRateModifierPerXFranchises = 0,
	GoldenAgeModifier = 0,
	GreatPeopleRateModifier = 0
WHERE Type = 'BUILDING_CIVILIZED_JEWELERS';

UPDATE Buildings SET GPRateModifierPerXFranchises = 2 WHERE Type = 'BUILDING_GIORGIO_ARMEIER';

UPDATE Buildings SET EmpireSizeModifierReductionGlobal = -2 WHERE Type = 'BUILDING_TWOKAY_FOODS';

-- sweep and reassign all specialist changes

DELETE FROM Corporation_SpecialistYieldChanges;

INSERT INTO Corporation_SpecialistYieldChanges
	(CorporationType, SpecialistType, YieldType, Yield)
VALUES
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_ARTIST', 'YIELD_CULTURE', 2),
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_ARTIST', 'YIELD_GOLD', 2),
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_ARTIST', 'YIELD_TOURISM', 2),	
	('CORPORATION_FIRAXITE_MATERIALS', 'SPECIALIST_SCIENTIST', 'YIELD_PRODUCTION', 2),
	('CORPORATION_HEXXON_REFINERY', 'SPECIALIST_ENGINEER', 'YIELD_SCIENCE', 2),
	('CORPORATION_TRADER_SIDS', 'SPECIALIST_MERCHANT', 'YIELD_FOOD', 3),
	('CORPORATION_POPULI_MEDICINE', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLD', 3);

INSERT INTO Corporation_SpecialistYieldChanges
	(CorporationType, SpecialistType, YieldType, Yield)
SELECT
	'CORPORATION_CENTAURUS_EXTRACTORS', Type, 'YIELD_GOLD', 1
FROM Specialists
UNION ALL
SELECT
	'CORPORATION_CIVILIZED_JEWELERS', Type, 'YIELD_TOURISM', 1
FROM Specialists;

-- sweep and reassign all building changes

DELETE FROM Corporation_BuildingClassYieldChanges;

INSERT INTO Corporation_BuildingClassYieldChanges
	(CorporationType, BuildingClassType, YieldType, YieldChange)
VALUES
	('CORPORATION_TRADER_SIDS', 'BUILDINGCLASS_BROADCAST_TOWER', 'YIELD_GOLD', 4),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'BUILDINGCLASS_MINEFIELD', 'YIELD_PRODUCTION', 8),
	('CORPORATION_HEXXON_REFINERY', 'BUILDINGCLASS_REFINERY', 'YIELD_PRODUCTION', 5),
	('CORPORATION_HEXXON_REFINERY', 'BUILDINGCLASS_REFINERY', 'YIELD_SCIENCE', 5),
	('CORPORATION_HEXXON_REFINERY', 'BUILDINGCLASS_REFINERY', 'YIELD_CULTURE_LOCAL', 5),
	('CORPORATION_GIORGIO_ARMEIER', 'BUILDINGCLASS_VP_MALL', 'YIELD_CULTURE', 4),
	('CORPORATION_FIRAXITE_MATERIALS', 'BUILDINGCLASS_STOCK_EXCHANGE', 'YIELD_SCIENCE', 3),
	('CORPORATION_TWOKAY_FOODS', 'BUILDINGCLASS_AGRIBUSINESS', 'YIELD_FOOD', 5),
	('CORPORATION_CIVILIZED_JEWELERS', 'BUILDINGCLASS_AIRPORT', 'YIELD_TOURISM', 6),
	('CORPORATION_POPULI_MEDICINE', 'BUILDINGCLASS_HOSPITAL', 'YIELD_FAITH', 3);

---------------------------------------
-- Specific Changes
---------------------------------------
---------------------------------------
-- HQ/Corps first

UPDATE Corporations
SET
	TradeRoutesInvulnerable = 0
WHERE Type = 'CORPORATION_FIRAXITE_MATERIALS';

INSERT INTO Building_ResourceQuantityPerXFranchises
	(BuildingType, ResourceType, NumFranchises)
VALUES
	('BUILDING_FIRAXITE_MATERIALS_HQ', 'RESOURCE_IRON', 1),
	('BUILDING_FIRAXITE_MATERIALS_HQ', 'RESOURCE_ALUMINUM', 2);

DELETE FROM Corporation_TradeRouteMod WHERE CorporationType = 'CORPORATION_FIRAXITE_MATERIALS';

INSERT INTO Corporation_TradeRouteCityYield 
	(CorporationType, YieldType, Yield)
VALUES
	('CORPORATION_FIRAXITE_MATERIALS', 'YIELD_SCIENCE', 3);  -- match the % balance above

INSERT INTO Building_ResourceQuantityPerXFranchises
	(BuildingType, ResourceType, NumFranchises)
VALUES
	('BUILDING_HEXXON_REFINERY_HQ', 'RESOURCE_COAL', 1),
	('BUILDING_HEXXON_REFINERY_HQ', 'RESOURCE_OIL', 1);

DELETE FROM Building_ResourceQuantityPerXFranchises WHERE BuildingType = 'BUILDING_HEXXON_REFINERY';

INSERT INTO Corporation_NumFreeResource
	(CorporationType, ResourceType, NumResource)
VALUES
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_OIL', 5),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_COAL', 5);

UPDATE Corporation_ResourceYieldChanges SET 
YieldType = 'YIELD_CULTURE_LOCAL',
Yield = 8 
WHERE CorporationType = 'CORPORATION_HEXXON_REFINERY';

UPDATE Building_ResourceYieldChanges SET 
YieldType = 'YIELD_CULTURE_LOCAL',
Yield = 8
WHERE BuildingType = 'BUILDING_HEXXON_REFINERY';


INSERT INTO Building_ResourceQuantityPerXFranchises
	(BuildingType, ResourceType, NumFranchises)
VALUES
	('BUILDING_TWOKAY_FOODS_HQ', 'RESOURCE_HORSE', 1);

UPDATE Corporations 
SET
	TradeRouteTargetBonus = 5
WHERE Type = 'CORPORATION_GIORGIO_ARMEIER';

UPDATE Corporations 
SET
	NumFreeTradeRoutes = 2
WHERE Type = 'CORPORATION_CIVILIZED_JEWELERS';

DELETE FROM Corporation_TradeRouteCityYield WHERE CorporationType = 'CORPORATION_CENTAURUS_EXTRACTORS';

INSERT INTO Corporation_TradeRouteMod
	(CorporationType, YieldType, Yield)
VALUES
	('CORPORATION_CENTAURUS_EXTRACTORS', 'YIELD_SCIENCE', 50);

UPDATE Corporations 
SET
	NumFreeTradeRoutes = 3
WHERE Type = 'CORPORATION_TRADER_SIDS';

UPDATE Corporations 
SET
	TradeRouteRecipientBonus = 5
WHERE Type = 'CORPORATION_POPULI_MEDICINE';

---------------------------------------
-- now do the offices
-- do some shared table updates first

INSERT INTO Building_YieldFromInternalTREnd
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_HEXXON_REFINERY', 'YIELD_CULTURE_LOCAL', 100),
	('BUILDING_GIORGIO_ARMEIER', 'YIELD_TOURISM', 80),	
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_GOLDEN_AGE_POINTS', 75),		
	('BUILDING_TRADER_SIDS', 'YIELD_GOLD', 50),	
	('BUILDING_POPULI_MEDICINE', 'YIELD_CULTURE', 40),
	('BUILDING_FIRAXITE_MATERIALS', 'YIELD_SCIENCE', 40);

INSERT INTO Building_YieldFromInternalTR
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_CENTAURUS_EXTRACTORS', 'YIELD_PRODUCTION', 6),
	('BUILDING_TWOKAY_FOODS', 'YIELD_FOOD', 10);

-- now the really specific things

UPDATE Buildings SET 
	BuildingProductionModifier = 10,
	EnhancedYieldTech = 'TECH_ELECTRONICS'
WHERE Type = 'BUILDING_FIRAXITE_MATERIALS';

INSERT INTO Building_TechEnhancedYieldChanges
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_FIRAXITE_MATERIALS', 'YIELD_SCIENCE', 8);

INSERT INTO Building_YieldFromConstruction
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_FIRAXITE_MATERIALS', 'YIELD_SCIENCE', 10);

DELETE FROM Corporation_UnitResourceProductionModifier WHERE CorporationType = 'CORPORATION_HEXXON_REFINERY';

INSERT INTO Building_YieldFromUnitProduction
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_HEXXON_REFINERY', 'YIELD_SCIENCE', 25);


DELETE FROM Building_YieldModifiers WHERE BuildingType = 'BUILDING_TWOKAY_FOODS';

UPDATE Buildings SET
DistressFlatReductionGlobal = 0,
PovertyFlatReductionGlobal = 0,
IlliteracyFlatReductionGlobal = 0,
BoredomFlatReductionGlobal = 0,
ReligiousUnrestFlatReductionGlobal = 0,
DistressFlatReduction = 1,
PovertyFlatReduction = 1,
IlliteracyFlatReduction = 1,
BoredomFlatReduction = 1,
ReligiousUnrestFlatReduction = 1
WHERE Type = 'BUILDING_TWOKAY_FOODS';


UPDATE Buildings SET
	SpecialistType = 'SPECIALIST_ARTIST',
	SpecialistCount = 1,
	IlliteracyFlatReduction = 0,
	BoredomFlatReduction = 0
WHERE Type = 'BUILDING_GIORGIO_ARMEIER';


INSERT INTO Building_YieldPerFriend
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_GOLD', 1);

INSERT INTO Building_YieldPerAlly
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_GOLD', 2),
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_TOURISM', 1);

INSERT INTO Building_GoldenAgeYieldMod
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_GOLD', 10),
	('BUILDING_CIVILIZED_JEWELERS', 'YIELD_TOURISM', 10);


INSERT INTO Building_SeaPlotYieldChanges
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_CENTAURUS_EXTRACTORS', 'YIELD_CULTURE', 1);
-- it already has the production

INSERT INTO Building_SeaResourceYieldChanges
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_CENTAURUS_EXTRACTORS', 'YIELD_SCIENCE', 1),	
	('BUILDING_CENTAURUS_EXTRACTORS', 'YIELD_CULTURE', 1);


UPDATE Buildings SET 
	TradeRouteRecipientBonus = 4,
	CityStateTradeRouteProductionModifier = 2
WHERE Type = 'BUILDING_TRADER_SIDS';


UPDATE Buildings SET 
	MinorFriendshipChange = 15,
	HappinessPerXPolicies = 6
WHERE Type = 'BUILDING_POPULI_MEDICINE';
