--------------------------------------------------------------
-- 자연 불가사의 더미 데이터
-- 2020년 5월 11일: 생성, adan_eslavo
--============================================--
-- 임시 수정
--============================================--
-- 여러 타일에 걸친 자연 불가사의는 새로운 테이블 없이는 균형을 맞출 수 없으므로, 추가될 때까지 이 결의안은 삭제되어야 합니다.
DELETE FROM Resolutions WHERE Type = 'RESOLUTION_NATURAL_HERITAGE_SITES';
--============================================--
-- 진급
--============================================--
INSERT INTO Language_ko_KR 
			(Tag,										Text) 
VALUES		('TXT_KEY_PROMOTION_KAILASH',				'마하프라스나니카 파르바'),
			('TXT_KEY_PROMOTION_KAILASH_HELP',			'[COLOR:255:230:85:255]언덕에서[ENDCOLOR] [ICON_MOVES]이동력 두 배.'),
			('TXT_KEY_PROMOTION_ULURU',					'오래된 부족'),
			('TXT_KEY_PROMOTION_ULURU_HELP',			'[COLOR:255:230:85:255]외교 사절 임무 후[ENDCOLOR] [ICON_INFLUENCE] 영향력 +10.'),
			('TXT_KEY_PROMOTION_SOLOMONS_MINES',		'왕을 위하여!'),
			('TXT_KEY_PROMOTION_SOLOMONS_MINES_HELP',	'+25% [ICON_WORKER] 작업 속도.'),	
			('TXT_KEY_PROMOTION_BERMUDA_TRIANGLE',		'시간과 공간 속에서 길을 잃다'),
			('TXT_KEY_PROMOTION_BERMUDA_TRIANGLE_HELP',	'-3[ICON_MOVES] 이동 포인트. [COLOR_NEGATIVE_TEXT]진급은 3턴 동안 지속됩니다[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_DALLOL',				'폭발성 혼합물'),
			('TXT_KEY_PROMOTION_DALLOL_HELP',			'+10%[ICON_RANGE_STRENGTH] 공격 원거리 전투력.'),
			('TXT_KEY_PROMOTION_CAUSEWAY',				'호기심'),
			('TXT_KEY_PROMOTION_CAUSEWAY_HELP',			'+1[ICON_MOVES] 이동 포인트. +10% [ICON_WORKER] 작업 속도.'),
			('TXT_KEY_PROMOTION_MT_EVEREST',			'세계의 지붕'),
			('TXT_KEY_PROMOTION_MT_EVEREST_HELP',		'유닛이 [COLOR:255:230:85:255]타일을 드러낼 때마다[ENDCOLOR] [ICON_TOURISM] 관광을 얻습니다.'),
			('TXT_KEY_PROMOTION_HA_LONG',				'강림하는 용'),
			('TXT_KEY_PROMOTION_HA_LONG_HELP',			'적 유닛의 [ICON_STRENGTH] 전투력의 80%를 [COLOR:255:230:85:255]처치 시[ENDCOLOR] [ICON_CULTURE] 문화로 얻습니다. +20%[ICON_STRENGTH] 방어 전투력'),
			('TXT_KEY_PROMOTION_AURORA',				'레본툴레트'),
			('TXT_KEY_PROMOTION_AURORA_HELP',			'[COLOR:255:230:85:255]설원에서[ENDCOLOR] [ICON_MOVES]이동력 두 배.');
			
INSERT INTO UnitPromotions 
			(Type,							Description,							Help,										Sound,				CannotBeChosen, LostWithUpgrade,	PortraitIndex,	IconAtlas,						PediaType,			PediaEntry) 
VALUES		('PROMOTION_KAILASH',			'TXT_KEY_PROMOTION_KAILASH',			'TXT_KEY_PROMOTION_KAILASH_HELP',			'AS2D_IF_LEVELUP',	1,				0,					12,				'promoVP_atlas_03',				'PEDIA_CIVILIAN',	'TXT_KEY_PROMOTION_KAILASH'),
			('PROMOTION_ULURU',				'TXT_KEY_PROMOTION_ULURU',				'TXT_KEY_PROMOTION_ULURU_HELP',				'AS2D_IF_LEVELUP',	1,				0,					8,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_DIPLO',		'TXT_KEY_PROMOTION_ULURU'),
			('PROMOTION_SOLOMONS_MINES',	'TXT_KEY_PROMOTION_SOLOMONS_MINES',		'TXT_KEY_PROMOTION_SOLOMONS_MINES_HELP',	'AS2D_IF_LEVELUP',	1,				0,					4,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_CIVILIAN',	'TXT_KEY_PROMOTION_SOLOMONS_MINES'),
			('PROMOTION_BERMUDA_TRIANGLE',	'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE',	'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE_HELP',	'AS2D_IF_LEVELUP',	1,				0,					9,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SHARED',		'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE'),
			('PROMOTION_DALLOL',			'TXT_KEY_PROMOTION_DALLOL',				'TXT_KEY_PROMOTION_DALLOL_HELP',			'AS2D_IF_LEVELUP',	1,				0,					10,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SIEGE',		'TXT_KEY_PROMOTION_DALLOL'),
			('PROMOTION_CAUSEWAY',			'TXT_KEY_PROMOTION_CAUSEWAY',			'TXT_KEY_PROMOTION_CAUSEWAY_HELP',			'AS2D_IF_LEVELUP',	1,				0,					17,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_CIVILIAN',	'TXT_KEY_PROMOTION_CAUSEWAY'),
			('PROMOTION_MT_EVEREST',		'TXT_KEY_PROMOTION_MT_EVEREST',			'TXT_KEY_PROMOTION_MT_EVEREST_HELP',		'AS2D_IF_LEVELUP',	1,				0,					19,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SCOUTING',	'TXT_KEY_PROMOTION_MT_EVEREST'),
			('PROMOTION_HA_LONG',			'TXT_KEY_PROMOTION_HA_LONG',			'TXT_KEY_PROMOTION_HA_LONG_HELP',			'AS2D_IF_LEVELUP',	1,				0,					18,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_NAVAL',		'TXT_KEY_PROMOTION_HA_LONG'),
			('PROMOTION_AURORA',			'TXT_KEY_PROMOTION_AURORA',				'TXT_KEY_PROMOTION_AURORA_HELP',			'AS2D_IF_LEVELUP',	1,				0,					21,				'PROMOTION_MORE_WONDERS_ATLAS',	'PEDIA_SHARED',		'TXT_KEY_PROMOTION_AURORA');

UPDATE UnitPromotions SET DiploMissionInfluence = 10 WHERE Type = 'PROMOTION_ULURU';
UPDATE UnitPromotions SET WorkRateMod = 25 WHERE Type = 'PROMOTION_SOLOMONS_MINES';
UPDATE UnitPromotions SET ExtraNavalMovement = -3, PromotionDuration = 3 WHERE Type = 'PROMOTION_BERMUDA_TRIANGLE';
UPDATE UnitPromotions SET RangedAttackModifier = 10 WHERE Type = 'PROMOTION_DALLOL';
UPDATE UnitPromotions SET WorkRateMod = 10, MovesChange = 1 WHERE Type = 'PROMOTION_CAUSEWAY';
UPDATE UnitPromotions SET OpenDefense = 20, RoughDefense = 20 WHERE Type = 'PROMOTION_HA_LONG';

INSERT INTO UnitPromotions_Terrains
			(PromotionType,			TerrainType,	DoubleMove)
VALUES		('PROMOTION_KAILASH',	'TERRAIN_HILL',	1),
			('PROMOTION_AURORA',	'TERRAIN_SNOW',	1);

INSERT INTO UnitPromotions_YieldFromScouting
			(PromotionType,				YieldType,			Yield)
VALUES		('PROMOTION_MT_EVEREST',	'YIELD_TOURISM',	1);

INSERT INTO UnitPromotions_YieldFromKills
			(PromotionType,			YieldType,			Yield)
VALUES		('PROMOTION_HA_LONG',	'YIELD_CULTURE',	80);

DELETE FROM UnitPromotions_CivilianUnitType WHERE PromotionType = 'PROMOTION_SACRED_STEPS';

UPDATE UnitPromotions SET VisibilityChange = 1 WHERE Type = 'PROMOTION_ALTITUDE_TRAINING';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SCOUTING' WHERE type = 'PROMOTION_ALTITUDE_TRAINING';
UPDATE Language_ko_KR SET Text = '+1[ICON_VIEW_CITY] 시야. '||Text WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_ALTITUDE_TRAINING';

INSERT INTO UnitPromotions_UnitCombats
			(PromotionType,					UnitCombatType)
VALUES		('PROMOTION_KAILASH',			'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_ULURU',				'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_SOLOMONS_MINES',	'UNITCOMBAT_WORKER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_NAVALMELEE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_NAVALRANGED'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SUBMARINE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_CARRIER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_CARGO'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_WORKBOAT'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_MELEE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_RECON'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_ARCHER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_MOUNTED'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SIEGE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_GUN'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_ARMOR'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_INQUISITOR'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SETTLER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_WORKER'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SPECIAL_PEOPLE'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_SPACESHIP_PART'),
			('PROMOTION_BERMUDA_TRIANGLE',	'UNITCOMBAT_ARCHAEOLOGIST'),
			('PROMOTION_DALLOL',			'UNITCOMBAT_SIEGE'),
			('PROMOTION_ALTITUDE_TRAINING',	'UNITCOMBAT_RECON'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_WORKER'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_WORKBOAT'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_SETTLER'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_SPECIAL_PEOPLE'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_SPACESHIP_PART'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_INQUISITOR'),
			('PROMOTION_SACRED_STEPS',		'UNITCOMBAT_ARCHAEOLOGIST'),
			('PROMOTION_CAUSEWAY',			'UNITCOMBAT_ARCHAEOLOGIST'),
			('PROMOTION_MT_EVEREST',		'UNITCOMBAT_RECON'),
			('PROMOTION_HA_LONG',			'UNITCOMBAT_NAVALMELEE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_MELEE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_RECON'),
			('PROMOTION_AURORA',			'UNITCOMBAT_ARCHER'),
			('PROMOTION_AURORA',			'UNITCOMBAT_MOUNTED'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SIEGE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_GUN'),
			('PROMOTION_AURORA',			'UNITCOMBAT_ARMOR'),
			('PROMOTION_AURORA',			'UNITCOMBAT_DIPLOMACY'),
			('PROMOTION_AURORA',			'UNITCOMBAT_MISSIONARY'),
			('PROMOTION_AURORA',			'UNITCOMBAT_INQUISITOR'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SETTLER'),
			('PROMOTION_AURORA',			'UNITCOMBAT_WORKER'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SPECIAL_PEOPLE'),
			('PROMOTION_AURORA',			'UNITCOMBAT_SPACESHIP_PART'),
			('PROMOTION_AURORA',			'UNITCOMBAT_ARCHAEOLOGIST');

UPDATE UnitPromotions SET FlagPromoOrder = 4, OrderPriority = 4 WHERE Type = 'PROMOTION_BERMUDA_TRIANGLE';
			
UPDATE UnitPromotions SET FlagPromoOrder = 70, OrderPriority = 70 WHERE Type = 'PROMOTION_EVERLASTING_YOUTH';
UPDATE UnitPromotions SET FlagPromoOrder = 71, OrderPriority = 71 WHERE Type = 'PROMOTION_HA_LONG';
UPDATE UnitPromotions SET FlagPromoOrder = 72, OrderPriority = 72 WHERE Type = 'PROMOTION_SOLOMONS_MINES';
UPDATE UnitPromotions SET FlagPromoOrder = 73, OrderPriority = 73 WHERE Type = 'PROMOTION_AURORA';

UPDATE UnitPromotions SET FlagPromoOrder = 250, OrderPriority = 250 WHERE Type = 'PROMOTION_DALLOL';
UPDATE UnitPromotions SET FlagPromoOrder = 251, OrderPriority = 251 WHERE Type = 'PROMOTION_ALTITUDE_TRAINING';

UPDATE UnitPromotions SET FlagPromoOrder = 252, OrderPriority = 252 WHERE Type = 'PROMOTION_SACRED_STEPS';
UPDATE UnitPromotions SET FlagPromoOrder = 253, OrderPriority = 253 WHERE Type = 'PROMOTION_KAILASH';
UPDATE UnitPromotions SET FlagPromoOrder = 254, OrderPriority = 254 WHERE Type = 'PROMOTION_ULURU';
UPDATE UnitPromotions SET FlagPromoOrder = 255, OrderPriority = 255 WHERE Type = 'PROMOTION_CAUSEWAY';
UPDATE UnitPromotions SET FlagPromoOrder = 256, OrderPriority = 256 WHERE Type = 'PROMOTION_MT_EVEREST';
--============================================--
-- 위대한 작품
--============================================--
INSERT INTO GreatWorks
			(Type,						Description,					GreatWorkClassType,	Audio,							Image,						Quote) 
VALUES		('GREAT_WORK_MT_PAEKTU',	'TXT_KEY_GREAT_WORK_MT_PAEKTU',	'GREAT_WORK_ART',	'AS2D_GREAT_ARTIST_ARTWORK',	'Great_Work_Mt_Paektu.dds',	NULL);

INSERT INTO Language_ko_KR 
			(Tag,									Text) 
VALUES		('TXT_KEY_GREAT_WORK_MT_PAEKTU',		'백두산 정상에 선 김일성과 김정일');
--============================================--
-- 건물
--============================================--
INSERT INTO BuildingClasses 
			(Type,								Description,						DefaultBuilding)
VALUES		('BUILDINGCLASS_MT_PAEKTU',			'TXT_KEY_BUILDING_MT_PAEKTU',		'BUILDING_MT_PAEKTU'),
			('BUILDINGCLASS_SCUBA_RESORT',		'TXT_KEY_BUILDING_SCUBA_RESORT',	'BUILDING_SCUBA_RESORT'),
			('BUILDINGCLASS_BATHYSCAPHE_BAY',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY',	'BUILDING_BATHYSCAPHE_BAY'),
			('BUILDINGCLASS_OCEAN_FACILITY',	'TXT_KEY_BUILDING_OCEAN_FACILITY',	'BUILDING_OCEAN_FACILITY');

INSERT INTO Buildings
			(Type,							BuildingClass,						Description,						Civilopedia,								Help,										IconAtlas,							PortraitIndex,	PrereqTech,				Cost,	FaithCost,	NukeImmune, ConquestProb,	IsDummy)
VALUES		('BUILDING_MT_PAEKTU',			'BUILDINGCLASS_MT_PAEKTU',			'TXT_KEY_BUILDING_MT_PAEKTU',		'TXT_KEY_BUILDING_MT_PAEKTU_PEDIA',			'TXT_KEY_BUILDING_MT_PAEKTU_HELP',			'NATURAL_WONDERS_BUILDINGS_ATLAS',	0,				NULL,					-1,		0,			1,          100,			0),
			('BUILDING_SCUBA_RESORT',		'BUILDINGCLASS_SCUBA_RESORT',		'TXT_KEY_BUILDING_SCUBA_RESORT',	'TXT_KEY_BUILDING_SCUBA_RESORT_PEDIA',		'TXT_KEY_BUILDING_SCUBA_RESORT_HELP',		'NATURAL_WONDERS_BUILDINGS_ATLAS',	1,				'TECH_PLASTIC',			1000,	0,			0,          66,				0),
			('BUILDING_BATHYSCAPHE_BAY',	'BUILDINGCLASS_BATHYSCAPHE_BAY',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY_PEDIA',	'TXT_KEY_BUILDING_BATHYSCAPHE_BAY_HELP',	'NATURAL_WONDERS_BUILDINGS_ATLAS',	2,				'TECH_REFRIGERATION',   1000,	0,			0,          66,				0),
			('BUILDING_OCEAN_FACILITY',		'BUILDINGCLASS_OCEAN_FACILITY',		'TXT_KEY_BUILDING_OCEAN_FACILITY',	'TXT_KEY_BUILDING_OCEAN_FACILITY_PEDIA',	'TXT_KEY_BUILDING_OCEAN_FACILITY_HELP',		'NATURAL_WONDERS_BUILDINGS_ATLAS',	3,				'TECH_BIOLOGY',			1000,	0,			0,          66,				0);

UPDATE Buildings SET GreatWorkSlotType = 'GREAT_WORK_SLOT_ART_ARTIFACT', GreatWorkCount = 1, FreeGreatWork = 'GREAT_WORK_MT_PAEKTU', SpecialistType = 'SPECIALIST_MUSICIAN', GreatPeopleRateChange = 1 WHERE Type = 'BUILDING_MT_PAEKTU';
UPDATE Buildings SET Water = 1, MinAreaSize = 10 WHERE Type = 'BUILDING_SCUBA_RESORT';
UPDATE Buildings SET Water = 1, MinAreaSize = 10 WHERE Type = 'BUILDING_BATHYSCAPHE_BAY';
UPDATE Buildings SET Water = 1, MinAreaSize = 10 WHERE Type = 'BUILDING_OCEAN_FACILITY';

INSERT INTO Language_ko_KR 
			(Tag,										Text) 
VALUES		('TXT_KEY_BUILDING_MT_PAEKTU',				'산 아래 태어난 자의 제단'),
			('TXT_KEY_BUILDING_MT_PAEKTU_PEDIA',		'작성 필요'),
			('TXT_KEY_BUILDING_MT_PAEKTU_HELP',			'+1 [ICON_GREAT_PEOPLE] 위대한 음악가 포인트. [ICON_GREAT_WORK] 위대한 예술품 슬롯 1개를 가지며, [ICON_GREAT_WORK] [COLOR_CULTURE_STORED]백두산 정상에 선 김일성과 김정일[ENDCOLOR]로 시작합니다.'),
			('TXT_KEY_BUILDING_SCUBA_RESORT',			'스쿠버 다이빙 리조트'),
			('TXT_KEY_BUILDING_SCUBA_RESORT_PEDIA',		'작성 필요'),
			('TXT_KEY_BUILDING_SCUBA_RESORT_HELP',		'이 도시가 점유한 환초에서 [ICON_GOLD] 골드 +1 및 [ICON_TOURISM] 관광 +1. 이 도시가 점유한 해양 타일에서 [ICON_GOLD] 골드 +1 및 [ICON_RESEARCH] 과학 +1.'),
			('TXT_KEY_BUILDING_BATHYSCAPHE_BAY',		'잠수정 정박소'),
			('TXT_KEY_BUILDING_BATHYSCAPHE_BAY_PEDIA',	'작성 필요'),
			('TXT_KEY_BUILDING_BATHYSCAPHE_BAY_HELP',	'도시에서 [COLOR_POSITIVE_TEXT]잠수함[ENDCOLOR] 건설 시 [ICON_PRODUCTION] 생산력 +35%.'),
			('TXT_KEY_BUILDING_OCEAN_FACILITY',			'심해 연구 시설'),
			('TXT_KEY_BUILDING_OCEAN_FACILITY_PEDIA',	'작성 필요'),
			('TXT_KEY_BUILDING_OCEAN_FACILITY_HELP',	'이 도시가 점유한 해양 타일에서 [ICON_FOOD] 식량 +1 및 [ICON_RESEARCH] 과학 +1.[NEWLINE][NEWLINE]이 도시의 모든 해양 자원은 [ICON_FOOD] 식량 +1을 얻습니다.');

INSERT INTO Building_YieldChanges 
			(BuildingType,					YieldType,					Yield) 
VALUES		('BUILDING_MT_PAEKTU',			'YIELD_FAITH',				3),
			('BUILDING_MT_PAEKTU',			'YIELD_GOLDEN_AGE_POINTS',	3),
			('BUILDING_SCUBA_RESORT',		'YIELD_GOLD',				2),
			('BUILDING_SCUBA_RESORT',		'YIELD_SCIENCE',			1),
			('BUILDING_SCUBA_RESORT',		'YIELD_TOURISM',			1),
			('BUILDING_BATHYSCAPHE_BAY',	'YIELD_PRODUCTION',			2),
			('BUILDING_BATHYSCAPHE_BAY',	'YIELD_SCIENCE',			2),
			('BUILDING_OCEAN_FACILITY',		'YIELD_SCIENCE',			5);

INSERT INTO Building_FeatureYieldChanges
			(BuildingType,				FeatureType,		YieldType,			Yield) 
VALUES		('BUILDING_SCUBA_RESORT',	'FEATURE_ATOLL',	'YIELD_GOLD',		1),
			('BUILDING_SCUBA_RESORT',	'FEATURE_ATOLL',	'YIELD_TOURISM',	1);

INSERT INTO Building_TerrainYieldChanges
			(BuildingType,				TerrainType,		YieldType,			Yield) 
VALUES		('BUILDING_SCUBA_RESORT',	'TERRAIN_OCEAN',	'YIELD_GOLD',		1),
			('BUILDING_SCUBA_RESORT',	'TERRAIN_OCEAN',	'YIELD_SCIENCE',	1),
			('BUILDING_OCEAN_FACILITY',	'TERRAIN_OCEAN',	'YIELD_FOOD',		1),
			('BUILDING_OCEAN_FACILITY',	'TERRAIN_OCEAN',	'YIELD_SCIENCE',	1);

INSERT INTO Building_UnitCombatProductionModifiers
			(BuildingType,					UnitCombatType,				Modifier) 
VALUES		('BUILDING_BATHYSCAPHE_BAY',	'UNITCOMBAT_SUBMARINE',		35);

INSERT INTO Building_ResourceYieldChanges	(BuildingType,				ResourceType,	YieldType,		Yield)
SELECT DISTINCT								'BUILDING_OCEAN_FACILITY',	Type,			'YIELD_FOOD',	1
FROM Resources WHERE TechCityTrade = 'TECH_SAILING';
--============================================--
-- 더미 건물
--============================================--
INSERT INTO BuildingClasses 
			(Type,									Description,								DefaultBuilding)
VALUES		('BUILDINGCLASS_SALAR_A_DUMMY',			'TXT_KEY_BUILDING_SALAR_A_DUMMY',			'BUILDING_SALAR_A_DUMMY'),
			('BUILDINGCLASS_SALAR_B_DUMMY',			'TXT_KEY_BUILDING_SALAR_B_DUMMY',			'BUILDING_SALAR_B_DUMMY'),
			('BUILDINGCLASS_EL_DORADO_DUMMY',		'TXT_KEY_BUILDING_EL_DORADO_DUMMY',			'BUILDING_EL_DORADO_DUMMY'),
			('BUILDINGCLASS_POTOSI_DUMMY',			'TXT_KEY_BUILDING_POTOSI_DUMMY',			'BUILDING_POTOSI_DUMMY'),
			('BUILDINGCLASS_CRATER_DUMMY',			'TXT_KEY_BUILDING_CRATER_DUMMY',			'BUILDING_CRATER_DUMMY'),
			('BUILDINGCLASS_MESA_DUMMY',			'TXT_KEY_BUILDING_MESA_DUMMY',				'BUILDING_MESA_DUMMY'),
			('BUILDINGCLASS_SOLOMONS_MINES_DUMMY',	'TXT_KEY_BUILDING_SOLOMONS_MINES_DUMMY',	'BUILDING_SOLOMONS_MINES_DUMMY'),
			('BUILDINGCLASS_VOLCANO_DUMMY',			'TXT_KEY_BUILDING_VOLCANO_DUMMY',			'BUILDING_VOLCANO_DUMMY'),
			('BUILDINGCLASS_FUJI_1_DUMMY',			'TXT_KEY_BUILDING_FUJI_DUMMY',				'BUILDING_FUJI_1_DUMMY'),
			('BUILDINGCLASS_FUJI_2_DUMMY',			'TXT_KEY_BUILDING_FUJI_DUMMY',				'BUILDING_FUJI_2_DUMMY'),
			('BUILDINGCLASS_FUJI_3_DUMMY',			'TXT_KEY_BUILDING_FUJI_DUMMY',				'BUILDING_FUJI_3_DUMMY'),
			('BUILDINGCLASS_MT_SINAI_DUMMY',		'TXT_KEY_BUILDING_MT_SINAI_DUMMY',			'BUILDING_MT_SINAI_DUMMY'),
			('BUILDINGCLASS_GEYSER_DUMMY',			'TXT_KEY_BUILDING_GEYSER_DUMMY',			'BUILDING_GEYSER_DUMMY'),
			('BUILDINGCLASS_MT_EVEREST_DUMMY',		'TXT_KEY_BUILDING_MT_EVEREST_DUMMY',		'BUILDING_MT_EVEREST_DUMMY'),
			('BUILDINGCLASS_NEW_REEF_A_DUMMY',		'TXT_KEY_BUILDING_REEF_DUMMY',				'BUILDING_NEW_REEF_A_DUMMY'),
			('BUILDINGCLASS_NEW_REEF_B_DUMMY',		'TXT_KEY_BUILDING_REEF_DUMMY',				'BUILDING_NEW_REEF_B_DUMMY'),
			('BUILDINGCLASS_NEW_REEF_C_DUMMY',		'TXT_KEY_BUILDING_REEF_DUMMY',				'BUILDING_NEW_REEF_C_DUMMY'),
			('BUILDINGCLASS_GIBRALTAR_DUMMY',		'TXT_KEY_BUILDING_GIBRALTAR_DUMMY',			'BUILDING_GIBRALTAR_DUMMY'),
			('BUILDINGCLASS_LAKE_VICTORIA_DUMMY',	'TXT_KEY_BUILDING_LAKE_VICTORIA_DUMMY',		'BUILDING_LAKE_VICTORIA_DUMMY'),
			('BUILDINGCLASS_CAUSEWAY_A_DUMMY',		'TXT_KEY_BUILDING_CAUSEWAY_A_DUMMY',		'BUILDING_CAUSEWAY_A_DUMMY'),
			('BUILDINGCLASS_CAUSEWAY_B_DUMMY',		'TXT_KEY_BUILDING_CAUSEWAY_B_DUMMY',		'BUILDING_CAUSEWAY_B_DUMMY'),
			('BUILDINGCLASS_RETBA_DUMMY',			'TXT_KEY_BUILDING_RETBA_DUMMY',				'BUILDING_RETBA_DUMMY'),
			('BUILDINGCLASS_LUMI_BAY_DUMMY',		'TXT_KEY_BUILDING_LUMI_BAY_DUMMY',			'BUILDING_LUMI_BAY_DUMMY'),
			('BUILDINGCLASS_DALLOL_DUMMY',			'TXT_KEY_BUILDING_DALLOL_DUMMY',			'BUILDING_DALLOL_DUMMY'),
			('BUILDINGCLASS_EYE_OF_SAHARA_A_DUMMY',	'TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',		'BUILDING_EYE_OF_SAHARA_A_DUMMY'),
			('BUILDINGCLASS_EYE_OF_SAHARA_B_DUMMY',	'TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',		'BUILDING_EYE_OF_SAHARA_B_DUMMY'),
			('BUILDINGCLASS_EYE_OF_SAHARA_C_DUMMY',	'TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',		'BUILDING_EYE_OF_SAHARA_C_DUMMY'),
			('BUILDINGCLASS_MT_KAILASH_DUMMY',		'TXT_KEY_BUILDING_MT_KAILASH_DUMMY',		'BUILDING_MT_KAILASH_DUMMY'),
			('BUILDINGCLASS_KILIMANJARO_DUMMY',		'TXT_KEY_BUILDING_KILIMANJARO_DUMMY',		'BUILDING_KILIMANJARO_DUMMY'),
			('BUILDINGCLASS_ULURU_DUMMY',			'TXT_KEY_BUILDING_ULURU_DUMMY',				'BUILDING_ULURU_DUMMY'),
			('BUILDINGCLASS_BLUE_HOLE_DUMMY',		'TXT_KEY_BUILDING_BLUE_HOLE_DUMMY',			'BUILDING_BLUE_HOLE_DUMMY'),
			('BUILDINGCLASS_GALAPAGOS_A_DUMMY',		'TXT_KEY_BUILDING_GALAPAGOS_A_DUMMY',		'BUILDING_GALAPAGOS_A_DUMMY'),
			('BUILDINGCLASS_GALAPAGOS_B_DUMMY',		'TXT_KEY_BUILDING_GALAPAGOS_B_DUMMY',		'BUILDING_GALAPAGOS_B_DUMMY'),
			('BUILDINGCLASS_HA_LONG_A_DUMMY',		'TXT_KEY_BUILDING_HA_LONG_A_DUMMY',			'BUILDING_HA_LONG_A_DUMMY'),
			('BUILDINGCLASS_HA_LONG_B_DUMMY',		'TXT_KEY_BUILDING_HA_LONG_B_DUMMY',			'BUILDING_HA_LONG_B_DUMMY'),
			('BUILDINGCLASS_ZHANGJIAJIE_DUMMY',		'TXT_KEY_BUILDING_ZHANGJIAJIE_DUMMY',		'BUILDING_ZHANGJIAJIE_DUMMY'),
			('BUILDINGCLASS_AURORA_A_DUMMY',		'TXT_KEY_BUILDING_AURORA_DUMMY',			'BUILDING_AURORA_A_DUMMY'),
			('BUILDINGCLASS_AURORA_B_DUMMY',		'TXT_KEY_BUILDING_AURORA_DUMMY',			'BUILDING_AURORA_B_DUMMY'),
			('BUILDINGCLASS_AURORA_C_DUMMY',		'TXT_KEY_BUILDING_AURORA_DUMMY',			'BUILDING_AURORA_C_DUMMY');

INSERT INTO Buildings
			(Type,								BuildingClass,							Description,								PrereqTech, Cost, FaithCost, GreatWorkCount , NukeImmune, ConquestProb, IsDummy)
VALUES		('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_SALAR_A_DUMMY',			'TXT_KEY_BUILDING_SALAR_A_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_SALAR_B_DUMMY',			'TXT_KEY_BUILDING_SALAR_B_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_EL_DORADO_DUMMY',		'BUILDINGCLASS_EL_DORADO_DUMMY',		'TXT_KEY_BUILDING_EL_DORADO_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_POTOSI_DUMMY',			'BUILDINGCLASS_POTOSI_DUMMY',			'TXT_KEY_BUILDING_POTOSI_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_CRATER_DUMMY',			'BUILDINGCLASS_CRATER_DUMMY',			'TXT_KEY_BUILDING_CRATER_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_MESA_DUMMY',				'BUILDINGCLASS_MESA_DUMMY',				'TXT_KEY_BUILDING_MESA_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_SOLOMONS_MINES_DUMMY',	'BUILDINGCLASS_SOLOMONS_MINES_DUMMY',	'TXT_KEY_BUILDING_SOLOMONS_MINES_DUMMY',	NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_VOLCANO_DUMMY',			'BUILDINGCLASS_VOLCANO_DUMMY',			'TXT_KEY_BUILDING_VOLCANO_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_FUJI_1_DUMMY',			'BUILDINGCLASS_FUJI_1_DUMMY',			'TXT_KEY_BUILDING_FUJI_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_FUJI_2_DUMMY',			'BUILDINGCLASS_FUJI_2_DUMMY',			'TXT_KEY_BUILDING_FUJI_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_FUJI_3_DUMMY',			'BUILDINGCLASS_FUJI_3_DUMMY',			'TXT_KEY_BUILDING_FUJI_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_MT_SINAI_DUMMY',			'BUILDINGCLASS_MT_SINAI_DUMMY',			'TXT_KEY_BUILDING_MT_SINAI_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_GEYSER_DUMMY',			'BUILDINGCLASS_GEYSER_DUMMY',			'TXT_KEY_BUILDING_GEYSER_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_MT_EVEREST_DUMMY',		'BUILDINGCLASS_MT_EVEREST_DUMMY',		'TXT_KEY_BUILDING_MT_EVEREST_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_NEW_REEF_A_DUMMY',		'BUILDINGCLASS_NEW_REEF_A_DUMMY',		'TXT_KEY_BUILDING_REEF_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_NEW_REEF_B_DUMMY',		'BUILDINGCLASS_NEW_REEF_B_DUMMY',		'TXT_KEY_BUILDING_REEF_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_NEW_REEF_C_DUMMY',		'BUILDINGCLASS_NEW_REEF_C_DUMMY',		'TXT_KEY_BUILDING_REEF_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_GIBRALTAR_DUMMY',		'BUILDINGCLASS_GIBRALTAR_DUMMY',		'TXT_KEY_BUILDING_GIBRALTAR_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_LAKE_VICTORIA_DUMMY',	'BUILDINGCLASS_LAKE_VICTORIA_DUMMY',	'TXT_KEY_BUILDING_LAKE_VICTORIA_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_CAUSEWAY_A_DUMMY',		'BUILDINGCLASS_CAUSEWAY_A_DUMMY',		'TXT_KEY_BUILDING_CAUSEWAY_A_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_CAUSEWAY_B_DUMMY',		'BUILDINGCLASS_CAUSEWAY_B_DUMMY',		'TXT_KEY_BUILDING_CAUSEWAY_B_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_RETBA_DUMMY',			'BUILDINGCLASS_RETBA_DUMMY',			'TXT_KEY_BUILDING_RETBA_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_LUMI_BAY_DUMMY',			'BUILDINGCLASS_LUMI_BAY_DUMMY',			'TXT_KEY_BUILDING_LUMI_BAY_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_DALLOL_DUMMY',			'BUILDINGCLASS_DALLOL_DUMMY',			'TXT_KEY_BUILDING_DALLOL_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_EYE_OF_SAHARA_A_DUMMY',	'BUILDINGCLASS_EYE_OF_SAHARA_A_DUMMY',	'TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_EYE_OF_SAHARA_B_DUMMY',	'BUILDINGCLASS_EYE_OF_SAHARA_B_DUMMY',	'TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_EYE_OF_SAHARA_C_DUMMY',	'BUILDINGCLASS_EYE_OF_SAHARA_C_DUMMY',	'TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_MT_KAILASH_DUMMY',		'BUILDINGCLASS_MT_KAILASH_DUMMY',		'TXT_KEY_BUILDING_MT_KAILASH_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_KILIMANJARO_DUMMY',		'BUILDINGCLASS_KILIMANJARO_DUMMY',		'TXT_KEY_BUILDING_KILIMANJARO_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_ULURU_DUMMY',			'BUILDINGCLASS_ULURU_DUMMY',			'TXT_KEY_BUILDING_ULURU_DUMMY',				NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_BLUE_HOLE_DUMMY',		'BUILDINGCLASS_BLUE_HOLE_DUMMY',		'TXT_KEY_BUILDING_BLUE_HOLE_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_GALAPAGOS_A_DUMMY',		'BUILDINGCLASS_GALAPAGOS_A_DUMMY',		'TXT_KEY_BUILDING_GALAPAGOS_A_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_GALAPAGOS_B_DUMMY',		'BUILDINGCLASS_GALAPAGOS_B_DUMMY',		'TXT_KEY_BUILDING_GALAPAGOS_B_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_HA_LONG_A_DUMMY',		'BUILDINGCLASS_HA_LONG_A_DUMMY',		'TXT_KEY_BUILDING_HA_LONG_A_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_HA_LONG_B_DUMMY',		'BUILDINGCLASS_HA_LONG_B_DUMMY',		'TXT_KEY_BUILDING_HA_LONG_B_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_ZHANGJIAJIE_DUMMY',		'BUILDINGCLASS_ZHANGJIAJIE_DUMMY',		'TXT_KEY_BUILDING_ZHANGJIAJIE_DUMMY',		NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_AURORA_A_DUMMY',			'BUILDINGCLASS_AURORA_A_DUMMY',			'TXT_KEY_BUILDING_AURORA_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_AURORA_B_DUMMY',			'BUILDINGCLASS_AURORA_B_DUMMY',			'TXT_KEY_BUILDING_AURORA_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1),
			('BUILDING_AURORA_C_DUMMY',			'BUILDINGCLASS_AURORA_C_DUMMY',			'TXT_KEY_BUILDING_AURORA_DUMMY',			NULL,       -1,   -1,        -1,              1,          0,			1);

INSERT INTO Language_ko_KR 
			(Tag,										Text) 
VALUES		('TXT_KEY_BUILDING_SALAR_A_DUMMY',			'우유니 소금사막 A'),
			('TXT_KEY_BUILDING_SALAR_B_DUMMY',			'우유니 소금사막 B'),
			('TXT_KEY_BUILDING_EL_DORADO_DUMMY',		'엘도라도'),
			('TXT_KEY_BUILDING_POTOSI_DUMMY',			'세로 데 포토시'),
			('TXT_KEY_BUILDING_CRATER_DUMMY',			'배링거 분화구'),
			('TXT_KEY_BUILDING_MESA_DUMMY',				'그랜드 메사'),
			('TXT_KEY_BUILDING_SOLOMONS_MINES_DUMMY',	'솔로몬 왕의 광산'),
			('TXT_KEY_BUILDING_VOLCANO_DUMMY',			'크라카타우'),
			('TXT_KEY_BUILDING_FUJI_DUMMY',				'후지산'),
			('TXT_KEY_BUILDING_MT_SINAI_DUMMY',			'시나이산'),
			('TXT_KEY_BUILDING_GEYSER_DUMMY',			'올드 페이스풀'),
			('TXT_KEY_BUILDING_MT_EVEREST_DUMMY',		'에베레스트산'),
			('TXT_KEY_BUILDING_REEF_DUMMY',				'그레이트배리어리프'),
			('TXT_KEY_BUILDING_GIBRALTAR_DUMMY',		'지브롤터 바위'),
			('TXT_KEY_BUILDING_LAKE_VICTORIA_DUMMY',	'빅토리아 호수'),
			('TXT_KEY_BUILDING_CAUSEWAY_A_DUMMY',		'자이언츠 코즈웨이 A'),
			('TXT_KEY_BUILDING_CAUSEWAY_B_DUMMY',		'자이언츠 코즈웨이 B'),
			('TXT_KEY_BUILDING_RETBA_DUMMY',			'레트바 호수'),
			('TXT_KEY_BUILDING_LUMI_BAY_DUMMY',			'생물 발광만'),
			('TXT_KEY_BUILDING_DALLOL_DUMMY',			'달롤'),
			('TXT_KEY_BUILDING_EYE_OF_SAHARA_DUMMY',	'사하라의 눈'),
			('TXT_KEY_BUILDING_MT_KAILASH_DUMMY',		'카일라스산'),
			('TXT_KEY_BUILDING_KILIMANJARO_DUMMY',		'킬리만자로산'),
			('TXT_KEY_BUILDING_ULURU_DUMMY',			'울루루'),
			('TXT_KEY_BUILDING_BLUE_HOLE_DUMMY',		'그레이트 블루홀'),
			('TXT_KEY_BUILDING_GALAPAGOS_A_DUMMY',		'갈라파고스 A'),
			('TXT_KEY_BUILDING_GALAPAGOS_B_DUMMY',		'갈라파고스 B'),
			('TXT_KEY_BUILDING_HA_LONG_A_DUMMY',		'하롱베이 A'),
			('TXT_KEY_BUILDING_HA_LONG_B_DUMMY',		'하롱베이 B'),
			('TXT_KEY_BUILDING_ZHANGJIAJIE_DUMMY',		'장가계'),
			('TXT_KEY_BUILDING_AURORA_DUMMY',			'오로라');

UPDATE Buildings SET SpecialistType = 'SPECIALIST_ARTIST', GreatPeopleRateChange = 3 WHERE Type = 'BUILDING_FUJI_1_DUMMY';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_WRITER', GreatPeopleRateChange = 2 WHERE Type = 'BUILDING_FUJI_2_DUMMY';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_MUSICIAN', GreatPeopleRateChange = 1 WHERE Type = 'BUILDING_FUJI_3_DUMMY';
UPDATE Buildings SET EmpireSizeModifierReductionGlobal = -10 WHERE Type = 'BUILDING_GEYSER_DUMMY';
UPDATE Buildings SET SpecialistType = 'SPECIALIST_SCIENTIST', GreatPeopleRateChange = 2 WHERE Type = 'BUILDING_VOLCANO_DUMMY';
UPDATE Buildings SET GlobalSpaceProductionModifier = 20 WHERE Type = 'BUILDING_CRATER_DUMMY';
UPDATE Buildings SET NumTradeRouteBonus = 1 WHERE Type = 'BUILDING_POTOSI_DUMMY';
UPDATE Buildings SET GlobalDefenseMod = 5, ExtraLeagueVotes = 8 WHERE Type = 'BUILDING_GIBRALTAR_DUMMY';
UPDATE Buildings SET CitySupplyFlatGlobal = 1 WHERE Type = 'BUILDING_MESA_DUMMY';
UPDATE Buildings SET AllowsFoodTradeRoutesGlobal = 1 WHERE Type = 'BUILDING_LAKE_VICTORIA_DUMMY';
UPDATE Buildings SET GlobalLandmarksTourismPercent = 6 WHERE Type = 'BUILDING_CAUSEWAY_A_DUMMY';
UPDATE Buildings SET GlobalLandmarksTourismPercent = 14 WHERE Type = 'BUILDING_CAUSEWAY_B_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_CONSTRUCTION' WHERE Type = 'BUILDING_EYE_OF_SAHARA_A_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY' WHERE Type = 'BUILDING_EYE_OF_SAHARA_A_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_SATELLITES' WHERE Type = 'BUILDING_EYE_OF_SAHARA_A_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_CONSTRUCTION' WHERE Type = 'BUILDING_EYE_OF_SAHARA_B_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY' WHERE Type = 'BUILDING_EYE_OF_SAHARA_B_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_SATELLITES' WHERE Type = 'BUILDING_EYE_OF_SAHARA_B_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_CONSTRUCTION' WHERE Type = 'BUILDING_EYE_OF_SAHARA_C_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY' WHERE Type = 'BUILDING_EYE_OF_SAHARA_C_DUMMY';
UPDATE Buildings SET EnhancedYieldTech = 'TECH_SATELLITES' WHERE Type = 'BUILDING_EYE_OF_SAHARA_C_DUMMY';

INSERT INTO Building_ResourceQuantity
			(BuildingType,					ResourceType,		Quantity) 
VALUES		('BUILDING_DALLOL_DUMMY',		'RESOURCE_SYLVITE',	1);

INSERT INTO Building_GreatWorkYieldChanges
			(BuildingType,				YieldType,					Yield) 
VALUES		('BUILDING_MT_SINAI_DUMMY',	'YIELD_FAITH',				1),
			('BUILDING_MT_SINAI_DUMMY',	'YIELD_GOLDEN_AGE_POINTS',	1);

INSERT INTO Building_ImprovementYieldChangesGlobal
			(BuildingType,						ImprovementType,				YieldType,						Yield) 
VALUES		('BUILDING_MT_SINAI_DUMMY',			'IMPROVEMENT_HOLY_SITE',		'YIELD_FAITH',					1),
			('BUILDING_MT_SINAI_DUMMY',			'IMPROVEMENT_HOLY_SITE',		'YIELD_GOLDEN_AGE_POINTS',		1),
			('BUILDING_NEW_REEF_B_DUMMY',		'IMPROVEMENT_FISHING_BOATS',	'YIELD_FOOD',					1),
			('BUILDING_NEW_REEF_C_DUMMY',		'IMPROVEMENT_FISHING_BOATS',	'YIELD_FOOD',					1),
			('BUILDING_SOLOMONS_MINES_DUMMY',	'IMPROVEMENT_MINE',				'YIELD_GOLDEN_AGE_POINTS',		1);
			
INSERT INTO Building_ResourceYieldChangesGlobal
			(BuildingType,					ResourceType,				YieldType,			Yield) 
VALUES		('BUILDING_EL_DORADO_DUMMY',	'RESOURCE_GOLD',			'YIELD_FAITH',		1),
			('BUILDING_KILIMANJARO_DUMMY',	'RESOURCE_IVORY',			'YIELD_CULTURE',	1),
			('BUILDING_LUMI_BAY_DUMMY',		'RESOURCE_FISH',			'YIELD_SCIENCE',	1),
			('BUILDING_LUMI_BAY_DUMMY',		'RESOURCE_TROPICAL_FISH',	'YIELD_SCIENCE',	1),
			('BUILDING_POTOSI_DUMMY',		'RESOURCE_SILVER',			'YIELD_SCIENCE',	1);

INSERT INTO Building_ResourceYieldChangesGlobal (BuildingType,					ResourceType,	YieldType,			Yield)
SELECT DISTINCT									'BUILDING_NEW_REEF_A_DUMMY',	Type,			'YIELD_SCIENCE',	1
FROM Resources WHERE ResourceClassType = 'RESOURCECLASS_LUXURY' and SeaResource = 1;

INSERT INTO Building_TechEnhancedYieldChanges
			(BuildingType,						YieldType,			Yield) 
VALUES		('BUILDING_EYE_OF_SAHARA_A_DUMMY',	'YIELD_CULTURE',	1),
			('BUILDING_EYE_OF_SAHARA_A_DUMMY',	'YIELD_TOURISM',	2),
			('BUILDING_EYE_OF_SAHARA_A_DUMMY',	'YIELD_TOURISM',	5),
			('BUILDING_EYE_OF_SAHARA_B_DUMMY',	'YIELD_CULTURE',	1),
			('BUILDING_EYE_OF_SAHARA_B_DUMMY',	'YIELD_TOURISM',	2),
			('BUILDING_EYE_OF_SAHARA_B_DUMMY',	'YIELD_TOURISM',	5),
			('BUILDING_EYE_OF_SAHARA_C_DUMMY',	'YIELD_CULTURE',	1),
			('BUILDING_EYE_OF_SAHARA_C_DUMMY',	'YIELD_TOURISM',	2),
			('BUILDING_EYE_OF_SAHARA_C_DUMMY',	'YIELD_TOURISM',	5);

INSERT INTO Building_SpecialistYieldChanges
			(BuildingType,				SpecialistType,			YieldType,			Yield) 
VALUES		('BUILDING_VOLCANO_DUMMY',	'SPECIALIST_SCIENTIST',	'YIELD_FOOD',		1),
			('BUILDING_VOLCANO_DUMMY',	'SPECIALIST_SCIENTIST',	'YIELD_SCIENCE',	1),
			('BUILDING_GEYSER_DUMMY',	'SPECIALIST_ENGINEER',	'YIELD_SCIENCE',	1);

INSERT INTO Building_BuildingClassYieldChanges
			(BuildingType,						BuildingClassType,				YieldType,			YieldChange) 
VALUES		('BUILDING_MT_KAILASH_DUMMY',		'BUILDINGCLASS_MONUMENT',		'YIELD_FAITH',		1),
			('BUILDING_MT_KAILASH_DUMMY',		'BUILDINGCLASS_TEMPLE',			'YIELD_FAITH',		1),
			('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_FACTORY',		'YIELD_PRODUCTION',	2),
			('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_SOLAR_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_NUCLEAR_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_WIND_PLANT',		'YIELD_PRODUCTION',	2),
			('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_HYDRO_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_SALAR_A_DUMMY',			'BUILDINGCLASS_TIDAL_PLANT',	'YIELD_PRODUCTION',	2),
			('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_FACTORY',		'YIELD_PRODUCTION',	1),
			('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_SOLAR_PLANT',	'YIELD_PRODUCTION',	1),
			('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_NUCLEAR_PLANT',	'YIELD_PRODUCTION',	1),
			('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_WIND_PLANT',		'YIELD_PRODUCTION',	1),
			('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_HYDRO_PLANT',	'YIELD_PRODUCTION',	1),
            ('BUILDING_SALAR_B_DUMMY',			'BUILDINGCLASS_TIDAL_PLANT',	'YIELD_PRODUCTION',	1),
			('BUILDING_GALAPAGOS_A_DUMMY',		'BUILDINGCLASS_WRITERS_GUILD',	'YIELD_SCIENCE',	4),
			('BUILDING_GALAPAGOS_B_DUMMY',		'BUILDINGCLASS_WRITERS_GUILD',	'YIELD_SCIENCE',	2);

INSERT INTO Building_UnitCombatProductionModifiers
			(BuildingType,				UnitCombatType,				Modifier) 
VALUES		('BUILDING_ULURU_DUMMY',	'UNITCOMBAT_DIPLOMACY',		20);

INSERT INTO Building_HurryModifiers
			(BuildingType,						HurryType,		HurryCostModifier) 
VALUES		('BUILDING_LAKE_VICTORIA_DUMMY',	'HURRY_GOLD',	-10);

INSERT INTO Building_GlobalYieldModifiers
			(BuildingType,						YieldType,			Yield) 
VALUES		('BUILDING_MT_EVEREST_DUMMY',		'YIELD_TOURISM',	5),
			('BUILDING_VOLCANO_DUMMY',			'YIELD_SCIENCE',	5),
			('BUILDING_RETBA_DUMMY',			'YIELD_FOOD',		5);

INSERT INTO Building_YieldFromTech
			(BuildingType,				YieldType,					Yield) 
VALUES		('BUILDING_CRATER_DUMMY',	'YIELD_GOLDEN_AGE_POINTS',	10);

INSERT INTO Building_YieldFromDeath
			(BuildingType,				YieldType,		Yield) 
VALUES		('BUILDING_AURORA_A_DUMMY',	'YIELD_FAITH',	2),
			('BUILDING_AURORA_B_DUMMY',	'YIELD_FAITH',	2),
			('BUILDING_AURORA_C_DUMMY',	'YIELD_FAITH',	2);

INSERT INTO Building_YieldFromYieldPercentGlobal
			(BuildingType,				YieldOut,			YieldIn,		Value) 
VALUES		('BUILDING_AURORA_A_DUMMY',	'YIELD_SCIENCE',	'YIELD_FAITH',	3),
			('BUILDING_AURORA_B_DUMMY',	'YIELD_SCIENCE',	'YIELD_FAITH',	3),
			('BUILDING_AURORA_C_DUMMY',	'YIELD_SCIENCE',	'YIELD_FAITH',	3);

INSERT INTO Building_InstantYield
			(BuildingType,				YieldType,		Yield) 
VALUES		('BUILDING_MT_SINAI_DUMMY',	'YIELD_FAITH',	100);
--============================================--
-- 정책
--============================================--
INSERT INTO Policies 
			(Type,							Description)
VALUES		('POLICY_RETBA_DUMMY', 			'TXT_KEY_POLICY_RETBA_DUMMY'),
			('POLICY_LUMI_BAY_DUMMY', 		'TXT_KEY_POLICY_LUMI_BAY_DUMMY'),
			('POLICY_MESA_DUMMY',			'TXT_KEY_POLICY_MESA_DUMMY'),
			('POLICY_HA_LONG_A_DUMMY', 		'TXT_KEY_POLICY_HA_LONG_A_DUMMY'),
			('POLICY_HA_LONG_B_DUMMY', 		'TXT_KEY_POLICY_HA_LONG_B_DUMMY'),
			('POLICY_ZHANGJIAJIE_DUMMY', 	'TXT_KEY_POLICY_ZHANGJIAJIE_DUMMY');

INSERT INTO Language_ko_KR 
			(Tag,									Text) 
VALUES		('TXT_KEY_POLICY_RETBA_DUMMY',			'레트바 호수'),
			('TXT_KEY_POLICY_LUMI_BAY_DUMMY',		'생물 발광만'),
			('TXT_KEY_POLICY_MESA_DUMMY',			'그랜드 메사'),
			('TXT_KEY_POLICY_HA_LONG_A_DUMMY',		'하롱베이 A'),
			('TXT_KEY_POLICY_HA_LONG_B_DUMMY',		'하롱베이 B'),
			('TXT_KEY_POLICY_ZHANGJIAJIE_DUMMY',	'장가계');

INSERT INTO Policy_WLTKDYieldMod 
			(PolicyType, 			YieldType, 		Yield)
VALUES 		('POLICY_RETBA_DUMMY', 	'YIELD_FOOD', 	10);

INSERT INTO Policy_YieldFromBirth 
			(PolicyType, 			YieldType, 			Yield)
VALUES 		('POLICY_RETBA_DUMMY', 	'YIELD_TOURISM', 	15);

INSERT INTO Policy_UnitCombatProductionModifiers
			(PolicyType, 				UnitCombatType, 			ProductionModifier)
VALUES 		('POLICY_MESA_DUMMY', 		'UNITCOMBAT_MOUNTED', 		20),
			('POLICY_HA_LONG_A_DUMMY', 	'UNITCOMBAT_NAVALMELEE', 	5),
			('POLICY_HA_LONG_B_DUMMY', 	'UNITCOMBAT_NAVALMELEE', 	5);

INSERT INTO Policy_ArtifactYieldChanges
			(PolicyType, 				YieldType, 			Yield)
VALUES 		('POLICY_HA_LONG_B_DUMMY', 	'YIELD_CULTURE', 	1);

INSERT INTO Policy_YieldGPExpend
			(PolicyType, 					YieldType, 			Yield)
VALUES 		('POLICY_ZHANGJIAJIE_DUMMY', 	'YIELD_TOURISM', 	50);

INSERT INTO Policy_ArtYieldChanges
			(PolicyType, 					YieldType, 					Yield)
VALUES 		('POLICY_ZHANGJIAJIE_DUMMY', 	'YIELD_GOLDEN_AGE_POINTS', 	2);

INSERT INTO Policy_LitYieldChanges
			(PolicyType, 					YieldType, 					Yield)
VALUES 		('POLICY_ZHANGJIAJIE_DUMMY', 	'YIELD_GOLDEN_AGE_POINTS', 	2);

INSERT INTO Policy_MusicYieldChanges
			(PolicyType, 					YieldType, 					Yield)
VALUES 		('POLICY_ZHANGJIAJIE_DUMMY', 	'YIELD_GOLDEN_AGE_POINTS', 	2);

INSERT INTO Policy_TourismOnUnitCreation	(PolicyType,				UnitClassType,	Tourism)
SELECT DISTINCT								'POLICY_LUMI_BAY_DUMMY',	Class,			25
FROM Units WHERE CombatClass in ('UNITCOMBAT_SETTLER', 'UNITCOMBAT_WORKER', 'UNITCOMBAT_WORKBOAT', 'UNITCOMBAT_CARGO', 'UNITCOMBAT_CARAVAN', 'UNITCOMBAT_INQUISITOR', 'UNITCOMBAT_MISSIONARY', 'UNITCOMBAT_DIPLOMACY', 'UNITCOMBAT_SPECIAL_PEOPLE', 'UNITCOMBAT_SPACESHIP_PART', 'UNITCOMBAT_ARCHAEOLOGIST');
--============================================--
-- 시설
--============================================--
INSERT INTO Improvement_Yields 
			(ImprovementType,							YieldType,			Yield)
SELECT		'IMPROVEMENT_FISHING_BOATS_GBH', 			YieldType,			Yield
FROM Improvement_Yields WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Belief_ImprovementYieldChanges 
			(BeliefType,	ImprovementType,					YieldType,		Yield)
SELECT		BeliefType,		'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Belief_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Building_ImprovementYieldChanges 
			(BuildingType,	ImprovementType,					YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Building_ImprovementYieldChangesGlobal
			(BuildingType,	ImprovementType,					YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChangesGlobal WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO EventChoice_ImprovementYieldChange
			(EventChoiceType,	ImprovementType,					YieldType,		YieldChange)
SELECT		EventChoiceType,	'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		YieldChange
FROM EventChoice_ImprovementYieldChange WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Improvement_YieldPerXAdjacentImprovement
			(ImprovementType,					OtherImprovementType,	YieldType,		Yield,	NumRequired)
SELECT		'IMPROVEMENT_FISHING_BOATS_GBH',	OtherImprovementType, 	YieldType,		Yield,	NumRequired
FROM Improvement_YieldPerXAdjacentImprovement WHERE OtherImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Policy_ImprovementYieldChanges 
			(PolicyType,	ImprovementType,					YieldType,		Yield)
SELECT		PolicyType,		'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Policy_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

INSERT INTO Trait_ImprovementYieldChanges 
			(TraitType,		ImprovementType,					YieldType,		Yield)
SELECT		TraitType,		'IMPROVEMENT_FISHING_BOATS_GBH', 	YieldType,		Yield
FROM Trait_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_FISHING_BOATS';



INSERT INTO Improvement_Yields 
			(ImprovementType,							YieldType,			Yield)
SELECT		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 		YieldType,			Yield
FROM Improvement_Yields WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Belief_ImprovementYieldChanges 
			(BeliefType,	ImprovementType,						YieldType,		Yield)
SELECT		BeliefType,		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Belief_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Building_ImprovementYieldChanges 
			(BuildingType,	ImprovementType,						YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Building_ImprovementYieldChangesGlobal
			(BuildingType,	ImprovementType,						YieldType,		Yield)
SELECT		BuildingType,	'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Building_ImprovementYieldChangesGlobal WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO EventChoice_ImprovementYieldChange
			(EventChoiceType,	ImprovementType,						YieldType,		YieldChange)
SELECT		EventChoiceType,	'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		YieldChange
FROM EventChoice_ImprovementYieldChange WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Improvement_YieldPerXAdjacentImprovement
			(ImprovementType,						OtherImprovementType,	YieldType,		Yield,	NumRequired)
SELECT		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH',	OtherImprovementType, 	YieldType,		Yield,	NumRequired
FROM Improvement_YieldPerXAdjacentImprovement WHERE OtherImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Policy_ImprovementYieldChanges 
			(PolicyType,	ImprovementType,						YieldType,		Yield)
SELECT		PolicyType,		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Policy_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';

INSERT INTO Trait_ImprovementYieldChanges 
			(TraitType,		ImprovementType,						YieldType,		Yield)
SELECT		TraitType,		'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', 	YieldType,		Yield
FROM Trait_ImprovementYieldChanges WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';



CREATE TRIGGER GBH_IY
AFTER INSERT ON Improvement_Yields
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield)
    SELECT DISTINCT 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield)
    SELECT DISTINCT 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Belief_IYC
AFTER INSERT ON Belief_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Belief_ImprovementYieldChanges (BeliefType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BeliefType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Belief_ImprovementYieldChanges (BeliefType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BeliefType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Building_IYC
AFTER INSERT ON Building_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Building_IYCG
AFTER INSERT ON Building_ImprovementYieldChangesGlobal
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Building_ImprovementYieldChangesGlobal (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Building_ImprovementYieldChangesGlobal (BuildingType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.BuildingType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_EventChoice_IYC
AFTER INSERT ON EventChoice_ImprovementYieldChange
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO EventChoice_ImprovementYieldChange (EventChoiceType, ImprovementType, YieldType, YieldChange)
    SELECT DISTINCT NEW.EventChoiceType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.YieldChange
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO EventChoice_ImprovementYieldChange (EventChoiceType, ImprovementType, YieldType, YieldChange)
    SELECT DISTINCT NEW.EventChoiceType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.YieldChange
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Improvement_AIYC
AFTER INSERT ON Improvement_YieldPerXAdjacentImprovement
WHEN NEW.OtherImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Improvement_YieldPerXAdjacentImprovement (ImprovementType, OtherImprovementType, YieldType, Yield, NumRequired)
    SELECT DISTINCT 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.OtherImprovementType, NEW.YieldType, NEW.Yield, NEW.NumRequired
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Improvement_YieldPerXAdjacentImprovement (ImprovementType, OtherImprovementType, YieldType, Yield, NumRequired)
    SELECT DISTINCT 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.OtherImprovementType, NEW.YieldType, NEW.Yield, NEW.NumRequired
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Policy_IYC
AFTER INSERT ON Policy_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.PolicyType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.PolicyType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;

CREATE TRIGGER GBH_Trait_IYC
AFTER INSERT ON Trait_ImprovementYieldChanges
WHEN NEW.ImprovementType IN ('IMPROVEMENT_FISHING_BOATS', 'IMPROVEMENT_OFFSHORE_PLATFORM')
BEGIN
    INSERT INTO Trait_ImprovementYieldChanges (TraitType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.TraitType, 'IMPROVEMENT_FISHING_BOATS_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_FISHING_BOATS';

    INSERT INTO Trait_ImprovementYieldChanges (TraitType, ImprovementType, YieldType, Yield)
    SELECT DISTINCT NEW.TraitType, 'IMPROVEMENT_OFFSHORE_PLATFORM_GBH', NEW.YieldType, NEW.Yield
    WHERE NEW.ImprovementType = 'IMPROVEMENT_OFFSHORE_PLATFORM';
END;
--------------------------------------------------------------
--------------------------------------------------------------