/*INSERT INTO Flavors (ID, Type) VALUES
(38, 'FLAVOR_ARCHER'),
(39, 'FLAVOR_SIEGE'),
(40, 'FLAVOR_SKIRMISHER'),
(41, 'FLAVOR_NAVAL_MELEE'),
(42, 'FLAVOR_NAVAL_RANGED'),
(43, 'FLAVOR_SUBMARINE'),
(44, 'FLAVOR_BOMBER'),
(45, 'FLAVOR_FIGHTER');*/

INSERT INTO Technology_Flavors (TechType, FlavorType, Flavor) VALUES
-- Archer Line
('TECH_TRAPPING', 'FLAVOR_ARCHER', 5),
('TECH_CURRENCY', 'FLAVOR_ARCHER', 5),
('TECH_MACHINERY', 'FLAVOR_ARCHER', 5),
('TECH_METALLURGY', 'FLAVOR_ARCHER', 5),
('TECH_DYNAMITE', 'FLAVOR_ARCHER', 5),
('TECH_BALLISTICS', 'FLAVOR_ARCHER', 5),
('TECH_MOBILE_TACTICS', 'FLAVOR_ARCHER', 5),

-- Siege Line
('TECH_IRON_WORKING', 'FLAVOR_SIEGE', 5),
('TECH_PHYSICS', 'FLAVOR_SIEGE', 5),
('TECH_GUNPOWDER', 'FLAVOR_SIEGE', 5),
('TECH_RIFLING', 'FLAVOR_SIEGE', 5),
('TECH_BALLISTICS', 'FLAVOR_SIEGE', 5),
('TECH_ADVANCED_BALLISTICS', 'FLAVOR_SIEGE', 5),

-- Skirmisher Line
('TECH_ANIMAL_HUSBANDRY', 'FLAVOR_SKIRMISHER', 5),
('TECH_MATHEMATICS', 'FLAVOR_SKIRMISHER', 5),
('TECH_PHYSICS', 'FLAVOR_SKIRMISHER', 5),
('TECH_METALLURGY', 'FLAVOR_SKIRMISHER', 5),
('TECH_MILITARY_SCIENCE', 'FLAVOR_SKIRMISHER', 5),
('TECH_BALLISTICS', 'FLAVOR_SKIRMISHER', 5),
('TECH_MOBILE_TACTICS', 'FLAVOR_SKIRMISHER', 5);

-- Mobile Line
/*
('TECH_ARCHERY', 'FLAVOR_MOBILE', 5),
('TECH_CHIVALRY', 'FLAVOR_MOBILE', 5),
('TECH_METALLURGY', 'FLAVOR_MOBILE', 5),
('TECH_COMBUSTION', 'FLAVOR_MOBILE', 5),
('TECH_COMBINED_ARMS', 'FLAVOR_MOBILE', 5),
('TECH_ADVANCED_BALLISTICS', 'FLAVOR_MOBILE', 5),
('TECH_ROBOTICS', 'FLAVOR_MOBILE', 5);
*/