-- New UnitAIs
INSERT INTO UnitAIInfos	 (ID, Type, Description) VALUES
(44, 'UNITAI_SKIRMISHER','UNITAI_SKIRMISHER'),
(45, 'UNITAI_SUBMARINE', 'UNITAI_SUBMARINE');

UPDATE Units SET DefaultUnitAI = 'UNITAI_SKIRMISHER' WHERE IsMounted = 1 AND CombatClass = 'UNITCOMBAT_ARCHER';
UPDATE Unit_AITypes SET UnitAIType = 'UNITAI_SKIRMISHER' WHERE UnitAIType = "UNITAI_COUNTER" AND UnitType IN (SELECT Type FROM Units WHERE IsMounted = 1 AND CombatClass = 'UNITCOMBAT_ARCHER');

UPDATE Units SET DefaultUnitAI = 'UNITAI_SUBMARINE' WHERE CombatClass = 'UNITCOMBAT_SUBMARINE';
UPDATE Unit_AITypes SET UnitAIType = 'UNITAI_SUBMARINE' WHERE UnitAIType = "UNITAI_ASSAULT_SEA" AND UnitType IN (SELECT Type FROM Units WHERE CombatClass = 'UNITCOMBAT_SUBMARINE');

-- Counter only used by AA
UPDATE Units SET DefaultUnitAI = 'UNITAI_DEFENSE' WHERE AirInterceptRange = 0 AND DefaultUnitAI = 'UNITAI_COUNTER';
DELETE FROM Unit_AITypes WHERE UnitAIType = "UNITAI_COUNTER" AND UnitType NOT IN (SELECT Type FROM Units WHERE AirInterceptRange != 0);
