INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_RECON' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARCHER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MOUNTED' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MELEE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_SIEGE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_GUN' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARMOR' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO Building_SpecialistYieldChanges (BuildingType, SpecialistType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'YIELD_GOLD', 8 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_FA_SEA_ACADEMY', 'YIELD_GREAT_ADMIRAL_POINTS', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_Flavors
SET Flavor = 0
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND FlavorType = 'FLAVOR_HAPPINESS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_BuildingClassHappiness
SET Happiness = 0
WHERE BuildingClassType = 'BUILDINGCLASS_FA_ELECTRIC_POWER' AND BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_BANK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1 );

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1 );

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1 );

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_HARBOR'
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 40, FreePromotion = 'PROMOTION_GENERAL_STACKING', GreatGeneralRateModifier = 0, HurryCostModifier = -20, FreeBuildingThisCity = NULL
WHERE Type = 'BUILDING_FA_WAR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 45, FreePromotion = 'PROMOTION_FA_SEA_ACADEMY', TrainedFreePromotion = NULL, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_SEA_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 60, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_AIR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 50, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_CENTRAL_BANK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 50, CityConnectionTradeRouteModifier = 25, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 70, FreeBuilding = 'BUILDINGCLASS_FA_ELECTRIC_POWER', HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_ELECTRIC_CO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_GOLD] Gold to Merchants in all Cities.[NEWLINE][NEWLINE]Must be built in the [ICON_CAPITAL] Capital. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_BANK_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+25% [ICON_GOLD] Gold from [ICON_TRADE] City Connections. +1 [ICON_GOLD] Gold to Factories, Train Stations, and Seaports.[NEWLINE][NEWLINE]Must have built a Factory in the City. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+25% [ICON_GOLD] Gold from [ICON_TRADE] City Connections.[NEWLINE][NEWLINE]Must have built a Factory in the City. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'All cities receive Electric Power which increases [ICON_RESEARCH] Science, [ICON_GOLD] Gold, and [ICON_PRODUCTION] Production in all cities.[NEWLINE][NEWLINE]Must be built in a city on a river. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Electric Power increases [ICON_RESEARCH] Science, [ICON_GOLD] Gold and [ICON_PRODUCTION] Production in its city.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+15 [ICON_WAR] XP and +15% [ICON_PRODUCTION] Production for all Land Units trained in this City. All land units may receive the Great General Combat Bonus promotion. [NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_WAR_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+15 [ICON_WAR] XP and +15% [ICON_PRODUCTION] Production for all Sea Units trained in this City. All naval units may receive the Seamanship Promotion.[NEWLINE][NEWLINE]Must have a Harbor in the city. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_SEA_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+25% [ICON_PRODUCTION] Production for all Air Units. All air units trained in this city may receive the Evasion Promotion. [NEWLINE][NEWLINE]Must have a Military Academy in the city. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_AIR_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Double movement on Ocean tiles.'
WHERE Tag = 'TXT_KEY_PROMOTION_FA_SEA_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);;

DELETE FROM UnitPromotions_Domains
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);;

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND UnitType = 'UNIT_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND UnitType = 'UNIT_FA_ELECTRIC_CO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Units
WHERE Type = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND UnitType = 'UNIT_GREAT_ADMIRAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);