INSERT INTO Language_en_US
        (Tag,													Text)
VALUES	('TXT_KEY_PROMOTION_IGNORE_ZOC',						'Ignores Zone of Control'),
        ('TXT_KEY_PROMOTION_IGNORE_ZOC_HELP',					'Ignores enemy unit [COLOR_UNIT_TEXT]Zone of Control[ENDCOLOR]'),
        ('TXT_KEY_PEDIA_PROMOTION_IGNORE_ZOC',					'Ignores Zone of Control');

INSERT INTO Unit_FreePromotions (UnitType,			PromotionType)
SELECT							Type,				'PROMOTION_IGNORE_ZOC'
FROM Units WHERE CombatClass='UNITCOMBAT_RECON';

UPDATE UnitPromotions
SET IgnoreZOC = 0
WHERE Type = 'PROMOTION_SURVIVALISM_1';

UPDATE Language_en_US
SET Text = REPLACE (Text, '[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].', '')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE UnitPromotions
SET IgnoreZOC = 0
WHERE Type = 'PROMOTION_SURVIVALISM_2';

UPDATE Language_en_US
SET Text = REPLACE (Text, '[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].', '')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE UnitPromotions
SET IgnoreZOC = 0
WHERE Type = 'PROMOTION_SURVIVALISM_3';

UPDATE Language_en_US
SET Text = REPLACE (Text, '[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].', '')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE UnitPromotions
SET IgnoreZOC = 0
WHERE Type = 'PROMOTION_WOODLAND_TRAILBLAZER_1';

UPDATE Language_en_US
SET Text = REPLACE (Text, '[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1_HELP';

UPDATE UnitPromotions
SET IgnoreZOC = 0
WHERE Type = 'PROMOTION_WOODLAND_TRAILBLAZER_2';

UPDATE Language_en_US
SET Text = REPLACE (Text, '[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2_HELP';

UPDATE UnitPromotions
SET IgnoreZOC = 0
WHERE Type = 'PROMOTION_WOODLAND_TRAILBLAZER_3';

UPDATE Language_en_US
SET Text = REPLACE (Text, '[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_en_US
SET Text = Text||' Double [COLOR_POSITIVE_TEXT]Heal[ENDCOLOR] in Oasis.'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';
