
-- GTAS_StartBias - Part of Really Advanced Setup Mod

DEFAULT_START_BIAS = 0;
START_ALONG_OCEAN = 1;
START_ALONG_RIVER = 2;
START_ESTUARY = 3;
START_REGION_PRIORITY = 4;
START_REGION_AVOID = 5;

START_BIAS_COUNT = 6;

START_BIAS_TEXT = { "TXT_KEY_DEFAULT_BUTTON", "TXT_KEY_GTAS_ALONG_OCEAN", "TXT_KEY_GTAS_ALONG_RIVER", "TXT_KEY_GTAS_ESTUARY", "TXT_KEY_GTAS_REGION_PRIORITY", "TXT_KEY_GTAS_REGION_AVOID" };

function GetStartBiasText(startID)
	return Locale.ConvertTextKey(START_BIAS_TEXT[startID+1]) or "";
end

