CREATE TABLE IF NOT EXISTS PNM_Mods(
  'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
  'Mod' TEXT NOT NULL UNIQUE,
  'Description' TEXT,
  'Name' TEXT NOT NULL,
  'Tooltip' TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PNM_Options(
  'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
  'Mod' TEXT NOT NULL,
  'Type' TEXT NOT NULL UNIQUE,
  'Description' TEXT,
  'Name' TEXT NOT NULL,
  'Tooltip' TEXT DEFAULT NULL,
  'Default' INTEGER DEFAULT 0,
  'Control' TEXT DEFAULT 'checkbox',
  'Order' INTEGER,
  'Parent' TEXT REFERENCES PNM_Options(Type) DEFAULT NULL
);
