--==========================================================================================================================
-- CULTURES
--==========================================================================================================================
-- JFD_CultureBranches
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO JFD_CultureBranches
		(Type,									ShortDescription)
VALUES	('CULTURE_BRANCH_JFD_AFRICA',			'TXT_KEY_CULTURE_BRANCH_JFD_AFRICA_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_CENTRAL_ASIA',		'TXT_KEY_CULTURE_BRANCH_JFD_CENTRAL_ASIA_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_EAST_ASIA',		'TXT_KEY_CULTURE_BRANCH_JFD_EAST_ASIA_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_EUROPE',			'TXT_KEY_CULTURE_BRANCH_JFD_EUROPE_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_MIDDLE_EAST',		'TXT_KEY_CULTURE_BRANCH_JFD_MIDDLE_EAST_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_NORTH_AMERICA',	'TXT_KEY_CULTURE_BRANCH_JFD_NORTH_AMERICA_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_OCEANIA',			'TXT_KEY_CULTURE_BRANCH_JFD_OCEANIA_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_SOUTH_AMERICA',	'TXT_KEY_CULTURE_BRANCH_JFD_SOUTH_AMERICA_SHORT_DESC'),
		('CULTURE_BRANCH_JFD_SOUTH_ASIA',		'TXT_KEY_CULTURE_BRANCH_JFD_SOUTH_ASIA_SHORT_DESC');
--==========================================================================================================================
-- CULTURES
--==========================================================================================================================
--------------------------------------------------------------------------------------------------------------------------
-- JFD_CultureTypes
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO JFD_CultureTypes
		(Type,									BranchType,									LowerTag,					ShortDescription,									StartingEraTag,		StartDistance,	FontIcon,								IconAtlas, 									PortraitIndex)
VALUES	('CULTURE_JFD_ABORIGINAL',				'CULTURE_BRANCH_JFD_OCEANIA',				'JFD_Aboriginal', 			'TXT_KEY_CULTURE_JFD_ABORIGINAL_SHORT_DESC', 		'ERA_ANCIENT',		30,				'[ICON_CULTURE_JFD_ABORIGINAL]', 		'CULDIV_JFD_ABORIGINAL_ICON_ATLAS',			0),
		('CULTURE_JFD_AMAZONIAN',				'CULTURE_BRANCH_JFD_SOUTH_AMERICA',			'JFD_Amazonian', 			'TXT_KEY_CULTURE_JFD_AMAZONIAN_SHORT_DESC', 		'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_AMAZONIAN]', 		'CULDIV_JFD_AMAZONIAN_ICON_ATLAS',			0),
		('CULTURE_JFD_ANDEAN',					'CULTURE_BRANCH_JFD_SOUTH_AMERICA',			'JFD_Andean', 				'TXT_KEY_CULTURE_JFD_ANDEAN_SHORT_DESC', 			'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_ANDEAN]',			'CULDIV_JFD_ANDEAN_ICON_ATLAS',				0),
		('CULTURE_JFD_BANTU',					'CULTURE_BRANCH_JFD_AFRICA',				'JFD_Bantu', 				'TXT_KEY_CULTURE_JFD_BANTU_SHORT_DESC', 			'ERA_ANCIENT',		20,				'[ICON_CULTURE_JFD_BANTU]', 			'CULDIV_JFD_BANTU_ICON_ATLAS',				0),
		('CULTURE_JFD_BHARATA',					'CULTURE_BRANCH_JFD_SOUTH_ASIA',			'JFD_Bharata', 				'TXT_KEY_CULTURE_JFD_BHARATA_SHORT_DESC', 			'ERA_ANCIENT',		15,				'[ICON_CULTURE_JFD_BHARATA]', 			'CULDIV_JFD_BHARATA_ICON_ATLAS',			0),
		('CULTURE_JFD_CENTRAL',					'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Central', 				'TXT_KEY_CULTURE_JFD_CENTRAL_SHORT_DESC', 			'ERA_MEDIEVAL',		10,				'[ICON_CULTURE_JFD_CENTRAL]', 			'CULDIV_JFD_CENTRAL_ICON_ATLAS',			0),
		('CULTURE_JFD_CENTRAL_AFRICAN',			'CULTURE_BRANCH_JFD_AFRICA',				'JFD_CentralAfrican', 		'TXT_KEY_CULTURE_JFD_CENTRAL_AFRICAN_SHORT_DESC', 	'ERA_MEDIEVAL',		15,				'[ICON_CULTURE_JFD_CENTRAL_AFRICAN]', 	'CULDIV_JFD_CENTRAL_AFRICAN_ICON_ATLAS',	0),
		('CULTURE_JFD_CLASSICAL',				'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Classical',			'TXT_KEY_CULTURE_JFD_CLASSICAL_SHORT_DESC', 		'ERA_CLASSICAL',	10,				'[ICON_CULTURE_JFD_CLASSICAL]', 		'CULDIV_JFD_CLASSICAL_ICON_ATLAS',			0),
		('CULTURE_JFD_COLONIAL',				'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Colonial', 			'TXT_KEY_CULTURE_JFD_COLONIAL_SHORT_DESC', 			'ERA_INDUSTRIAL',	25,				'[ICON_CULTURE_JFD_COLONIAL]', 			'CULDIV_JFD_COLONIAL_ICON_ATLAS',			0),
		('CULTURE_JFD_EASTERN',					'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Eastern', 				'TXT_KEY_CULTURE_JFD_EASTERN_SHORT_DESC', 			'ERA_CLASSICAL',	10,				'[ICON_CULTURE_JFD_EASTERN]', 			'CULDIV_JFD_EASTERN_ICON_ATLAS',			0),
		('CULTURE_JFD_EAST_AFRICAN',			'CULTURE_BRANCH_JFD_AFRICA',				'JFD_EastAfrican', 			'TXT_KEY_CULTURE_JFD_EAST_AFRICAN_SHORT_DESC', 		'ERA_MEDIEVAL',		15,				'[ICON_CULTURE_JFD_EAST_AFRICAN]', 		'CULDIV_JFD_EAST_AFRICAN_ICON_ATLAS',		0),
		('CULTURE_JFD_EAST_INDIES',				'CULTURE_BRANCH_JFD_EAST_ASIA',				'JFD_EastIndies', 			'TXT_KEY_CULTURE_JFD_EAST_INDIES_SHORT_DESC', 		'ERA_ANCIENT',		10,				'[ICON_CULTURE_JFD_EAST_INDIES]', 		'CULDIV_JFD_EAST_INDIES_ICON_ATLAS',		0),
		('CULTURE_JFD_FAR_EASTERN',				'CULTURE_BRANCH_JFD_EAST_ASIA',				'JFD_FarEastern', 			'TXT_KEY_CULTURE_JFD_FAR_EASTERN_SHORT_DESC', 		'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_FAR_EASTERN]', 		'CULDIV_JFD_FAR_EASTERN_ICON_ATLAS',		0),
		('CULTURE_JFD_GREAT_PLAINS',			'CULTURE_BRANCH_JFD_NORTH_AMERICA',			'JFD_GreatPlains', 			'TXT_KEY_CULTURE_JFD_GREAT_PLAINS_SHORT_DESC', 		'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_GREAT_PLAINS]',		'CULDIV_JFD_GREAT_PLAINS_ICON_ATLAS',		0),
		('CULTURE_JFD_HIMALAYAN',				'CULTURE_BRANCH_JFD_SOUTH_ASIA',			'JFD_Himalayan', 			'TXT_KEY_CULTURE_JFD_HIMALAYAN_SHORT_DESC', 		'ERA_MEDIEVAL',		25,				'[ICON_CULTURE_JFD_HIMALAYAN]', 		'CULDIV_JFD_HIMALAYAN_ICON_ATLAS',			0),
		('CULTURE_JFD_INDOCHINA',				'CULTURE_BRANCH_JFD_EAST_ASIA',				'JFD_Indochina', 			'TXT_KEY_CULTURE_JFD_INDOCHINA_SHORT_DESC', 		'ERA_MEDIEVAL',		25,				'[ICON_CULTURE_JFD_INDOCHINA]', 		'CULDIV_JFD_INDOCHINA_ICON_ATLAS',			0),
		('CULTURE_JFD_LEVANTINE',				'CULTURE_BRANCH_JFD_MIDDLE_EAST',			'JFD_Levantine', 			'TXT_KEY_CULTURE_JFD_LEVANTINE_SHORT_DESC', 		'ERA_ANCIENT',		0,				'[ICON_CULTURE_JFD_LEVANTINE]', 		'CULDIV_JFD_LEVANTINE_ICON_ATLAS',			0),
		('CULTURE_JFD_MESOAMERICAN',			'CULTURE_BRANCH_JFD_SOUTH_AMERICA',			'JFD_Mesoamerican', 		'TXT_KEY_CULTURE_JFD_MESOAMERICAN_SHORT_DESC',		'ERA_CLASSICAL',	25,				'[ICON_CULTURE_JFD_MESOAMERICAN]', 		'CULDIV_JFD_MESOAMERICAN_ICON_ATLAS',		0),
		('CULTURE_JFD_MESOPOTAMIC',				'CULTURE_BRANCH_JFD_MIDDLE_EAST',			'JFD_Mesopotamic', 			'TXT_KEY_CULTURE_JFD_MESOPOTAMIC_SHORT_DESC', 		'ERA_ANCIENT',		1,				'[ICON_CULTURE_JFD_MESOPOTAMIC]', 		'CULDIV_JFD_MESOPOTAMIC_ICON_ATLAS',		0),
		('CULTURE_JFD_MID_EASTERN',				'CULTURE_BRANCH_JFD_MIDDLE_EAST',			'JFD_MidEastern', 			'TXT_KEY_CULTURE_JFD_MID_EASTERN_SHORT_DESC', 		'ERA_MEDIEVAL',		1,				'[ICON_CULTURE_JFD_MID_EASTERN]', 		'CULDIV_JFD_MID_EASTERN_ICON_ATLAS',		0),
		('CULTURE_JFD_NORTHERN',				'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Northern', 			'TXT_KEY_CULTURE_JFD_NORTHERN_SHORT_DESC', 			'ERA_CLASSICAL',	20,				'[ICON_CULTURE_JFD_NORTHERN]', 			'CULDIV_JFD_NORTHERN_ICON_ATLAS',			0),
		('CULTURE_JFD_OCEANIC',					'CULTURE_BRANCH_JFD_OCEANIA',				'JFD_Oceanic', 				'TXT_KEY_CULTURE_JFD_OCEANIC_SHORT_DESC', 			'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_OCEANIC]', 			'CULDIV_JFD_OCEANIC_ICON_ATLAS',			0),
		('CULTURE_JFD_PACIFIC',					'CULTURE_BRANCH_JFD_NORTH_AMERICA',			'JFD_Pacific', 				'TXT_KEY_CULTURE_JFD_PACIFIC_SHORT_DESC', 			'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_PACIFIC]',			'CULDIV_JFD_PACIFIC_ICON_ATLAS',			0),
		('CULTURE_JFD_POLAR',					'CULTURE_BRANCH_JFD_NORTH_AMERICA',			'JFD_Polar', 				'TXT_KEY_CULTURE_JFD_POLAR_SHORT_DESC', 			'ERA_ANCIENT',		30,				'[ICON_CULTURE_JFD_POLAR]', 			'CULDIV_JFD_POLAR_ICON_ATLAS',				0),
		('CULTURE_JFD_SOUTHERN',				'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Southern',				'TXT_KEY_CULTURE_JFD_SOUTHERN_SHORT_DESC', 			'ERA_MEDIEVAL',		10,				'[ICON_CULTURE_JFD_SOUTHERN]', 			'CULDIV_JFD_SOUTHERN_ICON_ATLAS',			0),
		('CULTURE_JFD_STEPPE',					'CULTURE_BRANCH_JFD_CENTRAL_ASIA',			'JFD_Steppe', 				'TXT_KEY_CULTURE_JFD_STEPPE_SHORT_DESC', 			'ERA_MEDIEVAL',		5,				'[ICON_CULTURE_JFD_STEPPE]', 			'CULDIV_JFD_STEPPE_ICON_ATLAS',				0),
		('CULTURE_JFD_TOTALITARIAN',			'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Totalitarian', 		'TXT_KEY_CULTURE_JFD_TOTALITARIAN_SHORT_DESC',		'ERA_INDUSTRIAL',	10,				'[ICON_CULTURE_JFD_TOTALITARIAN]', 		'CULDIV_JFD_TOTALITARIAN_ICON_ATLAS',		0),
		('CULTURE_JFD_WESTERN',					'CULTURE_BRANCH_JFD_EUROPE',				'JFD_Western', 				'TXT_KEY_CULTURE_JFD_WESTERN_SHORT_DESC', 			'ERA_MEDIEVAL',		15,				'[ICON_CULTURE_JFD_WESTERN]', 			'CULDIV_JFD_WESTERN_ICON_ATLAS',			0),
		('CULTURE_JFD_WEST_AFRICAN',			'CULTURE_BRANCH_JFD_AFRICA',				'JFD_WestAfrican', 			'TXT_KEY_CULTURE_JFD_WEST_AFRICAN_SHORT_DESC', 		'ERA_MEDIEVAL',		15,				'[ICON_CULTURE_JFD_WEST_AFRICAN]', 		'CULDIV_JFD_WEST_AFRICAN_ICON_ATLAS',		0),
		('CULTURE_JFD_WOODLANDS',				'CULTURE_BRANCH_JFD_NORTH_AMERICA',			'JFD_Woodlands', 			'TXT_KEY_CULTURE_JFD_WOODLANDS_SHORT_DESC', 		'ERA_ANCIENT',		25,				'[ICON_CULTURE_JFD_WOODLANDS]',			'CULDIV_JFD_WOODLANDS_ICON_ATLAS',			0);

UPDATE JFD_CultureTypes
SET StartingEraTag = 'ERA_ENLIGHTENMENT'
WHERE Type = 'CULTURE_JFD_COLONIAL'
AND EXISTS (SELECT Type FROM Technologies WHERE Type = 'TECH_EE_FLINTLOCK');
--------------------------------------------------------------------------------------------------------------------------
-- JFD_CultureType_OldTags
--------------------------------------------------------------------------------------------------------------------------	
INSERT INTO JFD_CultureType_OldTags
		(CultureType,						OldTag)
VALUES	('CULTURE_JFD_ABORIGINAL',			'JFD_Sahul'),
		('CULTURE_JFD_AMAZONIAN',			'JFD_Katuje'),
		('CULTURE_JFD_AMAZONIAN',			'CULTURE_JFD_KATUJE'),
		('CULTURE_JFD_ANDEAN',				'JFD_Andean'),
		('CULTURE_JFD_BANTU',				'JFD_Bantu'),
		('CULTURE_JFD_BHARATA',				'JFD_Bharata'),
		('CULTURE_JFD_CENTRAL',				'JFD_Central'),
		('CULTURE_JFD_CLASSICAL',			'JFD_Classical'),
		('CULTURE_JFD_CLASSICAL',			'JFD_MediterraneanClassical'),
		('CULTURE_JFD_COLONIAL',			'JFD_Colonial'),
		('CULTURE_JFD_EASTERN',				'JFD_Eastern'),
		('CULTURE_JFD_EAST_AFRICAN',		'JFD_EastAfrican'),
		('CULTURE_JFD_EAST_INDIES',			'JFD_EastIndies'),
		('CULTURE_JFD_FAR_EASTERN',			'JFD_Oriental'),
		('CULTURE_JFD_FAR_EASTERN',			'CULTURE_JFD_ORIENTAL'),
		('CULTURE_JFD_GREAT_PLAINS',		'JFD_TribalAmerican'),
		('CULTURE_JFD_HIMALAYAN',			'JFD_Himalayan'),
		('CULTURE_JFD_INDOCHINA',			'JFD_Mandala'),
		('CULTURE_JFD_INDOCHINA',			'CULTURE_JFD_MANDALA'),
		('CULTURE_JFD_LEVANTINE',			'JFD_Semitic'),
		('CULTURE_JFD_LEVANTINE',			'CULTURE_JFD_SEMITIC'),
		('CULTURE_JFD_MESOAMERICAN',		'JFD_Mesoamerican'),
		('CULTURE_JFD_MESOPOTAMIC',			'JFD_Mesopotamic'),
		('CULTURE_JFD_MESOPOTAMIC',			'CULTURE_JFD_IRANIAN'),
		('CULTURE_JFD_MID_EASTERN',			'JFD_Islamic'),
		('CULTURE_JFD_MID_EASTERN',			'CULTURE_JFD_ISLAMIC'),
		('CULTURE_JFD_NORTHERN',			'JFD_Northern'),
		('CULTURE_JFD_OCEANIC',				'JFD_Oceanic'),
		('CULTURE_JFD_SOUTHERN',			'JFD_Southern'),
		('CULTURE_JFD_SOUTHERN',			'JFD_Mediterranean'),
		('CULTURE_JFD_SOUTHERN',			'JFD_Papal'),
		('CULTURE_JFD_STEPPE',				'JFD_Steppe'),
		('CULTURE_JFD_TOTALITARIAN',		'JFD_Totalitarian'),
		('CULTURE_JFD_WEST_AFRICAN',		'CULTURE_JFD_SAHARAN'),
		('CULTURE_JFD_WEST_AFRICAN',		'JFD_Saharan'),
		('CULTURE_JFD_WESTERN',				'JFD_Western');
--==========================================================================================================================
-- SUBCULTURES
--==========================================================================================================================
--------------------------------------------------------------------------------------------------------------------------
-- JFD_CultureSubTypes
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO JFD_CultureSubTypes
		(CultureType,					Type,										LowerTag,						ShortDescription)
VALUES	('CULTURE_JFD_CLASSICAL',		'SUBCULTURE_JFD_CLASSICAL_ROMAN',			'JFD_ClassicalRoman',			'TXT_KEY_CULTURE_SUB_JFD_CLASSICAL_ROMAN_SHORT_DESC'),
		('CULTURE_JFD_COLONIAL',		'SUBCULTURE_JFD_COLONIAL_AMERICAN',			'JFD_ColonialAmerican',			'TXT_KEY_CULTURE_SUB_JFD_COLONIAL_AMERICAN_SHORT_DESC'),
		('CULTURE_JFD_COLONIAL',		'SUBCULTURE_JFD_COLONIAL_LATIN',			'JFD_ColonialLatin',			'TXT_KEY_CULTURE_SUB_JFD_COLONIAL_LATIN_SHORT_DESC'),
		('CULTURE_JFD_EASTERN',			'SUBCULTURE_JFD_EASTERN_BYZANTINE',			'JFD_EasternByzantine',			'TXT_KEY_CULTURE_SUB_JFD_EASTERN_BYZANTINE_SHORT_DESC'),
		('CULTURE_JFD_EAST_AFRICAN',	'SUBCULTURE_JFD_EAST_AFRICAN_ETHIOPIAN',	'JFD_EastAfricanEthiopian',		'TXT_KEY_CULTURE_SUB_JFD_EAST_AFRICAN_ETHIOPIAN_SHORT_DESC'),
		('CULTURE_JFD_FAR_EASTERN',		'SUBCULTURE_JFD_FAR_EASTERN_JAPANESE',		'JFD_FarEasternJapanese',		'TXT_KEY_CULTURE_SUB_JFD_FAR_EASTERN_JAPANESE_SHORT_DESC'),
		('CULTURE_JFD_MESOPOTAMIC',		'SUBCULTURE_JFD_MESOPOTAMIC_EGYPTIAN',		'JFD_MesopotamicEgyptian',		'TXT_KEY_CULTURE_SUB_JFD_MESOPOTAMIC_EGYPTIAN_SHORT_DESC'),
		('CULTURE_JFD_MESOPOTAMIC',		'SUBCULTURE_JFD_MESOPOTAMIC_PERSIAN',		'JFD_MesopotamicPersian',		'TXT_KEY_CULTURE_SUB_JFD_MESOPOTAMIC_PERSIAN_SHORT_DESC'),
		('CULTURE_JFD_MID_EASTERN',		'SUBCULTURE_JFD_MID_EASTERN_OTTOMAN',		'JFD_MidEasternOttoman',		'TXT_KEY_CULTURE_SUB_JFD_MID_EASTERN_OTTOMAN_SHORT_DESC'),
		('CULTURE_JFD_NORTHERN',		'SUBCULTURE_JFD_NORTHERN_CELTIC',			'JFD_NorthernCeltic',			'TXT_KEY_CULTURE_SUB_JFD_NORTHERN_CELTIC_SHORT_DESC'),
		('CULTURE_JFD_SOUTHERN',		'SUBCULTURE_JFD_SOUTHERN_PAPAL',			'JFD_SouthernPapal',			'TXT_KEY_CULTURE_SUB_JFD_SOUTHERN_PAPAL_SHORT_DESC'),
		('CULTURE_JFD_STEPPE',			'SUBCULTURE_JFD_STEPPE_TURKIC',				'JFD_SteppeTurkic',				'TXT_KEY_CULTURE_SUB_JFD_STEPPE_TURKIC_SHORT_DESC'),
		('CULTURE_JFD_WESTERN',			'SUBCULTURE_JFD_WESTERN_BRITISH',			'JFD_WesternBritish',			'TXT_KEY_CULTURE_SUB_JFD_WESTERN_BRITISH_SHORT_DESC');
--------------------------------------------------------------------------------------------------------------------------
-- JFD_CultureSubType_OldTags
--------------------------------------------------------------------------------------------------------------------------	
INSERT INTO JFD_CultureSubType_OldTags
		(CultureSubType,							OldTag)
VALUES	('SUBCULTURE_JFD_CLASSICAL_ROMAN',			'CULTURE_SUB_JFD_CLASSICAL_ROMAN'),
		('SUBCULTURE_JFD_COLONIAL_AMERICAN',		'CULTURE_SUB_JFD_COLONIAL_AMERICAN'),
		('SUBCULTURE_JFD_COLONIAL_LATIN',			'CULTURE_SUB_JFD_COLONIAL_LATIN'),
		('SUBCULTURE_JFD_EASTERN_BYZANTINE',		'CULTURE_SUB_JFD_EAST_AFRICAN_ETHIOPIAN'),
		('SUBCULTURE_JFD_EAST_AFRICAN_ETHIOPIAN',	'CULTURE_SUB_JFD_EASTERN_BYZANTINE'),
		('SUBCULTURE_JFD_FAR_EASTERN_JAPANESE',		'CULTURE_SUB_JFD_MID_EASTERN_OTTOMAN'),
		('SUBCULTURE_JFD_MESOPOTAMIC_EGYPTIAN',		'CULTURE_SUB_JFD_FAR_EASTERN_JAPANESE'),
		('SUBCULTURE_JFD_MESOPOTAMIC_PERSIAN',		'CULTURE_SUB_JFD_STEPPE_TURKIC'),
		('SUBCULTURE_JFD_MID_EASTERN_OTTOMAN',		'CULTURE_SUB_JFD_MESOPOTAMIC_EGYPTIAN'),
		('SUBCULTURE_JFD_NORTHERN_CELTIC',			'CULTURE_SUB_JFD_MESOPOTAMIC_PERSIAN'),
		('SUBCULTURE_JFD_SOUTHERN_PAPAL',			'CULTURE_SUB_JFD_SOUTHERN_PAPAL'),
		('SUBCULTURE_JFD_STEPPE_TURKIC',			'SUBCULTURE_JFD_ISLAMIC_TURKIC'),
		('SUBCULTURE_JFD_WESTERN_BRITISH',			'CULTURE_SUB_JFD_WESTERN_BRITISH');
--==========================================================================================================================		
--==========================================================================================================================		