--======================================================================================================================================
-- Master Table
--======================================================================================================================================
CREATE TABLE IF NOT EXISTS JarCityStatesDefine (
	CSName			TEXT			NOT NULL,		-- 
	MinorCivTrait	TEXT			NOT NULL,		-- 
	ArtStyleType	TEXT			NOT NULL,		-- 
	ArtStyleSuffix	TEXT			NOT NULL,		-- 
	ArtStylePrefix	TEXT			NOT NULL,		-- 
	PRIMARY KEY (CSName)
);
--======================================================================================================================================
-- JarCityStatesDefine
--======================================================================================================================================
-- In the end 44 CS for each type -> 220 CS
----------------------------------------------------------------------------------------------------------------------------------------
-- UCS Finished
INSERT INTO JarCityStatesDefine
(CSName, 			ArtStyleType, 				ArtStyleSuffix, ArtStylePrefix, MinorCivTrait) VALUES
('ANANGULA', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('ANDORRA', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_CULTURED'),
('AYUTTHAYA', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
--('GWYNEDD', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_CULTURED'), no
('SEORABEOL', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
('KARASJOHKA', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_CULTURED'),
('KATENDE', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_CULTURED'),
('MANAGUA', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('NAN_MADOL', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_CULTURED'),
('NYARYANA_MARQ', 	'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
--('SIERRA_LEONE', 	'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_CULTURED'), no
('OYO', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_CULTURED'),
('THIMPHU', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
--
('ADEJE', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MARITIME'),
('PARIHAKA', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MARITIME'),
('CHEVAK', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MARITIME'),
('DJIBOUTI', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MARITIME'),
('HONIARA', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MARITIME'),
--('IRUNEA', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MARITIME'), no
('TONDO', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',	 		'MINOR_TRAIT_MARITIME'),
('JETARKTE', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MARITIME'),
('JUYUBIT', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MARITIME'),
('MENDYARRUP', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MARITIME'),
('SGANG_GWAAY', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MARITIME'),
('TAIWAN', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MARITIME'),
--
('AL_TIRABIN', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MERCANTILE'),
('DODOMA', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('DOUALA', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('HANUABADA', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MERCANTILE'),
('HONDURAS', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MERCANTILE'),
('MUISCA', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MERCANTILE'),
('MUSCAT', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('OC_EO', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MERCANTILE'),
('OUIDAH', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('PHANOTEUS', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_MERCANTILE'),
('QUELIMANE', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('SANAA', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('SANTO_DOMINGO', 	'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MERCANTILE'),
('TUNIS', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
--
--('AMBRACIA', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_MILITARISTIC'), no
('ZAZZAU', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('BALKH', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
--('CLERMONT', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MILITARISTIC'), no
('KEMZHIKET', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('DAKKAR', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('FAYA', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('GRANADA', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MILITARISTIC'),
('KIGALI', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
--('LACONIA', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_MILITARISTIC'), no
('NOGAI', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('LEVUKA', 			'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MILITARISTIC'),
('LONGYAN', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('MBABANE', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('ODENSO', 			'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MILITARISTIC'),
('PALMYRA', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('PELYM', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('POKROVKA', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
--('SURREY', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MILITARISTIC'), no
('DETTAH', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MILITARISTIC'),
('TBILISI', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('WOOTEI_NIICIE', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MILITARISTIC'),
--
--('ARMAGH', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_RELIGIOUS'), no
('SARATOV', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('BAGAN', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('BEDULU', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('CANOSSA', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_RELIGIOUS'),
('DALI', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('DANO', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_RELIGIOUS'),
('ISKANWAYA', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_RELIGIOUS'),
('KARYES', 			'ARTSTYLE_GRECO_ROMAN', 	'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_RELIGIOUS'),
('LAHORE', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('MULTAN', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('MUTITJULU', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_RELIGIOUS'),
('RISHIKESH', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('SADDARVAZEH', 	'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('SARNATH', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('SUCEAVA', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_RELIGIOUS'),
('TIWANAKU', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_RELIGIOUS'),
('YANGCHENG', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS');
-- UCS Unfinished
INSERT INTO JarCityStatesDefine
(CSName, 			ArtStyleType, 				ArtStyleSuffix, ArtStylePrefix, MinorCivTrait) VALUES
('CARARIES', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('YAIUWA', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('KITCISIPIRINIK', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('KOKAND', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
('MUTAWAYNATJI', 	'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_CULTURED'),
('SAGALA', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 	 		'MINOR_TRAIT_CULTURED'), -- VP5 Harappa
('SHAMAKHI', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN',	 		'MINOR_TRAIT_CULTURED'),
('SHAHRAZUR', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'), -- Sanandaj 
('THABA_BOSIU',		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_CULTURED'),
('TULA', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('VADUZ', 			'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_CULTURED'),
('VICTORIA', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
--
('ASMARA', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN',			'MINOR_TRAIT_MARITIME'),
--('BALLEY_CHASHTAL', 'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MARITIME'), no
('TORSHAVN', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MARITIME'),
('BOGANIDA', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MARITIME'), 
('CARAL', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MARITIME'),
('CAVVANBAH', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MARITIME'), 
('DAKAR', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN',			'MINOR_TRAIT_MARITIME'),
('KAGYRGYN', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MARITIME'),
('KARIATEBIKE', 	'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MARITIME'),
('MADURAI', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MARITIME'),
('OKAK', 			'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MARITIME'),
('REYKJAVIK', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MARITIME'),
('SKARA_BRAE', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MARITIME'),
--
('ABALESSA', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MERCANTILE'),
('AZEBA', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('GABORONE', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('LUXEMBOURG', 		'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN', 		'MINOR_TRAIT_MERCANTILE'),
('NYENI', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'),
('QARNAWU', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MERCANTILE'), -- VP5 Ouagadougou
('PEGU', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MERCANTILE'),
('POMBERUK', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MERCANTILE'),
('UGARIT', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MERCANTILE'),
--
('DIEGO_GARCIA', 	'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('GUNGNAE', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('MACACO', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('MANTHIMBA', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('ORISTANO', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_MILITARISTIC'),
('PONTOTOC', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MILITARISTIC'),
('PURUKCAHU', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_MILITARISTIC'),
('SCODRA', 			'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN',	'MINOR_TRAIT_MILITARISTIC'),
('TETOUAN', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_MILITARISTIC'),
('TILANTONGO', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MILITARISTIC'),
('VAITAPE', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MILITARISTIC'),
--
('ISHIYAMA', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('AVI_KWA_AME', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_RELIGIOUS'),
('CAHUACHI', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_RELIGIOUS'),
('CAIRO', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_RELIGIOUS'),
('CAMUTINS', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_RELIGIOUS'),
('DONGOLA', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_RELIGIOUS'),
('GONDAR', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_RELIGIOUS'),
('GROZNY', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN',			'MINOR_TRAIT_RELIGIOUS'),
('MATONJENI', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_RELIGIOUS'),
('SOMBAKE', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_RELIGIOUS'),
('TURA', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('YIRRKALA', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN', 		'MINOR_TRAIT_RELIGIOUS');
-- 38th group
INSERT INTO JarCityStatesDefine
(CSName, 			ArtStyleType, 				ArtStyleSuffix, ArtStylePrefix, MinorCivTrait) VALUES
('ATOLAN', 			'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_CULTURED'),
('BAGUIO', 			'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MARITIME'),
('SIPIWININIWAK', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MERCANTILE'),
('BAGHCASARAY', 	'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('NGAZARGAMU', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN', 			'MINOR_TRAIT_RELIGIOUS');
-- UCS Reserves + New
INSERT INTO JarCityStatesDefine
(CSName, 			ArtStyleType, 				ArtStyleSuffix, ArtStylePrefix, MinorCivTrait) VALUES
/*N*/('ZENU',		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('HALICARNASSUS', 	'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_CULTURED'),
('ELEA', 			'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN', 	'MINOR_TRAIT_CULTURED'),
('SANGGYEONG', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
/*N*/('NELEMNOYE', 	'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
/*N*/('ORUGALLU', 	'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_CULTURED'),
('MATURUCA', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
--
('ASHDOD', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN',			'MINOR_TRAIT_MARITIME'),
('ITHACA', 			'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN',	'MINOR_TRAIT_MARITIME'), 
('NGYLVO', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MARITIME'),
/*N*/('CAILIN', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MARITIME'),
/*N*/('PAPEETE', 	'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MARITIME'),
/*N*/('FITIUTA', 	'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MARITIME'), -- VP5 Apia
/*N*/('MANGAAS', 	'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MARITIME'),
--
('TARTESSOS', 		'ARTSTYLE_GRECO_ROMAN', 	'_MED', 	'MEDITERRANEAN',	'MINOR_TRAIT_MERCANTILE'),
('AGADEZ', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN',			'MINOR_TRAIT_MERCANTILE'),
('GONUR', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MERCANTILE'),
('ISCA', 			'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MERCANTILE'),
('SA_HUYN', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MERCANTILE'),
('SHURI', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_MERCANTILE'),
/*N*/('GEORGETOWN', 'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MERCANTILE'),
-- 
/*N*/('VALJALA', 	'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MILITARISTIC'),
/*N*/('WAITIKUBULI','ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_MILITARISTIC'),
('LUANGPRABANG', 	'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
('KANONWALOHALE', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MILITARISTIC'),
('PSKOV', 			'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MILITARISTIC'),
('YAMBIO', 			'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN',			'MINOR_TRAIT_MILITARISTIC'),
('PAVIA', 			'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_MILITARISTIC'),
-- 
('GHAZNI', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('UJJAIN', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('SUSA', 			'ARTSTYLE_MIDDLE_EAST',		'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('BOINNE', 			'ARTSTYLE_EUROPEAN', 		'_EURO', 	'EUROPEAN',			'MINOR_TRAIT_RELIGIOUS'),
('BUKHARA', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN',			'MINOR_TRAIT_RELIGIOUS'),
('MUARO_JAMBI', 	'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_RELIGIOUS'),
('THOLING', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN',			'MINOR_TRAIT_RELIGIOUS');
-- VP5 + New for balance (10)
INSERT INTO JarCityStatesDefine
(CSName, 			ArtStyleType, 				ArtStyleSuffix, ArtStylePrefix, MinorCivTrait) VALUES
-- Cultured (6+4):	Ecbatana, Holmul, Wanggeom, Yamatai, Seoul, Oviedo
('ETENHIRITIPA', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('MANGOLA', 		'ARTSTYLE_MIDDLE_EAST', 	'_AFRI', 	'AFRICAN',			'MINOR_TRAIT_CULTURED'),
('MELGITAT', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
('STANDING_ROCK', 	'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN', 		'MINOR_TRAIT_CULTURED'),
-- Maritime (7+3): 	Trowulan, Jakarta, Venice, Rio de Janeiro, Lisbon, Pago Pago, Perge
('KESPUKWITK', 		'ARTSTYLE_SOUTH_AMERICA', 	'_AMER', 	'AMERICAN',			'MINOR_TRAIT_MARITIME'),
('KOTA_BATU', 		'ARTSTYLE_POLYNESIAN', 		'_POLYNESIA', 	'ASIAN',		'MINOR_TRAIT_MARITIME'),
('LANTAU', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MARITIME'),
-- Mercantile (9+1): Harappa, Novgorod, Segou, Marrakesh, Heidabir, Lutetia, Ouagadougou, Utica, Bornu
('MANGAZEYA', 		'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MERCANTILE'),
-- Militaristic (9+1): Aztlan, Assur, Okilis, Kwa-Bulawayo, Longcheng, Sokoto, Ban Chiang, Zuunmod, Palatium
('CO_LOA', 			'ARTSTYLE_ASIAN', 			'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_MILITARISTIC'),
-- Religious (8+1):	Aksum, Djenne, Nippur, Raqmu, Salem, Onondaga, Shedet, Huari
('PIR_E_SABZ', 		'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN', 			'MINOR_TRAIT_RELIGIOUS'),
('DELHI', 			'ARTSTYLE_MIDDLE_EAST', 	'_ASIA', 	'ASIAN',			'MINOR_TRAIT_RELIGIOUS');
--======================================================================================================================================
-- MinorCivilizations
--======================================================================================================================================
INSERT OR REPLACE INTO MinorCivilizations 
		(Type, 					ShortDescription, 				Description, 					Civilopedia, 						Adjective, 								ArtDefineTag, 					DefaultPlayerColor, 			ArtStyleType, ArtStyleSuffix, ArtStylePrefix, MinorCivTrait, BullyUnitClass)
SELECT	'MINOR_CIV_'||CSName,	'TXT_KEY_CITYSTATE_'||CSName,	'TXT_KEY_CITYSTATE_'||CSName,	'TXT_KEY_CIV5_'||CSName||'_TEXT',	'TXT_KEY_CITYSTATE_'||CSName||'_ADJ',	'ART_DEF_CIVILIZATION_MINOR',	'PLAYERCOLOR_MINOR_'||CSName, 	ArtStyleType, ArtStyleSuffix, ArtStylePrefix, MinorCivTrait, 'UNITCLASS_WORKER'
FROM JarCityStatesDefine;
--======================================================================================================================================
-- MinorCivilization_CityNames
--======================================================================================================================================
INSERT INTO MinorCivilization_CityNames 
		(MinorCivType, 			CityName)
SELECT 	'MINOR_CIV_'||CSName, 	'TXT_KEY_CITYSTATE_'||CSName
FROM JarCityStatesDefine;
--======================================================================================================================================
-- MinorCivilization_Flavors
--======================================================================================================================================
-- 'FLAVOR_NUKE', 'FLAVOR_WONDER', 'FLAVOR_EXPANSION' --► Anyone 0
-- 'FLAVOR_CITY_DEFENSE', 'FLAVOR_DEFENSE', 'FLAVOR_OFFENSE', 'FLAVOR_MILITARY_TRAINING'--► only Militaristic	7
-- 'FLAVOR_NAVAL', 'FLAVOR_GROWTH' --► only Maritime 8
-- 'FLAVOR_CULTURE' --► only Cultured 10
-- 'FLAVOR_RELIGION' --► only Religious 10
-- 'FLAVOR_GOLD' --► only Mercantile 10
INSERT INTO MinorCivilization_Flavors
		(MinorCivType,			FlavorType,			Flavor)
SELECT 	'MINOR_CIV_'||CSName, 	'FLAVOR_NUKE',		0 	FROM JarCityStatesDefine UNION ALL
SELECT 	'MINOR_CIV_'||CSName, 	'FLAVOR_WONDER',	0 	FROM JarCityStatesDefine UNION ALL
SELECT 	'MINOR_CIV_'||CSName, 	'FLAVOR_EXPANSION',	0 	FROM JarCityStatesDefine;

-- Militaristic
INSERT INTO MinorCivilization_Flavors
		(MinorCivType,			FlavorType,				Flavor)
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_CITY_DEFENSE',	7 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_DEFENSE',		7 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_OFFENSE',		7 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_MILITARY_TRAINING',	7 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MILITARISTIC';

-- Maritime
INSERT INTO MinorCivilization_Flavors
		(MinorCivType,			FlavorType,			Flavor)
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_GROWTH',		8 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MARITIME' UNION ALL
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_NAVAL',			8 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MARITIME';

-- Cultured
INSERT INTO MinorCivilization_Flavors
		(MinorCivType,			FlavorType,			Flavor)
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_CULTURE',		10 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_CULTURED';

-- Religious
INSERT INTO MinorCivilization_Flavors
		(MinorCivType,			FlavorType,			Flavor)
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_RELIGION',		10 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_RELIGIOUS';

-- Mercantile
INSERT INTO MinorCivilization_Flavors
		(MinorCivType,			FlavorType,			Flavor)
SELECT 	'MINOR_CIV_'||CSName,	'FLAVOR_GOLD',			10 FROM JarCityStatesDefine WHERE MinorCivTrait='MINOR_TRAIT_MERCANTILE';
--======================================================================================================================================
-- MajorBlocksMinor
--======================================================================================================================================
INSERT INTO MajorBlocksMinor
		(MajorCiv, 						MinorCiv)
SELECT 	'CIVILIZATION_INDIA',			'MINOR_CIV_DELHI'			UNION ALL
SELECT 	'CIVILIZATION_CHINA',			'MINOR_CIV_LANTAU'			UNION ALL
SELECT 	'CIVILIZATION_LS_VIETNAM',		'MINOR_CIV_CO_LOA'			UNION ALL
SELECT 	'CIVILIZATION_JFD_PAPAL_STATES','MINOR_CIV_VATICAN_CITY'	UNION ALL
SELECT 	'CIVILIZATION_JAR_NANMADOL',	'MINOR_CIV_NAN_MADOL'		UNION ALL
SELECT 	'CIVILIZATION_JAR_MARAJOARA',	'MINOR_CIV_CAMUTINS'		;
--======================================================================================================================================
-- Remove shitty or conflictual VP5 City States
--======================================================================================================================================
DELETE FROM MinorCivilizations WHERE Type IN
('MINOR_CIV_COPENHAGEN', 'MINOR_CIV_DUBLIN', 'MINOR_CIV_EDINBURGH', 'MINOR_CIV_HELSINKI', 'MINOR_CIV_OSLO', 'MINOR_CIV_VIENNA',
'MINOR_CIV_WARSAW', 'MINOR_CIV_BUNKEYA', 'MINOR_CIV_LUBA', 'MINOR_CIV_ABERNETHY', 'MINOR_CIV_ARGOS',
'MINOR_CIV_BRANDENBURG', 'MINOR_CIV_DORESTAD', 'MINOR_CIV_ENNS', 'MINOR_CIV_ERACLEA', 'MINOR_CIV_MSOURA', 'MINOR_CIV_SHANGHAI',
'MINOR_CIV_SIGTUNA', 'MINOR_CIV_SOGUT', 'MINOR_CIV_STOCKHOLM', 'MINOR_CIV_VELIGRAD', 'MINOR_CIV_WINCHESTER');

DELETE FROM MinorCivilization_CityNames WHERE MinorCivType IN
('MINOR_CIV_COPENHAGEN', 'MINOR_CIV_DUBLIN', 'MINOR_CIV_EDINBURGH', 'MINOR_CIV_HELSINKI', 'MINOR_CIV_OSLO', 'MINOR_CIV_VIENNA',
'MINOR_CIV_WARSAW', 'MINOR_CIV_BUNKEYA', 'MINOR_CIV_LUBA', 'MINOR_CIV_ABERNETHY', 'MINOR_CIV_ARGOS',
'MINOR_CIV_BRANDENBURG', 'MINOR_CIV_DORESTAD', 'MINOR_CIV_ENNS', 'MINOR_CIV_ERACLEA', 'MINOR_CIV_MSOURA', 'MINOR_CIV_SHANGHAI',
'MINOR_CIV_SIGTUNA', 'MINOR_CIV_SOGUT', 'MINOR_CIV_STOCKHOLM', 'MINOR_CIV_VELIGRAD', 'MINOR_CIV_WINCHESTER');

DELETE FROM MajorBlocksMinor WHERE MinorCiv IN
('MINOR_CIV_COPENHAGEN', 'MINOR_CIV_DUBLIN', 'MINOR_CIV_EDINBURGH', 'MINOR_CIV_HELSINKI', 'MINOR_CIV_OSLO', 'MINOR_CIV_VIENNA',
'MINOR_CIV_WARSAW', 'MINOR_CIV_BUNKEYA', 'MINOR_CIV_LUBA', 'MINOR_CIV_ABERNETHY', 'MINOR_CIV_ARGOS',
'MINOR_CIV_BRANDENBURG', 'MINOR_CIV_DORESTAD', 'MINOR_CIV_ENNS', 'MINOR_CIV_ERACLEA', 'MINOR_CIV_MSOURA', 'MINOR_CIV_SHANGHAI',
'MINOR_CIV_SIGTUNA', 'MINOR_CIV_SOGUT', 'MINOR_CIV_STOCKHOLM', 'MINOR_CIV_VELIGRAD', 'MINOR_CIV_WINCHESTER');
--======================================================================================================================================
-- PlayerColors
--======================================================================================================================================
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_'||substr( Type, 11, LENGTH(Type) );

INSERT OR REPLACE INTO PlayerColors
		(Type, 													SecondaryColor,												PrimaryColor, 				TextColor)
SELECT	'PLAYERCOLOR_MINOR_'||substr( Type, 11, LENGTH(Type) ),	'COLOR_PLAYER_MINOR_'||substr( Type, 11, LENGTH(Type) ),	'COLOR_PLAYER_MINOR_ICON',	'COLOR_PLAYER_PEACH_TEXT'
FROM MinorCivilizations;
--======================================================================================================================================
DROP TABLE JarCityStatesDefine;
--======================================================================================================================================
--======================================================================================================================================