UPDATE Buildings 
SET Cost = 1250, HurryCostModifier = 5
WHERE Type = 'BUILDING_OIL_REFINERY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MOREINDUSTRIAL' AND Value= 1);

UPDATE Buildings 
SET Cost = 1000, HurryCostModifier = 5
WHERE Type = 'BUILDING_SYNTHFUEL_PLANT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MOREINDUSTRIAL' AND Value= 1);

UPDATE Buildings 
SET Cost = 800, HurryCostModifier = 5
WHERE Type = 'BUILDING_WEAPONS_FACTORY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MOREINDUSTRIAL' AND Value= 1);

UPDATE Buildings 
SET Cost = 800, HurryCostModifier = 5
WHERE Type = 'BUILDING_MUNITIONS_FACTORY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MOREINDUSTRIAL' AND Value= 1);