UPDATE Language_ko_KR
SET Text = '빔 액슬'
WHERE Tag = 'TXT_KEY_PROMOTION_ROUGH_TERRAIN_HALF_TURN';

UPDATE Language_ko_KR
SET Text = '험지 (숲, 정글, 언덕) 에서 이동력 [COLOR_NEGATIVE_TEXT]두 배[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ROUGH_TERRAIN_HALF_TURN_HELP';

INSERT INTO Language_ko_KR (Tag, Text)
VALUES
	('TXT_KEY_PROMOTION_SKIRMISHER_DEFENSE',		'이동 표적'),
	('TXT_KEY_PROMOTION_SKIRMISHER_DEFENSE_HELP',	'[COLOR_POSITIVE_TEXT]원거리 공격[ENDCOLOR] 방어 시 +50% [ICON_STRENGTH] 전투력 보너스');