INSERT INTO Language_ko_KR (Tag, Text)
VALUES	('TXT_KEY_PROMOTION_PROFESSIONAL_SOLDIER',		'정예병'),
		('TXT_KEY_PROMOTION_PROFESSIONAL_SOLDIER_HELP',	'[COLOR_POSITIVE_TEXT]원거리 공격[ENDCOLOR] 방어 시 +10% [ICON_STRENGTH] 전투력 보너스[NEWLINE]체력 +10.');