UPDATE Language_ko_KR
SET Text = REPLACE (Text, '방어 시 [ICON_STRENGTH] 전투력이 +25% 증가합니다.[NEWLINE][COLOR_POSITIVE_TEXT]아군 영토 밖에서[ENDCOLOR] 회복할 경우 체력을 +5  더 회복합니다.', '[COLOR_POSITIVE_TEXT]개방된[ENDCOLOR] 지형에서 [ICON_STRENGTH] 방어력이 +10% 증가합니다.')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '방어 시 [ICON_STRENGTH] 전투력이 +25% 증가합니다.[NEWLINE][COLOR_POSITIVE_TEXT]아군 영토 밖에서[ENDCOLOR] 회복할 경우 체력을 +5  더 회복합니다.', '[COLOR_POSITIVE_TEXT]원거리[ENDCOLOR] 공격에 대한 [ICON_STRENGTH] 방어력이 10% 증가합니다. [COLOR_POSITIVE_TEXT]아군 도시[ENDCOLOR] 주변 3 칸 내에서 [ICON_STRENGTH] 전투력이 +10% 증가합니다.')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_VP_VISION] 시야가 +1 증가합니다.[NEWLINE]아군 유닛과 인접해 있지 않으면 [ICON_STRENGTH] 전투력이 +10% 증가합니다. '||Text
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[ICON_VP_VISION] 시야와 승선 시야가 +1 증가합니다.[NEWLINE]', ' [COLOR_POSITIVE_TEXT]숲[ENDCOLOR], [COLOR_POSITIVE_TEXT]정글[ENDCOLOR], [COLOR_POSITIVE_TEXT]언덕[ENDCOLOR]에서 [ICON_WAR] 공격력이 +10% 증가합니다. ')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]험난한 지형[ENDCOLOR]으로 인해 [ICON_STRENGTH] 전투력이 +10% 증가합니다. 도시로부터의 피해가 -10% 감소합니다. '||Text
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[COLOR_POSITIVE_TEXT]아군 영토 밖[ENDCOLOR]에서 [ICON_STRENGTH] 전투력이 +20% 증가합니다.[NEWLINE]', '[ICON_VP_VISION] 시야가 +1 증가합니다.[NEWLINE][COLOR_POSITIVE_TEXT]인접한[ENDCOLOR] 정찰 유닛 1개당 [ICON_STRENGTH] 전투력이 +10% 증가합니다. [COLOR_POSITIVE_TEXT]숲, 정글, 습지, 오아시스[ENDCOLOR]에서 두 배로 회복합니다.')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, ' 승선, 산 건너기,', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '승선할 수 있고, 산을 건널 수 있습니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '승선할 수 있고 산을 건널 수 있습니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '산을 건널 수 있습니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, ' 산 건너기,', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '승선할 수 있습니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, ' 승선,', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[ICON_VP_VISION] 시야와 승선 시야가 +1 증가합니다.', '체력이 절반 이하인 유닛에 대한 [ICON_WAR] 공격력이 +10% 증가합니다. 승선할 수 있고 산을 건널 수 있습니다.')
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_1_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[NEWLINE][COLOR_POSITIVE_TEXT]통제 구역(ZOC)[ENDCOLOR]을 무시합니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[NEWLINE][COLOR_POSITIVE_TEXT]통제 구역(ZOC)[ENDCOLOR]을 무시합니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[NEWLINE][COLOR_POSITIVE_TEXT]통제 구역(ZOC)[ENDCOLOR]을 무시합니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[NEWLINE][COLOR_POSITIVE_TEXT]통제 구역(ZOC)[ENDCOLOR]을 무시합니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[NEWLINE][COLOR_POSITIVE_TEXT]통제 구역(ZOC)[ENDCOLOR]을 무시합니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2_HELP';

UPDATE Language_ko_KR
SET Text = REPLACE (Text, '[NEWLINE][COLOR_POSITIVE_TEXT]통제 구역(ZOC)[ENDCOLOR]을 무시합니다.', '')
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE Language_ko_KR
SET Text = Text||' 부상당한 유닛에 대한 [ICON_WAR] 공격력이 +10% 증가합니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_2_HELP';