-- move theming from the amphtheater 
UPDATE Language_ko_KR SET
Text = Replace(Text, 'Contains 2 slots for [ICON_GW_WRITING] Great Works of Writing.', 'Contains 1 slot for [ICON_GW_WRITING] Great Works of Writing.')
WHERE Tag = 'TXT_KEY_BUILDING_AMPHITHEATER_STRATEGY';

UPDATE Language_ko_KR SET
Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_AMPHITHEATER_HELP';

---------------------
-- policy changes 
---------------------
-- change out Amphitheater for Archive in Artistry. Amphi was v early for a Medieval late-policy anyway.
-- just adding would be a pretty big buff, so dont do that

UPDATE Language_ko_KR SET 
Text = Replace(Text, 'Amphitheaters', 'Archives')
WHERE Tag = 'TXT_KEY_POLICY_ETHICS_HELP';

----------------------
-- religion changes
----------------------
UPDATE Language_ko_KR SET
Text = '+3 [ICON_PEACE] Faith from all Archives in the Empire. ' || Text
WHERE Tag = 'TXT_KEY_BUILDING_CHARTARIUM_HELP';

UPDATE Language_ko_KR SET 
Text = Replace(Text, '+5 [ICON_RESEARCH] Science from [ICON_RELIGION] Holy Sites;', '+3 [ICON_PEACE] Faith from Archives; +5 [ICON_RESEARCH] Science from [ICON_RELIGION] Holy Sites;')
WHERE Tag = 'TXT_KEY_BELIEF_TITHE';

INSERT INTO Language_ko_KR 
	(Tag, Text)
VALUES
	('TXT_KEY_BELIEF_CUSTODIANS_SHORT', 'Custodianship'),
	('TXT_KEY_BELIEF_CUSTODIANS', 'May purchase Archives, Galleries, and Museums with [ICON_PEACE] Faith, and each building gains +2 [ICON_TOURISM] Tourism. +5 [ICON_FOOD] Food, +3 [ICON_RESEARCH] Science, and +2 [ICON_TOURISM] Tourism if the City has at least 18 [ICON_CITIZEN] Citizens.');

UPDATE Language_ko_KR SET
Text = Replace(Text, 'Museums, ', '')
WHERE Tag = 'TXT_KEY_BELIEF_UNDERGROUND_SECT';

-- this is actually undoing a different change in ReligionChanges.sql (loads first)
UPDATE Language_ko_KR SET
Text = Replace(Text, 'Galleries, ', '')
WHERE Tag = 'TXT_KEY_BELIEF_UNDERGROUND_SECT';

-- we should therefore rebalance these reformations
-- divine teachings

UPDATE Language_ko_KR SET 
Text = Replace(Text, ' Holy City gains 20 [ICON_PEACE] Faith each time the owner expends a [ICON_GREAT_PEOPLE] Great Person, scaling with Era.', ' When you spread your [ICON_RELIGION] Religion to foreign Cities, gain +15 [ICON_GOLD] Gold, scaling with the number of new Followers of your [ICON_RELIGION] Religion.')
WHERE Tag = 'TXT_KEY_BELIEF_JESUIT_EDUCATION';

UPDATE Language_ko_KR
SET Text = Replace(Text, 'Libraries, ', '')
WHERE Tag = 'TXT_KEY_BELIEF_JESUIT_EDUCATION';

UPDATE Language_ko_KR
SET Text = Replace(Text, 'Observatories, ', '')
WHERE Tag = 'TXT_KEY_BELIEF_JESUIT_EDUCATION';

-- and faith of the masses
UPDATE Language_ko_KR SET
Text = Replace(Text, ' Holy City owner gains +1 [ICON_HAPPINESS_1] Happiness for every two Cities following this Religion.', ' +2 [ICON_FOOD] Food, [ICON_PRODUCTION] Production, and [ICON_CULTURE] Culture in your Holy City for every unique Luxury Resource owned or imported.')
WHERE Tag = 'TXT_KEY_BELIEF_UNDERGROUND_SECT';

UPDATE Language_ko_KR SET
Text = Replace(Text, '. These buildings produce +2 [ICON_CULTURE] Culture each', ', and each building gains +2 [ICON_PEACE] Faith')
WHERE Tag = 'TXT_KEY_BELIEF_UNDERGROUND_SECT';
/*
-----------------------------
-- tourism effect
----------------------------
-- the wide scaling on this is too strong.

-- nerf the palace to move power to the archive
UPDATE Language_ko_KR SET 
Text = '+10% to [COLOR_POSITIVE_TEXT]All Yields[ENDCOLOR] in the City. +1 [COLOR_POSITIVE_TEXT]Tile Working Range[ENDCOLOR]. Strengthens [ICON_TOURISM] Tourism of [COLOR_POSITIVE_TEXT]Historic Events[ENDCOLOR] generated by the Palace. Contains 1 slot for a [ICON_GW_MUSIC] Great Work of Music.[NEWLINE][NEWLINE]Can only be constructed via the [COLOR_MAGENTA]{TXT_KEY_CIV5_POLICY_TRADITION_HEADING}[ENDCOLOR] Finisher.'
WHERE Tag = 'TXT_KEY_BUILDING_CAPITAL_THRONE_ROOM_HELP';

UPDATE Language_ko_KR
SET Text = Replace(Text, '1 [ICON_GW_MUSIC] Great Work of Music slot, 1 [ICON_MUSICIAN] Musician Slot', 'Strengthens [ICON_TOURISM] Tourism of [COLOR_POSITIVE_TEXT]Historic Events[ENDCOLOR] generated by the Palace, 1 [ICON_GW_MUSIC] Great Work of Music slot, 1 [ICON_MUSICIAN] Musician Slot')
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';
*/

------------------------------
-- Text
------------------------------
INSERT INTO Language_ko_KR (Tag, Text)
VALUES	('TXT_KEY_BUILDING_ARCHIVE',  'Archive'),
		('TXT_KEY_BUILDING_ARCHIVE_TEXT',   'Archives were well developed by the ancient Chinese, the ancient Greeks, and the ancient Romans (who called them Tabularia). The Greek term originally referred to the home or dwelling of the Archon, a ruler or chief magistrate, in which important official state documents were filed and interpreted; from there its meaning broadened to encompass such concepts as ''town hall'' and ''public records''. Indeed, the idea that a society would designate a place to preserve records is integral to the Justinian Code. Archival records are normally unpublished and almost always unique, unlike books or magazines, of which many identical copies may exist. This means that archives are quite distinct from libraries with regard to their functions and organization.[NEWLINE][NEWLINE]While there are many kinds of archives, the most recent census of archivists in the United States identifies five major types: academic, business (for profit), government, non-profit, and others, such as those run by museums or private individuals. Whilst clay tablets dating back to the third and second millenia BC have been found in Levantine archaeological sites, modern archival science is considered to date to the French Revolution. The French National Archives, which possess perhaps the largest archival collection in the world (with records going as far back as 625 A.D.), was created in 1790 during the Revolution from various government, religious, and private archives seized by the revolutionaries.'),
		('TXT_KEY_BUILDING_ARCHIVE_STRATEGY',	'A niche building with some minor yield increases that is required to unlock Theming bonuses for your Great Works of Writing. It also aids in generating Great People, but the effect will be wasted if you City is not also actively producing points.'),
		('TXT_KEY_BUILDING_ARCHIVE_HELP',    'Possible Theming Bonuses:
  [NEWLINE][ICON_BULLET] +4 [ICON_CULTURE] and [ICON_TOURISM] for two [COLOR_POSITIVE_TEXT]Domestic[ENDCOLOR] [ICON_GW_WRITING] Great Works of Writing.
  [NEWLINE][ICON_BULLET] +4 [ICON_CULTURE] and [ICON_TOURISM] for two [COLOR_POSITIVE_TEXT]Foreign[ENDCOLOR] [ICON_GW_WRITING] Great Works of Writing.');
-- When a [ICON_GREAT_PEOPLE] Great Person is born in the City, gain an instant boost of [ICON_RESEARCH] Science and [ICON_CULTURE] Culture equal to 50% of your [ICON_TOURISM] Tourism per turn. Nearby Oases yield +2 [ICON_GOLD] Gold.[NEWLINE][NEWLINE]+2 [ICON_CULTURE] Culture and +1 [ICON_RESEARCH] Science if [COLOR_POSITIVE_TEXT]Themed[ENDCOLOR].
--Strengthens [ICON_TOURISM] Tourism of [COLOR_POSITIVE_TEXT]Historic Events[ENDCOLOR] generated by the Palace.
