----------------
-- text
----------------
INSERT INTO Language_ko_KR
	(Tag, Text)
VALUES
	('TXT_KEY_GEOLOGICAL_SURVEY_HELP', '+33% [ICON_GREAT_SCIENTIST] Great Scientist Rate. +1 [ICON_RESEARCH] Science to all owned Refineries in the Empire.[NEWLINE][NEWLINE]+1 [ICON_RESEARCH] Science to nearby Mines, +2 [ICON_RESEARCH] Science to Quarries, and +3 [ICON_RESEARCH] Science to Oil Wells. +1 [ICON_FOOD] Food for every 4 tiles owned by the City. Claims all nearby [ICON_RES_OIL] Oil when constructed.[NEWLINE][NEWLINE]City [COLOR_NEGATIVE_TEXT]cannot have[ENDCOLOR] a Newsroom or a Switchyard.'),
	('TXT_KEY_GEOLOGICAL_SURVEY', 'Geological Survey'),
	('TXT_KEY_CIV5_GEOLOGICAL_SURVEY_TEXT', 'As a practice, a geological survey refers to the systematic investigation of the geology beneath a given piece of ground for the purpose of creating a geological map or model. As an institution, the world''s first geological survey was founded in London in 1835 to carry out the practice and also organize the training of students in mineralogy and metallurgy.[NEWLINE][NEWLINE]Geological maps are important for many reasons, such as locating ground water sources, guiding infrastructure development, and locating natural resources. The first stage of the geological analysis of a territory is called prospecting. Traditionally prospecting relied on direct observation of mineralization in rock outcrops or in sediments. Modern prospecting also includes the use of geologic, geophysical, and geochemical tools to search for anomalies.'),	
	('TXT_KEY_GEOLOGICAL_SURVEY_STRATEGY', 'Establishing a Geology Survey is most useful in Cities on your Empire''s frontier, and you gain bonuses to Food and Border Growth which feed off each other, but importantly seize control of all nearby Oil, even if someone else thought they owned it first! Extracting minerals, and working Mines generally, will further your Science output, so consider chopping down any Forest or Jungles on your Hills. Indeed if a City already had many Mines, Quarries, and Wells, it might make sense to construct a Survey without further considerations. Empires in search of more Science output will naturally lean towards this Building because of its bonuses to Great Scientists and stacking Science bonus on your Empire''s Refineries, which can become substantial!'),	

	('TXT_KEY_SWITCHYARD_HELP', '+33% [ICON_GREAT_ENGINEER] Great Engineer Rate. +2 [ICON_GOLD] Gold to all owned Coaling Stations in the Empire.[NEWLINE][NEWLINE]-1% Building [ICON_GOLD] Gold Maintenance in the Empire. +5 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold if a [ICON_INTERNATIONAL_TRADE] Trade Route passes through this City. Gain an instant boost of 25 [ICON_PRODUCTION] Production after constructing a Building, scaling with Era.[NEWLINE][NEWLINE]City [COLOR_NEGATIVE_TEXT]cannot have[ENDCOLOR] a Geological Survey or a Newsroom.'),
	('TXT_KEY_SWITCHYARD', 'Switchyard'),
	('TXT_KEY_CIV5_SWITCHYARD_TEXT', 'A switchyard (or ''substation'') is a part of an electrical generation, transmission, and distribution system. Substations transform voltage from high to low, or the reverse, or perform any of several other important functions like regulating the voltage and reactive power of the power system. In large distribution systems with many generators connected in parallel, it may be necessary to use a series switchyard reactor to prevent excessively large current flow during a short circuit; this protects transmission line conductors and switching apparatus from damage due to high currents and forces produced.'),	
	('TXT_KEY_SWITCHYARD_STRATEGY', 'Setting up a Switchyard is always useful to reduce your Gold expenditure everywhere. Indeed, Empires in search of more Gold output will naturally lean towards this Building because of its stacking Gold bonus on your Empire''s Coaling Stations, which can become substantial! If you do build one, this City will benefit from churning out infrastructure, and you can consider sending an Internal Trade Route to speed that up, because a passing Trade Route will also grant additional yields! Working Engineers will also grant additional Great Engineer Points.'),

	('TXT_KEY_NEWSROOM_HELP', '+33% [ICON_GREAT_MERCHANT] Great Merchant Rate. +1 [ICON_TOURISM] Tourism to all owned Wire Services in the Empire.[NEWLINE][NEWLINE]+1 [ICON_RES_PAPER] Paper and 1 [ICON_GOLD] Gold for every 6 [ICON_CITIZEN] Citizens. Identifying a foreign [ICON_SPY] Spy in this City gain 50 [ICON_CULTURE] Culture, when you kill a foreign [ICON_SPY] Spy in this City gain 100 [ICON_CULTURE] Culture, and when you successfully [ICON_PUPPET] Rig an Election in a [ICON_CITY_STATE] City-State gain 20 [ICON_CULTURE] Culture, all scaling with Era. Gain 10 [ICON_CULTURE] Culture whenever you kill an Enemy Unit and 25 [ICON_CULTURE] Culture whenever an Owned Unit dies, both scaling with Era.[NEWLINE][NEWLINE]Requires an [ICON_INDUSTRIAL_CONNECTED] Industrial City Connection. City [COLOR_NEGATIVE_TEXT]cannot have[ENDCOLOR] a Geological Survey or a Switchyard.'),
	('TXT_KEY_NEWSROOM', 'Newsroom'),
	('TXT_KEY_CIV5_NEWSROOM_TEXT', 'A newsroom is the central place where journalists (reporters, editors, photojournalists, along with other staffers) work to gather news to be published in a newspaper, an online newspaper or magazine, or broadcast on radio, television, or cable. In a print publication''s newsroom, reporters sit at desks, gather information, and write articles or stories, on typewriters (after the early 1980s, on personal computers). These stories are submitted to editors, who usually sit together at one large desk, where the stories are reviewed and possibly rewritten. Once finished, editors write a headline for the story and begin to lay it out (see publishing) on a newspaper or magazine page. Editors also review photographs or other graphics to be used with a story before sending for print.'),	
	('TXT_KEY_NEWSROOM_STRATEGY', 'Founding a successful Newsroom can be an engine for generating large amounts of Culture. However the triggers are unusual: reacting to foreign Spies, rigging Elections, and finally Unit kills and deaths. These last two are obvious how to generate, but the first is quite rare. When foreign Spies are Identified, they might not be Killed, and vice-versa. If both happen then you get really lucky, so this creates a disincentive for your opponents to conduct the most risky operations in your Cities with good journalists! You don''t have to just be a victim though, as sending your Spies to City-States will also make headlines, and extra Paper (which can be hard to come by) is a strong boost in the diplomacy game! Indeed, your Wire Services will all generate more Tourism for every Newsroom, a bonus which can become substantial! Finally, Cities with lots of Merchant Specialists are good candidates for a Newsroom, since you receive more Great Merchant Points.');