------------------------------
-- Text
------------------------------
INSERT INTO Language_ko_KR (Tag, Text)
VALUES	('TXT_KEY_BUILDING_SYNCHROTRON',			'Synchrotron'),
		('TXT_KEY_BUILDING_SYNCHROTRON_TEXT',		'A synchrotron is a particular type of cyclic particle accelerator, descended from the cyclotron, in which the accelerating particle beam travels around a fixed closed-loop path. The strength of the magnetic field which bends the particle beam into its closed path increases with time during the accelerating process, being synchronized to the increasing kinetic energy of the particles. The synchrotron is one of the first accelerator concepts to enable the construction of large-scale facilities, since bending, beam focusing and acceleration can be separated into different components.[NEWLINE][NEWLINE]Synchrotron radiation has a wide range of applications: protein crystallography, lithography, chemical and material spectroscopy, radiometry, and even in some cancer therapies. As each beamline (there may be 20 to 50 at a large synchrotron) costs another two or three million dollars on average, these installations are mostly built by the science funding agencies of governments of developed countries, or by collaborations between several countries in a region, and operated as infrastructure facilities available to scientists from universities and research organisations throughout the country, region, or world.'),
		('TXT_KEY_BUILDING_SYNCHROTRON_STRATEGY',	'The final Science building, the Synchrotron gives the final push to get to the Spaceship Victory. Soon you will want every Scientist slot filled, especially in the City where you can make use of the Great Person Rate boost. Indeed every Synchrotron City should be pumping its Production into the Research Process to wind down the clock to Future Tech.'),
		('TXT_KEY_BUILDING_SYNCHROTRON_HELP',		'');

--The [COLOR_YELLOW]Research[ENDCOLOR] Process is 20% more efficient at converting [ICON_PRODUCTION] Production into [ICON_RESEARCH] Science. +1 [ICON_PRODUCTION] Production and [ICON_RESEARCH] Science from every [ICON_SCIENTIST] Scientist in the Empire. +67% [ICON_GREAT_SCIENTIST] Great Scientist Rate.[NEWLINE][NEWLINE]Requires 1 [ICON_RES_ALUMINUM] Aluminum.
