-- update the rationalism policy
UPDATE Language_ko_KR SET Text = REPLACE(Text, '-5 [ICON_HAPPINESS_3] Unhappiness from Religious Unrest in all Cities.', 'Generate 15% [COLOR_NEGATIVE_TEXT]less[ENDCOLOR] [ICON_PEACE] Faith, but 15% of the [ICON_PEACE] Faith created by each City is converted to [ICON_RESEARCH] Science.')
WHERE Tag = 'TXT_KEY_POLICY_FREE_THOUGHT_HELP';

-- humanitarianism
INSERT INTO Language_ko_KR (Tag, Text)
VALUES	('TXT_KEY_BUILDING_HARMONY_AID',			'Aid Agency'),
		('TXT_KEY_BUILDING_HARMONY_AID_TEXT',		'In 1863 the International Committee for Relief to the Wounded organized an international conference to develop possible measures to improve medical services on the battlefield. Only a year later, the Swiss government invited the governments of all European countries, as well as the United States, the Empire of Brazil and the Mexican Empire to attend an official diplomatic conference. Sixteen countries sent a total of 26 delegates to Geneva. On 22 August 1864, the conference adopted the first Geneva Convention "for the Amelioration of the Condition of the Wounded in Armies in the Field". Representatives of 12 states and kingdoms signed the convention, establishing for the first time legally binding rules guaranteeing neutrality and protection for wounded soldiers, field medical personnel, and specific humanitarian institutions in an armed conflict.[NEWLINE][NEWLINE]Although today there are many organizations, both governmental and otherwise, that give humanitarian aid to those in need around the world, the Red Cross (and Islamic Red Crescent formed when the Ottoman Empire ratified the aforementioned treaty in 1865)  exists in nearly every country in the world, with a headquarters in Geneva employing over 22,000 staff and with a budget of around 2.5 billion Swiss francs. Most of that money comes from states, including Switzerland in its capacity as the depositary state of the Geneva Conventions, from national Red Cross societies, the signatory states of the Geneva Conventions, and from international organizations like the European Union. All payments to the ICRC are voluntary and are received as donations based on two types of appeals issued by the committee: an annual Headquarters Appeal to cover its internal costs and Emergency Appeals for its individual missions. In 2023, Ukraine is the ICRC''s biggest humanitarian operation (at 316.5 million Swiss francs), followed by Afghanistan (218 million francs) and Syria (171.7 million francs).'),
		('TXT_KEY_BUILDING_HARMONY_AID_STRATEGY',	'A late-game Building that focusses on Food and Faith generation and value. It also provides these yields from City-States, whether they be Friends or Allies. Additionally your Units that can learn it will receive the Medic II Promotion when trained in this City, which is strengthens your military capability, but in a way appropriate to Harmony. While the bonuses are powerful, you must give up some of your precious Oil to obtain them; as a follower of Harmony, you shouldn''t be using that for its usual purpose anyway!'),
		('TXT_KEY_BUILDING_HARMONY_AID_HELP',		'Requires [COLOR_MAGENTA]Humanitarianism[ENDCOLOR]. 10% of the cost of [ICON_PEACE] Faith Purchases and [ICON_INVEST] Gold Purchases are converted into both [ICON_FOOD] Food and [ICON_PEACE] Faith. Eligible Units trained in this City receive the [COLOR_POSITIVE_TEXT]Medic II[ENDCOLOR] Promotion. Boosts starting Religious Strength of all [ICON_MISSIONARY] Missionaries by 5%.[NEWLINE][NEWLINE][ICON_CITY_STATE]City-State [COLOR_POSITIVE_TEXT]Friend[ENDCOLOR] Bonus: +1 [ICON_FOOD] Food and [ICON_PEACE] Faith each.[NEWLINE][ICON_CITY_STATE]City-State [COLOR_CYAN]Ally[ENDCOLOR] Bonus: +1 [ICON_FOOD] Food and [ICON_PEACE] Faith each.[NEWLINE][NEWLINE]Requires 1 [ICON_RES_OIL] Oil.');

UPDATE Language_ko_KR
SET Text = REPLACE(Text,  'Camps, ', 'Villages, ')
WHERE Tag = 'TXT_KEY_POLICY_CIVIL_SOCIETY_HELP';

-- naturopathy
INSERT INTO Language_ko_KR (Tag, Text)
VALUES	('TXT_KEY_BUILDING_HARMONY_CLINIC',			'Clinic'),
		('TXT_KEY_BUILDING_HARMONY_CLINIC_TEXT',		'Many countries have a legal framework to support alternative or complementary medicine. In Austria and Germany overwhelming practiced by doctors with MDs, compared to American alternative practitioners where perhaps only half are licensed MDs. In Germany herbs are tightly regulated: half are prescribed by doctors and covered by health insurance. Although in the West there is a general stigma against the non-scientific basis of such treatments, in developing nations, access to essential medicines is severely restricted by lack of resources and poverty. Traditional remedies, often closely resembling or forming the basis for alternative remedies, may comprise primary healthcare or be integrated into the healthcare system. In Africa, traditional medicine is used for 80% of primary healthcare, and in developing nations as a whole over one-third of the population lack access to essential medicines. The challenge for third sector entities trying to improve global public health by working in the global south is therefore, often, reversed.'),
		('TXT_KEY_BUILDING_HARMONY_CLINIC_STRATEGY',	'A late-game Building that rewards ''thickening'' a ''wide'' Empire, providing bonuses for tiles but also from City output upon Growth. It also provides various Happiness bonuses to deal with having larger Cities. While the bonuses are powerful, you must give up some of your Strategic Resources to obtain them; as a follower of Harmony, you shouldn''t be using those for their usual purpose anyway!'),
		('TXT_KEY_BUILDING_HARMONY_CLINIC_HELP',		'Requires [COLOR_MAGENTA]Naturopathy[ENDCOLOR]. 33% of the [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith output of the City is added as an instant boost when a [ICON_CITIZEN] Citizen is born in this City. 10% of the cost of [ICON_PEACE] Faith Purchases are converted into [ICON_FOOD] Food, [ICON_RESEARCH] Science, and more [ICON_PEACE] Faith. Increases the City''s resistance to [ICON_RELIGION] Religious conversion by 25%[NEWLINE][NEWLINE]Nearby [ICON_RES_IRON] Iron: +2 [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith.[NEWLINE]Nearby [ICON_RES_COAL] Coal: +2 [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith.[NEWLINE]Nearby [ICON_RES_ALUMINUM] Aluminum: +2 [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith.[NEWLINE]Nearby [ICON_RES_URANIUM] Uranium: +2 [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith.[NEWLINE][NEWLINE]-1 [ICON_HAPPINESS_3] Unhappiness from [ICON_FOOD] and [ICON_PRODUCTION] Distress and from [ICON_GOLD] Poverty.[NEWLINE][NEWLINE]Requires 1 [ICON_RES_IRON] Iron, [ICON_RES_COAL] Coal, [ICON_RES_ALUMINUM] Aluminum, and [ICON_RES_URANIUM] Uranium.');