INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_2', 'Your culture no longer has the same intrinsic value that we all once shared. That degeneracy you call culture shall end.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_3', 'Challenging an ever-increasingly dominant culture is difficult, but necessary to preserve the culture of everyone else.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_4', 'We won''t submit as a captive culture to yours. Our culture will fight for freedom against yours.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_5', 'Our culture won''t be preoccupied with your dangerous influence on the world.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_SPACESHIP_2', 'Your arrogance that you only dare merit a place among the stars will instead see us merit a place among your lands.'),
	('en_US', 'TXT_KEY_DEFENSE_PACT_OFFER_5', 'If we were to form a defensive pact, we could surely develop a strong barrier of defense against the enemies of this world.'),
	('en_US', 'TXT_KEY_DEFENSE_PACT_OFFER_6', 'The enemies surrounds us everywhere. With a strong alliance between us, we are sure to prevail.'),
	('en_US', 'TXT_KEY_DEFENSE_PACT_OFFER_7', 'In this dangerous world, I am surprised we are not allied with each other to defend against the evils of this world. Let us be allies.'),
	('en_US', 'TXT_KEY_CITY_TRADE_OFFER_4', 'Surely, we can freely exchange territories between the two of our nations, can''t we?'),
	('en_US', 'TXT_KEY_CITY_TRADE_OFFER_5', 'I want your land. You want my land. We want our land.'),
	('en_US', 'TXT_KEY_THIRD_PARTY_WAR_OFFER_4', 'You have a great army. I have uses for that army if you accept.'),
	('en_US', 'TXT_KEY_THIRD_PARTY_PEACE_OFFER_4', 'Bury the hatchet with your enemies and my friends, will you not? Consider this offer dearly.'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_3', 'Who do you think you are with that attitude? No more of your nonsense prepare for war!'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_4', 'You have made a mistake in saying that!'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_5', 'You dare mock me? Prepare your soldiers for battle!'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_6', 'You''ll pay for that!'),
	('en_US', 'TXT_KEY_GENERIC_DOW_WARMONGER_3', 'In order to maintain peace, I must end greater evils such as yourself.'),
	('en_US', 'TXT_KEY_GENERIC_DOW_WARMONGER_4', 'First you came for only them, and I did not interfere - because I was not them; Then you came for others, and I did not speak out - but if there is no one left to prevent this, who will?'),
	('en_US', 'TXT_KEY_GENERIC_ATTACKED_STRONG_WARMONGER_2', 'You make me laugh, you attempt to challenge those stronger than you? Go ahead!'),
	('en_US', 'TXT_KEY_GENERIC_ATTACKED_WEAK_WARMONGER_2', 'We may lack your military strength, however I would rather die a noble death than be a bloody tyrant like you.'),
	('en_US', 'TXT_KEY_GENERIC_ATTACKED_IDEOLOGY_SAME_2', 'Have you gone mad? We are on your side! There are others against us and you choose us?'),
	('en_US', 'TXT_KEY_GENERIC_EMBASSY_EXCHANGE_4', 'We should have embassies in our capital for faster communications shall we?'),
	('en_US', 'TXT_KEY_GENERIC_EMBASSY_EXCHANGE_5', 'To help prevent any misunderstanding, we should have an embassy between each other.'),
	('en_US', 'TXT_KEY_GENERIC_EMBASSY_EXCHANGE_6', 'Let''s improve our relations with an embassy.'),
	('en_US', 'TXT_KEY_GENERIC_SAME_POLICIES_FREEDOM_3', 'I see you share the same belief for freedom in the world as I do. I believe we should work together to help liberate other countries to freedom!'),
	('en_US', 'TXT_KEY_GENERIC_SAME_POLICIES_ORDER_3', 'I see you share the same belief for order in the world as I do. Come, help us form an utopian society'),
	('en_US', 'TXT_KEY_GENERIC_SAME_POLICIES_AUTOCRACY_3', 'I see you share the same belief for absolute power in the world as I do. Let us work together for greater power.'),
	('en_US', 'TXT_KEY_GENERIC_CAUGHT_YOUR_SPY_FRIENDLY_3', 'I understand your motive for spying on us.. but we are friends, we shouldn''t spy on each other!'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_SHARE_INTRIGUE_DECEPTION_4', '{1_PlayerName} is plotting against you. I hope you will take some actions for this.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_3', 'You have done well in providing this. This {@1_CivAdjective} plot will fail to succeed.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_4', 'Excellent, thanks for the tip!'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_5', 'That is indeed useful advice, {@1_CivAdjective} will not know of your forthcoming.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_6', 'You''ve been helpful in providing valuable information.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_7', 'That is very interesting information to tell, I thank you for it.'),
	('en_US', 'TXT_KEY_GENERIC_CONFRONT_YOU_KILLED_MY_SPY_3', 'I hope we came here to discuss friendly agreements... not spy incidents!'),
	('en_US', 'TXT_KEY_GENERIC_SWITCHED_TO_FREEDOM_3', 'You have been liberated from oppression. Come enjoy the benefits of freedom and liberty!'),
	('en_US', 'TXT_KEY_GENERIC_SWITCHED_TO_ORDER_3', 'Let us rejoice as we are one step closer to utopia!'),
	('en_US', 'TXT_KEY_GENERIC_SWITCHED_TO_AUTOCRACY_3', 'We knew that you couldn''t resist absolute power.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_HUMAN_CLASSICAL_2', 'Admire me and my legacy for mine shall live on forever while your legacy will crumble. No one shall ever utter a word of yours again.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_HUMAN_RENAISSANCE_2', 'Your traditions of your ancestors are swept away. We will bring you cultural enlightenment into what you call darkness.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_HUMAN_MODERN_2', 'You were once a proud and independent culture. Now that is in the archives. I urge you to forget about that and embrace the new and present culture we have to offer.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_AI_CLASSICAL_2', 'Although, our legacy will crumble. Your legacy will not reign forever. There will be a higher power to contest this!'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_AI_RENAISSANCE_2', 'Your influence may drive our people toward your ways, but we will have a reminder of our old culture should your culture fails to no longer exist!'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_AI_MODERN_2', 'What former glory we may still have is in our history and what we might still preserve and learn from is that there will be greater rivals whose people will be resistant to your attempts to control them.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_WORLD_CONQUEST_2', 'You are like a cloud of darkness as I am a beacon of light. I must end your pathetic attempt.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_WORLD_CONGRESS_3', 'I don''t mean to judge. But when you speak with a lying tongue and a treasury of emptiness, it''s tiring.'),
	('en_US', 'TXT_KEY_GENERIC_DOW_OLD_ENEMIES_3', 'My respected nemesis, let us charge once more into the breach.'),
	('en_US', 'TXT_KEY_GENERIC_DOW_OLD_ENEMIES_4', 'Oh what fun we had before, it''s a pleasure to redo it again.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_HOSTILE_REPEAT_5', 'You have some nerves coming to visit me right now. This better be good.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_HOSTILE_REPEAT_6', 'I did not ask to be your audience. Make it quick.'),
	('en_US', 'TXT_KEY_DENOUNCE_11', 'You are a waste of time. Rot in your corner of the world, I have no time for you.[NEWLINE][NEWLINE]([COLOR_WARNING_TEXT]They have publicly denounced us! NOTE: You are not at war.[ENDCOLOR])'),
	('en_US', 'TXT_KEY_DENOUNCE_12', 'Your actions are unforgivable and unforgettable. You are the one that will bring us toward a dark age.[NEWLINE][NEWLINE]([COLOR_WARNING_TEXT]They have publicly denounced us! NOTE: You are not at war.[ENDCOLOR])'),
	('en_US', 'TXT_KEY_COOP_WAR_REQUEST_7', '{1_PlayerName:textkey} must be punished for their crimes against humanity. I cannot enforce a punishment alone, will you join me?'),
	('en_US', 'TXT_KEY_GENERIC_BOOT_KISSING_5', 'Did I ever tell you are my role model?'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_MILITARY_4', 'An army of your presence is merely breathtaking, I must say.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_MILITARY_5', 'I can only hope your large military exist to uphold the peace.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_MILITARY_6', 'There is a legend of an empire where a mere soldier could take on 10 soldiers at once before falling. I wonder if your men had already accomplished such a task.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_ECONOMY_4', 'Your coffers are full compared to my empty coffers. If you could only teach your ways, I would be very appreciative of your teaching.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_ECONOMY_5', 'There''s a saying that a small investments of your empire could make anyone rich. I wonder if that is true.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_ECONOMY_6', 'There are rumors of an empire with such a vast economy that is unrivaled to everyone. I wonder if they were talking about your empire.'),
	('en_US', 'TXT_KEY_GENERIC_REPEAT_TRADE_7', 'Are you trying to play dumb with me? Come back with something better.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_9', 'Like how the sun smiles upon the mountains and oceans, we greet you with joy.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_10', 'Like how the moon smiles upon the hills and seas, we welcome you with joy.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_11', 'Greetings, how can I be of service?'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_12', 'My salutations to you, fellow leader!'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_13', 'Your presence here has been a pleasant one. Come what shall we discuss?');