UPDATE Technologies
SET AudioIntro = 'AS2D_WONDER_CORPORATION_HQ'
WHERE Type = 'TECH_CORPORATIONS';

UPDATE Technologies
SET AudioIntroHeader = 'AS2D_HEADING_TECH_GLOBALIZATION'
WHERE Type = 'TECH_CORPORATIONS';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_2'
Where Type = 'BUILDING_CIVILIZED_JEWELERS_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_7'
Where Type = 'BUILDING_TWOKAY_FOODS_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_3'
Where Type = 'BUILDING_FIRAXITE_MATERIALS_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_5'
Where Type = 'BUILDING_HEXXON_REFINERY_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_4'
Where Type = 'BUILDING_GIORGIO_ARMEIER_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_1'
Where Type = 'BUILDING_LANDSEA_EXTRACTORS_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CORPORATION_HQ_6'
Where Type = 'BUILDING_TRADER_SIDS_HQ';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_FORUM'
Where Type = 'BUILDING_FORUM';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_SUMMER_PALACE'
Where Type = 'BUILDING_SUMMER_PALACE';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_GRAND_CANAL'
Where Type = 'BUILDING_GRAND_CANAL';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CRYSTAL_PALACE'
Where Type = 'BUILDING_CRYSTAL_PALACE';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_OLYMPIC'
Where Type = 'BUILDING_OLYMPIC_VILLAGE';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_SLATER_MILL'
Where Type = 'BUILDING_SLATER_MILL';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_BLETCHY'
Where Type = 'BUILDING_BLETCHLEY_PARK';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_EMPIRE_STATE'
Where Type = 'BUILDING_EMPIRE_STATE_BUILDING';

UPDATE Buildings
SET WonderSplashAudio = 'AS2D_WONDER_CERN'
Where Type = 'BUILDING_CERN';

