----------------------------------------------------
-- Generic info
----------------------------------------------------

INSERT INTO UnitPromotions (Type, PediaType, IconAtlas, PortraitIndex, Sound) VALUES
('PROMOTION_FW_SPACESHIP',     	'PEDIA_AIR',      'CIV_COLOR_ATLAS_FW_PROMOTIONS', 42, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_ANGELNET',       'PEDIA_SHARED',   'CIV_COLOR_ATLAS_FW_PROMOTIONS', 16, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_APEXPREDATOR',   'PEDIA_MOUNTED',  'PROMOTION_ATLAS',               13, 'AS2D_IF_LEVELUP');

INSERT INTO UnitPromotions (Type, PediaType, IconAtlas, PortraitIndex, Sound, LostWithUpgrade, OrderPriority, CombatPercent) VALUES
('PROMOTION_FW_IMPLANTS',       'PEDIA_SHARED',     'CIV_COLOR_ATLAS_FW_PROMOTIONS', 17, 'AS2D_IF_LEVELUP', 0, 1, 10);


INSERT INTO UnitPromotions 
(Type, 								Description,								Help,												PediaType,			 	PediaEntry,									IconAtlas, 				PortraitIndex, 	Sound, 				LostWithUpgrade,	CannotBeChosen, 	MovesChange,	IgnoreZOC,	VisibilityChange) VALUES
('PROMOTION_FW_ADVANCED_TACTICS',   'TXT_KEY_FW_PROMOTION_ADVANCED_TACTICS',	'TXT_KEY_FW_PROMOTION_ADVANCED_TACTICS_HELP',		'PEDIA_ATTRIBUTES',  	'TXT_KEY_FW_PROMOTION_ADVANCED_TACTICS',	'PROMOTION_ATLAS', 		23, 			'AS2D_IF_LEVELUP', 	0, 					1,					1,				1,			1),
('PROMOTION_FW_IMPLANTS_WORKER',    'TXT_KEY_FW_PROMOTION_IMPLANTS_WORKER',		'TXT_KEY_FW_PROMOTION_IMPLANTS_WORKER_HELP',		'PEDIA_ATTRIBUTES',  	'TXT_KEY_FW_PROMOTION_IMPLANTS_WORKER',		'PROMOTION_ATLAS', 		36, 			'AS2D_IF_LEVELUP', 	0, 					1,					3,				0,			1);

UPDATE UnitPromotions
SET Description = 'TXT_KEY_'||Type, Help = 'TXT_KEY_'||Type||'_HELP', PediaEntry = 'TXT_KEY_'||Type, CannotBeChosen = 1
WHERE Type IN (
'PROMOTION_FW_SPACESHIP',
'PROMOTION_FW_ANGELNET',
'PROMOTION_FW_APEXPREDATOR',
'PROMOTION_FW_IMPLANTS');

INSERT INTO UnitPromotions (Type, Description, PediaEntry, Help, PediaType, IconAtlas, PortraitIndex, AdjacentMod, Sound) VALUES
	('PROMOTION_FW_MASTER_RACE', 'TXT_KEY_FW_PROMOTION_MASTER_RACE', 'TXT_KEY_FW_PROMOTION_MASTER_RACE', 'TXT_KEY_FW_PROMOTION_MASTER_RACE_HELP',	'PEDIA_SHARED',      'PROMOTION_ATLAS', 23, -15, 'AS2D_IF_LEVELUP');

INSERT INTO UnitPromotions_UnitCombatMods (PromotionType, 						UnitCombatType, 						Modifier) 
VALUES	('PROMOTION_FW_MASTER_RACE',		                                	'UNITCOMBAT_GUN',				    		30);

----------------------------------------------------
-- Promotions' unique features
----------------------------------------------------
UPDATE UnitPromotions SET CombatPercent = 25 WHERE Type = 'PROMOTION_FW_ANGELNET';
UPDATE UnitPromotions SET CombatPercent = 15 WHERE Type = 'PROMOTION_FW_SPACESHIP';
UPDATE UnitPromotions SET OpenAttack = 25, AttackWoundedMod = 10  WHERE Type = 'PROMOTION_FW_APEXPREDATOR';
UPDATE UnitPromotions SET CanCrossMountains = 1 WHERE Type = 'PROMOTION_ICE_BREAKERS';

-- Free Promotions 
INSERT INTO Technology_FreePromotions
	(TechType, PromotionType)
VALUES
	('TECH_IMPLANTS', 			'PROMOTION_FW_IMPLANTS_WORKER'),
	('TECH_FUTURE_BALLISTICS', 	'PROMOTION_FW_ADVANCED_TACTICS'),
	('TECH_TRANSGENICS', 	    'PROMOTION_FALLOUT_IMMUNITY');

UPDATE Technology_FreePromotions SET TechType = 'TECH_DYNAMITE' WHERE PromotionType = 'PROMOTION_ICE_BREAKERS' AND TechType = 'TECH_BALLISTICS';

INSERT INTO UnitPromotions_CivilianUnitType
	(UnitType, PromotionType)
VALUES
	('UNIT_GREAT_GENERAL', 			'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_MONGOLIAN_KHAN', 		'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_ZULU_INDABA', 			'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_CARTHAGE_SHOPHET', 		'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_GREAT_ADMIRAL', 			'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_CARTHAGE_SHOPHET_BOAT', 	'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_ARCHAEOLOGIST', 			'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_FW_AUGMENTED_DIPLOMAT', 	'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_FW_SPACE_COLONIST', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_MUSICIAN', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_ARTIST', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_WRITER', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_ENGINEER', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_KHMER_TROMEAK', 			'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_SCIENTIST', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_GREAT_DIPLOMAT', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_IROQUOIS_TADODAHO', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_MERCHANT', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_VENETIAN_MERCHANT', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_WORKER', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_WORKBOAT', 				'PROMOTION_FW_IMPLANTS_WORKER');

INSERT INTO UnitPromotions 
			(Type, 										Description, 										Help, 														Sound, 				PlagueChance, 	PlaguePromotion, 							BarbarianCombatBonus,	MovesChange,	AttackMod,	DefenseMod, ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 	IconAtlas, 				PediaType, 			PediaEntry)
VALUES		('PROMOTION_NEUROTIC_POISON',               'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0',	            'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0_HELP', 	                'AS2D_IF_LEVELUP',	100, 			'PROMOTION_NEUROTIC_POISON_1', 	            0,						0,				0,			0,			0,					0,			0,					1, 				12, 			'promoMUC_atlas_01', 	'PEDIA_SCOUTING',	'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0');

INSERT INTO UnitPromotions 
			(Type, 										Description, 										Help, 													Sound, 				MaxHitPointsChange, EnemyHealChange, 	NeutralHealChange, 	FriendlyHealChange, PromotionDuration, 	PlagueID, 	PlaguePriority, BarbarianCombatBonus,	MovesChange,	AttackMod,	DefenseMod, ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 	IconAtlas, 				PediaType, 			PediaEntry)
VALUES		('PROMOTION_NEUROTIC_POISON_1',             'TXT_KEY_PROMOTION_FW_UNIT_SWARM_1',	            'TXT_KEY_PROMOTION_FW_UNIT_SWARM_1_HELP',               'AS2D_IF_LEVELUP',	-20, 				-15, 				-15, 				-15, 				3, 					1, 			0, 				0,						-1,				0,			0,			0,					0,			0,					1, 				13, 			'promoMUC_atlas_01', 	'PEDIA_SCOUTING',	'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0');

----------------------------------------------------
-- Eligible combats
----------------------------------------------------

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType) VALUES
-- all except planes
('PROMOTION_FW_APEXPREDATOR',	   'UNITCOMBAT_MOUNTED'),
('PROMOTION_SPLASH',			   'UNITCOMBAT_GUN'),
('PROMOTION_FW_GENGINEERED',	   'UNITCOMBAT_MELEE'),
('PROMOTION_FW_GENGINEERED',	   'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_GENGINEERED',	   'UNITCOMBAT_HELICOPTER'),
('PROMOTION_FW_IMPLANTS',          'UNITCOMBAT_GUN'),
('PROMOTION_FW_BIOMODS',           'UNITCOMBAT_GUN'),

('PROMOTION_FW_AEROPLEX_DROP', 'UNITCOMBAT_GUN'),
('PROMOTION_FW_AEROPLEX_DROP', 'UNITCOMBAT_ARMOR'),
('PROMOTION_FW_AEROPLEX_DROP', 'UNITCOMBAT_SIEGE'),
('PROMOTION_FW_AEROPLEX_DROP', 'UNITCOMBAT_RECON'),

('PROMOTION_FW_AUTO_REPAIR', 'UNITCOMBAT_GUN'),
('PROMOTION_FW_AUTO_REPAIR', 'UNITCOMBAT_ARCHER'),
('PROMOTION_FW_AUTO_REPAIR', 'UNITCOMBAT_ARMOR'),
('PROMOTION_FW_AUTO_REPAIR', 'UNITCOMBAT_SIEGE'),

('PROMOTION_FW_TRANSGENICS', 'UNITCOMBAT_MELEE'),
('PROMOTION_FW_TRANSGENICS', 'UNITCOMBAT_GUN'),
('PROMOTION_FW_TRANSGENICS', 'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_TRANSGENICS', 'UNITCOMBAT_HELICOPTER'),

('PROMOTION_FW_MUTATION', 'UNITCOMBAT_MELEE'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_GUN'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_ARCHER'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_ARMOR'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_SIEGE'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_HELICOPTER'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_RECON'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_FIGHTER'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_BOMBER'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_SUBMARINE'),
('PROMOTION_FW_MUTATION', 'UNITCOMBAT_CARRIER'),

('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_MELEE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_GUN'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_MOUNTED'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_ARCHER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_ARMOR'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_SIEGE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_HELICOPTER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_RECON'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_FIGHTER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_BOMBER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_SUBMARINE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_CARRIER'),
('PROMOTION_FW_SPACESHIP',	       'UNITCOMBAT_FIGHTER'),
('PROMOTION_FW_SPACESHIP',         'UNITCOMBAT_BOMBER'),
('PROMOTION_FW_ANGELNET',    	   'UNITCOMBAT_RECON'),
('PROMOTION_FW_ANGELNET',   	   'UNITCOMBAT_ARCHER'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_MELEE'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_SIEGE'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_GUN'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_ARMOR'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_HELICOPTER'),
('PROMOTION_FW_ANGELNET',   	   'UNITCOMBAT_SUBMARINE');


INSERT INTO UnitPromotions_UnitClasses
	(PromotionType, UnitClassType, Attack, Defense)
VALUES
	('PROMOTION_ANTI_SUBMARINE_I', 'UNITCLASS_FW_MECHASUB', 33, 25),
	('PROMOTION_ANTI_SUBMARINE_I', 'UNITCLASS_FW_CYBERSUB', 33, 25),
	('PROMOTION_ANTI_SUBMARINE_II', 'UNITCLASS_FW_MECHASUB', 66, 50),
	('PROMOTION_ANTI_SUBMARINE_II', 'UNITCLASS_FW_CYBERSUB', 66, 50);

INSERT INTO UnitPromotions_UnitClasses
	(PromotionType, UnitClassType, Modifier)
VALUES
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_APACHE',       150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_VERTOL',       150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_HOVERTANK',    150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_NEXUS',        150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_HELICARIIER',  150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_NANOHIVE',     150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_MEGAHIVE',     150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_MODERN_DRONE', 150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_HYBRID_DRONE', 150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_BIODRONE',     150);


-- 유전자 계열: 기본 선택창에 나오면 안 되니까 CannotBeChosen = 1
UPDATE UnitPromotions SET CannotBeChosen = 1
WHERE Type IN (
  'PROMOTION_FW_ADRENAL_GLANDS',
  'PROMOTION_FW_PREDATOR_INSTINCT',
  'PROMOTION_FW_ENHANCED_REFLEXES',
  'PROMOTION_FW_ENHANCED_VISION',
  'PROMOTION_FW_ENHANCED_MUSCLES',
  'PROMOTION_FW_URBAN_WARFARE',
  'PROMOTION_FW_CHAMELEON'
);

-- 바이오 계열
UPDATE UnitPromotions SET CannotBeChosen = 1
WHERE Type IN (
  'PROMOTION_FW_IMPACT_MOD',           
  'PROMOTION_FW_BOOST_MOD',
  'PROMOTION_FW_BIOREGENERATION_MOD',
  'PROMOTION_FW_SYNTHETIC_LUNGS_MOD',
  'PROMOTION_FW_VISION_ENHANCEMENT_MOD',
  'PROMOTION_FW_REFLEX_MOD',
  'PROMOTION_FW_TOXIN_MOD',
  'PROMOTION_FW_SHOCK_WAVE_SHIELD_MOD'
);
