-- Colonist
INSERT INTO UnitGameplay2DScripts 	
			(UnitType, 					   SelectionSound, 		FirstSelectionSound)
VALUES		
    ('UNIT_FW_MODERN_COLONIST',    'AS2D_SELECT_SETTLER',   'AS2D_BIRTH_SETTLER'),
	('UNIT_FW_SPACE_COLONIST',     'AS2D_SELECT_SETTLER',   'AS2D_BIRTH_SETTLER');

-- Diplomat
INSERT INTO UnitGameplay2DScripts 	
			(UnitType, 					   SelectionSound, 		FirstSelectionSound)
VALUES		
	('UNIT_FW_AUGMENTED_DIPLOMAT', 'AS2D_BUILD_UNIT',       'AS2D_BUILD_UNIT');


-- Missile 
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES 
 ('UNIT_FW_CLUSTER_MISSILE',         'AS2D_SELECT_GUIDED_MISSILE',  'AS2D_BIRTH_GUIDED_MISSILE'),
 ('UNIT_FW_HYPERMISSILE',            'AS2D_SELECT_GUIDED_MISSILE',  'AS2D_BIRTH_GUIDED_MISSILE'),
 ('UNIT_FW_ADVANCED_MISSILE_GUIDED', 'AS2D_SELECT_GUIDED_MISSILE',  'AS2D_BIRTH_GUIDED_MISSILE'),
 ('UNIT_FW_RAILGUN_MISSILE',         'AS2D_SELECT_GUIDED_MISSILE',  'AS2D_BIRTH_GUIDED_MISSILE'),
 ('UNIT_FW_GOD_ROD',                 'AS2D_SELECT_NUCLEAR_MISSILE', 'AS2D_BIRTH_NUCLEAR_MISSILE'),
 ('UNIT_FW_GOD_ROD2',                'AS2D_SELECT_NUCLEAR_MISSILE', 'AS2D_BIRTH_NUCLEAR_MISSILE'),
 ('UNIT_FW_HYDROGEN_BOMB',           'AS2D_SELECT_NUCLEAR_MISSILE', 'AS2D_BIRTH_NUCLEAR_MISSILE'),
 ('UNIT_FW_THERMONUCLEAR_BOMB',      'AS2D_SELECT_NUCLEAR_MISSILE', 'AS2D_BIRTH_NUCLEAR_MISSILE');

-- Armor
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_FW_RAILGUN_TANK', 'AS2D_SELECT_MECH', 'AS2D_BIRTH_MECH'),
	('UNIT_FW_ZEKE',         'AS2D_SELECT_MECH', 'AS2D_BIRTH_MECH');

-- Air-recon
INSERT INTO UnitGameplay2DScripts 	(UnitType, 					   SelectionSound, 		FirstSelectionSound)
VALUES		
    ('UNIT_FW_MODERN_DRONE', 'AS2D_SELECT_FIGHTER', 	'AS2D_BIRTH_FIGHTER'),
    ('UNIT_FW_HYBRID_DRONE', 'AS2D_SELECT_FIGHTER', 	'AS2D_BIRTH_FIGHTER'),
	('UNIT_FW_BIODRONE',	 'AS2D_SELECT_FIGHTER', 	'AS2D_BIRTH_FIGHTER');

-- Helicopter
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_APACHE',     'AS2D_SELECT_HELICOPTER_GUNSHIP', 'AS2D_BIRTH_HELICOPTER_GUNSHIP'),
 ('UNIT_FW_VERTOL',     'AS2D_SELECT_HELICOPTER_GUNSHIP', 'AS2D_BIRTH_HELICOPTER_GUNSHIP'),
 ('UNIT_FW_HOVERTANK',  'AS2D_SELECT_HELICOPTER_GUNSHIP', 'AS2D_BIRTH_HELICOPTER_GUNSHIP');

-- SAM
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_MODERN_MOBILE_SAM', 'AS2D_SELECT_MOBILE_SAM', 'AS2D_BIRTH_MOBILE_SAM'),
 ('UNIT_FW_CYBERSAM',          'AS2D_SELECT_MOBILE_SAM', 'AS2D_BIRTH_MOBILE_SAM'),
 ('UNIT_FW_CRAWLER',           'AS2D_SELECT_MOBILE_SAM', 'AS2D_BIRTH_MOBILE_SAM');

-- Siege
INSERT INTO UnitGameplay2DScripts 	(UnitType, 					   SelectionSound, 		FirstSelectionSound)
VALUES		
    ('UNIT_FW_HIMARS',         'AS2D_SELECT_ROCKET_ARTILLERY', 	'AS2D_BIRTH_ROCKET_ARTILLERY'),
    ('UNIT_FW_MECH_ARTILLERY', 'AS2D_SELECT_ROCKET_ARTILLERY', 	'AS2D_BIRTH_ROCKET_ARTILLERY'),
	('UNIT_FW_ANGEL',	       'AS2D_SELECT_ROCKET_ARTILLERY', 	'AS2D_BIRTH_ROCKET_ARTILLERY');

-- Armor soldiers
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_FW_POWER_ARMOR_INFANTRY', 'AS2D_SELECT_MECH_INFANTRY', 'AS2D_BIRTH_MECH_INFANTRY'),
	('UNIT_FW_BATTLESUIT',           'AS2D_SELECT_MECH_INFANTRY', 'AS2D_BIRTH_MECH_INFANTRY'),
	('UNIT_FW_GUNDAM',               'AS2D_SELECT_MECH_INFANTRY', 'AS2D_BIRTH_MECH_INFANTRY');

-- Biosoldiers
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_FW_BIOINFANTRY',          'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY'),
	('UNIT_FW_CLONETROOPER',         'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY'),
	('UNIT_FW_BIOTROOPER',           'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY'),
	('UNIT_FW_SUPERSOLDIERS',        'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY');

-- PMC
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_CAYM_PMC',                'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY'),
	('UNIT_FW_ELITE_MERCENARIES',    'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY'),
	('UNIT_FW_ENHANCED_MERCENARIES', 'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY'),
	('UNIT_FW_BIO_MERCENARIES',      'AS2D_SELECT_INFANTRY', 'AS2D_BIRTH_INFANTRY');

-- Archer
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_FW_ATGM',           'AS2D_SELECT_ARTILLERY', 'AS2D_BIRTH_ARTILLERY'),
    ('UNIT_FW_AUTOMATON',      'AS2D_SELECT_ARTILLERY', 'AS2D_BIRTH_ARTILLERY'),
    ('UNIT_FW_ROBOT_INFANTRY', 'AS2D_SELECT_ARTILLERY', 'AS2D_BIRTH_ARTILLERY'),
    ('UNIT_FW_COLOSSUS',       'AS2D_SELECT_ARTILLERY', 'AS2D_BIRTH_ARTILLERY');

-- Sapper
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_FW_AIRBORNE_FORCES',             'AS2D_SELECT_PARATROOPER', 'AS2D_SELECT_PARATROOPER'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER',  'AS2D_SELECT_PARATROOPER', 'AS2D_SELECT_PARATROOPER'),
    ('UNIT_FW_SPACEMARINES',                'AS2D_SELECT_PARATROOPER', 'AS2D_SELECT_PARATROOPER');

-- Gene Units
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
	('UNIT_FW_CHIMERA',     'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT'),
	('UNIT_FW_SWARM',       'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT');

-- Dino
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_RAPTOR',      'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT'),
 ('UNIT_FW_TRICERATOPS', 'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT'),
 ('UNIT_FW_TREX',        'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT');

-- Gunboats
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES 
 ('UNIT_FW_GUNBOAT',      'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP'),
 ('UNIT_FW_ADV_GUNBOAT',  'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP');

-- Destroyer
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES 
 ('UNIT_FW_NEODESTROYER',      'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP'),
 ('UNIT_FW_RAILGUN_DESTROYER', 'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP'),
 ('UNIT_FW_BIO_DESTROYER',     'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP');

-- Cruiser
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES 
 ('UNIT_FW_ARSENAL_SHIP',      'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP'),
 ('UNIT_FW_RAILGUN_CRUISER',   'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP'),
 ('UNIT_FW_BIO_CRUISER',       'AS2D_SELECT_BATTLESHIP', 'AS2D_BIRTH_BATTLESHIP');

-- Submarine
INSERT INTO UnitGameplay2DScripts (UnitType,   SelectionSound, 		FirstSelectionSound)
VALUES	
    ('UNIT_FW_MECHASUB',         'AS2D_SELECT_NUCLEAR_SUBMARINE', 	'AS2D_BIRTH_NUCLEAR_SUBMARINE'),
    ('UNIT_FW_CYBERSUB',         'AS2D_SELECT_NUCLEAR_SUBMARINE', 	'AS2D_BIRTH_NUCLEAR_SUBMARINE');

-- Carrier
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_SUPERCARRIER', 'AS2D_SELECT_CARRIER', 'AS2D_SELECT_CARRIER');

-- Airfighter
INSERT INTO UnitGameplay2DScripts
			(UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_DRONE_FIGHTER_2', 'AS2D_SELECT_JET_FIGHTER', 'AS2D_SELECT_JET_FIGHTER'),
 ('UNIT_FW_PLASMA_FIGHTER',  'AS2D_SELECT_JET_FIGHTER', 'AS2D_SELECT_JET_FIGHTER'),
 ('UNIT_FW_SPACE_FIGHTER',   'AS2D_SELECT_JET_FIGHTER', 'AS2D_SELECT_JET_FIGHTER');

 -- Bomber
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES 
 ('UNIT_FW_SUBORBITAL_BOMBER', 'AS2D_SELECT_STEALTH_BOMBER', 'AS2D_SELECT_STEALTH_BOMBER'),
 ('UNIT_FW_PLASMA_BOMBER',     'AS2D_SELECT_STEALTH_BOMBER', 'AS2D_SELECT_STEALTH_BOMBER'),
 ('UNIT_FW_SPACE_BOMBER',      'AS2D_SELECT_STEALTH_BOMBER', 'AS2D_SELECT_STEALTH_BOMBER');

-- Unique units
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_HYDRA',       'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT'),
 ('UNIT_FW_MUTANT',      'AS2D_SELECT_CARTHAGINIAN_FOREST_ELEPHANT', 'AS2D_BIRTH_CARTHAGINIAN_FOREST_ELEPHANT');

INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_NANOHIVE', 'AS2D_WONDER_APOLLO_PROGRAM', 'AS2D_BIRTH_SS_ENGINE'),
 ('UNIT_FW_MEGAHIVE', 'AS2D_WONDER_APOLLO_PROGRAM', 'AS2D_BIRTH_SS_ENGINE');

INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
VALUES
 ('UNIT_FW_HELICARRIER', 'AS2D_SELECT_CARRIER', 'AS2D_SELECT_CARRIER'),
 ('UNIT_FW_NEXUS',       'AS2D_SELECT_CARRIER', 'AS2D_SELECT_CARRIER');


----- Units Sound
INSERT OR REPLACE INTO Audio_Sounds
		(SoundID,				           Filename,	             LoadType)
VALUES	
 ('SND_UNIT_VELOCIRAPTOR_ATTACK',	'VelociraptorAttack',	'DynamicResident'),
 ('SND_UNIT_TREX',              	'trex',              	'DynamicResident'),
 ('SND_UNIT_TREX_STEP',             'trexstep',             'DynamicResident');

INSERT OR REPLACE INTO Audio_3DSounds
		(ScriptID,			                	SoundID,			 SoundType, 	MaxVolume,	MinVolume)
VALUES	
 ('AS3D_UNIT_VELOCIRAPTOR_ATTACK',	'SND_UNIT_VELOCIRAPTOR_ATTACK',	'GAME_SFX',      45,			35),
 ('AS3D_UNIT_TREX',	                'SND_UNIT_TREX',	            'GAME_SFX',      45,			35),
 ('AS3D_UNIT_TREX_STEP',	        'SND_UNIT_TREX_STEP',	        'GAME_SFX',      30,			15);

INSERT OR REPLACE INTO Audio_Sounds
		(SoundID,				           Filename,	             LoadType)
VALUES	
 ('SND_SELECT_CLONETROOPER',	'Clonetrooper_Select',	'DynamicResident');

INSERT OR REPLACE INTO Audio_2DSounds
		(ScriptID,				      SoundID,			        SoundType,	  MaxVolume,	MinVolume)
VALUES	('AS2D_SELECT_CLONETROOPER', 'SND_SELECT_CLONETROOPER',	'GAME_SFX',    45,			35);
 
INSERT OR REPLACE INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound) VALUES
('UNIT_FW_THERMOMISSILE','AS2D_SELECT_GUIDED_MISSILE','AS2D_BIRTH_GUIDED_MISSILE'),
('UNIT_FW_VAULT_RACK','AS2D_SELECT_UNIT','AS2D_BIRTH_UNIT');

