INSERT INTO Defines (Name, Value) SELECT 'FW_MODERN_COLONIST_POPULATION_CHANGE', '5';
INSERT INTO Defines (Name, Value) SELECT 'FW_MODERN_COLONIST_EXTRA_PLOTS', '5';
INSERT INTO Defines (Name, Value) SELECT 'FW_MODERN_COLONIST_FOOD_PERCENT', '50';
INSERT INTO Defines (Name, Value) SELECT 'FW_SPACE_COLONIST_POPULATION_CHANGE', '5';
INSERT INTO Defines (Name, Value) SELECT 'FW_SPACE_COLONIST_EXTRA_PLOTS', '5';
INSERT INTO Defines (Name, Value) SELECT 'FW_SPACE_COLONIST_FOOD_PERCENT', '50';


-- =======================================================================================================
--		Moderen Colonist
-- =======================================================================================================
INSERT INTO ArtDefine_UnitInfos	(Type, DamageStates, Formation)
VALUES
	('ART_DEF_UNIT_FW_MODERN_COLONIST',		1,	'Vehicle');

INSERT INTO ArtDefine_UnitInfoMemberInfos	(UnitInfoType, UnitMemberInfoType, NumMembers)
VALUES 
	('ART_DEF_UNIT_FW_MODERN_COLONIST',		'ART_DEF_UNIT_MEMBER_FW_MODERN_COLONIST2', 	1),     
	('ART_DEF_UNIT_FW_MODERN_COLONIST',		'ART_DEF_UNIT_MEMBER_FW_MODERN_COLONIST3', 	1),     
	('ART_DEF_UNIT_FW_MODERN_COLONIST',		'ART_DEF_UNIT_MEMBER_FW_MODERN_COLONIST4', 	1);

INSERT INTO ArtDefine_UnitMemberInfos	(Type, Scale, Model, MaterialTypeTag, MaterialTypeSoundOverrideTag, Domain)
VALUES 
	('ART_DEF_UNIT_MEMBER_FW_MODERN_COLONIST2', 0.08, 'GreatArtist_Late.fxsxml', 'CLOTH', 'FLESH',   NULL),  
	('ART_DEF_UNIT_MEMBER_FW_MODERN_COLONIST3', 0.05, 'Caravan_Late.fxsxml',     'CLOTH', 'FLESH',   NULL),  
	('ART_DEF_UNIT_MEMBER_FW_MODERN_COLONIST4', 0.05, 'Caravan_Late.fxsxml',     'CLOTH', 'FLESH',   NULL);  

-- =======================================================================================================
--  Space Colonist 
-- =======================================================================================================
INSERT INTO ArtDefine_UnitInfos (Type, DamageStates, Formation)
VALUES ('ART_DEF_UNIT_FW_SPACE_COLONIST', 1, 'ThreeBigGuns');
INSERT INTO ArtDefine_UnitInfoMemberInfos (UnitInfoType, UnitMemberInfoType, NumMembers)
VALUES ('ART_DEF_UNIT_FW_SPACE_COLONIST', 'ART_DEF_UNIT_MEMBER_FW_SPACE_COLONIST', 3);
INSERT INTO ArtDefine_UnitMemberInfos (Type, Scale, Model, MaterialTypeTag, MaterialTypeSoundOverrideTag)
VALUES ('ART_DEF_UNIT_MEMBER_FW_SPACE_COLONIST', 0.130000001490116, 'rangedmarine01.fxsxml', 'CLOTH', 'FLESH');
INSERT INTO ArtDefine_UnitMemberCombats (UnitMemberType, EnableActions, HasShortRangedAttack, HasStationaryMelee, HasRefaceAfterCombat, ReformBeforeCombat, HasOpponentTracking)
VALUES ('ART_DEF_UNIT_MEMBER_FW_SPACE_COLONIST', 'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady', 1, 1, 1, 1, 1);
INSERT INTO ArtDefine_UnitMemberCombatWeapons  (UnitMemberType, "Index", SubIndex, VisKillStrengthMin, VisKillStrengthMax, HitEffect, WeaponTypeTag, WeaponTypeSoundOverrideTag)
VALUES  ('ART_DEF_UNIT_MEMBER_FW_SPACE_COLONIST', 0, 0, 25.0, 50.0, 'ART_DEF_VEFFECT_TANK_IMPACT_$(TERRAIN)', 'EXPLOSIVE', 'EXPLOSION20POUND');

-- =======================================================================================================
--  Diplomat
-- =======================================================================================================
-- ArtDefine_UnitInfos
INSERT INTO ArtDefine_UnitInfos (Type, DamageStates, Formation)
VALUES ('ART_DEF_UNIT_FW_AUGMENTED_DIPLOMAT', 1, 'UnFormed');

INSERT INTO ArtDefine_UnitInfos (Type, DamageStates, Formation)
VALUES ('ART_DEF_UNIT_SAS_SCRIBE', 1, 'EarlyGreatArtist');

-- ArtDefine_UnitInfoMemberInfos
INSERT INTO ArtDefine_UnitInfoMemberInfos (UnitInfoType, UnitMemberInfoType, NumMembers)
VALUES ('ART_DEF_UNIT_FW_AUGMENTED_DIPLOMAT', 'ART_DEF_UNIT_MEMBER_SAS_SCRIBE', 1);

INSERT INTO ArtDefine_UnitInfoMemberInfos (UnitInfoType, UnitMemberInfoType, NumMembers)
VALUES ('ART_DEF_UNIT_SAS_SCRIBE', 'ART_DEF_UNIT_MEMBER_SAS_SCRIBE', 1);

-- ArtDefine_UnitMemberInfos
INSERT INTO ArtDefine_UnitMemberInfos
  (Type,                           Scale, Model,              Domain, MaterialTypeTag, MaterialTypeSoundOverrideTag)
VALUES
  ('ART_DEF_UNIT_MEMBER_SAS_SCRIBE', 0.12, 'BOSScribe.fxsxml', 'Land', 'CLOTH',        'FLESH');

-- ArtDefine_UnitMemberCombats
INSERT INTO ArtDefine_UnitMemberCombats
  (UnitMemberType,                    EnableActions,                                 DisableActions, HasRefaceAfterCombat, HasShortRangedAttack, HasLongRangedAttack, HasStationaryMelee, HasIndependentWeaponFacing, RushAttackFormation)
VALUES
  ('ART_DEF_UNIT_MEMBER_SAS_SCRIBE', 'Idle Fidget Run Death Fortify CombatReady',    NULL,           1,                   0,                    0,                   0,                  0,                         NULL);


 -- ================================================================================================================================================================
UPDATE Units SET ObsoleteTech = 'TECH_IMPLANTS' WHERE Class = 'UNITCLASS_AMBASSADOR'; 
UPDATE Units SET ObsoleteTech = 'TECH_COMPUTERS' WHERE Class = 'UNITCLASS_COLONIST';

INSERT INTO Trait_NoTrain
	(TraitType, UnitClassType)
VALUES
	('TRAIT_SUPER_CITY_STATE', 'UNITCLASS_FW_MODERN_COLONIST'),
	('TRAIT_SUPER_CITY_STATE', 'UNITCLASS_FW_SPACE_COLONIST');

INSERT INTO Unit_ClassUpgrades
	(UnitType, UnitClassType)
VALUES
	('UNIT_COLONIST', 		 			'UNITCLASS_FW_MODERN_COLONIST'),
	('UNIT_FW_MODERN_COLONIST', 		'UNITCLASS_FW_SPACE_COLONIST'),
	('UNIT_AMBASSADOR', 		 		'UNITCLASS_FW_AUGMENTED_DIPLOMAT');

INSERT INTO Unit_FreePromotions
	(UnitType, PromotionType)
VALUES
	('UNIT_FW_AUGMENTED_DIPLOMAT', 	'PROMOTION_AUGMENTED'),
	('UNIT_FW_AUGMENTED_DIPLOMAT', 	'PROMOTION_FW_CHAMELEON'),
	('UNIT_FW_MODERN_COLONIST', 	'PROMOTION_EXTRA_SIGHT_I'),
	('UNIT_FW_MODERN_COLONIST', 	'PROMOTION_DEFENSIVE_EMBARKATION'),
	('UNIT_FW_MODERN_COLONIST', 	'PROMOTION_OCEAN_MOVEMENT'),
	('UNIT_FW_SPACE_COLONIST', 		'PROMOTION_EXTRA_SIGHT_I'),
	('UNIT_FW_SPACE_COLONIST', 		'PROMOTION_DEFENSIVE_EMBARKATION'),
	('UNIT_FW_SPACE_COLONIST', 		'PROMOTION_OCEAN_MOVEMENT'),
	('UNIT_FW_SPACE_COLONIST', 		'PROMOTION_EXTENDED_PARADROP');


INSERT INTO Unit_BuildOnFound
	(UnitType, BuildingClassType)
VALUES
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_AMPHITHEATER'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_AQUEDUCT'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_COLOSSEUM'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_BARRACKS'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_GROVE'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_FORGE'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_GRANARY'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_HERBALIST'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_LIBRARY'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_LIGHTHOUSE'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_LODGE'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_HARBOR'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_MARKET'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_MONUMENT'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_SHRINE'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_TEMPLE'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_WATERMILL'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_WELL'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_WINDMILL'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_WORKSHOP'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_MILITARY_ACADEMY'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_MUSEUM'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_BROADCAST_TOWER'),
	('UNIT_FW_MODERN_COLONIST', 'BUILDINGCLASS_STOCK_EXCHANGE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_AMPHITHEATER'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_AQUEDUCT'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_COLOSSEUM'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_BARRACKS'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_GROVE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_FORGE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_GRANARY'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_HERBALIST'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_LIBRARY'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_LIGHTHOUSE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_LODGE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_HARBOR'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_MARKET'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_MONUMENT'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_SHRINE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_TEMPLE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_WATERMILL'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_WELL'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_WINDMILL'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_WORKSHOP'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_MILITARY_ACADEMY'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_MUSEUM'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_BROADCAST_TOWER'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_STOCK_EXCHANGE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_AIRPORT'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_STADIUM'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_BOMB_SHELTER'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_MILITARY_BASE'),
	('UNIT_FW_SPACE_COLONIST', 'BUILDINGCLASS_POLICE_STATION');

