--------------------------------
-- VP original change
--------------------------------
UPDATE Units SET ObsoleteTech = 'TECH_ECOLOGY' WHERE Type = 'UNIT_GUERILLA';
UPDATE Units SET ObsoleteTech = 'TECH_SEA_EXPLORE' WHERE Type = 'UNIT_ATTACK_SUBMARINE';
UPDATE Units SET ObsoleteTech = 'TECH_GENERATIVE_AI' WHERE Type = 'UNIT_MISSILE_CRUISER';
UPDATE Units SET ObsoleteTech = 'TECH_GRID_COMPUTING' WHERE Type = 'UNIT_MOBILE_SAM';
UPDATE Units SET ObsoleteTech = 'TECH_ROBOTICS' WHERE Type = 'UNIT_BAZOOKA';
UPDATE Units SET ObsoleteTech = 'TECH_ARTIFICIAL_ENVIRONMENTS' WHERE Type = 'UNIT_MECHANIZED_INFANTRY';
UPDATE Units SET ObsoleteTech = 'TECH_FUTURE_BALLISTICS' WHERE Type = 'UNIT_GUIDED_MISSILE';
UPDATE Units SET ObsoleteTech = 'TECH_ROBOTICS' WHERE Type = 'UNIT_HELICOPTER_GUNSHIP';
UPDATE Units SET ObsoleteTech = 'TECH_ROBOTICS' WHERE Type = 'UNIT_PREDATOR_DRONE';
UPDATE Units SET ObsoleteTech = 'TECH_PARTICLE_PHYSICS' WHERE Type = 'UNIT_ROCKET_ARTILLERY';

UPDATE Units SET PrereqTech = 'TECH_ENERGY_THEORY', Cost = 20000 WHERE Type = 'UNIT_SS_BOOSTER';
UPDATE Units SET PrereqTech = 'TECH_COMPUTRONIUM', Cost = 22500 WHERE Type = 'UNIT_SS_STASIS_CHAMBER';
UPDATE Units SET PrereqTech = 'TECH_SPACE_COLONIZATION', Cost = 22500 WHERE Type = 'UNIT_SS_COCKPIT';
UPDATE Units SET PrereqTech = 'TECH_SPACE_COLONIZATION', Cost = 22500 WHERE Type = 'UNIT_SS_ENGINE';
UPDATE Units SET PrereqTech = 'TECH_NANOTECHNOLOGY' WHERE Type = 'UNIT_STEALTH_BOMBER';
UPDATE Units SET PrereqTech = 'TECH_NANOTECHNOLOGY' WHERE Type = 'UNIT_ADVJET';
UPDATE Units SET PrereqTech = 'TECH_INTERNET' WHERE Type = 'UNIT_SUPERCARRIER';
UPDATE Units SET PrereqTech = 'TECH_NUCLEAR_FUSION', Combat = 145, BaseLandAirDefense = 25, Cost = 4250, FaithCost = 2250 WHERE Type = 'UNIT_MECH';
UPDATE Units SET PrereqTech = 'TECH_SEA_EXPLORE' WHERE Type = 'UNIT_NUCLEAR_SUBMARINE';

DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_XCOM_SQUAD' AND PromotionType = 'PROMOTION_EXTENDED_PARADROP';
UPDATE Units SET PrereqTech = 'TECH_PLANETARY_MIGRATION', Cost = 2950, FaithCost = 2250, Combat = 115, Moves = 4 WHERE Type = 'UNIT_XCOM_SQUAD';

UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_CAYM_PMC' WHERE UnitType = 'UNIT_GUERILLA';
UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_FW_AIRBORNE_FORCES' WHERE UnitType = 'UNIT_MARINE';
UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_FW_RAILGUN_TANK' WHERE UnitType = 'UNIT_MODERN_ARMOR';
--------------------------------------
-- Future
--------------------------------------
DELETE FROM Unit_ClassUpgrades
WHERE UnitType IN ('UNIT_JET_FIGHTER','UNIT_ADVJET');

INSERT INTO Unit_ClassUpgrades (UnitType, UnitClassType)
SELECT 'UNIT_JET_FIGHTER', u.Class
FROM Units u
WHERE u.Type = 'UNIT_ADVJET'
  AND EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_JET_FIGHTER')
  AND NOT EXISTS (SELECT 1 FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_JET_FIGHTER');

INSERT INTO Unit_ClassUpgrades (UnitType, UnitClassType)
SELECT 'UNIT_ADVJET', 'UNITCLASS_FW_DRONE_FIGHTER_2'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_ADVJET')
  AND EXISTS (SELECT 1 FROM UnitClasses WHERE Type = 'UNITCLASS_FW_DRONE_FIGHTER_2')
  AND NOT EXISTS (SELECT 1 FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_ADVJET');

INSERT INTO Unit_ClassUpgrades (UnitType, UnitClassType)
SELECT 'UNIT_JET_FIGHTER', 'UNITCLASS_FW_DRONE_FIGHTER_2'
WHERE NOT EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_ADVJET')
  AND EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_JET_FIGHTER')
  AND EXISTS (SELECT 1 FROM UnitClasses WHERE Type = 'UNITCLASS_FW_DRONE_FIGHTER_2')
  AND NOT EXISTS (SELECT 1 FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_JET_FIGHTER');



--==========================================================================================================================	
-- UNITS
--==========================================================================================================================	
-- =========================================================
-- Space ship carrier
-- =========================================================
INSERT OR IGNORE INTO SpecialUnits (Type, Description, Valid, CityLoad)
VALUES ('SPECIALUNIT_SPACEAIRSHIP','TXT_KEY_SPECIALUNIT_SPACESHIP',1,1);
UPDATE SpecialUnits SET Valid=1, CityLoad=1 WHERE Type='SPECIALUNIT_SPACEAIRSHIP';

UPDATE Units SET Special = 'SPECIALUNIT_SPACEAIRSHIP' WHERE Type = 'UNIT_FW_SPACE_PLANE';

INSERT INTO SpecialUnit_CarrierUnitAI (SpecialUnitType, UnitAIType)
SELECT 'SPECIALUNIT_SPACEAIRSHIP','UNITAI_CARRIER_SEA'
WHERE EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='SpecialUnit_CarrierUnitAI');
----------------------------------------------------------------------------------------------------------------------

INSERT INTO Trait_FreePromotionUnitClass
	(TraitType, UnitClassType, PromotionType)
VALUES
	('TRAIT_TERROR', 'UNITCLASS_FW_APACHE',    'PROMOTION_MONGOL_TERROR'),
    ('TRAIT_TERROR', 'UNITCLASS_FW_VERTOL',    'PROMOTION_MONGOL_TERROR'),
    ('TRAIT_TERROR', 'UNITCLASS_FW_HOVERTANK', 'PROMOTION_MONGOL_TERROR');

--------------------------------
-- Unit_FreePromotions
--------------------------------
INSERT INTO Unit_FreePromotions 
    (UnitType, PromotionType)
VALUES 
    -- Missile
    ('UNIT_FW_CLUSTER_MISSILE',         'PROMOTION_FW_SPLASH_DAMAGE_1'),
    ('UNIT_FW_CLUSTER_MISSILE',         'PROMOTION_AIR_SIEGE_1'),
    ('UNIT_FW_HYPERMISSILE',            'PROMOTION_FW_SPLASH_DAMAGE_2'),
    ('UNIT_FW_HYPERMISSILE',            'PROMOTION_PLASMA_EVASION'),
    ('UNIT_FW_HYPERMISSILE',            'PROMOTION_AIR_SIEGE_1'),
    ('UNIT_FW_THERMOMISSILE',           'PROMOTION_FW_SPLASH_DAMAGE_3'),
    ('UNIT_FW_THERMOMISSILE',           'PROMOTION_PLASMA_EVASION'),
    ('UNIT_FW_THERMOMISSILE',           'PROMOTION_AIR_SIEGE_1'),
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED', 'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED', 'PROMOTION_AIR_SIEGE_1'),
    ('UNIT_FW_RAILGUN_MISSILE',         'PROMOTION_SUBORBITAL_EVASION'),
    ('UNIT_FW_RAILGUN_MISSILE',         'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_RAILGUN_MISSILE',         'PROMOTION_AIR_SIEGE_1'),
    ('UNIT_FW_GOD_ROD',                 'PROMOTION_FW_SPLASH_DAMAGE_4'),
    ('UNIT_FW_GOD_ROD',                 'PROMOTION_EVASION_I'),
    ('UNIT_FW_GOD_ROD',                 'PROMOTION_SPACE_EVASION'),
    ('UNIT_FW_GOD_ROD',                 'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_GOD_ROD2',                'PROMOTION_FW_SPLASH_DAMAGE_5'),
    ('UNIT_FW_GOD_ROD2',                'PROMOTION_SPACE_EVASION'),
    ('UNIT_FW_GOD_ROD2',                'PROMOTION_EVASION_I'),
    ('UNIT_FW_GOD_ROD2',                'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_HYDROGEN_BOMB',           'PROMOTION_NUCLEAR_SILO'),
    ('UNIT_FW_HYDROGEN_BOMB',           'PROMOTION_SUBORBITAL_EVASION'),
    ('UNIT_FW_HYDROGEN_BOMB',           'PROMOTION_EVASION_I'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',      'PROMOTION_NUCLEAR_SILO'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',      'PROMOTION_SPACE_EVASION'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',      'PROMOTION_EVASION_I'),
    -- Tank
    ('UNIT_FW_RAILGUN_TANK',           'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_RAILGUN_TANK',           'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_RAILGUN_TANK',           'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_MECH',                      'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_MECH',                      'PROMOTION_FW_NUCLEAR_SMR'),   
    -- Drone
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_MARCH'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_AIR_RECON'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_MARCH'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_NO_DEFENSIVE_BONUSES'),
    --Helicopter
    ('UNIT_FW_APACHE',                 'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_APACHE',                 'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_APACHE',                 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_APACHE',                 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_APACHE',                 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_APACHE',                 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_APACHE',                 'PROMOTION_ONLY_DEFENSIVE'),
	('UNIT_FW_APACHE',                 'PROMOTION_SCOUT_XP_PILLAGE'),
	('UNIT_FW_APACHE',                 'PROMOTION_SKIRMISHER_DOCTRINE'),
	('UNIT_FW_APACHE',                 'PROMOTION_HELI_AMBUSH_1'),
	('UNIT_FW_VERTOL',                 'PROMOTION_SKIRMISHER_DOCTRINE'),
	('UNIT_FW_VERTOL',                 'PROMOTION_SCOUT_XP_PILLAGE'),
	('UNIT_FW_VERTOL',                 'PROMOTION_HELI_AMBUSH_1'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_ONLY_DEFENSIVE'),
	('UNIT_FW_HOVERTANK',              'PROMOTION_SKIRMISHER_DOCTRINE'),
	('UNIT_FW_HOVERTANK',              'PROMOTION_SCOUT_XP_PILLAGE'),
	('UNIT_FW_HOVERTANK',              'PROMOTION_HELI_AMBUSH_1'),
    -- Sam
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_CARGO_II'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_INTERCEPTION_III'), 
    ('UNIT_FW_CYBERSAM',               'PROMOTION_CARGO_III'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_CARGO_I'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_CARGO_III'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_FREE_PILLAGE_MOVES'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_COVER_1'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_INTERCEPTION_III'), 
    ('UNIT_FW_CRAWLER',                'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_FW_NUCLEAR_SMR'),     
    -- Siege
    ('UNIT_FW_HIMARS', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_HIMARS', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_HIMARS', 'PROMOTION_CITY_SIEGE'),
    ('UNIT_FW_HIMARS', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HIMARS', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_HIMARS', 'PROMOTION_SIGHT_PENALTY'),
    ('UNIT_FW_HIMARS', 'PROMOTION_SIEGE_INACCURACY'),
    ('UNIT_FW_HIMARS', 'PROMOTION_COVER_1'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_CITY_SIEGE'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_SIGHT_PENALTY'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_SIEGE_INACCURACY'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_COVER_1'),   
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_ANGEL', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_ANGEL', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_ANGEL', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_ANGEL', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_ANGEL', 'PROMOTION_CITY_SIEGE'),
    ('UNIT_FW_ANGEL', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_ANGEL', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_ANGEL', 'PROMOTION_FREE_PILLAGE_MOVES'),
    ('UNIT_FW_ANGEL', 'PROMOTION_SIEGE_INACCURACY'),
    ('UNIT_FW_ANGEL', 'PROMOTION_COVER_1'),
    ('UNIT_FW_ANGEL', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_ANGEL', 'PROMOTION_FW_NUCLEAR_SMR'),   
    -- Armor solider
    ('UNIT_FW_POWER_ARMOR_INFANTRY', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_BATTLESUIT', 'PROMOTION_FORMATION_1'),
    ('UNIT_FW_BATTLESUIT', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_FORMATION_1'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_EXTRA_SIGHT_I'),
    -- Bio soldier
    ('UNIT_FW_BIOINFANTRY', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_BIOINFANTRY', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_CLONETROOPER', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_CLONETROOPER', 'PROMOTION_MARCH'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_MARCH'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_RIVAL_TERRITORY'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_FW_CHAMELEON'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_FW_MASTER_RACE'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_MARCH'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_RIVAL_TERRITORY'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_FIELD_WORKS_3'),
    -- PMC
    ('UNIT_CAYM_PMC', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_CAYM_PMC', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_CAYM_PMC', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_CAYM_PMC', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_FIELD_WORKS_3'),
    -- Archer
    ('UNIT_FW_ATGM', 'PROMOTION_COVERING_FIRE_2'),
    ('UNIT_FW_ATGM', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_ATGM', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_ATGM', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_COVERING_FIRE_2'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_FW_NETWORKED'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_COVERING_FIRE_2'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_FW_NETWORKED'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_COVERING_FIRE_2'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_FW_NETWORKED'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    -- Sapper
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_COMMANDO'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_SCOUT_XP_PILLAGE'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_ATTACK_BONUS'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_EXTENDED_PARADROP'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_COMMANDO'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_ATTACK_BONUS'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_SCOUT_XP_PILLAGE'),
    ('UNIT_XCOM_SQUAD','PROMOTION_COMMANDO'),
    ('UNIT_XCOM_SQUAD','PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_COMMANDO'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_SAPPER'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_ATTACK_BONUS'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_SCOUT_XP_PILLAGE'),
    -- Gene units
    ('UNIT_FW_CHIMERA', 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_MARCH'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_NEUROTIC_POISON'),
    ('UNIT_FW_SWARM',   'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_SWARM',   'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_SWARM',   'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_SWARM',   'PROMOTION_NEUROTIC_POISON'),
    -- Dino
    ('UNIT_FW_TREX', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_TREX', 'PROMOTION_FW_APEXPREDATOR'),
    ('UNIT_FW_TREX', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_TRICERATOPS', 'PROMOTION_COVER_1'),
    ('UNIT_FW_TRICERATOPS', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_TRICERATOPS', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_RAPTOR', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_RAPTOR', 'PROMOTION_MOHAWK'),
    ('UNIT_FW_RAPTOR', 'PROMOTION_IGNORE_TERRAIN_COST'),
    -- Gunboat
    ('UNIT_FW_GUNBOAT', 			'PROMOTION_OCEAN_HALF_MOVES'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_EXTENDED_PARADROP'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_EXTRA_SIGHT_II'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_ORBITAL_DROP'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_EXTRA_SIGHT_II'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_OCEAN_HALF_MOVES'),
	('UNIT_FW_ADV_GUNBOAT',         'PROMOTION_CARGO_I'),
    --Destroyer
	('UNIT_FW_NEODESTROYER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_NAVIGATOR_1'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_INTERCEPTION_I'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_INTERCEPTION_II'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_INTERCEPTION_III'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_CARGO_I'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_CARGO_III'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_ANTI_SUBMARINE_II'),
    ('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_NAVIGATOR_1'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_INTERCEPTION_I'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_INTERCEPTION_II'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_INTERCEPTION_III'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_CARGO_I'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_CARGO_III'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_ANTI_SUBMARINE_II'),
    ('UNIT_FW_BIO_DESTROYER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_NAVIGATOR_1'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_INTERCEPTION_I'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_INTERCEPTION_II'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_INTERCEPTION_III'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_CARGO_I'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_CARGO_III'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_ANTI_SUBMARINE_II'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_MARCH'),
    -- Cruiser
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_MARCH'),
    -- Air fighter
    ('UNIT_FW_DRONE_FIGHTER_2','PROMOTION_INTERCEPTION_1'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_AIR_SWEEP'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_AIR_RECON'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_AIR_MISFIRE'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_ANTI_HELICOPTER'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_RECON_RANGE_2'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_STEALTH'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_INTERCEPTION_1'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_AIR_SWEEP'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_AIR_RECON'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_AIR_MISFIRE'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_ANTI_HELICOPTER'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_RECON_RANGE_2'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_STEALTH'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_INTERCEPTION_1'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_AIR_SWEEP'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_AIR_RECON'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_AIR_MISFIRE'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_ANTI_HELICOPTER'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_STEALTH'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_RECON_RANGE_2'),
    -- Air bomber
    ('UNIT_FW_SUBORBITAL_BOMBER', 'PROMOTION_SUBORBITAL_EVASION'),
    ('UNIT_FW_SUBORBITAL_BOMBER', 'PROMOTION_STEALTH'),
    ('UNIT_FW_SUBORBITAL_BOMBER', 'PROMOTION_AIR_RECON'),
    ('UNIT_FW_PLASMA_BOMBER',        'PROMOTION_PLASMA_EVASION'),
    ('UNIT_FW_PLASMA_BOMBER',        'PROMOTION_STEALTH'),
    ('UNIT_FW_PLASMA_BOMBER',        'PROMOTION_AIR_RECON'),
    ('UNIT_FW_SPACE_BOMBER',        'PROMOTION_SPACE_EVASION'),
    ('UNIT_FW_SPACE_BOMBER',        'PROMOTION_STEALTH'),
    ('UNIT_FW_SPACE_BOMBER',        'PROMOTION_AIR_RECON'),
    -- Carrier
    ('UNIT_SUPERCARRIER', 'PROMOTION_FW_NUCLEAR_SMR'),           
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_IV'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_SUPERCARRIER', 'PROMOTION_ANTI_SUBMARINE_I'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_FW_NUCLEAR_SMR'),      
    -- Submarine
    ('UNIT_FW_MECHASUB', 'PROMOTION_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_CAN_MOVE_IMPASSABLE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_SILENT_HUNTER'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_FW_NUCLEAR_SMR'),           
    ('UNIT_FW_CYBERSUB', 'PROMOTION_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_CAN_MOVE_IMPASSABLE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_SILENT_HUNTER'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_FW_NUCLEAR_SMR'),   
    ('UNIT_FW_CYBERSUB', 'PROMOTION_RIVAL_TERRITORY'),
    -- Unique units
    ('UNIT_FW_MUTANT', 'PROMOTION_MARCH'),
    ('UNIT_FW_MUTANT', 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_MUTANT', 'PROMOTION_FW_MUTATION'),   
    ('UNIT_FW_MUTANT', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_HYDRA',  'PROMOTION_MARCH'),
    ('UNIT_FW_HYDRA',  'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_HYDRA',  'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_HYDRA',  'PROMOTION_COVER_1'),
    ('UNIT_FW_HYDRA',  'PROMOTION_MECH'),
    ('UNIT_FW_HYDRA',  'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_FW_HYDRA',  'PROMOTION_FW_MUTATION'),   
    ('UNIT_FW_HYDRA',  'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_HYDRA',  'PROMOTION_FW_NUCLEAR_SMR'),         

    ('UNIT_FW_NANOHIVE', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_FW_NANOHIVE_PROMOTION'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_MARCH'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_FW_NANOHIVE_PROMOTION'),

    ('UNIT_FW_HELICARRIER', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_COVER_1'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_ARMOR_PLATING_3'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_FW_NUCLEAR_SMR'),         
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_NEXUS', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_NEXUS', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_NEXUS', 'PROMOTION_COVER_1'),
    ('UNIT_FW_NEXUS', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_NEXUS', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_NEXUS', 'PROMOTION_ARMOR_PLATING_3'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_NANOHIVE_PROMOTION'),
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_NEXUS'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_IV'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_NUCLEAR_SMR'),
    -- Vault Rack
    ('UNIT_FW_VAULT_RACK',                'PROMOTION_CARGO_III');


-- Building Required for purchase
INSERT INTO	Unit_BuildingClassPurchaseRequireds
		(UnitType, 				                BuildingClassType)
VALUES
    -- Missile
    ('UNIT_FW_CLUSTER_MISSILE',             'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CLUSTER_MISSILE',             'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_HYPERMISSILE',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HYPERMISSILE',                'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_THERMOMISSILE',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_THERMOMISSILE',               'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED',	    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED',     'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_RAILGUN_MISSILE',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_RAILGUN_MISSILE',             'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_GOD_ROD',                     'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    ('UNIT_FW_GOD_ROD',                     'BUILDINGCLASS_FW_ORBITAL_HABITAT'),
    ('UNIT_FW_GOD_ROD2',                    'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    ('UNIT_FW_GOD_ROD2',                    'BUILDINGCLASS_FW_ORBITAL_HABITAT'),
    -- Tank
    ('UNIT_FW_RAILGUN_TANK',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_RAILGUN_TANK',                'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_ZEKE',                        'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ZEKE',                        'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_MECH',                           'BUILDINGCLASS_FW_NANOFORGE'),
    -- Drone
    ('UNIT_FW_MODERN_DRONE',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_MODERN_DRONE',	            'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_HYBRID_DRONE',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HYBRID_DRONE',	            'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_BIODRONE',                    'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_BIODRONE',                    'BUILDINGCLASS_AIRPORT'),
    -- Helicopter
    ('UNIT_FW_APACHE',	                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_APACHE',	                    'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_VERTOL',                      'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_VERTOL',                      'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_VERTOL',                      'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_HOVERTANK',                   'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HOVERTANK',                   'BUILDINGCLASS_FW_NANOFORGE'),
    -- Sam
    ('UNIT_FW_MODERN_MOBILE_SAM',	        'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CYBERSAM',	                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CYBERSAM',                    'BUILDINGCLASS_FW_BIOCOMPUTER'),
    ('UNIT_FW_CRAWLER', 	                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CRAWLER', 	                'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_CRAWLER', 	                'BUILDINGCLASS_FW_BIOCOMPUTER'),
    -- Siage
    ('UNIT_FW_HIMARS',                      'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_MECH_ARTILLERY',              'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_MECH_ARTILLERY',              'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_ANGEL',                       'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ANGEL',                       'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_ANGEL',                       'BUILDINGCLASS_FW_FUSION_PLANT'),
    -- Armored soldiers
    ('UNIT_FW_POWER_ARMOR_INFANTRY',	    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_BATTLESUIT',                  'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_BATTLESUIT',                  'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_GUNDAM',                      'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_GUNDAM',                      'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_GUNDAM',                      'BUILDINGCLASS_FW_LAUNCH_FACILITY'),
    ('UNIT_FW_GUNDAM',                      'BUILDINGCLASS_FW_ORBITAL_MINING'),
    -- Biosoldiers
    ('UNIT_FW_BIOINFANTRY',                 'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_BIOINFANTRY',                 'BUILDINGCLASS_FW_BIO_AUG_CLINIC'),
    ('UNIT_FW_CLONETROOPER',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CLONETROOPER',                'BUILDINGCLASS_FW_BIO_AUG_CLINIC'),
    ('UNIT_FW_CLONETROOPER',	            'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_BIOTROOPER',                  'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_BIOTROOPER',                  'BUILDINGCLASS_FW_BIO_AUG_CLINIC'),
    ('UNIT_FW_BIOTROOPER',                  'BUILDINGCLASS_FW_BIOMOD_TANK'),
    ('UNIT_FW_SUPERSOLDIERS',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SUPERSOLDIERS',               'BUILDINGCLASS_FW_BIO_AUG_CLINIC'),
    ('UNIT_FW_SUPERSOLDIERS',               'BUILDINGCLASS_FW_BIOMOD_TANK'),
    -- Archer
    ('UNIT_FW_ATGM',	                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_AUTOMATON',                   'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ROBOT_INFANTRY',              'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ROBOT_INFANTRY',              'BUILDINGCLASS_FW_DRONE_HIVE'),
    ('UNIT_FW_COLOSSUS',                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_COLOSSUS',                    'BUILDINGCLASS_FW_DRONE_HIVE'),
    ('UNIT_FW_COLOSSUS',                    'BUILDINGCLASS_FW_BIGBROTHER_CONTROL'),
    -- Sapper
    ('UNIT_FW_AIRBORNE_FORCES',             'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_AIRBORNE_FORCES',             'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER',  'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER',  'BUILDINGCLASS_FW_LAUNCH_FACILITY'),
    ('UNIT_FW_SPACEMARINES',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACEMARINES',                'BUILDINGCLASS_FW_LAUNCH_FACILITY'),
    ('UNIT_FW_SPACEMARINES',                'BUILDINGCLASS_FW_ORBITAL_MINING'),
    -- Gene units
    ('UNIT_FW_CHIMERA',                     'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_CHIMERA',                     'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_SWARM',                       'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_SWARM',                       'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    -- Dino
    ('UNIT_FW_TREX',                        'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_TRICERATOPS',                 'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_RAPTOR',                      'BUILDINGCLASS_FW_CLONE_LAB'),
    -- Gunboat
    ('UNIT_FW_GUNBOAT',                     'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_GUNBOAT',                     'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_ADV_GUNBOAT',                 'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_ADV_GUNBOAT',                 'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    -- Destroyer
    ('UNIT_FW_NEODESTROYER',                'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_RAILGUN_DESTROYER',           'BUILDINGCLASS_FW_TIDAL_PORT'),
    ('UNIT_FW_RAILGUN_DESTROYER',           'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_BIO_DESTROYER',               'BUILDINGCLASS_FW_TIDAL_PORT'),
    ('UNIT_FW_BIO_DESTROYER',               'BUILDINGCLASS_SEAPORT'),
    -- Cruiser
    ('UNIT_FW_ARSENAL_SHIP',                'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_RAILGUN_CRUISER',             'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_RAILGUN_CRUISER',             'BUILDINGCLASS_FW_TIDAL_PORT'),
    ('UNIT_FW_BIO_CRUISER',                 'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_BIO_CRUISER',                 'BUILDINGCLASS_FW_TIDAL_PORT'),
    ('UNIT_FW_BIO_CRUISER',                 'BUILDINGCLASS_FW_BIOMOD_TANK'),
    -- Submarine
    ('UNIT_FW_MECHASUB',                    'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_CYBERSUB',                    'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_CYBERSUB',                    'BUILDINGCLASS_FW_TIDAL_PORT'),
    ('UNIT_FW_CYBERSUB',                    'BUILDINGCLASS_FW_QUANTUM_LINK'),
     -- Carrier
    ('UNIT_FW_SUPERCARRIER',                'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_SUPERCARRIER',                'BUILDINGCLASS_AIRPORT'),
    -- Air fighter
    ('UNIT_FW_DRONE_FIGHTER_2',	            'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_DRONE_FIGHTER_2',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_PLASMA_FIGHTER',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_PLASMA_FIGHTER',	            'BUILDINGCLASS_FW_SKYRAIL_HUB'),
    ('UNIT_FW_SPACE_FIGHTER',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACE_FIGHTER',	            'BUILDINGCLASS_FW_SKYRAIL_HUB'),
    ('UNIT_FW_SPACE_FIGHTER',               'BUILDINGCLASS_FW_ORBITAL_MINING'),
    -- Air Bomber
    ('UNIT_FW_SUBORBITAL_BOMBER',           'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_SUBORBITAL_BOMBER',           'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_PLASMA_BOMBER',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_PLASMA_BOMBER',               'BUILDINGCLASS_FW_SKYRAIL_HUB'),
    ('UNIT_FW_SPACE_BOMBER',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACE_BOMBER',                'BUILDINGCLASS_FW_SKYRAIL_HUB'),
    ('UNIT_FW_SPACE_BOMBER',                'BUILDINGCLASS_FW_ORBITAL_MINING'),
     -- Unique units
    ('UNIT_FW_MUTANT',	                    'BUILDINGCLASS_FW_TRANSGENIC_NURSERY'),
    ('UNIT_FW_HYDRA',                       'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_NANOHIVE',                    'BUILDINGCLASS_FW_DRONE_HIVE'),
    ('UNIT_FW_MEGAHIVE',                    'BUILDINGCLASS_FW_BIGBROTHER_CONTROL'),
    ('UNIT_FW_HELICARRIER',                 'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HELICARRIER',                 'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    ('UNIT_FW_NEXUS',                       'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_NEXUS',                       'BUILDINGCLASS_FW_ORBITAL_HABITAT');

-----------------------------------------------------------------
-- Military flags
-----------------------------------------------------------------
UPDATE Units
SET MilitarySupport = 1, MilitaryProduction = 1
WHERE CombatClass IN (
  SELECT Type FROM UnitCombatInfos WHERE IsMilitary = 1
) OR Class IN (
  'UNITCLASS_FW_CLUSTER_MISSILE',
  'UNITCLASS_FW_HYPERMISSILE',
  'UNITCLASS_FW_THERMOMISSILE',
  'UNITCLASS_FW_ADVANCED_MISSILE_GUIDED',
  'UNITCLASS_FW_RAILGUN_MISSILE',
  'UNITCLASS_FW_GOD_ROD',
  'UNITCLASS_FW_GOD_ROD2'
);

-- Air units and missiles don't cost supply
UPDATE Units
SET NoSupply = 1
WHERE CombatClass IN (
  SELECT Type FROM UnitCombatInfos WHERE IsAerial = 1
) OR Class IN (
  'UNITCLASS_FW_CLUSTER_MISSILE',
  'UNITCLASS_FW_HYPERMISSILE',
  'UNITCLASS_FW_THERMOMISSILE',
  'UNITCLASS_FW_ADVANCED_MISSILE_GUIDED',
  'UNITCLASS_FW_RAILGUN_MISSILE',
  'UNITCLASS_FW_GOD_ROD',
  'UNITCLASS_FW_GOD_ROD2'
);

-- Rack: exclude from military rules entirely
DELETE FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_FW_VAULT_RACK';

UPDATE Units
SET MilitarySupport = 0, MilitaryProduction = 0, NoSupply = 1
WHERE Type = 'UNIT_FW_VAULT_RACK';

-- (선택) 랙 정리
UPDATE Units
SET CombatClass = NULL, ObsoleteTech = NULL
WHERE Type = 'UNIT_FW_VAULT_RACK';

-----------------------------------------------------------------
-- Barbarians cannot use/spawn these classes
-----------------------------------------------------------------
INSERT INTO Civilization_UnitClassOverrides (CivilizationType, UnitClassType)
SELECT 'CIVILIZATION_BARBARIAN', Type
FROM UnitClasses
WHERE Type IN (
  'UNITCLASS_FW_MODERN_COLONIST',
  'UNITCLASS_FW_SPACE_COLONIST',
  'UNITCLASS_FW_AUGMENTED_DIPLOMAT',

  -- Scouting line
  'UNITCLASS_FW_AIRBORNE_FORCES',
  'UNITCLASS_FW_ORBITAL_DROP_SHOCK_TROOPER',
  'UNITCLASS_FW_SPACEMARINES',

  -- Siege
  'UNITCLASS_FW_HIMARS',
  'UNITCLASS_FW_MECH_ARTILLERY',
  'UNITCLASS_FW_ANGEL',

  -- Airrecon
  'UNITCLASS_FW_MODERN_DRONE',
  'UNITCLASS_FW_HYBRID_DRONE',
  'UNITCLASS_FW_BIODRONE',

  -- Anti-Air Units
  'UNITCLASS_FW_MODERN_MOBILE_SAM',
  'UNITCLASS_FW_CYBERSAM',
  'UNITCLASS_FW_CRAWLER',

  -- Air & Missiles
  'UNITCLASS_FW_DRONE_FIGHTER_2',
  'UNITCLASS_FW_PLASMA_FIGHTER',
  'UNITCLASS_FW_SPACE_FIGHTER',
  'UNITCLASS_FW_SUBORBITAL_BOMBER',
  'UNITCLASS_FW_PLASMA_BOMBER',
  'UNITCLASS_FW_SPACE_BOMBER',
  'UNITCLASS_FW_CLUSTER_MISSILE',
  'UNITCLASS_FW_HYPERMISSILE',
  'UNITCLASS_FW_THERMOMISSILE',
  'UNITCLASS_FW_ADVANCED_MISSILE_GUIDED',
  'UNITCLASS_FW_RAILGUN_MISSILE',
  'UNITCLASS_FW_GOD_ROD',
  'UNITCLASS_FW_GOD_ROD2',
  'UNITCLASS_FW_HYDROGEN_BOMB',
  'UNITCLASS_FW_THERMONUCLEAR_BOMB',

  -- Misc.
  'UNITCLASS_FW_SUPERCARRIER',
  'UNITCLASS_FW_HELICARRIER',
  'UNITCLASS_FW_NEXUS',
  'UNITCLASS_FW_VAULT_RACK'
);

INSERT INTO Civilization_UnitClassOverrides
	(CivilizationType, UnitClassType)
SELECT
	'CIVILIZATION_MINOR', Type
FROM UnitClasses
WHERE Type IN (
	-- Late settlers
    'UNITCLASS_FW_MODERN_COLONIST',
    'UNITCLASS_FW_SPACE_COLONIST',
	-- Diplo units
    'UNITCLASS_FW_AUGMENTED_DIPLOMAT',
    -- Dino
    'UNITCLASS_FW_RAPTOR',
    'UNITCLASS_FW_TRICERATOPS',
    'UNITCLASS_FW_TREX',
	-- Carriers
	'UNITCLASS_SUPERCARRIER',
	-- Nukes&ICBM
	'UNITCLASS_FW_GOD_ROD',
    'UNITCLASS_FW_GOD_ROD2',
    'UNITCLASS_FW_HYDROGEN_BOMB',
    'UNITCLASS_FW_THERMONUCLEAR_BOMB'
);