--------------------------------
-- VP original change
--------------------------------
UPDATE Units SET ObsoleteTech = 'TECH_MOBILE_TACTICS' WHERE Type = 'UNIT_GUERILLA';
UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_CAYM_PMC' WHERE UnitType = 'UNIT_GUERILLA';
UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_FW_AIRBORNE_FORCES' WHERE UnitType = 'UNIT_MARINE';
UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_FW_RAILGUN_TANK' WHERE UnitType = 'UNIT_MODERN_ARMOR';

UPDATE Units SET PrereqTech = 'TECH_ENERGY_THEORY', Cost = 20000 WHERE Type = 'UNIT_SS_BOOSTER';
UPDATE Units SET PrereqTech = 'TECH_COMPUTRONIUM', Cost = 22500 WHERE Type = 'UNIT_SS_STASIS_CHAMBER';
UPDATE Units SET PrereqTech = 'TECH_SPACE_COLONIZATION', Cost = 22500 WHERE Type = 'UNIT_SS_COCKPIT';
UPDATE Units SET PrereqTech = 'TECH_SPACE_COLONIZATION', Cost = 22500 WHERE Type = 'UNIT_SS_ENGINE';
UPDATE Units SET PrereqTech = 'TECH_NANOTECHNOLOGY' WHERE Type = 'UNIT_STEALTH_BOMBER';
UPDATE Units SET PrereqTech = 'TECH_NANOTECHNOLOGY' WHERE Type = 'UNIT_ADVJET';
UPDATE Units SET PrereqTech = 'TECH_INTERNET' WHERE Type = 'UNIT_SUPERCARRIER';
UPDATE Units SET PrereqTech = 'TECH_NUCLEAR_FUSION', Combat = 145, BaseLandAirDefense = 25, Cost = 4250, FaithCost = 2250 WHERE Type = 'UNIT_MECH';
UPDATE Units SET PrereqTech = 'TECH_QUANTUM_COMPUTERS' WHERE Type = 'UNIT_NUCLEAR_SUBMARINE';
UPDATE Units SET PrereqTech = 'TECH_PROMETHEUS_PROGRAM', Cost = 2950, FaithCost = 2250, Combat = 125, Moves = 3 WHERE Type = 'UNIT_XCOM_SQUAD';

UPDATE Units SET ObsoleteTech = 'TECH_COGNITIVE_TECH' WHERE Type = 'UNIT_MISSILE_CRUISER';
UPDATE Units SET ObsoleteTech = 'TECH_GEN_MANIP' WHERE Type = 'UNIT_MOBILE_SAM';
UPDATE Units SET ObsoleteTech = 'TECH_ROBOTICS' WHERE Type = 'UNIT_BAZOOKA';
UPDATE Units SET ObsoleteTech = 'TECH_ARTIFICIAL_ENVIRONMENTS' WHERE Type = 'UNIT_MECHANIZED_INFANTRY';
UPDATE Units SET ObsoleteTech = 'TECH_FUTURE_BALLISTICS' WHERE Type = 'UNIT_GUIDED_MISSILE';
UPDATE Units SET ObsoleteTech = 'TECH_ROBOTICS' WHERE Type = 'UNIT_HELICOPTER_GUNSHIP';
UPDATE Units SET ObsoleteTech = 'TECH_SUPERCOMPUTERS' WHERE Type = 'UNIT_PREDATOR_DRONE';
UPDATE Units SET ObsoleteTech = 'TECH_PARTICLE_PHYSICS' WHERE Type = 'UNIT_ROCKET_ARTILLERY';

--------------------------------------
-- Future
--------------------------------------
INSERT OR IGNORE INTO UnitPromotions_UnitCombats
    (PromotionType, UnitCombatType)
SELECT PromotionType, 'UNITCOMBAT_HELICOPTER'
FROM UnitPromotions_UnitCombats
WHERE UnitCombatType = 'UNITCOMBAT_RECON';

--==========================================================================================================================	
-- UNITS
--==========================================================================================================================	
-- =========================================================
-- Space ship carrier
-- =========================================================
INSERT OR IGNORE INTO SpecialUnits (Type, Description, Valid, CityLoad)
VALUES ('SPECIALUNIT_SPACESHIP','TXT_KEY_SPECIALUNIT_SPACESHIP',1,1);
UPDATE SpecialUnits SET Valid=1, CityLoad=1 WHERE Type='SPECIALUNIT_SPACESHIP';

UPDATE Units SET Special = 'SPECIALUNIT_SPACESHIP' WHERE Type = 'UNIT_FW_SPACE_PLANE';

INSERT OR IGNORE INTO Unit_AITypes (UnitType, UnitAIType)
VALUES ('UNIT_FW_AIR_LAND_CARRIER','UNITAI_CARRIER_SEA');

INSERT INTO SpecialUnit_CarrierUnitAI (SpecialUnitType, UnitAIType)
SELECT 'SPECIALUNIT_SPACESHIP','UNITAI_CARRIER_SEA'
WHERE EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='SpecialUnit_CarrierUnitAI');
----------------------------------------------------------------------------------------------------------------------
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_XCOM_SQUAD' AND PromotionType = 'PROMOTION_EXTENDED_PARADROP';

-- Recon class base sight +1
UPDATE Units SET BaseSightRange = '3' WHERE Type IN ('UNIT_FW_AIRBORNE_FORCES','UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'UNIT_FW_SPACEMARINES');

INSERT INTO Trait_FreePromotionUnitClass
	(TraitType, UnitClassType, PromotionType)
VALUES
	('TRAIT_TERROR', 'UNITCLASS_FW_APACHE',    'PROMOTION_MONGOL_TERROR'),
    ('TRAIT_TERROR', 'UNITCLASS_FW_VERTOL',    'PROMOTION_MONGOL_TERROR'),
    ('TRAIT_TERROR', 'UNITCLASS_FW_HOVERTANK', 'PROMOTION_MONGOL_TERROR');

--------------------------------
-- Unit_FreePromotions
--------------------------------
INSERT INTO Unit_FreePromotions 
    (UnitType, PromotionType)
VALUES 
    -- Missile
    ('UNIT_FW_CLUSTER_MISSILE',         'PROMOTION_FW_SPLASH_DAMAGE_1'),
    ('UNIT_FW_HYPERMISSILE',            'PROMOTION_FW_SPLASH_DAMAGE_2'),
    ('UNIT_FW_THERMOMISSILE',           'PROMOTION_FW_SPLASH_DAMAGE_3'),
    ('UNIT_GUIDED_MISSILE',             'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED', 'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_RAILGUN_MISSILE',         'PROMOTION_SUBORBITAL_EVASION'),
    ('UNIT_FW_RAILGUN_MISSILE',         'PROMOTION_HEAVY_PAYLOAD'),
    ('UNIT_FW_GOD_ROD',                 'PROMOTION_FW_SPLASH_DAMAGE_4'),
    ('UNIT_FW_GOD_ROD',                 'PROMOTION_SUBORBITAL_EVASION'),
    ('UNIT_FW_GOD_ROD2',                'PROMOTION_FW_SPLASH_DAMAGE_5'),
    ('UNIT_FW_GOD_ROD2',                'PROMOTION_SPACE_EVASION'),
    ('UNIT_FW_HYDROGEN_BOMB',           'PROMOTION_NUCLEAR_SILO'),
    ('UNIT_FW_HYDROGEN_BOMB',           'PROMOTION_EVASION_I'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',      'PROMOTION_NUCLEAR_SILO'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',      'PROMOTION_EVASION_I'),
    -- Tank
    ('UNIT_FW_RAILGUN_TANK',           'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_RAILGUN_TANK',           'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_RAILGUN_TANK',           'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ZEKE',                   'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_MECH',                      'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_MECH',                      'PROMOTION_FW_NUCLEAR_SMR'),   
    -- Drone
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_RECON_DRONE'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_ANTI_SUBMARINE_I'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_MODERN_DRONE',           'PROMOTION_HOVERING_UNIT'),

    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_MARCH'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_RECON_DRONE'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_ANTI_SUBMARINE_I'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_HYBRID_DRONE',           'PROMOTION_HOVERING_UNIT'),

    ('UNIT_FW_BIODRONE',               'PROMOTION_AIR_RECON'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_MARCH'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_ANTI_SUBMARINE_I'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_BIODRONE',               'PROMOTION_HOVERING_UNIT'),

    --Helicopter
    ('UNIT_FW_APACHE',                 'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_APACHE',                 'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_APACHE',                 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_APACHE',                 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_APACHE',                 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_APACHE',                 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_APACHE',                 'PROMOTION_ONLY_DEFENSIVE'),
	('UNIT_FW_APACHE',                 'PROMOTION_SCOUT_XP_PILLAGE'),
	('UNIT_FW_APACHE',                 'PROMOTION_SKIRMISHER_DOCTRINE'),
	('UNIT_FW_APACHE',                 'PROMOTION_HELI_AMBUSH_1'),
	('UNIT_FW_VERTOL',                 'PROMOTION_SKIRMISHER_DOCTRINE'),
	('UNIT_FW_VERTOL',                 'PROMOTION_SCOUT_XP_PILLAGE'),
	('UNIT_FW_VERTOL',                 'PROMOTION_HELI_AMBUSH_1'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_VERTOL',                 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_FLAT_MOVEMENT_COST'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_HOVERING_UNIT'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_HOVERTANK',              'PROMOTION_ONLY_DEFENSIVE'),
	('UNIT_FW_HOVERTANK',              'PROMOTION_SKIRMISHER_DOCTRINE'),
	('UNIT_FW_HOVERTANK',              'PROMOTION_SCOUT_XP_PILLAGE'),
	('UNIT_FW_HOVERTANK',              'PROMOTION_HELI_AMBUSH_1'),
    -- Sam
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_MODERN_MOBILE_SAM',      'PROMOTION_CARGO_II'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_CYBERSAM',               'PROMOTION_INTERCEPTION_III'), 
    ('UNIT_FW_CYBERSAM',               'PROMOTION_CARGO_III'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_CARGO_I'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_CARGO_III'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_FREE_PILLAGE_MOVES'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_COVER_1'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_INTERCEPTION_III'), 
    ('UNIT_FW_CRAWLER',                'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_CRAWLER',                'PROMOTION_FW_NUCLEAR_SMR'),     
    -- Siege
    ('UNIT_FW_HIMARS', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_HIMARS', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_HIMARS', 'PROMOTION_CITY_SIEGE'),
    ('UNIT_FW_HIMARS', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HIMARS', 'PROMOTION_SIGHT_PENALTY'),
    ('UNIT_FW_HIMARS', 'PROMOTION_SIEGE_INACCURACY'),
    ('UNIT_FW_HIMARS', 'PROMOTION_COVER_1'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_CITY_SIEGE'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_SIGHT_PENALTY'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_SIEGE_INACCURACY'),
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_COVER_1'),   
    ('UNIT_FW_MECH_ARTILLERY', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_ANGEL', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_ANGEL', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_ANGEL', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_ANGEL', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_ANGEL', 'PROMOTION_CITY_SIEGE'),
    ('UNIT_FW_ANGEL', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_ANGEL', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_ANGEL', 'PROMOTION_FREE_PILLAGE_MOVES'),
    ('UNIT_FW_ANGEL', 'PROMOTION_SIEGE_INACCURACY'),
    ('UNIT_FW_ANGEL', 'PROMOTION_COVER_1'),
    ('UNIT_FW_ANGEL', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_ANGEL', 'PROMOTION_FW_NUCLEAR_SMR'),   
    -- Armor solider
    ('UNIT_FW_POWER_ARMOR_INFANTRY', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_BATTLESUIT', 'PROMOTION_FORMATION_1'),
    ('UNIT_FW_BATTLESUIT', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_FORMATION_1'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_GUNDAM', 'PROMOTION_EXTRA_SIGHT_I'),
    -- Bio soldier
    ('UNIT_FW_BIOINFANTRY', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_BIOINFANTRY', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_CLONETROOPER', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_CLONETROOPER', 'PROMOTION_MARCH'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_MARCH'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_RIVAL_TERRITORY'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_BIOTROOPER', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_FW_CHAMELEON'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_FW_MASTER_RACE'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_MARCH'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_RIVAL_TERRITORY'),
    ('UNIT_FW_SUPERSOLDIERS', 'PROMOTION_FIELD_WORKS_3'),
    -- PMC
    ('UNIT_CAYM_PMC', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_CAYM_PMC', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_CAYM_PMC', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_CAYM_PMC', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_FW_ELITE_MERCENARIES', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_FW_ENHANCED_MERCENARIES', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_FLANK_ATTACK_BONUS'),
    ('UNIT_FW_BIO_MERCENARIES', 'PROMOTION_FIELD_WORKS_3'),
    -- Archer
    ('UNIT_FW_ATGM', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_ATGM', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_ATGM', 'PROMOTION_MODERN_RANGED_PENALTY_II'),
    ('UNIT_FW_ATGM', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_FW_NETWORKED'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_MODERN_RANGED_PENALTY_II'),
    ('UNIT_FW_AUTOMATON', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_FW_NETWORKED'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_MODERN_RANGED_PENALTY_II'),
    ('UNIT_FW_ROBOT_INFANTRY', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_FW_NETWORKED'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_NAVAL_MISFIRE'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_MODERN_RANGED_PENALTY_II'),
    ('UNIT_FW_COLOSSUS', 'PROMOTION_ONLY_DEFENSIVE'),
    -- Sapper
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_SCOUT_XP_PILLAGE'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_ATTACK_BONUS'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_EXTENDED_PARADROP'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_ATTACK_BONUS'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_SCOUT_XP_PILLAGE'),
    ('UNIT_XCOM_SQUAD','PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_ORBITAL_DROP'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_AMPHIBIOUS'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_ATTACK_BONUS'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_SCOUT_XP_PILLAGE'),
    -- Gene units
    ('UNIT_FW_CHIMERA', 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_MARCH'),
    ('UNIT_FW_CHIMERA', 'PROMOTION_NEUROTIC_POISON'),
    ('UNIT_FW_SWARM',   'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_SWARM',   'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_SWARM',   'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_SWARM',   'PROMOTION_NEUROTIC_POISON'),
    -- Dino
    ('UNIT_FW_TREX', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_TREX', 'PROMOTION_FW_APEXPREDATOR'),
    ('UNIT_FW_TREX', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_TRICERATOPS', 'PROMOTION_COVER_1'),
    ('UNIT_FW_TRICERATOPS', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_TRICERATOPS', 'PROMOTION_ANTI_TANK'),
    ('UNIT_FW_RAPTOR', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_RAPTOR', 'PROMOTION_MOHAWK'),
    ('UNIT_FW_RAPTOR', 'PROMOTION_IGNORE_TERRAIN_COST'),
    -- Gunboat
    ('UNIT_FW_GUNBOAT', 			'PROMOTION_OCEAN_HALF_MOVES'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_EXTENDED_PARADROP'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
	('UNIT_FW_GUNBOAT', 			'PROMOTION_EXTRA_SIGHT_II'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_EXTENDED_PARADROP'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_EXTRA_SIGHT_II'),
	('UNIT_FW_ADV_GUNBOAT', 		'PROMOTION_OCEAN_HALF_MOVES'),
	('UNIT_FW_ADV_GUNBOAT',         'PROMOTION_CARGO_I'),
    --Destroyer
	('UNIT_FW_NEODESTROYER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_NAVIGATOR_1'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_INTERCEPTION_I'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_INTERCEPTION_II'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_INTERCEPTION_III'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_CARGO_I'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_CARGO_III'),
	('UNIT_FW_NEODESTROYER', 'PROMOTION_ANTI_SUBMARINE_II'),
    ('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_NAVIGATOR_1'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_INTERCEPTION_I'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_INTERCEPTION_II'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_INTERCEPTION_III'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_CARGO_I'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_CARGO_III'),
	('UNIT_FW_RAILGUN_DESTROYER', 'PROMOTION_ANTI_SUBMARINE_II'),
    ('UNIT_FW_BIO_DESTROYER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_NAVIGATOR_1'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_INTERCEPTION_I'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_INTERCEPTION_II'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_INTERCEPTION_III'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_CARGO_I'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_CARGO_III'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_ANTI_SUBMARINE_II'),
	('UNIT_FW_BIO_DESTROYER', 'PROMOTION_MARCH'),
    -- Cruiser
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_ARSENAL_SHIP', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_RAILGUN_CRUISER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_BIO_CRUISER', 'PROMOTION_MARCH'),
    -- Air fighter
    ('UNIT_FW_DRONE_FIGHTER_2','PROMOTION_INTERCEPTION_1'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_AIR_SWEEP'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_AIR_RECON'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_AIR_MISFIRE'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_ANTI_HELICOPTER'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_RECON_RANGE_2'),
    ('UNIT_FW_DRONE_FIGHTER_2', 'PROMOTION_STEALTH'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_INTERCEPTION_1'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_AIR_SWEEP'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_AIR_RECON'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_AIR_MISFIRE'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_ANTI_HELICOPTER'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_RECON_RANGE_2'),
    ('UNIT_FW_PLASMA_FIGHTER',       'PROMOTION_STEALTH'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_INTERCEPTION_1'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_AIR_SWEEP'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_AIR_RECON'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_AIR_MISFIRE'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_ANTI_HELICOPTER'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_STEALTH'),
    ('UNIT_FW_SPACE_FIGHTER',       'PROMOTION_RECON_RANGE_2'),
    -- Air bomber
    ('UNIT_FW_SUBORBITAL_BOMBER', 'PROMOTION_SUBORBITAL_EVASION'),
    ('UNIT_FW_SUBORBITAL_BOMBER', 'PROMOTION_STEALTH'),
    ('UNIT_FW_SUBORBITAL_BOMBER', 'PROMOTION_AIR_RECON'),
    ('UNIT_FW_PLASMA_BOMBER',        'PROMOTION_PLASMA_EVASION'),
    ('UNIT_FW_PLASMA_BOMBER',        'PROMOTION_STEALTH'),
    ('UNIT_FW_PLASMA_BOMBER',        'PROMOTION_AIR_RECON'),
    ('UNIT_FW_SPACE_BOMBER',        'PROMOTION_SPACE_EVASION'),
    ('UNIT_FW_SPACE_BOMBER',        'PROMOTION_STEALTH'),
    ('UNIT_FW_SPACE_BOMBER',        'PROMOTION_AIR_RECON'),
    -- Carrier
    ('UNIT_SUPERCARRIER', 'PROMOTION_FW_NUCLEAR_SMR'),           
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_CARGO_IV'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_ANTI_AIR'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
	('UNIT_FW_SUPERCARRIER', 'PROMOTION_ANTI_SUBMARINE_I'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_SUPERCARRIER', 'PROMOTION_FW_NUCLEAR_SMR'),      
    -- Submarine
    ('UNIT_FW_MECHASUB', 'PROMOTION_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_CAN_MOVE_IMPASSABLE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_SILENT_HUNTER'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_DIVE_II'),
    ('UNIT_FW_MECHASUB', 'PROMOTION_FW_NUCLEAR_SMR'),           
    ('UNIT_FW_CYBERSUB', 'PROMOTION_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_CAN_MOVE_IMPASSABLE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_SILENT_HUNTER'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_DIVE_II'),
    ('UNIT_FW_CYBERSUB', 'PROMOTION_FW_NUCLEAR_SMR'),   
    -- Unique units
    ('UNIT_FW_MUTANT', 'PROMOTION_MARCH'),
    ('UNIT_FW_MUTANT', 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_MUTANT', 'PROMOTION_FW_MUTATION'),   
    ('UNIT_FW_MUTANT', 'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_HYDRA',  'PROMOTION_MARCH'),
    ('UNIT_FW_HYDRA',  'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY'),
    ('UNIT_FW_HYDRA',  'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_HYDRA',  'PROMOTION_COVER_1'),
    ('UNIT_FW_HYDRA',  'PROMOTION_MECH'),
    ('UNIT_FW_HYDRA',  'PROMOTION_EXTRA_SIGHT_I'),
    ('UNIT_FW_HYDRA',  'PROMOTION_FW_MUTATION'),   
    ('UNIT_FW_HYDRA',  'PROMOTION_FIELD_WORKS_3'),
    ('UNIT_FW_HYDRA',  'PROMOTION_FW_NUCLEAR_SMR'),         

    ('UNIT_FW_NANOHIVE', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_NANOHIVE', 'PROMOTION_FW_NANOHIVE_PROMOTION'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_MARCH'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_ONLY_DEFENSIVE'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_CAN_MOVE_AFTER_ATTACKING'),
    ('UNIT_FW_MEGAHIVE', 'PROMOTION_FW_NANOHIVE_PROMOTION'),

    ('UNIT_FW_HELICARRIER', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_COVER_1'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_ARMOR_PLATING_3'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_HELICARRIER', 'PROMOTION_FW_NUCLEAR_SMR'),         
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_MOVE_ALL_TERRAIN'),
    ('UNIT_FW_NEXUS', 'PROMOTION_IGNORE_TERRAIN_COST'),
    ('UNIT_FW_NEXUS', 'PROMOTION_NO_DEFENSIVE_BONUSES'),
    ('UNIT_FW_NEXUS', 'PROMOTION_COVER_1'),
    ('UNIT_FW_NEXUS', 'PROMOTION_ARMOR_PLATING_1'),
    ('UNIT_FW_NEXUS', 'PROMOTION_ARMOR_PLATING_2'),
    ('UNIT_FW_NEXUS', 'PROMOTION_ARMOR_PLATING_3'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INTERCEPTION_I'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INTERCEPTION_II'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INTERCEPTION_III'),
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_NANOHIVE_PROMOTION'),
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_NEXUS'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_I'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_II'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_III'),
    ('UNIT_FW_NEXUS', 'PROMOTION_CARGO_IV'),
    ('UNIT_FW_NEXUS', 'PROMOTION_INDIRECT_FIRE'),
    ('UNIT_FW_NEXUS', 'PROMOTION_FW_NUCLEAR_SMR'),
    -- Vault Rack
    ('UNIT_FW_VAULT_RACK',                'PROMOTION_CARGO_III');


-- Building Required for purchase
INSERT INTO	Unit_BuildingClassPurchaseRequireds
		(UnitType, 				                BuildingClassType)
VALUES
    -- Missile
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED',	    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ADVANCED_MISSILE_GUIDED',     'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_RAILGUN_MISSILE',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_RAILGUN_MISSILE',             'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_HYPERMISSILE',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HYPERMISSILE',                'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_HYDROGEN_BOMB',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HYDROGEN_BOMB',               'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',          'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_THERMONUCLEAR_BOMB',          'BUILDINGCLASS_AIRPORT'),
    -- Tank
    ('UNIT_FW_RAILGUN_TANK',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_RAILGUN_TANK',                'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_FW_ZEKE',                        'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ZEKE',                        'BUILDINGCLASS_FW_NANOFORGE'),
    ('UNIT_MECH',                           'BUILDINGCLASS_FW_NANOFORGE'),
    -- Drone
    ('UNIT_FW_MODERN_DRONE',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HYBRID_DRONE',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HYBRID_DRONE',	            'BUILDINGCLASS_FW_FUNGAL_AGRIGENOMICS'),
    ('UNIT_FW_BIODRONE',                    'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_BIODRONE',                    'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_BIODRONE',                    'BUILDINGCLASS_FW_BIOMOD_TANK'),
    -- Helicopter
    ('UNIT_FW_APACHE',	                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_APACHE',	                    'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_VERTOL',                      'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_VERTOL',                      'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HOVERTANK',                   'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_HOVERTANK',                   'BUILDINGCLASS_FW_CYBERCLINIC'),
    -- Sam
    ('UNIT_FW_MODERN_MOBILE_SAM',	        'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CYBERSAM',	                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CYBERSAM',                    'BUILDINGCLASS_FW_CYBERCLINIC'),
    ('UNIT_FW_CRAWLER', 	                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CRAWLER',                     'BUILDINGCLASS_FW_CYBERCLINIC'),
    -- Siage
    ('UNIT_FW_HIMARS',                      'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_MECH_ARTILLERY',              'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_MECH_ARTILLERY',              'BUILDINGCLASS_FW_NANOMAT_PLANT'),
    ('UNIT_FW_ANGEL',                       'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ANGEL',                       'BUILDINGCLASS_FW_DRONE_HIVE'),
    -- ARMOR soldier
    ('UNIT_FW_BATTLESUIT',                  'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_GUNDAM',                      'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_GUNDAM',                      'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    -- Biosoldier
    ('UNIT_FW_BIOINFANTRY',                 'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CLONETROOPER',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_CLONETROOPER',	            'BUILDINGCLASS_FW_FUNGAL_AGRIGENOMICS'),
    ('UNIT_FW_BIOTROOPER',                  'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_BIOTROOPER',                  'BUILDINGCLASS_FW_BIOMOD_TANK'),
    ('UNIT_FW_SUPERSOLDIERS',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SUPERSOLDIERS',               'BUILDINGCLASS_FW_BIOMOD_TANK'),
    ('UNIT_FW_SUPERSOLDIERS',               'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    -- Archer
    ('UNIT_FW_ATGM',	                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_POWER_ARMOR_INFANTRY',	    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_AUTOMATON',                   'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ROBOT_INFANTRY',              'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ROBOT_INFANTRY',              'BUILDINGCLASS_FW_DRONE_HIVE'),
    ('UNIT_FW_COLOSSUS',                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_COLOSSUS',                    'BUILDINGCLASS_FW_DRONE_HIVE'),
    -- Sapper
    ('UNIT_FW_SPEC_FORCES',	                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPEC_FORCES',	                'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_AIRBORNE_FORCES',             'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_AIRBORNE_FORCES',             'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER',  'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER',  'BUILDINGCLASS_AIRPORT'),
    ('UNIT_XCOM_SQUAD',                     'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    ('UNIT_FW_SPACEMARINES',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACEMARINES',                'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    -- Gene units
    ('UNIT_FW_CHIMERA',                     'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_CHIMERA',                     'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_SWARM',                       'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_SWARM',                       'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_SWARM',                       'BUILDINGCLASS_FW_BIOMOD_TANK'),
    -- Dino
    ('UNIT_FW_TREX',                        'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_TRICERATOPS',                 'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_RAPTOR',                      'BUILDINGCLASS_FW_CLONE_LAB'),
    -- Gunboat
    ('UNIT_FW_GUNBOAT',                     'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_GUNBOAT',                     'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_ADV_GUNBOAT',                 'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_ADV_GUNBOAT',                 'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    -- Destroyer
    ('UNIT_FW_RAILGUN_DESTROYER',           'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_BIO_DESTROYER',               'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_BIO_DESTROYER',	            'BUILDINGCLASS_FW_BIOMOD_TANK'), 
    -- Cruiser
    ('UNIT_FW_ARSENAL_SHIP',                'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_RAILGUN_CRUISER',             'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_BIO_CRUISER',                 'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_BIO_CRUISER',	                'BUILDINGCLASS_FW_BIOMOD_TANK'),
    -- Submarine
    ('UNIT_FW_MECHASUB',                    'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_CYBERSUB',                    'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_CYBERSUB',                    'BUILDINGCLASS_FW_CYBERCLINIC'),
     -- Carrier
    ('UNIT_FW_SUPERCARRIER',                'BUILDINGCLASS_SEAPORT'),
    ('UNIT_FW_HELICARRIER',                 'BUILDINGCLASS_MILITARY_BASE'),
    -- Air fighter
    ('UNIT_FW_DRONE_FIGHTER_2',	            'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_DRONE_FIGHTER_2',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_PLASMA_FIGHTER',	            'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_PLASMA_FIGHTER',	            'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACE_FIGHTER',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACE_FIGHTER',               'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    -- Air Bomber
    ('UNIT_FW_SUBORBITAL_BOMBER',           'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_SUBORBITAL_BOMBER',           'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_PLASMA_BOMBER',               'BUILDINGCLASS_AIRPORT'),
    ('UNIT_FW_PLASMA_BOMBER',               'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACE_BOMBER',                'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_SPACE_BOMBER',                'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
     -- Unique units
    ('UNIT_FW_MUTANT',	                    'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_MUTANT',	                    'BUILDINGCLASS_FW_TRANSGENIC_NURSERY'),
    ('UNIT_FW_HYDRA',                       'BUILDINGCLASS_FW_CLONE_LAB'),
    ('UNIT_FW_HYDRA',                       'BUILDINGCLASS_FW_ECTOGENESIS_POD'),
    ('UNIT_FW_HYDRA',                       'BUILDINGCLASS_FW_BIOMOD_TANK'),
    ('UNIT_FW_NANOHIVE',                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_NANOHIVE',                    'BUILDINGCLASS_FW_DRONE_HIVE'),
    ('UNIT_FW_MEGAHIVE',                    'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_MEGAHIVE',                    'BUILDINGCLASS_FW_DRONE_HIVE'),
    ('UNIT_FW_HELICARRIER',                 'BUILDINGCLASS_FW_AEROSPACE_COMPLEX'),
    ('UNIT_FW_NEXUS',                       'BUILDINGCLASS_MILITARY_BASE'),
    ('UNIT_FW_NEXUS',                       'BUILDINGCLASS_FW_AEROSPACE_COMPLEX');

-----------------------------------------------------------------
-- Military flags
-----------------------------------------------------------------
UPDATE Units
SET MilitarySupport = 1, MilitaryProduction = 1
WHERE CombatClass IN (
  SELECT Type FROM UnitCombatInfos WHERE IsMilitary = 1
) OR Class IN (
  'UNITCLASS_FW_CLUSTER_MISSILE',
  'UNITCLASS_FW_HYPERMISSILE',
  'UNITCLASS_FW_THERMOMISSILE',
  'UNITCLASS_FW_ADVANCED_MISSILE_GUIDED',
  'UNITCLASS_FW_RAILGUN_MISSILE',
  'UNITCLASS_FW_GOD_ROD',
  'UNITCLASS_FW_GOD_ROD2'
  -- 'UNITCLASS_FW_VAULT_RACK'  ← 제외
);

-- Air units and missiles don't cost supply
UPDATE Units
SET NoSupply = 1
WHERE CombatClass IN (
  SELECT Type FROM UnitCombatInfos WHERE IsAerial = 1
) OR Class IN (
  'UNITCLASS_FW_CLUSTER_MISSILE',
  'UNITCLASS_FW_HYPERMISSILE',
  'UNITCLASS_FW_THERMOMISSILE',
  'UNITCLASS_FW_ADVANCED_MISSILE_GUIDED',
  'UNITCLASS_FW_RAILGUN_MISSILE',
  'UNITCLASS_FW_GOD_ROD',
  'UNITCLASS_FW_GOD_ROD2'
);

-- Rack: exclude from military rules entirely
DELETE FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_FW_VAULT_RACK';

UPDATE Units
SET MilitarySupport = 0, MilitaryProduction = 0, NoSupply = 1
WHERE Type = 'UNIT_FW_VAULT_RACK';

-- (선택) 랙 정리
UPDATE Units
SET CombatClass = NULL, ObsoleteTech = NULL
WHERE Type = 'UNIT_FW_VAULT_RACK';

-----------------------------------------------------------------
-- Barbarians cannot use/spawn these classes
-----------------------------------------------------------------
INSERT INTO Civilization_UnitClassOverrides (CivilizationType, UnitClassType)
SELECT 'CIVILIZATION_BARBARIAN', Type
FROM UnitClasses
WHERE Type IN (
  'UNITCLASS_FW_MODERN_COLONIST',
  'UNITCLASS_FW_SPACE_COLONIST',
  'UNITCLASS_FW_AUGMENTED_DIPLOMAT',

  -- Scouting line
  'UNITCLASS_MARINE',
  'UNITCLASS_XCOM_SQUAD',

  -- Siege
  'UNITCLASS_FW_HIMARS',
  'UNITCLASS_FW_MECH_ARTILLERY',
  'UNITCLASS_FW_ANGEL',

  -- AA
  'UNITCLASS_FW_MODERN_MOBILE_SAM',
  'UNITCLASS_FW_CYBERSAM',
  'UNITCLASS_FW_CRAWLER',

  -- Air & Missiles
  'UNITCLASS_FW_DRONE_FIGHTER_2',
  'UNITCLASS_FW_PLASMA_FIGHTER',
  'UNITCLASS_FW_SPACE_FIGHTER',
  'UNITCLASS_FW_SUBORBITAL_BOMBER',
  'UNITCLASS_FW_PLASMA_BOMBER',
  'UNITCLASS_FW_SPACE_BOMBER',
  'UNITCLASS_FW_CLUSTER_MISSILE',
  'UNITCLASS_FW_HYPERMISSILE',
  'UNITCLASS_FW_THERMOMISSILE',
  'UNITCLASS_FW_ADVANCED_MISSILE_GUIDED',
  'UNITCLASS_FW_RAILGUN_MISSILE',
  'UNITCLASS_FW_GOD_ROD',
  'UNITCLASS_FW_GOD_ROD2',
  'UNITCLASS_FW_HYDROGEN_BOMB',
  'UNITCLASS_FW_THERMONUCLEAR_BOMB',

  -- Misc.
  'UNITCLASS_SUPERCARRIER',
  'UNITCLASS_FW_SUPERCARRIER',
  'UNITCLASS_FW_HELICARRIER',
  'UNITCLASS_FW_NEXUS',
  'UNITCLASS_FW_VAULT_RACK'
);
/*
-- ===============================================================================================================================================================================
-- New test
-- =========================================================
-- ATGM 전용: 화이트리스트 유닛만 적재 가능하게 제한
--  - SpecialUnits 보정
--  - 화이트리스트 외 모두 권한 제거
--  - 화이트리스트엔 권한 보장 + 최소 1칸 보장
-- =========================================================
DELETE FROM Unit_FreePromotions WHERE PromotionType = 'PROMOTION_ANTI_TANK' AND UnitType = 'UNIT_BAZOOKA';
DELETE FROM Unit_FreePromotions WHERE PromotionType = 'PROMOTION_ANTI_TANK' AND UnitType = 'UNIT_HELICOPTER_GUNSHIP';
UPDATE Units SET Range = '2', DefaultUnitAI = 'UNITAI_RANGED' WHERE Type = 'UNIT_BAZOOKA';

-- 0) ATGM 스페셜 정의/보정 (도시 적재 허용)
INSERT OR IGNORE INTO SpecialUnits (Type, Description, Valid, CityLoad)
VALUES ('SPECIALUNIT_ANTITANK_MISSILE','TXT_KEY_SPECIALUNIT_ANTITANK_MISSILE',1,1);
UPDATE SpecialUnits SET Valid=1, CityLoad=1 WHERE Type='SPECIALUNIT_ANTITANK_MISSILE';

-- 화이트리스트 목록
-- (여기에 적힌 타입만 ATGM 적재 가능)
--  * 필요 시 목록에서 추가/삭제하면 됨
--  * 아래 IN (...) 자리에 동일하게 사용
--    UNIT_FW_ATGM 을 캐리어로 쓰지 않을 거면 목록에서 빼세요.
--    (그 유닛이 미사일 본체라면 캐리어 지정은 불필요)
-- ---------------------------------------------------------
-- 'UNIT_BAZOOKA','UNIT_HELICOPTER_GUNSHIP','UNIT_FW_APACHE',
-- 'UNIT_FW_ATGM','UNIT_FW_VERTOL','UNIT_FW_HOVERTANK',
-- 'UNIT_FW_AUTOMATON','UNIT_FW_ROBOT_INFANTRY','UNIT_FW_COLOSSUS'

-- 1) 화이트리스트 외 모든 유닛에서 ATGM 적재 권한 제거
UPDATE Units
SET SpecialCargo = NULL,
    DomainCargo  = NULL
WHERE SpecialCargo = 'SPECIALUNIT_ANTITANK_MISSILE'
  AND Type NOT IN (
    'UNIT_BAZOOKA','UNIT_HELICOPTER_GUNSHIP','UNIT_FW_APACHE',
    'UNIT_FW_ATGM','UNIT_FW_VERTOL','UNIT_FW_HOVERTANK',
    'UNIT_FW_AUTOMATON','UNIT_FW_ROBOT_INFANTRY','UNIT_FW_COLOSSUS'
  );

-- 2) 화이트리스트 유닛에 권한 보장 (idempotent)
UPDATE Units
SET SpecialCargo = 'SPECIALUNIT_ANTITANK_MISSILE',
    DomainCargo  = 'DOMAIN_AIR'
WHERE Type IN (
  'UNIT_BAZOOKA','UNIT_HELICOPTER_GUNSHIP','UNIT_FW_APACHE',
  'UNIT_FW_ATGM','UNIT_FW_VERTOL','UNIT_FW_HOVERTANK',
  'UNIT_FW_AUTOMATON','UNIT_FW_ROBOT_INFANTRY','UNIT_FW_COLOSSUS'
);

-- 3) 화이트리스트 유닛에 최소 1칸 화물칸 보장
INSERT INTO Unit_FreePromotions    (UnitType, PromotionType)
VALUES 
	('UNIT_BAZOOKA',             'PROMOTION_CARGO_I'),
	('UNIT_HELICOPTER_GUNSHIP',  'PROMOTION_CARGO_I');


-- 4) (선택) AI 힌트: 해상 캐리어 AI도 이 스페셜을 싣는 대상으로 인지
INSERT OR IGNORE INTO SpecialUnit_CarrierUnitAI (SpecialUnitType, UnitAIType)
VALUES ('SPECIALUNIT_ANTITANK_MISSILE','UNITAI_CARRIER_SEA');


--------------------------------
-- UnitClasses
--------------------------------
INSERT INTO UnitClasses
		(Type, 							Description, 					DefaultUnit)
VALUES	('UNITCLASS_ZEPPELIN', 			'TXT_KEY_UNIT_ZEPPELIN_CBP', 	'UNIT_ZEPPELIN'),
		('UNITCLASS_WWI_ZEPPELIN', 		'TXT_KEY_UNIT_WWI_ZEPPELIN', 	'UNIT_WWI_ZEPPELIN'),
		('UNITCLASS_PREDATOR_DRONE', 	'TXT_KEY_UNIT_PREDATOR_DRONE', 	'UNIT_PREDATOR_DRONE');

--------------------------------	
-- Units
--------------------------------	
INSERT INTO Units
		(Class, 						Type, 					Combat, Cost, 	FaithCost, 	RequiresFaithPurchaseEnabled, 	Moves, 	BaseSightRange, BaseLandAirDefense, 	PrereqTech, 		ObsoleteTech, 	                   CombatClass, 			Domain, 	NoBadGoodies, 	DefaultUnitAI, 		Description, 					Civilopedia, 							Strategy, 									Help, 								Pillage, 	MilitarySupport, 	MilitaryProduction, Mechanized, AdvancedStartCost, 	XPValueAttack, 	XPValueDefense, UnitArtInfo, 									UnitFlagAtlas, 						UnitFlagIconOffset, PortraitIndex, 	IconAtlas, 						MoveRate, 	PurchaseCooldown)
VALUES	('UNITCLASS_ZEPPELIN', 			'UNIT_ZEPPELIN', 		32, 	700, 	600, 		1, 								3, 		4, 				2, 						'TECH_STEAM_POWER', 'TECH_PLASTIC', 	            'UNITCOMBAT_HELICOPTER', 	'DOMAIN_LAND', 	1, 				'UNITAI_EXPLORE', 	'TXT_KEY_UNIT_ZEPPELIN_CBP', 	'TXT_KEY_CIV5_ZEPPELIN_TEXT_CBP', 		'TXT_KEY_UNIT_ZEPPELIN_STRATEGY_CBP', 		'TXT_KEY_UNIT_HELP_ZEPPELIN_CBP', 	1, 			1, 					1, 					1, 			30, 				3, 				3, 				'ART_DEF_UNIT_SMOKEY_STEAM_AIRSHIP_LEVEL_1', 	'EXPANSION_SCEN_UNIT_FLAG_ATLAS', 	7, 					7, 				'EXPANSION_SCEN_UNIT_ATLAS', 	'WHEELED', 	1),
		('UNITCLASS_WWI_ZEPPELIN', 		'UNIT_WWI_ZEPPELIN', 	42, 	1000, 	900, 		1, 								3, 		4, 				3, 						'TECH_PLASTIC',     'TECH_SATELLITES',              'UNITCOMBAT_HELICOPTER', 	'DOMAIN_LAND', 	1, 				'UNITAI_EXPLORE', 	'TXT_KEY_UNIT_WWI_ZEPPELIN', 	'TXT_KEY_UNIT_WWI_ZEPPELIN_TEXT', 		'TXT_KEY_UNIT_WWI_ZEPPELIN_STRATEGY', 		'TXT_KEY_UNIT_WWI_ZEPPELIN_HELP', 	1, 			1, 					1, 					1, 			30, 				3, 				3, 				'ART_DEF_UNIT_SMOKEY_STEAM_AIRSHIP', 		    'EXPANSION_SCEN_UNIT_FLAG_ATLAS', 	8, 					8, 		    	'EXPANSION_SCEN_UNIT_ATLAS', 	'WHEELED', 	1),
        ('UNITCLASS_PREDATOR_DRONE', 	'UNIT_PREDATOR_DRONE', 	65, 	1800, 	1400, 		1, 								4, 		4, 				25, 					'TECH_SATELLITES',  'TECH_SUPERCOMPUTERS', 			'UNITCOMBAT_HELICOPTER', 	'DOMAIN_LAND',  1, 				'UNITAI_EXPLORE', 	'TXT_KEY_UNIT_PREDATOR_DRONE', 	'TXT_KEY_UNIT_PREDATOR_DRONE_TEXT', 	'TXT_KEY_UNIT_PREDATOR_DRONE_STRATEGY', 	'TXT_KEY_UNIT_PREDATOR_DRONE_HELP', 1, 			1, 					1, 					1, 			30, 				3, 				3, 				'ART_DEF_UNIT_PREDATOR_DRONE', 				    'UNIT_UAV_FLAG_ATLAS', 		       	0, 					63, 				'TCS_MOD_ICON_ATLAS', 		'WHEELED', 	1);


--------------------------------



--------------------------------	
-- Unit_Flavors
--------------------------------	
INSERT INTO		Unit_Flavors
		(UnitType, 				FlavorType,				Flavor)
VALUES	('UNIT_ZEPPELIN',		'FLAVOR_NAVAL_RECON',	10),
		('UNIT_ZEPPELIN',		'FLAVOR_OFFENSE',		5),
		('UNIT_ZEPPELIN',		'FLAVOR_RECON',			10),
		('UNIT_WWI_ZEPPELIN',	'FLAVOR_NAVAL_RECON',	10),
		('UNIT_WWI_ZEPPELIN',	'FLAVOR_OFFENSE',		5),
		('UNIT_WWI_ZEPPELIN',	'FLAVOR_RECON',			10),
		('UNIT_PREDATOR_DRONE',	'FLAVOR_NAVAL_RECON',	10),
		('UNIT_PREDATOR_DRONE',	'FLAVOR_OFFENSE',		5),
		('UNIT_PREDATOR_DRONE',	'FLAVOR_RECON',			10);
--------------------------------	
-- Unit_BuildingClassPurchaseRequireds
--------------------------------	
INSERT INTO	Unit_BuildingClassPurchaseRequireds
			(UnitType, 				BuildingClassType)
VALUES		('UNIT_ZEPPELIN',		'BUILDINGCLASS_ARMORY'),
			('UNIT_WWI_ZEPPELIN',	'BUILDINGCLASS_ARMORY'),
			('UNIT_PREDATOR_DRONE',	'BUILDINGCLASS_MILITARY_BASE');
--------------------------------	
-- UnitGameplay2DScripts
--------------------------------		
INSERT INTO UnitGameplay2DScripts 	
			(UnitType, 				SelectionSound, FirstSelectionSound)
SELECT		'UNIT_WWI_ZEPPELIN',	SelectionSound, FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_ZEPPELIN';

INSERT INTO UnitGameplay2DScripts 	
			(UnitType, 				SelectionSound, 		FirstSelectionSound)
VALUES		('UNIT_PREDATOR_DRONE',	'AS2D_SELECT_FIGHTER', 	'AS2D_BIRTH_FIGHTER');
--------------------------------	
-- Unit_AITypes
--------------------------------		
INSERT INTO Unit_AITypes 	
			(UnitType, 				UnitAIType)
VALUES		('UNIT_ZEPPELIN',		'UNITAI_EXPLORE_SEA'),
			('UNIT_ZEPPELIN',		'UNITAI_EXPLORE'),
			('UNIT_WWI_ZEPPELIN',	'UNITAI_EXPLORE_SEA'),
			('UNIT_WWI_ZEPPELIN',	'UNITAI_EXPLORE'),
			('UNIT_PREDATOR_DRONE',	'UNITAI_EXPLORE_SEA'),
			('UNIT_PREDATOR_DRONE',	'UNITAI_EXPLORE');
--------------------------------	
-- Unit_ClassUpgrades
--------------------------------
INSERT INTO Unit_ClassUpgrades 
		(UnitType, UnitClassType) 
VALUES	('UNIT_ZEPPELIN', 		'UNITCLASS_WWI_ZEPPELIN'),
		('UNIT_WWI_ZEPPELIN', 	'UNITCLASS_PREDATOR_DRONE');

--------------------------------	
-- Unit_FreePromotions
--------------------------------	
INSERT INTO		Unit_FreePromotions
		(UnitType,				PromotionType)
VALUES	
		('UNIT_ZEPPELIN', 		'PROMOTION_IGNORE_TERRAIN_COST'),
		('UNIT_ZEPPELIN', 		'PROMOTION_RECON_SHORT_RANGE'),
		('UNIT_ZEPPELIN', 		'PROMOTION_RECON_DRONE'),
		('UNIT_ZEPPELIN', 		'PROMOTION_SCOUT_XP_SPOTTING'),
		('UNIT_ZEPPELIN', 		'PROMOTION_RECON_EXPERIENCE'),
		('UNIT_ZEPPELIN', 		'PROMOTION_ANTI_TANK'),
		('UNIT_ZEPPELIN',       'PROMOTION_WOODLAND_TRAILBLAZER_3'),
	('UNIT_ZEPPELIN',                  'PROMOTION_WOODLAND_TRAILBLAZER_3'),

		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_IGNORE_TERRAIN_COST'),
		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_RECON_SHORT_RANGE'),
		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_RECON_DRONE'),
		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_SCOUT_XP_SPOTTING'),
		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_RECON_EXPERIENCE'),
		('UNIT_WWI_ZEPPELIN', 	'PROMOTION_ANTI_TANK'),
		('UNIT_WWI_ZEPPELIN',   'PROMOTION_WOODLAND_TRAILBLAZER_3'),

		('UNIT_PREDATOR_DRONE', 'PROMOTION_IGNORE_TERRAIN_COST'),
		('UNIT_PREDATOR_DRONE', 'PROMOTION_RECON_DRONE'),
		('UNIT_PREDATOR_DRONE', 'PROMOTION_SCOUT_XP_SPOTTING'),
		('UNIT_PREDATOR_DRONE', 'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
		('UNIT_PREDATOR_DRONE', 'PROMOTION_ANTI_SUBMARINE_I'),
		('UNIT_PREDATOR_DRONE', 'PROMOTION_ANTI_TANK'),
		('UNIT_PREDATOR_DRONE', 'PROMOTION_WOODLAND_TRAILBLAZER_3');

--------------------------------	
-- Civilization_UnitClassOverrides
--------------------------------
INSERT INTO Civilization_UnitClassOverrides
	(CivilizationType, UnitClassType, UnitType)
VALUES
	('CIVILIZATION_MINOR', 'UNITCLASS_ZEPPELIN', 		NULL),
	('CIVILIZATION_MINOR', 'UNITCLASS_WWI_ZEPPELIN', 	NULL),
	('CIVILIZATION_MINOR', 'UNITCLASS_PREDATOR_DRONE', 	NULL);

----------------
-- FLAVOR 
----------------

INSERT INTO Technology_Flavors (TechType, FlavorType, Flavor)
VALUES
	('TECH_STEAM_POWER', 'FLAVOR_RECON', 10),
	('TECH_PLASTIC',     'FLAVOR_RECON', 10),
	('TECH_SATELLITES',  'FLAVOR_RECON', 10);

----------------
-- PROMOTION CHANGE
----------------

INSERT INTO UnitPromotions_UnitClasses
	(PromotionType, UnitClassType, Modifier)
VALUES
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_ZEPPELIN', 150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_WWI_ZEPPELIN', 150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_PREDATOR_DRONE', 150);
--------------------------------------
-- Text
-------------------------------
--------------------------------
-- TEXT (US)
--------------------------------
-- NEW COMBAT TYPE

INSERT OR REPLACE INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_UNITCOMBAT_HOVER', 'Airship Unit');

UPDATE Language_en_US
SET Text = 'Bonus vs Helicopters and Air Recon units(150)'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';

UPDATE Language_en_US
SET Text = '+150% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Helicopter Gunship Units and Airship Units[ENDCOLOR].'
WHERE Tag ='TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP';
-----------------------
-- TEXT (KR)
-----------------------
-- NEW COMBAT TYPE
INSERT OR REPLACE INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_UNITCOMBAT_HOVER', '비행선 유닛');

UPDATE Language_ko_KR
SET Text = '헬리콥터, 비행선유닛 대항 보너스 (150)'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';

UPDATE Language_ko_KR
SET Text = '헬리콥터 유닛과 비행선유닛 대항 시 [ICON_STRENGTH] 전투력 보너스 [COLOR_POSITIVE_TEXT]+150%[ENDCOLOR]'
WHERE Tag ='TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP';

INSERT INTO Language_en_US (Tag, Text)
VALUES
	('TXT_KEY_UNIT_ZEPPELIN_CBP',				'Dirigible'),
	('TXT_KEY_CIV5_ZEPPELIN_TEXT_CBP',			'The oldest means of powered flight were lighter than air craft called dirigibles, or navigable balloons. These craft were used to observe and communicate over active battlefields, first seeing military action in the US Civil War.'),
	('TXT_KEY_UNIT_ZEPPELIN_STRATEGY_CBP',		'Dirigibles are a tough Industrial-era Airship unit that doubles as a potent city attacker. Use Dirigbles to monitor your borders, detect enemy submarines, or to strike undefended enemy cities.'),
	('TXT_KEY_UNIT_HELP_ZEPPELIN_CBP',			'industrial-age Airship unit. Used to deter armored forces and monitor borders. Can go through sea tiles.'),
	('TXT_KEY_UNIT_WWI_ZEPPELIN',				'Zeppelin Airship'), 
	('TXT_KEY_UNIT_WWI_ZEPPELIN_TEXT',			'A Zeppelin was a type of rigid airship named after the German Count Ferdinand von Zeppelin who pioneered rigid airship development at the beginning of the 20th century. Zeppelin''s ideas were first formulated in 1874 and developed in detail in 1893. They were patented in Germany in 1895 and in the United States in 1899. After the outstanding success of the Zeppelin design, the word zeppelin came to be commonly used to refer to all rigid airships. Zeppelins were first flown commercially in 1910 by Deutsche Luftschiffahrts-AG (DELAG), the world''s first airline in revenue service. By mid-1914, DELAG had carried over 10,000 fare-paying passengers on over 1,500 flights. During World War I the German military made extensive use of Zeppelins as bombers and scouts, killing over 500 people in bombing raids in Britain.'), 
	('TXT_KEY_UNIT_WWI_ZEPPELIN_STRATEGY',		'Zeppelins are a tough modern-era reconnaissance unit that doubles as a potent city attacker. Use Zeppelins to monitor your borders, detect enemy submarines, or to strike undefended enemy cities.'), 
	('TXT_KEY_UNIT_WWI_ZEPPELIN_HELP',			'A Airship unit of the modern-nuclear age. They are used to deter armored forces, detect submarines or monitor borders. Can go through sea tiles.'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE',				'CAS fighter'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE_TEXT',		'A patrol aircraft is an aircraft that performs surveillance and reconnaissance missions while flying in maritime airspace. The patrol aircraft is equipped with infrared detection devices, sound detectors, magnetic detectors, and communication capabilities with artificial satellites. Since it has to perform reconnaissance missions for a long time on the sea, it must be able to fly for a long time, and it must have good low-altitude flight performance because low-altitude operations are mainly performed. Recently, the main mission is to detect and attack enemy submarines with submarine detection equipment. Anti-submarine/maritime patrol aircraft are specialized in maritime operations such as anti-submarine warfare, anti-ship warfare, and mine warfare at sea. On the other hand, patrol aircraft are divided into land-based types that take off and land from ground airfields, and ship-based types that can be operated from aircraft carriers. There are P-1, P-2, P-3, P-8, etc. in the form of ground-type patrol aircraft that take off from ground airfields, and these types are generally as large as passenger aircraft. There are S-2 and S-3 types of carrier-based aircraft that can be operated from aircraft carriers, and the size of these types is small.'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE_STRATEGY',	'Patrol aircraft are reconnaissance units capable of detecting submarines in the information age. Use patrol planes to observe borders and spot enemy submarines'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE_HELP',		'An Information Age recon unit capable of monitoring borders or submarines. Can go through sea tiles.');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES
	('TXT_KEY_UNIT_ZEPPELIN_CBP',				'열기구'),
	('TXT_KEY_CIV5_ZEPPELIN_TEXT_CBP',			'가장 오래된 동력 비행 수단은 비행선(dirigibles) 또는 항해 가능한 풍선(navigable balloons)이라고 하는 항공기보다 가볍습니다. 이 우주선은 활발한 전장을 관찰하고 통신하는 데 사용되었으며 미국 남북 전쟁에서 처음으로 군사 행동을 목격했습니다.'),
	('TXT_KEY_UNIT_ZEPPELIN_STRATEGY_CBP',		'비행선은 산업 시대 정찰 유닛입니다. 비행선을 사용하여 국경을 관찰하고 적의 잠수함을 탐지하십시오.'),
	('TXT_KEY_UNIT_HELP_ZEPPELIN_CBP',			'산업 시대 원거리 정찰 유닛으로 국경을 감시할 수 있습니다. 대양 위를 다닐 수 있습니다'),
	('TXT_KEY_UNIT_WWI_ZEPPELIN',				'체펠린 비행선'), 
	('TXT_KEY_UNIT_WWI_ZEPPELIN_TEXT',			'체펠린은 20세기 초 경식 비행선 개발을 개척한 독일의 페르디난트 폰 체펠린 백작의 이름을 딴 경식 비행선의 일종입니다. Zeppelin의 아이디어는 1874년에 처음 공식화되었고 1893년에 세부적으로 개발되었습니다. 그들은 1895년에 독일에서, 1899년에 미국에서 특허를 받았습니다. Zeppelin 디자인의 뛰어난 성공 이후 zeppelin이라는 단어는 일반적으로 모든 단단한 비행선을 참조하십시오. Zeppelins는 1910년 세계 최초의 수익 서비스 항공사인 Deutsche Luftschiffahrts-AG(DELAG)에 의해 처음으로 상업적으로 비행되었습니다. 1914년 중반까지 DELAG는 1,500편이 넘는 항공편에서 10,000명 이상의 유료 승객을 태웠습니다. 제1차 세계 대전 동안 독일군은 제플린을 폭격기와 정찰병으로 광범위하게 사용하여 영국에서 폭격으로 500명 이상을 죽였습니다.'), 
	('TXT_KEY_UNIT_WWI_ZEPPELIN_STRATEGY',		'체펠린 비행선은 강력한 현대 시대 비행선 유닛입니다. 체펠린 비행선을 사용하여 국경을 관찰하고 적의 잠수함을 탐지하십시오.'), 
	('TXT_KEY_UNIT_WWI_ZEPPELIN_HELP',			'현대 시대 정찰 유닛으로 국경 또는 잠수함을 감시할 수 있습니다. 대양 위를 다닐 수 있습니다'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE',				'초계기'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE_TEXT',		'초계기는 해상공역을 비행하면서 경계 및 정찰 임무를 수행하는 항공기로, 장기간 해상에 떠서 적 함대의 동정을 감시하는 것을 주임무로 하고 있다. 초계기는 적외선 탐지장치, 음향 탐지기, 자기 탐지기 등은 물론 인공위성과의 통신능력 등을 갖추고 있다. 바다 위에서 오랫동안 정찰 임무 등을 수행해야 하므로 장시간 비행이 가능해야 하고, 주로 저공 작전이 이뤄지므로 저공비행 성능이 좋아야 한다. 근래에는 잠수함 탐지장비를 갖춰 적의 잠수함을 발견, 공격하는 것을 주임무로 하고 있는데 이를 "대잠 초계기"라고도 하며, 해상에서 주로 활동하므로 ‘해상 초계기’라고도 한다. 대잠/해상초계기는 해상에서의 대잠전, 대함전, 기뢰전 등 해상작전에 특화돼 있다.한편, 초계기는 지상 비행장에서 이착륙하는 지상형과 항공모함 등에서 운용이 가능한 함재기형으로 구분된다. 지상 비행장에서 이륙하는 형태의 지상형 초계기에는 P-1, P-2, P-3, P-8 등이 있고 이들 기종은 대체적으로 여객기 수준으로 크다. 항공모함 등에서 운용 가능한 함재기형 항공기에는 S-2, S-3 등이 있으며, 이들 기종의 크기는 작은 편이다.'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE_STRATEGY',	'초계기는 정보화 시대의 잠수함을 탐지할 수 있는 정찰 유닛입니다. 초계기를 사용하여 국경을 관찰하고 적의 잠수함을 탐지하십시오.'), 
	('TXT_KEY_UNIT_PREDATOR_DRONE_HELP',		'정보화시대 정찰 유닛으로 국경 또는 잠수함을 감시할 수 있습니다. 대양 위를 다닐 수 있습니다.'); 

---------------------
-- TEXT (US)
---------------------
UPDATE Language_en_US
SET Text = 'Melee Withdraw'
WHERE Tag ='TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_I';

UPDATE Language_en_US
SET Text = 'Unit withdraws from the first Melee attack each turn if there are open tiles behind the unit.'
WHERE Tag ='TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_HELP_I';

UPDATE Language_en_US
SET Text = 'Industrial Era Recon unit, gains bonus attack power when attacking and Withdrwas from the first Melee attack each turn. A Sapper who helps capture the city.' 
WHERE Tag = 'TXT_KEY_UNIT_HELP_COMMANDO_CBP';

UPDATE Language_en_US
SET Text = 'A modern-era Recon unit, gains bonus attack power when attacking and Withdrwas from the first Melee attack each turn. A Sapper who helps capture the city. [COLOR_PLAYER_PURPLE] There is an air drop [ENDCOLOR] upgrade.' 
WHERE Tag = 'TXT_KEY_UNIT_HELP_PARATROOPER';

UPDATE Language_en_US
SET Text = 'An Atomic Era Recon unit, gains bonus attack power when attacking and Withdrwas from the first Melee attack each turn. A Sapper who helps capture the city. [COLOR_PLAYER_PURPLE] Drop Troops[ENDCOLOR] There is a promotion.' 
WHERE Tag = 'TXT_KEY_UNIT_HELP_MARINE'; 

---------------------
-- TEXT (KR)
---------------------
UPDATE Language_ko_KR
SET Text = '위급회피'
WHERE Tag ='TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_I';

UPDATE Language_ko_KR
SET Text = '산업 시대 정찰 유닛으로, 공격 시 추가 전투력을 얻고 근접 유닛 대항 시 후퇴 할 수 있습니다. 도시의 공략을 도우는 공병입니다.' 
WHERE Tag = 'TXT_KEY_UNIT_HELP_COMMANDO_CBP';

UPDATE Language_ko_KR
SET Text = '현대 시대 정찰 유닛으로, 공격 시 추가 전투력을 얻고 근접 유닛 대항 시 후퇴 할 수 있습니다. 도시의 공략을 도우는 공병입니다. [COLOR_PLAYER_PURPLE]공중투하[ENDCOLOR]승급이 있습니다.' 
WHERE Tag = 'TXT_KEY_UNIT_HELP_PARATROOPER';

UPDATE Language_ko_KR
SET Text = '원자력 시대 정찰 유닛으로, 공격 시 추가 전투력을 얻고 근접 유닛 대항 시 후퇴 할 수 있습니다. 도시의 공략을 도우는 공병입니다. [COLOR_PLAYER_PURPLE]공중투하[ENDCOLOR] 승급이 있습니다.' 
WHERE Tag = 'TXT_KEY_UNIT_HELP_MARINE'; 

------------------------------	
----------------------------------------------------------------------------------------------------
-- New unit making
------------------------------------------------------------------------------------------------------
--=====================================================================================	
-- Recon UNIT REWORK  (AIRSHIP RECON + LAND RECON)
--=====================================================================================
INSERT INTO Unit_FreePromotions
		(UnitType,							PromotionType)
VALUES	
    ('UNIT_COMMANDO','PROMOTION_SAPPER'),
	('UNIT_COMMANDO','PROMOTION_OCEAN_CROSSING'),
	('UNIT_COMMANDO','PROMOTION_EMBARKED_SIGHT'),
	('UNIT_COMMANDO','PROMOTION_DEFENSIVE_EMBARKATION'),
	('UNIT_GREECE_KLEPHT','PROMOTION_SAPPER'),
	('UNIT_GREECE_KLEPHT','PROMOTION_OCEAN_CROSSING'),
	('UNIT_GREECE_KLEPHT','PROMOTION_EMBARKED_SIGHT'),
	('UNIT_GREECE_KLEPHT','PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_MARINE','PROMOTION_SAPPER'),
    ('UNIT_MARINE','PROMOTION_COMMANDO'),
	('UNIT_MARINE','PROMOTION_OCEAN_CROSSING'),
	('UNIT_MARINE','PROMOTION_EMBARKED_SIGHT'),
	('UNIT_MARINE','PROMOTION_DEFENSIVE_EMBARKATION'),
	('UNIT_PARATROOPER','PROMOTION_SAPPER'),
	('UNIT_PARATROOPER','PROMOTION_OCEAN_CROSSING'),
	('UNIT_PARATROOPER','PROMOTION_EMBARKED_SIGHT'),
	('UNIT_PARATROOPER','PROMOTION_DEFENSIVE_EMBARKATION'),
	('UNIT_PARATROOPER','PROMOTION_COMMANDO'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_COMMANDO'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_SAPPER'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_OCEAN_CROSSING'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_EMBARKED_SIGHT'),
    ('UNIT_FW_AIRBORNE_FORCES','PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_COMMANDO'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_SAPPER'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_OCEAN_CROSSING'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_EMBARKED_SIGHT'),
    ('UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER','PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_XCOM_SQUAD','PROMOTION_SAPPER'),
	('UNIT_XCOM_SQUAD','PROMOTION_COMMANDO'),
	('UNIT_XCOM_SQUAD','PROMOTION_OCEAN_CROSSING'),
    ('UNIT_XCOM_SQUAD','PROMOTION_EMBARKED_SIGHT'),
    ('UNIT_XCOM_SQUAD','PROMOTION_DEFENSIVE_EMBARKATION'),
    ('UNIT_FW_SPACEMARINES','PROMOTION_SAPPER'),
	('UNIT_FW_SPACEMARINES','PROMOTION_COMMANDO'),
	('UNIT_FW_SPACEMARINES','PROMOTION_OCEAN_CROSSING'),
	('UNIT_FW_SPACEMARINES','PROMOTION_EMBARKED_SIGHT'),
	('UNIT_FW_SPACEMARINES','PROMOTION_DEFENSIVE_EMBARKATION');
    
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_XCOM_SQUAD' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_ResourceQuantityRequirements  WHERE UnitType = 'UNIT_XCOM_SQUAD' AND ResourceType = 'RESOURCE_OIL';

DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_COMMANDO' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_GREECE_KLEPHT' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_PARATROOPER' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_PARATROOPER' AND PromotionType = 'PROMOTION_FREE_PILLAGE_MOVES';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_MARINE' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_SCOUT_XP_PILLAGE';
-------------------------------------------------------------------------------------------------------------------------------





*/

/*
----------------------------------------
--  Need Resources
---------------------------------------
-- MARINE에 OIL 1 요구 (존재 확인 + 중복 방지)
INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost)
SELECT 'UNIT_MARINE', 'RESOURCE_OIL', 1
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_MARINE')
  AND NOT EXISTS (
      SELECT 1 FROM Unit_ResourceQuantityRequirements
      WHERE UnitType = 'UNIT_MARINE' AND ResourceType = 'RESOURCE_OIL'
  );

-- PARATROOPER
INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost)
SELECT 'UNIT_PARATROOPER', 'RESOURCE_OIL', 1
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_PARATROOPER')
  AND NOT EXISTS (
      SELECT 1 FROM Unit_ResourceQuantityRequirements
      WHERE UnitType = 'UNIT_PARATROOPER' AND ResourceType = 'RESOURCE_OIL'
  );

-- XCOM SQUAD
INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost)
SELECT 'UNIT_XCOM_SQUAD', 'RESOURCE_OIL', 1
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_XCOM_SQUAD')
  AND NOT EXISTS (
      SELECT 1 FROM Unit_ResourceQuantityRequirements
      WHERE UnitType = 'UNIT_XCOM_SQUAD' AND ResourceType = 'RESOURCE_OIL'
  );

-- COMMANDO (유닛이 실제로 있는 모드인지 확인 필요)
INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost)
SELECT 'UNIT_COMMANDO', 'RESOURCE_COAL', 1
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_COMMANDO')
  AND NOT EXISTS (
      SELECT 1 FROM Unit_ResourceQuantityRequirements
      WHERE UnitType = 'UNIT_COMMANDO' AND ResourceType = 'RESOURCE_COAL'
  );

  -- PARATROOPER
INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost)
SELECT 'UNIT_PARATROOPER', 'RESOURCE_OIL', 1
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND NOT EXISTS (
      SELECT 1 FROM Unit_ResourceQuantityRequirements
      WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND ResourceType = 'RESOURCE_OIL'
  );

-----------------------------------------------------
-- FUTURE 모드 추가
-----------------------------------------------------
-- === AIRBORNE FORCES ===
INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_AIRBORNE_FORCES', 'PROMOTION_SAPPER'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_AIRBORNE_FORCES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_SAPPER')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_SAPPER'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_AIRBORNE_FORCES', 'PROMOTION_OCEAN_CROSSING'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_AIRBORNE_FORCES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_OCEAN_CROSSING')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_OCEAN_CROSSING'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_AIRBORNE_FORCES', 'PROMOTION_EMBARKED_SIGHT'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_AIRBORNE_FORCES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_EMBARKED_SIGHT')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_EMBARKED_SIGHT'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_AIRBORNE_FORCES', 'PROMOTION_COMMANDO'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_AIRBORNE_FORCES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_COMMANDO')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_COMMANDO'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_AIRBORNE_FORCES', 'PROMOTION_DEFENSIVE_EMBARKATION'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_AIRBORNE_FORCES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_DEFENSIVE_EMBARKATION')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_DEFENSIVE_EMBARKATION'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_AIRBORNE_FORCES', 'PROMOTION_SCOUT_GOODY_BONUS'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_AIRBORNE_FORCES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_SCOUT_GOODY_BONUS')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_AIRBORNE_FORCES' AND PromotionType = 'PROMOTION_SCOUT_GOODY_BONUS'
  );

-- === ORBITAL DROP SHOCK TROOPER ===
INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'PROMOTION_SAPPER'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_SAPPER')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_SAPPER'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'PROMOTION_OCEAN_CROSSING'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_OCEAN_CROSSING')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_OCEAN_CROSSING'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'PROMOTION_EMBARKED_SIGHT'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_EMBARKED_SIGHT')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_EMBARKED_SIGHT'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'PROMOTION_COMMANDO'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_COMMANDO')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_COMMANDO'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'PROMOTION_DEFENSIVE_EMBARKATION'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_DEFENSIVE_EMBARKATION')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_DEFENSIVE_EMBARKATION'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER', 'PROMOTION_SCOUT_GOODY_BONUS'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_SCOUT_GOODY_BONUS')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_ORBITAL_DROP_SHOCK_TROOPER' AND PromotionType = 'PROMOTION_SCOUT_GOODY_BONUS'
  );

-- === SPACEMARINES ===
INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_SPACEMARINES', 'PROMOTION_SAPPER'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_SPACEMARINES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_SAPPER')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_SAPPER'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_SPACEMARINES', 'PROMOTION_OCEAN_CROSSING'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_SPACEMARINES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_OCEAN_CROSSING')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_OCEAN_CROSSING'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_SPACEMARINES', 'PROMOTION_EMBARKED_SIGHT'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_SPACEMARINES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_EMBARKED_SIGHT')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_EMBARKED_SIGHT'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_SPACEMARINES', 'PROMOTION_COMMANDO'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_SPACEMARINES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_COMMANDO')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_COMMANDO'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_SPACEMARINES', 'PROMOTION_DEFENSIVE_EMBARKATION'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_SPACEMARINES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_DEFENSIVE_EMBARKATION')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_DEFENSIVE_EMBARKATION'
  );

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
SELECT 'UNIT_FW_SPACEMARINES', 'PROMOTION_SCOUT_GOODY_BONUS'
WHERE EXISTS (SELECT 1 FROM Units WHERE Type = 'UNIT_FW_SPACEMARINES')
  AND EXISTS (SELECT 1 FROM UnitPromotions WHERE Type = 'PROMOTION_SCOUT_GOODY_BONUS')
  AND NOT EXISTS (
    SELECT 1 FROM Unit_FreePromotions 
    WHERE UnitType = 'UNIT_FW_SPACEMARINES' AND PromotionType = 'PROMOTION_SCOUT_GOODY_BONUS'
  );

------------------------------------------------------------------------
