UPDATE Units SET Capture = Class
WHERE Class IN ('UNITCLASS_ENGINEER', 'UNITCLASS_SCIENTIST', 'UNITCLASS_MERCHANT', 'UNITCLASS_ARTIST', 'UNITCLASS_MUSICIAN', 'UNITCLASS_WRITER', 'UNITCLASS_GREAT_DIPLOMAT', 'UNITCLASS_PROPHET', 'UNITCLASS_WORKBOAT', 'UNITCLASS_EMISSARY', 'UNITCLASS_ENVOY', 'UNITCLASS_DIPLOMAT', 'UNITCLASS_AMBASSADOR');

CREATE TRIGGER IF NOT EXISTS Jar_CaptureCivilians
AFTER INSERT ON Units WHEN Class IN
('UNITCLASS_ENGINEER', 'UNITCLASS_SCIENTIST', 'UNITCLASS_MERCHANT', 'UNITCLASS_ARTIST', 'UNITCLASS_MUSICIAN', 'UNITCLASS_WRITER', 'UNITCLASS_GREAT_DIPLOMAT', 'UNITCLASS_PROPHET', 'UNITCLASS_WORKBOAT', 'UNITCLASS_EMISSARY', 'UNITCLASS_ENVOY', 'UNITCLASS_DIPLOMAT', 'UNITCLASS_AMBASSADOR')
BEGIN
	UPDATE Units SET Capture = NEW.Class WHERE Type= NEW.Type;
END;

--select Type, Capture from Units WHERE Class IN ('UNITCLASS_ENGINEER', 'UNITCLASS_SCIENTIST', 'UNITCLASS_MERCHANT', 'UNITCLASS_ARTIST', 'UNITCLASS_MUSICIAN', 'UNITCLASS_WRITER', 'UNITCLASS_GREAT_DIPLOMAT', 'UNITCLASS_PROPHET', 'UNITCLASS_WORKBOAT', 'UNITCLASS_EMISSARY', 'UNITCLASS_ENVOY', 'UNITCLASS_DIPLOMAT', 'UNITCLASS_AMBASSADOR');