UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]산코레 대학[ENDCOLOR] 건설.', 	'불가사의: [COLOR_CYAN]산코레 대학[ENDCOLOR], [COLOR_CYAN]쉐다곤 파고다[ENDCOLOR], [COLOR_CYAN]노트르담 대성당[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 	WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]자금성[ENDCOLOR] 건설.', 		'불가사의: [COLOR_CYAN]자금성[ENDCOLOR], [COLOR_CYAN]바르트부르크 성[ENDCOLOR], [COLOR_CYAN]뷔위크 한[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 					WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]알함브라[ENDCOLOR] 건설.', 					'불가사의: [COLOR_CYAN]알함브라[ENDCOLOR], [COLOR_CYAN]다마스쿠스 대장간[ENDCOLOR], [COLOR_CYAN]그레이트 짐바브웨[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 				WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]붉은 성[ENDCOLOR] 건설.', 				'불가사의: [COLOR_CYAN]붉은 성[ENDCOLOR], [COLOR_CYAN]금각사[ENDCOLOR], [COLOR_CYAN]솔로베츠키 수도원[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]웨스트민스터 궁전[ENDCOLOR] 건설.', 	'불가사의: [COLOR_CYAN]웨스트민스터 궁전[ENDCOLOR], [COLOR_CYAN]킬와 키시와니[ENDCOLOR], [COLOR_CYAN]모스타르의 오래된 다리[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]루브르 박물관[ENDCOLOR] 건설.', 					'불가사의: [COLOR_CYAN]루브르 박물관[ENDCOLOR], [COLOR_CYAN]몬테카를로 카지노[ENDCOLOR], [COLOR_CYAN]박물관 섬[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 							WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]브로드웨이[ENDCOLOR] 건설.', 					'불가사의: [COLOR_CYAN]브로드웨이[ENDCOLOR], [COLOR_CYAN]루르 밸리[ENDCOLOR], [COLOR_CYAN]밴프 스프링스 호텔[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 			WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]펜타곤[ENDCOLOR] 건설.', 				'불가사의: [COLOR_CYAN]펜타곤[ENDCOLOR], [COLOR_CYAN]브란덴부르크 문[ENDCOLOR], [COLOR_CYAN]화이트 샌즈 미사일 시험장[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 				WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]블레츨리 파크[ENDCOLOR] 건설.', 				'불가사의: [COLOR_CYAN]블레츨리 파크[ENDCOLOR], [COLOR_CYAN]큐 왕립식물원[ENDCOLOR], [COLOR_CYAN]아레시보 천문대[ENDCOLOR] (새로 잠금 해제된 이 불가사의들 중 제국에 [COLOR_NEGATIVE_TEXT]하나만[ENDCOLOR] 건설할 수 있습니다).') 			WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';
--============================================--
-- FREE ART HELP TEXTS
--============================================--
UPDATE Language_ko_KR SET Text = REPLACE(Text, '미리 제작된 [ICON_GREAT_WORK] 위대한 예술품을 포함합니다. ', '[ICON_GREAT_WORK] [COLOR_CULTURE_STORED]왕관 보석[ENDCOLOR]으로 시작합니다.[NEWLINE][NEWLINE]') WHERE Tag ='TXT_KEY_BUILDING_WHITE_TOWER_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]무료[ENDCOLOR] [ICON_GREAT_WORK] 위대한 작품과 함께 제공됩니다', '[COLOR_CULTURE_STORED] [COLOR_MAGENTA]홍수 서판[ENDCOLOR]으로 시작합니다') WHERE Tag ='TXT_KEY_BUILDING_ROYAL_LIBRARY_HELP';