CREATE TABLE Civilization_4UCSupport (
	CivilizationType	varchar(255),
	Has4UCSupport		bool
);


INSERT INTO	Civilization_4UCSupport
			(CivilizationType, Has4UCSupport)
VALUES		('CIVILIZATION_AMERICA', 1),
			('CIVILIZATION_ARABIA', 1),
			('CIVILIZATION_AZTEC', 1),
			('CIVILIZATION_CHINA', 1),
			('CIVILIZATION_EGYPT', 1),
			('CIVILIZATION_ENGLAND', 1),
			('CIVILIZATION_FRANCE', 1),
			('CIVILIZATION_GERMANY', 1),
			('CIVILIZATION_GREECE', 1),
			('CIVILIZATION_INDIA', 1),
			('CIVILIZATION_IROQUOIS', 1),
			('CIVILIZATION_JAPAN', 1),
			('CIVILIZATION_OTTOMAN', 1),
			('CIVILIZATION_PERSIA', 1),
			('CIVILIZATION_ROME', 1),
			('CIVILIZATION_RUSSIA', 1),
			('CIVILIZATION_SIAM', 1),
			('CIVILIZATION_SONGHAI', 1),
			('CIVILIZATION_MONGOL', 1),
			('CIVILIZATION_INCA', 1),
			('CIVILIZATION_SPAIN', 1),
			('CIVILIZATION_POLYNESIA', 1),
			('CIVILIZATION_DENMARK', 1),
			('CIVILIZATION_KOREA', 1),
			('CIVILIZATION_BABYLON', 1),
			('CIVILIZATION_AUSTRIA', 1),
			('CIVILIZATION_BYZANTIUM', 1),
			('CIVILIZATION_CARTHAGE', 1),
			('CIVILIZATION_CELTS', 1),
			('CIVILIZATION_ETHIOPIA', 1),
			('CIVILIZATION_HUNS', 1),
			('CIVILIZATION_MAYA', 1),
			('CIVILIZATION_NETHERLANDS', 1),
			('CIVILIZATION_SWEDEN', 1),
			('CIVILIZATION_ASSYRIA', 1),
			('CIVILIZATION_BRAZIL', 1),
			('CIVILIZATION_INDONESIA', 1),
			('CIVILIZATION_MOROCCO', 1),
			('CIVILIZATION_POLAND', 1),
			('CIVILIZATION_PORTUGAL', 1),
			('CIVILIZATION_SHOSHONE', 1),
			('CIVILIZATION_VENICE', 1),
			('CIVILIZATION_ZULU', 1),
			('CIVILIZATION_JFD_JAPAN_TOJO', 1),
			('CIVILIZATION_JFD_PRUSSIA', 1),
			('CIVILIZATION_JFD_GREAT_BRITAIN', 1),
			('CIVILIZATION_AKKADIAN_MOD', 1),
			('CIVILIZATION_LEUGI_ISRAEL', 1),
			('CIVILIZATION_JFD_PAPAL_STATES', 1),
			('CIVILIZATION_TIMURIDS_MOD', 1);

-- Dummy building
INSERT INTO BuildingClasses
			(Type,									DefaultBuilding,				NoLimit)
VALUES		('BUILDINGCLASS_GENERIC_BONUS_DUMMY',	'BUILDING_GENERIC_BONUS_DUMMY',	1);

INSERT INTO Buildings
			(Type,										BuildingClass,	
			Cost,	FaithCost,	GreatWorkCount, PrereqTech, NeverCapture,	NukeImmune)
VALUES		('BUILDING_GENERIC_BONUS_DUMMY',		'BUILDINGCLASS_GENERIC_BONUS_DUMMY',
			-1,		-1,			-1,				NULL,		1);

INSERT INTO Building_YieldChanges
			(BuildingType,						YieldType,			Yield)
VALUES		('BUILDING_GENERIC_BONUS_DUMMY',	'YIELD_FOOD',		1),
			('BUILDING_GENERIC_BONUS_DUMMY',	'YIELD_PRODUCTION',	1),
			('BUILDING_GENERIC_BONUS_DUMMY',	'YIELD_GOLD',		1);
