INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
SELECT 'ENGINSEER_ATLAS', '256', 'WCRAtlas256.dds', 4, 3 UNION ALL
SELECT 'ENGINSEER_ATLAS', '128', 'WCRAtlas128.dds', 4, 3 UNION ALL
SELECT 'ENGINSEER_ATLAS', '80', 'WCRAtlas80.dds', 4, 3 UNION ALL
SELECT 'ENGINSEER_ATLAS', '64', 'WCRAtlas64.dds', 4, 3 UNION ALL
SELECT 'ENGINSEER_ATLAS', '45', 'WCRAtlas45.dds', 4, 3 UNION ALL
SELECT 'ENGINSEER_ATLAS', '32', 'WCRAtlas32.dds', 4, 3;