UPDATE Language_ko_KR
SET Text = '이 불가사의가 건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_STONE_WORKS}과 [ICON_RESEARCH] 과학 40을 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_BARNENEZ_HELP';

UPDATE Language_ko_KR
SET Text = '이 불가사의가 건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_GRANARY}를 제공합니다. 도시에 새로운 [ICON_CITIZEN] 시민이 태어나면 [ICON_GOLDEN_AGE] 황금기 점수 20을 얻습니다. (시대에 따라 보정) [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_NEWGRANGE_HELP';

UPDATE Language_ko_KR
SET Text = '도시 근처에 {TXT_KEY_UNIT_WORKER}가 나타납니다. 도시 근처에 [ICON_RES_HORSE] 말 4마리를 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_SKARABRAE_HELP';

UPDATE Language_ko_KR
SET Text = '건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_LODGE}과 [ICON_CITIZEN] 인구 2명을 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_GGANTIJA_HELP';

UPDATE Language_ko_KR
SET Text = '건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_GROVE}과 [ICON_PEACE] 신앙 60을 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_STONEHENGE_HELP' AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE');