INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
SELECT 'POLICY_ICONATLAS', 256, 'POLICY_ICONATLAS256.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 128, 'POLICY_ICONATLAS128.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 80, 'POLICY_ICONATLAS80.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 64, 'POLICY_ICONATLAS64.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 45, 'POLICY_ICONATLAS45.dds', 8, 2;

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Tradition grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_TRADITION} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PUBLIC_BATHS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Progress grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_LIBERTY} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_TOWN_COUNCIL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';

UPDATE Language_en_US
	SET Text = Text || '[NEWLINE][ICON_BULLET]+1 [ICON_CULTURE_LOCAL] Border Growth from City Halls.'
	WHERE Tag = 'TXT_KEY_POLICY_COLLECTIVE_RULE_HELP';

UPDATE Language_en_US
	SET Text = Text || '[NEWLINE][ICON_BULLET]+1 [ICON_GOLDEN_AGE] Golden Age Point from City Halls.'
	WHERE Tag = 'TXT_KEY_POLICY_CITIZENSHIP_HELP';

UPDATE Language_en_US
	SET Text = Text || '[NEWLINE][ICON_BULLET]+1 [ICON_PRODUCTION] Production from City Halls.'
	WHERE Tag = 'TXT_KEY_POLICY_REPUBLIC_HELP';

UPDATE Language_en_US
	SET Text = Text || '[NEWLINE][ICON_BULLET]+1 [ICON_GOLD] Gold from City Halls.'
	WHERE Tag = 'TXT_KEY_POLICY_REPRESENTATION_HELP';

UPDATE Language_en_US
	SET Text = Text || '[NEWLINE][ICON_BULLET]+1 [ICON_FOOD] Food from City Halls.'
	WHERE Tag = 'TXT_KEY_POLICY_MERITOCRACY_HELP';
	
UPDATE Language_en_US
	SET TEXT = REPLACE(Text, 'toward Castles', 'toward Manor Houses, Castles,')
	WHERE Tag = 'TXT_KEY_POLICY_MANDATE_OF_HEAVEN_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Authority grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_HONOR} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_STRONGHOLD}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Fealty grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_PIETY} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Statecraft grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_PATRONAGE} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_CHANCERY}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Artistry grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_AESTHETICS} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_MEMORIAL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Industry grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_COMMERCE} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PATENT_OFFICE}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Imperialism grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_EXPLORATION} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_DEPOT}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';

UPDATE	Language_en_US SET
		Text = REPLACE(Text, 'Adopting Rationalism grants:[ENDCOLOR]', 'Adopting {TXT_KEY_POLICY_BRANCH_RATIONALISM} grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';

INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', 'Sauna'),
	('en_US', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', 'City Hall'),
	('en_US', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', 'Stronghold'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', 'Manor House'),
	('en_US', 'TXT_KEY_BUILDING_TCS_CHANCERY', 'State Embassy'),
	('en_US', 'TXT_KEY_BUILDING_TCS_MEMORIAL', 'Memorial'),
	('en_US', 'TXT_KEY_BUILDING_TCS_DEPOT', 'Depot'),
	('en_US', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', 'Botanical Garden'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', 'Patent Office'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', '{TXT_KEY_BUILDING_WELL} and {TXT_KEY_BUILDING_BATH} in this City gain +1 [ICON_FOOD] Food and start 10 turns of "We Love the King Day" in the City.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_TRADITION}[ENDCOLOR]'),
	('en_US', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', '+2% [ICON_GOLD] Gold from [ICON_CONNECTED] City Connections. City Hall generate additional yields as [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_LIBERTY}[ENDCOLOR] policies are unlocked.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_LIBERTY}[ENDCOLOR]'),
	('en_US', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', '+75 [ICON_CULTURE_LOCAL] Border Growth when completed. +1 [ICON_PRODUCTION] Production to Forts and Citadels. +1 [ICON_RESEARCH] Science once [COLOR_CYAN]{TXT_KEY_TECH_ENGINEERING}[ENDCOLOR] is discovered.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_HONOR}[ENDCOLOR].'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', '+100 [ICON_FOOD] Food when completed. Gain 15% of the Cost of any [ICON_PEACE] Faith purchase as [ICON_FOOD] Food and [ICON_CULTURE] Culture in this City. +15% [ICON_PEACE] Faith during "We Love the King Day."[NEWLINE][NEWLINE][ICON_CITY_STATE] Empire Size Modifier is reduced by 5% in this City.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_PIETY}[ENDCOLOR].'),
	('en_US', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', '+1 [ICON_RES_PAPER] Paper. Receive 1 [COLOR_POSITIVE_TEXT]Additional[ENDCOLOR] [ICON_DIPLOMAT] Delegate in the World Congress. Civil Servants in all Cities produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE]+1 [ICON_GOLD] Gold for every City-State Friend, and additionally +1 [ICON_RESEARCH] Science and [ICON_CULTURE] Culture for every Ally.[NEWLINE][NEWLINE]Can only be constructed in the [ICON_CAPITAL] Capital and if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_PATRONAGE}[ENDCOLOR].'),
	('en_US', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', '+5 [ICON_GOLDEN_AGE] Golden Age Points when you expend a [ICON_GREAT_PEOPLE] Great Person, scaling with Era.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_AESTHETICS}[ENDCOLOR].'),
	('en_US', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', '+10% [ICON_SILVER_FIST] Military Supply from [ICON_CITIZEN] Population. Internal [ICON_INTERNATIONAL_TRADE] Trade Routes to or from this City generate 100 [ICON_GOLD] Gold in their Origin City when completed, scaling with Era.[NEWLINE][NEWLINE]When you train a Unit in this City, gain [ICON_GOLD] Gold equal to 10% of the Unit''s [ICON_PRODUCTION] Production cost.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_EXPLORATION}[ENDCOLOR].'),
	('en_US', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', '+1 [ICON_RESEARCH] Science for every 2 Jungle, Forest, and Flood Plains worked by the City. +1 [ICON_RESEARCH] Science from every Marshes, Oases, and Atolls.[NEWLINE][NEWLINE][ICON_VP_SCIENTIST] Scientists, {TXT_KEY_BUILDING_GARDEN}, and {TXT_KEY_BUILDING_THEATRE} in the City generate +2 [ICON_FOOD] Food.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_RATIONALISM}[ENDCOLOR].'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', '[ICON_VP_ENGINEER] Engineers, [ICON_VP_MERCHANT] Merchants, and [ICON_GREAT_WORK] Great Works in this City produce +1  [ICON_GOLD] Gold.[NEWLINE][NEWLINE]Gain 20 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold every time you research a Technology, scaling with Era.[NEWLINE][NEWLINE]Can only be constructed if you adopt [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_COMMERCE}[ENDCOLOR].');

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
	SELECT 'BUILDINGCLASS_TCS_PUBLIC_BATHS', 'BUILDING_TCS_PUBLIC_BATHS', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'BUILDING_TCS_TOWN_COUNCIL', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_STRONGHOLD', 'BUILDING_TCS_STRONGHOLD', 'TXT_KEY_BUILDING_TCS_STRONGHOLD' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_CHANCERY', 'BUILDING_TCS_CHANCERY', 'TXT_KEY_BUILDING_TCS_CHANCERY' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_MEMORIAL', 'BUILDING_TCS_MEMORIAL', 'TXT_KEY_BUILDING_TCS_MEMORIAL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_DEPOT', 'BUILDING_TCS_DEPOT', 'TXT_KEY_BUILDING_TCS_DEPOT' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_BOTANICAL_GARDENS', 'BUILDING_TCS_BOTANICAL_GARDENS', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_PATENT_OFFICE', 'BUILDING_TCS_PATENT_OFFICE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE';

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, PolicyBranchType, Description, Help, MinAreaSize, NukeImmune, NeverCapture, HurryCostModifier, IconAtlas, PortraitIndex)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_TCS_PUBLIC_BATHS', 80, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'), NULL, 'POLICY_BRANCH_TRADITION', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY'), 'POLICY_ICONATLAS', 0 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 80, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'), NULL, 'POLICY_BRANCH_LIBERTY', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY'), 'POLICY_ICONATLAS', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'BUILDINGCLASS_TCS_STRONGHOLD', 80, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'), NULL, 'POLICY_BRANCH_HONOR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY'), 'POLICY_ICONATLAS', 2 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 250, 0, NULL, 'POLICY_BRANCH_PIETY', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HARBOR'), 'POLICY_ICONATLAS', 3 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'BUILDINGCLASS_TCS_CHANCERY', 500, 0, NULL, 'POLICY_BRANCH_PATRONAGE', 'TXT_KEY_BUILDING_TCS_CHANCERY', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HARBOR'), 'POLICY_ICONATLAS', 4 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'BUILDINGCLASS_TCS_MEMORIAL', 250, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_HARBOR'), NULL, 'POLICY_BRANCH_AESTHETICS', 'TXT_KEY_BUILDING_TCS_MEMORIAL', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HARBOR'), 'POLICY_ICONATLAS', 5 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'BUILDINGCLASS_TCS_DEPOT', 500, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), NULL, 'POLICY_BRANCH_EXPLORATION', 'TXT_KEY_BUILDING_TCS_DEPOT', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'POLICY_ICONATLAS', 6 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_TCS_BOTANICAL_GARDENS', 500, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), NULL, 'POLICY_BRANCH_RATIONALISM', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'POLICY_ICONATLAS', 7 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'BUILDINGCLASS_TCS_PATENT_OFFICE', 500, 0, NULL, 'POLICY_BRANCH_COMMERCE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'POLICY_ICONATLAS', 8;
--So it got flipped. Depot is moved to Imperialism. Botanical Garden moved to Rationalism. Patent Office moved to Industry!
INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
	SELECT 'BUILDING_TCS_CHANCERY', 'BUILDINGCLASS_PALACE';

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_CULTURE', 1 UNION ALL
	--SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FAITH', 2 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FOOD', 2 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_CULTURE', 2 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_SCIENCE', 2 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 2 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_CULTURE', 3 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_TOURISM', 2 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_GOLD', 3 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_PRODUCTION', 5 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_FOOD', 3;

INSERT INTO Building_TechEnhancedYieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_SCIENCE', 1;
	
INSERT INTO Building_InstantYield (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_CULTURE_LOCAL', 75 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FOOD', 100;
	
INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_FORT', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_CITADEL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_MONGOLIA_ORDO', 'YIELD_PRODUCTION', 1;
	
INSERT INTO Building_ResourceQuantity (BuildingType, ResourceType, Quantity)
	SELECT 'BUILDING_TCS_CHANCERY', 'RESOURCE_PAPER', 1;
	
--INSERT	INTO Building_YieldFromYieldPercent (BuildingType, YieldIn, YieldOut, Value )
--	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_FOOD', 'YIELD_SCIENCE', 5;

INSERT	INTO Building_YieldPerXFeatureTimes100 (BuildingType, FeatureType, YieldType, Yield)
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', Type, 'YIELD_SCIENCE', 50 FROM Features
	WHERE Type IN ('FEATURE_JUNGLE', 'FEATURE_FOREST', 'FEATURE_FLOOD_PLAINS');
	
INSERT INTO Building_FeatureYieldChanges (BuildingType, FeatureType, YieldType, Yield)
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FEATURE_MARSH', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FEATURE_ATOLL', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FEATURE_OASIS', 'YIELD_SCIENCE', 1;
		
INSERT INTO Building_BuildingClassLocalYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_WELL', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_BATH', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_GARDEN', 'YIELD_FOOD', 2 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_THEATRE', 'YIELD_FOOD', 2;

INSERT INTO Building_YieldFromFaithPurchase (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FOOD', 15 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_CULTURE', 15;
	
INSERT	INTO Building_WLTKDYieldMod (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FAITH', 15;

INSERT INTO Building_SpecialistYieldChanges (BuildingType, SpecialistType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLD', 1;
	
INSERT INTO Building_YieldPerFriend (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 1;

INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_CULTURE', 1 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_SCIENCE', 1;

INSERT	INTO Building_YieldFromGPExpend (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_GOLDEN_AGE_POINTS', 5;
	
INSERT	INTO Building_GreatWorkYieldChangesLocal (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_GOLD', 1;
	
INSERT	INTO Building_SpecialistYieldChangesLocal (BuildingType, SpecialistType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'SPECIALIST_ENGINEER', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'SPECIALIST_SCIENTIST', 'YIELD_FOOD', 2;
	
INSERT	INTO Building_YieldFromUnitProduction (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 10;
	
INSERT	INTO Building_YieldFromTech (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_GOLD', 20  UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_PRODUCTION', 20;
	
INSERT INTO Building_YieldFromInternalTREnd (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 100;

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_CULTURE', 10 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_GROWTH', 20 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_GREAT_PEOPLE', 5 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'FLAVOR_INFRASTRUCTURE', 20 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'FLAVOR_PRODUCTION', 5 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_CITY_DEFENSE', 10 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_EXPANSION', 5 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_MILITARY_TRAINING', 15 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_OFFENSE', 20 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_RELIGION', 20 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_CULTURE', 10 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_EXPANSION', 5 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_GROWTH', 5 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_RELIGION', 25 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_CULTURE', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_DIPLOMACY', 25 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_GOLD', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_SCIENCE', 5 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'FLAVOR_CULTURE', 25 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'FLAVOR_GREAT_PEOPLE', 20 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_GOLD', 10 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_MILITARY_TRAINING', 30 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_PRODUCTION', 15 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FLAVOR_GROWTH', 25 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FLAVOR_SCIENCE', 30 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_GOLD', 20 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_INFRASTRUCTURE', 30 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_PRODUCTION', 15;
	
INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
	SELECT 'POLICY_COLLECTIVE_RULE', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
	SELECT 'POLICY_CITIZENSHIP', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
	SELECT 'POLICY_REPUBLIC', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'POLICY_REPRESENTATION', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'POLICY_MERITOCRACY', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_FOOD', 1;
	
INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
	SELECT 'POLICY_MANDATE_OF_HEAVEN', 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 100;

UPDATE Buildings
SET WLTKDTurns = 10
WHERE Type = 'BUILDING_TCS_PUBLIC_BATHS';

UPDATE	Buildings
SET CityConnectionTradeRouteModifier = 2
WHERE Type = 'BUILDING_TCS_TOWN_COUNCIL';
	
UPDATE Buildings
SET Defense = 300, ExtraCityHitPoints = 50, EnhancedYieldTech = 'TECH_ENGINEERING'
WHERE Type = 'BUILDING_TCS_STRONGHOLD';

UPDATE Buildings
SET FaithCost = 200 --, EmpireSizeModifierReduction = -5
WHERE Type = 'BUILDING_TCS_PAROCHIAL_SCHOOL';

UPDATE Buildings
SET SingleLeagueVotes = 1, CapitalOnly = 1, SpecialistType = 'SPECIALIST_CIVIL_SERVANT', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_TCS_CHANCERY';	

UPDATE Buildings
SET CitySupplyModifier = 10, Happiness = 1
WHERE Type = 'BUILDING_TCS_DEPOT';