---------------------------------------------------
-- Updates - Language_ko_KR
---------------------------------------------------
UPDATE Language_ko_KR SET Text = '[NEWLINE][COLOR_WARNING_TEXT][ICON_BULLET] 군사력이 상위 50% 안에 들어야 합니다. 당신의 군사력은 상위 {1_Num}% 입니다.[ENDCOLOR]' WHERE Tag = 'TXT_KEY_POP_CSTATE_PLEDGE_NEED_MORE_MILITARY_TT';
UPDATE Language_ko_KR
SET Text = '당신은 {1_CityStateName:textkey}의 [COLOR_POSITIVE_TEXT]동맹[ENDCOLOR]입니다. 만약 당신이 동맹을 잃게 된다면 보너스는 [COLOR_FONT_RED]3[ENDCOLOR]턴 동안만 지속될 것입니다. 매 턴 해당 도시 국가와의 [ICON_INFLUENCE]영향력이 {2_Num} 변경됩니다. 당신이 [COLOR_POSITIVE_TEXT]보호 선언[ENDCOLOR]을 하고서 {1_CityStateName:textkey}{@1_CityStateName: plural 1?이; 2?가;} 피해를 받으면 영향력은 3배 빠르게 감소합니다.'
WHERE Tag = 'TXT_KEY_ALLIES_CSTATE_TT';
UPDATE Language_ko_KR
SET Text =  '도시 국가와의 [ICON_INFLUENCE]영향력이 [COLOR_POSITIVE_TEXT]45[ENDCOLOR]에서 시작합니다. 우호 및 동맹인 도시 국가의 산출량이 [COLOR_POSITIVE_TEXT]75%[ENDCOLOR] 증가합니다. 동맹인 도시 국가 수도의 전투력이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 증가합니다. 도시 국가로부터 선물 받은 유닛의 경험치가 [COLOR_POSITIVE_TEXT]10[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_TRAIT_CITY_STATE_BONUSES';

UPDATE Language_ko_KR SET Text = REPLACE(Text, 'Available![ENDCOLOR]', '[ENDCOLOR]available!') WHERE Tag = 'TXT_KEY_CSTATE_CAN_EMBASSY';
UPDATE Language_ko_KR SET Text = REPLACE(Text, 'Available![ENDCOLOR].', '[ENDCOLOR]available!') WHERE Tag = 'TXT_KEY_CSTATE_CAN_PROTECT';
UPDATE Language_ko_KR SET Text = REPLACE(Text, 'early.[NEWLINE][NEWLINE]', 'early.') WHERE Tag = 'TXT_KEY_CSTATE_JERK_STATUS';	
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
-- Texts
---------------------------------------------------
INSERT INTO Language_ko_KR (Tag, Text)
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV', '동맹 변화'  UNION ALL
SELECT 'TXT_KEY_CS_ACTIVE_BONUS_HEADER', 				'[COLOR_LIGHT_GREY]도시국가의 주 플레이어 보너스:[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_CS_PASSIVE_BONUS_HEADER', 				'[COLOR_LIGHT_GREY]도시국가의 기본 능력:[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_CS_UU_QUICK_INFO', 						'고유 유닛: [COLOR_YIELD_FOOD]{1_Unique_Unit}[ENDCOLOR], [COLOR_CYAN]{2_Tech}[ENDCOLOR] 이후'  UNION ALL
SELECT 'TXT_KEY_MARITIME_BONUS', 						'[COLOR:90:205:40:255]건축가 (해양적):[ENDCOLOR][NEWLINE][ICON_BULLET] 제조공장과 추가 보너스 자원을 가지고 시작합니다.[NEWLINE][ICON_BULLET]  [ICON_FOOD] 인구 성장 +15%[NEWLINE][ICON_BULLET] [ICON_CITIZEN] 시민이 탄생할 때마다 10 [ICON_CULTURE_LOCAL] 국경 확장 점수[NEWLINE][ICON_BULLET] [COLOR_NEGATIVE_TEXT] [ICON_SPY] 스파이 작업 속도 +20%[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_MARITIME_FRIENDLY_BONUS', 				'[COLOR:200:240:140:255]수확자 (해양적 우호적):[ENDCOLOR][NEWLINE][ICON_BULLET] 5%의 확률로 플레이어의 영토에 노동자 또는 작업선이 등장합니다. (작업선은 해양 도시에서만 등장)[NEWLINE][ICON_BULLET] 노동자와 작업선 생산 시 [ICON_PRODUCTION] 생산 +50%[NEWLINE][ICON_BULLET] 보너스 자원 [ICON_FOOD] 식량 +1'  UNION ALL
SELECT 'TXT_KEY_MARITIME_NEUTRAL_BONUS', 				'[COLOR:110:160:70:255]보안 창고 (해양적 중립적):[ENDCOLOR][NEWLINE][ICON_BULLET] [ICON_CITIZEN] 시민 4명마다 +10 [ICON_FOOD] 식량을 얻습니다. [NEWLINE][ICON_BULLET] [ICON_STRENGTH] 방어력 +10, 도시 체력 +50'  UNION ALL
SELECT 'TXT_KEY_MARITIME_HOSTILE_BONUS', 				'[COLOR:60:125:40:255]탐욕스런 수집가 (해양적 적대적):[ENDCOLOR][NEWLINE][ICON_BULLET] 해상 유닛 생산시 +20% [ICON_PRODUCTION] 생산력을 얻습니다.[NEWLINE][ICON_BULLET] 유닛을 [ICON_PRODUCTION]생산 시 50 [ICON_FOOD] 식량과 20 [ICON_CULTURE_LOCAL] 국경 확장 점수[NEWLINE][ICON_BULLET] [ICON_CITIZEN]시민 2명마다 +1 [ICON_PRODUCTION] 생산'  UNION ALL
SELECT 'TXT_KEY_MERCANTILE_BONUS', 						'[COLOR:240:215:65:255]무역 센터 (상업적):[ENDCOLOR][NEWLINE][ICON_BULLET] 근처에 마을과 추가 사치자원을 가지고 시작합니다.[NEWLINE][ICON_BULLET] [ICON_GOLD] 골드 +10%[NEWLINE][ICON_BULLET]  [ICON_GOLD] 골드 생산량의 5%만큼 [ICON_FOOD] 식량과 [ICON_PRODUCTION] 생산을 얻음[NEWLINE][ICON_BULLET] [ICON_GOLD] 투자 비용 -20%[NEWLINE][ICON_BULLET] [COLOR_NEGATIVE_TEXT]군사 유닛 [ICON_PRODUCTION] 생산 비용 -20%[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_MERCANTILE_FRIENDLY_BONUS', 			'[COLOR:240:240:165:255]황금의 도시 (상업적 우호적):[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_MERCANTILE_NEUTRAL_BONUS', 				'[COLOR:210:210:70:255]그림자 의회 (상업적 중립적):[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_MERCANTILE_HOSTILE_BONUS', 				'[COLOR:130:130:20:255]자유 도시 (상업적 적대적):[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_CULTURED_BONUS', 						'[COLOR:210:65:200:255]학습의 장 (문화적):[ENDCOLOR][NEWLINE][ICON_BULLET] 아카데미를 가지고 시작합니다.'  UNION ALL
SELECT 'TXT_KEY_CULTURED_FRIENDLY_BONUS', 				'[COLOR:240:180:235:255]열린 대학 (문화적 우호적):[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_CULTURED_NEUTRAL_BONUS', 				'[COLOR:210:90:195:255]후원자 (문화적 중립적):[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_CULTURED_HOSTILE_BONUS', 				'[COLOR:130:30:115:255]은둔 법원 (문화적 적대적):[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_RELIGIOUS_BONUS', 						'[COLOR:25:110:250:255]신앙의 중심 (종교적):[ENDCOLOR][NEWLINE][ICON_BULLET] 근처에 성지를 가지고 시작합니다. [NEWLINE][ICON_BULLET] [ICON_PEACE] 종교 압력 +33%[NEWLINE][ICON_BULLET] 자연 불가사의, 산, 산호섬에 +2 [ICON_GOLD] 골드, +2 [ICON_CULTURE] 문화, +2 [ICON_PEACE] 신앙[NEWLINE][ICON_BULLET] [COLOR_NEGATIVE_TEXT] [ICON_CULTURE_LOCAL] 국경 확장 점수 -5[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_RELIGIOUS_FRIENDLY_BONUS', 				'[COLOR:160:220:250:255]열린 정신 (종교적 우호적):[ENDCOLOR][NEWLINE][ICON_BULLET] 5%의 확률로 플레이어의 영토에 선교사가 나타납니다.[NEWLINE][ICON_BULLET] [ICON_PEACE] 개종 저항 -25%[NEWLINE][ICON_BULLET] [ICON_INTERNATIONAL_TRADE]교역로마다  +2 [ICON_CULTURE] 문화'  UNION ALL
SELECT 'TXT_KEY_RELIGIOUS_NEUTRAL_BONUS', 				'[COLOR:105:155:230:255]탁발 수도회 (종교적 중립적):[ENDCOLOR][NEWLINE][ICON_BULLET] [ICON_PEACE] 개종 저항 +10%[NEWLINE][ICON_BULLET] 이 도시국가 내 신자가 한 명 이상인 종교의 종류 하나당 [ICON_PRODUCTION] 생산 +5[NEWLINE][ICON_BULLET] 강 근처 타일에 [ICON_FOOD] 식량 +1, 호수에 [ICON_FOOD] 식량 +2'  UNION ALL
SELECT 'TXT_KEY_RELIGIOUS_HOSTILE_BONUS', 				'[COLOR:25:110:170:255]유일한 진리 (종교적 적대적):[ENDCOLOR][NEWLINE][ICON_BULLET] [ICON_PEACE] 개종 저항 +25%[NEWLINE][ICON_BULLET] [ICON_PEACE] 종교 압력 +25%[NEWLINE][ICON_BULLET] 유닛이 죽을 때 마다 [ICON_CULTURE] 문화 10'  UNION ALL
SELECT 'TXT_KEY_MILITARISTIC_BONUS', 					'[COLOR:245:40:40:255]요새 (군사적):[ENDCOLOR][NEWLINE][ICON_BULLET] 근처에 요새와 추가 전략자원을 가지고 시작합니다.[NEWLINE][ICON_BULLET] 도시국가의 고유 유닛을 생산할 수 있습니다.[NEWLINE][ICON_BULLET] 도시 국가와 동맹이라면 도시국가 안에서 유닛 업그레이드가 가능합니다.[NEWLINE][ICON_BULLET] 군사 유닛 [ICON_PRODUCTION] 생산시 생산력 +10%[NEWLINE][ICON_BULLET] [COLOR_NEGATIVE_TEXT][ICON_FOOD] 인구 성장 -33%[ENDCOLOR]'  UNION ALL
SELECT 'TXT_KEY_MILITARISTIC_FRIENDLY_BONUS', 			'[COLOR:255:180:180:255]용병 허브 (군사적 우호적):[ENDCOLOR][NEWLINE][ICON_BULLET] 우호적 플레이어에게 유닛을 5% 더 자주 선물합니다.[NEWLINE][ICON_BULLET] 도시국가에서 생산된 유닛의 경험치 +30'  UNION ALL
SELECT 'TXT_KEY_MILITARISTIC_NEUTRAL_BONUS', 			'[COLOR:245:90:90:255]고용된 군대 (군사적 중립적):[ENDCOLOR][NEWLINE][ICON_BULLET] [ICON_WAR] 글로벌 보급 한도 +25%[NEWLINE][ICON_BULLET] 도시국가에서 생산된 유닛이 전투로 얻는 경험치 +20%[NEWLINE][ICON_BULLET] 도시국가에서 생산된 유닛의 경험치 +10'  UNION ALL
SELECT 'TXT_KEY_MILITARISTIC_HOSTILE_BONUS', 			'[COLOR:170:10:10:255]숨은 용 (군사적 적대적):[ENDCOLOR][NEWLINE][ICON_BULLET] [ICON_WAR] 글로벌 보급 한도 +50%[NEWLINE][ICON_BULLET] 군사 유닛 [ICON_PRODUCTION] 생산시 생산력 +33%'  UNION ALL
-- main definitions
SELECT 'TXT_KEY_CITYSTATE_CLERMONT', '클레몬트' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CLERMONT_ADJ', '클레몬트의' UNION ALL
SELECT 'TXT_KEY_CIV5_CLERMONT_TEXT', '클레몬트는 제1차 십자군 원정의 시작점이었고, 기독교는 예루살렘을 무슬림의 지배로부터 해방시키려고 했습니다. 교황 우르바노 2세는 1095년 제2차 클레몬트 공의회에서 십자군을 모았습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_HONDURAS', '온두라스' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_HONDURAS_ADJ', '온두라스의' UNION ALL
SELECT 'TXT_KEY_CIV5_HONDURAS_TEXT', '온두라스는 16세기에 스페인이 점령하기 전에 몇몇 메소아메리카 문화의 고향이었습니다. 온두라스는 1821년에 독립했고 그 이후로 공화국이 되었습니다. 그러나 공화국은 그들의 정부가 외국인 투자자들로부터 바나나의 개발만을 지원받은 바나나 공화국의 모습으로 남아있습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AUCKLAND', '오클랜드' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AUCKLAND_ADJ', '오클랜드의' UNION ALL
SELECT 'TXT_KEY_CIV5_AUCKLAND_TEXT', '마오리족이 지금의 뉴질랜드 북부에 있는 지협에 정착했을 때, 그들은 비옥한 땅, 무성한 정글, 그리고 휴화산으로 가득한 주변 풍경을 발견했습니다. 지협 양쪽에 있는 자연 보호 항구는 풍부한 어업과 전쟁 카누의 기지를 제공했습니다. 정착민들은 그것을 ''타마키 마카오''라고 불렀는데, 대략 "백 명의 연인들이 찾는 소녀"로 번역됩니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ARMAGH', '아마' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ARMAGH_ADJ', '아마의' UNION ALL
SELECT 'TXT_KEY_CIV5_ARMAGH_TEXT', '아일랜드의 마을인 아마는 오랫동안 종교를 알고 있었습니다. 고대 이교도들의 예배 장소였던 것으로 생각되는 이곳은 5세기에 기독교 선교사 성 패트릭이 언덕 꼭대기에 석조 교회를 세우고 봉헌하면서 유명해졌습니다. 그 주변에 수도원이 생겼고, 그리고 나서 신학의 첨탑인 아일랜드 전역에 기독교를 전파하는 데 헌신한 마을이 생겼습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUSCAT', '무스카트' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUSCAT_ADJ', '무스카트의' UNION ALL
SELECT 'TXT_KEY_CIV5_MUSCAT_TEXT', '무스카트를 통해 흐르는 무역은 적어도 2천년 동안 그것의 생명선이었습니다. 알 하자르 산의 기슭에 둥지를 튼 프톨레마이오스는 이 곳을 1세기 초에 숨겨진 항구(''크립투스 포르투스'')라고 불렀습니다. 불행히도 이 도시는 잘 숨겨져 있지 않았습니다. 페르시아 만의 어귀에 위치한 이 도시의 주요 위치는 오랫동안 이곳을 정복하기 위한 매력적인 목표로 만들었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GRANADA', '그라나다' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GRANADA_ADJ', '그라나다의' UNION ALL
SELECT 'TXT_KEY_CIV5_GRANADA_TEXT', '8세기에 우마이야 칼리프는 이베리아 반도를 통해 퍼져나가 비시고딕 히스파니아를 빠르게 정복했습니다. 현재 스페인 남부에 있는 요새화된 정착지인 그라나다가 침공으로 휩쓸렸습니다. 15세기 후반에 이르러서는 가톨릭 군주들에게 항복함으로써 안달루시아의 레키스타는 막을 내리게 되었지만, 천년의 4분의 3 동안 그라나다는 무어인의 소유가 되었습니다.
시에라 네바다 산맥의 기슭에 위치한 그라나다는 낮은 평야에 위치해 있기 때문에 거의 방어할 수 없는 불운을 겪었습니다. 그곳의 무어 통치자들은 재빨리 이 사실을 깨닫고 그들의 권력을 마을을 내려다볼 수 있는 더 방어하기 쉬운 언덕으로 옮겼습니다. 그들의 계획 중 일부는 나중에 아름다운 알함브라로 개조될 알자르를 건설하는 것을 포함했습니다.
그라나다의 무어족 주인들은 수세기에 걸쳐 변화했습니다. 알모아 가문은 우마이야 왕조의 잔당을 이어받은 알모라비드 가문을 대체했습니다. 그 도시의 운명은 13세기에 가톨릭 왕국 카스티야 왕국과 동맹을 맺은 나스리드 왕조와 함께 그라나다 토후국으로 다시 바뀌었습니다. 사하라 이남 아프리카에 있는 무역 센터로의 직접 접근은 그라나다를 한동안 레콩키스타로부터 해방시켰습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NANMANDOL', '레루' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NANMANDOL_ADJ', '레루의' UNION ALL
SELECT 'TXT_KEY_CIV5_NANMANDOL_TEXT', '레루는 선사 시대와 역사적인 주요 고고학 유적지입니다. 그 유적들은 14세기와 15세기 경에 절정에 달했던 문명의 유적들로, 19세기 초 유럽인들의 접촉 당시에도 여전히 그 요소들을 볼 수 있습니다. 레루의 통치자들은 점차적으로 코스라에 섬을 정복하고 통일했습니다. 수도 레루에서, 그들은 고고학자들이 통가나 하와이의 왕국들과 비슷하다고 여기는 군주제로 그 섬을 통치했습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GWYNEDD', '귀네드' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GWYNEDD_ADJ', '귀네드의' UNION ALL
SELECT 'TXT_KEY_CIV5_GWYNEDD_TEXT', '귀네드는 로마 시대 말기부터 독립적인 웨일스 왕국이었습니다. 13세기에 영국에 의해 정복되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUISCA', '무이스카' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUISCA_ADJ', '무이스카의' UNION ALL
SELECT 'TXT_KEY_CIV5_MUISCA_TEXT', '무이스카는 16세기까지 서쪽의 판체, 북서쪽의 무조, 북쪽의 과네, 북동쪽의 라체, 동쪽의 아카과아, 그리고 남쪽의 수타가오와 같은 안데스 문화의 고향이었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LACONIA', '라코니아' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LACONIA_ADJ', '라코니아의' UNION ALL
SELECT 'TXT_KEY_CIV5_LACONIA_TEXT', '도시 국가의 수도인 스파르타의 한 지역으로 여겨지는 라코니아는 펠로폰네소스 지역에서 지배권을 다투는 가장 강력한 지역 세력 중 하나입니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CHEVAK', '셰바크' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CHEVAK_ADJ', '셰바크의' UNION ALL
SELECT 'TXT_KEY_CIV5_CHEVAK_TEXT', '알래스카의 체박족이 사는 지역입니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SANTO_DOMINGO', '산토도밍고' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SANTO_DOMINGO_ADJ', '산토도밍고의' UNION ALL
SELECT 'TXT_KEY_CIV5_SANTO_DOMINGO_TEXT', '산토도밍고는 아메리카 대륙에서 가장 오래된 유럽 도시가 되었습니다. 원래 이름은 라 누에바 이사벨라였고, 1495년에 성 도미니크를 기념하기 위해 산토 도밍고로 이름이 바뀌었습니다. 산토 도밍고는 도시가 커지고 번창하면서 "캐리비안의 관문"으로 알려지게 되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MANAGUA', '마나과' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MANAGUA_ADJ', '마나과의' UNION ALL
SELECT 'TXT_KEY_CIV5_MANAGUA_TEXT', '메스티소와 스페인 상류층 백인들로 구성된 마나과로, 이 도시는 어촌 마을에서 번영하는 스페인 도시가 되었고, 현재 가장 잘 알려진 중앙아메리카의 발전된 도시가 되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO', '오덴소' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO_ADJ', '오덴소의' UNION ALL
SELECT 'TXT_KEY_CIV5_ODENSO_TEXT', '문자 그대로 오딘의 섬으로 번역된 이 섬은 핀란드 왕국에 의해 북유럽 신화의 신 오딘을 인정받아 명명되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_YANGCHENG', '양청' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_YANGCHENG_ADJ', '양청의' UNION ALL
SELECT 'TXT_KEY_CIV5_YANGCHENG_TEXT', '하 왕조의 첫 번째 수도로 여겨지는, 그것은 음강 위에 지어졌고 그들의 왕조가 멸망할 때까지 유지되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_PHANOTEUS', '파노테우스' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_PHANOTEUS_ADJ', '파노테우스의' UNION ALL
SELECT 'TXT_KEY_CIV5_PHANOTEUS_TEXT', '파노테우스는 매우 오래된 마을로, 원래 플라레야에가 거주했습니다. 프로메테소스가 이곳에서 인류를 만들었다고 여겨집니다. 그것은 크세르크세스 휘하의 페르시아인, 필리포스 2세 휘하의 마케도니아인, 폼페이 대왕 휘하의 로마인들에 의해 시간이 지남에 따라 파괴되고 파괴될 때까지 유지되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DOUALA', '두알라' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DOUALA_ADJ', '두알라의' UNION ALL
SELECT 'TXT_KEY_CIV5_DOUALA_TEXT', '두알라는 카메룬에서 가장 큰 도시이자 이 지역에서 가장 강력한 경제 성장을 한 도시입니다. 1960년 카메룬의 독립은 두알라의 경제적 중요성이 발전과 번영에 결정적이 되면서 두알라의 강력한 급속한 경제 성장을 낳았습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AMBRACIA', '암브라시아' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AMBRACIA_ADJ', '암브라시아의' UNION ALL
SELECT 'TXT_KEY_CIV5_AMBRACIA_TEXT', '암브레시아는 고대 그리스 역사에서 마케도니아 왕 카산드로스가 에피로스의 왕 피로스에게 선물한 도시입니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DJIBOUTI', '지부티' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DJIBOUTI_ADJ', '지부티의' UNION ALL
SELECT 'TXT_KEY_CIV5_DJIBOUTI_TEXT', '지부티는 프랑스의 지배하에 오복으로 정착하기 전까지 원래 무인도 해안 지역이었습니다. 그것은 프랑스로부터 독립한 후에 이름이 바뀌었고 또한 각각의 이름 있는 나라의 수도가 되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DODOMA', '도도마' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DODOMA_ADJ', '도도마의' UNION ALL
SELECT 'TXT_KEY_CIV5_DODOMA_TEXT', '도도마는 인구 규모가 작고 탄자니아 자체의 갈림길, 저렴한 개발비 가능성이 실현되면서 탄자니아의 수도로 선정된 작은 무역도시로 구성된 지역입니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_FAYA', '파야' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_FAYA_ADJ', '파야의' UNION ALL
SELECT 'TXT_KEY_CIV5_FAYA_TEXT', '파야는 현대 차드 북부의 많은 인구를 자랑하는 열대의 더운 지역입니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_KIGALI', '키갈리' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_KIGALI_ADJ', '키갈리의' UNION ALL
SELECT 'TXT_KEY_CIV5_KIGALI_TEXT', '키갈리는 14세기에 르완다 왕국에 의해 처음 개발되고 있는 르완다의 수도이며, 근대에 역사적인 수도가 되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LEVUKA', '나이로비' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LEVUKA_ADJ', '나이로비의' UNION ALL
SELECT 'TXT_KEY_CIV5_LEVUKA_TEXT', 'TODO' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_QUELIMANE', '켈리마네' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_QUELIMANE_ADJ', '켈리마네의' UNION ALL
SELECT 'TXT_KEY_CIV5_QUELIMANE_TEXT', '켈리마네는 홍수에 극도로 취약한 지역입니다. 스와힐리 교역소로 설립된 이곳은 번영하는 항구로 발전했습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SIERRA_LEONE', '시에라리온' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SIERRA_LEONE_ADJ', '시에라리온의' UNION ALL
SELECT 'TXT_KEY_CIV5_SIERRA_LEONE_TEXT', '시에라리온은 사막과 습지의 다양한 지역입니다. 영국의 지배하에 세워진 이 나라는 독립성을 부여받았고 이웃나라에 비해 종교적 관용을 자랑했습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SURREY', '셔리' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SURREY_ADJ', '셔리의' UNION ALL
SELECT 'TXT_KEY_CIV5_SURREY_TEXT', '서리는 영국 남동부에 있는 군입니다. 비행장으로서의 첫 번째 용도로 알려진, 그 카운티는 비행기와 항공기의 생산에 있어 중요시 되었습니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_TAIWAN', 						'타이페이' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_TAIWAN_ADJ', 					'타이페이의' UNION ALL
SELECT 'TXT_KEY_CIV5_TAIWAN_TEXT', 						'타이베이는 중화민국의 수도이며, 대만의 문화, 정치, 경제의 중심입니다. 국민당의 중국 망명 정부가 수립되기 전에, 타이베이는 중국, 일본, 필리핀 사이의 무역로를 따라 위치한 작은 지방 수도였습니다. 주변 지역의 대부분은 한족에 의한 중국 본토의 지배와 구별되는 풍부한 문화적 구조를 형성하면서, 몇몇 타이완 원주민들이 계속해서 거주합니다.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_OC_EO', 						'옥에오' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_OC_EO_ADJ', 					'옥에오의' UNION ALL
SELECT 'TXT_KEY_CIV5_OC_EO_TEXT', 						'TODO' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_THIMPHU', 					'팀푸' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_THIMPHU_ADJ', 				'팀푸의' UNION ALL
SELECT 'TXT_KEY_CIV5_THIMPHU_TEXT', 					'TODO' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ANDORRA', 					'안도라' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ANDORRA_ADJ', 				'안도라의' UNION ALL
SELECT 'TXT_KEY_CIV5_ANDORRA_TEXT', 					'TODO' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CANOSSA', 					'카노사' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CANOSSA_ADJ', 				'카노사의' UNION ALL
SELECT 'TXT_KEY_CIV5_CANOSSA_TEXT', 					'TODO' UNION ALL
-- abilities
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ALMATY', '[COLOR_MAGENTA]알마투:[ENDCOLOR] [ICON_TRADE]도시 연결에서 [ICON_RESEARCH]과학 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTANANARIVO', '[COLOR_MAGENTA]해적 피난항:[ENDCOLOR] 처치한 적의 전투력 100%만큼 [ICON_GOLD]골드 제공[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTWERP', '[COLOR_MAGENTA]이코노믹스 프로망스:[ENDCOLOR] 상인 전문가의 +2 [ICON_GOLD]골드[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BELGRADE', '[COLOR_MAGENTA]백색 요새:[ENDCOLOR] 공성 유닛 체력 +25[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BOGOTA', '[COLOR_MAGENTA]독립 연합:[ENDCOLOR] 점령한 도시가 [ICON_CULTURE]문화 20 제공, 해방시킨 도시는 시대 및 도시 수에 따라 [ICON_CULTURE]문화 15~45 제공[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BRATISLAVA', '[COLOR_MAGENTA]슬라브 문화의 심장:[ENDCOLOR] 길드의 [ICON_CULTURE]문화 +2 [ICON_TOURISM]관광 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BRUSSELS', '[COLOR_MAGENTA]습지의 고향:[ENDCOLOR] 습지 타일의 [ICON_CULTURE]문화 +1, [COLOR_POSITIVE_TEXT]습지 복원 시설[ENDCOLOR]건설 가능[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BUCHAREST', '[COLOR_MAGENTA]동방의 파리:[ENDCOLOR] 걸작에서 오는 [ICON_CULTURE]문화 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BUDAPEST', '[COLOR_MAGENTA]다뉴브의 진주:[ENDCOLOR] [ICON_RES_HORSE]말 +5 제공[NEWLINE][NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BUENOS_AIRES', '[COLOR_MAGENTA]민중의 소리:[ENDCOLOR] 보너스 자원의 [ICON_CULTURE]문화 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BYBLOS', '[COLOR_MAGENTA]레바논 삼나무:[ENDCOLOR] 어선, 호수, 오아시스 타일의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CAHOKIA', '[COLOR_MAGENTA]카호키아 유적:[ENDCOLOR] [COLOR_POSITIVE_TEXT]카호키아 마운드[ENDCOLOR] 시설 건설 가능, 마운드의 [ICON_GOLD]골드 +1 [ICON_PEACE]신앙 +1, 마을 인접 시 [ICON_GOLD]골드 +1 [ICON_PEACE]신앙 +1, 인접 도시에 [ICON_GOLDEN_AGE]황금기 점수 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CAPE_TOWN', '[COLOR_MAGENTA]희망의 봉우리:[ENDCOLOR] [ICON_INTERNATIONAL_TRADE]교역로 범위 +10%, [ICON_INTERNATIONAL_TRADE]교역로가 끝나는 도시의 [ICON_CITIZEN]시민 수에 따라 [ICON_GOLD]골드 20~40 제공[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_COLOMBO', '[COLOR_MAGENTA]쿠베라:[ENDCOLOR] 정글, 숲 타일의 [ICON_GOLD]골드 +2, 제재소 및 벌목장 건설 시 [ICON_GOLD]골드 [COLOR_NEGATIVE_TEXT]-2[ENDCOLOR][NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_FLORENCE', '[COLOR_MAGENTA]르네상스의 요람:[ENDCOLOR] 채석장의 [ICON_CULTURE]문화 +1, 예술가 전문가의 [ICON_GOLDEN_AGE]황금기 점수 +2[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GENEVA', '[COLOR_MAGENTA]교회론:[ENDCOLOR] 도시의 [ICON_CITIZEN]시민 5명당 [ICON_PEACE]신앙 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GENOA', '[COLOR_MAGENTA]라 수페르바:[ENDCOLOR] [ICON_GREAT_PEOPLE]위인이 출현할 때 [ICON_GOLD]골드 50, [ICON_GOLDEN_AGE]황금기 점수 15[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HANOI', '[COLOR_MAGENTA]애국심:[ENDCOLOR] 우호 영토 내 [ICON_STRENGTH]전투력 +10%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HONG_KONG', '[COLOR_MAGENTA]국가 번영:[ENDCOLOR] 도시의 [ICON_CITIZEN]시민 6명당 [ICON_GOLD]골드 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_IFE', '[COLOR_MAGENTA]요루바:[ENDCOLOR] 도시의 국경이 확장될 때 [ICON_PEACE]신앙 +3, 성소의 국경 확장 점수 +2[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_JERUSALEM', '[COLOR_MAGENTA]성스러운 도시:[ENDCOLOR] 동맹인 문명의 수도와 같은 대중 종교를 채택, 예루살렘의 대한 "영향권" 제공, 성도와 같은 종교 압력을 가짐[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KABUL', '[COLOR_MAGENTA]지상 낙원:[ENDCOLOR] 도시 주변 산 타일 1개마다 [ICON_CULTURE]문화 +0.66[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KATHMANDU', '[COLOR_MAGENTA]더 마운틴:[ENDCOLOR] 도시 주변 산 타일 1개마다 [ICON_PEACE]신앙 +0.66[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KIEV', '[COLOR_MAGENTA]오래된 이야기:[ENDCOLOR] [COLOR_POSITIVE_TEXT]빌리나[ENDCOLOR] 건설 가능 (걸작 음악 슬롯 +1)[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KUALA_LUMPUR', '[COLOR_MAGENTA]진흙투성이 강:[ENDCOLOR] 우물의 [ICON_CULTURE]문화 +5%, 물레방앗간의 [ICON_CULTURE]문화 +2[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KYZYL', '[COLOR_MAGENTA]아시아의 중심:[ENDCOLOR] 궁전, 기념비의 [ICON_TOURISM]관광 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LA_VENTA', '[COLOR_MAGENTA]의례적 창조물:[ENDCOLOR] 위인 시설에 [ICON_PEACE]신앙 +1, 성소의 [ICON_PEACE]신앙 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LHASA', '[COLOR_MAGENTA]신의 정원:[ENDCOLOR] [ICON_GREAT_PEOPLE]위인이 출현할 때 [ICON_PEACE]신앙 25, [COLOR_YELLOW]포탈라 궁[ENDCOLOR] 불가사의 건설 가능[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MALACCA', '[COLOR_MAGENTA]해협 식민지:[ENDCOLOR] 사치 자원의 +1 [ICON_GOLD]골드[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MANILA', '[COLOR_MAGENTA]동양의 진주:[ENDCOLOR] [ICON_INTERNATIONAL_TRADE]교역로가 끝나는 도시의 [ICON_CITIZEN]시민 수에 따라 [ICON_FOOD]식량 [ICON_PRODUCTION]생산 1~15 제공[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MBANZA_KONGO', '[COLOR_MAGENTA]마니콩고의 영광:[ENDCOLOR] 숲, 정글, 습지, 범람원 타일에서 전투 시 [ICON_STRENGTH]전투력 보너스 +15%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MELBOURNE', '[COLOR_MAGENTA]골드 러쉬:[ENDCOLOR] 광산, 위인 시설의 [ICON_GOLD]골드 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MILAN', '[COLOR_MAGENTA]비스콘티 특사:[ENDCOLOR] [COLOR_POSITIVE_TEXT]비스콘티 저택[ENDCOLOR] 건설 가능 (걸작 예술품 슬롯 +1)[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MOGADISHU', '[COLOR_MAGENTA]떠오르는 해양 도시:[ENDCOLOR] 범람원, 해양 타일의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MOMBASA', '[COLOR_MAGENTA]개발도상 연합:[ENDCOLOR] 모든 보너스 자원의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MONACO', '[COLOR_MAGENTA]금융 천국:[ENDCOLOR] 시장, 은행의 [ICON_CULTURE]문화 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ORMUS', '[COLOR_MAGENTA]보석 반지:[ENDCOLOR] 모든 사치 자원의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PANAMA_CITY', '[COLOR_MAGENTA]파나마 운하:[ENDCOLOR] 요새, 성채, 부교의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PRAGUE', '[COLOR_MAGENTA]프라하 성:[ENDCOLOR] 성벽, 성의 [ICON_CULTURE]문화 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_QUEBEC_CITY', '[COLOR_MAGENTA]일백조합인상사:[ENDCOLOR] 야영지, 제재소, 벌목장의 [ICON_GOLD]골드 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_RAGUSA', '[COLOR_MAGENTA]해양 종속국:[ENDCOLOR] 우호 및 동맹인 도시 국가가 모든 도시에 [ICON_FOOD]식량 +1 제공, 대사관 시설의 [ICON_FOOD]식량 +1 [NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_RIGA', '[COLOR_MAGENTA]라트비아 상업중심지:[ENDCOLOR] 도시의 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]+3%[ENDCOLOR][NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SAMARKAND', '[COLOR_MAGENTA]소그드:[ENDCOLOR] 국제 [ICON_INTERNATIONAL_TRADE]교역로의 [ICON_GOLD]골드 +4[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SIDON', '[COLOR_MAGENTA]이웃집 불청객:[ENDCOLOR] 동맹일 때 시돈에 대한 "영향권" 제공, 적 영토 내 군사 유닛의 체력이 매 턴 +5 회복[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SINGAPORE', '[COLOR_MAGENTA]발전된 부:[ENDCOLOR] 모든 외교 유닛에 [COLOR_PURPLE_PLAYER]귀족[ENDCOLOR] 승급 부여[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SOFIA', '[COLOR_MAGENTA]세르디카:[ENDCOLOR] 위대한 장군 및 위대한 제독이 인접 유닛에 추가 [ICON_STRENGTH]전투력 보너스 +5%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SYDNEY', '[COLOR_MAGENTA]자본 인프라:[ENDCOLOR] [ICON_HAPPINESS_1]국왕 경축일에 [ICON_FOOD]식량 +5%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_TYRE', '[COLOR_MAGENTA]고대의 유적:[ENDCOLOR] 걸작, 랜드마크 시설의 [ICON_GOLD]골드 +2[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_UR', '[COLOR_MAGENTA]문명의 요람:[ENDCOLOR] [ICON_TRADE]도시 연결에서 [ICON_FOOD]식량 +2[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VALLETTA', '[COLOR_MAGENTA]그랜드 하버:[ENDCOLOR] [COLOR_POSITIVE_TEXT]그랜드 하버[ENDCOLOR] 건설 가능[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VANCOUVER', '[COLOR_MAGENTA]터미널 시티:[ENDCOLOR] 마을, 위인 시설의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VATICAN_CITY', '[COLOR_MAGENTA]절대 믿음:[ENDCOLOR] [ICON_PEACE]신앙 구매 비용 -10%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VILNIUS', '[COLOR_MAGENTA]북쪽의 아테네:[ENDCOLOR] [COLOR_POSITIVE_TEXT]여명의 문[ENDCOLOR] 건설 가능 (걸작 문학 슬롯 +1)[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_WELLINGTON', '[COLOR_MAGENTA]타라의 위대한 항구:[ENDCOLOR] 전략 자원의 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_WITTENBERG', '[COLOR_MAGENTA]종교 개혁의 탄생:[ENDCOLOR] 모든 도시의 종교적 분쟁의 오는 [ICON_HAPPINESS_3]불행 -5%, 공무원, 근로자의 [ICON_PEACE]신앙 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_YEREVAN', '[COLOR_MAGENTA]손자병법:[ENDCOLOR] 처치한 적의 전투력 50%만큼 [ICON_CULTURE]문화 제공[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ZANZIBAR', '[COLOR_MAGENTA]향신료의 섬:[ENDCOLOR] 보너스, 전략 자원의 [ICON_GOLD]골드 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ZURICH', '[COLOR_MAGENTA]금융 박람회:[ENDCOLOR] 화폐 주조소의 [ICON_GOLD]골드 +2%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT', '[COLOR_MAGENTA]성전의 열의:[ENDCOLOR] 새로 훈련된 근접 및 화약 유닛에 첫 전투에 따라 10턴간 무작위 승급 부여. 근접 유닛 전투 경험치 +33%.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HONDURAS', '[COLOR_MAGENTA]바나나 공화국:[ENDCOLOR] 도시 국가에서 제공하는 자원도 글로벌 독점에 포함.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_AUCKLAND', '[COLOR_MAGENTA]타마키 마카우라우:[ENDCOLOR] 해안 도시의 [ICON_FOOD]식량 +3.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ARMAGH', '[COLOR_MAGENTA]성도 후원자:[ENDCOLOR] 신앙으로 위대한 아일랜드 성인 구매 가능 (대중 종교 필요).[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MUSCAT', '[COLOR_MAGENTA]은둔의 항구:[ENDCOLOR]등대, 항만, 항구, 부두의 [ICON_GOLD]골드 +1.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GRANADA', '[COLOR_MAGENTA]알카자르:[ENDCOLOR]요새, 성채의 [ICON_CULTURE]문화 +1.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_NANMANDOL', '[COLOR_MAGENTA]천상의 보초:[ENDCOLOR] 해양 타일의 [ICON_CULTURE]문화 +1.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GWYNEDD', '[COLOR_MAGENTA]허우엘 법률:[ENDCOLOR] [ICON_GOLDEN_AGE]황금기동안 [ICON_CULTURE]문화 +10%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MUISCA', '[COLOR_MAGENTA]황금 도시:[ENDCOLOR] [ICON_CAPITAL]수도의 [ICON_CITIZEN]시민 2명당 [ICON_GOLD]골드 +1[NEWLINE][ICON_BULLET]제국 전역 [ICON_CITIZEN]시민 30명당 [ICON_GOLD]골드 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA', '[COLOR_MAGENTA]스파르타의 규율:[ENDCOLOR] 우호 유닛 인접 시 [ICON_STRENGTH]전투력 보너스 +15%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CHEVAK', '[COLOR_MAGENTA]알래스카의 바람:[ENDCOLOR] 툰드라 타일 4개당 [ICON_FOOD]식량 +1[NEWLINE][ICON_BULLET]설원 타일 3개당 [ICON_FOOD]식량 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SANTO_DOMINGO', '[COLOR_MAGENTA]카리브해의 관문:[ENDCOLOR] 글로벌 독점에서 오는 행복 및 산출량의 합 +3[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MANAGUA', '[COLOR_MAGENTA]빅맨의 도시:[ENDCOLOR] 글로벌 독점에서 오는 황금기의 길이 및 산출량의 합 +7%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO', '[COLOR_MAGENTA]사냥의 군주:[ENDCOLOR] 군사 유닛의 시야 +1[NEWLINE][ICON_BULLET]중립 지역에서 매 턴 체력 회복 +5[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_YANGCHENG', '[COLOR_MAGENTA]십이간지:[ENDCOLOR] 동물 자원에 [ICON_PEACE]신앙 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PHANOTEUS', '[COLOR_MAGENTA]프로메테우스의 선물:[ENDCOLOR] 도시 국가 부정 선거 및 쿠데타 확률 +25%[NEWLINE][ICON_BULLET]적 스파이 포획 가능성 +25%[NEWLINE][ICON_BULLET]스파이가 걸작 및 기술을 훔칠 확률 +25%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DOUALA', '[COLOR_MAGENTA]호텔 아프리카:[ENDCOLOR] 추가 [ICON_INTERNATIONAL_TRADE]교역로 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_AMBRACIA', '[COLOR_MAGENTA]피로스의 용병:[ENDCOLOR] 지상 주둔군이 [ICON_PRODUCTION]생산 5% 제공, 도시 국가의 군사 유닛 선물 속도 +50%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DJIBOUTI', '[COLOR_MAGENTA]타 넷제루:[ENDCOLOR] 모든 도시의 빈곤에서 오는 [ICON_HAPPINESS_3]불행 -5%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DODOMA', '[COLOR_MAGENTA]황야의 항해:[ENDCOLOR] 해상 유닛 [ICON_STRENGTH]전투력 보너스 +5%, 해상 유닛 [ICON_MOVES]행동력 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_FAYA', '[COLOR_MAGENTA]전쟁의 성과:[ENDCOLOR] 처치한 적 전투력의 50%만큼 [ICON_RESEARCH]과학 획득[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LEVUKA', '[COLOR_MAGENTA]바우 파괴자:[ENDCOLOR] 야만인을 처치하거나, 야만인 캠프를 파괴하거나 적 도시를 점령하면 [ICON_FOOD] 식량을 얻습니다. 정복한 도시마다 +1 [ICON_GREAT_GENERAL] 위대한 장군 점수를 얻습니다.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_NAIROBI', '[COLOR_MAGENTA]함무라비:[ENDCOLOR] 모든 도시의 [ICON_HAPPINESS_3]곤경에서 오는 불행 -5%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_QUELIMANE', '[COLOR_MAGENTA]좋은 징조의 강:[ENDCOLOR] 강 타일에 [ICON_GOLDEN_AGE]황금기 점수 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SIERRA_LEONE', '[COLOR_MAGENTA]자유의 왕국:[ENDCOLOR] 모든 도시의 무료에서 오는 [ICON_HAPPINESS_3]불행 -5%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SURREY', '[COLOR_MAGENTA]장엄한 비행:[ENDCOLOR] 해상 및 지상 유닛 대항 시 전투기, 폭격기의 [ICON_STRENGTH]전투력 보너스 +10%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_TAIWAN', 				'[COLOR_MAGENTA]대만의 기적:[ENDCOLOR] 연구 협정의  [ICON_RESEARCH]과학 +5%. [ICON_RESEARCH]과학의 2%를 [ICON_FOOD] 식량으로 전환.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_OC_EO', 				'[COLOR_MAGENTA]위대한 글래스 강의 군주들:[ENDCOLOR] 해안 도시의 [ICON_INTERNATIONAL_TRADE] 교역로에서 [ICON_CULTURE_LOCAL] 영토 확장 점수 +1, [ICON_HAPPINESS_1] 제국 행복 +1 [NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_THIMPHU', 			'[COLOR_MAGENTA]전룡의 왕국:[ENDCOLOR] 언덕 위 도시에서 +3 [ICON_CULTURE] 문화[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ANDORRA', 			'[COLOR_MAGENTA]피레네 영주:[ENDCOLOR] 일할 수 있는 범위의 산마다 +1 [ICON_TOURISM] 관광. 산 근처 도시의 [ICON_HAPPINESS_3] 무료 -10%[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CANOSSA', 			'[COLOR_MAGENTA]경건한 마음속의 열렬한 불꽃:[ENDCOLOR] 공무원 전문가에 신앙 +1. 사원이 있는 도시에 위대한 외교관 포인트 +1[NEWLINE]' UNION ALL
-- promotions
SELECT 'TXT_KEY_PROMOTION_ANTANANARIVO', 				'해적 피난항' UNION ALL
SELECT 'TXT_KEY_PROMOTION_ANTANANARIVO_HELP', 			'처치한 적의 [ICON_STRENGTH]전투력 100%만큼 [ICON_GOLD] 골드 제공' UNION ALL
SELECT 'TXT_KEY_PROMOTION_BELGRADE', 					'백색 요새' UNION ALL
SELECT 'TXT_KEY_PROMOTION_BELGRADE_HELP', 				'체력 +25' UNION ALL
SELECT 'TXT_KEY_PROMOTION_HANOI', 						'애국심' UNION ALL
SELECT 'TXT_KEY_PROMOTION_HANOI_HELP', 					'우호 영토 내 [ICON_STRENGTH]전투력 +10%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_MBANZA_KONGO', 				'마니콩고의 영광' UNION ALL
SELECT 'TXT_KEY_PROMOTION_MBANZA_KONGO_HELP', 			'숲, 정글, 습지, 범람원 타일에서 전투 시 [ICON_STRENGTH]전투력 보너스 +15%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_SIDON', 						'이웃집 불청객' UNION ALL
SELECT 'TXT_KEY_PROMOTION_SIDON_HELP', 					'적 영토 내 군사 유닛의 체력이 매 턴 +5 회복' UNION ALL
SELECT 'TXT_KEY_PROMOTION_YEREVAN', 					'손자병법' UNION ALL
SELECT 'TXT_KEY_PROMOTION_YEREVAN_HELP', 				'처치한 적의 [ICON_STRENGTH]전투력 50%만큼 [ICON_CULTURE] 문화 제공' UNION ALL
SELECT 'TXT_KEY_PROMOTION_LACONIA', 					'스파르타의 규율' UNION ALL
SELECT 'TXT_KEY_PROMOTION_LACONIA_HELP', 				'우호 유닛 인접 시 [ICON_STRENGTH]전투력 보너스 +15%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_ODENSO', 						'사냥의 군주' UNION ALL
SELECT 'TXT_KEY_PROMOTION_ODENSO_HELP', 				' 군사 유닛의 시야 +1[NEWLINE][ICON_BULLET]중립 지역에서 매 턴 체력 회복 +5[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_PROMOTION_AMBRACIA', 					'피로스의 용병' UNION ALL
SELECT 'TXT_KEY_PROMOTION_AMBRACIA_HELP', 				'지상 주둔군이 [ICON_PRODUCTION]생산 5% 제공' UNION ALL
SELECT 'TXT_KEY_PROMOTION_DODOMA', 						'황야의 항해' UNION ALL
SELECT 'TXT_KEY_PROMOTION_DODOMA_HELP', 				'[ICON_STRENGTH]전투력 보너스 +5%, [ICON_MOVES]행동력 +1[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_PROMOTION_FAYA', 						'전쟁의 성과' UNION ALL
SELECT 'TXT_KEY_PROMOTION_FAYA_HELP', 					'처치한 적의 [ICON_STRENGTH]전투력 50%만큼 [ICON_RESEARCH] 과학 제공' UNION ALL
SELECT 'TXT_KEY_PROMOTION_SURREY', 						'장엄한 비행' UNION ALL
SELECT 'TXT_KEY_PROMOTION_SURREY_HELP', 				'해상 및 지상 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 +10%.' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT', 					'심판' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT_HELP', 				'전투 경험치 +15%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT1', 					'클레몬트의 축복' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT1_HELP', 				'첫 전투에 따라 임시로 무작위 [ICON_STRENGTH]전투력 보너스 제공' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT2', 					'서두름' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT2_HELP', 				'[ICON_MOVES]이동력 +2. 공격 후 이동 가능' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT3', 					'대동단결' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT3_HELP', 				'우호 유닛 인접 시 [ICON_STRENGTH]전투력 보너스 +20%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT4', 					'충전' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT4_HELP', 				'공격 시 [ICON_STRENGTH]전투력 보너스 +10%. 요새화한 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 +15%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT5', 					'보강' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT5_HELP', 				'방어 시 [ICON_STRENGTH]전투력 보너스 +15%. 공격 후 회복 가능' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT6', 					'하느님께 영광을' UNION ALL
SELECT 'TXT_KEY_PROMOTION_CLERMONT6_HELP', 				'위대한 장군처럼 인접한 유닛에 [ICON_STRENGTH]전투력 보너스 제공. 이 유닛과 인접한 타일의 모든 유닛은 매 턴 체력 회복 +5' UNION ALL
SELECT 'TXT_KEY_PROMOTION_MILITARISTIC_NEUTRAL', 		'고용된 군대' UNION ALL
SELECT 'TXT_KEY_PROMOTION_MILITARISTIC_NEUTRAL_HELP', 	'전투 경험치 +20%' UNION ALL
SELECT 'TXT_KEY_PROMOTION_LEVUKA', 						'바우 파괴자' UNION ALL
SELECT 'TXT_KEY_PROMOTION_LEVUKA_HELP', 				'야만인 처치 시 [ICON_FOOD] 식량 획득' UNION ALL
-- improvements
SELECT 'TXT_KEY_BUILD_MARSH', '습지 복원 시설을 건설합니다.'  UNION ALL
SELECT 'TXT_KEY_BUILD_MARSH_HELP', '해당 타일을 습지로 바꾸고 습지 복원 시설을 건설할 수 있습니다. [COLOR_POSITIVE_TEXT]브뤼셀[ENDCOLOR]과 동맹 관계를 유지해야 건설할 수 있습니다.'  UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MARSH', '습지 복원 시설' UNION ALL
SELECT 'TXT_KEY_CIV5_IMPROVEMENTS_MARSH', '어떤 지형에서도 습지를 복원하려면 물이 자연스럽게 흐르도록 하십시오. 만약 물이 얼지 않는다면 설원에도 효과가 있습니다!' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MARSH_HELP', '브뤼셀과 동맹인 문명만이 습지 복원 사업을 계속할 수 있습니다.' UNION ALL
SELECT 'TXT_KEY_BUILD_MOUND', '카호키아 마운드를 건설합니다.'  UNION ALL
SELECT 'TXT_KEY_BUILD_MOUND_HELP', '도심에 인접해 건설하면 [ICON_GOLDEN_AGE]황금기 점수가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 마을에 인접하여 건설하면 [ICON_GOLD]골드 및 [ICON_PEACE] 신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. 동맹 관계가 유지되지 않으면 보너스를 잃습니다. [COLOR_POSITIVE_TEXT]카호키아[ENDCOLOR]와 동맹 관계를 유지해야 건설할 수 있습니다.' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MOUND', '카호키아 마운드' UNION ALL
SELECT 'TXT_KEY_CIV5_IMPROVEMENTS_MOUND', '운반된 흙과 점토로 지어진 피라미드입니다.' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MOUND_HELP', '카호키아와 동맹인 문명만이 이 건축물의 아름다움을 누릴 수 있습니다.' UNION ALL
-- dummy buildings
SELECT 'TXT_KEY_BUILDING_MARITIME', 					'건축가' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_HELP', 				'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_FRIENDLY', 			'수확자' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_FRIENDLY_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_NEUTRAL', 			'보안 창고' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_NEUTRAL_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_HOSTILE', 			'탐욕스런 수집가' UNION ALL
SELECT 'TXT_KEY_BUILDING_MARITIME_HOSTILE_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE', 					'무역 센터' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_HELP', 				'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_FRIENDLY', 			'황금의 도시' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_FRIENDLY_HELP', 	'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_NEUTRAL', 			'그림자 의회' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_NEUTRAL_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_HOSTILE', 			'자유 도시' UNION ALL
SELECT 'TXT_KEY_BUILDING_MERCANTILE_HOSTILE_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED', 					'학습의 장' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_HELP', 				'' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_FRIENDLY', 			'열린 대학' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_FRIENDLY_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_NEUTRAL', 			'후원자' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_NEUTRAL_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_HOSTILE', 			'은둔 법원' UNION ALL
SELECT 'TXT_KEY_BUILDING_CULTURED_HOSTILE_HELP', 		'' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS', 					'신앙의 중심' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_HELP', 				'종교적 압력 +33%,  [ICON_CULTURE_LOCAL] 국경 확장 점수 -10.' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_FRIENDLY', 			'열린 정신' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_FRIENDLY_HELP', 		'[ICON_PEACE] 개종 저항 -25%. 우호적인 플레이어의 영토에 5% 확률로 선교사가 나타날 수 있음.' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_NEUTRAL', 			'탁발 수도회' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_NEUTRAL_HELP', 		' 이 도시국가 내 신자가 한 명 이상인 종교의 종류 하나당 [ICON_PRODUCTION] 생산력 +3.' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_HOSTILE', 			'유일한 진리' UNION ALL
SELECT 'TXT_KEY_BUILDING_RELIGIOUS_HOSTILE_HELP', 		'[ICON_PEACE] 개종 저항, [ICON_PEACE] 종교 압력 +25%.' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC', 				'요새' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_HELP', 			'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_FRIENDLY', 		'용병 허브' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_FRIENDLY_HELP', 	'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_NEUTRAL', 		'고용된 군대' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_NEUTRAL_HELP', 	'' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_HOSTILE', 		'숨은 용' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILITARISTIC_HOSTILE_HELP', 	'' UNION ALL
SELECT 'TXT_KEY_BUILDING_BYBLOS', '레바논 삼나무 무역 회사' UNION ALL
SELECT 'TXT_KEY_BUILDING_BYBLOS_HELP', '오아시스, 호수, 어선의 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_CAPE_TOWN', '희망봉' UNION ALL
SELECT 'TXT_KEY_BUILDING_CAPE_TOWN_HELP', '[ICON_INTERNATIONAL_TRADE]교역로 범위가 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다. [ICON_INTERNATIONAL_TRADE]교역로가 끝나는 도시의 [ICON_CITIZEN]시민 수에 비례하여 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]20~40[ENDCOLOR] 증가합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_GENEVA', '성피에르 성당' UNION ALL
SELECT 'TXT_KEY_BUILDING_GENEVA_HELP', '[ICON_CITIZEN]시민 5명마다 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [COLOR_POSITIVE_TEXT]제네바[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_HONG_KONG', '국가 번영 위원회' UNION ALL
SELECT 'TXT_KEY_BUILDING_HONG_KONG_HELP', '[ICON_CITIZEN]시민 6명마다 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [COLOR_POSITIVE_TEXT]홍콩[ENDCOLOR]과 동맹 관계를 유지해야 합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_JERUSALEM', '성스러운 도시' UNION ALL
SELECT 'TXT_KEY_BUILDING_JERUSALEM_HELP', '이곳은 성스러운 도시입니다. 많은 사람들이 그들의 종교를 위해 이 도시를 순례했습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_KABUL', '지상 낙원' UNION ALL
SELECT 'TXT_KEY_BUILDING_KABUL_HELP', '도시 3타일 이내의 산 타일 1개마다[ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]0.66[ENDCOLOR] 증가합니다. [COLOR_POSITIVE_TEXT]카불[ENDCOLOR]과 동맹 관계를 유지해야 합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_KATHMANDU', '더 마운틴' UNION ALL
SELECT 'TXT_KEY_BUILDING_KATHMANDU_HELP', '도시 3타일 이내의 산 타일 1개마다 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]0.66[ENDCOLOR] 증가합니다. [COLOR_POSITIVE_TEXT]카트만두[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_RAGUSA', '해양 식민 총독부' UNION ALL
SELECT 'TXT_KEY_BUILDING_RAGUSA_HELP', '동맹인 도시 국가가 제공하는 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [COLOR_POSITIVE_TEXT]라구사[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_RIGA', '라트비아 상공회의소' UNION ALL
SELECT 'TXT_KEY_BUILDING_RIGA_HELP', '[ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]3%[ENDCOLOR] 증가합니다. [COLOR_POSITIVE_TEXT]리가[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_SAMARKAND', '소그드' UNION ALL
SELECT 'TXT_KEY_BUILDING_SAMARKAND_HELP', '[ICON_INTERNATIONAL_TRADE]국제 교역로의 [ICON_GOLD]골드가 [COLOR_YELLOW]4[ENDCOLOR] 증가합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_CHEVAK', '[ICON_CITY_STATE]알래스카 국립야생보호구역' UNION ALL
SELECT 'TXT_KEY_BUILDING_CHEVAK_HELP', '툰드라 타일 4개마다 또는 설원 타일 3개마다 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_QUELIMANE', '자연보호기금' UNION ALL
SELECT 'TXT_KEY_BUILDING_QUELIMANE_HELP', '강 타일에서 [ICON_GOLDEN_AGE]황금기 점수를 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 제공합니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_TAIWAN', 						'대만의 기적' UNION ALL
SELECT 'TXT_KEY_BUILDING_TAIWAN_HELP', 					'연구 협정의  [ICON_RESEARCH]과학 +10%.' UNION ALL
SELECT 'TXT_KEY_BUILDING_KIEV_2', 						'옛 이야기' UNION ALL
SELECT 'TXT_KEY_BUILDING_KIEV_2_HELP', 					'[ICON_GREAT_MUSICIAN] 위대한 음악가 생성 +5%' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILAN_2', 						'비스콘티 가문' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILAN_2_HELP', 				'[ICON_GREAT_ARTIST] 위대한 예술가 생성 +5%' UNION ALL
SELECT 'TXT_KEY_BUILDING_OC_EO', 						'위대한 글래스 강의 군주들' UNION ALL
SELECT 'TXT_KEY_BUILDING_OC_EO_HELP', 					' 해안 도시의 [ICON_INTERNATIONAL_TRADE] 교역로에서 [ICON_CULTURE_LOCAL]영토 확장 점수 +1' UNION ALL
SELECT 'TXT_KEY_BUILDING_OC_EO_2', 						'위대한 글래스 강의 군주들' UNION ALL
SELECT 'TXT_KEY_BUILDING_OC_EO_2_HELP', 				'해안 도시의 [ICON_INTERNATIONAL_TRADE] 교역로에서 [ICON_HAPPINESS_1] 행복 +1' UNION ALL
SELECT 'TXT_KEY_BUILDING_CLERMONT', 					'클레몬트의 축복' UNION ALL
SELECT 'TXT_KEY_BUILDING_CLERMONT_HELP', 				'첫 전투에 따라 임시로 무작위 [ICON_STRENGTH]전투력 보너스 제공' UNION ALL
SELECT 'TXT_KEY_BUILDING_THIMPHU', 						'전룡의 왕국' UNION ALL
SELECT 'TXT_KEY_BUILDING_THIMPHU_HELP', 				'언덕 위 도시에서 +3 [ICON_CULTURE] 문화' UNION ALL
SELECT 'TXT_KEY_BUILDING_THIMPHU_2', 					'전룡의 왕국' UNION ALL
SELECT 'TXT_KEY_BUILDING_THIMPHU_2_HELP', 				'도시 [ICON_CULTURE] 문화의 10%가 [ICON_STRENGTH] 방어력으로 전환' UNION ALL
SELECT 'TXT_KEY_BUILDING_ANDORRA', 						'피레네 영주' UNION ALL
SELECT 'TXT_KEY_BUILDING_ANDORRA_HELP', 				'산 근처 도시의 [ICON_HAPPINESS_3] 무료 -10%' UNION ALL
SELECT 'TXT_KEY_BUILDING_ANDORRA_2', 					'피레네 영주' UNION ALL
SELECT 'TXT_KEY_BUILDING_ANDORRA_2_HELP', 				'일할 수 있는 범위의 산마다 +1 [ICON_TOURISM] 관광.' UNION ALL
SELECT 'TXT_KEY_BUILDING_CANOSSA', 						'경건한 마음속의 열렬한 불꽃' UNION ALL
SELECT 'TXT_KEY_BUILDING_CANOSSA_HELP', 				'공무원 전문가에 신앙 +1. 사원이 있는 도시에 위대한 외교관 포인트 +1' UNION ALL
-- regular buildings`
SELECT 'TXT_KEY_BUILDING_KIEV', '빌리나' UNION ALL
SELECT 'TXT_KEY_BUILDING_KIEV_HELP', '걸작 음악 슬롯을 제공합니다. [COLOR_POSITIVE_TEXT]키예프[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILAN', '비스콘티 저택' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILAN_HELP', '걸작 예술품 슬롯을 제공합니다. 반드시 [COLOR_POSITIVE_TEXT]밀란[ENDCOLOR]과 동맹 관계를 유지해야 합니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_VALLETTA', '그랜드 하버' UNION ALL
SELECT 'TXT_KEY_BUILDING_VALLETTA_HELP', '[COLOR_POSITIVE_TEXT]발레타[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 도시 주변에 어선이 건설된 해양 자원이 있어야 합니다. 동맹 관계가 유지되지 않으면 산출량이 사라집니다.모든 해상 유닛의 경험치가 [COLOR_POSITIVE_TEXT]15[ENDCOLOR] 증가합니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_VILNIUS', '여명의 문' UNION ALL
SELECT 'TXT_KEY_BUILDING_VILNIUS_HELP', '걸작 문학 슬롯을 제공합니다. [COLOR_POSITIVE_TEXT]빌뉴스[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH1', '성 파트리치오' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH1_HELP', '무료에서 오는 [ICON_HAPPINESS_3]불행 감소 [COLOR_POSITIVE_TEXT]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 동맹 관계가 유지되지 않으면 문화 보너스가 사라집니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH2', '성 베니뇨' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH2_HELP', '문맹에서 오는 [ICON_HAPPINESS_3]불행 감소 [COLOR_POSITIVE_TEXT]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 동맹 관계가 유지되지 않으면 과학 보너스가 사라집니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH3', '성 세쿤디누스' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH3_HELP', '빈곤에서 오는 [ICON_HAPPINESS_3]불행 감소 [COLOR_POSITIVE_TEXT]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 동맹 관계가 유지되지 않으면 골드 보너스가 사라집니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH4', '성 첼레스티노' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH4_HELP', '곤경에서 오는 [ICON_HAPPINESS_3]불행 감소 [COLOR_POSITIVE_TEXT]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 동맹 관계가 유지되지 않으면 식량/생산 보너스가 사라집니다. 파괴될 수 없습니다.' UNION ALL
-- world wonders
SELECT 'TXT_KEY_BUILDING_LHASA', '포탈라 궁' UNION ALL
SELECT 'TXT_KEY_BUILDING_LHASA_HELP', '[ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR], [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다. 추가 대표단 [COLOR_POSITIVE_TEXT]1명[ENDCOLOR]을 확보합니다. 세계 의회가 열릴 때까지 [COLOR_POSITIVE_TEXT]라사[ENDCOLOR]와 동맹 관계를 유지해야 합니다. 동맹 관계가 유지되지 않으면 산출량이 절반으로 감소합니다. 파괴될 수 없습니다.' UNION ALL
SELECT 'TXT_KEY_BUILDING_LHASA_QUOTE', '[NEWLINE][TAB][TAB]"내가 포탈라 궁의 옥상에 처음 발을 디뎠을 때, 이전에 느껴보지 못했고 이후로도 느껴보지 못한 신기한 느낌을 받았다. 내가 방문해보지 않은 무슨 의식의 차원 같은, 마치 내 존재의 옥상에 발을 디딘 것 같았다."[NEWLINE] – 피코 아이어';
---------------------------------------------------