UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]의식[ENDCOLOR][NEWLINE]모든 국가 불가사의의 [ICON_HAPPINESS_1]행복이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다. [ICON_CAPITAL]수도에 [COLOR_YELLOW]궁정 점술사[ENDCOLOR]가 출현합니다.(과학자 전문가 슬롯 +1, [ICON_RESEARCH]과학 +3; 모든 도시에서 자문회, 오두막, 약초상에 [ICON_RESEARCH]과학 +1)'
WHERE Tag = 'TXT_KEY_POLICY_LEGALISM_HELP';
--Replace GA length from Tradition. Replace with +1 working range in Capital. Add +1 production to GPTIs
UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]전통[ENDCOLOR]은 위인 및 인상적인 수도의 건설에 초점을 맞춥니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR] [NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_FOOD]식량, [ICON_CITIZEN]시민, [ICON_HAPPINESS_1]행복 +2[NEWLINE][ICON_BULLET][ICON_CITIZEN]시민 2명마다 [ICON_CAPITAL]수도의 [ICON_CULTURE]문화 +1[NEWLINE][ICON_BULLET]모든 도시의 [ICON_FOOD]성장률 +5%[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR] [NEWLINE][ICON_BULLET]모든 도시의 [ICON_FOOD]성장률 +3%[NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_RESEARCH]과학 +1 [NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]상코레 대학[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]랜드마크 및 위인 시설의 [ICON_FOOD]식량 +1 [ICON_PRODUCTION]생산 +1[NEWLINE][ICON_BULLET][ICON_CAPITAL]수도에 [COLOR_YELLOW]알현실[ENDCOLOR] 출현[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_ENGINEER][COLOR_YELLOW]위대한 기술자[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_CAPITAL]수도에 음악가 전문가 슬롯을 [COLOR_POSITIVE_TEXT]1개[ENDCOLOR] 제공합니다. [ICON_GREAT_WORK]걸작 음악 슬롯을 [COLOR_POSITIVE_TEXT]1개[ENDCOLOR] 포함합니다. 이 도시의 작업 영역을 +1 증가시키고 모든 도시의 산출량이 [COLOR_POSITIVE_TEXT]10%[ENDCOLOR] 증가합니다. 군사 유닛 보급 한도가 [COLOR_POSITIVE_TEXT]4[ENDCOLOR] 증가합니다. 전문가 [COLOR_POSITIVE_TEXT]2명[ENDCOLOR]이 더이상 도시화에서 오는 [ICON_HAPPINESS_3]불행을 증가시키지 않습니다.  [NEWLINE][NEWLINE][COLOR_MAGENTA]전통[ENDCOLOR] 정책을 완성해야 건설할 수 있습니다.'
WHERE Tag = 'TXT_KEY_BUILDING_CAPITAL_THRONE_ROOM_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]탁월[ENDCOLOR][NEWLINE][ICON_GREAT_PEOPLE]위인을 소모할 때 [ICON_CULTURE]문화를 [COLOR_POSITIVE_TEXT]50[ENDCOLOR] [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR] 제공합니다. [ICON_CAPITAL]수도에 [COLOR_YELLOW]궁정 정원[ENDCOLOR]이 출현합니다.(작가 전문가 슬롯 +1, [ICON_GREAT_WORK]걸작 문학 슬롯 +1, [ICON_FOOD]식량 +5; 모든 도시에서 기념비, 정원, 목욕탕에 [ICON_CULTURE]문화 +2)'
WHERE Tag = 'TXT_KEY_POLICY_LANDED_ELITE_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]미학[ENDCOLOR]은 [ICON_GREAT_WORK]걸작과 [ICON_GOLDEN_AGE]황금기에 대한 잠재력을 극대화하는 능력을 강화합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_GREAT_PEOPLE]위대한 작가, 위대한 예술가, 위대한 음악가 출현율 +25%[NEWLINE][ICON_BULLET]모든 길드 건설 시 [ICON_PRODUCTION]생산 보너스 +100%[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_GOLDEN_AGE]황금기 점수 +2 [ICON_RESEARCH]과학 +1[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]루브르 박물관[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]사적지 발굴 또는 [ICON_GOLDEN_AGE]황금기 시작 시 알려진 모든 문명에 대한 [ICON_TOURISM]관광 증가[NEWLINE][ICON_BULLET]숨겨진 사적지 발굴 가능[NEWLINE][ICON_BULLET]랜드마크의 [ICON_RESEARCH]과학 및 [ICON_GOLDEN_AGE]황금기 점수 +3[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_MUSICIAN][COLOR_YELLOW]위대한 음악가[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]국보[ENDCOLOR][NEWLINE][ICON_CAPITAL]수도 근처에 원하는 [ICON_GREAT_PEOPLE][COLOR_YELLOW]위인[ENDCOLOR]이 1명 출현합니다. [ICON_GREAT_PEOPLE]세계 불가사의를 건설할 때 [ICON_GOLD]골드를 [COLOR_POSITIVE_TEXT]250[ENDCOLOR] [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR] 제공합니다.'
WHERE Tag = 'TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]문화유산[ENDCOLOR][NEWLINE] 모든 대학의 [ICON_GOLDEN_AGE]황금기 점수 및 [ICON_TOURISM]관광이 [COLOR_POSITIVE_TEXT]4[ENDCOLOR] 증가합니다. [ICON_GOLDEN_AGE]황금기 시작 비용이 25% 감소합니다.'
WHERE Tag = 'TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP';

--