------------------------------
-- Mongolia Changes
------------------------------
INSERT INTO Trait_FreePromotionUnitClass
	(TraitType, UnitClassType, PromotionType)
SELECT
	'TRAIT_TERROR', UnitClassType, 'PROMOTION_ENVELOPMENT'
FROM Trait_FreePromotionUnitClass
WHERE TraitType = 'TRAIT_TERROR' AND PromotionType = 'PROMOTION_MONGOL_TERROR';

UPDATE UnitPromotions
SET
	ExtraAttacks = 0,
	MovesChange = 1
WHERE Type = 'PROMOTION_MONGOL_TERROR';

UPDATE Language_en_US
SET Text = 'Mounted Ranged Units gain +1 [ICON_MOVES] Moves and the [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_ENVELOPMENT}[ENDCOLOR] Promotion. Gain All Yields equal to 20% of the [ICON_GOLD] Gold from bullying [ICON_CITY_STATE] City-States.'
WHERE Tag = 'TXT_KEY_TRAIT_TERROR';

UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES] Moves.'
WHERE Tag = 'TXT_KEY_PROMOTION_MONGOL_TERROR_HELP';

------------------------------
-- SKIRMISHER LINE CHANGES
------------------------------
INSERT INTO UnitPromotions
	(Type, Description, Help, Sound, RangedDefenseMod, ExtraAttacks, LostWithUpgrade, CannotBeChosen, PortraitIndex, IconAtlas, PediaType, PediaEntry)
VALUES
	('PROMOTION_SKIRMISHER_XP_PENALTY', 'TXT_KEY_PROMOTION_SKIRMISHER_XP_PENALTY', 'TXT_KEY_PROMOTION_SKIRMISHER_XP_PENALTY_HELP', 'AS2D_IF_LEVELUP', 50, 1, 1, 1, 44, 'extraPromo_Atlas', 'PEDIA_RANGED', 'TXT_KEY_PROMOTION_SKIRMISHER_XP_PENALTY');

INSERT INTO Language_en_US
	(Tag, Text)
VALUES
	('TXT_KEY_PROMOTION_SKIRMISHER_XP_PENALTY', 'Skirmisher Doctrine'),
	('TXT_KEY_PROMOTION_SKIRMISHER_XP_PENALTY_HELP', '+1 [ICON_WAR] Attack.[NEWLINE]+50% [ICON_STRENGTH] Combat Strength when defending against [COLOR_POSITIVE_TEXT]Ranged Attacks[ENDCOLOR].');

DELETE FROM Unit_FreePromotions WHERE PromotionType = 'PROMOTION_SKIRMISHER_DOCTRINE';

INSERT INTO Unit_FreePromotions
	(UnitType, PromotionType)
VALUES
	('UNIT_CHARIOT_ARCHER', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_CLINUIT_QAMUTIIK', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_EGYPTIAN_WARCHARIOT', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_MONGOLIAN_KESHIK', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_CELTS_SCYTHED_CHARIOT', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_HUN_HORSE_ARCHER', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_IA_YUEZHI', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_MOUNTED_BOWMAN', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_ARABIAN_CAMELARCHER', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_POLAND_PANCERNY', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_CUIRASSIER', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_AUSTRIAN_HUSSAR', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_INDIAN_WARELEPHANT', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_CAVALRY', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_BERBER_CAVALRY', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_SHOSHONE_COMANCHE_RIDERS', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_RUSSIAN_COSSACK', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_CL_AFGHANISTAN_ZAMBURAK', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_ANTI_TANK_GUN', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_ARABIA_HASHEMITE_RAIDER', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_HELICOPTER_GUNSHIP', 'PROMOTION_SKIRMISHER_XP_PENALTY'),
	('UNIT_ANTI_TANK_GUN','PROMOTION_ARMOR_PLATING_1'),
	('UNIT_HELICOPTER_GUNSHIP',	'PROMOTION_ARMOR_PLATING_1');

UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_CHARIOT_ARCHER';
UPDATE Units SET Moves = 3 WHERE Type = 'UNIT_CLINUIT_QAMUTIIK';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_EGYPTIAN_WARCHARIOT';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_MONGOLIAN_KESHIK';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_CELTS_SCYTHED_CHARIOT';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_HUN_HORSE_ARCHER';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_IA_YUEZHI';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_MOUNTED_BOWMAN';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_ARABIAN_CAMELARCHER';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_POLAND_PANCERNY';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_CUIRASSIER';
UPDATE Units SET Moves = 3 WHERE Type = 'UNIT_INDIAN_WARELEPHANT';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_AUSTRIAN_HUSSAR';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_JFD_DEATHS_HEAD';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_CAVALRY';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_BERBER_CAVALRY';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_SHOSHONE_COMANCHE_RIDERS';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_RUSSIAN_COSSACK';
UPDATE Units SET Moves = 4 WHERE Type = 'UNIT_CL_AFGHANISTAN_ZAMBURAK';
UPDATE Units SET Moves = 5 WHERE Type = 'UNIT_ANTI_TANK_GUN';
UPDATE Units SET Moves = 5 WHERE Type = 'UNIT_ARABIA_HASHEMITE_RAIDER';
UPDATE Units SET Moves = 6 WHERE Type = 'UNIT_HELICOPTER_GUNSHIP';

UPDATE Units SET Combat = 6 WHERE Type = 'UNIT_CHARIOT_ARCHER';
UPDATE Units SET Combat = 6 WHERE Type = 'UNIT_CLINUIT_QAMUTIIK';
UPDATE Units SET Combat = 8 WHERE Type = 'UNIT_EGYPTIAN_WARCHARIOT';
UPDATE Units SET Combat = 9 WHERE Type = 'UNIT_MONGOLIAN_KESHIK';
UPDATE Units SET Combat = 8 WHERE Type = 'UNIT_CELTS_SCYTHED_CHARIOT';
UPDATE Units SET Combat = 10 WHERE Type = 'UNIT_HUN_HORSE_ARCHER';
UPDATE Units SET Combat = 10 WHERE Type = 'UNIT_IA_YUEZHI';
UPDATE Units SET Combat = 15 WHERE Type = 'UNIT_MOUNTED_BOWMAN';
UPDATE Units SET Combat = 17 WHERE Type = 'UNIT_ARABIAN_CAMELARCHER';
UPDATE Units SET Combat = 18 WHERE Type = 'UNIT_POLAND_PANCERNY';
UPDATE Units SET Combat = 21 WHERE Type = 'UNIT_CUIRASSIER';
UPDATE Units SET Combat = 25 WHERE Type = 'UNIT_INDIAN_WARELEPHANT';
UPDATE Units SET Combat = 23 WHERE Type = 'UNIT_AUSTRIAN_HUSSAR';
UPDATE Units SET Combat = 25 WHERE Type = 'UNIT_JFD_DEATHS_HEAD';
UPDATE Units SET Combat = 31 WHERE Type = 'UNIT_CAVALRY';
UPDATE Units SET Combat = 32 WHERE Type = 'UNIT_BERBER_CAVALRY';
UPDATE Units SET Combat = 32 WHERE Type = 'UNIT_SHOSHONE_COMANCHE_RIDERS';
UPDATE Units SET Combat = 33 WHERE Type = 'UNIT_RUSSIAN_COSSACK';
UPDATE Units SET Combat = 29 WHERE Type = 'UNIT_CL_AFGHANISTAN_ZAMBURAK';
UPDATE Units SET Combat = 41 WHERE Type = 'UNIT_ANTI_TANK_GUN';
UPDATE Units SET Combat = 51 WHERE Type = 'UNIT_ARABIA_HASHEMITE_RAIDER';
UPDATE Units SET Combat = 59 WHERE Type = 'UNIT_HELICOPTER_GUNSHIP';

UPDATE Units SET RangedCombat = 6 WHERE Type = 'UNIT_CHARIOT_ARCHER';
UPDATE Units SET RangedCombat = 5 WHERE Type = 'UNIT_CLINUIT_QAMUTIIK';
UPDATE Units SET RangedCombat = 7 WHERE Type = 'UNIT_EGYPTIAN_WARCHARIOT';
UPDATE Units SET RangedCombat = 8 WHERE Type = 'UNIT_MONGOLIAN_KESHIK';
UPDATE Units SET RangedCombat = 9 WHERE Type = 'UNIT_CELTS_SCYTHED_CHARIOT';
UPDATE Units SET RangedCombat = 9 WHERE Type = 'UNIT_HUN_HORSE_ARCHER';
UPDATE Units SET RangedCombat = 9 WHERE Type = 'UNIT_IA_YUEZHI';
UPDATE Units SET RangedCombat = 12 WHERE Type = 'UNIT_MOUNTED_BOWMAN';
UPDATE Units SET RangedCombat = 13 WHERE Type = 'UNIT_ARABIAN_CAMELARCHER';
UPDATE Units SET RangedCombat = 13 WHERE Type = 'UNIT_POLAND_PANCERNY';
UPDATE Units SET RangedCombat = 17 WHERE Type = 'UNIT_CUIRASSIER';
UPDATE Units SET RangedCombat = 20 WHERE Type = 'UNIT_INDIAN_WARELEPHANT';
UPDATE Units SET RangedCombat = 18 WHERE Type = 'UNIT_AUSTRIAN_HUSSAR';
UPDATE Units SET RangedCombat = 20 WHERE Type = 'UNIT_JFD_DEATHS_HEAD';
UPDATE Units SET RangedCombat = 27 WHERE Type = 'UNIT_CAVALRY';
UPDATE Units SET RangedCombat = 28 WHERE Type = 'UNIT_BERBER_CAVALRY';
UPDATE Units SET RangedCombat = 28 WHERE Type = 'UNIT_SHOSHONE_COMANCHE_RIDERS';
UPDATE Units SET RangedCombat = 30 WHERE Type = 'UNIT_RUSSIAN_COSSACK';
UPDATE Units SET RangedCombat = 25 WHERE Type = 'UNIT_CL_AFGHANISTAN_ZAMBURAK';
UPDATE Units SET RangedCombat = 34 WHERE Type = 'UNIT_ANTI_TANK_GUN';
UPDATE Units SET RangedCombat = 37 WHERE Type = 'UNIT_ARABIA_HASHEMITE_RAIDER';
UPDATE Units SET RangedCombat = 50 WHERE Type = 'UNIT_HELICOPTER_GUNSHIP';

UPDATE UnitPromotions
SET MinimumRangeRequired = 2
WHERE Type = 'PROMOTION_LOGISTICS';

UPDATE UnitPromotions
SET PromotionPrereqOr2 = 'PROMOTION_BARRAGE_3'
WHERE Type = 'PROMOTION_SKIRMISHER_MOBILITY';

----------------------------------------------------
-- XP on first attack only
----------------------------------------------------

UPDATE CustomModOptions SET Value = 1 WHERE Name = 'BALANCE_CORE_XP_ON_FIRST_ATTACK';
