/*
VPEE compatibility patch!
0 = Disabled disregarding if its detects VPEE by Infixo.
1 = Enabled if it detects the VPEE by Infixo.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY
		(Type,			Value)
VALUES	('MUCfVP-EE', 2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'MUCfVP-EE' AND EXISTS (SELECT * FROM Eras WHERE Type='ERA_ENLIGHTENMENT') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 0);

-- Main Compatibility Code
	-- Armada
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_SHIP_OF_THE_LINE' WHERE UnitType = 'UNIT_SPAIN_ARMADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_ROCKETRY' WHERE Type = 'UNIT_SPAIN_ARMADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET PrereqTech = 'TECH_EE_EXPLORATION' WHERE Type = 'UNIT_SPAIN_ARMADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Cost = '350' WHERE Type = 'UNIT_SPAIN_ARMADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Black Tug
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_MONGOLIA_BLACK_TUG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Cacadores
	UPDATE Civilization_UnitClassOverrides SET UnitClassType = 'UNITCLASS_EE_SKIRMISHER' WHERE UnitType = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_GATLINGGUN' WHERE UnitType = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Class = 'UNITCLASS_EE_SKIRMISHER' WHERE Type = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_BALLISTICS' WHERE Type = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET PrereqTech = 'TECH_EE_FORTIFICATION' WHERE Type = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Combat = '25' WHERE Type = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET RangedCombat = '38' WHERE Type = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Cost = '375' WHERE Type = 'UNIT_PORTUGUESE_CACADORES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO	Unit_FreePromotions SELECT 'UNIT_PORTUGUESE_CACADORES', PromotionType FROM Unit_FreePromotions WHERE UnitType = 'UNIT_EE_SKIRMISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '야전병을 대체하는 포르투갈의 고유 유닛입니다. [NEWLINE]승급을 하면, 무작위로 [COLOR_PLAYER_PURPLE]개척[ENDCOLOR] 승급 또는 [COLOR_PLAYER_PURPLE]생존[ENDCOLOR] 승급을 얻습니다. [COLOR_PLAYER_PURPLE]엄호 사격 I[ENDCOLOR]승급을 받고 시작합니다.'
		WHERE Tag = 'TXT_KEY_UNIT_PORTUGUESE_CACADORES_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '야전병을 대체하는 포르투갈의 고유 유닛입니다. 승급을 하면 무작위로 전장에 도움되는 승급을 얻습니다.'
		WHERE Tag = 'TXT_KEY_UNIT_PORTUGUESE_CACADORES_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Carolean
	DELETE FROM Civilization_UnitClassOverrides WHERE CivilizationType = 'CIVILIZATION_SWEDEN' AND UnitClassType = 'UNITCLASS_RIFLEMAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Cost = '400', FaithCost = '500' WHERE Type = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Class = 'UNITCLASS_EE_LINE_INFANTRY' WHERE Type = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET PrereqTech = 'TECH_EE_FLINTLOCK' WHERE Type = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Combat = '34' WHERE Type = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_REPLACEABLE_PARTS' WHERE Type = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_RIFLEMAN' WHERE Type = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_RIFLEMAN' WHERE UnitType = 'UNIT_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Unit_Flavors SET Flavor = '20' WHERE UnitType = 'UNIT_SWEDISH_CAROLEAN' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Unit_Flavors SET Flavor = '20' WHERE UnitType = 'UNIT_SWEDISH_CAROLEAN' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Corsair
	UPDATE Civilization_UnitClassOverrides SET UnitClassType = 'UNITCLASS_EE_SHIP_OF_THE_LINE' WHERE UnitType = 'UNIT_MOROCCO_CORSAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Class = 'UNITCLASS_EE_SHIP_OF_THE_LINE' WHERE Type = 'UNIT_MOROCCO_CORSAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Combat = '35' WHERE Type = 'UNIT_MOROCCO_CORSAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Cost = '400' WHERE Type = 'UNIT_MOROCCO_CORSAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO	Unit_FreePromotions SELECT 'UNIT_MOROCCO_CORSAIR', PromotionType FROM Unit_FreePromotions WHERE UnitType = 'UNIT_EE_SHIP_OF_THE_LINE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '코르벳을 대체하는 모로코의 고유 유닛입니다. 한 시대 먼저 생산이 가능합니다. 해상 교역로를 습격하고 약탈하는 데 특화되어 있으며, 적 유닛을 죽이고 교역로를 약탈할 때마다 식량과 생산을 얻습니다. 이 유닛은 국경 개방 협정 없이도 다른 문명의 국경에 들어갈 수 있으며, 이는 무역로를 방해할 수 있습니다.'
		WHERE Tag = 'TXT_KEY_UNIT_MOROCCO_CORSAIR_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '코르벳을 대체하는 모로코의 고유 유닛입니다. 한 시대 먼저 생산이 가능합니다. 국경 개방 없이 상대방의 영토에 침입할 수 있습니다. 유닛을 처치하거나 자원 타일이나 [ICON_INTERNATIONAL_TRADE]해상 교역로를 약탈하면 [ICON_FOOD]식량과 [ICON_PRODUCTION]생산을 얻습니다.'
		WHERE Tag = 'TXT_KEY_UNIT_MOROCCO_CORSAIR_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Dromon
	UPDATE Units SET ObsoleteTech = 'TECH_EE_WARSHIPS' WHERE Type = 'UNIT_BYZANTIUM_DROMON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Fusta
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_GALLEON' WHERE UnitType = 'UNIT_VENICE_FUSTA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_EE_WARSHIPS' WHERE Type = 'UNIT_VENICE_FUSTA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Great Bombard
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_FIELD_GUN' WHERE UnitType = 'UNIT_OTTOMANS_GREAT_TURKISH_BOMBARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_OTTOMANS_GREAT_TURKISH_BOMBARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Great Galleas
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_GALLEON' WHERE UnitType = 'UNIT_VENETIAN_GALLEASS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_EE_WARSHIPS' WHERE Type = 'UNIT_VENETIAN_GALLEASS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Hakkapeliitta
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_UHLAN' WHERE UnitType = 'UNIT_SWEDISH_HAKKAPELIITTA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_COMBUSTION' WHERE Type = 'UNIT_SWEDISH_HAKKAPELIITTA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_EE_UHLAN' WHERE Type = 'UNIT_SWEDISH_HAKKAPELIITTA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Langskib
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_CARRACK' WHERE UnitType = 'UNIT_DENMARK_LANGSKIB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_NAVIGATION' WHERE Type = 'UNIT_DENMARK_LANGSKIB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Licorne
	UPDATE Civilization_UnitClassOverrides SET UnitClassType = 'UNITCLASS_EE_FIELD_GUN' WHERE UnitType = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_FIELD_GUN' WHERE UnitType = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Class = 'UNITCLASS_EE_FIELD_GUN' WHERE Type = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_BALLISTICS' WHERE Type = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET PrereqTech = 'TECH_EE_FLINTLOCK' WHERE Type = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Combat = '20' WHERE Type = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET RangedCombat = '35' WHERE Type = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Cost = '375' WHERE Type = 'UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '평사포를 대체하는 러시아의 고유 유닛입니다. 야전포보다 더 빠른 시기에 이용 가능하고, 적 영토에서 이동력이 줄어 들지 않고,  [COLOR_PLAYER_PURPLE]공격 후 이동[ENDCOLOR]이 가능합니다. 접근 유닛과 화약 유닛에 매우 효과적입니다.'
		WHERE Tag = 'TXT_KEY_UNIT_RUSSIA_LICORNE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Prowler
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_SKIRMISHER' WHERE UnitType = 'UNIT_IROQUOIS_PROWLER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_DYNAMITE' WHERE Type = 'UNIT_IROQUOIS_PROWLER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Qizilbash
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EE_UHLAN' WHERE UnitType = 'UNIT_PERSIA_QIZILBASH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_COMBUSTION' WHERE Type = 'UNIT_PERSIA_QIZILBASH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Shotel Swordsman
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_2HANDER' WHERE UnitType = 'UNIT_ETHIOPIA_SHOTELAI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_EE_FLINTLOCK' WHERE Type = 'UNIT_ETHIOPIA_SHOTELAI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Seir Morb
	UPDATE Units SET Range = '3' WHERE Type = 'UNIT_SIAM_SEIR_MORB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '곡사포를 대체하는 시암의 고유 유닛입니다. 해상 유닛에 보너스를 가지지만, [COLOR_RED]도시에 보너스[ENDCOLOR]가 없습니다.[NEWLINE][NEWLINE]해당 턴에 움직이지 않는다면 추가 피해를 입힐 수 있습니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]엄폐 I[ENDCOLOR] 승급과 [COLOR_POSITIVE_TEXT]엄폐 II[ENDCOLOR] 승급을 가지고 시작합니다.'
		WHERE Tag = 'TXT_KEY_UNIT_SIAM_SEIR_MORB_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '강력한 해안 방어 대포인 시아몹은 특히 해상 목표물에 대해 대체 곡사포보다 강력하지만 도시에 주는 피해는 적습니다. 시아몹은 공격할 때 남은 이동 수치마다 전투력이 증가 되므로 좋은 지점을 선택하고 안정적으로 유지하십시오. 거점, 거점, 거점.'
		WHERE Tag = 'TXT_KEY_UNIT_SIAM_SEIR_MORB_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Turtle Ship
	UPDATE Civilization_UnitClassOverrides SET UnitClassType = 'UNITCLASS_EE_CARRACK' WHERE UnitType = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET ObsoleteTech = 'TECH_INDUSTRIALIZATION' WHERE Type = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Class = 'UNITCLASS_EE_CARRACK' WHERE Type = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET PrereqTech = 'TECH_ASTRONOMY' WHERE Type = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Combat = '38' WHERE Type = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Moves = '3' WHERE Type = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Units SET Cost = '250' WHERE Type = 'UNIT_KOREAN_TURTLE_SHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '거북선은 전술적 목적을 위한 철갑선의 초기버젼이며 해안선을 방어하는 데 가장 적합합니다. 높은 전투력 덕분에 적 캐라벨 및 프리깃과 쉽게 싸울 수 있습니다. 주요 단점은 대체하는 카락과 달리 심해를 쉽게 이동할 수 없습니다.'
		WHERE Tag = 'TXT_KEY_CIV5_KOREA_TURTLESHIP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '카락을 대체하는 한국의 고유 유닛입니다. 다른 카락보다 더 높은 [ICON_STRENGTH] 전투력을 가지고, 다른 해상 근접 유닛에 효과적입니다. 대양 타일에서 매우 느려집니다.'
		WHERE Tag = 'TXT_KEY_CIV5_KOREA_TURTLESHIP_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Xiafan Guanjun
	UPDATE Units SET PrereqTech = 'TECH_NAVIGATION' WHERE Type = 'UNIT_CHINA_XIAFAN_GUANJUN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Yellow Brow
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_SHOSHONE_YELLOW_BROW' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- BUILDINGS
	-- Sambadrome
	UPDATE Civilization_BuildingClassOverrides SET BuildingClassType = 'BUILDINGCLASS_EE_SALON' WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET BuildingClass = 'BUILDINGCLASS_EE_SALON' WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET PrereqTech = (SELECT PrereqTech FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET FaithCost = (SELECT FaithCost FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET UnlockedByBelief = (SELECT UnlockedByBelief FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET IlliteracyFlatReduction = (SELECT IlliteracyFlatReduction FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET MutuallyExclusiveGroup = -1 WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET SpecialistCount = (SELECT SpecialistCount FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET SpecialistType = (SELECT SpecialistType FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GreatWorkCount = (SELECT GreatWorkCount FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GreatWorkSlotType = (SELECT GreatWorkSlotType FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GreatWorkYieldType = (SELECT GreatWorkYieldType FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET MinAreaSize = (SELECT MinAreaSize FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET ArtDefineTag = (SELECT ArtDefineTag FROM Buildings WHERE Type = 'BUILDING_EE_SALON') WHERE Type = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_SpecificGreatPersonRateModifier WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_GreatWorkYieldChangesLocal WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_BuildingClassYieldChanges WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_YieldModifiers WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Building_YieldChanges SET Yield = 2 WHERE BuildingType = 'BUILDING_BRAZIL_SAMBADROME' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_BRAZIL_SAMBADROME', YieldType, Yield FROM Building_YieldChangesPerPop
	WHERE BuildingType = 'BUILDING_EE_SALON'
	AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '삼바축제장은 {TXT_KEY_BUILDING_EE_SALON}를 대체하는 브라질 고유건물입니다. {TXT_KEY_BUILDING_EE_SALON}의 보너스 외에도 황금기 점수 및 관광을 얻습니다. 삼바축제장은 {TXT_KEY_BUILDING_EE_ACADEMY}가 있는 도시에 지을 수 있으므로, 일반 {TXT_KEY_BUILDING_EE_SALON}처럼 과학 발전을 방해하지 않습니다.'
		WHERE Tag = 'TXT_KEY_BUILDING_BRAZIL_SAMBADROME_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '사교회를 대체하는 브라질 고유건물입니다. 도시의 [ICON_CITIZEN]인구 5명 마다 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]증가합니다. 도시의 [ICON_CULTURE]문화가 +5% 증가합니다. 도시가 생성한 [ICON_CULTURE]문화의 10%가 턴 당 [ICON_GOLDEN_AGE]황금기 점수로 계산됩니다.[NEWLINE][NEWLINE]완성되면 "카니발"을 10턴 동안 합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_EE_ACADEMY}와 같이 지을 수 있습니다.'
		WHERE Tag = 'TXT_KEY_BUILDING_BRAZIL_SAMBADROME_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Schutzenstand
	UPDATE Civilization_BuildingClassOverrides SET BuildingClassType = 'BUILDINGCLASS_EE_GUNSMITH' WHERE BuildingType = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET BuildingClass = 'BUILDINGCLASS_EE_GUNSMITH' WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET PrereqTech = (SELECT PrereqTech FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') - 150 WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') - 1 WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET Defense = (SELECT Defense FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET ExtraCityHitPoints = (SELECT ExtraCityHitPoints FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET CitySupplyModifier = (SELECT CitySupplyModifier FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET CitySupplyFlat = (SELECT CitySupplyFlat FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET AllowsRangeStrike = (SELECT AllowsRangeStrike FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET HealRateChange = (SELECT HealRateChange FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET CityRangedStrikeRange = (SELECT CityRangedStrikeRange FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET CityIndirectFire = (SELECT CityIndirectFire FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET EmpireSizeModifierReduction = (SELECT EmpireSizeModifierReduction FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET MinAreaSize = (SELECT MinAreaSize FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET ArtDefineTag = (SELECT ArtDefineTag FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GreatWorkYieldType = (SELECT GreatWorkYieldType FROM Buildings WHERE Type = 'BUILDING_EE_GUNSMITH') WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
--	UPDATE Buildings SET BlockScienceTheft = '0' WHERE Type = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Building_ClassesNeededInCity SET BuildingClassType = (SELECT BuildingClassType FROM Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_EE_GUNSMITH') WHERE BuildingType = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Building_Flavors SET FlavorType = 'FLAVOR_MILITARY_TRAINING' WHERE BuildingType = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND FlavorType = 'FLAVOR_CITY_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Building_UnitCombatProductionModifiers SET Modifier = '10' WHERE BuildingType = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_UnitCombatProductionModifiers WHERE BuildingType = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND UnitCombatType != 'UNITCOMBAT_GUN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_UnitCombatFreeExperiences WHERE BuildingType = 'BUILDING_AUSTRIA_STANDSCHUTZEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO Building_DomainProductionModifiers
	SELECT 'BUILDING_AUSTRIA_STANDSCHUTZEN', DomainType, Modifier + 5 FROM Building_DomainProductionModifiers
	WHERE BuildingType = 'BUILDING_EE_GUNSMITH'
	AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO Building_DomainFreeExperiences
	SELECT 'BUILDING_AUSTRIA_STANDSCHUTZEN', DomainType, Experience + 20 FROM Building_DomainFreeExperiences
	WHERE BuildingType = 'BUILDING_EE_GUNSMITH'
	AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO Building_YieldFromUnitProduction
	SELECT 'BUILDING_AUSTRIA_STANDSCHUTZEN', YieldType, Yield FROM Building_YieldFromUnitProduction
	WHERE BuildingType = 'BUILDING_EE_GUNSMITH'
	AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '화기제작소를 대체하는 오스트리아의 고유건물입니다. 도시 국가 동맹마다 [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 및 [ICON_CULTURE]문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]이 증가합니다. 화약 유닛을 생산할때 [ICON_PRODUCTION]생산보너스가 [COLOR_POSITIVE_TEXT]30%[ENDCOLOR]가 증가합니다. 다른 모든 지상 군사 유닛을 생산할때 [ICON_PRODUCTION]생산 보너스 [COLOR_POSITIVE_TEXT]20%[ENDCOLOR]를 주며 모두 [COLOR_POSITIVE_TEXT]40[ENDCOLOR]의 경험치를 받습니다.[NEWLINE][NEWLINE]이 도시에 유닛을 생산하면, 해당 유닛 [ICON_PRODUCTION]생산 비용의 5%에 해당하는 [ICON_RESEARCH]과학을 얻습니다.[NEWLINE][NEWLINE][ICON_SILVER_FIST]군사 유닛 보급한도가 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
		WHERE Tag = 'TXT_KEY_BUILDING_AUSTRIA_STANDSCHUTZEN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '스탠드슈첸은 {TXT_KEY_BUILDING_EE_GUNSMITH}를 대체하는 오스트리아의 고유 건물입니다. {TXT_KEY_BUILDING_EE_GUNSMITH} 보다 생산 비용이 저렴하고, 도시에서 지상군 유닛을 더 빠르고 더 좋게 생산할 수 있습니다. 또한 도시 국가 동맹마다 [ICON_PRODUCTION] 생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]및 [ICON_CULTURE] 문화가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]이 증가합니다.'
		WHERE Tag = 'TXT_KEY_BUILDING_AUSTRIA_STANDSCHUTZEN_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Waag
	UPDATE Civilization_BuildingClassOverrides SET BuildingClassType = 'BUILDINGCLASS_EE_WEIGH_HOUSE' WHERE BuildingType = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET BuildingClass = 'BUILDINGCLASS_EE_WEIGH_HOUSE' WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET PrereqTech = 'TECH_ECONOMICS' WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET FreeStartEra = (SELECT FreeStartEra FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET SpecialistCount = (SELECT SpecialistCount FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET TradeRouteSeaGoldBonus = (SELECT TradeRouteSeaGoldBonus FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET TradeRouteRecipientBonus = (SELECT TradeRouteRecipientBonus FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET TradeRouteTargetBonus = (SELECT TradeRouteTargetBonus FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET EnhancedYieldTech = (SELECT EnhancedYieldTech FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET TechEnhancedTourism = (SELECT TechEnhancedTourism FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET AllowsRangeStrike = (SELECT AllowsRangeStrike FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET TrainedFreePromotion = (SELECT TrainedFreePromotion FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET CitySupplyFlat = (SELECT CitySupplyFlat FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GreatPeopleRateModifier = (SELECT GreatPeopleRateModifier FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET GreatWorkSlotType = (SELECT GreatWorkSlotType FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET FreshWater = (SELECT FreshWater FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET Happiness = (SELECT Happiness FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Buildings SET ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE') WHERE Type = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Building_ClassesNeededInCity SET BuildingClassType = (SELECT BuildingClassType FROM Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_EE_WEIGH_HOUSE') WHERE BuildingType = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	--UPDATE Building_YieldChanges SET Yield = '5' WHERE BuildingType = 'BUILDING_NETHERLANDS_WAAG' AND YieldType = 'YIELD_GOLD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_NETHERLANDS_WAAG', 'YIELD_GOLD', 50 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_ResourceYieldChanges WHERE BuildingType = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_YieldFromPurchase WHERE BuildingType = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	DELETE FROM Building_BuildingClassLocalYieldChanges WHERE BuildingType = 'BUILDING_NETHERLANDS_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Building_BuildingClassLocalYieldChanges SET BuildingClassType = 'BUILDINGCLASS_EE_WEIGH_HOUSE' WHERE BuildingType = 'BUILDING_D_FOR_WAAG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '바그는 {TXT_KEY_BUILDING_EE_WEIGH_HOUSE}를 대체하는 네덜란드의 고유 건물입니다. {TXT_KEY_BUILDING_EE_WEIGH_HOUSE}의 일반 보너스에 더해, 보다 더 일찍 건설 할 수 있으며 방어력과 생산력에 보너스를 제공합니다. 바그의 보너스는 네덜란드가 통제하는 사치품과 전략품, 모두를 포함하는 국제적 독점의 총 수에 따라 확장됩니다. 주변과 평화롭고 수익성 있는 관계를 유지하십시오. 거래 파트너와의 기습적인 전쟁은 갑자기 도시의 방어력을 약화시킬 수 있습니다!'
		WHERE Tag = 'TXT_KEY_BUILDING_NETHERLANDS_WAAG_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
	UPDATE Language_ko_KR
		SET Text = '측정소를 대체하는 네덜란드의 고유 건물입니다. 도시의 모든 [ICON_CITIZEN]시민 2명 마다 [ICON_GOLD]골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]이 증가합니다. 도시의 [ICON_SPY]스파이 저항이 [COLOR_POSITIVE_TEXT]20%[ENDCOLOR] 증가합니다.[NEWLINE][NEWLINE]문명의 독점 자원당 이 도시의 [ICON_GOLD]골드, [ICON_CULTURE]문화, [ICON_PRODUCTION]생산이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]씩 증가합니다.[NEWLINE][NEWLINE]이 도시로 향하는 교역로마다 도시의 골드가 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가하고, 교역로를 개설한 상대 문명의 골드도 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다. 해상 교역로에서도 [ICON_GOLD]골드 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]이 증가합니다.'
		WHERE Tag = 'TXT_KEY_BUILDING_NETHERLANDS_WAAG_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	-- Salon name changed to Parlour
	UPDATE Language_ko_KR
		SET Text = '사교회'
		WHERE Tag = 'TXT_KEY_BUILDING_EE_SALON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);

	UPDATE Language_ko_KR
		SET Text = '{TXT_KEY_BUILDING_EE_SALON}는 수도원의 외부 방이나 건물로, 수도사들이 방문객 및 일반인과 대화하고 사업을 할 수 있는 장소로 시작되었습니다. 이후, 이 건물은 중산층 가정의 필수 공간으로 확산되었으며, 그곳에서 당대의 아이디어가 논의되었습니다. 오늘날에는 장례식장 및 미용실의 형태로, 사업 장소로서의 사용이 지속되고 있습니다.'
		WHERE Tag = 'TXT_KEY_BUILDING_EE_SALON_PEDIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='MUCfVP-EE' AND Value= 1);
