INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARMOR';

INSERT INTO Building_SpecialistYieldChanges (BuildingType, SpecialistType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK');

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'YIELD_GOLD', 4 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'BUILDING_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'BUILDING_FA_SEA_ACADEMY', 'YIELD_GREAT_ADMIRAL_POINTS', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');

UPDATE Building_Flavors
SET Flavor = 0
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND FlavorType = 'FLAVOR_HAPPINESS';

UPDATE Building_BuildingClassHappiness
SET Happiness = 0
WHERE BuildingClassType = 'BUILDINGCLASS_FA_ELECTRIC_POWER' AND BuildingType = 'BUILDING_FA_ELECTRIC_CO';

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_BANK';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_HARBOR'
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_TRAINSTATION'
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION';

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'BUILDINGCLASS_BANK' WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK');

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD';

DELETE FROM Building_DomainFreeExperiences
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

DELETE FROM Building_DomainProductionModifiers
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

DELETE FROM Building_DomainFreeExperiences
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

DELETE FROM Building_DomainProductionModifiers
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), TrainedFreePromotion = 'PROMOTION_GENERAL_STACKING', GreatGeneralRateModifier = 0, CitySupplyModifier = 10, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), FreeBuildingThisCity = NULL
WHERE Type = 'BUILDING_FA_WAR_ACADEMY';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HERMITAGE'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_HERMITAGE'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_HERMITAGE'), FreePromotion = 'PROMOTION_FA_SEA_ACADEMY', TrainedFreePromotion = NULL, CitySupplyFlat = 2, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')
WHERE Type = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Buildings
SET Cost = ((SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'))/2, NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'), NationalPopRequired = ((SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'))/2, GreatPeopleRateChange = 1, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE')
WHERE Type = 'BUILDING_FA_CENTRAL_BANK';

UPDATE Buildings
SET Cost = ((SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'))/2, NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'), NationalPopRequired = ((SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'))/2, CityConnectionTradeRouteModifier = 25, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE')
WHERE Type = 'BUILDING_FA_CENTRAL_STATION';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE'), HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FOREIGN_OFFICE')
WHERE Type = 'BUILDING_FA_AIR_ACADEMY';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), FreeBuilding = 'BUILDINGCLASS_FA_ELECTRIC_POWER', HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), GoldMaintenance = 0, FreeBuildingThisCity = 'BUILDINGCLASS_HYDRO_PLANT'
WHERE Type = 'BUILDING_FA_ELECTRIC_CO';

UPDATE Language_ko_KR
SET Text = '모든 도시의 상인에게 [ICON_GOLD] 골드 +1을 제공합니다.[NEWLINE][NEWLINE][ICON_CAPITAL] 수도에만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_BANK_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_CONNECTED] 도시 연결에서 오는 [ICON_GOLD] 골드가 +25% 증가합니다. 공장의 [ICON_GOLD] 골드가 +1 증가합니다.[[NEWLINE][NEWLINE]문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_CONNECTED] 도시 연결에서 오는 [ICON_GOLD] 골드가 +25% 증가합니다. 공장의 [ICON_GOLD] 골드가 +1 증가합니다.[NEWLINE][NEWLINE]문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION2_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_HYDRO_PLANT}를 제공합니다. 모든 도시는 [COLOR_POSITIVE_TEXT]전력소[ENDCOLOR]를 공급받으며, 이를 통해 모든 도시의 [ICON_RESEARCH] 과학, [ICON_GOLD] 금, [ICON_PRODUCTION] 생산이 증가합니다.[NEWLINE][NEWLINE]강가에 있는 도시에 건설해야 합니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO_HELP';

UPDATE Language_ko_KR
SET Text = '모든 도시는 [COLOR_POSITIVE_TEXT]전력소[ENDCOLOR]를 공급받으며, 이를 통해 모든 도시의 [ICON_RESEARCH] 과학, [ICON_GOLD] 금, [ICON_PRODUCTION] 생산이 증가합니다.[NEWLINE][NEWLINE]강가에 있는 도시에 건설해야 합니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO2_HELP';

UPDATE Language_ko_KR
SET Text = '이 도시에서 생성된 모든 지상 전투 유닛(과거 또는 미래)은 [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_GENERAL_STACKING}[ENDCOLOR] 승급을 받습니다. ({TXT_KEY_PROMOTION_GENERAL_STACKING_HELP}) [ICON_SILVER_FIST] 이 도시의 인구가 공급하는 군사 유닛이 10% 증가합니다.[NEWLINE][NEWLINE]문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_WAR_ACADEMY_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_SILVER_FIST] 군사 유닛 공급 한도가 2 증가합니다. 모든 해상 전투 유닛은 [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_FA_SEA_ACADEMY}[ENDCOLOR] 승급을 받습니다. ({TXT_KEY_PROMOTION_FA_SEA_ACADEMY_HELP})[NEWLINE][NEWLINE]문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_SEA_ACADEMY_HELP';

UPDATE Language_ko_KR
SET Text = '공중 전투 유닛을 생산할 때 [ICON_PRODUCTION]생산 보너스를 +25% 제공합니다. 이 도시에서 훈련된 모든 공중 전투 유닛은 [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_EVASION}[ENDCOLOR] 승급을 받습니다. ({TXT_KEY_PROMOTION_EVASION_HELP})[NEWLINE][NEWLINE]문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION] 생산과 [ICON_CITIZEN] 시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_AIR_ACADEMY_HELP';

UPDATE Language_ko_KR
SET Text = '전투에서 얻는 경험치 50% 증가, [ICON_MOVES] 이동력 +1'
WHERE Tag = 'TXT_KEY_PROMOTION_FA_SEA_ACADEMY_HELP';

UPDATE UnitPromotions
SET ExperiencePercent = 50, MovesChange = 1, PortraitIndex = 34, IconAtlas = 'promoVP_atlas_01'
WHERE Type = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_Domains 
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_Terrains
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL';

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND UnitType = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND UnitType = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND UnitType = 'UNIT_GREAT_ADMIRAL';

INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_AIR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_ELECTRIC_CO') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');

INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_AIR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_ELECTRIC_CO') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');