INSERT INTO Audio_Sounds
	(SoundID, Filename, LoadType)
VALUES
	('SND_WONDER_SKARABRAE', 'SkaraBrae', 'DynamicResident'),
	('SND_WONDER_NEWGRANGE', 'Newgrange', 'DynamicResident'),
	('SND_WONDER_GGANTIJA', 'Ggantija', 'DynamicResident'),
	('SND_WONDER_BARNENEZ', 'Barnenez', 'DynamicResident');

INSERT INTO Audio_2DSounds
	(ScriptID, SoundID, SoundType, MinVolume, MaxVolume, IsMusic, TaperSoundtrackVolume)
VALUES
	('AS2D_WONDER_SKARABRAE', 'SND_WONDER_SKARABRAE', 'GAME_MUSIC_STINGS', 120, 120, 'true', 0.0),
	('AS2D_WONDER_NEWGRANGE', 'SND_WONDER_NEWGRANGE', 'GAME_MUSIC_STINGS', 120, 120, 'true', 0.0),
	('AS2D_WONDER_GGANTIJA', 'SND_WONDER_GGANTIJA', 'GAME_MUSIC_STINGS', 120, 120, 'true', 0.0),
	('AS2D_WONDER_BARNENEZ', 'SND_WONDER_BARNENEZ', 'GAME_MUSIC_STINGS', 120, 120, 'true', 0.0);

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_STONEHENGE'), PrereqTech = 'TECH_MINING', EnhancedYieldTech = 'TECH_ARCHAEOLOGY', TechEnhancedTourism = 2, WonderSplashAudio = 'AS2D_WONDER_BARNENEZ', HurryCostModifier = -5, FreeBuildingThisCity = 'BUILDINGCLASS_STONE_WORKS', MutuallyExclusiveGroup = 600, SpecialistType = 'SPECIALIST_ARTIST', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_BARNENEZ';
DELETE FROM Building_ResourceYieldChanges WHERE BuildingType = 'BUILDING_BARNENEZ';
UPDATE Building_YieldChanges SET Yield = 1 WHERE BuildingType = 'BUILDING_BARNENEZ';
INSERT INTO Building_InstantYield (BuildingType, YieldType, Yield) SELECT 'BUILDING_BARNENEZ', 'YIELD_SCIENCE', 40 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_BARNENEZ');
--INSERT INTO Building_BuildingClassYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange) SELECT 'BUILDING_BARNENEZ', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_BARNENEZ');
--INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield) SELECT 'BUILDING_BARNENEZ', 'IMPROVEMENT_QUARRY', 'YIELD_PRODUCTION', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_BARNENEZ');
INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_BARNENEZ', 'FLAVOR_PRODUCTION', 50 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_BARNENEZ') UNION ALL
SELECT 'BUILDING_BARNENEZ', 'FLAVOR_SCIENCE', 10 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_BARNENEZ') UNION ALL
SELECT 'BUILDING_BARNENEZ', 'FLAVOR_WONDER', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_BARNENEZ');

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_STONEHENGE'), PrereqTech = 'TECH_TRAPPING', EnhancedYieldTech = 'TECH_ARCHAEOLOGY', TechEnhancedTourism = 2, WonderSplashAudio = 'AS2D_WONDER_GGANTIJA', HurryCostModifier = -5, FreeBuildingThisCity = 'BUILDINGCLASS_LODGE', MutuallyExclusiveGroup = 600, SpecialistType = 'SPECIALIST_MERCHANT', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_GGANTIJA';
UPDATE Building_Flavors SET FlavorType = 'FLAVOR_RELIGION' WHERE BuildingType = 'BUILDING_GGANTIJA' AND Flavor = 10;
DELETE FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_GGANTIJA';
DELETE FROM Building_GlobalYieldModifiers WHERE BuildingType = 'BUILDING_GGANTIJA';
INSERT INTO Building_YieldChanges (BuildingType,YieldType, Yield) SELECT 'BUILDING_GGANTIJA', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_GGANTIJA') UNION ALL
SELECT 'BUILDING_GGANTIJA', 'YIELD_FOOD', 1; 
INSERT INTO Building_InstantYield (BuildingType, YieldType, Yield) SELECT 'BUILDING_GGANTIJA', 'YIELD_POPULATION', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_GGANTIJA');
INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_GGANTIJA', 'FLAVOR_GROWTH', 35 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_GGANTIJA') UNION ALL
SELECT 'BUILDING_GGANTIJA', 'FLAVOR_PRODUCTION', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_GGANTIJA') UNION ALL
SELECT 'BUILDING_GGANTIJA', 'FLAVOR_WONDER', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_GGANTIJA');

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_STONEHENGE'), PrereqTech = 'TECH_POTTERY', EnhancedYieldTech = 'TECH_ARCHAEOLOGY', TechEnhancedTourism = 2, WonderSplashAudio = 'AS2D_WONDER_NEWGRANGE', HurryCostModifier = -5, FreeBuildingThisCity = 'BUILDINGCLASS_GRANARY', MutuallyExclusiveGroup = 600
WHERE Type = 'BUILDING_NEWGRANGE';
DELETE FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_NEWGRANGE';
INSERT INTO Building_YieldChanges (BuildingType,YieldType, Yield) SELECT 'BUILDING_NEWGRANGE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE'); 
INSERT INTO Building_YieldChanges (BuildingType,YieldType, Yield) SELECT 'BUILDING_NEWGRANGE', 'YIELD_GOLDEN_AGE_POINTS', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE'); 
INSERT INTO Building_YieldFromBirth (BuildingType, YieldType, Yield) SELECT 'BUILDING_NEWGRANGE', 'YIELD_GOLDEN_AGE_POINTS', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE');
INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_NEWGRANGE', 'FLAVOR_GROWTH', 35 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE') UNION ALL
SELECT 'BUILDING_NEWGRANGE', 'FLAVOR_HAPPINESS', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE') UNION ALL
SELECT 'BUILDING_NEWGRANGE', 'FLAVOR_WONDER', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE');

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_STONEHENGE'), PrereqTech = 'TECH_ANIMAL_HUSBANDRY', EnhancedYieldTech = 'TECH_ARCHAEOLOGY', TechEnhancedTourism = 2, WonderSplashAudio = 'AS2D_WONDER_SKARABRAE', HurryCostModifier = -5, FreeBuildingThisCity = NULL, MutuallyExclusiveGroup = 600, SpecialistType = 'SPECIALIST_SCIENTIST', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_SKARABRAE';
DELETE FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_SKARABRAE';
INSERT INTO Building_YieldChanges (BuildingType,YieldType, Yield) SELECT 'BUILDING_SKARABRAE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
SELECT 'BUILDING_SKARABRAE', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE');
DELETE FROM Building_ResourceYieldChanges WHERE BuildingType = 'BUILDING_SKARABRAE';
--INSERT INTO Building_BuildingClassYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange) SELECT 'BUILDING_SKARABRAE', 'BUILDINGCLASS_GRANARY', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE');
--INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield) SELECT 'BUILDING_SKARABRAE', 'RESOURCE_HORSE', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION All
--SELECT 'BUILDING_SKARABRAE', 'RESOURCE_COW', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
--SELECT 'BUILDING_SKARABRAE', 'RESOURCE_SHEEP', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE');
INSERT INTO Building_ResourcePlotsToPlace (BuildingType, ResourceType, NumPlots, ResourceQuantityToPlace) SELECT 'BUILDING_SKARABRAE', 'RESOURCE_HORSE', 1, 4 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE');
INSERT INTO Building_FreeUnits (BuildingType, UnitType, NumUnits) SELECT 'BUILDING_SKARABRAE', 'UNIT_WORKER', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE');
INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_SKARABRAE', 'FLAVOR_GROWTH', 34 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
SELECT 'BUILDING_SKARABRAE', 'FLAVOR_OFFENSE', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
SELECT 'BUILDING_SKARABRAE', 'FLAVOR_DEFENSE', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
SELECT 'BUILDING_SKARABRAE', 'FLAVOR_MOBILE', 8 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
SELECT 'BUILDING_SKARABRAE', 'FLAVOR_RANGED', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE') UNION ALL
SELECT 'BUILDING_SKARABRAE', 'FLAVOR_WONDER', 20 WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_SKARABRAE');

UPDATE Buildings
SET EnhancedYieldTech = 'TECH_ARCHAEOLOGY', TechEnhancedTourism = 2, MutuallyExclusiveGroup = 600
WHERE Type = 'BUILDING_STONEHENGE' AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE');

UPDATE Language_ko_KR
SET Text = '이 불가사의가 건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_STONE_WORKS}과 [ICON_RESEARCH] 과학 40을 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_BARNENEZ_HELP';

UPDATE Language_ko_KR
SET Text = '이 불가사의가 건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_GRANARY}를 제공합니다. 도시에 새로운 [ICON_CITIZEN] 시민이 태어나면 [ICON_GOLDEN_AGE] 황금기 점수 20을 얻습니다. (시대에 따라 보정) [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_NEWGRANGE_HELP';

UPDATE Language_ko_KR
SET Text = '도시 근처에 {TXT_KEY_UNIT_WORKER}가 나타납니다. 도시 근처에 [ICON_RES_HORSE] 말 4마리를 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_SKARABRAE_HELP';

UPDATE Language_ko_KR
SET Text = '건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_LODGE}과 [ICON_CITIZEN] 인구 2명을 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_WONDER_GGANTIJA_HELP';

UPDATE Language_ko_KR
SET Text = '건설된 도시에 [COLOR_POSITIVE_TEXT]무료[ENDCOLOR] {TXT_KEY_BUILDING_GROVE}과 [ICON_PEACE] 신앙 60을 제공합니다. [COLOR_RESEARCH_STORED]{TXT_KEY_TECH_ARCHAEOLOGY}[ENDCOLOR]을 연구하면 [ICON_TOURISM] 관광이 +2 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_STONEHENGE_HELP' AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_NEWGRANGE');