INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
SELECT 'POLICY_ICONATLAS', 256, 'POLICY_ICONATLAS256.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 128, 'POLICY_ICONATLAS128.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 80, 'POLICY_ICONATLAS80.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 64, 'POLICY_ICONATLAS64.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 45, 'POLICY_ICONATLAS45.dds', 8, 2;

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '전통 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_TRADITION} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PUBLIC_BATHS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '진보 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_LIBERTY} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_TOWN_COUNCIL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_CULTURE_LOCAL] 국경 확장 +1'
	WHERE Tag = 'TXT_KEY_POLICY_COLLECTIVE_RULE_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_GOLDEN_AGE] 황금기 점수 +1'
	WHERE Tag = 'TXT_KEY_POLICY_CITIZENSHIP_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_PRODUCTION] 생산력 +1'
	WHERE Tag = 'TXT_KEY_POLICY_REPUBLIC_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_GOLD] 골드 +1'
	WHERE Tag = 'TXT_KEY_POLICY_REPRESENTATION_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_FOOD] 식량 +1'
	WHERE Tag = 'TXT_KEY_POLICY_MERITOCRACY_HELP';
	
UPDATE Language_ko_KR
	SET TEXT = REPLACE(Text, '성을 향해', '영주 저택을 향해, 성,')
	WHERE Tag = 'TXT_KEY_POLICY_MANDATE_OF_HEAVEN_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '권위 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_HONOR} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_STRONGHOLD}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '충성 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_PIETY} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '외교 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_PATRONAGE} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_CHANCERY}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '미학 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_AESTHETICS} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_MEMORIAL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '산업 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_COMMERCE} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PATENT_OFFICE}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '제국 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_EXPLORATION} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_DEPOT}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '합리 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_RATIONALISM} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';

INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', '사우나'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', '시청'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', '성채'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', '영주 저택'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_CHANCERY', '대사관'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_MEMORIAL', '기념비'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_DEPOT', '창고'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', '식물원'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', '특허청'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', '이 도시의 {TXT_KEY_BUILDING_WELL}과 {TXT_KEY_BUILDING_BATH}은 [ICON_FOOD] 식량 +1을 얻고, 이 도시에서 10턴 동안 "국왕 경축일"을 시작합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_TRADITION}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다. '),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', '+2% [ICON_GOLD] Gold from [ICON_CONNECTED] City Connections. City Hall generate additional yields as [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_LIBERTY}[ENDCOLOR] policies are unlocked.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_LIBERTY}[ENDCOLOR]를 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', '+75 [ICON_CULTURE_LOCAL] Border Growth when completed. +1 [ICON_PRODUCTION] Production to Forts and Citadels. +1 [ICON_RESEARCH] Science once [COLOR_CYAN]{TXT_KEY_TECH_ENGINEERING}[ENDCOLOR] is discovered.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_HONOR}[ENDCOLOR]를 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', '건설이 완료되면 [ICON_FOOD] 식량 +100를 얻습니다. 이 도시에서 [ICON_PEACE] 신앙 구매 비용의 15%를 [ICON_FOOD] 식량과 [ICON_CULTURE] 문화로 얻습니다. "국왕 경축일" 동안 [ICON_PEACE] 신앙이 +15% 증가합니다.[NEWLINE][NEWLINE][ICON_CITY_STATE] 이 도시에서 문명 크기 수정치가 5% 감소합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_PIETY}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', '[ICON_RES_PAPER] 종이 +1을 추가합니다. 세계 의회에서 [COLOR_POSITIVE_TEXT]추가[ENDCOLOR] [ICON_DIPLOMAT] 대표 1명을 받습니다. 모든 도시의 공무원은 [ICON_GOLD] 골드 +1을 생산합니다.[NEWLINE][NEWLINE]도시 국가 친구 1명당 [ICON_GOLD] 골드 +1 , 동맹 1명당 [ICON_RESEARCH] 과학 +1, [ICON_CULTURE] 문화 +1 를 추가로 획득합니다.[NEWLINE][NEWLINE][ICON_CAPITAL] 수도에만 건설할 수 있고 [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_PATRONAGE}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', '[ICON_GREAT_PEOPLE] 위인을 소모하면 +5 [ICON_GOLDEN_AGE] 황금기 점수를 얻습니다. (시대에 따라 조정)[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_AESTHETICS}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', '[ICON_CITIZEN] 인구로부터 군사 공급이 +10% 증가합니다. 이 도시와의 내부 [ICON_INTERNATIONAL_TRADE] 교역로가 완성되면 출발하는 도시에 [ICON_GOLD] 골드 100이 생성됩니다. (시대에 따라 조정)[NEWLINE][NEWLINE]이 도시에서 유닛을 훈련할 때, 유닛 생산 비용 [ICON_PRODUCTION]의 10%에 해당하는 [ICON_GOLD] 골드를 얻습니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_EXPLORATION}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', '도시에서 작업하는 정글, 숲, 범람원 2개마다 [ICON_RESEARCH] 과학이 +1 증가합니다. 모든 습지, 오아시스, 산호섬에서 과학이 +1 [ICON_RESEARCH] 증가합니다.[NEWLINE][NEWLINE]도시에 있는 [ICON_VP_SCIENTIST] 과학자, {TXT_KEY_BUILDING_GARDEN}, {TXT_KEY_BUILDING_THEATRE}에서 [ICON_FOOD] 식량 +2를 생성합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_RATIONALISM}[ENDCOLOR]를 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', '이 도시의 [ICON_VP_ENGINEER] 기술자, [ICON_VP_MERCHANT] 상인, [ICON_GREAT_WORK] 걸작이 [ICON_GOLD] 골드 +1을 생산합니다.[NEWLINE][NEWLINE]기술을 연구할 때마다 [ICON_PRODUCTION] 생산력과 [ICON_GOLD] 골드를 20 얻습니다. (시대에 따라 보정)[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_COMMERCE}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.');

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
	SELECT 'BUILDINGCLASS_TCS_PUBLIC_BATHS', 'BUILDING_TCS_PUBLIC_BATHS', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'BUILDING_TCS_TOWN_COUNCIL', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_STRONGHOLD', 'BUILDING_TCS_STRONGHOLD', 'TXT_KEY_BUILDING_TCS_STRONGHOLD' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_CHANCERY', 'BUILDING_TCS_CHANCERY', 'TXT_KEY_BUILDING_TCS_CHANCERY' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_MEMORIAL', 'BUILDING_TCS_MEMORIAL', 'TXT_KEY_BUILDING_TCS_MEMORIAL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_DEPOT', 'BUILDING_TCS_DEPOT', 'TXT_KEY_BUILDING_TCS_DEPOT' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_BOTANICAL_GARDENS', 'BUILDING_TCS_BOTANICAL_GARDENS', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_PATENT_OFFICE', 'BUILDING_TCS_PATENT_OFFICE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE';

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, PolicyBranchType, Description, Help, MinAreaSize, NukeImmune, NeverCapture, HurryCostModifier, IconAtlas, PortraitIndex)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_TCS_PUBLIC_BATHS', 80, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'), NULL, 'POLICY_BRANCH_TRADITION', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY'), 'POLICY_ICONATLAS', 0 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 80, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'), NULL, 'POLICY_BRANCH_LIBERTY', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY'), 'POLICY_ICONATLAS', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'BUILDINGCLASS_TCS_STRONGHOLD', 80, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'), NULL, 'POLICY_BRANCH_HONOR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY'), 'POLICY_ICONATLAS', 2 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 250, 0, NULL, 'POLICY_BRANCH_PIETY', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HARBOR'), 'POLICY_ICONATLAS', 3 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'BUILDINGCLASS_TCS_CHANCERY', 500, 0, NULL, 'POLICY_BRANCH_PATRONAGE', 'TXT_KEY_BUILDING_TCS_CHANCERY', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HARBOR'), 'POLICY_ICONATLAS', 4 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'BUILDINGCLASS_TCS_MEMORIAL', 250, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_HARBOR'), NULL, 'POLICY_BRANCH_AESTHETICS', 'TXT_KEY_BUILDING_TCS_MEMORIAL', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HARBOR'), 'POLICY_ICONATLAS', 5 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'BUILDINGCLASS_TCS_DEPOT', 500, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), NULL, 'POLICY_BRANCH_EXPLORATION', 'TXT_KEY_BUILDING_TCS_DEPOT', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'POLICY_ICONATLAS', 6 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_TCS_BOTANICAL_GARDENS', 500, (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), NULL, 'POLICY_BRANCH_RATIONALISM', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'POLICY_ICONATLAS', 7 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'BUILDINGCLASS_TCS_PATENT_OFFICE', 500, 0, NULL, 'POLICY_BRANCH_COMMERCE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', -1, 1, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PUBLIC_SCHOOL'), 'POLICY_ICONATLAS', 8;
--So it got flipped. Depot is moved to Imperialism. Botanical Garden moved to Rationalism. Patent Office moved to Industry!
INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
	SELECT 'BUILDING_TCS_CHANCERY', 'BUILDINGCLASS_PALACE';

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_CULTURE', 1 UNION ALL
	--SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FAITH', 2 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FOOD', 2 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_CULTURE', 2 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_SCIENCE', 2 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 2 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_CULTURE', 3 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_TOURISM', 2 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_GOLD', 3 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_PRODUCTION', 5 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_FOOD', 3;

INSERT INTO Building_TechEnhancedYieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_SCIENCE', 1;
	
INSERT INTO Building_InstantYield (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_CULTURE_LOCAL', 75 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FOOD', 100;
	
INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_FORT', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_CITADEL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_MONGOLIA_ORDO', 'YIELD_PRODUCTION', 1;
	
INSERT INTO Building_ResourceQuantity (BuildingType, ResourceType, Quantity)
	SELECT 'BUILDING_TCS_CHANCERY', 'RESOURCE_PAPER', 1;
	
--INSERT	INTO Building_YieldFromYieldPercent (BuildingType, YieldIn, YieldOut, Value )
--	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_FOOD', 'YIELD_SCIENCE', 5;

INSERT	INTO Building_YieldPerXFeatureTimes100 (BuildingType, FeatureType, YieldType, Yield)
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', Type, 'YIELD_SCIENCE', 50 FROM Features
	WHERE Type IN ('FEATURE_JUNGLE', 'FEATURE_FOREST', 'FEATURE_FLOOD_PLAINS');
	
INSERT INTO Building_FeatureYieldChanges (BuildingType, FeatureType, YieldType, Yield)
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FEATURE_MARSH', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FEATURE_ATOLL', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FEATURE_OASIS', 'YIELD_SCIENCE', 1;
		
INSERT INTO Building_BuildingClassLocalYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_WELL', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_BATH', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_GARDEN', 'YIELD_FOOD', 2 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_THEATRE', 'YIELD_FOOD', 2;

INSERT INTO Building_YieldFromFaithPurchase (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FOOD', 15 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_CULTURE', 15;
	
INSERT	INTO Building_WLTKDYieldMod (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FAITH', 15;

INSERT INTO Building_SpecialistYieldChanges (BuildingType, SpecialistType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLD', 1;
	
INSERT INTO Building_YieldPerFriend (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 1;

INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_CULTURE', 1 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_SCIENCE', 1;

INSERT	INTO Building_YieldFromGPExpend (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_GOLDEN_AGE_POINTS', 5;
	
INSERT	INTO Building_GreatWorkYieldChangesLocal (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_GOLD', 1;
	
INSERT	INTO Building_SpecialistYieldChangesLocal (BuildingType, SpecialistType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'SPECIALIST_ENGINEER', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'SPECIALIST_SCIENTIST', 'YIELD_FOOD', 2;
	
INSERT	INTO Building_YieldFromUnitProduction (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 10;
	
INSERT	INTO Building_YieldFromTech (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_GOLD', 20  UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_PRODUCTION', 20;
	
INSERT INTO Building_YieldFromInternalTREnd (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 100;

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_CULTURE', 10 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_GROWTH', 20 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_GREAT_PEOPLE', 5 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'FLAVOR_INFRASTRUCTURE', 20 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'FLAVOR_PRODUCTION', 5 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_CITY_DEFENSE', 10 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_EXPANSION', 5 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_MILITARY_TRAINING', 15 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_OFFENSE', 20 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_RELIGION', 20 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_CULTURE', 10 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_EXPANSION', 5 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_GROWTH', 5 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_RELIGION', 25 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_CULTURE', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_DIPLOMACY', 25 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_GOLD', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_SCIENCE', 5 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'FLAVOR_CULTURE', 25 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'FLAVOR_GREAT_PEOPLE', 20 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_GOLD', 10 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_MILITARY_TRAINING', 30 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_PRODUCTION', 15 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FLAVOR_GROWTH', 25 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FLAVOR_SCIENCE', 30 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_GOLD', 20 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_INFRASTRUCTURE', 30 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_PRODUCTION', 15;
	
INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
	SELECT 'POLICY_COLLECTIVE_RULE', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
	SELECT 'POLICY_CITIZENSHIP', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_GOLDEN_AGE_POINTS', 1 UNION ALL
	SELECT 'POLICY_REPUBLIC', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'POLICY_REPRESENTATION', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'POLICY_MERITOCRACY', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_FOOD', 1;
	
INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
	SELECT 'POLICY_MANDATE_OF_HEAVEN', 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 100;

UPDATE Buildings
SET WLTKDTurns = 10
WHERE Type = 'BUILDING_TCS_PUBLIC_BATHS';

UPDATE	Buildings
SET CityConnectionTradeRouteModifier = 2
WHERE Type = 'BUILDING_TCS_TOWN_COUNCIL';
	
UPDATE Buildings
SET Defense = 300, ExtraCityHitPoints = 50, EnhancedYieldTech = 'TECH_ENGINEERING'
WHERE Type = 'BUILDING_TCS_STRONGHOLD';

UPDATE Buildings
SET FaithCost = 200 --, EmpireSizeModifierReduction = -5
WHERE Type = 'BUILDING_TCS_PAROCHIAL_SCHOOL';

UPDATE Buildings
SET SingleLeagueVotes = 1, CapitalOnly = 1, SpecialistType = 'SPECIALIST_CIVIL_SERVANT', GreatPeopleRateChange = 1
WHERE Type = 'BUILDING_TCS_CHANCERY';	

UPDATE Buildings
SET CitySupplyModifier = 10, Happiness = 1
WHERE Type = 'BUILDING_TCS_DEPOT';