
/*
-- Increasing World Wonder Production costs
UPDATE Defines SET Value = '15' WHERE Name = 'BALANCE_CORE_WORLD_WONDER_SAME_ERA_COST_MODIFIER';
UPDATE Defines SET Value = '10' WHERE Name = 'BALANCE_CORE_WORLD_WONDER_PREVIOUS_ERA_COST_MODIFIER';
UPDATE Defines SET Value = '5'  WHERE Name = 'BALANCE_CORE_WORLD_WONDER_SECOND_PREVIOUS_ERA_COST_MODIFIER';
UPDATE Defines SET Value = '0'  WHERE Name = 'BALANCE_CORE_WORLD_WONDER_EARLIER_ERA_COST_MODIFIER';

-----------------------------------
 --- 원더 설명 변경
----------------------------------

DELETE FROM Language_ko_KR WHERE Tag ='TXT_KEY_WONDER_COST_INCREASE_METRIC';


INSERT INTO Language_ko_KR (Tag, Text)
VALUES 
('TXT_KEY_WONDER_COST_INCREASE_METRIC', '보유한 세계 불가사의로 인한 추가적인 [ICON_PRODUCTION]생산 비용: [COLOR_POSITIVE_TEXT]{1_Num}%[ENDCOLOR][NEWLINE][ICON_PRODUCTION] 다음에서 생산 비용 증가:[NEWLINE][ICON_BULLET] 같은 시대에 건설한 불가사의: [COLOR_POSITIVE_TEXT]15%[ENDCOLOR][NEWLINE][ICON_BULLET] 이전 시대에 건설한 불가사의: [COLOR_POSITIVE_TEXT]10%[ENDCOLOR].[NEWLINE][ICON_BULLET] 2시대 전에 건설한 불가사의: [COLOR_POSITIVE_TEXT]5%[ENDCOLOR][NEWLINE][ICON_BULLET] 참고: 3시대 전의 불가사의나 그보다 더 오래된 불가사의는 비용을 부과하지 않습니다.');

UPDATE Language_ko_KR
SET Text = '보유한 세계 불가사의로 인한 추가적인 [ICON_PRODUCTION]생산 비용: [COLOR_POSITIVE_TEXT]{1_Num}%[ENDCOLOR][NEWLINE][ICON_PRODUCTION] 다음에서 생산 비용 증가:[NEWLINE][ICON_BULLET] 같은 시대에 건설한 불가사의: [COLOR_POSITIVE_TEXT]15%[ENDCOLOR][NEWLINE][ICON_BULLET] 이전 시대에 건설한 불가사의: [COLOR_POSITIVE_TEXT]10%[ENDCOLOR].[NEWLINE][ICON_BULLET] 2시대 전에 건설한 불가사의: [COLOR_POSITIVE_TEXT]5%[ENDCOLOR][NEWLINE][ICON_BULLET] 참고: 3시대 전의 불가사의나 그보다 더 오래된 불가사의는 비용을 부과하지 않습니다.'
WHERE Tag = 'TXT_KEY_WONDER_COST_INCREASE_METRIC';

*/