-- futurism's great work buff is very minor. I have 30 great works so its 60 culture (nothing)
INSERT INTO Policy_GreatWorkYieldChanges
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_FUTURISM', 'YIELD_PRODUCTION', 2),
	('POLICY_FUTURISM', 'YIELD_TOURISM', 2);

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Futurism[ENDCOLOR]: Strengthens [ICON_TOURISM] Tourism of [COLOR_POSITIVE_TEXT]Historic Events[ENDCOLOR] generated by the Palace. +2 [ICON_PRODUCTION] Production, [ICON_CULTURE] Culture, and [ICON_TOURISM] Tourism from Great Works. Earn 50 [ICON_TOURISM] Tourism when you conquer a city for the first time, scaling with Era and city size.'
WHERE Tag = 'TXT_KEY_POLICY_FUTURISM_HELP';

-- new world order. want to use name elsewhere so revert name change here
-- can keep some of the xenophobic overtones with slight name adjustment without undermining gameplay effect

UPDATE Language_en_US
SET Text = 'Secure Borders'
WHERE Tag = 'TXT_KEY_POLICY_FORTIFIED_BORDERS';

-- i will add mine field because of the... implication
-- if new buildings are added we can change constable to something more modern, like penitentiary
DELETE FROM Policy_BuildingClassYieldChanges WHERE PolicyType = 'POLICY_FORTIFIED_BORDERS';
INSERT INTO Policy_BuildingClassYieldChanges
	(PolicyType, BuildingClassType, YieldType, YieldChange)
VALUES
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_CONSTABLE', 'YIELD_PRODUCTION', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_CONSTABLE', 'YIELD_TOURISM', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_CONSTABLE', 'YIELD_CULTURE', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_POLICE_STATION', 'YIELD_PRODUCTION', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_POLICE_STATION', 'YIELD_TOURISM', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_POLICE_STATION', 'YIELD_CULTURE', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_MINEFIELD', 'YIELD_PRODUCTION', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_MINEFIELD', 'YIELD_TOURISM', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_MINEFIELD', 'YIELD_CULTURE', 3);

INSERT INTO Policy_BuildingClassProductionModifiers
	(PolicyType, BuildingClassType, ProductionModifier)
VALUES
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_MINEFIELD', 100);

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Secure Borders[ENDCOLOR]: -2 [ICON_HAPPINESS_3] Unhappiness from [ICON_FOOD] and [ICON_PRODUCTION] Distress in all Cities. Gain +100% [ICON_PRODUCTION] Production towards Constabularies, Mine Fields, and Police Stations. These Buildings produce +3 [ICON_PRODUCTION] Production, [ICON_CULTURE] Culture and [ICON_TOURISM] Tourism.'
WHERE Tag = 'TXT_KEY_POLICY_FORTIFIED_BORDERS_HELP';

UPDATE Language_en_US
SET Text = 'Border control comprises measures taken by governments to monitor and regulate the movement of people, animals, and goods across land, air, and maritime borders, and has its origins in antiquity. However, even following the adoption of measures such as the White Australia Policy and the Chinese Exclusion Act in the 1800s, pervasive control of international borders remained a relatively rare phenomenon until World War I, when European governments introduced border passport requirements for security reasons, and to control the emigration of people with useful skills. These controls remained in place after the war, becoming a standard, though controversial, procedure. British tourists of the 1920s complained, especially about attached photographs and physical descriptions, which they considered led to a "nasty dehumanisation". Decolonisation during the twentieth century saw the emergence of mass emigration from nations in the Global South, thus leading former colonial occupiers to introduce stricter border controls. Although today''s world raises new challenges for border control to address, such as biosecurity and the threat of pandemics, the political discourse around border control remains a right-wing stomping ground closely associated with race relations.'
WHERE Tag = 'TXT_KEY_POLICY_FORTIFIED_BORDERS_TEXT';


-- Lebensraum. remove unbalaceable nightmare that is citadel boost. give border growth yields

UPDATE Policies
SET
	CultureBombBoost = 0
WHERE Type = 'POLICY_INDUSTRIAL_ESPIONAGE';

INSERT INTO Policy_YieldFromKills
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_INDUSTRIAL_ESPIONAGE', 'YIELD_CULTURE_LOCAL', 250);

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Lebensraum[ENDCOLOR]: Receive 10 [ICON_CULTURE] Culture and [ICON_GOLDEN_AGE] Golden Age Points when your borders expand, scaling with Era. Receive [ICON_CULTURE_LOCAL] Border Growth Points when you kill a Unit equal to 250% of its [ICON_STRENGTH] Strength.'
WHERE Tag = 'TXT_KEY_POLICY_INDUSTRIAL_ESPIONAGE_HELP';

-- police state. too much overlap with foritifed borders, spy effect doesnt make sense since you arent going for sci victory. redesign

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Police State[ENDCOLOR]: The [ICON_CAPITAL] Capital gains +6% [ICON_TOURISM] Tourism for every 100 [ICON_SPY_POINT] Spy Points ever accumulated (up to 30%). +3 [ICON_HAPPINESS_1] Local Happiness from every Police Station. -25% Yield penalties for [ICON_PUPPET] Puppeted Cities.'
WHERE Tag = 'TXT_KEY_POLICY_POLICE_STATE_HELP';

DELETE FROM Policy_BuildingClassSecurityChanges WHERE PolicyType = 'POLICY_POLICE_STATE';

DELETE FROM Policy_BuildingClassProductionModifiers WHERE PolicyType = 'POLICY_POLICE_STATE';

-- tall benefit to keep pumping everything out from capital
INSERT INTO Policy_YieldModifierFromActiveSpies
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_POLICE_STATE', 'YIELD_TOURISM', 6);

UPDATE Policies
SET PuppetYieldPenaltyMod = 25
WHERE Type = 'POLICY_POLICE_STATE';

UPDATE Policy_BuildingClassHappiness SET BuildingClassType='BUILDINGCLASS_POLICE_STATION' WHERE PolicyType='POLICY_POLICE_STATE';
-- keeps synergy with t1 police

-- third alternative. strategic effect is too strong and simplifying. lower and add additional effect.
-- tbh does the third alternative even exist lol. it's either looting or colonialism 

UPDATE Policies
SET StrategicResourceMod = 50
WHERE Type = 'POLICY_THIRD_ALTERNATIVE';

INSERT INTO Policy_YieldModifierFromGreatWorks
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_THIRD_ALTERNATIVE', 'YIELD_GOLD', 2),
	('POLICY_THIRD_ALTERNATIVE', 'YIELD_CULTURE', 2);

UPDATE Language_en_US
SET Text = 'New Order'
WHERE Tag = 'TXT_KEY_POLICY_THIRD_ALTERNATIVE';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]New Order[ENDCOLOR]: Quantity of [COLOR_POSITIVE_TEXT]Strategic Resources[ENDCOLOR] produced is increased by 50%. Reduces Unit [ICON_GOLD] Gold Maintenance costs by 25%. Cities generate +2% [ICON_GOLD] Gold and [ICON_CULTURE] Culture for every [ICON_GREAT_WORK] Great Work present (up to 20%).'
WHERE Tag = 'TXT_KEY_POLICY_THIRD_ALTERNATIVE_HELP';

UPDATE Language_en_US
SET Text = 'The New Order of Europe was the political and social system that Nazi Germany wanted to impose on the areas of Europe that it conquered and occupied. According to the Nazi government, the goal was to secure a fair rearrangement of territory for the common benefit of a new, economically integrated Europe and, later, world peace through complete and uncontested military supremacy. In practice, to the extent it was able to be enacted, it meant a rigid racial heirarchy, forced labour, martial law, and the looting of art and other cultural artifacts to be transferred back to the Fatherland.'
WHERE Tag = 'TXT_KEY_POLICY_THIRD_ALTERNATIVE_TEXT';

-- mare nostrum. a little bit weak, add some Tourism that we are lacking

INSERT INTO Policy_ImprovementYieldChanges
	(PolicyType, ImprovementType, YieldType, Yield)
VALUES
	('POLICY_NATIONALISM', 'IMPROVEMENT_OFFSHORE_PLATFORM', 'YIELD_TOURISM', 2),
	('POLICY_NATIONALISM', 'IMPROVEMENT_FISHING_BOATS', 'YIELD_TOURISM', 2);

INSERT INTO Policy_FeatureYieldChanges
	(PolicyType, FeatureType, YieldType, Yield)
VALUES
	('POLICY_NATIONALISM', 'FEATURE_ATOLL', 'YIELD_TOURISM', 2);

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Mare Nostrum[ENDCOLOR]: +1 [ICON_RES_OIL] Oil and [ICON_RES_COAL] Coal for every [ICON_CITY_STATE] City-State [COLOR_CYAN]Ally[ENDCOLOR]. +2 [ICON_PRODUCTION] Production, [ICON_CULTURE] Culture, and [ICON_TOURISM] Tourism to Atolls, Fishing Boats, and Offshore Platforms. Naval Ranged Units gain the [COLOR_POSITIVE_TEXT]Mare Nostrum[ENDCOLOR] Promotion.'
WHERE Tag = 'TXT_KEY_POLICY_NATIONALISM_HELP';

-- syndicalism. name is weird and civilopedia text is weirder. 

UPDATE Language_en_US
SET Text = 'Third Position'
WHERE Tag = 'TXT_KEY_POLICY_INFILTRATION';
-- unhelpful I know

UPDATE Policy_BuildingClassYieldChanges SET
YieldChange = 5
WHERE PolicyType = 'POLICY_INFILTRATION';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Third Position[ENDCOLOR]: [ICON_FRANCHISE] Corporate Franchises count double in the Cities of Civilizations you are at least [COLOR_MAGENTA]Popular[ENDCOLOR] with, and this does not count for your Global Franchise maximum. Can establish 5 additional [ICON_FRANCHISE] Franchises in foreign Cities. +5 [ICON_PRODUCTION] Production from all [ICON_OFFICE] Corporate Offices.'
WHERE Tag = 'TXT_KEY_POLICY_INFILTRATION_HELP';

UPDATE Language_en_US
SET Text = 'The Third Alternative, or Third Position, is a nationalist political philosophy that emphasizes its opposition to both capitalism and communism, instead synthesizing radical ideas from both. Those following this approach favor state ownership of production and the distribution of goods and services to "the productive members of society," peaceful segregation of ethnic and racial groups within the state, and have recently embraced radical environmentalism. Many political scientists have argued that the movement, which arose in the wake of World War II in countries such as Argentina and South Africa, is not a third alternative, but rather a mutation of neo-fascism and ultra-nationalism.'
WHERE Tag = 'TXT_KEY_POLICY_INFILTRATION_TEXT';

--if we are talking about right wing unions then lets do that
--UPDATE Language_en_US
--SET Text = 'Trade unionism is most closely associated with socialist and communist politics, but throughout the modern era nationalistic forms of syndicalism have also existed. A "Closed Shop" refers to a company whose workers all belong to the same union, and must belong to that union. In Britain such situations existed even in the Victorian era, and were a powerful tool used to enforce the social norms of the working class on its members, by its members. Often such norms reflected the highly conservative--rather than liberal--opinions of the population, including (but not limited to) racial politics. For example, it was common for ethnic minorities to be ineligible to join a closed shop union, and therefore unable to work in that particular industry in that particular place.'
--WHERE Tag = 'TXT_KEY_POLICY_INFILTRATION_TEXT';

-- cult of personality, replace AI unfriendly and weird tourism boost 
UPDATE Policies
SET
	PositiveWarScoreTourismMod = 0,
	NumFreeGreatPeople = 1,
	IncludesOneShotFreeUnits = 1
WHERE Type = 'POLICY_CULT_PERSONALITY';

INSERT INTO Policy_YieldFromKills
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_CULT_PERSONALITY', 'YIELD_TOURISM', 250);

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Cult of Personality[ENDCOLOR]: +50% Tourism [ICON_TOURISM] to civilizations fighting a common enemy. Receive [ICON_TOURISM] Tourism when you kill a Unit equal to 250% of its [ICON_STRENGTH] Strength. A [ICON_GREAT_PEOPLE] Great Person of your choice appears near your [ICON_CAPITAL] Capital.'
WHERE Tag = 'TXT_KEY_POLICY_CULT_PERSONALITY_HELP';

--below are just text fixes/updates

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Iron Fist[ENDCOLOR]: Capitulated [ICON_OCCUPIED] Vassals cannot rebel. Vassals may not be liberated, and tribute an additional 25% of their yields and [ICON_HAPPINESS_1] excess Happiness. Yields from [ICON_CITY_STATE] City-States increased by 25%. +50% [ICON_WORKER] Work Rate.'
WHERE Tag = 'TXT_KEY_POLICY_UNIVERSAL_HEALTHCARE_A_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Elite Forces[ENDCOLOR]: Newly created Military Units receive [COLOR_POSITIVE_TEXT]+15[ENDCOLOR] Experience. Military Units gain [COLOR_POSITIVE_TEXT]50% more[ENDCOLOR] Experience from combat.'
WHERE Tag = 'TXT_KEY_POLICY_ELITE_FORCES_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Total War[ENDCOLOR]: +25% [ICON_PRODUCTION] Production when training Land Units. Warscore increases 25% more quickly, and it is 25% easier to [ICON_PIRATE] Bully City-States.'
WHERE Tag = 'TXT_KEY_POLICY_TOTAL_WAR_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Co-Prosperity Sphere[ENDCOLOR]: Demanding [ICON_PIRATE] Tribute from City-States no longer reduces [ICON_INFLUENCE] Influence, revokes Quests, or cancels Pledges of Protection. Doing so decreases the [ICON_INFLUENCE] Influence of all other Civs with the bullied City-State by 10%, and increases your [ICON_INFLUENCE] Influence by 10%.'
WHERE Tag = 'TXT_KEY_POLICY_GUNBOAT_DIPLOMACY_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Air Supremacy[ENDCOLOR]: Receive a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Airport in every City. +25% [ICON_PRODUCTION] Production when training Air Units. Can build [COLOR_YELLOW]Zeroes[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_POLICY_MILITARISM_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Futurism[ENDCOLOR]: Strengthens [ICON_TOURISM] Tourism of [COLOR_POSITIVE_TEXT]Historic Events[ENDCOLOR] generated by the Palace. +2 [ICON_CULTURE] Culture from [ICON_GREAT_WORK] Great Works. Earn 50 [ICON_TOURISM] Tourism when you conquer a city for the first time, scaling with Era and City size.'
WHERE Tag = 'TXT_KEY_POLICY_FUTURISM_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Military-Industrial Complex[ENDCOLOR]: -33% [ICON_GOLD] Gold cost of Purchasing Units. +3 [ICON_RESEARCH] Science from [ICON_STRENGTH] Defense Buildings, Citadels, Forts, and Unique Improvements.'
WHERE Tag = 'TXT_KEY_POLICY_MOBILIZATION_HELP';




