-- ========================================
-- songhai UA so civilians get movement too
-- ========================================
INSERT INTO Trait_FreePromotionUnitCombats
	(TraitType, PromotionType, UnitCombatType)
VALUES
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_SETTLER'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_WORKER'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_CARAVAN'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_MISSIONARY'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_INQUISITOR'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_DIPLOMACY'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_AMPHIBIOUS', 'UNITCOMBAT_ARCHAEOLOGIST'),

	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_SETTLER'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_WORKER'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_CARAVAN'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_MISSIONARY'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_INQUISITOR'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_DIPLOMACY'),
	('TRAIT_AMPHIB_WARLORD', 'PROMOTION_WAR_CANOES', 'UNITCOMBAT_ARCHAEOLOGIST');

UPDATE Language_en_US SET
Text = 'Sewn Canoes'
WHERE Tag = 'TXT_KEY_PROMOTION_WAR_CANOES';