/*
UCS compatibility patch!
0 = Disabled disregarding if its detects UCS by Enginseer.
1 = Enabled if it detects the UCS by Enginseer.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('COLORS-UCS', 	2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'COLORS-UCS' AND EXISTS (SELECT * FROM MinorCivilizations WHERE Type='MINOR_CIV_HONDURAS') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 0);

-- Main Compatibility Code
	-- defining new color schemes for minors
    INSERT INTO Colors 
				(Type, 									Red, 		Green, 		Blue, 		Alpha)
	-- Maritime
	SELECT		'COLOR_PLAYER_MINOR_ADEJE',	    		0.4,		0.6,		0,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_AUCKLAND',			0.020,		0.424,		0.207,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CHEVAK',			0.4,		0.8,		0,			1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DJIBOUTI',			0.478,		0.898,		0.172,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_HONIARA',			0.549,		0.722,		0,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_IRUNEA',			0.859,		0.941,		0.161,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_JETARKTE',			0.561,		0.592,		0.475,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_JUYUBIT',			0.004,		0.914,		0.730,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MENDYARRUP',		0.6,		0.8,		0,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SGANG_GWAAY',		0.749,		0.217,		0.059,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TAIWAN',			0.875,		0.941,		0.729,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Mercantile
	SELECT		'COLOR_PLAYER_MINOR_AL_TIRABIN',		1,			0.894,		0.769,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DODOMA',			0.937,		0.851,		0.015,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DOUALA',			0.81,		0.79,		0.11,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_HANUABADA',	    	0.863,		0.765,		0.039,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_HONDURAS',			1,			0.663,		0.176,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MUISCA',			1,			0.767,		0.420,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MUSCAT',			1,			0.969,		0.282,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_OC_EO',	    		0.788,		0.8,		0.282,		1		WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_OUIDAH',			0.91,		0.714,		0.494,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_PHANOTEUS',			0.992,		0.607,		0.337,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_QUELIMANE',			1,			0.415,		0,			1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SANAA',				0.91,		0.784,		0.596,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SANTO_DOMINGO',		1,			0.835,		0.588,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TUNIS',				0.514,		0.439,		0.149,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Militaristic
	SELECT		'COLOR_PLAYER_MINOR_AMBRACIA',			0.749,		0.078,		0.106,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_BALKH',	    		0.894,	    0.420,		0.325,    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CLERMONT',			0.905,		0.153,		0.153,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DAKKAR',			0.776,		0.447,		0.294,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_FAYA',				0.588,		0.369,		0.082,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_GRANADA',			1,			0.365,		0.365,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KIGALI',			1,			0.106,		0.106,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_LACONIA',			0.521,		0.157,		0.157,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_LEVUKA',			0.925,		0.231,		0.231,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_LONGYAN',			0.784,	    0.298,		0.102,	   	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MBABANE',			1,			0.835,		0.804,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_ODENSO',			0.627,		0.455,		0.227,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_PALMYRA',			0.702,	   	0.412,		0.412,	   	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_PELYM',		    	0.722,		0.361,		0,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_POKROVKA',			0.89,    	0.663,		0.6,	    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SURREY',			1,			0.341,		0.227,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TBILISI',			0.6,		0,		    0,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_WOOTEI_NIICIE',		0.4,		0,	    	0.2,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
		
	-- Cultured
	SELECT		'COLOR_PLAYER_MINOR_ANANGULA',			0.737,		0.655,		0.910,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_ANDORRA',			1,	    	0.4,		0.6,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_AYUTTHAYA',			0.439,		0.188,		0.627,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_GWYNEDD',			0.8,		0.475,		0.780,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KARASJOHKA',		0.612,		0.525,		0.686,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KATENDE',			0.8,		0,		    0.8,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MANAGUA',			0.518,		0.035,		0.372,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_NAN_MADOL',			0.8,		0.474,		0.780,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_NYARYANA_MARQ',		0.996,	   	0,	    	0.733,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SIERRA_LEONE',		0.596,		0.345,		0.894,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_THIMPHU',			0.824,		0.29,		0.596,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Religious
	SELECT		'COLOR_PLAYER_MINOR_ARMAGH',			0.184,		0.824,		0.776,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_BAGAN',	    		0,	    	0.6,		0.6,    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_BEDULU',			0.4,		1,		    1,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CANOSSA',			0,	    	0.6,		0.8,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DALI',				0,	    	0.4,		1,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DANO',				0.2,		0.6,		1,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_ISKANWAYA',			0.557,		0.663,		0.859,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KARYES',			0.376,		0.427,		0.902,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_LAHORE',			0.8,		0.925,		1,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MULTAN',			0.2,	   	0.2,		0.8,	   	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MUTITJULU',			0.4,	    0.8,		1,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_RISHIKESH',			0.2,	   	0.4,		0.6,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SADDARVAZEH',		0.306,		0.769,		0.878,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SARNATH',			0.616,		0.816,		0.906,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SUCEAVA',			0.294,		0.612,		0.827,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TIWANAKU',			0,  		0.8,		1,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_YANGCHENG',			0.227,		0.667,		0.671,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) /*UNION ALL
		
	
	
	SELECT		'COLOR_PLAYER_MINOR_ISHIYAMA',			0.569,		0.639,		0.690,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	SELECT		'COLOR_PLAYER_MINOR_YAIUWA',			0.6,		0.6,		1,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SHAHRAZUR',			0.831,		0.451,		0.831,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	SELECT		'COLOR_PLAYER_MINOR_ASMARA',			0.639,	   	1,	    	0.82,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_BALLEY_CHASHTAL',	0.086,		0.557,		0.463,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CARAL',		    	0.6,	   	1,		    0.4,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DAKAR',				0.576,		0.773,		0.447,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KAGYRGYN',			0,		    1,		    0.6,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KARIATEBIKE',		0.227,		0.325,		0.067,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MADURAI',			0.337,		0.510,		0.012,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_OKAK',				0.675,		0.882,		0.686,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_REYKJAVIK',			0,	    	0.8,		0.6,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SKARA_BRAE',		0.251,		0.847,		0.392,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_???TULA',			0,			0.459,		0.369,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_???MBABANE',		0.792,		0.878,		0.051,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	SELECT		'COLOR_PLAYER_MINOR_ABALESSA',			0.878,		0.596,		0.165,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_AZEBA',				0.769,		0.569,		0.008,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_GABORONE',			0.925,		0.345,		0,			1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_HANTHAWADDY',		0.929,		0.569,		0.129,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_LUXEMBOURG',		0.933,		0.910,		0.667,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_NYENI',				0.612,		0.506,		0.110,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_OUAGADOUGOU',		0.808,		0.796,		0.486,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_POMBERUK',			0.855,		0.647,		0.125,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_UGARIT',			1,	    	1,	    	0.231,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	SELECT		'COLOR_PLAYER_MINOR_DIEGO_GARCIA',		0.925,		0.643,		0.584,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_GUNGNAE',			0.6,	   	0.2,		0,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MACACO',			0.541,		0.200,		0.141,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MANTHIMBA',			1,	   	    0.475,		0.486,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_ORISTANO',			0.980,		0.502,		0.447,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_PONTOTOC',			0.753,		0.251,		0,			1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_PURUKCAHU',			0.651,		0.482,		0.357,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SCODRA',			0.698,		0.133,		0.133,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TETOUAN',			0.475,		0.267,		0.231,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TILANTONGO',		0.647,		0.165,		0.165,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_VAITAPE',			0.4,		0.2,		0,		    1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_VALJALA',			0.855,		0.173,		0.263,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_WAITIKUBULI',		1,	    	0.608,		0.616,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	SELECT		'COLOR_PLAYER_MINOR_CARARIES',			0.867,		0.627,		0.867,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KITCISIPIRINIK',	0.533,		0,			0.522,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_KOKAND',			0.424,		0.188,		0.510,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MOHENJO_DARO',		1,	   	    0.773,		1,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MUTAWAYNATJI',		0.949,		0.757,		0.820,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_NGAZARGAMU',		0.698,		0.518,		0.745,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SHAMAKHI',			0.922,		0.049,		0.922		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_THABA_BOSIU',		0.788,	   	0.376,		0.871,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_VADUZ',		    	0.741,		0.741,		1,  		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_VICTORIA',			0.604,		0.173,		0.627,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TULA',				0.78,		0.082,		0522,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	SELECT		'COLOR_PLAYER_MINOR_AVI_KWA_AME',		0.412,		0.412,		0.714,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CAHUACHI',			0.537,		0.812,		0.941,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CAIRO',				0.122,		0.718,		0.718,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_CAMUTINS',			0.941,		0.973,		1,			1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_DONGOLA',			0.106,	   	0.859,		0.898,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_GONDAR',			0.063,		0.204,		0.651,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_GROZNY',			0.4,		0.6,		0.8,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_MATONJENI',			0.2,	   	0.2,		1,	    	1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_SOMBAKE',			0.506,		0.847,		0.816,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_TURA',				0.392,		0.584,		0.929,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'COLOR_PLAYER_MINOR_YIRRKALA',			0.6,	   	0.6,		0.6,		1       WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	*/;
	
	-- defining whole minor schemes
    INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	-- Maritime
	SELECT		'PLAYERCOLOR_MINOR_ADEJE',	    	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ADEJE',	    	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_AUCKLAND',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_AUCKLAND',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_CHEVAK',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_CHEVAK',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_DJIBOUTI',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DJIBOUTI',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_HONIARA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_HONIARA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_IRUNEA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_IRUNEA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_JETARKTE',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_JETARKTE',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_JUYUBIT',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_JUYUBIT',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MENDYARRUP',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MENDYARRUP',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SGANG_GWAAY',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SGANG_GWAAY',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_TAIWAN',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_TAIWAN',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Mercantile
	SELECT		'PLAYERCOLOR_MINOR_AL_TIRABIN',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_AL_TIRABIN',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_DODOMA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DODOMA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_DOUALA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DOUALA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_HANUABADA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_HANUABADA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_HONDURAS',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_HONDURAS',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MANAGUA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MANAGUA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MUISCA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MUISCA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MUSCAT',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MUSCAT',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_OC_EO',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_OC_EO',	    	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_OUIDAH',		    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_OUIDAH',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_PHANOTEUS',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_PHANOTEUS',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_QUELIMANE',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_QUELIMANE',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SANAA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SANAA',			'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SANTO_DOMINGO',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SANTO_DOMINGO',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_TUNIS',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_TUNIS',			'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Militaristic
	SELECT		'PLAYERCOLOR_MINOR_AMBRACIA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_AMBRACIA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_CLERMONT',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_CLERMONT',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_DAKKAR',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DAKKAR',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_FAYA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_FAYA',			'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_GRANADA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_GRANADA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_KIGALI',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_KIGALI',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_LACONIA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_LACONIA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_LEVUKA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_LEVUKA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_LONGYAN',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_LONGYAN',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MBABANE',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MBABANE',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_ODENSO',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ODENSO',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_PALMYRA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_PALMYRA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_PELYM',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_PELYM',		    'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_POKROVKA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_POKROVKA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SURREY',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SURREY',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_TBILISI',	    'COLOR_PLAYER_MINOR_ICON',	    'COLOR_PLAYER_MINOR_TBILISI',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_WOOTEI_NIICIE',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_WOOTEI_NIICIE',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Cultured
	SELECT		'PLAYERCOLOR_MINOR_ANANGULA',	    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ANANGULA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_ANDORRA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ANDORRA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
    SELECT		'PLAYERCOLOR_MINOR_AYUTTHAYA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_AYUTTHAYA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
    SELECT		'PLAYERCOLOR_MINOR_GWYNEDD',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_GWYNEDD',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_KARASJOHKA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_KARASJOHKA',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_KATENDE',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_KATENDE',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_NAN_MADOL',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_NAN_MADOL',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_NYARYANA_MARQ',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_NYARYANA_MARQ',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SIERRA_LEONE',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SIERRA_LEONE',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_THIMPHU',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_THIMPHU',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	
	-- Religious
	SELECT		'PLAYERCOLOR_MINOR_ARMAGH',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ARMAGH',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_BAGAN',		    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_BAGAN',		    'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_BALKH',		    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_BALKH',		    'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_BEDULU',	    	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_BEDULU',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_CANOSSA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_CANOSSA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_DALI',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DALI',			'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_DANO',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DANO',			'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_ISKANWAYA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ISKANWAYA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_KARYES',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_KARYES',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_LAHORE',		    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_LAHORE',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MULTAN',		    'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MULTAN',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_MUTITJULU',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MUTITJULU',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_RISHIKESH',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_RISHIKESH',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SADDARVAZEH',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SADDARVAZEH',	'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SARNATH',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SARNATH',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SUCEAVA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SUCEAVA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_TIWANAKU',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_TIWANAKU',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_YANGCHENG',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_YANGCHENG',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) /*UNION ALL
	
	
	SELECT		'PLAYERCOLOR_MINOR_YAIUWA',	    	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_YAIUWA',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL
	SELECT		'PLAYERCOLOR_MINOR_SHAHRAZUR',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SHAHRAZUR',		'COLOR_PLAYER_PEACH_TEXT'   WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1) UNION ALL	
	*/;
	
	-- updating color scheme for minor civs
	-- Maritime
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ADEJE' WHERE Type = 'MINOR_CIV_ADEJE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_AUCKLAND' WHERE Type = 'MINOR_CIV_AUCKLAND' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CHEVAK' WHERE Type = 'MINOR_CIV_CHEVAK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DJIBOUTI' WHERE Type = 'MINOR_CIV_DJIBOUTI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_HONIARA' WHERE Type = 'MINOR_CIV_HONIARA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_IRUNEA' WHERE Type = 'MINOR_CIV_IRUNEA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_JETARKTE' WHERE Type = 'MINOR_CIV_JETARKTE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_JUYUBIT' WHERE Type = 'MINOR_CIV_JUYUBIT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MENDYARRUP' WHERE Type = 'MINOR_CIV_MENDYARRUP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SGANG_GWAAY' WHERE Type = 'MINOR_CIV_ST_SGANG_GWAAY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_TAIWAN' WHERE Type = 'MINOR_CIV_TAIWAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- Mercantile
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_AL_TIRABIN' WHERE Type = 'MINOR_CIV_AL_TIRABIN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DODOMA' WHERE Type = 'MINOR_CIV_DODOMA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DOUALA' WHERE Type = 'MINOR_CIV_DOUALA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_HANUABADA' WHERE Type = 'MINOR_CIV_HANUABADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_HONDURAS' WHERE Type = 'MINOR_CIV_HONDURAS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MANAGUA' WHERE Type = 'MINOR_CIV_MANAGUA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MUISCA' WHERE Type = 'MINOR_CIV_MUISCA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MUSCAT' WHERE Type = 'MINOR_CIV_MUSCAT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_OC_EO' WHERE Type = 'MINOR_CIV_OC_EO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_OUIDAH' WHERE Type = 'MINOR_CIV_OUIDAH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PHANOTEUS' WHERE Type = 'MINOR_CIV_PHANOTEUS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_QUELIMANE' WHERE Type = 'MINOR_CIV_QUELIMANE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SANAA' WHERE Type = 'MINOR_CIV_SANAA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SANTO_DOMINGO' WHERE Type = 'MINOR_CIV_SANTO_DOMINGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_TUNIS' WHERE Type = 'MINOR_CIV_TUNIS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- Militaristic
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_AMBRACIA' WHERE Type = 'MINOR_CIV_AMBRACIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CLERMONT' WHERE Type = 'MINOR_CIV_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DAKKAR' WHERE Type = 'MINOR_CIV_DAKKAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_FAYA' WHERE Type = 'MINOR_CIV_FAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_GRANADA' WHERE Type = 'MINOR_CIV_GRANADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KIGALI' WHERE Type = 'MINOR_CIV_KIGALI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_LACONIA' WHERE Type = 'MINOR_CIV_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_LEVUKA' WHERE Type = 'MINOR_CIV_LEVUKA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_LONGYAN' WHERE Type = 'MINOR_CIV_LONGYAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MBABANE' WHERE Type = 'MINOR_CIV_MBABANE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ODENSO' WHERE Type = 'MINOR_CIV_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PALMYRA' WHERE Type = 'MINOR_CIV_PALMYRA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PELYM' WHERE Type = 'MINOR_CIV_PELYM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_POKROVKA' WHERE Type = 'MINOR_CIV_POKROVKA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SURREY' WHERE Type = 'MINOR_CIV_SURREY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_TBILISI' WHERE Type = 'MINOR_CIV_TBILISI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_WOOTEI_NIICIE' WHERE Type = 'MINOR_CIV_WOOTEI_NIICIE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- Cultured
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ANANGULA' WHERE Type = 'MINOR_CIV_ANANGULA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ANDORRA' WHERE Type = 'MINOR_CIV_ANDORRA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_AYUTTHAYA' WHERE Type = 'MINOR_CIV_AYUTTHAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_GWYNEDD' WHERE Type = 'MINOR_CIV_GWYNEDD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KARASJOHKA' WHERE Type = 'MINOR_CIV_KARASJOHKA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KATENDE' WHERE Type = 'MINOR_CIV_KATENDE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_NAN_MADOL' WHERE Type = 'MINOR_CIV_NAN_MADOL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_NYARYANA_MARQ' WHERE Type = 'MINOR_CIV_NYARYANA_MARQ' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SIERRA_LEONE' WHERE Type = 'MINOR_CIV_SIERRA_LEONE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_THIMPHU' WHERE Type = 'MINOR_CIV_THIMPHU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- Religious
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ARMAGH' WHERE Type = 'MINOR_CIV_ARMAGH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BAGAN' WHERE Type = 'MINOR_CIV_BAGAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BALKH' WHERE Type = 'MINOR_CIV_BALKH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BEDULU' WHERE Type = 'MINOR_CIV_BEDULU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CANOSSA' WHERE Type = 'MINOR_CIV_CANOSSA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DALI' WHERE Type = 'MINOR_CIV_DALI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DANO' WHERE Type = 'MINOR_CIV_DANO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ISKANWAYA' WHERE Type = 'MINOR_CIV_ISKANWAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KARYES' WHERE Type = 'MINOR_CIV_KARYES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_LAHORE' WHERE Type = 'MINOR_CIV_LAHORE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MULTAN' WHERE Type = 'MINOR_CIV_MULTAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MUTITJULU' WHERE Type = 'MINOR_CIV_MUTITJULU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_RISHIKESH' WHERE Type = 'MINOR_CIV_RISHIKESH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SADDARVAZEH' WHERE Type = 'MINOR_CIV_SADDARVAZEH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SARNATH' WHERE Type = 'MINOR_CIV_SARNATH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SUCEAVA' WHERE Type = 'MINOR_CIV_SUCEAVA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_TIWANAKU' WHERE Type = 'MINOR_CIV_TIWANAKU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_YANGCHENG' WHERE Type = 'MINOR_CIV_YANGCHENG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	/*
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_YAIUWA' WHERE Type = 'MINOR_CIV_YAIUWA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SHAHRAZUR' WHERE Type = 'MINOR_CIV_SHAHRAZUR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	*/