--==========================================================================================================================
-- GAME OPTIONS
--==========================================================================================================================
-- Civilizations_YnAEMP
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO GameOptions
		(Type,										Description,								Help,											'Default',	Visible,	SupportsSinglePlayer,	SupportsMultiplayer,	IsMapOption)
VALUES	('GAMEOPTION_CULTURE_JFD_ALL',				'TXT_KEY_GAME_OPTION_JFD_ALL',				'TXT_KEY_GAME_OPTION_JFD_ALL_HELP',				0,			0,			1,						1,						0),
		('GAMEOPTION_CULTURE_JFD_ABORIGINAL',		'TXT_KEY_GAME_OPTION_JFD_ABORIGINAL',		'TXT_KEY_GAME_OPTION_JFD_ABORIGINAL_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_ANDEAN',			'TXT_KEY_GAME_OPTION_JFD_ANDEAN',			'TXT_KEY_GAME_OPTION_JFD_ANDEAN_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_BANTU',			'TXT_KEY_GAME_OPTION_JFD_BANTU',			'TXT_KEY_GAME_OPTION_JFD_BANTU_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_BHARATA',			'TXT_KEY_GAME_OPTION_JFD_BHARATA',			'TXT_KEY_GAME_OPTION_JFD_BHARATA_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_CENTRAL',			'TXT_KEY_GAME_OPTION_JFD_CENTRAL',			'TXT_KEY_GAME_OPTION_JFD_CENTRAL_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_CLASSICAL',		'TXT_KEY_GAME_OPTION_JFD_CLASSICAL',		'TXT_KEY_GAME_OPTION_JFD_CLASSICAL_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_COLONIAL',			'TXT_KEY_GAME_OPTION_JFD_COLONIAL',			'TXT_KEY_GAME_OPTION_JFD_COLONIAL_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_EASTERN',			'TXT_KEY_GAME_OPTION_JFD_EASTERN',			'TXT_KEY_GAME_OPTION_JFD_EASTERN_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_EAST_INDIES',		'TXT_KEY_GAME_OPTION_JFD_EAST_INDIES',		'TXT_KEY_GAME_OPTION_JFD_EAST_INDIES_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_GREAT_PLAINS',		'TXT_KEY_GAME_OPTION_JFD_GREAT_PLAINS',		'TXT_KEY_GAME_OPTION_JFD_GREAT_PLAINS_HELP',	1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_HIMALAYAN',		'TXT_KEY_GAME_OPTION_JFD_HIMALAYAN',		'TXT_KEY_GAME_OPTION_JFD_HIMALAYAN_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_IRANIAN',			'TXT_KEY_GAME_OPTION_JFD_IRANIAN',			'TXT_KEY_GAME_OPTION_JFD_IRANIAN_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_ISLAMIC',			'TXT_KEY_GAME_OPTION_JFD_ISLAMIC',			'TXT_KEY_GAME_OPTION_JFD_ISLAMIC_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_KATUJE',			'TXT_KEY_GAME_OPTION_JFD_KATUJE',			'TXT_KEY_GAME_OPTION_JFD_KATUJE_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_MANDALA',			'TXT_KEY_GAME_OPTION_JFD_MANDALA',			'TXT_KEY_GAME_OPTION_JFD_MANDALA_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_MESOAMERICAN',		'TXT_KEY_GAME_OPTION_JFD_MESOAMERICAN',		'TXT_KEY_GAME_OPTION_JFD_MESOAMERICAN_HELP',	1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_MESOPOTAMIC',		'TXT_KEY_GAME_OPTION_JFD_MESOPOTAMIC',		'TXT_KEY_GAME_OPTION_JFD_MESOPOTAMIC_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_NORTHERN',			'TXT_KEY_GAME_OPTION_JFD_NORTHERN',			'TXT_KEY_GAME_OPTION_JFD_NORTHERN_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_OCEANIC',			'TXT_KEY_GAME_OPTION_JFD_OCEANIC',			'TXT_KEY_GAME_OPTION_JFD_OCEANIC_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_ORIENTAL',			'TXT_KEY_GAME_OPTION_JFD_ORIENTAL',			'TXT_KEY_GAME_OPTION_JFD_ORIENTAL_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_PACIFIC',			'TXT_KEY_GAME_OPTION_JFD_PACIFIC',			'TXT_KEY_GAME_OPTION_JFD_PACIFIC_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_POLAR',			'TXT_KEY_GAME_OPTION_JFD_POLAR',			'TXT_KEY_GAME_OPTION_JFD_POLAR_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_SAHARAN',			'TXT_KEY_GAME_OPTION_JFD_SAHARAN',			'TXT_KEY_GAME_OPTION_JFD_SAHARAN_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_SEMITIC',			'TXT_KEY_GAME_OPTION_JFD_SEMITIC',			'TXT_KEY_GAME_OPTION_JFD_SEMITIC_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_SOUTHERN',			'TXT_KEY_GAME_OPTION_JFD_SOUTHERN',			'TXT_KEY_GAME_OPTION_JFD_SOUTHERN_HELP',		1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_STEPPE',			'TXT_KEY_GAME_OPTION_JFD_STEPPE',			'TXT_KEY_GAME_OPTION_JFD_STEPPE_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_TOTALITARIAN',		'TXT_KEY_GAME_OPTION_JFD_TOTALITARIAN',		'TXT_KEY_GAME_OPTION_JFD_TOTALITARIAN_HELP',	1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_WEST_AFRICAN',		'TXT_KEY_GAME_OPTION_JFD_WEST_AFRICAN',		'TXT_KEY_GAME_OPTION_JFD_WEST_AFRICAN_HELP',	1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_WESTERN',			'TXT_KEY_GAME_OPTION_JFD_WESTERN',			'TXT_KEY_GAME_OPTION_JFD_WESTERN_HELP',			1,			1,			1,						1,						1),
		('GAMEOPTION_CULTURE_JFD_WOODLANDS',		'TXT_KEY_GAME_OPTION_JFD_WOODLANDS',		'TXT_KEY_GAME_OPTION_JFD_WOODLANDS_HELP',		1,			1,			1,						1,						1);
--==========================================================================================================================
--==========================================================================================================================