DELETE FROM Unit_FreePromotions
        WHERE PromotionType="PROMOTION_IGNORE_TERRAIN_COST" AND UnitType IN (SELECT Type FROM Units 
        WHERE CombatClass='UNITCOMBAT_RECON');

UPDATE UnitPromotions
SET HillsDoubleMove = 1
WHERE Type = 'PROMOTION_WOODLAND_TRAILBLAZER_3';

UPDATE Language_ko_KR
SET Text = Text||' 습지에서 [ICON_MOVES] 이동력 [COLOR_POSITIVE_TEXT]두 배[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1_HELP';

UPDATE Language_ko_KR
SET Text = Text||' 언덕에서 [ICON_MOVES] 이동력 [COLOR_POSITIVE_TEXT]두 배[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP';

UPDATE UnitPromotions
SET CannotBeChosen = 1
WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';

