----------------------------------------------------------
-- EMR Compatibility
UPDATE Language_ko_KR
SET Text = '[ICON_RES_BEER] Beer, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TRADER_SIDS', 'TXT_KEY_BUILDING_TRADER_SIDS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_CHEESE] Cheese, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_LANDSEA_EXTRACTORS', 'TXT_KEY_BUILDING_LANDSEA_EXTRACTORS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_OBSIDIAN] Obsidian, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_HEXXON_REFINERY', 'TXT_KEY_BUILDING_HEXXON_REFINERY_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_CHAMPAGNE] Champagne, [ICON_RES_LAVENDER] Lavender, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_TIN] Tin, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_FIRAXITE_MATERIALS', 'TXT_KEY_BUILDING_FIRAXITE_MATERIALS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_HONEY] Honey, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_MANUSCRIPTS] Manuscripts, [ICON_RES_PLATINUM] Platinum, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_CIVILIZED_JEWELERS', 'TXT_KEY_BUILDING_CIVILIZED_JEWELERS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_BIRDS_NEST] {TXT_KEY_RESOURCE_BIRDS_NEST}, [ICON_RES_POPPY] Poppy, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_POPULI_MEDICINE', 'TXT_KEY_BUILDING_POPULI_MEDICINE_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER');

---------------------------------------------------
-- now some custom civs
UPDATE Language_ko_KR
SET Text = '[ICON_RES_JAR_WILDLIFE] Wildlife, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_POPULI_MEDICINE', 'TXT_KEY_BUILDING_POPULI_MEDICINE_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_WILDLIFE');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_JAR_YAK] Yak, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_JAR_YAK');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_JAR_BUCCHERO] Bucchero, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_BUCCHERO');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_SHRIMP] Shrimp, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_LANDSEA_EXTRACTORS', 'TXT_KEY_BUILDING_LANDSEA_EXTRACTORS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_SHRIMP');

-------------------------------------------------------
-- camels, feathers, quartz, alpacas
UPDATE Language_ko_KR
SET Text = '[ICON_RES_FEATHERS] Feathers, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_FEATHERS');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_CAMEL] Camel, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_TWOKAY_FOODS', 'TXT_KEY_BUILDING_TWOKAY_FOODS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_CAMEL');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_QUARTZ] Quartz, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_FIRAXITE_MATERIALS', 'TXT_KEY_BUILDING_FIRAXITE_MATERIALS_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_QUARTZ');

UPDATE Language_ko_KR
SET Text = '[ICON_RES_ALPACA] Alpaca, ' || Text
WHERE Tag IN ('TXT_KEY_CORPORATION_RESOURCE_BONUS_GIORGIO_ARMEIER', 'TXT_KEY_BUILDING_GIORGIO_ARMEIER_FRANCHISE_HELP') AND EXISTS (SELECT * FROM Resources WHERE Type = 'RESOURCE_ALPACA');