UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]상코레 대학[ENDCOLOR]을 건설할 수 있습니다.', 	'불가사의: [COLOR_CYAN]상코레 대학[ENDCOLOR], [COLOR_CYAN]쉐다곤 파고다[ENDCOLOR] 및 [COLOR_CYAN]노트르담[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]자금성[ENDCOLOR]을 건설할 수 있습니다.', 		'불가사의: [COLOR_CYAN]바르트부르크[ENDCOLOR], [COLOR_CYAN]자금성[ENDCOLOR] 및 [COLOR_CYAN]부유크 한[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 						WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]알람브라[ENDCOLOR]를 건설할 수 있습니다.', 					'불가사의: [COLOR_CYAN]알람브라[ENDCOLOR], [COLOR_CYAN]그레이트 짐바브웨[ENDCOLOR] 및 [COLOR_CYAN]다마스쿠스의 대장간[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 					WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]붉은 요새[ENDCOLOR]를 건설할 수 있습니다.', 				'불가사의: [COLOR_CYAN]금각사[ENDCOLOR], [COLOR_CYAN]솔로베츠키 수도원[ENDCOLOR] 및 [COLOR_CYAN]붉은 요새[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 			WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]웨스트민스터 궁전[ENDCOLOR]을 건설할 수 있습니다.', 	'불가사의: [COLOR_CYAN]킬와 키시와니[ENDCOLOR], [COLOR_CYAN]오래된 다리[ENDCOLOR] 및 [COLOR_CYAN]웨스트민스터 궁전[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 			WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]루브르 박물관[ENDCOLOR]을 건설할 수 있습니다.', 					'불가사의: [COLOR_CYAN]박물관 섬[ENDCOLOR], [COLOR_CYAN]루브르 박물관[ENDCOLOR] 및 [COLOR_CYAN]몬테카를로 카지노[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 					WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]브로드웨이[ENDCOLOR]를 건설할 수 있습니다.', 					'불가사의: [COLOR_CYAN]브로드웨이[ENDCOLOR], [COLOR_CYAN]루르 계곡[ENDCOLOR] 및 [COLOR_CYAN]밴프 스프링스 호텔[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 					WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]펜타곤[ENDCOLOR]을 건설할 수 있습니다.', 				'불가사의: [COLOR_CYAN]펜타곤[ENDCOLOR], [COLOR_CYAN]브란덴부르크 문[ENDCOLOR] 및 [COLOR_CYAN]화이트 샌즈 미사일 발사장[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]블레츨리 파크[ENDCOLOR]를 건설할 수 있습니다.', 				'불가사의: [COLOR_CYAN]블레츨리 파크[ENDCOLOR], [COLOR_CYAN]큐 왕립 식물원[ENDCOLOR] 및 [COLOR_CYAN]아레시보 천문대[ENDCOLOR] (새로 잠금 해제된 불가사의 중 [COLOR_NEGATIVE_TEXT]하나[ENDCOLOR]만 제국 내에 건설할 수 있습니다).') 			WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';
---------------------------------------------------------
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]상코레 대학[ENDCOLOR]', 	'불가사의: [COLOR_CYAN]시기리야[ENDCOLOR], [COLOR_CYAN]상코레 대학[ENDCOLOR]') 	WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]바르트부르크[ENDCOLOR]', 				'불가사의: [COLOR_CYAN]모라이 테라스[ENDCOLOR], [COLOR_CYAN]바르트부르크[ENDCOLOR]') 			WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]알람브라[ENDCOLOR]', 				'불가사의: [COLOR_CYAN]크라크 데 슈발리에[ENDCOLOR], [COLOR_CYAN]알람브라[ENDCOLOR]') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]금각사[ENDCOLOR]', 		'불가사의: [COLOR_CYAN]시스티나 성당[ENDCOLOR], [COLOR_CYAN]금각사[ENDCOLOR]') 	WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]킬와 키시와니[ENDCOLOR]', 		'불가사의: [COLOR_CYAN]이화원[ENDCOLOR], [COLOR_CYAN]킬와 키시와니[ENDCOLOR]') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1) AND NOT EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_EE');
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]박물관 섬[ENDCOLOR]', 			'불가사의: [COLOR_CYAN]마라에 아라후라후[ENDCOLOR], [COLOR_CYAN]박물관 섬[ENDCOLOR]') 		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]브로드웨이[ENDCOLOR]', 				'불가사의: [COLOR_CYAN]아키하바라 전자상가[ENDCOLOR], [COLOR_CYAN]브로드웨이[ENDCOLOR]') 	WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]펜타곤[ENDCOLOR]', 				'불가사의: [COLOR_CYAN]파나마 운하[ENDCOLOR], [COLOR_CYAN]펜타곤[ENDCOLOR]') 				WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]블레츨리 파크[ENDCOLOR]', 		'불가사의: [COLOR_CYAN]극지 탐험[ENDCOLOR], [COLOR_CYAN]블레츨리 파크[ENDCOLOR]') 	WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP' AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
--============================================--
-- FREE ART HELP TEXTS
--============================================--
UPDATE Language_ko_KR SET Text = REPLACE(Text, '사전에 제작된 [ICON_GREAT_WORK] 예술 걸작이 포함되어 있습니다. ', '[ICON_GREAT_WORK] [COLOR_CULTURE_STORED]왕관 보석[ENDCOLOR]과 함께 시작합니다.[NEWLINE][NEWLINE]') WHERE Tag ='TXT_KEY_BUILDING_WHITE_TOWER_HELP';
UPDATE Language_ko_KR SET Text = REPLACE(Text, '[COLOR_POSITIVE_TEXT]무료[ENDCOLOR] [ICON_GREAT_WORK] 걸작과 함께', '[COLOR_CULTURE_STORED] [COLOR_MAGENTA]홍수 서판[ENDCOLOR]과 함께 시작합니다') WHERE Tag ='TXT_KEY_BUILDING_ROYAL_LIBRARY_HELP';
--============================================--
-- EE Compatibility
--============================================--
UPDATE Language_ko_KR SET Text = REPLACE(Text, '불가사의: [COLOR_CYAN]킬와 키시와니[ENDCOLOR]', '불가사의: [COLOR_CYAN]불향각[ENDCOLOR], [COLOR_CYAN]킬와 키시와니[ENDCOLOR]') WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_EE') AND EXISTS (SELECT * FROM Community WHERE Type='MW-SETTING-POLICIES' AND Value=1);
DELETE FROM Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_SUMMER_PALACE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_EE');