INSERT INTO Language_ko_KR (Text, Tag)
SELECT  '아니요. 지금은 바꾸고 싶지 않아요.',
		'TXT_KEY_EVENT_CIVIC_NOPE' UNION ALL
SELECT  '구관이 명관이죠.[NEWLINE][NEWLINE]같은 턴에 이 설정을 두 번 이상 사용하지 마세요!',
		'TXT_KEY_EVENT_CIVIC_NOPE_HELP' UNION ALL		
SELECT  '정부 정책',
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION' UNION ALL
SELECT  '"우리는 신의 권리로 정부를 인정하지 않는다. 통치할 수 있는 유일한 합법적 권리는 피지배자로부터의 명시적 권한 부여뿐이다."[NEWLINE]-- 윌리엄 헨리 해리슨', 
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP' UNION ALL
SELECT 	'전제정치',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]문맹으로 [ICON_HAPPINESS_3] 불행 -10% [ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] 저항  가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 0%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '세습 통치',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]군사 이론 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]주둔군에서 [ICON_HAPPINESS_1] 행복 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]아군 도시 근처에서 군사 유닛의 [ICON_STRENGTH] 전투력이 +10% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER]불가사의를 향한 [ICON_PRODUCTION] 생산력 +5%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE] [NEWLINE]의교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  '연방제', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]문자 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CAPITAL] 수도의 [ICON_HAPPINESS_1] 행복도 +4[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]수도가 아닌 도시의 [ICON_GOLD] 골드 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]수도가 아닌 모든 도시의 모든 요구 사항에 대한 [ICON_HAPPINESS_3] 불행 수정치 +10%
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[NEWLINE][ICON_BULLET]문자 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CAPITAL] 수도의 [ICON_HAPPINESS_1] 행복도 +4[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]수도가 아닌 도시의 [ICON_GOLD] 골드 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]수도가 아닌 모든 도시의 모든 요구 사항에 대한 [ICON_HAPPINESS_3] 불행 수정치 +10%
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '후원', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]교육 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_INFLUENCE] 도시 국가 Resting 점수 +15[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITY_STATE] 도시 국가에 군사적 선물을 줄 시 [ICON_INFLUENCE]영향력 추가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_CHANCERY} 및 {TXT_KEY_BUILDING_WIRE_SERVICE}에서 발생하는 기본 골드 유지비의 100%를 골드 보너스로 추가[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP' UNION ALL
 --[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]도시 국가 간 우호 관계가 오를 때마다 [ICON_CAPITAL] 수도의 [ICON_GOLD] 골드와 [ICON_TOURISM] 관광이 +1 증가 (도시 국가 간 동맹인 경우 3배 증가)[ENDCOLOR] 
SELECT  '대의권', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]인쇄기 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]도시에 거주하는 [ICON_CITIZEN] 시민 15명당 [ICON_HAPPINESS_1] 행복 +1 [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]전문가로부터 [ICON_RESEARCH] 과학 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  '전체주의', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]강선 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_GENERAL][ICON_GREAT_ADMIRAL] 위대한 장군/제독의 리더십 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WAR] 전쟁 피로도 감소로 [ICON_HAPPINESS_3] 불행 -25% [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_BARRACKS}, {TXT_KEY_BUILDING_ARMORY}, {TXT_KEY_BUILDING_STABLE}, {TXT_KEY_BUILDING_HARBOR}, {TXT_KEY_BUILDING_SEAPORT}, 그리고 {TXT_KEY_BUILDING_MILITARY_ACADEMY}의 기본 골드 유지비의 100% 골드 보너스[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]강선 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_GENERAL] 위대한 장군의 전투 보너스가 +15% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]군사 유닛 생산 +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] 외국 스파이가 당신의 도시에서 [ICON_RESEARCH] 기술을 훔치는 데 +33% 더 비효율적[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]병영, 무기고, 사관 학교에서 [ICON_GOLD] 골드 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]경찰서로부터 [ICON_HAPPINESS_1] 행복 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '국민 참정권', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]원자론 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시 및 유닛 업그레이드 시 [ICON_INVEST] 골드 투자 비용 -10% 감소[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] 시민들이 [ICON_FOOD] 식량, [ICON_PRODUCTION] 생산, [ICON_GOLD] 골드를 +0.25 생성[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] 위인, 시설 및 [ICON_RES_ARTIFACTS] 랜드마크에서 얻은 [ICON_FOOD] 식량 +5[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]원자론 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] 시민들이 [ICON_FOOD] 식량, [ICON_PRODUCTION] 생산, [ICON_GOLD] 골드를 +0.25 생성[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] 위인 시설이 [ICON_FOOD] 식량 +4 생성[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시의 [ICON_INVEST] 골드 투자 비용 -8% 감소[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '법률 정책',
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION' UNION ALL
SELECT  '"어떤 사람이든 국가를 세우고 법을 주기를 원하는 사람은, 모든 사람이 나쁘다고 가정하고, 기회가 있을 때마다 그들의 악랄한 본성을 드러낼 준비가 되어 있다고 가정하는 것으로 시작해야 한다."[NEWLINE]-- 니콜로 마키아벨리의 로마사 논고', 
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP' UNION ALL
SELECT 	'무정부주의',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]빈곤으로 인한 [ICON_HAPPINESS_3] 불행 -10%[ENDCOLOR]
[NEWLINE][ICON_BULLET]선택 시 [ICON_RESISTANCE] 저항 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance} [ICON_GOLD])
[NEWLINE][ICON_BULLET]선택 시 [ICON_RESISTANCE] 저항 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '성문화된 법률',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]수학 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] 세계 불가사의로부터 [ICON_CULTURE] 문화 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시의 전문가 1명이 더 이상 [ICON_URBANIZATION] 도시화로 인한 [ICON_HAPPINESS_3] 불행을 생성하지 않음[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  '봉건제', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]기사도 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]유지비 -35% ([ICON_GOLD] +{2_Gold})[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]유닛 훈련 추가 경험치 +15[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]도시 국가로부터 산출량 +20% 증가, 종속국이 산출량의 10%를 추가 조공, [ICON_PUPPET] 괴뢰 도시에서 산출량 패널티 -10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  '관료제', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]물리학 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]추가 타일이나 전문가 슬롯을 작업할 수 있는 [ICON_CAPITAL] 수도의 [ICON_CITIZEN_RED] 노동자 +7[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CAPITAL] 수도의 전문가 7인이 더 이상 [ICON_URBANIZATION] 도시화로 인한 [ICON_HAPPINESS_3] 불행을 생성하지 않음[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]건물 요구 사항이 있는 궁전 및 국가 불가사의의 기본 산출량 및 산출량 수정치 +100% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  '국가주의', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]군사 과학 필요
[NEWLINE][ICON_BULLET]유지비 없음
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]외국 도시에서 [ICON_SPY] 스파이 활동에 성공시 [ICON_CULTURE] 문화 및 [ICON_GOLDEN_AGE] 황금기 점수 25를 획득 (시대에 따라 조정)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN]인구에 의해 생성된 [ICON_SILVER_FIST] 유닛 공급량 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 35%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  '표현의 자유', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]라디오 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]모든 도시에서 [ICON_CULTURE] 문화 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] 위인들의 시설 및 [ICON_RES_ARTIFACTS] 랜드마크로부터 [ICON_CULTURE] 문화 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  '입헌주의', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]전기 통신 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GOLDEN_AGE] 황금기 길이 +25%[ENDCOLOR]
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET][ICON_GOLDEN_AGE] 황금기 동안 [ICON_FOOD] 식량, [ICON_RESEARCH] 과학, [ICON_PEACE] 신앙 +20% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] 시민들이 [ICON_GOLDEN_AGE] 황금기 점수 +1 생성[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  '노동 정책',
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION' UNION ALL
SELECT  '"밤이 거의 새어 낮이 가까웠습니다. 그러니 어둠의 행실을 벗어버리고 빛의 갑옷을 입읍시다."[NEWLINE]-- 신약 성경: 로마인들에게 보낸 편지, 13:12', 
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP' UNION ALL
SELECT 	'부족제',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]무료로인한 [ICON_HAPPINESS_3] 불행 -10% 감소[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '노예제',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]청동 기술 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시에 추가 타일이나 전문가 슬롯을 작업할 수 있는 [ICON_CITIZEN_RED] 노동자 +1명 추가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]모든 도시에서 [ICON_FOOD] 식량 성장 -10% 감소[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]법원이 없는 모든 도시에서 [ICON_HAPPINESS_4] 불행 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  '장원제', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]공공 행정 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]타일 시설 생산량 +25%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]비전문가 [ICON_CITIZEN] 시민 5명당 도시의 [ICON_FOOD] 식량 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  '신분제', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]길드 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]문명의 [ICON_CITIZEN] 시민 40명당 [ICON_CAPITAL] 수도에 [ICON_GREAT_GENERAL] 위대한 장군 점수 +1과 [ICON_GREAT_ADMIRAL] 위대한 제독 점수 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]전문가는 기본 생산량에 +1 추가 생산 (예외: 공무원은 [ICON_GOLDEN_AGE] 황금기 생산량에 +1 추가 생산)[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]길드 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]문명의 [ICON_CITIZEN] 시민 25명당 [ICON_CAPITAL] 수도에 [ICON_GREAT_GENERAL] 위대한 장군 점수 +1과 [ICON_GREAT_ADMIRAL] 위대한 제독 점수 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]전문가는 기본 산출량에 +1 추가 생산[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]도시가 [ICON_HAPPINESS_3] 불행을 1 더 많이 생성[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '산업 노예', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]산업화 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시에서 [ICON_FOOD] 식량 성장 +10% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]비전문가 [ICON_CITIZEN] 시민 4명당 도시의 [ICON_PRODUCTION] 생산력과 [ICON_GOLD] 골드 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]농장, 요새, 광산, 제재소, 마을이 기본 산출량에 +1 추가 생산[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  '노동조합주의', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]전기 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]길드, 노동 조합, 신용 조합, 학술 기관, 외교공관의 산출량 +4, [ICON_HAPPINESS_1] 행복 +2, 건설 속도 100% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  '해방', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]세계화 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]각 도시에서 생산되는 [ICON_HAPPINESS_1] 행복의 25%를 턴당 도시의 [ICON_CULTURE] 문화로 추가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_HAPPINESS_1] 행복도가 낮은 문명의 [ICON_TOURISM] 관광 +25% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  '경제 정책', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION' UNION ALL
SELECT  '"마음이 행복할 때의 빵 한 조각이 불행할 때의 부보다 낫다."[NEWLINE]-- 아메네모페', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP' UNION ALL
SELECT 	'물물교환',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Poverty[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '탈중앙화',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]교역 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT] 국제 [ICON_INTERNATIONAL_TRADE] 교역로에서 [ICON_GOLD] 골드 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT] 도시 국가와의 [ICON_INTERNATIONAL_TRADE] 교역로(대상 도시 국가 포함)가 소유한 도시 국가 교역로 하나당 [ICON_INFLUENCE] 영향력을 턴당 +0.75 생성 (최대 +3.75)[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  '상업주의',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]화폐 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CONNECTED] 도시 연결로 인한 [ICON_FOOD] 식량 +3, [ICON_PRODUCTION] 생산 +3[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]국내 [ICON_INTERNATIONAL_TRADE] 교역로에서 [ICON_FOOD] 식량 +33%, [ICON_PRODUCTION] 생산 +33% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]동맹인 도시 국가, 가신, 영주에게만 국제 [ICON_INTERNATIONAL_TRADE] 교역로를 생성할 수 있음[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  '자유시장', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]경제학 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_INTERNATIONAL_TRADE] 교역로 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][COLOR_POSITIVE_TEXT]교역로[ENDCOLOR]에 대한 [ICON_TOURISM] 관광 수정치 +12%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]교역 유닛 훈련 속도 25% 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  '국유재산', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]기업 본사 누락됨', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]기업 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]기업 필요
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] 기업 본사에서 [ICON_FOOD] 식량과 [ICON_CULTURE] 문화 생산 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_OFFICE] 기업 사무소에서 [ICON_FOOD]식량 +4 와 [ICON_RESEARCH] 과학 +2 생산[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_ENGINEER] 기술자, 광산, 채석장, 제재소, 제조소에서 생산되는 [ICON_FOOD] 식량 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]과학 이론 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]광산, 채석장, 제재소, 제조소에서 [ICON_FOOD] 식량 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]작업장이 있는 도시에서 [ICON_FOOD] 식량 +10%, [ICON_PRODUCTION] 생산 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '협동조합주의', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]기업 본사 누락됨', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]기업 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]기업 필요
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] 기업 본사에서 [ICON_GOLD] 골드와 [ICON_TOURISM] 관광 생산 +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT] [ICON_VP_OFFICE] 기업 사무소에서 기본 골드 유지비의 100% 골드 보너스로 추가[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]각각의 고유한 [ICON_VP_MONOPOLY] 국제적 독점 수정치는 백분율 기반인 경우 추가로 5% 증가, 그렇지 않으면 +2 증가[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]산업화 필요
[NEWLINE][ICON_BULLET]높은 유지비
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]시장과 은행의 [ICON_PRODUCTION] 생산과 [ICON_GOLD] 골드 +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '환경주의', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]대체 에너지 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]문명의 [ICON_CITIZEN] 시민 2명당 [ICON_CAPITAL] 수도에 [ICON_GOLD] 골드 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_FRANCHISE] 기업 프랜차이즈에서 [ICON_GOLD] 골드 +10[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_RES_ARTIFACTS] 랜드마크, 숲, 정글, 습지, 범람원, 오아시스, 산호섬, 자연경관에서 [ICON_CULTURE] 문화 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]농장으로부터 [ICON_FOOD] 식량 -1  Food from Farms[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]광산, 채석장, 제재소 및 제조소로부터 [ICON_PRODUCTION] 생산 -3[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  '종교 정책', 
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION' UNION ALL
SELECT  '"인간의 구원에는 세 가지가 필요하다. 믿을 것을 아는 것, 추구할 것을 아는 것, 해야 할 것을 아는 것이다."[NEWLINE]-- 성 토마스 아퀴나스',
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP' UNION ALL
SELECT 	'무종교',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]종교 분쟁으로 인한 [ICON_HAPPINESS_3] 불행 -10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 없음
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '조상 숭배', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]달력 필요
[NEWLINE][ICON_BULLET]낮은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_RELIGION]당신의 다수 종교를 따르는 도시에서 [ICON_PEACE] 신앙 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]제단의 신앙 구매 해제 ([ICON_PEACE] 신앙 비용 50, [ICON_PEACE] 신앙 +1, [ICON_CULTURE_LOCAL] 국경 성장 점수 +1)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]제단에서 [ICON_PEACE] 신앙 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]자연경관에서 [ICON_PEACE] 신앙 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 25%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  '조직된 신앙',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]당신의 다수 종교(존재하는 경우)에는 강화 신앙이나 종교 개혁 신앙이 없습니다.',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]철학 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]강화 또는 개혁 신앙을 가진 다수 종교 필요
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]종교 창시자 건물이 모든 산출량의 +5%를 생산[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]당신의 [ICON_RELIGION] 다수 종교를 따르는 도시에서 [ICON_PRODUCTION] 생산 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]사원, 성지, [ICON_RES_ARTIFACTS] 랜드마크에서 [ICON_PRODUCTION] 생산 +3[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 )  UNION ALL
SELECT  '[ICON_BULLET]철학 필요
[NEWLINE][ICON_BULLET]높은 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]당신의 [ICON_RELIGION] 다수 종교를 따르는 도시에서 [ICON_PRODUCTION] 생산 +1 [ICON_PEACE] 신앙 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]사원, 성지, [ICON_RES_ARTIFACTS] 랜드마크에서 [ICON_PRODUCTION] 생산 +3[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 5%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 )  UNION ALL
SELECT  '신정제', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]다수 종교가 누락되었습니다.',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]신학 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]다수 종교 필요
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]군사 유닛이 적대적이지 않은 영토에서 턴당 추가 체력 5 회복, 패배한 적 유닛으로부터 [ICON_PEACE] 신앙 획득[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_RESEARCH] Science[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]사원, 성지, [ICON_RES_ARTIFACTS] 랜드마크에서 [ICON_GOLD] 골드 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  '평화주의', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]생물학 필요
[NEWLINE][ICON_BULLET]유지비 없음
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] 위인 생성률 +25% ([ICON_GOLDEN_AGE] 황금기동안 두 배)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]전문가에게 [ICON_GOLDEN_AGE] 황금기 점수 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT][ICON_WAR] 전쟁 피로에서 [ICON_HAPPINESS_3] 불행 +50%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]유닛 유지비 +100% (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 35%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]생물학 필요
[NEWLINE][ICON_BULLET]유지비 없음
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] 위인 생성률 +25% ([ICON_GOLDEN_AGE] 황금기동안 두 배)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]당신의 [ICON_RELIGION] 다수 종교를 따르는 도시에서 [ICON_CULTURE] 문화 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]기본 유닛 유지비 +100% (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 35%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '유명인 숭배', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]비행 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]우상 건설 해제 ([ICON_GOLDEN_AGE] 황금기 점수 +1)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]우상에서 [ICON_CULTURE] 문화 +3, [ICON_TOURISM] 관광 +2, [ICON_HAPPINESS_1] 행복 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]성지와 [ICON_RES_ARTIFACTS] 랜드마크에서 [ICON_CULTURE] 문화 +2[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  '종교의 자유', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]페니실린 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시에서 [ICON_HAPPINESS_1] 행복 +1 [ICON_RESEARCH] 과학 +10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시에 적어도 한 명의 추종자가 있는 모든 세계 종교에 대해 모든 도시 산출량 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]페니실린 필요
[NEWLINE][ICON_BULLET]중간 유지비 (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]모든 도시에서 [ICON_HAPPINESS_1] 행복 +1[ENDCOLOR]
[NEWLINE][ICON_BULLET][ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]저항[ENDCOLOR] 가능성: 15%
[NEWLINE][NEWLINE]외교 의견: [ICON_FLOWER] 좋아함 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] 용서못함 [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  '세금',
		'TXT_KEY_TAX' UNION ALL
SELECT  '제단',
		'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT  '[COLOR_MAGENTA]{TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7}[ENDCOLOR]을 채택한 경우에만 신앙으로 구매 가능.',
		'TXT_KEY_ANCESTOR_WORSHIP_HELP' UNION ALL
SELECT  '우상',
		'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT  '힘이 곧 정의',
		'TXT_KEY_PROMOTION_HEREDITARYRULE' UNION ALL
SELECT  '[COLOR_POSITIVE_TEXT]아군 도시에 인접해 있거나 주둔[ENDCOLOR]하고 있을 경우 [ICON_STRENGTH] 전투력이 +10% 증가합니다.',
		'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP' UNION ALL
SELECT  '신정 전사',
		'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL
SELECT  '적국이 아닌 영토에서 턴당 [COLOR_POSITIVE_TEXT]체력을 +5 회복[ENDCOLOR]합니다.[NEWLINE][NEWLINE]패배한 적군 유닛 [ICON_STRENGTH] 전투력의 50%를 [ICON_PEACE]신앙으로 획득',
		'TXT_KEY_PROMOTION_DEUSVULT_HELP'; --UNION ALL
--SELECT  '정책이란 무엇입니까?',
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q1_DESC' UNION ALL
--SELECT  '유지, 혁명, 외교?', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q2_DESC' UNION ALL
--SELECT  '혁명의 기회?',
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q3_DESC' UNION ALL
--SELECT  '정책과 개혁이 설치되었습니다!', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_DESC' UNION ALL
--SELECT  '축하합니다. 정책과 개혁이 성공적으로 활성화되었습니다. 이 모드는 Civilization IV의 정책에서 상당한 영향을 받았다는 것을 알 수 있습니다. 이것이 여러분의 문명을 관리하는 방법에 대한 정부의 결정에 영향을 미치기를 바랍니다! 다양하게 실험해 보고 즐겨보세요! 게임에서 이벤트 시스템이 활성화되어 있지 않으면 이 모드는 제대로 작동하지 않습니다.', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_HELP' UNION ALL
--SELECT  '세습 통치 해제[NEWLINE][NEWLINE]세습 통치는 통치권이 가족 구성원 간에 물려지는 정부 형태입니다. 세습 통치의 장점은 보통 왕위 계승이 명확하기 때문에 현 군주가 죽었을 때 권력 다툼이 덜할 수 있다는 것입니다. 그러나 세습 통치는 모든 비선출 통치자와 마찬가지로 다음과 같은 약점을 안고 있습니다. 지도자는 국민에게 책임을 질 필요가 없으며, 나쁜 지도자를 제거하는 것은 매우 어려울 수 있습니다.',
--		'TXT_KEY_TUTORIAL_HEREDITARY_RULE_HELP';
--------------------------------------------------------------------------------------------------------------------------
--INSERT INTO CustomTutorials (Type, Description, Help, AdvisorType, AudioSound, DoNotRepeat)
--SELECT 'TUTORIAL_VP_CIVICS', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_DESC', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_HELP', 'ADVISOR_MILITARY', 'AS2D_M_A_ADVISOR_SPEECH_EXCUSE_ME', 1 UNION ALL
--SELECT 'CIVIC_HEREDITARY_RULE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_TUTORIAL_HEREDITARY_RULE_HELP', 'ADVISOR_MILITARY', 'AS2D_M_A_ADVISOR_SPEECH_EXCUSE_ME', 1;

--INSERT INTO CustomTutorial_Questions (TutorialType, ConceptType, Description)
--SELECT 'TUTORIAL_VP_CIVICS', 'CONCEPT_CIVICS_INTRODUCTION', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q3_DESC' UNION ALL
--SELECT 'TUTORIAL_VP_CIVICS', 'CONCEPT_CIVICS_INTRODUCTION', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q2_DESC' UNION ALL
--SELECT 'TUTORIAL_VP_CIVICS', 'CONCEPT_CIVICS_INTRODUCTION', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q1_DESC';

INSERT INTO Events (Type, Description, Help, EventArt, RandomChance, NumChoices, IgnoresGlobalCooldown, EventCooldown)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC', 'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP', 'GovernmentCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC', 'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP', 'LegalCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC', 'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP', 'LaborCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC', 'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP', 'EconomyCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC', 'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP', 'ReligionCivics.dds', -1, 7, 1, 0;

INSERT INTO EventChoices (Type, Description, Help, EventDuration, PrereqTech)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP', -1, 'TECH_ARCHERY'  UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP', -1, 'TECH_WRITING' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP', -1, 'TECH_EDUCATION' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP', -1, 'TECH_PRINTING_PRESS' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP', -1, 'TECH_RIFLING' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP', -1, 'TECH_ATOMIC_THEORY' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP', -1, 'TECH_MATHEMATICS'  UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP', -1, 'TECH_CHIVALRY' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP', -1, 'TECH_PHYSICS' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP', -1, 'TECH_MILITARY_SCIENCE' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP', -1, 'TECH_RADIO' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP', -1, 'TECH_TELECOM' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP', -1, 'TECH_BRONZE_WORKING'  UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP', -1, 'TECH_CIVIL_SERVICE' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP', -1, 'TECH_GUILDS' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP', -1, 'TECH_INDUSTRIALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP', -1, 'TECH_ELECTRICITY' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP', -1, 'TECH_GLOBALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP', -1, 'TECH_HORSEBACK_RIDING' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP', -1, 'TECH_CURRENCY'  UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP', -1, 'TECH_ECONOMICS' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP', -1, 'TECH_SCIENTIFIC_THEORY' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP', -1, 'TECH_INDUSTRIALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP', -1, 'TECH_ECOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP', -1, 'TECH_CALENDAR' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP', -1, 'TECH_PHILOSOPHY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP', -1, 'TECH_THEOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP', -1, 'TECH_BIOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP', -1, 'TECH_FLIGHT' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP', -1, 'TECH_PENICILIN' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL;

INSERT INTO Event_ParentEvents (EventChoiceType, EventType)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_8', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_8', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8', 'PLAYER_EVENT_RELIGIONCIVIC';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1';

UPDATE EventChoices
SET PrereqTech = 'TECH_CORPORATIONS', DisabledTooltip = 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_DISABLED'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE EventChoices
SET PrereqTech = 'TECH_CORPORATIONS', DisabledTooltip = 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_DISABLED'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE EventChoices
SET Expires = 1, EventPromotion = 'PROMOTION_HEREDITARYRULE'
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2';

--UPDATE EventChoices
--SET EventBuildingClassGlobal = 'BUILDINGCLASS_PATRONAGE', Expires = 1, CapitalEffectOnly = 1
--WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_SUFFRAGE', Expires = 1
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_BUREAUCRACYCIVIC', Expires = 1, CapitalEffectOnly = 1
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_NATIONHOOD', Expires = 1, CapitalEffectOnly = 1
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5';

UPDATE EventChoices
SET DisabledTooltip = 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_DISABLED'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2';

UPDATE EventChoices
SET EventPromotion = 'PROMOTION_DEUSVULT', Expires = 1, DisabledTooltip = 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_DISABLED'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3';

INSERT INTO EventChoiceFlavors (EventChoiceType, FlavorType, Flavor)
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_CITY_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_WONDER', 10 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_HAPPINESS', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'FLAVOR_GOLD', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', -3 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_DIPLOMACY', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_SCIENCE', 11 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_OFFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_PRODUCTION', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_GROWTH', 25 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_INFRASTRUCTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GREAT_PEOPLE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_HAPPINESS', 5 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_MILITARY_TRAINING', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_DIPLOMACY', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_OFFENSE', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_DEFENSE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_WONDER', 15 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_ESPIONAGE', 5 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', 15 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_SCIENCE', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_GROWTH', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_RELIGION', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_GROWTH', -5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_HAPPINESS', -4 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_TILE_IMPROVEMENT', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_GROWTH', 10 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_MILITARY_TRAINING', 1 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_PRODUCTION', 15 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_GROWTH', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_PRODUCTION', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_SCIENCE', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_GREAT_PEOPLE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 15 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'FLAVOR_DIPLOMACY', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_GROWTH', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_I_LAND_TRADE_ROUTE', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_I_SEA_TRADE_ROUTE', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_I_TRADE_DESTINATION', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_I_TRADE_ORIGIN', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_GROWTH', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_SCIENCE', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_TILE_IMPROVEMENT', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_PRODUCTION', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_CULTURE', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_TILE_IMPROVEMENT', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 12 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_PRODUCTION', -2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_RELIGION', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_RELIGION', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_SCIENCE', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_OFFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_RELIGION', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_HAPPINESS', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_OFFENSE', -5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 15 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_CULTURE', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_SCIENCE', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_HAPPINESS', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_RELIGION', -1;

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_TAX', 'BUILDING_TAXTAXTAX', 'TXT_KEY_TAX' UNION ALL
--SELECT 'BUILDINGCLASS_PATRONAGE', 'BUILDING_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT 'BUILDINGCLASS_BUREAUCRACYCIVIC', 'BUILDING_BUREAUCRACYCIVIC', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4' UNION ALL
SELECT 'BUILDINGCLASS_ANCESTOR_WORSHIP', 'BUILDING_ANCESTOR_WORSHIP', 'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT 'BUILDINGCLASS_NATIONHOOD', 'BUILDING_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT 'BUILDINGCLASS_STATE_ATHEISM', 'BUILDING_STATE_ATHEISM', 'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT 'BUILDINGCLASS_SUFFRAGE', 'BUILDING_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6';

INSERT INTO Buildings (Type, Description, BuildingClass, Cost, PrereqTech, ArtDefineTag, MinAreaSize, NeverCapture, NukeImmune, HurryCostModifier, PortraitIndex, IconAtlas, GreatWorkCount, FaithCost, ReligiousPressureModifier, IsDummy)
SELECT 'BUILDING_TAXTAXTAX', 'TXT_KEY_TAX', 'BUILDINGCLASS_TAX', -1, NULL, 'NONE', -1, 0, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
--SELECT 'BUILDING_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'BUILDINGCLASS_PATRONAGE', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_BUREAUCRACYCIVIC', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4', 'BUILDINGCLASS_BUREAUCRACYCIVIC', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION', 'BUILDINGCLASS_ANCESTOR_WORSHIP', -1, NULL, 'NONE', -1, 0, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_SHRINE'), 4, 'MORE_SPECIALIST_ATLAS', 0, 50, 0, 0 UNION ALL
SELECT 'BUILDING_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 'BUILDINGCLASS_NATIONHOOD', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION All
SELECT 'BUILDING_STATE_ATHEISM', 'TXT_KEY_STATE_ATHEISM_DESCRIPTION', 'BUILDINGCLASS_STATE_ATHEISM', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_WIRE_SERVICE'), NULL, 'NONE', -1, 1, 1, -1, 5, 'MORE_SPECIALIST_ATLAS', 0, 0, 0, 0 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'BUILDINGCLASS_SUFFRAGE', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1;

UPDATE Buildings
SET ConquestProb = 100
WHERE Type = 'BUILDING_TAXTAXTAX';

--UPDATE Buildings
--SET CapitalOnly = 1
--WHERE Type = 'BUILDING_PATRONAGE';

UPDATE Buildings
SET CapitalOnly = 1, CityAutomatonWorkersChange = 7
WHERE Type = 'BUILDING_BUREAUCRACYCIVIC';

UPDATE Buildings
SET CapitalOnly = 1
WHERE Type = 'BUILDING_NATIONHOOD';

UPDATE Buildings
SET PolicyType = 'POLICY_CIVIC_ANCESTOR_WORSHIP', Help = 'TXT_KEY_ANCESTOR_WORSHIP_HELP'
WHERE Type = 'BUILDING_ANCESTOR_WORSHIP';

UPDATE Buildings
SET PolicyType = 'POLICY_CIVIC_STATE_ATHEISM', GoldMaintenance = 1
WHERE Type = 'BUILDING_STATE_ATHEISM';

INSERT INTO Building_YieldFromSpyAttack (BuildingType, YieldType, Yield)
SELECT 'BUILDING_NATIONHOOD', 'YIELD_GOLDEN_AGE_POINTS', 25 UNION ALL
SELECT 'BUILDING_NATIONHOOD', 'YIELD_CULTURE', 25;

--INSERT INTO Building_YieldPerFriend (BuildingType, YieldType, Yield)
--SELECT 'BUILDING_PATRONAGE', 'YIELD_TOURISM', 1 UNION ALL
--SELECT 'BUILDING_PATRONAGE', 'YIELD_GOLD', 1;

--INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
--SELECT 'BUILDING_PATRONAGE', 'YIELD_TOURISM', 3 UNION ALL
--SELECT 'BUILDING_PATRONAGE', 'YIELD_GOLD', 3;

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_SUFFRAGE', 'YIELD_FOOD', 25 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'YIELD_PRODUCTION', 25 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'YIELD_GOLD', 25;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'YIELD_FAITH', 1 UNION ALL
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
SELECT 'BUILDING_STATE_ATHEISM', 'YIELD_GOLDEN_AGE_POINTS', 1;

INSERT INTO UnitPromotions (Type, Description, Help, Sound, CannotBeChosen, PortraitIndex, IconAtlas, PediaType, PediaEntry)
SELECT 'PROMOTION_DEUSVULT', 'TXT_KEY_PROMOTION_DEUSVULT', 'TXT_KEY_PROMOTION_DEUSVULT_HELP', 'AS2D_IF_LEVELUP', 1, 1, 'MORE_SPECIALIST_ATLAS2', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL 
SELECT 'PROMOTION_HEREDITARYRULE', 'TXT_KEY_PROMOTION_HEREDITARYRULE', 'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP', 'AS2D_IF_LEVELUP', 1, 0, 'MORE_SPECIALIST_ATLAS2', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_HEREDITARYRULE';

UPDATE UnitPromotions
SET IsNearbyPromotion = 1, NearbyRange = 1, NearbyFriendlyCityCombatMod = 10
WHERE Type = 'PROMOTION_HEREDITARYRULE';

UPDATE UnitPromotions
SET FriendlyHealChange = 5, NeutralHealChange = 5
WHERE Type = 'PROMOTION_DEUSVULT';

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_DEUSVULT', 'YIELD_FAITH', 50;

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_FIGHTER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_BOMBER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_CARRIER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_SUBMARINE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_FIGHTER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_BOMBER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_CARRIER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_SUBMARINE';

--INSERT INTO UnitPromotions_YieldChanges (PromotionType, YieldType, Yield)
--SELECT 'PROMOTION_HEREDITARYRULE', 'YIELD_GOLD', 1 UNION ALL
--SELECT 'PROMOTION_HEREDITARYRULE', 'YIELD_PRODUCTION', 1;