INSERT INTO Language_en_US (Text, Tag)
SELECT  'No thanks. I don''t want to change now.',
		'TXT_KEY_EVENT_CIVIC_NOPE' UNION ALL
SELECT  'The old ways are best.[NEWLINE][NEWLINE]Don''t use this option more than twice in the same turn!',
		'TXT_KEY_EVENT_CIVIC_NOPE_HELP' UNION ALL		
SELECT  'Government Civics',
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION' UNION ALL
SELECT  '"We admit of no government by divine right ... the only legitimate right to govern is an express grant of power from the governed."[NEWLINE]--William Henry Harrison', 
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP' UNION ALL
SELECT 	'Despotism',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Illiteracy[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] Resistance: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 0%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Hereditary Rule',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Military Strategy
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness from Garrison[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Military Units gain +10% [ICON_STRENGTH] Combat Strength near Friendly Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+5% [ICON_PRODUCTION] Production toward [ICON_WONDER] Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE] [NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Confederation', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Writing
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+4 [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_GOLD] Gold in non-Capital Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+10% [ICON_HAPPINESS_3] Unhappiness Modifier for all Needs in all non-Capital Cities
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[NEWLINE][ICON_BULLET]Requires Writing
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+4 [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_GOLD] Gold in Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cities generate 3 [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Patronage', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Education
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15 [ICON_INFLUENCE] City-State Resting Point[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Military gifts to [ICON_CITY_STATE] City-States yield an additional +5 [ICON_INFLUENCE] Influence[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]100% of Base Gold Maintenance from {TXT_KEY_BUILDING_CHANCERY} and {TXT_KEY_BUILDING_WIRE_SERVICE} is added as a Gold Bonus[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP' UNION ALL
 --[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold and [ICON_TOURISM] Tourism in the [ICON_CAPITAL] Capital for every City-State Friendship (tripled if City-State Ally)[ENDCOLOR] 
SELECT  'Representation', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Printing Press
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness for every 15 [ICON_CITIZEN] Citizens in a City[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_RESEARCH] Science from Specialists[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  'Totalitarianism', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Rifling
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_GREAT_GENERAL][ICON_GREAT_ADMIRAL] Great General/Admiral''s Leadership[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-25% [ICON_HAPPINESS_3] from [ICON_WAR] War Weariness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]100% of Base Gold Maintenance from {TXT_KEY_BUILDING_BARRACKS}, {TXT_KEY_BUILDING_ARMORY}, {TXT_KEY_BUILDING_STABLE}, {TXT_KEY_BUILDING_HARBOR}, {TXT_KEY_BUILDING_SEAPORT}, and {TXT_KEY_BUILDING_MILITARY_ACADEMY} is added as a Gold Bonus[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Rifling
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_GENERAL] Great General''s Combat Bonus increased by +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15% Military Unit Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Foreign Spies are +33% ineffective at stealing [ICON_RESEARCH] Technologies from your Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold from Barracks, Armories, and Military Academies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness from Police Station[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'National Suffrage', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Atomic Theory
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% Cost of [ICON_INVEST] Gold Investments in all Cities and Unit Upgrades[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] Citizens generate +0.25 [ICON_FOOD] Food, [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+5 [ICON_FOOD] Food from [ICON_GREAT_PEOPLE] Great People Improvements and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Atomic Theory
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Citizens generate +0.25 [ICON_FOOD] Food [ICON_PRODUCTION] Production, and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] Great People Improvements generates +4 [ICON_FOOD] Food[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cost of [ICON_INVEST] Gold Investments in all cities reduced by -8%[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Legal Civics',
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION' UNION ALL
SELECT  '"Whoever desires to found a state and give it laws, must start with assuming that all men are bad and ever ready to display their vicious nature, whenever they may find occasion for it."[NEWLINE]--Niccolo Machiavelli', 
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP' UNION ALL
SELECT 	'Anarchism',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Distress[ENDCOLOR]
[NEWLINE][ICON_BULLET]No [ICON_RESISTANCE] Resistance when chosen
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance} [ICON_GOLD])
[NEWLINE][ICON_BULLET]No [ICON_RESISTANCE] Resistance when chosen
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Codified Law',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Mathematics
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_CULTURE] Culture from [ICON_WONDER] World Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]1 Specialist in every City no longer produces [ICON_HAPPINESS_3] Unhappiness from [ICON_URBANIZATION] Urbanization[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Feudalism', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Chivalry
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-35% Unit Maintenance (+{2_Gold}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Units trained gain an additional +15 XP[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+20% Yield from City-States, Vassals tribute an additional 10% of their yields, -10% Yield penalties from [ICON_PUPPET] Puppeted Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Bureaucracy', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Physics
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+7 [ICON_CITIZEN_RED] Laborer in the [ICON_CAPITAL] Capital that can work an additional tile or a specialist slot[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]7 Specialists in the [ICON_CAPITAL] Capital no longer produces [ICON_HAPPINESS_3] Unhappiness from [ICON_URBANIZATION] Urbanization[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+100% Base Yields and Yield Modifiers of the Palace and National Wonders that have a building requirement[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  'Nationhood', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Military Science
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Gain 25 [ICON_CULTURE] Culture and [ICON_GOLDEN_AGE] Golden Age Points when you succeed in an [ICON_SPY] Espionage action in a foreign City, scaling with Era[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_SILVER_FIST] Unit Supply generated by [ICON_CITIZEN] Population[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Free Speech', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Radio
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]+10% [ICON_CULTURE] Culture in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_CULTURE] Culture from [ICON_GREAT_PEOPLE] Great People Improvements and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Constitutionalism', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Telecommunications
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_GOLDEN_AGE] Golden Age Length[ENDCOLOR]
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]+20% [ICON_FOOD] Food, [ICON_RESEARCH] Science, and [ICON_PEACE] Faith during a [ICON_GOLDEN_AGE] Golden Age[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_CITIZEN] Citizens generate +1 [ICON_GOLDEN_AGE] Golden Age Point[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Labor Civics',
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION' UNION ALL
SELECT  '"The night is far spent, the day is at hand; let us therefore cast off the works of darkness, and let us put on the armor of light."[NEWLINE]--The Holy Bible: Romans, 13:12', 
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP' UNION ALL
SELECT 	'Tribalism',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Boredom[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Slavery',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Bronze Working
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_CITIZEN_RED] Laborer in all Cities that can work an additional tile or a specialist slot[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-10% [ICON_FOOD] Growth in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+1 [ICON_HAPPINESS_4] Unhappiness in all Cities with no Courthouses[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Manorialism', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Civil Service
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% Tile improvement rate[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food in Cities for every 5 non-Specialist [ICON_CITIZEN] Citizens[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Caste System', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Guilds
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GREAT_GENERAL] Great General Point and [ICON_GREAT_ADMIRAL] Great Admiral Point in your [ICON_CAPITAL] Capital for every 40 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Specialists produce an additional +1 of their base yield (Exception: Civil Servants produce +1 [ICON_GOLDEN_AGE])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Guilds
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GREAT_GENERAL] Great General Point and [ICON_GREAT_ADMIRAL] Great Admiral Point in your [ICON_CAPITAL] Capital for every 25 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Specialists produce an additional +1 of their base yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cities produce 1 more [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Industrial Servitude', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Industrialization
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_FOOD] Growth in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_PRODUCTION] Production and [ICON_GOLD] in Cities for every 4 non-Specialist [ICON_CITIZEN] Citizens[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Farms, Forts, Mines, Lumbermills, and Villages produce an additional +1 of their base yields[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Unionism', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Electricity
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Guilds, Labor Associations, Credit Unions, Science Institutions, and Civil Departments produce +4 of their respective yields, +2 [ICON_HAPPINESS_1] Happiness, and build 100% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Emancipation', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Globalization
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]25% of [ICON_HAPPINESS_1] Happiness produced in each City is added to the City''s [ICON_CULTURE] Culture per Turn[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_TOURISM] Tourism to civilizations that have less [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Economy Civics', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION' UNION ALL
SELECT  '"Better is bread with a happy heart than wealth with vexation."[NEWLINE]--Amenemope', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP' UNION ALL
SELECT 	'Bartering',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Poverty[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Decentralization',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Trade
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_GOLD] Gold from [ICON_INTERNATIONAL_TRADE] International Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_INTERNATIONAL_TRADE] Trade Routes to City-States generate +0.75 [ICON_INFLUENCE] Influence per turn (with the target City-State) per each owned City-State Trade Route (up to +3.75)[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Commercialism',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Currency
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_FOOD] Food and [ICON_PRODUCTION] Production from [ICON_CONNECTED] City Connections[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+33% [ICON_FOOD] Food and [ICON_PRODUCTION] Production from Internal [ICON_INTERNATIONAL_TRADE] Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Can only create International [ICON_INTERNATIONAL_TRADE] Trade Routes to Allied City-States, Vassals, and Masters[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Free Market', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Economics
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_INTERNATIONAL_TRADE] Trade Route[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+12% [ICON_TOURISM] Tourism modifier for [COLOR_POSITIVE_TEXT]Trade Routes[ENDCOLOR][ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Train Trade Units 25% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'State Property', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]You are missing a Corporate Headquarter', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Corporation
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Corporation
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] Corporate Headquarter produces +10% [ICON_FOOD] Food and [ICON_CULTURE] Culture [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_OFFICE] Corporate Offices produce +4 [ICON_FOOD] Food and +2 [ICON_RESEARCH] Science [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food from [ICON_VP_ENGINEER] Engineers, Mines, Quarries, Lumbermills, and Manufactories[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Scientific Theory
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food to Mine, Quarry, Lumbermill, and Manufactory[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities with a Workshop produce +10% [ICON_FOOD] Food and [ICON_PRODUCTION] Production
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Corporatism', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]You are missing a Corporate Headquarter', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Corporation
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Corporation
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_WONDER] Corporate Headquarter produces +15% [ICON_GOLD] Gold and [ICON_TOURISM] Tourism[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]100% of Base Gold Maintenance from [ICON_VP_OFFICE] Corporate Offices is added as a Gold Bonus[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Each unique [ICON_VP_MONOPOLY] Global Monopoly modifier is increased by an additional 5% if it is percentage-based, or +2 otherwise.[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Industrialization
[NEWLINE][ICON_BULLET]High Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Markets and Banks produce +15% more [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Environmentalism', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Alternative Energy
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold in your [ICON_CAPITAL] Capital for every 2 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_VP_FRANCHISE] Corporate Franchises produce +10 [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_CULTURE] Culture from [ICON_RES_ARTIFACTS] Landmarks, Forests, Jungles, Marshes, Flood Plains, Oases, Atolls, and Natural Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-1 [ICON_FOOD] Food from Farms[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-3 [ICON_PRODUCTION] Production from Mines, Quarries, Lumbermills, and Manufactories[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Religion Civics', 
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION' UNION ALL
SELECT  '"Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do."[NEWLINE]--St. Thomas Aquinas',
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP' UNION ALL
SELECT 	'Paganism',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from Religious Unrest[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Ancestor Veneration', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Calendar
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_PEACE] Faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Unlocks the faith purchases of Altars (50 [ICON_PEACE] Faith cost, +1 [ICON_PEACE] Faith, +1 [ICON_CULTURE_LOCAL] Border Growth Point)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Altars generate +10% [ICON_PEACE] Faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_PEACE] Faith from Natural Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Organized Faith',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]Your Majority Religion (if present) does not have an Enhancer or a Reformation Belief.',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Philosophy
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Majority Religion that has an Enhancer or Reformation Belief
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Religious Founder building produce +5% of all yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_PRODUCTION] Production from Temples, Holy Sites, and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 )  UNION ALL
SELECT  '[ICON_BULLET]Requires Philosophy
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +1 [ICON_PRODUCTION] Production and [ICON_PEACE] faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Temple, Holy Sites, and Landmarks generate +3 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 )  UNION ALL
SELECT  'Theocracy', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3' UNION ALL
SELECT  '[NEWLINE] [ICON_BULLET]You are missing a Majority Religion.',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_DISABLED' UNION ALL
SELECT  '[ICON_BULLET]Requires Theology
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Majority Religion
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Military Units heal 5 additional HP per turn in non-hostile territory and gain [ICON_PEACE] Faith from defeated enemy units[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_RESEARCH] Science[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_GOLD] Gold from Temple, Holy Sites, and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Pacifism', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Biology
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_GREAT_PEOPLE] Great People Generation Rate (doubled during [ICON_GOLDEN_AGE] Golden Ages)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLDEN_AGE] Golden Age Point to Specialists[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+50% [ICON_HAPPINESS_3] from [ICON_WAR] War Weariness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+100% Unit Maintenance (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Biology
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+25% [ICON_GREAT_PEOPLE] Great People Generation Rate (doubled during [ICON_GOLDEN_AGE] Golden Ages)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_CULTURE] Culture[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+100% Base Unit Maintenance (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Celebrity Worship', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Flight
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Unlocks the construction of Idols (+1 [ICON_GOLDEN_AGE] Golden Age Point)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Idols generate +3 [ICON_CULTURE] Culture, +2 [ICON_TOURISM] Tourism, and +1 [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_CULTURE] Culture from Holy Sites and [ICON_RES_ARTIFACTS] Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Free Religion', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Penicilin
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness and +10% [ICON_RESEARCH] Science in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 to all City Yields for every World Religion that has at least one Follower in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Penicilin
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Taxes',
		'TXT_KEY_TAX' UNION ALL
SELECT  'Altar',
		'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT  'Can only be faith purchased if you adopt [COLOR_MAGENTA]{TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7}[ENDCOLOR].',
		'TXT_KEY_ANCESTOR_WORSHIP_HELP' UNION ALL
SELECT  'Idol',
		'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT  'Might Makes Right',
		'TXT_KEY_PROMOTION_HEREDITARYRULE' UNION ALL
SELECT  '+10% [ICON_STRENGTH] Combat Strength when [COLOR_POSITIVE_TEXT]adjacent to or stationed in a friendly City[ENDCOLOR].',
		'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP' UNION ALL
SELECT  'Theocratic Warrior',
		'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL
SELECT  '[COLOR_POSITIVE_TEXT]Heal +5 HP[ENDCOLOR] per turn in non-enemy territory.[NEWLINE][NEWLINE]Gain 50% of the [ICON_STRENGTH] Combat Strength of defeated Enemy Unit as [ICON_PEACE] Faith',
		'TXT_KEY_PROMOTION_DEUSVULT_HELP'; --UNION ALL
--SELECT  'What are Civics?',
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q1_DESC' UNION ALL
--SELECT  'Maintenance, Revolution, Diplomacy?', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q2_DESC' UNION ALL
--SELECT  'Chance of Revolution?',
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q3_DESC' UNION ALL
--SELECT  'Civics and Reform Installed!', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_DESC' UNION ALL
--SELECT  'Congratulations, Civics and Reform have been activated successfully. You will find this mod to have a considerable amount of influence from Civilization IV''s concept of Civics. I hope it will influence your government decisions in how you manage your Civilization! Experiment around and enjoy! If your game does not have Event System enabled, this mod will not function properly.', 
--		'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_HELP' UNION ALL
--SELECT  'Hereditary Rule Unlocked[NEWLINE][NEWLINE]Hereditary Rule is a form of government wherein the rulership is passed down from one member of the family to the next. The strength of hereditary rule is that there is usually a clear line of succession, and thus perhaps less squabbling for power when the current monarch dies. However, hereditary rule suffers the same kind of weaknesses as do all unelected rulers: the leader is not answerable to the people, and it can be extremely difficult to get rid of a bad one.',
--		'TXT_KEY_TUTORIAL_HEREDITARY_RULE_HELP';
--------------------------------------------------------------------------------------------------------------------------
--INSERT INTO CustomTutorials (Type, Description, Help, AdvisorType, AudioSound, DoNotRepeat)
--SELECT 'TUTORIAL_VP_CIVICS', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_DESC', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_HELP', 'ADVISOR_MILITARY', 'AS2D_M_A_ADVISOR_SPEECH_EXCUSE_ME', 1 UNION ALL
--SELECT 'CIVIC_HEREDITARY_RULE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_TUTORIAL_HEREDITARY_RULE_HELP', 'ADVISOR_MILITARY', 'AS2D_M_A_ADVISOR_SPEECH_EXCUSE_ME', 1;

--INSERT INTO CustomTutorial_Questions (TutorialType, ConceptType, Description)
--SELECT 'TUTORIAL_VP_CIVICS', 'CONCEPT_CIVICS_INTRODUCTION', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q3_DESC' UNION ALL
--SELECT 'TUTORIAL_VP_CIVICS', 'CONCEPT_CIVICS_INTRODUCTION', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q2_DESC' UNION ALL
--SELECT 'TUTORIAL_VP_CIVICS', 'CONCEPT_CIVICS_INTRODUCTION', 'TXT_KEY_TUTORIAL_CIVIC_INTRODUCTION_Q1_DESC';

INSERT INTO Events (Type, Description, Help, EventArt, RandomChance, NumChoices, IgnoresGlobalCooldown, EventCooldown)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC', 'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP', 'GovernmentCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC', 'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP', 'LegalCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC', 'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP', 'LaborCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC', 'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP', 'EconomyCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC', 'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP', 'ReligionCivics.dds', -1, 7, 1, 0;

INSERT INTO EventChoices (Type, Description, Help, EventDuration, PrereqTech)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP', -1, 'TECH_ARCHERY'  UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP', -1, 'TECH_WRITING' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP', -1, 'TECH_EDUCATION' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP', -1, 'TECH_PRINTING_PRESS' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP', -1, 'TECH_RIFLING' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP', -1, 'TECH_ATOMIC_THEORY' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP', -1, 'TECH_MATHEMATICS'  UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP', -1, 'TECH_CHIVALRY' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP', -1, 'TECH_PHYSICS' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP', -1, 'TECH_MILITARY_SCIENCE' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP', -1, 'TECH_RADIO' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP', -1, 'TECH_TELECOM' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP', -1, 'TECH_BRONZE_WORKING'  UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP', -1, 'TECH_CIVIL_SERVICE' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP', -1, 'TECH_GUILDS' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP', -1, 'TECH_INDUSTRIALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP', -1, 'TECH_ELECTRICITY' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP', -1, 'TECH_GLOBALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP', -1, 'TECH_HORSEBACK_RIDING' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP', -1, 'TECH_CURRENCY'  UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP', -1, 'TECH_ECONOMICS' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP', -1, 'TECH_SCIENTIFIC_THEORY' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP', -1, 'TECH_INDUSTRIALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP', -1, 'TECH_ECOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP', -1, 'TECH_CALENDAR' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP', -1, 'TECH_PHILOSOPHY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP', -1, 'TECH_THEOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP', -1, 'TECH_BIOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP', -1, 'TECH_FLIGHT' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP', -1, 'TECH_PENICILIN' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', -1, NULL;

INSERT INTO Event_ParentEvents (EventChoiceType, EventType)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_8', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_8', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8', 'PLAYER_EVENT_RELIGIONCIVIC';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1';

UPDATE EventChoices
SET PrereqTech = 'TECH_CORPORATIONS', DisabledTooltip = 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_DISABLED'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE EventChoices
SET PrereqTech = 'TECH_CORPORATIONS', DisabledTooltip = 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_DISABLED'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE EventChoices
SET Expires = 1, EventPromotion = 'PROMOTION_HEREDITARYRULE'
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2';

--UPDATE EventChoices
--SET EventBuildingClassGlobal = 'BUILDINGCLASS_PATRONAGE', Expires = 1, CapitalEffectOnly = 1
--WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_SUFFRAGE', Expires = 1
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_BUREAUCRACYCIVIC', Expires = 1, CapitalEffectOnly = 1
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_NATIONHOOD', Expires = 1, CapitalEffectOnly = 1
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5';

UPDATE EventChoices
SET DisabledTooltip = 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_DISABLED'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2';

UPDATE EventChoices
SET EventPromotion = 'PROMOTION_DEUSVULT', Expires = 1, DisabledTooltip = 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_DISABLED'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3';

INSERT INTO EventChoiceFlavors (EventChoiceType, FlavorType, Flavor)
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_CITY_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_WONDER', 10 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_HAPPINESS', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'FLAVOR_GOLD', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', -3 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_DIPLOMACY', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_SCIENCE', 11 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_OFFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_PRODUCTION', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_GROWTH', 25 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_INFRASTRUCTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GREAT_PEOPLE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_HAPPINESS', 5 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_MILITARY_TRAINING', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_DIPLOMACY', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_OFFENSE', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_DEFENSE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_WONDER', 15 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_ESPIONAGE', 5 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', 15 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_SCIENCE', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_GROWTH', 3 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_RELIGION', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_GROWTH', -5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_HAPPINESS', -4 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_TILE_IMPROVEMENT', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_GROWTH', 10 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_MILITARY_TRAINING', 1 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_PRODUCTION', 15 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_GROWTH', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_PRODUCTION', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_SCIENCE', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_GREAT_PEOPLE', 10 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 15 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'FLAVOR_DIPLOMACY', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_GROWTH', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_I_LAND_TRADE_ROUTE', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_I_SEA_TRADE_ROUTE', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_I_TRADE_DESTINATION', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_I_TRADE_ORIGIN', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_GROWTH', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_SCIENCE', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_TILE_IMPROVEMENT', 3 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_PRODUCTION', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_CULTURE', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_TILE_IMPROVEMENT', 5 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 12 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_PRODUCTION', -2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_RELIGION', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_RELIGION', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_SCIENCE', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_OFFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_RELIGION', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_GOLD', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_HAPPINESS', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_OFFENSE', -5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 15 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_CULTURE', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_SCIENCE', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_HAPPINESS', 10 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_RELIGION', -1;

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_TAX', 'BUILDING_TAXTAXTAX', 'TXT_KEY_TAX' UNION ALL
--SELECT 'BUILDINGCLASS_PATRONAGE', 'BUILDING_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT 'BUILDINGCLASS_BUREAUCRACYCIVIC', 'BUILDING_BUREAUCRACYCIVIC', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4' UNION ALL
SELECT 'BUILDINGCLASS_ANCESTOR_WORSHIP', 'BUILDING_ANCESTOR_WORSHIP', 'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT 'BUILDINGCLASS_NATIONHOOD', 'BUILDING_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT 'BUILDINGCLASS_STATE_ATHEISM', 'BUILDING_STATE_ATHEISM', 'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT 'BUILDINGCLASS_SUFFRAGE', 'BUILDING_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6';

INSERT INTO Buildings (Type, Description, BuildingClass, Cost, PrereqTech, ArtDefineTag, MinAreaSize, NeverCapture, NukeImmune, HurryCostModifier, PortraitIndex, IconAtlas, GreatWorkCount, FaithCost, ReligiousPressureModifier, IsDummy)
SELECT 'BUILDING_TAXTAXTAX', 'TXT_KEY_TAX', 'BUILDINGCLASS_TAX', -1, NULL, 'NONE', -1, 0, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
--SELECT 'BUILDING_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'BUILDINGCLASS_PATRONAGE', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_BUREAUCRACYCIVIC', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4', 'BUILDINGCLASS_BUREAUCRACYCIVIC', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION', 'BUILDINGCLASS_ANCESTOR_WORSHIP', -1, NULL, 'NONE', -1, 0, 1, (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_SHRINE'), 4, 'MORE_SPECIALIST_ATLAS', 0, 50, 0, 0 UNION ALL
SELECT 'BUILDING_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 'BUILDINGCLASS_NATIONHOOD', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION All
SELECT 'BUILDING_STATE_ATHEISM', 'TXT_KEY_STATE_ATHEISM_DESCRIPTION', 'BUILDINGCLASS_STATE_ATHEISM', (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_WIRE_SERVICE'), NULL, 'NONE', -1, 1, 1, -1, 5, 'MORE_SPECIALIST_ATLAS', 0, 0, 0, 0 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'BUILDINGCLASS_SUFFRAGE', -1, NULL, 'NONE', -1, 1, 1, -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1;

UPDATE Buildings
SET ConquestProb = 100
WHERE Type = 'BUILDING_TAXTAXTAX';

--UPDATE Buildings
--SET CapitalOnly = 1
--WHERE Type = 'BUILDING_PATRONAGE';

UPDATE Buildings
SET CapitalOnly = 1, CityAutomatonWorkersChange = 7
WHERE Type = 'BUILDING_BUREAUCRACYCIVIC';

UPDATE Buildings
SET CapitalOnly = 1
WHERE Type = 'BUILDING_NATIONHOOD';

UPDATE Buildings
SET PolicyType = 'POLICY_CIVIC_ANCESTOR_WORSHIP', Help = 'TXT_KEY_ANCESTOR_WORSHIP_HELP'
WHERE Type = 'BUILDING_ANCESTOR_WORSHIP';

UPDATE Buildings
SET PolicyType = 'POLICY_CIVIC_STATE_ATHEISM', GoldMaintenance = 1
WHERE Type = 'BUILDING_STATE_ATHEISM';

INSERT INTO Building_YieldFromSpyAttack (BuildingType, YieldType, Yield)
SELECT 'BUILDING_NATIONHOOD', 'YIELD_GOLDEN_AGE_POINTS', 25 UNION ALL
SELECT 'BUILDING_NATIONHOOD', 'YIELD_CULTURE', 25;

--INSERT INTO Building_YieldPerFriend (BuildingType, YieldType, Yield)
--SELECT 'BUILDING_PATRONAGE', 'YIELD_TOURISM', 1 UNION ALL
--SELECT 'BUILDING_PATRONAGE', 'YIELD_GOLD', 1;

--INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
--SELECT 'BUILDING_PATRONAGE', 'YIELD_TOURISM', 3 UNION ALL
--SELECT 'BUILDING_PATRONAGE', 'YIELD_GOLD', 3;

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_SUFFRAGE', 'YIELD_FOOD', 25 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'YIELD_PRODUCTION', 25 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'YIELD_GOLD', 25;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'YIELD_FAITH', 1 UNION ALL
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
SELECT 'BUILDING_STATE_ATHEISM', 'YIELD_GOLDEN_AGE_POINTS', 1;

INSERT INTO UnitPromotions (Type, Description, Help, Sound, CannotBeChosen, PortraitIndex, IconAtlas, PediaType, PediaEntry)
SELECT 'PROMOTION_DEUSVULT', 'TXT_KEY_PROMOTION_DEUSVULT', 'TXT_KEY_PROMOTION_DEUSVULT_HELP', 'AS2D_IF_LEVELUP', 1, 1, 'MORE_SPECIALIST_ATLAS2', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL 
SELECT 'PROMOTION_HEREDITARYRULE', 'TXT_KEY_PROMOTION_HEREDITARYRULE', 'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP', 'AS2D_IF_LEVELUP', 1, 0, 'MORE_SPECIALIST_ATLAS2', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_HEREDITARYRULE';

UPDATE UnitPromotions
SET IsNearbyPromotion = 1, NearbyRange = 1, NearbyFriendlyCityCombatMod = 10
WHERE Type = 'PROMOTION_HEREDITARYRULE';

UPDATE UnitPromotions
SET FriendlyHealChange = 5, NeutralHealChange = 5
WHERE Type = 'PROMOTION_DEUSVULT';

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_DEUSVULT', 'YIELD_FAITH', 50;

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_FIGHTER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_BOMBER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_CARRIER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_SUBMARINE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_FIGHTER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_BOMBER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_CARRIER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_SUBMARINE';

--INSERT INTO UnitPromotions_YieldChanges (PromotionType, YieldType, Yield)
--SELECT 'PROMOTION_HEREDITARYRULE', 'YIELD_GOLD', 1 UNION ALL
--SELECT 'PROMOTION_HEREDITARYRULE', 'YIELD_PRODUCTION', 1;