UPDATE Language_ko_KR
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION_HELP';

UPDATE Language_ko_KR
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO_HELP';

UPDATE Language_ko_KR
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_WAR_ACADEMY_HELP';

UPDATE Language_ko_KR
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_SEA_ACADEMY_HELP';

UPDATE Language_ko_KR
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_AIR_ACADEMY_HELP';

UPDATE Language_ko_KR
SET Text = '전투에서 얻는 경험치 50% 증가, [ICON_MOVES] 이동력 +1'
WHERE Tag = 'TXT_KEY_PROMOTION_FA_SEA_ACADEMY_HELP';