UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '전통 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_TRADITION} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PUBLIC_BATHS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '진보 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_LIBERTY} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_TOWN_COUNCIL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_GOLD] 골드 +1'
	WHERE Tag = 'TXT_KEY_POLICY_COLLECTIVE_RULE_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_GOLDEN_AGE] 황금기 점수 +1'
	WHERE Tag = 'TXT_KEY_POLICY_CITIZENSHIP_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_PRODUCTION] 생산력 +1'
	WHERE Tag = 'TXT_KEY_POLICY_REPUBLIC_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_RESEARCH] 과학 +1'
	WHERE Tag = 'TXT_KEY_POLICY_REPRESENTATION_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_FOOD] 식량 +1'
	WHERE Tag = 'TXT_KEY_POLICY_MERITOCRACY_HELP';
	
UPDATE Language_ko_KR
	SET TEXT = REPLACE(Text, '성을 향해', '영주 저택을 향해, 성,')
	WHERE Tag = 'TXT_KEY_POLICY_MANDATE_OF_HEAVEN_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '권위 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_HONOR} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_STRONGHOLD}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '충성 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_PIETY} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_RELIQUARY}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '외교 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_PATRONAGE} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_STATE_EMBASSY}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '미학 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_AESTHETICS} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_MEMORIAL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '산업 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_COMMERCE} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PATENT_OFFICE}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '제국 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_EXPLORATION} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_DEPOT}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '합리 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_RATIONALISM} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';

INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', '시스턴'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', '시청'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', '성채'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', '영주 저택'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_CHANCERY', '대사관'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_MEMORIAL', '기념비'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_DEPOT', '창고'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', '식물원'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', '특허청'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_CISTERN_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_RELIQUARY_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STATE_EMBASSY_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', '도시 내 위대한 [ICON_GREAT_WRITER] 작가, [ICON_GREAT_ARTIST] 예술가, [ICON_GREAT_MUSICIAN] 음악가에게 [ICON_GREAT_PEOPLE] 위인 점수 +1를 줍니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', ''),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', '');