INSERT INTO Language_ko_KR (Tag, Text, Plurality)
SELECT 'TXT_KEY_CITYSTATE_CLERMONT', '클레몬트' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CLERMONT_ADJ', '클레몬트의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_CLERMONT_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_HONDURAS', '온두라스' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_HONDURAS_ADJ', '온두라스의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_HONDURAS_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_HONDURAS}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AUCKLAND', '오클랜드' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AUCKLAND_ADJ', '오클랜드의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_AUCKLAND_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_AUCKLAND}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ARMAGH', '아마 ' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ARMAGH_ADJ', '아마의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_ARMAGH_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_ARMAGH}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUSCAT', '무스카트' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUSCAT_ADJ', '무스카트의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_MUSCAT_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_MUSCAT}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GRANADA', '그라나다' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GRANADA_ADJ', '그라나다의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_GRANADA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_GRANADA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NANMANDOL', '레루' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NANMANDOL_ADJ', '레루의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_NANMANDOL_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_NANMANDOL}' , 2 UNION ALL
SELECT '', '[COLOR_YELLOW]성전의 열의[ENDCOLOR][NEWLINE][ICON_BULLET]새로 훈련된 근접 및 화약 유닛에 첫 전투에따라 무작위 승급 부여[NEWLINE][ICON_BULLET]근접 유닛 전투 경험치 +33%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HONDURAS', '[COLOR_YELLOW]바나나 공화국[ENDCOLOR][NEWLINE][ICON_BULLET]도시 국가에서 제공하는 자원도 글로벌 독점에 포함' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_AUCKLAND', '[COLOR_YELLOW]타마키 마카우라우[ENDCOLOR][NEWLINE][ICON_BULLET]해안 도시의 [ICON_FOOD]식량 +3' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ARMAGH', '[COLOR_YELLOW]성도 후원자[ENDCOLOR][NEWLINE][ICON_BULLET]신앙으로 위대한 성인 구매 가능 (대중 종교 필요)' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MUSCAT', '[COLOR_YELLOW]은둔의 항구[ENDCOLOR][NEWLINE][ICON_BULLET]등대, 항만, 항구의 [ICON_GOLD]골드 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GRANADA', '[COLOR_YELLOW]알카자르[ENDCOLOR][NEWLINE][ICON_BULLET]요새, 성채의 [ICON_CULTURE]문화 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_NANMANDOL', '[COLOR_YELLOW]천상의 보초[ENDCOLOR][NEWLINE][ICON_BULLET]해양 타일의 [ICON_CULTURE]문화 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0', '심판' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0_HELP', '전투 경험치 +33%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1', '클레몬트의 축복' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1_HELP', '첫 전투에 따라 임시로 무작위 [ICON_STRENGTH]전투력 보너스 제공' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2', '서두름' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2_HELP', '[ICON_MOVES]이동력 +2. 공격 후 이동 가능' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3', '대동단결' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3_HELP', '우호 유닛 인접 시 [ICON_STRENGTH]전투력 보너스 +25%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4', '충전' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4_HELP', '공격 시 [ICON_STRENGTH]전투력 보너스 +15%. 요새화한 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 +25%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5', '보강' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5_HELP', '방어 시 [ICON_STRENGTH]전투력 보너스 +15%. 공격 후 회복 가능' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6', '하느님께 영광을' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6_HELP', '위대한 장군처럼 인접한 유닛에 [ICON_STRENGTH]전투력 보너스 제공. 이 유닛과 인접한 타일의 모든 유닛은 매 턴 체력 회복 +5' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH1', 'St.파트리쿠스' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH1_HELP', '무료에서 오는 [ICON_HAPPINESS_3]불행 감소[NEWLINE][NEWLINE]반드시 [COLOR_YELLOW]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH2', 'St.베닝구스' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH2_HELP', '문맹에서 오는 [ICON_HAPPINESS_3]불행 감소[NEWLINE][NEWLINE]반드시 [COLOR_YELLOW]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH3', 'St.세쿤디누스' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH3_HELP', '빈곤에서 오는 [ICON_HAPPINESS_3]불행 감소[NEWLINE][NEWLINE]반드시 [COLOR_YELLOW]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH4', 'St.셀레스티누스' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH4_HELP', '곤경에서 오는 [ICON_HAPPINESS_3]불행 감소[NEWLINE][NEWLINE]반드시 [COLOR_YELLOW]아마[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' , 2 ;
