INSERT INTO Language_ko_KR (Tag, Text)
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ALMATY', '[COLOR_YELLOW]알마투[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_TRADE]도시 연결에서 [ICON_RESEARCH]과학 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTANANARIVO', '[COLOR_YELLOW]해적 피난항[ENDCOLOR][NEWLINE][ICON_BULLET]처치한 적의 전투력 100%만큼 [ICON_GOLD]골드 제공' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTWERP', '[COLOR_YELLOW]이코노믹스 프로망스[ENDCOLOR][NEWLINE][ICON_BULLET]상인 전문가의 +2 [ICON_GOLD]골드' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BELGRADE', '[COLOR_YELLOW]백색 요새[ENDCOLOR][NEWLINE][ICON_BULLET]공성 유닛 체력 +25' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BOGOTA', '[COLOR_YELLOW]독립 연합[ENDCOLOR][NEWLINE][ICON_BULLET]점령한 도시가 [ICON_CULTURE]문화 20 제공 [NEWLINE][ICON_BULLET]해방시킨 도시는 시대 및 도시 수에 따라 [ICON_CULTURE]문화 15~45 제공' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BRATISLAVA', '[COLOR_YELLOW]슬라브 문화의 심장[ENDCOLOR][NEWLINE][ICON_BULLET]길드의 [ICON_CULTURE]문화 +2 [ICON_TOURISM]관광 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BRUSSELS', '[COLOR_YELLOW]습지의 고향[ENDCOLOR][NEWLINE][ICON_BULLET]습지 타일의 [ICON_CULTURE]문화 +1[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]습지 복원 시설[ENDCOLOR]건설 가능' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BUCHAREST', '[COLOR_YELLOW]동방의 파리[ENDCOLOR][NEWLINE][ICON_BULLET]걸작에서 오는 [ICON_CULTURE]문화 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BUDAPEST', '[COLOR_YELLOW]다뉴브의 진주[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_RES_HORSE]말 +5 제공[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BUENOS_AIRES', '[COLOR_YELLOW]민중의 소리[ENDCOLOR][NEWLINE][ICON_BULLET]보너스 자원의 [ICON_CULTURE]문화 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_BYBLOS', '[COLOR_YELLOW]레바논 삼나무[ENDCOLOR][NEWLINE][ICON_BULLET]어선, 호수, 오아시스 타일의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CAHOKIA', '[COLOR_YELLOW]카호키아 유적[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]카호키아 마운드[ENDCOLOR] 시설 건설 가능[NEWLINE][ICON_BULLET]마운드의 [ICON_GOLD]골드 +1 [ICON_PEACE]신앙 +1[NEWLINE][ICON_BULLET]마을 인접 시 [ICON_GOLD]골드 +1 [ICON_PEACE]신앙 +1[NEWLINE][ICON_BULLET]인접 도시에 [ICON_GOLDEN_AGE]황금기 점수 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CAPE_TOWN', '[COLOR_YELLOW]희망의 봉우리[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_INTERNATIONAL_TRADE]교역로 범위 +10%[NEWLINE][ICON_BULLET][ICON_INTERNATIONAL_TRADE]교역로가 끝나는 도시의 [ICON_CITIZEN]시민 수에 따라 [ICON_GOLD]골드 20~40 제공' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_COLOMBO', '[COLOR_YELLOW]쿠베라[ENDCOLOR][NEWLINE][ICON_BULLET]정글, 숲 타일의 [ICON_GOLD]골드 +2[NEWLINE][ICON_BULLET]제재소 및 벌목장 건설 시 [ICON_GOLD]골드 [COLOR_NEGATIVE_TEXT]-2[ENDCOLOR]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_FLORENCE', '[COLOR_YELLOW]르네상스의 요람[ENDCOLOR][NEWLINE][ICON_BULLET]채석장의 [ICON_CULTURE]문화 +1[NEWLINE][ICON_BULLET]예술가 전문가의 [ICON_GOLDEN_AGE]황금기 점수 +2' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GENEVA', '[COLOR_YELLOW]교회론[ENDCOLOR][NEWLINE][ICON_BULLET]도시의 [ICON_CITIZEN]시민 5명당 [ICON_PEACE]신앙 +1'UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GENOA', '[COLOR_YELLOW]라 수페르바[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_GREAT_PEOPLE]위인이 출현할 때 [ICON_GOLD]골드 50[NEWLINE][ICON_BULLET][ICON_GOLDEN_AGE]황금기 점수 15' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HANOI', '[COLOR_YELLOW]애국심[ENDCOLOR][NEWLINE][ICON_BULLET]우호 영토 내 [ICON_STRENGTH]전투력 +10%' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HONG_KONG', '[COLOR_YELLOW]국가 번영[ENDCOLOR][NEWLINE][ICON_BULLET]도시의 [ICON_CITIZEN]시민 6명당 [ICON_GOLD]골드 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_IFE', '[COLOR_YELLOW]요루바[ENDCOLOR][NEWLINE][ICON_BULLET]도시의 국경이 확장될 때 [ICON_PEACE]신앙 +3 [NEWLINE][ICON_BULLET]성소의 국경 확장 점수 +2' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_JERUSALEM', '[COLOR_YELLOW]성스러운 도시[ENDCOLOR][NEWLINE][ICON_BULLET]동맹인 문명의 수도와 같은 대중 종교를 채택[NEWLINE][ICON_BULLET]예루살렘의 대한 "영향권" 제공[NEWLINE][ICON_BULLET]성도와 같은 종교 압력을 가짐' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KABUL', '[COLOR_YELLOW]지상 낙원[ENDCOLOR][NEWLINE][ICON_BULLET]도시 주변 산 타일 1개마다 [ICON_CULTURE]문화 +0.66' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KATHMANDU', '[COLOR_YELLOW]더 마운틴[ENDCOLOR][NEWLINE][ICON_BULLET]도시 주변 산 타일 1개마다 [ICON_PEACE]신앙 +0.66' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KIEV', '[COLOR_YELLOW]오래된 이야기[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]빌리나[ENDCOLOR] 건설 가능 (걸작 음악 슬롯 +1)' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KUALA_LUMPUR', '[COLOR_YELLOW]진흙투성이 강[ENDCOLOR][NEWLINE][ICON_BULLET]우물의 [ICON_CULTURE]문화 +5%, 물레방앗간의 [ICON_CULTURE]문화 +2' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KYZYL', '[COLOR_YELLOW]아시아의 중심[ENDCOLOR][NEWLINE][ICON_BULLET]궁전, 기념비의 [ICON_TOURISM]관광 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LA_VENTA', '[COLOR_YELLOW]의례적 창조물[ENDCOLOR] 위인 시설에 [ICON_PEACE]신앙 +1, 성소의 [ICON_PEACE]신앙 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LHASA', '[COLOR_YELLOW]신의 정원[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_GREAT_PEOPLE]위인이 출현할 때 [ICON_PEACE]신앙 25 [NEWLINE][ICON_BULLET][COLOR_YELLOW]포탈라 궁[ENDCOLOR] 불가사의 건설 가능' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MALACCA', '[COLOR_YELLOW]해협 식민지[ENDCOLOR][NEWLINE][ICON_BULLET]사치 자원의 +1 [ICON_GOLD]골드' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MANILA', '[COLOR_YELLOW]동양의 진주[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_INTERNATIONAL_TRADE]교역로가 끝나는 도시의 [ICON_CITIZEN]시민 수에 따라 [ICON_FOOD]식량 [ICON_PRODUCTION]생산 1~15 제공' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MBANZA_KONGO', '[COLOR_YELLOW]마니콩고의 영광[ENDCOLOR][NEWLINE][ICON_BULLET]숲, 정글, 습지, 범람원 타일에서 전투 시 [ICON_STRENGTH]전투력 보너스 +15%' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MELBOURNE', '[COLOR_YELLOW]골드 러쉬[ENDCOLOR][NEWLINE][ICON_BULLET]광산, 위인 시설의 [ICON_GOLD]골드 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MILAN', '[COLOR_YELLOW]비스콘티 특사[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]비스콘티 저택[ENDCOLOR] 건설 가능 (걸작 예술품 슬롯 +1)' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MOGADISHU', '[COLOR_YELLOW]떠오르는 해양 도시[ENDCOLOR][NEWLINE][ICON_BULLET]범람원, 해양 타일의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MOMBASA', '[COLOR_YELLOW]개발도상 연합[ENDCOLOR][NEWLINE][ICON_BULLET]모든 보너스 자원의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MONACO', '[COLOR_YELLOW]금융 천국[ENDCOLOR][NEWLINE][ICON_BULLET]시장, 은행의 [ICON_CULTURE]문화 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ORMUS', '[COLOR_YELLOW]보석 반지[ENDCOLOR][NEWLINE][ICON_BULLET]모든 사치 자원의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PANAMA_CITY', '[COLOR_YELLOW]파나마 운하[ENDCOLOR][NEWLINE][ICON_BULLET]요새, 성채, 부교의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PRAGUE', '[COLOR_YELLOW]프라하 성[ENDCOLOR][NEWLINE][ICON_BULLET]성벽, 성의 [ICON_CULTURE]문화 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_QUEBEC_CITY', '[COLOR_YELLOW]일백조합인상사[ENDCOLOR][NEWLINE][ICON_BULLET]야영지, 제재소, 벌목장의 [ICON_GOLD]골드 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_RAGUSA', '[COLOR_YELLOW]해양 종속국[ENDCOLOR][NEWLINE][ICON_BULLET]우호 및 동맹인 도시 국가가 모든 도시에 [ICON_FOOD]식량 +1 제공, 대사관 시설의 [ICON_FOOD]식량 +1 ' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_RIGA', '[COLOR_YELLOW]라트비아 상업중심지[ENDCOLOR][NEWLINE][ICON_BULLET]도시의 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]+3%[ENDCOLOR]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SAMARKAND', '[COLOR_YELLOW]소그드[ENDCOLOR][NEWLINE][ICON_BULLET]국제 [ICON_INTERNATIONAL_TRADE]교역로의 [ICON_GOLD]골드 +4' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SIDON', '[COLOR_YELLOW]이웃집 불청객[ENDCOLOR][NEWLINE][ICON_BULLET]동맹일 때 시돈에 대한 "영향권" 제공[NEWLINE][ICON_BULLET]적 영토 내 군사 유닛의 체력이 매 턴 +5 회복' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SINGAPORE', '[COLOR_YELLOW]발전된 부[ENDCOLOR][NEWLINE][ICON_BULLET]모든 외교 유닛에 [COLOR_PURPLE_PLAYER]귀족[ENDCOLOR] 승급 부여' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SOFIA', '[COLOR_YELLOW]세르디카[ENDCOLOR][NEWLINE][ICON_BULLET]위대한 장군 및 위대한 제독이 인접 유닛에 추가 [ICON_STRENGTH]전투력 보너스 +5%' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SYDNEY', '[COLOR_YELLOW]자본 인프라[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_HAPPINESS_1]국왕 경축일에 [ICON_FOOD]식량 +5%' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_TYRE', '[COLOR_YELLOW]고대의 유적[ENDCOLOR][NEWLINE][ICON_BULLET]걸작, 랜드마크 시설의 [ICON_GOLD]골드 +2' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_UR', '[COLOR_YELLOW]문명의 요람[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_TRADE]도시 연결에서 [ICON_FOOD]식량 +2' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VALLETTA', '[COLOR_YELLOW]그랜드 하버[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]그랜드 하버[ENDCOLOR] 건설 가능' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VANCOUVER', '[COLOR_YELLOW]터미널 시티[ENDCOLOR][NEWLINE][ICON_BULLET]마을, 위인 시설의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VATICAN_CITY', '[COLOR_YELLOW]절대 믿음[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_PEACE]신앙 구매 비용 -10%' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_VILNIUS', '[COLOR_YELLOW]북쪽의 아테네[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]여명의 문[ENDCOLOR] 건설 가능 (걸작 문학 슬롯 +1)' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_WELLINGTON', '[COLOR_YELLOW]타라의 위대한 항구[ENDCOLOR][NEWLINE][ICON_BULLET]전략 자원의 [ICON_FOOD]식량 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_WITTENBERG', '[COLOR_YELLOW]종교 개혁의 탄생[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 종교적 분쟁의 오는 [ICON_HAPPINESS_3]불행 -5%[NEWLINE][ICON_BULLET]공무원, 근로자의 [ICON_PEACE]신앙 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_YEREVAN', '[COLOR_YELLOW]손자병법[ENDCOLOR][NEWLINE][ICON_BULLET]처치한 적의 전투력 50%만큼 [ICON_CULTURE]문화 제공' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ZANZIBAR', '[COLOR_YELLOW]향신료의 섬[ENDCOLOR][NEWLINE][ICON_BULLET]보너스, 전략 자원의 [ICON_GOLD]골드 +1' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ZURICH', '[COLOR_YELLOW]금융 박람회[ENDCOLOR][NEWLINE][ICON_BULLET]화폐 주조소의 [ICON_GOLD]골드 +2%';

UPDATE Language_ko_KR
SET Text = '당신은 {1_CityStateName:textkey}의 [COLOR_POSITIVE_TEXT]동맹[ENDCOLOR]입니다. 만약 당신이 동맹을 잃게 된다면 보너스는 [COLOR_FONT_RED]3[ENDCOLOR]턴 동안만 지속될 것입니다. 매 턴 해당 도시 국가와의 [ICON_INFLUENCE]영향력이 {2_Num} 변경됩니다. {1_CityStateName:textkey}{@1_CityStateName: plural 1?이; 2?가;} 피해를 받거나 당신이 [COLOR_POSITIVE_TEXT]보호 선언[ENDCOLOR]을 한다면 영향력은 3배 빠르게 감소합니다.'
WHERE Tag = 'TXT_KEY_ALLIES_CSTATE_TT';

UPDATE Language_ko_KR
SET Text = '도시 국가와의 [ICON_INFLUENCE]영향력이 [COLOR_POSITIVE_TEXT]45[ENDCOLOR]에서 시작합니다. 우호 및 동맹인 도시 국가의 산출량이 [COLOR_POSITIVE_TEXT]75%[ENDCOLOR] 증가합니다. 동맹인 도시 국가 수도의 전투력이 [COLOR_POSITIVE_TEXT]25%[ENDCOLOR] 증가합니다. 도시 국가로부터 선물 받은 유닛의 경험치가 [COLOR_POSITIVE_TEXT]10[ENDCOLOR] 증가합니다.'
WHERE Tag = 'TXT_KEY_TRAIT_CITY_STATE_BONUSES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_ALMATY}'
WHERE Tag = 'TXT_KEY_CIV5_ALMATY_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_ANTANANARIVO}'
WHERE Tag = 'TXT_KEY_CIV5_ANTANANARIVO_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_ANTWERP}'
WHERE Tag = 'TXT_KEY_CIV5_ANTWERP_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BELGRADE}'
WHERE Tag = 'TXT_KEY_CIV5_BELGRADE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BOGOTA}'
WHERE Tag = 'TXT_KEY_CIV5_BOGOTA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BRATISLAVA}'
WHERE Tag = 'TXT_KEY_CIV5_BRATISLAVA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BRUSSELS}'
WHERE Tag = 'TXT_KEY_CIV5_BRUSSELS_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BUCHAREST}'
WHERE Tag = 'TXT_KEY_CIV5_BUCHAREST_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BUDAPEST}'
WHERE Tag = 'TXT_KEY_CIV5_BUDAPEST_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BUENOS_AIRES}'
WHERE Tag = 'TXT_KEY_CIV5_BUENOS_AIRES_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_BYBLOS}'
WHERE Tag = 'TXT_KEY_CIV5_BYBLOS_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_CAHOKIA}'
WHERE Tag = 'TXT_KEY_CIV5_CAHOKIA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_CAPE_TOWN}'
WHERE Tag = 'TXT_KEY_CIV5_CAPETOWN_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_COLOMBO}'
WHERE Tag = 'TXT_KEY_CIV5_COLOMBO_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_FLORENCE}'
WHERE Tag = 'TXT_KEY_CIV5_FLORENCE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_GENEVA}'
WHERE Tag = 'TXT_KEY_CIV5_GENEVA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_GENOA}'
WHERE Tag = 'TXT_KEY_CIV5_GENOA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_HANOI}'
WHERE Tag = 'TXT_KEY_CIV5_HANOI_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_IFE}'
WHERE Tag = 'TXT_KEY_CIV5_IFE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_JERUSALEM}'
WHERE Tag = 'TXT_KEY_CIV5_JERUSALEM_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_KABUL}'
WHERE Tag = 'TXT_KEY_CIV5_KABUL_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_KATHMANDU}'
WHERE Tag = 'TXT_KEY_CIV5_SEOUL_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_KIEV}'
WHERE Tag = 'TXT_KEY_CIV5_KIEV_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_KUALA_LUMPUR}'
WHERE Tag = 'TXT_KEY_CIV5_KUALALAMPUR_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_KYZYL}'
WHERE Tag = 'TXT_KEY_CIV5_KYZYL_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_LA_VENTA}'
WHERE Tag = 'TXT_KEY_CIV5_LA_VENTA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_LHASA}'
WHERE Tag = 'TXT_KEY_CIV5_LHASA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MALACCA}'
WHERE Tag = 'TXT_KEY_CIV5_MALACCA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MANILA}'
WHERE Tag = 'TXT_KEY_CIV5_MANILA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MBANZA_KONGO}'
WHERE Tag = 'TXT_KEY_CIV5_MBANZA_KONGO_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MELBOURNE}'
WHERE Tag = 'TXT_KEY_CIV5_MELBOURNE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MILAN}'
WHERE Tag = 'TXT_KEY_CIV5_MILAN_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MOGADISHU}'
WHERE Tag = 'TXT_KEY_CIV5_MOGADISHU_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MOMBASA}'
WHERE Tag = 'TXT_KEY_CIV5_MOMBASA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_MONACO}'
WHERE Tag = 'TXT_KEY_CIV5_MONACO_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_ORMUS}'
WHERE Tag = 'TXT_KEY_CIV5_ORMUS_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_PRAGUE}'
WHERE Tag = 'TXT_KEY_CIV5_PRAGUE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_QUEBEC_CITY}'
WHERE Tag = 'TXT_KEY_CIV5_OSLO_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_PANAMA_CITY}'
WHERE Tag = 'TXT_KEY_CIV5_PANAMA_CITY_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_RAGUSA}'
WHERE Tag = 'TXT_KEY_CIV5_RAGUSA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_RIGA}'
WHERE Tag = 'TXT_KEY_CIV5_RIGA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_SAMARKAND}'
WHERE Tag = 'TXT_KEY_CIV5_SAMARKAND_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_SIDON}'
WHERE Tag = 'TXT_KEY_CIV5_SIDON_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_SINGAPORE}'
WHERE Tag = 'TXT_KEY_CIV5_SINGAPORE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_SOFIA}'
WHERE Tag = 'TXT_KEY_CIV5_SOFIA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_SYDNEY}'
WHERE Tag = 'TXT_KEY_CIV5_COPENHAGEN_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_TYRE}'
WHERE Tag = 'TXT_KEY_CIV5_TYRE_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_UR}'
WHERE Tag = 'TXT_KEY_CIV5_UR_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_VALLETTA}'
WHERE Tag = 'TXT_KEY_CIV5_VALLETTA_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_VANCOUVER}'
WHERE Tag = 'TXT_KEY_CIV5_VANCOUVER_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_VATICAN_CITY}'
WHERE Tag = 'TXT_KEY_CIV5_VATICAN_CITY_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_VILNIUS}'
WHERE Tag = 'TXT_KEY_CIV5_VILNIUS_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_WELLINGTON}'
WHERE Tag = 'TXT_KEY_CIV5_WELLINGTON_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_WITTENBERG}'
WHERE Tag = 'TXT_KEY_CIV5_WITTENBERG_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_YEREVAN}'
WHERE Tag = 'TXT_KEY_CIV5_YEREVAN_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_ZANZIBAR}'
WHERE Tag = 'TXT_KEY_CIV5_ZANZIBAR_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_ZURICH}'
WHERE Tag = 'TXT_KEY_CIV5_ZURICH_TEXT' ;

UPDATE Language_ko_KR
SET Text = '{TXT_KEY_CSTRAIT_MINOR_CIV_HONG_KONG}'
WHERE Tag = 'TXT_KEY_CIV5_HONG_KONG_TEXT' ;