INSERT INTO Language_ko_KR (Tag, Text, Plurality)
SELECT 'TXT_KEY_CITYSTATE_GWYNEDD', '귀네드' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GWYNEDD_ADJ', '귀네드의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_GWYNEDD_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_GWYNEDD}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUISCA', '무이스카' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUISCA_ADJ', '무이스카의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_MUISCA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_MUISCA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LACONIA', '라코니아' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LACONIA_ADJ', '라코니아의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_LACONIA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CHEVAK', '셰바크' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CHEVAK_ADJ', '셰바크의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_CHEVAK_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_CHEVAK}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SANTO_DOMINGO', '산토도밍고' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SANTO_DOMINGO_ADJ', '산토도밍고의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_SANTO_DOMINGO_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_SANTO_DOMINGO}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MANAGUA', '마나과' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MANAGUA_ADJ', '마나과의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_MANAGUA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_MANAGUA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO', '오덴소' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO_ADJ', '오덴소의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_ODENSO_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_YANGCHENG', '양청' , 1 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_YANGCHENG_ADJ', '양청의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_YANGCHENG_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_YANGCHENG}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_PHANOTEUS', '파노테우스' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_PHANOTEUS_ADJ', '파노테우스의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_PHANOTEUS_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_PHANOTEUS}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DOUALA', '두알라' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DOUALA_ADJ', '두알라의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_DOUALA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_DOUALA}' , 2 UNION ALL

SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GWYNEDD', '[COLOR_YELLOW]허우엘 법률[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_GOLDEN_AGE]황금기동안 [ICON_CULTURE]문화 +10%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MUISCA', '[COLOR_YELLOW]황금 도시[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_CITIZEN]시민 2명당 [ICON_GOLD]골드 +1[NEWLINE][ICON_BULLET]제국 전역 [ICON_CITIZEN]시민 30명당 [ICON_GOLD]골드 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA', '[COLOR_YELLOW]스파르타의 규율[ENDCOLOR][NEWLINE][ICON_BULLET]우호 유닛 인접 시 [ICON_STRENGTH]전투력 보너스 +10%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CHEVAK', '[COLOR_YELLOW]알래스카의 바람[ENDCOLOR][NEWLINE][ICON_BULLET]툰드라 타일 4개당 [ICON_FOOD]식량 +1[NEWLINE][ICON_BULLET]설원 타일 3개당 [ICON_FOOD]식량 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SANTO_DOMINGO', '[COLOR_YELLOW]카리브해의 관문[ENDCOLOR][NEWLINE][ICON_BULLET]글로벌 독점에서 오는 행복 및 산출량의 합 +3' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MANAGUA', '[COLOR_YELLOW]빅맨의 도시[ENDCOLOR][NEWLINE][ICON_BULLET]글로벌 독점에서 오는 황금기의 길이 및 산출량의 합 +7%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO', '[COLOR_YELLOW]사냥의 군주[ENDCOLOR][NEWLINE][ICON_BULLET]군사 유닛의 시야 +1[NEWLINE][ICON_BULLET]중립 지역에서 매 턴 체력 회복 +5' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_YANGCHENG', '[COLOR_YELLOW]십이간지[ENDCOLOR][NEWLINE][ICON_BULLET]동물 자원에 [ICON_PEACE]신앙 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PHANOTEUS', '[COLOR_YELLOW]프로메테우스의 선물[ENDCOLOR][NEWLINE][ICON_BULLET]도시 국가 부정 선거 및 쿠데타 확률 +25%[NEWLINE][ICON_BULLET]적 스파이 포획 가능성 +25%[NEWLINE][ICON_BULLET]스파이가 걸작 및 기술을 훔칠 확률 +25%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DOUALA', '[COLOR_YELLOW]호텔 아프리카[ENDCOLOR][NEWLINE][ICON_BULLET]추가 [ICON_INTERNATIONAL_TRADE]교역로 +1' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_CHEVAK', '[ICON_CITY_STATE]알래스카 국립야생보호구역' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_CHEVAK_HELP', '툰드라 타일 4개마다 또는 설원 타일 3개마다 [ICON_FOOD]식량이 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 증가합니다.[NEWLINE][NEWLINE]반드시 [COLOR_YELLOW]셰바크[ENDCOLOR]와 동맹 관계를 유지해야 합니다.' , 2 UNION ALL

SELECT 'TXT_KEY_CITYSTATE_LACONIA_HELP1', '스파르타의 규율' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO_HELP1', '사냥의 군주', 2 ;
