INSERT INTO Language_ko_KR (Tag, Text, Plurality)
SELECT 'TXT_KEY_CITYSTATE_AMBRACIA', '암브라시아' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AMBRACIA_ADJ', '암브라시아의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_AMBRACIA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_AMBRACIA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DJIBOUTI', '지부티' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DJIBOUTI_ADJ', '지부티의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_DJIBOUTI_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_DJIBOUTI}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DODOMA', '도도마' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DODOMA_ADJ', '도도마의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_DODOMA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_DODOMA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_FAYA', '파야' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_FAYA_ADJ', '파야의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_FAYA_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_FAYA}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_KIGALI', '키갈리' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_KIGALI_ADJ', '키갈리의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_KIGALI_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_KIGALI}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NAIROBI', '나이로비' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NAIROBI_ADJ', '나이로비의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_NAIROBI_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_NAIROBI}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_QUELIMANE', '켈리마네' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_QUELIMANE_ADJ', '켈리마네의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_QUELIMANE_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_QUELIMANE}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SIERRA_LEONE', '시에라리온' , 1 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SIERRA_LEONE_ADJ', '시에라리온의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_SIERRA_LEONE_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_SIERRA_LEONE}' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SURREY', '셔리' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SURREY_ADJ', '셔리의' , 2 UNION ALL
SELECT 'TXT_KEY_CIV5_SURREY_TEXT', '{TXT_KEY_CSTRAIT_MINOR_CIV_SURREY}' , 2 UNION ALL

SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_AMBRACIA', '[COLOR_YELLOW]피로스의 용병[ENDCOLOR][NEWLINE][ICON_BULLET]지상 주둔군이 [ICON_PRODUCTION]생산 5% 제공[NEWLINE][ICON_BULLET]도시 국가의 군사 유닛 선물 속도 +50%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DJIBOUTI', '[COLOR_YELLOW]타 넷제루[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 빈곤에서 오는 [ICON_HAPPINESS_3]불행 -5%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DODOMA', '[COLOR_YELLOW]황야의 항해[ENDCOLOR][NEWLINE][ICON_BULLET]해상 유닛 [ICON_STRENGTH]전투력 보너스 +5%[NEWLINE][ICON_BULLET]해상 유닛 [ICON_MOVES]행동력 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_FAYA', '[COLOR_YELLOW]전쟁의 성과[ENDCOLOR][NEWLINE][ICON_BULLET]처치한 적 전투력의 50%만큼 [ICON_RESEARCH]과학 획득' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_KIGALI', '[COLOR_YELLOW]이중 커리큘럼[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 문맹에서 오는 [ICON_HAPPINESS_3]불행 -5%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_NAIROBI', '[COLOR_YELLOW]함무라비[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_HAPPINESS_3]곤경에서 오는 불행 -5%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_QUELIMANE', '[COLOR_YELLOW]좋은 징조의 강[ENDCOLOR][NEWLINE][ICON_BULLET]강 타일에 [ICON_GOLDEN_AGE]황금기 점수 +1' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SIERRA_LEONE', '[COLOR_YELLOW]자유의 왕국[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 무료에서 오는 [ICON_HAPPINESS_3]불행 -5%' , 2 UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SURREY', '[COLOR_YELLOW]장엄한 비행[ENDCOLOR][NEWLINE][ICON_BULLET]해상 및 지상 유닛 대항 시 전투기, 폭격기의 [ICON_STRENGTH]전투력 보너스 +10%' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_QUELIMANE', '[ICON_CITY_STATE]자연보호기금' , 2 UNION ALL
SELECT 'TXT_KEY_BUILDING_QUELIMANE_HELP', '강 타일에서 [ICON_GOLDEN_AGE]황금기 점수를 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 제공합니다.[NEWLINE][NEWLINE]반드시 [COLOR_YELLOW]켈리마네[ENDCOLOR]와 동맹 관계를 유지해야 합니다.', 2 UNION ALL

SELECT 'TXT_KEY_CITYSTATE_AMBRACIA_HELP1', '피로스의 용병' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DODOMA_HELP1', '황야의 항해' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_FAYA_HELP1', '전쟁의 성과' , 2 UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SURREY_HELP1', '장엄한 비행', 2 ;