--======================================================================================================================
-- Language_ko_KR
--======================================================================================================================
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_BARRACKS}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_HEROIC_EPIC');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_MONUMENT_DESC}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_NATIONAL_EPIC');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_LIBRARY}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_NATIONAL_COLLEGE');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with an [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_COLOSSEUM}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_CIRCUS_MAXIMUS');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_WORKSHOP}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_IRONWORKS');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_EE_MANOR}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_EE_SUMMER_PALACE')
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_EE_MANOR');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_UNIVERSITY}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_OXFORD_UNIVERSITY');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_GALLERY}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_HERMITAGE');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_CHANCERY}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_PRINTING_PRESS');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_WIRE_SERVICE}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_FOREIGN_OFFICE');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_MINT}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_NATIONAL_TREASURY');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TEMPLE_DESC}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_GRAND_TEMPLE' AND Type != 'BUILDING_LEUGI_JERUSALEM_TEMPLE');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_POLICE_STATION}[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_INTELLIGENCE_AGENCY');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]Harbor[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_FA_SEA_ACADEMY')
 AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with [COLOR_POSITIVE_TEXT]Castle[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_FA_WAR_ACADEMY')
 AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with [COLOR_POSITIVE_TEXT]Military Academy[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_FA_AIR_ACADEMY')
 AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_AIR_ACADEMY');
UPDATE Language_ko_KR SET Text = Text||' [NEWLINE]Newly founded Cities start with [COLOR_POSITIVE_TEXT]Walls[ENDCOLOR].'
WHERE Tag IN (SELECT Help FROM Buildings WHERE BuildingClass='BUILDINGCLASS_COURT_SCRIBE');
 
INSERT OR REPLACE INTO Language_ko_KR (Tag, Text) VALUES
('TXT_KEY_BUILDING_JAR_DURUNTASH', 'Dur Untash'),	
('TXT_KEY_BUILDING_JAR_DURUNTASH_PEDIA', 'Dur Untash, also known as Chogha Zanbil, is an ancient Elamite complex located near Susa in modern-day Iran. Constructed around 1250 BCE by the king Untash-Napirisha, Dur Untash stands as a remarkable testament to the architectural and engineering prowess of the Elamite civilization. The complex is primarily composed of a massive ziggurat, dedicated to the god Inshushinak, and is surrounded by a well-planned city with residential areas, temples, and other structures. Despite its grandeur, Dur Untash was abandoned relatively soon after its completion, possibly due to political instability and the fall of the Elamite civilization. The site was rediscovered in the 19th century and in 1979 it was recognized as a UNESCO World Heritage site, providing valuable insights into the ancient Elamite culture and its religious practices. [NEWLINE][NEWLINE]Dur Untash''s ziggurat is an outstanding example of Elamite architecture, featuring a unique design with square terraces and a cylindrical core. The construction involved the use of mud bricks and baked bricks, and the ziggurat once soared to a height of about 52 meters. The site''s archaeological significance extends beyond its architectural marvels, as it also contains inscriptions and artifacts that offer glimpses into the religious beliefs and rituals of the Elamite people. Despite the site''s historical importance, Dur Untash faces challenges such as environmental decay and the need for preservation efforts to ensure its continued existence as a valuable cultural heritage site.'),	
('TXT_KEY_BUILDING_JAR_DURUNTASH_STRATEGY', 'Constructing this building is crucial to found a religion faster. A City must have a {TXT_KEY_BUILDING_SHRINE} before it can construct the {TXT_KEY_BUILDING_JAR_DURUNTASH}.'),	
('TXT_KEY_BUILDING_JAR_DURUNTASH_HELP', ''),	
('TXT_KEY_BUILDING_JAR_WATERWORKS', 'Waterworks'),	
('TXT_KEY_BUILDING_JAR_WATERWORKS_PEDIA', 'The origins of sanitation and waterworks can be traced back to ancient civilizations that recognized the vital importance of clean water and effective waste management. One of the earliest examples is found in the ancient Indus Valley Civilization (circa 3300–1300 BCE), where urban centers like Mohenjo-daro featured an advanced urban planning system that included a sophisticated network of brick-lined sewers. Homes in these cities were equipped with private bathrooms and toilets, connected to a comprehensive sewage system that reflected a high level of understanding regarding the necessity of sanitation for public health. The Indus people''s emphasis on maintaining clean and efficient water systems is a testament to their early recognition of the connection between hygiene and overall well-being. [NEWLINE][NEWLINE]In ancient Mesopotamia, the Sumerians developed innovative water management practices, constructing canals and irrigation systems to harness the waters of the Tigris and Euphrates rivers for agricultural purposes. The Code of Hammurabi, dating back to around 1754 BCE, even contained regulations related to water usage and sanitation. Meanwhile, the ancient Egyptians demonstrated a profound understanding of water control through the construction of canals, reservoirs, and drainage systems, particularly along the Nile River. These early efforts laid the groundwork for subsequent civilizations to refine and expand upon the principles of sanitation and waterworks, ultimately shaping the evolution of urban infrastructure and public health.'),	
('TXT_KEY_BUILDING_JAR_WATERWORKS_STRATEGY', 'A National Wonder granting a population growth boost to the City where it is constructed and to future Cities. A City must have a {TXT_KEY_BUILDING_GRANARY} before it can construct the {TXT_KEY_BUILDING_JAR_WATERWORKS}.'),	
('TXT_KEY_BUILDING_JAR_WATERWORKS_HELP', 'Newly founded Cities start with +1 [ICON_CITIZEN] Citizen.'),
('TXT_KEY_BUILDING_JAR_JOUSTING', 'National Joust'),	
('TXT_KEY_BUILDING_JAR_JOUSTING_PEDIA', 'Emerging in feudal Europe, jousting evolved from the practical need for knights to hone their combat skills. The earliest recorded tournaments took place in 11th-century France, where knights engaged in mock battles to sharpen their abilities in warfare. Over time, jousting became a highly stylized and ritualized spectacle, often held during festive occasions or as part of royal celebrations. The pinnacle of jousting''s popularity occurred during the High Middle Ages, with tournaments attracting participants from across Europe, showcasing chivalry, honor, and martial prowess. [NEWLINE][NEWLINE]Jousting tournaments typically involved two knights on horseback charging at each other with lances, aiming to unseat their opponent or break their lance on the opponent''s shield or armor. The events also included melee combat and other contests of skill. Jousting''s decline began in the late 16th century due to changes in warfare, shifting social values, and the rise of firearms. Despite its waning popularity, the legacy of medieval jousting endures in contemporary portrayals of chivalry and tournaments, highlighting its enduring impact on the cultural imagination of the Middle Ages.'),	
('TXT_KEY_BUILDING_JAR_JOUSTING_STRATEGY', 'A building granting some nifty military bonuses. A City must have an {TXT_KEY_BUILDING_ARMORY} before it can construct the {TXT_KEY_BUILDING_JAR_JOUSTING}.'),	
('TXT_KEY_BUILDING_JAR_JOUSTING_HELP', 'Newly founded Cities start with an [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_ARMORY}[ENDCOLOR].'),	
('TXT_KEY_BUILDING_JAR_DIPLOMIS', 'Diplomatic Mission'),	
('TXT_KEY_BUILDING_JAR_DIPLOMIS_PEDIA', 'The formal establishment of permanent embassies as recognized diplomatic missions began to take shape during the Renaissance in the 15th and 16th centuries. The first modern embassy is often considered to be the Spanish Embassy in Venice, established in 1487. This marked a shift from ad-hoc diplomatic missions to a more structured and permanent system of representation. Over time, European nations formalized diplomatic practices, and embassies became essential institutions for fostering diplomatic relations, negotiating treaties, and promoting economic and cultural ties between states. [NEWLINE][NEWLINE]The concept of diplomatic immunity also emerged during this period, ensuring that diplomats could perform their duties without fear of arrest or interference. The Peace of Westphalia in 1648 further solidified the principles of modern diplomacy, recognizing the independence and equality of states. As the world became more interconnected, embassies proliferated globally, serving as hubs for international relations and playing a crucial role in maintaining peaceful interactions and resolving conflicts between nations. Today, embassies continue to be central to the conduct of international diplomacy, providing a physical presence for countries to engage with one another and navigate the complexities of the global political landscape.'),	
('TXT_KEY_BUILDING_JAR_DIPLOMIS_STRATEGY', 'A building that increases your geopolitic weight in the world as well as the defenses against foreign secret agents. A City must have a {TXT_KEY_BUILDING_CONSTABLE} before it can construct the {TXT_KEY_BUILDING_JAR_DIPLOMIS}.'),	
('TXT_KEY_BUILDING_JAR_DIPLOMIS_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_CONSTABLE}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_NATTHEATRE', 'National Theater'),	
('TXT_KEY_BUILDING_JAR_NATTHEATRE_PEDIA', 'One of the earliest national theaters is the Comédie-Francaise in Paris, established in 1680, which served as a model for similar institutions. However, the idea of a dedicated national theater gained prominence in the 19th century as many European nations sought to establish cultural identity and foster a sense of unity. For instance, the National Theatre in London, founded in 1847, was established with the aim of providing a venue for high-quality drama that reflected the cultural heritage and aspirations of the British people.'),	
('TXT_KEY_BUILDING_JAR_NATTHEATRE_STRATEGY', 'This National Wonder boosts culture and prosperity empire-wide. A City must have an {TXT_KEY_BUILDING_AMPHITHEATER} before it can construct the {TXT_KEY_BUILDING_JAR_NATTHEATRE}.'),	
('TXT_KEY_BUILDING_JAR_NATTHEATRE_HELP', 'Newly founded Cities start with an [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_AMPHITHEATER}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_NATAQUARIUM', 'National Aquarium'),	
('TXT_KEY_BUILDING_JAR_NATAQUARIUM_PEDIA', 'The world''s first national aquarium is often attributed to the Marine Biological Association of the United Kingdom, which opened its doors in 1887. This institution aimed to showcase marine specimens for scientific research and public education. The concept of national aquaria gained momentum in the 20th century, with many countries establishing their own facilities to promote marine awareness, research, and conservation. These institutions often play a dual role, serving as both educational centers for the public and hubs for scientific research to better understand and protect aquatic ecosystems. [NEWLINE][NEWLINE]Today, national aquaria around the world continue to evolve, incorporating advanced technologies and interactive exhibits to engage visitors and raise awareness about marine biodiversity and conservation issues. Many national aquaria also participate in breeding programs for endangered species, research initiatives, and collaborate with marine scientists to contribute valuable data to global efforts aimed at preserving the health of our oceans.'),	
('TXT_KEY_BUILDING_JAR_NATAQUARIUM_STRATEGY', 'Constructing this building boosts research and prosperity empire-wide. A City must have a {TXT_KEY_BUILDING_THEATRE} before it can construct the {TXT_KEY_BUILDING_JAR_NATAQUARIUM}.'),	
('TXT_KEY_BUILDING_JAR_NATAQUARIUM_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]Circus[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_NATSTADIUM', 'Olympic Stadium'),	
('TXT_KEY_BUILDING_JAR_NATSTADIUM_PEDIA', 'One of the earliest national stadiums is the Helsinki Olympic Stadium in Finland, completed in 1938. The stadium was initially constructed for the 1940 Summer Olympics, which were later canceled due to World War II. However, the Helsinki Olympic Stadium played a crucial role in hosting subsequent Olympic Games and became a symbol of national pride. This early example set the precedent for other nations to invest in large-scale, multipurpose stadiums that could host not only sports events but also cultural and national celebrations. [NEWLINE][NEWLINE]In the post-war era, many countries around the world followed suit, constructing national stadiums to host major sporting events and symbolize collective achievements. These venues often serve as iconic landmarks and focal points for national celebrations, hosting a variety of events ranging from sports competitions and concerts to political gatherings. As the demand for modern and state-of-the-art facilities increased, national stadiums evolved to incorporate advanced technologies, seating capacities, and amenities to meet the needs of diverse events and activities.'),	
('TXT_KEY_BUILDING_JAR_NATSTADIUM_STRATEGY', 'This National Wonder boosts duration of Golden Ages. A City must have a {TXT_KEY_BUILDING_STADIUM_DESC} before it can construct the {TXT_KEY_BUILDING_JAR_NATSTADIUM}.'),	
('TXT_KEY_BUILDING_JAR_NATSTADIUM_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_THEATRE}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_POLYTECHNIC', 'Polytechnic Institute'),
('TXT_KEY_BUILDING_JAR_POLYTECHNIC_EE', 'National Academy'),
('TXT_KEY_BUILDING_JAR_POLYTECHNIC_PEDIA', 'The concept of polytechnic education emerged as a response to the increasing demand for professionals trained in engineering, technology, and applied sciences. The world''s first polytechnic institute, École Polytechnique in France, founded in 1794, set the standard for institutions that focused on practical and hands-on learning to prepare individuals for careers in industry and innovation. The success of École Polytechnique inspired the establishment of similar institutions globally, with each adapting to the unique needs and priorities of their respective countries. [NEWLINE][NEWLINE]Several prominent polytechnic institutes have gained international recognition for their contributions to education, research, and technological advancements. Institutions like the Massachusetts Institute of Technology (MIT) in the United States, the Swiss Federal Institute of Technology (ETH Zurich) in Switzerland, and the Tokyo Institute of Technology in Japan have emerged as leaders in providing cutting-edge education and fostering innovation. These institutes have played a pivotal role in shaping the landscape of technology and engineering on a global scale, producing graduates who have made significant contributions to various industries and fields of study.'),	
('TXT_KEY_BUILDING_JAR_POLYTECHNIC_STRATEGY', 'A National Wonder affecting production and research. A City must have a {TXT_KEY_BUILDING_PUBLIC_SCHOOL} before it can construct the {TXT_KEY_BUILDING_JAR_POLYTECHNIC}.'),	
('TXT_KEY_BUILDING_JAR_POLYTECHNIC_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_PUBLIC_SCHOOL}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_GWAYSTATION', 'Grand Waystation'),
('TXT_KEY_BUILDING_JAR_GWAYSTATION_PEDIA', 'Dating back to early civilizations such as the Persian Empire, which established the Royal Road with waystations for royal couriers, these facilities enabled efficient movement across empires. In ancient China, similar stations supported the imperial postal system, while in the Roman Empire, mutationes and mansiones provided services for official messengers and travelers. Throughout the medieval period, especially along the Silk Road and pilgrimage routes, waystations continued to offer shelter and logistical support for merchants, diplomats, and pilgrims. These stops were crucial for maintaining long-distance connectivity, fostering economic and cultural exchange, and supporting the infrastructure of states and empires.'),
('TXT_KEY_BUILDING_JAR_GWAYSTATION_STRATEGY', 'Constructing this National Wonder provides benefits for trade and Merchant specialists. A City must have a {TXT_KEY_BUILDING_CARAVANSARY} before it can construct the {TXT_KEY_BUILDING_JAR_GWAYSTATION}.'),
('TXT_KEY_BUILDING_JAR_GWAYSTATION_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_CARAVANSARY}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_CENTRALBANK', 'Central Bank'),
('TXT_KEY_BUILDING_JAR_CENTRALBANK_PEDIA', 'The history of central banking dates back to the 17th century, with the establishment of Sweden’s Sveriges Riksbank in 1668, widely regarded as the world''s first central bank. However, the model for modern central banking was shaped significantly by the founding of the Bank of England in 1694, created to finance government debt during wartime. Early central banks were primarily established to serve the fiscal needs of their governments, including managing public debt and issuing banknotes. Over time, their roles expanded to include regulating currency and credit, stabilizing national financial systems, and acting as lenders of last resort during crises. [NEWLINE][NEWLINE]In the 20th century, central banks evolved further into independent institutions tasked with broader economic mandates, such as controlling inflation, maintaining employment, and ensuring financial stability. The U.S. Federal Reserve System, founded in 1913, became a key model for this transformation, particularly after the Great Depression and the 2008 financial crisis, which underscored the central bank’s critical role in crisis management and monetary policy. As globalization increased, central banks also began coordinating policies internationally, especially through forums like the Bank for International Settlements (BIS). Today, while their specific functions may vary by country, central banks are central to economic planning and stability in nearly every modern economy.'),
('TXT_KEY_BUILDING_JAR_CENTRALBANK_STRATEGY', 'This National Wonder boosts Production and Merchant specialists across the empire. A City must have a {TXT_KEY_BUILDING_BANK} before it can construct the {TXT_KEY_BUILDING_JAR_CENTRALBANK}.'),
('TXT_KEY_BUILDING_JAR_CENTRALBANK_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_BANK}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_STATEARCHIVES', 'State Archives'),
('TXT_KEY_BUILDING_JAR_STATEARCHIVES_PEDIA', 'State archives can be traced to ancient civilizations, where recordkeeping was vital for administration, law, and governance. Early examples include clay tablets stored in temple archives in Mesopotamia and the official records kept by ancient Egyptian and Chinese bureaucracies. However, the concept of a centralized national archive emerged more clearly in the modern era, particularly in Europe during the Enlightenment. The French Revolution marked a turning point with the establishment of the Archives Nationales in 1790, aimed at preserving public records as national property and ensuring transparency and accountability in governance. This model influenced the development of similar institutions across Europe and later in newly formed nation-states. [NEWLINE][NEWLINE]By the 19th and 20th centuries, as governments expanded and literacy increased, national and state archives evolved into formal institutions tasked with preserving not only legal and administrative documents but also cultural heritage and historical memory. Advances in archival science, along with technological innovations, transformed archival practices and access, making it possible to systematically collect, catalog, and preserve vast volumes of materials. Today, national and state archives serve as custodians of public records and play a critical role in historical research, public accountability, and cultural preservation, often balancing traditional preservation with digital archiving and public outreach.'),
('TXT_KEY_BUILDING_JAR_STATEARCHIVES_STRATEGY', 'A building boosting Science and Tourism. A City must have a {TXT_KEY_BUILDING_MUSEUM} before it can construct the {TXT_KEY_BUILDING_JAR_STATEARCHIVES}.'),
('TXT_KEY_BUILDING_JAR_STATEARCHIVES_HELP', 'Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_MUSEUM}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_INDUSTRYCONFED', 'Confederation of Industry'),
('TXT_KEY_BUILDING_DUMMY_INDUSTRYCONFED', 'DummyConfedIndustry'),	
('TXT_KEY_BUILDING_JAR_INDUSTRYCONFED_PEDIA', 'National industry confederations emerged in the late 19th and early 20th centuries as countries industrialized and business leaders sought organized representation to influence economic policy and labor relations. These confederations typically brought together various sectoral trade associations and chambers of commerce to form unified national voices for industry. In Europe, early examples include Germany’s Reichsverband der Deutschen Industrie (1904) and Italy’s Confindustria (1910), while in the United States, the National Association of Manufacturers (founded in 1895) played a similar role. These organizations aimed to advocate for pro-business legislation, standardize industrial practices, and counter the growing influence of labor unions and socialist movements during the industrial era. [NEWLINE][NEWLINE]As governments became more involved in economic planning—especially during and after the World Wars—national industry confederations grew in importance. They collaborated with states on issues like economic reconstruction, infrastructure development, and trade policy, often participating in tripartite dialogues alongside labor unions and governments. In the postwar period, especially in developed economies, they became key players in shaping industrial strategy, tax policy, education and training programs, and global trade negotiations. Today, these confederations continue to act as influential intermediaries between the private sector and the state, promoting competitiveness, innovation, and economic growth at both national and international levels.'),
('TXT_KEY_BUILDING_JAR_INDUSTRYCONFED_STRATEGY', 'This National Wonder improves production and gold productivity across the empire. A City must have a {TXT_KEY_BUILDING_FACTORY} before it can construct the National {TXT_KEY_BUILDING_JAR_INDUSTRYCONFED}.'),
('TXT_KEY_BUILDING_JAR_INDUSTRYCONFED_HELP', '+2 [ICON_PRODUCTION] Production on Snow tiles in the Empire. [NEWLINE][NEWLINE]Newly founded Cities start with a [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_FACTORY}[ENDCOLOR].'),
('TXT_KEY_BUILDING_JAR_CONCERT_HALL', 'Grand Concert Hall'),
('TXT_KEY_BUILDING_DUMMY_CONCERT_HALL', 'DummyConcertHall'),	
('TXT_KEY_BUILDING_JAR_CONCERT_HALL_PEDIA', 'The concept of the concert hall evolved alongside the development of public musical performance in Europe during the 17th and 18th centuries. Prior to this, music was largely performed in private salons, royal courts, or religious settings. As interest in secular music grew and orchestras expanded, the need for dedicated performance spaces led to the creation of early concert halls. One of the earliest known purpose-built venues was the Holywell Music Room in Oxford, England, opened in 1748. By the 19th century, the rise of the middle class and increased public access to the arts spurred the construction of grand concert halls across Europe, such as the Gewandhaus in Leipzig and the Musikverein in Vienna, designed not only for acoustical excellence but also as architectural symbols of civic pride. [NEWLINE][NEWLINE]In the 20th and 21st centuries, concert halls became global cultural landmarks, with advances in acoustical engineering and design allowing for increasingly sophisticated and flexible performance environments. Iconic modern examples include the Sydney Opera House, completed in 1973, and the Elbphilharmonie in Hamburg, opened in 2017. These venues often serve as homes to major orchestras and are designed to host a wide range of musical genres, from classical to contemporary. Today, concert halls continue to play a central role in cultural life, acting as venues for artistic expression, community gathering, and international prestige, while adapting to changing technologies and audience expectations.'),
('TXT_KEY_BUILDING_JAR_CONCERT_HALL_STRATEGY', 'Constructing this building will improve the culture and tourism rate across the empire. A City must have an {TXT_KEY_BUILDING_OPERA_HOUSE} before it can construct the {TXT_KEY_BUILDING_JAR_CONCERT_HALL}.'),
('TXT_KEY_BUILDING_JAR_CONCERT_HALL_HELP', '+10% [ICON_TOURISM] Tourism in the Empire during [ICON_GOLDEN_AGE] Golden Ages. [NEWLINE][NEWLINE]Possible Theming Bonuses:
  [NEWLINE][ICON_BULLET] +20 [ICON_CULTURE] and [ICON_TOURISM] for three [COLOR_POSITIVE_TEXT]Domestic[ENDCOLOR] [ICON_GW_MUSIC] Great Works of Music. [NEWLINE]Newly founded Cities start with an [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_OPERA_HOUSE}[ENDCOLOR]. '),
('TXT_KEY_THEMING_BONUS_CONCERT_HALL', 'Popular Orchestral Symphonies'),
('TXT_KEY_THEMING_BONUS_CONCERT_HALL_HELP', 'To maximize your bonus, make sure all the Great Work Slots are all filled with Music created by you.');