--==========================================================================================================================	
-- Civilization_BuildingClassOverrides
--==========================================================================================================================		
INSERT INTO Language_ko_KR (Tag, Text)
VALUES	('TXT_KEY_BUILDING_BRAZIL_EMBRAPA',			'Embrapa'),
		('TXT_KEY_BUILDING_BRAZIL_EMBRAPA_TEXT',		'Embrapa is a state-owned research corporation affiliated with the Brazilian Ministry of Agriculture. Since its inception on April 26, 1973, it has been devoted to developing technologies, knowledge and technical-scientific information aimed at Brazilian agriculture, including livestock. Embrapa''s organizational structure is composed of 46 centers that can be divided into Research Units or Service Units, and of 17 Central Units that comprise the corporation''s headquarters. Such research centers are distributed throughout the country in nearly all Brazilian states.'),
		('TXT_KEY_BUILDING_BRAZIL_EMBRAPA_STRATEGY',	'The Embrapa provides bonuses to Tourism, Culture, and even Gold, on top of Science bonuses like the Research Lab, which it replaces. Brazilwood Camps, as well as the Jungle and/or Forest tiles on which they are built receive additional Science as well as either Tourism or Culture and Gold. Pastures and the plant bonuses resources are also boosted like the Brazilwood Camp. These bonuses are most effective for a large empire with many Brazilwood Camps and ways of turning Culture on tiles into Tourism. Finally Cities gain Tourism from a percentage of their total Food, increasing its value to your Empire.'),
		('TXT_KEY_BUILDING_BRAZIL_EMBRAPA_HELP', '+4 [ICON_RESEARCH] Science from [ICON_RES_OIL] Oil, [ICON_RES_ALUMINUM] Aluminum, [ICON_RES_URANIUM] Uranium, and Academies worked by this City.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold, [ICON_RESEARCH] Science, and [ICON_CULTURE] Culture from Brazilwood Camps, Pastures, [ICON_RES_BANANA] Bananas, [ICON_RES_RICE] Rice, [ICON_RES_MAIZE] Maize, and [ICON_RES_WHEAT] Wheat worked by this City. +1 [ICON_RESEARCH] Science and [ICON_TOURISM] Tourism from Forest and Jungle tiles worked by this City. 5% of [ICON_FOOD] Food created by the City counts as [ICON_TOURISM] Tourism.[NEWLINE][NEWLINE]+4 [ICON_RESEARCH] Science from Hospitals, Factories, and Medical Labs, and [ICON_GREAT_SCIENTIST] Great Scientists are produced 33% more quickly in this City.[NEWLINE][NEWLINE]-1 [ICON_HAPPINESS_3] Unhappiness from [ICON_RESEARCH] Illiteracy.');


