INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_2', '당신의 문화는 더 이상 우리 모두가 한때 공유했던 동일한 본질적 가치를 갖지 않습니다. 당신이 문화라고 부르는 타락은 끝날 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_3', '점점 더 지배적인 문화에 도전하는 것은 어렵지만 다른 모든 사람들의 문화를 보존하는 데 필요합니다.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_4', '우리는 당신의 문화의 포로로 복종하지 않을 것입니다. 우리 문화는 당신에 대항해서 자유를 위해 싸울 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_5', '우리 문화는 당신이 세계에 미치는 위험한 영향에 사로잡히지 않을 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_SPACESHIP_2', '당신이 감히 별들 사이에서 한 자리를 차지할 거라는 오만함 때문에 우리들이 당신이 차지할 땅에서 한 자리를 차지할걸 보게 만들거요.'),
	('en_US', 'TXT_KEY_DEFENSE_PACT_OFFER_5', '우리가 방위조약을 맺는다면, 이 세계의 적들에 대한 강력한 방어벽을 확실히 구축할 수 있을 것입니다.'),
	('en_US', 'TXT_KEY_DEFENSE_PACT_OFFER_6', '적들은 우리를 사방에 둘러싸고 있습니다. 우리 사이의 강력한 동맹으로 우리는 반드시 승리할 것입니다.'),
	('en_US', 'TXT_KEY_DEFENSE_PACT_OFFER_7', '이 위험한 세상에서 우리가 이 세상의 악을 방어하기 위해 서로 동맹을 맺지 않았다는 사실에 놀랐습니다. 동맹을 맺읍시다.'),
	('en_US', 'TXT_KEY_CITY_TRADE_OFFER_4', '물론 양국끼리 자유롭게 영토를 교환할 수 있지 않겠습니까?'),
	('en_US', 'TXT_KEY_CITY_TRADE_OFFER_5', '나는 당신의 땅을 원하고 당신은 내 땅을 원합니다. 이런 제안은 어떻습니까?'),
	('en_US', 'TXT_KEY_THIRD_PARTY_WAR_OFFER_4', '당신은 훌륭한 군대를 가지고 있군요. 당신이 수락만 하면 나는 그 군대에 대한 용도를 알려줄 수 있습니다.'),
	('en_US', 'TXT_KEY_THIRD_PARTY_PEACE_OFFER_4', '당신의 적들과 내 친구들과 화해하는것이 좋을것 같군요. 그렇지 않소? 이 제안을 진지하게 고려해보십시오.'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_3', '당신이 그런 태도를 가져도 되는 사람이라고 생각하시오? 이 이상의 모욕은 참을 수 없소, 전쟁을 준비하시오!'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_4', '그런 말을 하는 것이 큰 실수가 될 것이오!'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_5', '지금 나를 조롱하는 것입니까? 전쟁을 준비하시오!'),
	('en_US', 'TXT_KEY_WAR_DEMAND_INSULTED_6', '그 말의 대가를 치루게 해주지!'),
	('en_US', 'TXT_KEY_GENERIC_DOW_WARMONGER_3', '평화를 유지하기 위해, 나는 당신과 같은 더 큰 악을 끝내야 합니다.'),
	('en_US', 'TXT_KEY_GENERIC_DOW_WARMONGER_4', '당신이 다른 이들을 덮쳤을 때, 나는 침묵했소. 내 일이 아니었기 때문에. 그 다음에 당신이 또 다른 이들을 덮쳤을 때도 나는 침묵했소. 내 일이 아니었기 때문에. 그러나 지금 이것마저 막을 사람이 아무도 남지 않는다면, 누가 하겠습니까?'),
	('en_US', 'TXT_KEY_GENERIC_ATTACKED_STRONG_WARMONGER_2', '날 웃게 만드는구나, 너보다 더 강한 나에게 도전해보려고? 한번 해봐라!'),
	('en_US', 'TXT_KEY_GENERIC_ATTACKED_WEAK_WARMONGER_2', '우리가 비록 당신의 군사력보다 부족할지 모르지만, 당신 같은 피비린내 나는 폭군이 되느니 차라리 고귀하게 죽을것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_ATTACKED_IDEOLOGY_SAME_2', '정신 나갔습니까? 우린 당신 편이야! 우리를 반대하는 이들을 냅두고 우리를 공격한다고?'),
	('en_US', 'TXT_KEY_GENERIC_EMBASSY_EXCHANGE_4', '더 빠른 양국의 교류를 위해 각국 수도에 대사관을 설치해야하지 않겠습니까?'),
	('en_US', 'TXT_KEY_GENERIC_EMBASSY_EXCHANGE_5', '상호간에 오해가 생기지 않도록 서로 대사관이 있어야 합니다.'),
	('en_US', 'TXT_KEY_GENERIC_EMBASSY_EXCHANGE_6', '대사관을 설치하여 양국간의 관계를 개선해 봅시다.'),
	('en_US', 'TXT_KEY_GENERIC_SAME_POLICIES_FREEDOM_3', '나는 당신이 나와 같은 세상의 자유에 대한 믿음을 공유하는 것을 보았습니다. 우리가 함께 노력하여 다른 나라들이 자유를 얻을 수 있도록 도와야 한다고 믿습니다!'),
	('en_US', 'TXT_KEY_GENERIC_SAME_POLICIES_ORDER_3', '나는 당신이 나와 같은 세상의 질서에 대한 믿음을 공유하는 것을 보았습니다. 자, 우리 함께 유토피아 사회를 만들도록 합시다.'),
	('en_US', 'TXT_KEY_GENERIC_SAME_POLICIES_AUTOCRACY_3', '나는 당신이 나와 같은 세계의 절대 권력에 대한 같은 믿음을 공유하는 것을 보았습니다. 더 큰 힘을 위해 함께 일합시다.'),
	('en_US', 'TXT_KEY_GENERIC_CAUGHT_YOUR_SPY_FRIENDLY_3', '우리를 염탐했던 동기는 이해합니다. 하지만 우리는 친구입니다. 서로를 염탐하면 안 됩니다!'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_SHARE_INTRIGUE_DECEPTION_4', '{1_PlayerName}{1: plural 1?이; 2?가;} 당신을 향해 음모를 꾸미고 있습니다. 나는 그들의 행위에 당신이 무언가 조치를 취했으면 합니다.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_3', '정보 제공을 해줘서 무척 고맙습니다. 당신 덕분에 {@1_CivAdjective} 음모는 실패할 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_4', '좋습니다. 정보 감사하군요!'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_5', '참으로 도움이 되는 조언이었습니다. {@1_CivAdjective}{1: plural 1?은; 2?는;} 정보 제공자가 당신일거라곤 알지 못 할 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_6', '가치 있는 정보 제공에 무척 감사드리는 바이오.'),
	('en_US', 'TXT_KEY_GENERIC_RESPONSE_WARNED_ABOUT_INTRIGUE_7', '그 정보에 정말 흥미가 있군요, 감사합니다.'),
	('en_US', 'TXT_KEY_GENERIC_CONFRONT_YOU_KILLED_MY_SPY_3', '스파이 사건이 아니라 우호적인 합의에 대해 논의하기 위해 여기에 왔으면 좋겠습니다!'),
	('en_US', 'TXT_KEY_GENERIC_SWITCHED_TO_FREEDOM_3', '드디어 압제에서 해방되었군요. 이리 와서 자유와 자유의 혜택을 즐겨보십시오!'),
	('en_US', 'TXT_KEY_GENERIC_SWITCHED_TO_ORDER_3', '당신이 유토피아에 한 발짝 더 다가가서 기쁘군요!'),
	('en_US', 'TXT_KEY_GENERIC_SWITCHED_TO_AUTOCRACY_3', '우리는 당신이 절대 권력에 저항할 수 없다는 것을 알고 있었습니다.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_HUMAN_CLASSICAL_2', '당신의 유산이 무너질 동안 내 유산은 영원히 계속될 것입니다. 아무도 당신들의 말을 다시는 말하지 않을 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_HUMAN_RENAISSANCE_2', '당신의 조상들이 유지하던 전통이 사라질 것입니다. 우리는 당신들이 어둠이라고 부르는 것에 문화적 깨달음을 가져다 줄 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_HUMAN_MODERN_2', '당신은 한때 자랑스럽고 독립적인 문화를 가졌습니다. 하지만 지금 그것들은 박물관에나 있죠. 저는 여러분이 그런 것들을 잊고 우리가 제공하는 새롭고 현재의 문화를 받아들이기를 촉구합니다.'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_AI_CLASSICAL_2', '비록 우리의 문화는 이렇게 무너지지만, 당신의 문화도 영원히 통치하지 않을 것입니다. 이보다 더 높은 문화가 어딘가 있을 것입니다!'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_AI_RENAISSANCE_2', '당신의 영향력이 우리 민족을 당신의 방식대로 끌고 가지만, 만약 당신의 문화가 지속되지 않는다면 우리는 우리의 옛 문화를 다시 떠올릴 것입니다!'),
	('en_US', 'TXT_KEY_GENERIC_INFLUENTIAL_ON_AI_MODERN_2', '과거의 영광은 여전히 우리의 역사에 남아 있고, 우리가 여전히 보존하고 배울 수 있는 것은 아직은 더 큰 경쟁자들이 있다는 것입니다. 그 들은 그들을 통제하려는 당신의 시도에 저항할 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_WORLD_CONQUEST_2', '나는 빛의 등대와도 같고, 그대는 어둠의 구름과도 같소. 당신의 한심한 시도를 이제 끝내야겠소.'),
	('en_US', 'TXT_KEY_GENERIC_BLOCK_ANNOUNCE_WORLD_CONGRESS_3', '평가하려는 것은 아닙니다. 허나 당신이 거짓된 혓바닥과 비어있는 보물을 가지고 말하는건 정말 피곤합니다.'),
	('en_US', 'TXT_KEY_GENERIC_DOW_OLD_ENEMIES_3', '존경하는 나의 숙적이여, 다시 한번 더 우리가 당신의 틈을 파고들어야 하겠소.'),
	('en_US', 'TXT_KEY_GENERIC_DOW_OLD_ENEMIES_4', '오, 우리가 이전에 서로 얼마나 재미있었나. 다시 그것을 하게 되어 기쁘군.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_HOSTILE_REPEAT_5', '지금 나를 찾아오는 배짱이 있군요. 차라리 그게 낫겠군요.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_HOSTILE_REPEAT_6', '난 당신의 청중이 되는걸 요구한적이 없어요. 할 말이 있으면 빨리 하세요.'),
	('en_US', 'TXT_KEY_DENOUNCE_11', '당신이랑 있는건 시간낭비예요. 세상 한구석에서 썩어 버리길, 당신을 위해 쓸 시간은 없습니다.[NEWLINE][NEWLINE]([COLOR_WARNING_TEXT]이들은 우리를 공개적으로 비난했습니다![ENDCOLOR])'),
	('en_US', 'TXT_KEY_DENOUNCE_12', '당신의 행동은 용서할 수 없고 잊을 수 없습니다. 당신은 우리를 암흑의 시대로 이끌 사람입니다.[NEWLINE][NEWLINE]([COLOR_WARNING_TEXT]이들은 우리를 공개적으로 비난했습니다![ENDCOLOR])'),
	('en_US', 'TXT_KEY_COOP_WAR_REQUEST_7', '{1_PlayerName:textkey}{1: plural 1?은; 2?는;} 반인륜적 범죄를 저지른 처벌이 있어야 합니다. 저 혼자서는 힘들것 같은데, 함께 해주시겠습니까?'),
	('en_US', 'TXT_KEY_GENERIC_BOOT_KISSING_5', '이전에 내가 당신이 나의 롤모델이라고 말한 적이 있었나요?'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_MILITARY_4', '당신의 군대는 숨이 턱 멎는 듯할 정도로 놀랍다고 말할 수 밖에 없군요. '),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_MILITARY_5', '당신의 군대가 오직 평화를 유지하기 위해 존재하길 바랍니다.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_MILITARY_6', '한 명의 병사가 쓰러지기 전에 한번에 10명의 병사를 쓰러뜨렸다던 제국의 전설이 있습니다. 당신의 부하들이 이런 전설을 만들어낸게 아닌지 궁금하군요.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_ECONOMY_4', '내 빈 금고에 비해 당신의 금고는 가득 차있습니다. 당신이 방법을 가르쳐준다면, 나는 당신의 가르침에 매우 감사할 것입니다.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_ECONOMY_5', '당신의 제국에서는 작은 투자만 해도 누구나 부자가 될 수 있다고 하던데, 사실인지 궁금하군요.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_FRIENDLY_STRONG_ECONOMY_6', '들리는 소문에 의하면 누구하고도 비교할 수 없는 거대한 경제를 가진 제국이 있다던데, 그것이 당신의 제국이 아닌지 궁금합니다.'),
	('en_US', 'TXT_KEY_GENERIC_REPEAT_TRADE_7', '장난합니까? 더 나은 조건을 가지고 돌아오십시오.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_9', '태양이 산과 대양에 미소 짓는 것처럼 우리도 기쁨으로 당신을 맞이합니다.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_10', '달이 언덕과 바다에 미소 짓는 것처럼 우리도 기쁨으로 당신을 환영합니다.'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_11', '안녕하십니까, 무엇을 도와드릴까요?'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_12', '당신께 경의를, 존경하는 지도자여!'),
	('en_US', 'TXT_KEY_GENERIC_GREETING_POLITE_HELLO_13', '당신이 이곳에 와 주셔서 정말 즐겁습니다. 무슨 이야기를 하고자 오셨나요?');