INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_AIR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_ELECTRIC_CO') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARMOR';

INSERT INTO Building_SpecialistYieldChanges (BuildingType, SpecialistType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK');

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'YIELD_GOLD', 8 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'BUILDING_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'BUILDING_FA_SEA_ACADEMY', 'YIELD_GREAT_ADMIRAL_POINTS', 4 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');

UPDATE Building_Flavors
SET Flavor = 0
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND FlavorType = 'FLAVOR_HAPPINESS';

UPDATE Building_BuildingClassHappiness
SET Happiness = 0
WHERE BuildingClassType = 'BUILDINGCLASS_FA_ELECTRIC_POWER' AND BuildingType = 'BUILDING_FA_ELECTRIC_CO';

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_BANK';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_HARBOR'
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD';

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 40, FreePromotion = 'PROMOTION_GENERAL_STACKING', GreatGeneralRateModifier = 0, HurryCostModifier = -20, FreeBuildingThisCity = NULL
WHERE Type = 'BUILDING_FA_WAR_ACADEMY';

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 45, FreePromotion = 'PROMOTION_FA_SEA_ACADEMY', TrainedFreePromotion = NULL, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 50, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_CENTRAL_BANK';

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 50, CityConnectionTradeRouteModifier = 25, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_CENTRAL_STATION';

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 60, HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_AIR_ACADEMY';

UPDATE Buildings
SET Cost = 125, NumCityCostMod = 10, NationalPopRequired = 70, FreeBuilding = 'BUILDINGCLASS_FA_ELECTRIC_POWER', HurryCostModifier = -20
WHERE Type = 'BUILDING_FA_ELECTRIC_CO';

UPDATE Language_en_US
SET Text = '모든 도시의 상인 전문가 1명마다 [ICON_GOLD]골드가 1씩 제공합니다.[NEWLINE][NEWLINE][COLOR_YELLOW][ICON_CAPITAL]수도에만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_BANK_HELP';

UPDATE Language_en_US
SET Text = '[ICON_CONNECTED]도시 연결에서 오는 [ICON_GOLD]골드가 +25% 증가합니다. 공장, 철도역, 항구의 [ICON_GOLD]골드가 +1 증가합니다.[NEWLINE][NEWLINE]도시에 [COLOR_YELLOW]공장이 있어야만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION_HELP';

UPDATE Language_en_US
SET Text = '[ICON_CONNECTED]도시 연결에서 오는 [ICON_GOLD]골드가 +25% 증가합니다.[NEWLINE][NEWLINE]도시에 [COLOR_YELLOW]공장이 있어야만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION2_HELP';

UPDATE Language_en_US
SET Text = '모든 도시의 전력소가 건설됩니다.[NEWLINE][NEWLINE]도시가 [COLOR_YELLOW]강에 있어야만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO_HELP';

UPDATE Language_en_US
SET Text = '건설된 도시의 [ICON_RESEARCH]과학, [ICON_GOLD]골드, [ICON_PRODUCTION]생산을 증가시킵니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO2_HELP';

UPDATE Language_en_US
SET Text = '육군 유닛을 생산할 때 [ICON_PRODUCTION]생산 보너스를 +15% 제공하고, [ICON_WAR]경험치도 +15 제공합니다. 모든 육군 유닛이 위대한 장군의 전투 보너스를 받습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_WAR_ACADEMY_HELP';

UPDATE Language_en_US
SET Text = '해군 유닛을 생산할 때 [ICON_PRODUCTION]생산 보너스를 +15% 제공하고, [ICON_WAR]경험치도 +15 제공합니다. 모든 해군 유닛이 [COLOR_PLAYER_PURPLE]바다사람[ENDCOLOR] 승급을 받습니다.[NEWLINE][NEWLINE]도시에 [COLOR_YELLOW]항만이 있어야만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_SEA_ACADEMY_HELP';

UPDATE Language_en_US
SET Text = '공군 유닛을 생산할 때 [ICON_PRODUCTION]생산 보너스를 +25% 제공합니다. 모든 공군 유닛이 [COLOR_PLAYER_PURPLE]회피[ENDCOLOR] 승급을 받습니다.[NEWLINE][NEWLINE]도시에 [COLOR_YELLOW]사관학교가 있어야만[ENDCOLOR] 건설할 수 있습니다. 문명에 도시가 많을수록 건설에 필요한 [ICON_PRODUCTION]생산과 [ICON_CITIZEN]시민이 증가합니다.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_AIR_ACADEMY_HELP';

UPDATE Language_en_US
SET Text = '대양 타일에서 이동력이 2배.'
WHERE Tag = 'TXT_KEY_PROMOTION_FA_SEA_ACADEMY_HELP';

DELETE FROM UnitPromotions_Domains
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND UnitType = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND UnitType = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND UnitType = 'UNIT_GREAT_ADMIRAL';