INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
SELECT 'POLICY_ICONATLAS', 256, 'POLICY_ICONATLAS256.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 128, 'POLICY_ICONATLAS128.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 80, 'POLICY_ICONATLAS80.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 64, 'POLICY_ICONATLAS64.dds', 8, 2 UNION ALL
SELECT 'POLICY_ICONATLAS', 45, 'POLICY_ICONATLAS45.dds', 8, 2;

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Tradition[ENDCOLOR] focuses on generating Great People and the construction of an impressive Capital.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Tradition grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +2 [ICON_FOOD] Food, [ICON_CITIZEN] Population, and [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital. [NEWLINE][ICON_BULLET] +1 [ICON_CULTURE] Culture in the Capital for every 2 [ICON_CITIZEN] Citizens. [NEWLINE][ICON_BULLET] +5% [ICON_FOOD] Growth in all Cities.[NEWLINE] [ICON_BULLET] Unlocks the [COLOR_CYAN]Saunas[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Tradition policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +3% [ICON_FOOD] Growth in all Cities, and +1 [ICON_RESEARCH] Science in your [ICON_CAPITAL] Capital.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all Policies in Tradition grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building the [COLOR_POSITIVE_TEXT]University of Sankore[ENDCOLOR]. [NEWLINE][ICON_BULLET] +1 [ICON_FOOD] Food from all Great Person Improvements and Landmarks.[NEWLINE][ICON_BULLET] [COLOR_POSITIVE_TEXT]Throne Room[ENDCOLOR] built in [ICON_CAPITAL] Capital (+10% to all Yields, 1 Musician Specialist, 1 [ICON_GREAT_WORK] Great Work of Music slot, [ICON_GOLDEN_AGE] Golden Ages last 25% longer).[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_ENGINEER] Great Engineers with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Progress[ENDCOLOR] is best for civilizations which desire robust infrastructure and scientific advancement.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Progress grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] Receive 20 [ICON_RESEARCH] Science when a [ICON_CITIZEN] Citizen is born in your [ICON_CAPITAL] Capital.[NEWLINE][ICON_BULLET] Receive 15 [ICON_RESEARCH] Science for every [ICON_CITIZEN] Citizen already in your [ICON_CAPITAL] Capital, scaling with Era. [NEWLINE][ICON_BULLET] Receive 10 [ICON_CULTURE] Culture when a Technology is researched, scaling with Era, and 10 [ICON_CULTURE] Culture per Technology already unlocked (not scaling with Era).[NEWLINE] [ICON_BULLET] Unlocks the [COLOR_CYAN]Town Councils[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Progress policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] Gain an additional 10 [ICON_CULTURE] Culture when a Technology is researched, scaling with Era.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all policies in Progress grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building the [COLOR_POSITIVE_TEXT]Forbidden Palace[ENDCOLOR]. [NEWLINE][ICON_BULLET] Receive 25 [ICON_GOLD] Gold when a [ICON_CITIZEN] Citizen is born in any city, scaling with Era.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_WRITER] Great Writers with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Authority[ENDCOLOR] will greatly benefit warlike and expansionist civilizations.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Authority grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +25% combat bonus VS Barbarians, and receive announcements when Barbarian Camps spawn in revealed territory. [NEWLINE][ICON_BULLET] Gain [ICON_CULTURE] Culture when you kill Units and clear Barbarian Camps.[NEWLINE][ICON_BULLET] +1 [ICON_PRODUCTION] Production in every City.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Strongholds[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Authority policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +1 [ICON_PRODUCTION] Production in every City.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all policies in Authority grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building [COLOR_POSITIVE_TEXT]Alhambra[ENDCOLOR]. [NEWLINE][ICON_BULLET] Yields from [COLOR_POSITIVE_TEXT]Tribute[ENDCOLOR] Policy doubled.[NEWLINE][ICON_BULLET] Allows the purchasing of [COLOR_YELLOW]Landsknechts[ENDCOLOR], [COLOR_YELLOW]Foreign Legions[ENDCOLOR], and [COLOR_YELLOW]Mercenaries[ENDCOLOR] as their prerequisite technologies are researched.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_GENERAL] Great Generals with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Fealty[ENDCOLOR] is best for empires focused on [ICON_RELIGION] Religion, City [ICON_PRODUCTION] Infrastructure, and [ICON_FOOD] Growth.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Fealty grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] Can purchase Monasteries with [ICON_PEACE] Faith (+2 [ICON_PEACE] Faith, +3 [ICON_FOOD] Food, +3 [ICON_RESEARCH] Science).[NEWLINE][ICON_BULLET] -25% [ICON_PEACE] Faith costs for purchasing Buildings, Missionaries, and Inquisitors.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Manor Houses[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Fealty policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +1 [ICON_FOOD] Food and [ICON_STRENGTH] Strength in every City.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all Policies in Fealty grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] Unlocks building the [COLOR_POSITIVE_TEXT]Red Fort[ENDCOLOR].[NEWLINE][ICON_BULLET] The [ICON_TOURISM] Tourism modifier for [COLOR_POSITIVE_TEXT]Shared Religion[ENDCOLOR] is increased by 25%.[NEWLINE][ICON_BULLET] Cities that follow your [ICON_RELIGION] Majority Religion generate +3 [ICON_RESEARCH] Science, [ICON_PEACE] Faith, [ICON_PRODUCTION] Production, and [ICON_CULTURE] Culture.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_ARTIST] Great Artists with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Statecraft[ENDCOLOR] improves your ability to benefit from [ICON_INTERNATIONAL_TRADE] Trade Routes, [ICON_CITY_STATE] City-States, [ICON_SPY] Spies, and [ICON_DIPLOMAT] the World Congress.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Statecraft grants:[ENDCOLOR][NEWLINE][ICON_BULLET] +1 of every Yield in [ICON_CAPITAL] Capital for every 20 [ICON_CITIZEN] Citizens in your Empire.[NEWLINE][ICON_BULLET] +1 [ICON_GOLD] Gold in every City.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]State Embassy[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Statecraft policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +10% [ICON_INFLUENCE] Influence from Trade Missions, and +1 [ICON_GOLD] Gold in every City.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all policies in Statecraft grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building the [COLOR_POSITIVE_TEXT]Palace of Westminster[ENDCOLOR]. [NEWLINE][ICON_BULLET] Every World Congress Session, gain [ICON_CULTURE] Culture, [ICON_RESEARCH] Science, and [ICON_GOLD] Gold based on the number of [ICON_DIPLOMAT] Delegates you control, scaling with Era.[NEWLINE][ICON_BULLET] World Wonders require 1 less unlocked Policy for every 3 City-State alliances you maintain.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Artistry[ENDCOLOR] allows you to maximize the potential of [ICON_GREAT_WORK] Great Works, [ICON_GREAT_PEOPLE] Great People, and [ICON_GOLDEN_AGE] Golden Ages.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Artistry grants:[ENDCOLOR][NEWLINE][ICON_BULLET] +25% [ICON_GREAT_PEOPLE] Great Person rates in all cities.[NEWLINE][ICON_BULLET] +100% [ICON_PRODUCTION] construction rate of all Guilds.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Memorials[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Artistry policy unlocked grants:[ENDCOLOR][NEWLINE][ICON_BULLET] +2 [ICON_GOLDEN_AGE] Golden Age Points and +1 [ICON_RESEARCH] Science in every City.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all policies in Artistry grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building the [COLOR_POSITIVE_TEXT]Louvre[ENDCOLOR]. [NEWLINE][ICON_BULLET] Completing an Archaeological Dig or starting a [ICON_GOLDEN_AGE] Golden Age generates [ICON_TOURISM] Tourism with all known Civilizations. [NEWLINE][ICON_BULLET] Allows you to see Hidden Antiquity Sites, and Landmarks gain +3 [ICON_RESEARCH] Science and [ICON_GOLDEN_AGE] Golden Age Points. [NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_MUSICIAN] Great Musicians with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Industry[ENDCOLOR] provides bonuses to empires focused on [ICON_GOLD] Gold and [ICON_PRODUCTION] Production.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Industry grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +100% [ICON_PRODUCTION] Production speed of Train Stations and Seaports.[NEWLINE][ICON_BULLET] -5% [ICON_GOLD] Gold needed for purchases.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Depots[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Industry policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] -5% [ICON_GOLD] Gold needed for purchases.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all Policies in Industry grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building [COLOR_POSITIVE_TEXT]Broadway[ENDCOLOR]. [NEWLINE][ICON_BULLET] Doubles the Empire-Wide [ICON_HAPPINESS_1] Happiness value for owned Luxuries. [NEWLINE][ICON_BULLET] Specialists gain +2 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_MERCHANT] Great Merchants with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Imperialism[ENDCOLOR] enhances your ability to spread your empire through military power, particularly naval (and later air) supremacy.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Imperialism grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +1 [ICON_MOVES] Movement for Naval units, Embarked units, and [ICON_GREAT_GENERAL] Great Generals, as well as +1 Sight for Naval melee and Land melee units. [NEWLINE][ICON_BULLET] +10% [ICON_PRODUCTION] Production for Military Units, -10% [ICON_GOLD] Gold required for upgrades.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Botanical Gardens[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Imperialism policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +5% [ICON_PRODUCTION] Production for Military Units, -5% [ICON_GOLD] Gold required for upgrades.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all policies in Imperialism grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building the [COLOR_POSITIVE_TEXT]Pentagon[ENDCOLOR]. [NEWLINE][ICON_BULLET] Each Air Unit stationed in a city increases the City''s [ICON_STRENGTH] Defense by 3, and reduces [ICON_HAPPINESS_3] Unhappiness from Needs by 3%.[NEWLINE][ICON_BULLET] All Naval units gain the [COLOR_POSITIVE_TEXT]Ironsides[ENDCOLOR] Promotion (become stronger as they take damage).[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_ADMIRAL] Great Admirals with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Rationalism[ENDCOLOR] focuses on maximizing [ICON_FOOD] Growth and [ICON_RESEARCH] Science output.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Rationalism grants:[ENDCOLOR][NEWLINE][ICON_BULLET] +3 [ICON_RESEARCH] Science and +2 [ICON_PRODUCTION] Production from all Strategic Resources.[NEWLINE][ICON_BULLET] +5% [ICON_RESEARCH] Science, and -5% [ICON_HAPPINESS_3] Unhappiness Modifier for all Needs.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Patent Offices[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Rationalism policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] +2% [ICON_RESEARCH] Science, and -2% [ICON_HAPPINESS_3] Unhappiness Modifier for all Needs.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all Policies in Rationalism grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building [COLOR_POSITIVE_TEXT]Bletchley Park[ENDCOLOR]. [NEWLINE][ICON_BULLET] +33% [ICON_GREAT_SCIENTIST] Great Scientist rate in all cities. [NEWLINE][ICON_BULLET] +25% [ICON_FOOD] Growth in all cities.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_SCIENTIST] Great Scientists with [ICON_PEACE] Faith starting in the Industrial Era.'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]전통[ENDCOLOR]은 위인 및 인상적인 수도의 건설에 초점을 맞춥니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR] [NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_FOOD]식량, [ICON_CITIZEN]시민, [ICON_HAPPINESS_1]행복 +2[NEWLINE][ICON_BULLET][ICON_CITIZEN]시민 2명마다 [ICON_CAPITAL]수도의 [ICON_CULTURE]문화 +1[NEWLINE][ICON_BULLET]모든 도시의 [ICON_FOOD]성장률 +5%[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]사우나[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR] [NEWLINE][ICON_BULLET]모든 도시의 [ICON_FOOD]성장률 +3%[NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_RESEARCH]과학 +1[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]상코레 대학[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]랜드마크 및 위인 시설의 [ICON_FOOD]식량 +1[NEWLINE][ICON_BULLET][ICON_CAPITAL]수도에 [COLOR_YELLOW]알현실[ENDCOLOR] 출현[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_ENGINEER][COLOR_YELLOW]위대한 기술자[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]진보[ENDCOLOR]는 탄탄한 사회 기반 시설과 과학 발전을 원하는 문명에 적합합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_CITIZEN]시민이 태어날 때 [ICON_RESEARCH]과학 20[NEWLINE][ICON_BULLET][ICON_CAPITAL]수도의 [ICON_CITIZEN]시민 1명마다 [ICON_RESEARCH]과학 15 [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR][NEWLINE][ICON_BULLET]기술 발견 시 [ICON_CULTURE]문화 15 [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR][NEWLINE][ICON_BULLET]이미 발견된 기술마다 [ICON_CULTURE]문화 15[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]시청[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR] [NEWLINE][ICON_BULLET]기술 발견 시 [ICON_CULTURE]문화 15 [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR][NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]자금성[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET][ICON_CITIZEN]시민이 태어날 때 [ICON_GOLD]골드 25 [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR][NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_WRITER][COLOR_YELLOW]위대한 작가[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]권위[ENDCOLOR]는 호전적이고 팽창을 지향하는 문명에 크게 도움이 됩니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]야만인 대항 전투력 보너스 +25%[NEWLINE][ICON_BULLET]야만인 주둔지 출현 시 알람[NEWLINE][ICON_BULLET]적 유닛 처치 및 야만인 주둔지 파괴 시 [ICON_CULTURE]문화 획득[NEWLINE][ICON_BULLET]모든 도시의 [ICON_PRODUCTION]생산 +1[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]성곽[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR] [NEWLINE][ICON_BULLET]모든 도시의 [ICON_PRODUCTION]생산 +1[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]알함브라 궁전[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET][COLOR_MAGENTA]공물[ENDCOLOR] 정책의 산출량 두 배[NEWLINE][ICON_BULLET][COLOR_YELLOW]자유용병대[ENDCOLOR], [COLOR_YELLOW]외인부대[ENDCOLOR], [COLOR_YELLOW]용병[ENDCOLOR] 구매 가능[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_GENERAL][COLOR_YELLOW]위대한 장군[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]충성[ENDCOLOR]은 [ICON_RELIGION]종교, 도시 인프라, 성장에 초점을 맞춘 제국에 적합합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][ICON_PEACE]신앙으로 [COLOR_YELLOW]수도원[ENDCOLOR] 구매 가능[NEWLINE][ICON_BULLET][ICON_PEACE]신앙으로 건물, 선교사, 이단심문관 구매 비용 -25%[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]장원[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_FOOD]식량 및 [ICON_STRENGTH]전투력 +1[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]붉은 요새[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]같은 종교에서 오는 [ICON_TOURISM]관광 +25%[NEWLINE][ICON_BULLET]당신 문명의 대중 종교를 따르는 도시의 [ICON_RESEARCH]과학, [ICON_PEACE]신앙, [ICON_PRODUCTION]생산, [ICON_CULTURE]문화 +30[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_ARTIST][COLOR_YELLOW]위대한 예술가[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]외교[ENDCOLOR]는 [ICON_INTERNATIONAL_TRADE]교역로, [ICON_CITY_STATE]도시 국가, [ICON_SPY]스파이, [ICON_DIPLOMAT]세계 대회에서 오는 보너스를 극대화하는 능력을 향상시킵니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]전역 [ICON_CITIZEN]시민 20명마다 [ICON_CAPITAL]수도의 모든 산출량 +1[NEWLINE][ICON_BULLET]모든 도시의 [ICON_GOLD]골드 +1[NEWLINE][ICON_BULLET][ICON_CAPITAL]수도에 [COLOR_YELLOW]외교공관[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]무역 임무의 [ICON_INFLUENCE]영향력 +10%[NEWLINE][ICON_BULLET]모든 도시의 [ICON_GOLD]골드 +1[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]웨스트민스터 궁전[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]세계 대회가 열릴 때마다 확보한 [ICON_DIPLOMAT]대표단 수에 기반한 [ICON_CULTURE]문화, [ICON_RESEARCH]과학, [ICON_GOLD]골드 제공 [COLOR:105:105:105:255](시대별 보정)[ENDCOLOR][NEWLINE][ICON_BULLET]동맹인 [ICON_CITY_STATE]도시 국가 3개마다 불가사의 건설에 필요한 정책 수 -1'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]미학[ENDCOLOR]은 [ICON_GREAT_WORK]걸작, [ICON_GREAT_PEOPLE]위인, [ICON_GOLDEN_AGE]황금기에 대한 잠재력을 극대화하는 능력을 강화합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_GREAT_PEOPLE]위인 출현율 +25%[NEWLINE][ICON_BULLET]모든 길드 건설 시 [ICON_PRODUCTION]생산 보너스 +100%[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]기념관[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_GOLDEN_AGE]황금기 점수 +2 [ICON_RESEARCH]과학 +1[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]루브르 박물관[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]사적지 발굴 또는 [ICON_GOLDEN_AGE]황금기 시작 시 알려진 모든 문명에 대한 [ICON_TOURISM]관광 증가[NEWLINE][ICON_BULLET]숨겨진 사적지 발굴 가능[NEWLINE][ICON_BULLET]랜드마크의 [ICON_RESEARCH]과학 및 [ICON_GOLDEN_AGE]황금기 점수 +3[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_MUSICIAN][COLOR_YELLOW]위대한 음악가[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]산업[ENDCOLOR]은 제국의 [ICON_GOLD]골드 및 [ICON_PRODUCTION]생산에 초점을 맞춘 보너스를 제공합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]무료 [ICON_INTERNATIONAL_TRADE]교역로 +2[NEWLINE][ICON_BULLET]구매에 필요한 [ICON_GOLD]골드 비용 -5%[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]창고[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]구매에 필요한 [ICON_GOLD]골드 비용 -5%[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]브로드웨이[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]모든 사치 자원의 전역 [ICON_HAPPINESS_1]행복 두 배[NEWLINE][ICON_BULLET]모든 전문가의 [ICON_PRODUCTION]생산 및 [ICON_GOLD]골드 +2[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_MERCHANT][COLOR_YELLOW]위대한 상인[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]제국주의[ENDCOLOR]는 군사력, 특히 해군(후반에는 공군)의 우위를 통해 제국 확장하는 능력을 강화합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]해상 유닛, 승선 유닛, [ICON_GREAT_GENERAL]위대한 장군 [ICON_MOVES]이동력 +1[NEWLINE][ICON_BULLET]근접 지상 유닛 및 근접 해상 유닛의 시야 +1[NEWLINE][ICON_BULLET]군사 유닛 [ICON_PRODUCTION]생산 보너스 +10%[NEWLINE][ICON_BULLET]군사 유닛 업그레이드 [ICON_GOLD]비용 -10%[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]식물원[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]군사 유닛 [ICON_PRODUCTION]생산 보너스 +5%[NEWLINE][ICON_BULLET]군사 유닛 업그레이드 [ICON_GOLD]비용 -5%[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]펜타곤[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET]주둔한 공군 유닛 1기마다 도시 [ICON_STRENGTH]방어력 +3 [ICON_HAPPINESS_3]불행 -3%[NEWLINE][ICON_BULLET]모든 해상 유닛에 [COLOR_PLAYER_PURPLE]철갑선[ENDCOLOR] 승급 부여[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_ADMIRAL][COLOR_YELLOW]위대한 제독[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]합리주의[ENDCOLOR]는 도시 성장 및 과학 산출량을 극대화 합니다.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]정책 개방 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 전략 자원의 [ICON_PRODUCTION]생산 +2 [ICON_RESEARCH]과학 +3[NEWLINE][ICON_BULLET]모든 도시의 [ICON_RESEARCH]과학 +5%[NEWLINE][ICON_BULLET]모든 요구 [ICON_HAPPINESS_3]불행 수치가 -5%[NEWLINE][ICON_BULLET]각 도시에 [COLOR_YELLOW]특허청[ENDCOLOR] 건설 가능[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]각 정책 채택 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET]모든 도시의 [ICON_RESEARCH]과학 +2%[NEWLINE][ICON_BULLET]모든 요구 [ICON_HAPPINESS_3]불행 수치 -2%[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]계열 완성 보너스:[ENDCOLOR][NEWLINE][ICON_BULLET][COLOR_YELLOW]블레츨리 파크[ENDCOLOR] 불가사의 건설 가능[NEWLINE][ICON_BULLET][ICON_GREAT_SCIENTIST]위대한 과학자 출현율 +33%[NEWLINE][ICON_BULLET]모든 도시의 성장률 +25%[NEWLINE][ICON_BULLET]산업 시대 이후 [ICON_PEACE]신앙으로 [ICON_GREAT_SCIENTIST][COLOR_YELLOW]위대한 과학자[ENDCOLOR] 구매 가능'
WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';

INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', '사우나'),
	('en_US', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', '시청'),
	('en_US', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', '성곽'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', '장원'),
	('en_US', 'TXT_KEY_BUILDING_TCS_CHANCERY', '외교공관'),
	('en_US', 'TXT_KEY_BUILDING_TCS_MEMORIAL', '기념관'),
	('en_US', 'TXT_KEY_BUILDING_TCS_DEPOT', '창고'),
	('en_US', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', '식물원'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', '특허청'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', '건설이 완료되면, [COLOR_POSITIVE_TEXT]국왕 경축일[ENDCOLOR]이 10턴 동안 열립니다. [COLOR_POSITIVE_TEXT]국왕 경축일[ENDCOLOR] 동안 [ICON_FOOD]식량이 +10% 증가합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]전통[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', '건설이 완료되면, [ICON_CULTURE_LOCAL]국경 확장 점수 +40을 즉시 제공합니다 (시대별 보정). 시청은 이후에 건설되는 다른 건물의 산출량을 증가시키기도 합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]진보[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', '요새와 성채의 [ICON_PRODUCTION]생산을 +1 증가시킵니다. 도시에서 훈련하는 모든 유닛에 경험치를 추가로 +5 제공합니다. 도시의 [ICON_STRENGTH]방어력이 +4 증가합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]권위[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', '도시의 체력이 +75 증가합니다. [ICON_CITIZEN]시민이 증가하면 [ICON_PRODUCTION]생산을 10 제공합니다 (시대별 보정). 군사 유닛 보급 한도가 [ICON_CITIZEN]시민의 10%만큼 증가합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]충성[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', '세계 의회의 [ICON_CITY_STATE]추가 대표단을 1명 얻습니다. [ICON_CITIZEN]시민 10명 마다 모든 산출량이 +1씩 증가합니다. 공무원 슬롯을 1개 제공합니다. 공무원의 [ICON_GOLD]골드, [ICON_RESEARCH]과학, [ICON_CULTURE]문화가 +1 증가합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]외교[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다. [COLOR_YELLOW][ICON_CAPITAL]수도에만[ENDCOLOR] 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', '도시의 [ICON_GREAT_PEOPLE]위인 출현율이 +10% 증가합니다. 도시에 [COLOR_POSITIVE_TEXT]길드가 있으면[ENDCOLOR] 산출량이 증가합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]미학[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', '해당 도시에서 건물이 건설될 때마다 [ICON_GOLD]골드를 +5 제공합니다. 상인 전문가 슬롯을 1개 제공합니다. 이 도시에서 출발하거나 도착하는 국내 [ICON_INTERNATIONAL_TRADE]교역로가 완료되면, 교역을 시작한 도시에 [ICON_GOLD]골드를 20 제공합니다 (시대별 보정).[NEWLINE][NEWLINE][COLOR_MAGENTA]산업[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', '[ICON_CITIZEN]시민 5명마다 [ICON_GOLDEN_AGE]황금기 점수와 [ICON_CULTURE]문화를 +1씩 제공합니다. 기술자 전문가 슬롯을 1개 제공합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]제국주의[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.'),
	('en_US', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', '[ICON_CITIZEN]시민 5명마다 [ICON_RESEARCH]과학을 +1씩 제공합니다. 과학자 전문가 슬롯을 1개 제공합니다. 전역 요구에서 오는 [ICON_HAPPINESS_3]불행을 -2% 감소시킵니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]합리주의[ENDCOLOR] 정책을 개방해야 건설할 수 있습니다.');

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
	SELECT 'BUILDINGCLASS_TCS_PUBLIC_BATHS', 'BUILDING_TCS_PUBLIC_BATHS', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'BUILDING_TCS_TOWN_COUNCIL', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_STRONGHOLD', 'BUILDING_TCS_STRONGHOLD', 'TXT_KEY_BUILDING_TCS_STRONGHOLD' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_CHANCERY', 'BUILDING_TCS_CHANCERY', 'TXT_KEY_BUILDING_TCS_CHANCERY' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_MEMORIAL', 'BUILDING_TCS_MEMORIAL', 'TXT_KEY_BUILDING_TCS_MEMORIAL' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_DEPOT', 'BUILDING_TCS_DEPOT', 'TXT_KEY_BUILDING_TCS_DEPOT' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_BOTANICAL_GARDENS', 'BUILDING_TCS_BOTANICAL_GARDENS', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS' UNION ALL
	SELECT 'BUILDINGCLASS_TCS_PATENT_OFFICE', 'BUILDING_TCS_PATENT_OFFICE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE';

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, PolicyBranchType, Description, Help, MinAreaSize, NukeImmune, NeverCapture, HurryCostModifier, IconAtlas, PortraitIndex)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'BUILDINGCLASS_TCS_PUBLIC_BATHS', 70, 1, NULL, 'POLICY_BRANCH_TRADITION', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 0 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 70, 1, NULL, 'POLICY_BRANCH_LIBERTY', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'BUILDINGCLASS_TCS_STRONGHOLD', 70, 1, NULL, 'POLICY_BRANCH_HONOR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 2 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'BUILDINGCLASS_TCS_PAROCHIAL_SCHOOL', 250, 0, NULL, 'POLICY_BRANCH_PIETY', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 3 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'BUILDINGCLASS_TCS_CHANCERY', 500, 5, NULL, 'POLICY_BRANCH_PATRONAGE', 'TXT_KEY_BUILDING_TCS_CHANCERY', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 4 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'BUILDINGCLASS_TCS_MEMORIAL', 250, 2, NULL, 'POLICY_BRANCH_AESTHETICS', 'TXT_KEY_BUILDING_TCS_MEMORIAL', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 5 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'BUILDINGCLASS_TCS_DEPOT', 500, 0, NULL, 'POLICY_BRANCH_COMMERCE', 'TXT_KEY_BUILDING_TCS_DEPOT', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 6 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'BUILDINGCLASS_TCS_BOTANICAL_GARDENS', 500, 2, NULL, 'POLICY_BRANCH_EXPLORATION', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 7 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'BUILDINGCLASS_TCS_PATENT_OFFICE', 500, 2, NULL, 'POLICY_BRANCH_RATIONALISM', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', -1, 1, 1, 25, 'POLICY_ICONATLAS', 8;

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
	SELECT 'BUILDING_TCS_CHANCERY', 'BUILDINGCLASS_PALACE';

INSERT INTO Building_DomainFreeExperiences (BuildingType, DomainType, Experience)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'DOMAIN_LAND', 5 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'DOMAIN_SEA', 5 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'DOMAIN_AIR', 5;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_FOOD', 2 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_CULTURE', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_FAITH', 2 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'YIELD_CULTURE', 2 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_PRODUCTION', 2 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 2 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_GREAT_GENERAL_POINTS', 2 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_GREAT_ADMIRAL_POINTS', 2 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_SCIENCE', 2;

INSERT INTO Building_WLTKDYieldMod (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'YIELD_FOOD', 10;
	
INSERT INTO Building_BuildingClassLocalYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange)
	SELECT 'BUILDING_AQUEDUCT', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_FOOD', 1 UNION ALL
	SELECT 'BUILDING_FORGE', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_LIBRARY', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_AMPHITHEATER', 'BUILDINGCLASS_TCS_TOWN_COUNCIL', 'YIELD_CULTURE', 1 UNION ALL
	SELECT 'BUILDING_MUSICIANS_GUILD', 'BUILDINGCLASS_TCS_MEMORIAL', 'YIELD_TOURISM', 3 UNION ALL
	SELECT 'BUILDING_ARTISTS_GUILD', 'BUILDINGCLASS_TCS_MEMORIAL', 'YIELD_GOLDEN_AGE_POINTS', 2 UNION ALL
	SELECT 'BUILDING_WRITERS_GUILD', 'BUILDINGCLASS_TCS_MEMORIAL', 'YIELD_CULTURE', 1;
	
INSERT INTO Building_InstantYield (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'YIELD_CULTURE_LOCAL', 40;

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_FOOD', 10 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_PRODUCTION', 10 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_GOLD', 10 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_CULTURE', 10 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_SCIENCE', 10 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_FAITH', 10 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'YIELD_TOURISM', 10 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_GOLDEN_AGE_POINTS', 20 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'YIELD_CULTURE', 20 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'YIELD_SCIENCE', 20;

INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_FORT', 'YIELD_PRODUCTION', 1 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'IMPROVEMENT_CITADEL', 'YIELD_PRODUCTION', 1;

INSERT INTO Building_YieldFromBirth (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'YIELD_PRODUCTION', 10;

INSERT INTO Building_SpecialistYieldChangesLocal (BuildingType, SpecialistType, YieldType, Yield)
	SELECT 'BUILDING_TCS_CHANCERY', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLD', 1 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_SCIENCE', 1 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_CULTURE', 1;
	
INSERT INTO Building_YieldFromConstruction (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 5;

INSERT INTO Building_YieldFromInternalTREnd (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_TCS_DEPOT', 'YIELD_GOLD', 20;

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_GROWTH', 15 UNION ALL
	SELECT 'BUILDING_TCS_PUBLIC_BATHS', 'FLAVOR_CULTURE', 10 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'FLAVOR_EXPANSION', 15 UNION ALL
	SELECT 'BUILDING_TCS_TOWN_COUNCIL', 'FLAVOR_CULTURE', 15 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_CITY_DEFENSE', 20 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_MILITARY_TRAINING', 20 UNION ALL
	SELECT 'BUILDING_TCS_STRONGHOLD', 'FLAVOR_OFFENSE', 5 UNION ALL
	SELECT 'BUILDING_TCS_PAROCHIAL_SCHOOL', 'FLAVOR_RELIGION', 20 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_PRODUCTION', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_GOLD', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_CULTURE', 5 UNION ALL
	SELECT 'BUILDING_TCS_CHANCERY', 'FLAVOR_DIPLOMACY', 15 UNION ALL
	SELECT 'BUILDING_TCS_MEMORIAL', 'FLAVOR_CULTURE', 20 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_GOLD', 10 UNION ALL
	SELECT 'BUILDING_TCS_DEPOT', 'FLAVOR_PRODUCTION', 15 UNION ALL
	SELECT 'BUILDING_TCS_BOTANICAL_GARDENS', 'FLAVOR_HAPPINESS', 10 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_SCIENCE', 20 UNION ALL
	SELECT 'BUILDING_TCS_PATENT_OFFICE', 'FLAVOR_GOLD', 5;

UPDATE Buildings
SET WLTKDTurns = 10
WHERE Type = 'BUILDING_TCS_PUBLIC_BATHS';
	
UPDATE Buildings
SET Defense = 400
WHERE Type = 'BUILDING_TCS_STRONGHOLD';	

UPDATE Buildings
SET FaithCost = 200, ExtraCityHitPoints = 75, CitySupplyModifier = 10
WHERE Type = 'BUILDING_TCS_PAROCHIAL_SCHOOL';

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_CIVIL_SERVANT', SpecialistCount = 1, SingleLeagueVotes = 1
WHERE Type = 'BUILDING_TCS_CHANCERY';

UPDATE Buildings
SET GreatPeopleRateModifier = 10
WHERE Type = 'BUILDING_TCS_MEMORIAL';

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_MERCHANT', SpecialistCount = 1
WHERE Type = 'BUILDING_TCS_DEPOT';			

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_ENGINEER', SpecialistCount = 1
WHERE Type = 'BUILDING_TCS_BOTANICAL_GARDENS';

UPDATE Buildings
SET PovertyHappinessChange = -2, DefenseHappinessChange = -2, IlliteracyHappinessChange = -2, UnculturedHappinessChange = -2, MinorityHappinessChange = -2, SpecialistType = 'SPECIALIST_SCIENTIST', SpecialistCount = 1
WHERE Type = 'BUILDING_TCS_PATENT_OFFICE';