UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '전통 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_TRADITION} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PUBLIC_BATHS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '진보 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_LIBERTY} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_TOWN_COUNCIL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_GOLD] 골드 +1'
	WHERE Tag = 'TXT_KEY_POLICY_COLLECTIVE_RULE_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_GOLDEN_AGE] 황금기 점수 +1'
	WHERE Tag = 'TXT_KEY_POLICY_CITIZENSHIP_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_PRODUCTION] 생산력 +1'
	WHERE Tag = 'TXT_KEY_POLICY_REPUBLIC_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_RESEARCH] 과학 +1'
	WHERE Tag = 'TXT_KEY_POLICY_REPRESENTATION_HELP';

UPDATE Language_ko_KR
	SET Text = Text || '[NEWLINE][ICON_BULLET] 시청에서 [ICON_FOOD] 식량 +1'
	WHERE Tag = 'TXT_KEY_POLICY_MERITOCRACY_HELP';
	
UPDATE Language_ko_KR
	SET TEXT = REPLACE(Text, '성을 향해', '영주 저택을 향해, 성,')
	WHERE Tag = 'TXT_KEY_POLICY_MANDATE_OF_HEAVEN_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '권위 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_HONOR} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_STRONGHOLD}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_HONOR_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '충성 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_PIETY} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PIETY_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '외교 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_PATRONAGE} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_CHANCERY}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '미학 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_AESTHETICS} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_MEMORIAL}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '산업 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_COMMERCE} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_PATENT_OFFICE}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '제국 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_EXPLORATION} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_DEPOT}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP';

UPDATE	Language_ko_KR SET
		Text = REPLACE(Text, '합리 채택 보상:[ENDCOLOR]', '{TXT_KEY_POLICY_BRANCH_RATIONALISM} 채택 보상:[ENDCOLOR][NEWLINE][ICON_BULLET] 건물 해제: [COLOR_POSITIVE_TEXT]{TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS}[ENDCOLOR].')
		WHERE Tag = 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP';

INSERT INTO LocalizedText
	(Language, Tag, Text)
VALUES
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS', '시스턴'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL', '시청'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD', '성채'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL', '영주 저택'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_CHANCERY', '대사관'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_MEMORIAL', '기념비'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_DEPOT', '창고'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS', '식물원'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE', '특허청'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PUBLIC_BATHS_HELP', '새로운 [ICON_CITIZEN] 시민이 태어난 후 [ICON_FOOD] 식량의 10%가 이월됩니다. 이 도시에서 10턴 동안 "국왕 경축일"을 시작합니다.[NEWLINE]이 도시에서 작업 중인 {TXT_KEY_BUILDING_WELL}과 {TXT_KEY_BUILDING_BATH}으로부터 [ICON_FOOD] 식량 +1을 얻습니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_TRADITION}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다. '),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_TOWN_COUNCIL_HELP', '[ICON_CONNECTED] 도시 연결로 얻는 [ICON_GOLD] 골드가 +3% 증가하고 [ICON_INDUSTRIAL_CONNECTED] 산업 도시 연결로 얻는 생산력이 +3% 증가합니다. [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_LIBERTY}[ENDCOLOR] 정책이 해제되면 시청에서 추가 산출량을 생성합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_LIBERTY}[ENDCOLOR]를 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_STRONGHOLD_HELP', '[ICON_CULTURE_LOCAL] 국경 성장이 +3 증가합니다. 완성되면 [ICON_CULTURE_LOCAL] 국경 성장이 +75 증가합니다. 요새와 성채의 [ICON_PRODUCTION] 생산력이 +1 증가합니다. [NEWLINE][COLOR_CYAN]{TXT_KEY_TECH_ENGINEERING}[ENDCOLOR]을 발견하면 [ICON_RESEARCH] 과학이 +1 증가합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_HONOR}[ENDCOLOR]를 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PAROCHIAL_SCHOOL_HELP', '건설이 완료되면 [ICON_FOOD] 식량 +100를 얻습니다. 이 도시에서 [ICON_PEACE] 신앙 구매 비용의 15%를 [ICON_FOOD] 식량과 [ICON_CULTURE] 문화로 얻습니다. "국왕 경축일" 동안 [ICON_PEACE] 신앙이 +15% 증가합니다.[NEWLINE][ICON_CITY_STATE] 이 도시에서 문명 크기 수정치가 5% 감소합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_PIETY}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_CHANCERY_HELP', '[ICON_RES_PAPER] 종이 +1을 추가합니다. 세계 의회에서 [COLOR_POSITIVE_TEXT]추가[ENDCOLOR] [ICON_DIPLOMAT] 대표 1명을 받습니다. 모든 도시의 공무원은 [ICON_GOLD] 골드 +1을 생산합니다.[NEWLINE]도시 국가 친구 1명당 [ICON_GOLD] 골드 +1, 동맹 1명당 [ICON_RESEARCH] 과학 +1, [ICON_CULTURE] 문화 +1 를 추가로 획득합니다.[NEWLINE][NEWLINE][ICON_CAPITAL] 수도에만 건설할 수 있고 [COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_PATRONAGE}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_MEMORIAL_HELP', '도시 내 위대한 [ICON_GREAT_WRITER] 작가, [ICON_GREAT_ARTIST] 예술가, [ICON_GREAT_MUSICIAN] 음악가에게 [ICON_GREAT_PEOPLE] 위인 점수 +1를 줍니다.[NEWLINE][ICON_GREAT_PEOPLE] 위인을 소모하면 [ICON_RESEARCH] 과학, [ICON_GOLDEN_AGE] 황금기 점수를 +5 얻습니다. (시대에 따라 조정)[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_AESTHETICS}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_DEPOT_HELP', '+1 [ICON_GREAT_GENERAL] Great General Point, [ICON_GREAT_ADMIRAL] Great Admiral Point. 이 도시와의 내부 [ICON_INTERNATIONAL_TRADE] 교역로가 완성되면 출발하는 도시에 [ICON_GOLD] 골드 100이 생성됩니다. (시대에 따라 조정)[NEWLINE][NEWLINE]이 도시에서 유닛을 훈련할 때, 유닛 [ICON_PRODUCTION] 생산력의 10%에 해당하는 [ICON_CULTURE] 문화를 얻습니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_EXPLORATION}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_BOTANICAL_GARDENS_HELP', '도시에서 작업하는 정글, 숲, 범람원 2개마다 [ICON_RESEARCH] 과학이 +1 증가합니다. 모든 습지, 오아시스, 산호섬에서 과학이 +1 [ICON_RESEARCH] 증가합니다.[NEWLINE][NEWLINE]도시에 있는 [ICON_VP_SCIENTIST] 과학자, {TXT_KEY_BUILDING_GARDEN}, {TXT_KEY_BUILDING_THEATRE}에서 [ICON_FOOD] 식량 +2를 생성합니다.[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_RATIONALISM}[ENDCOLOR]를 채택하는 경우에만 건설할 수 있습니다.'),
	('ko_KR', 'TXT_KEY_BUILDING_TCS_PATENT_OFFICE_HELP', '이 도시의 [ICON_VP_ENGINEER] 기술자, [ICON_VP_MERCHANT] 상인, [ICON_GREAT_WORK] 걸작으로부터 [ICON_GOLD] 골드, [ICON_RESEARCH] 과학을 +1 얻습니다.[NEWLINE][NEWLINE]기술을 연구할 때마다 [ICON_GOLD] 골드, [ICON_PRODUCTION] 생산력, [ICON_GOLDEN_AGE] 황금기 점수를 20 얻습니다. (시대에 따라 보정)[NEWLINE][NEWLINE][COLOR_MAGENTA]{TXT_KEY_POLICY_BRANCH_COMMERCE}[ENDCOLOR]을 채택하는 경우에만 건설할 수 있습니다.');