name: VPKR+ModPack
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: iscc "vp_modmods_kr mpinstaller file/VPKRMP.iss" /O"out_githubaction" /F"VPKR+ModPack"
      - uses: actions/upload-artifact@v4
        with:
          name: "VPKR+ModPack"
          path: "out_githubaction/VPKR+ModPack.exe"