name: VP INT MP Ex build to .exe
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: iscc "vp_modmods_kr mpinstaller file/VPINTModpack.iss" /O"out_githubaction" /F"VP INT Modpack Ex"
      - uses: actions/upload-artifact@v4
        with:
          name: "VP INT Modpack Ex"
          path: "out_githubaction/VP INT Modpack Ex.exe"
