name: vp_kr+
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: iscc "vp_modmods_kr installer file/VPKR.iss" /O"out_githubaction" /F"VP 한국어"
      - uses: actions/upload-artifact@v4
        with:
          name: "VP 한국어"
          path: "out_githubaction/VP 한국어.exe"