INSERT INTO UnitPromotions 
	(Type, Description, Help, Sound, 
	LostWithUpgrade, OrderPriority, CannotBeChosen, PortraitIndex, IconAtlas,	PediaType,	PediaEntry, 
	EnemyRoute, HillsDoubleMove, IsVisibleAboveFlag) 
VALUES 
	('PROMOTION_SURVEYMAPS', 'TXT_KEY_PROMOTION_SURVEYMAPS',	'TXT_KEY_PROMOTION_SURVEYMAPS_HELP',	'AS2D_IF_LEVELUP',	
	0, 1,	1, 59, 'extraPromo_Atlas', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SURVEYMAPS', 
	1, 1, 0);

INSERT INTO Technology_FreePromotions
	(TechType, PromotionType)
VALUES
	('TECH_BALLISTICS', 'PROMOTION_SURVEYMAPS');

INSERT INTO UnitPromotions_UnitCombats
	(PromotionType, UnitCombatType)
VALUES 
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_MELEE'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_ARCHER'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_MOUNTED'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_GUN'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_SIEGE'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_ARMOR'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_GUN'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_SETTLER'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_WORKER'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_MISSIONARY'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_INQUISITOR'),
	('PROMOTION_SURVEYMAPS', 'UNITCOMBAT_DIPLOMACY');

INSERT OR REPLACE INTO Language_en_US 
	(Tag, Text)
Values 
	('TXT_KEY_PROMOTION_SURVEYMAPS', 'Ordnance Survey'),
	('TXT_KEY_PROMOTION_SURVEYMAPS_HELP', 'Double [ICON_MOVES] Movement in [COLOR_POSITIVE_TEXT]Hills[ENDCOLOR].[NEWLINE]Can use Enemy Routes.');

UPDATE Technology_FreePromotions SET TechType = 'TECH_DYNAMITE' WHERE PromotionType = 'PROMOTION_ICE_BREAKERS';