-- temperance
INSERT INTO Language_ko_KR
	(Tag, Text)
VALUES	('TXT_KEY_BUILDING_PROSPERITY_SPEAKEASY', 'Speakeasy'),
	('TXT_KEY_BUILDING_PROSPERITY_SPEAKEASY_HELP', 'Internal [ICON_INTERNATIONAL_TRADE] Trade Routes to or from this City generate 25 [ICON_GOLD] Gold and [ICON_CULTURE] Culture when completed, scaling with Era. Incoming [ICON_ARROW_LEFT] Trade Routes generate +2 [ICON_GOLD] Gold for the City and for the [ICON_ARROW_RIGHT] Trade Route owner. [COLOR_NEGATIVE_TEXT]Reduces[ENDCOLOR] the [ICON_FOOD] Food output of the City by [COLOR_NEGATIVE_TEXT]-12[ENDCOLOR].[NEWLINE][NEWLINE]Nearby Farms: +1 [ICON_GOLD] Gold and [ICON_CULTURE] Culture.[NEWLINE][NEWLINE]Requires the [COLOR_MAGENTA]Temperance[ENDCOLOR] Policy.'),
	('TXT_KEY_BUILDING_PROSPERITY_SPEAKEASY_STRATEGY', 'The Speakeasy boosts Gold and Culture output, but this is in the context of removing large amounts of free Food the Temperance Policy gives for following your Religion. If you want to break prohibition by building the Speakeasy, you will trade in your growth bonus for other yields, and so this decision has to be made on a City-by-City basis. Additionally, the bonuses to trade routes allow Internal options to be explored while trying to attract International routes to compensate you for shifting away from them yourself.'),
	('TXT_KEY_BUILDING_PROSPERITY_SPEAKEASY_TEXT', 'A speakeasy, also called a beer flat or blind pig or blind tiger, was an illicit establishment that sold alcoholic beverages. Speakeasy bars in the United States date back to at least the 1880s, but came into prominence in the United States during the Prohibition era (1920–1933, longer in some states). During that time, the sale, manufacture, and transportation (bootlegging) of alcoholic beverages was illegal throughout the United States, due to the Eighteenth Amendment to the United States Constitution. The quality of the alcohol sold in speakeasies ranged from very poor to very good, depending on the owner''s source. Cheap liquor was generally used because it was more profitable, was responsible for a shift away from 19th-century "classic" cocktails, that celebrated the raw taste of the liquor (such as the gin cocktail, made with Genever (sweet) gin), to new cocktails aimed at masking the taste of rough moonshine.');

-- great awakening
INSERT INTO Language_ko_KR
	(Tag, Text)
VALUES	('TXT_KEY_BUILDING_PROSPERITY_CAMP', 'Chautauqua'),
	('TXT_KEY_BUILDING_PROSPERITY_CAMP_HELP', 'Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this City by 25%. +25% [ICON_GREAT_PEOPLE] Great Person generation in this City. Gain 20 [ICON_CULTURE] Culture in the City when its borders expand, scaling with Era. +4 [ICON_CULTURE_LOCAL] Border Growth Points from [ICON_GREAT_WORK] Great Works in this City.[NEWLINE][NEWLINE]Requires the [COLOR_MAGENTA]Great Awakening[ENDCOLOR] Policy.'),
	('TXT_KEY_BUILDING_PROSPERITY_CAMP_STRATEGY', 'The Chautauqua can be Purchased in weaker Cities and then, by moving Great Works there, turbo-charge its Border Growth and all the yields that might come from that. It also boosts Great People generation and Religious Pressure, which are both excellent in stronger Cities, where you might instead choose to construct the Building with Production.'),
	('TXT_KEY_BUILDING_PROSPERITY_CAMP_TEXT', 'In 1874, Methodist Episcopal minister John Heyl Vincent and businessman Lewis Miller organized the New York Chautauqua Assembly at a campsite on the shores of Chautauqua Lake in the state of New York. The gatherings grew in popularity and spread across the country. Some were so religiously oriented that they were essentially church camps, while more secular Chautauquas resembled summer school and competed with vaudeville in theaters and circus tent shows with their animal acts and trapeze acrobats. In all cases lectures were the mainstay of the Chautauqua. The most prolific speaker was Russell Conwell, who delivered his famous "Acres of Diamonds" speech 5,000 times to audiences on the Chautauqua and Lyceum circuits.');