INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARMOR';

INSERT INTO Building_SpecialistYieldChanges (BuildingType, SpecialistType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 2 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'BUILDING_FA_CENTRAL_BANK', 'SPECIALIST_MERCHANT', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'BUILDING_FA_CENTRAL_BANK', 'SPECIALIST_MERCHANT', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK');

INSERT INTO Building_HurryModifiers
		(BuildingType, HurryType, HurryCostModifier)
VALUES	('BUILDING_FA_CENTRAL_BANK', 'HURRY_GOLD', -10);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'YIELD_GOLD', 4 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'BUILDING_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 2 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'BUILDING_FA_SEA_ACADEMY', 'YIELD_GREAT_ADMIRAL_POINTS', 2 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');

UPDATE Building_Flavors
SET Flavor = 0
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND FlavorType = 'FLAVOR_HAPPINESS';

UPDATE Building_BuildingClassHappiness
SET Happiness = 0
WHERE BuildingClassType = 'BUILDINGCLASS_FA_ELECTRIC_POWER' AND BuildingType = 'BUILDING_FA_ELECTRIC_CO';

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_BANK';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION';

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_HARBOR'
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_TRAINSTATION'
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION';

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'BUILDINGCLASS_BANK' WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK');

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD';

DELETE FROM Building_DomainFreeExperiences
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

DELETE FROM Building_DomainProductionModifiers
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY';

DELETE FROM Building_DomainFreeExperiences
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

DELETE FROM Building_DomainProductionModifiers
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), TrainedFreePromotion = 'PROMOTION_GENERAL_STACKING', GreatGeneralRateModifier = 0, CitySupplyModifier = 10, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_PRINTING_PRESS'), FreeBuildingThisCity = NULL
WHERE Type = 'BUILDING_FA_WAR_ACADEMY';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HERMITAGE'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_HERMITAGE'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_HERMITAGE'), FreePromotion = 'PROMOTION_FA_SEA_ACADEMY', TrainedFreePromotion = NULL, CitySupplyFlat = 2, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')
WHERE Type = 'BUILDING_FA_SEA_ACADEMY';

UPDATE Buildings
SET Cost = ((SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'))/2, NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'), NationalPopRequired = ((SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'))/2, GreatPeopleRateChange = 1, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU')
WHERE Type = 'BUILDING_FA_CENTRAL_BANK';

UPDATE Buildings
SET Cost = ((SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'))/2, NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'), NationalPopRequired = ((SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_HERMITAGE')+(SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'))/2, CityConnectionTradeRouteModifier = 25, HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU')
WHERE Type = 'BUILDING_FA_CENTRAL_STATION';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU'), HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FOREIGN_BUREAU')
WHERE Type = 'BUILDING_FA_AIR_ACADEMY';

UPDATE Buildings
SET Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), NumCityCostMod = (SELECT NumCityCostMod FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), FreeBuilding = 'BUILDINGCLASS_FA_ELECTRIC_POWER', HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_INTELLIGENCE_AGENCY'), GoldMaintenance = 0, FreeBuildingThisCity = 'BUILDINGCLASS_HYDRO_PLANT'
WHERE Type = 'BUILDING_FA_ELECTRIC_CO';

UPDATE Language_en_US
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_BANK_HELP';

UPDATE Language_en_US
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION_HELP';

UPDATE Language_en_US
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO_HELP';

UPDATE Language_en_US
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_WAR_ACADEMY_HELP';

UPDATE Language_en_US
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_SEA_ACADEMY_HELP';

UPDATE Language_en_US
SET Text = ''
WHERE Tag = 'TXT_KEY_BUILDING_FA_AIR_ACADEMY_HELP';

UPDATE Language_en_US
SET Text = '+50% Experience gained from Combat. +1 [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_FA_SEA_ACADEMY_HELP';

UPDATE UnitPromotions
SET ExperiencePercent = 50, MovesChange = 1, PortraitIndex = 34, IconAtlas = 'PROMOTION_ATLAS_VP_01'
WHERE Type = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_Domains 
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_Terrains
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY';

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL';

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND UnitType = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND UnitType = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_ELECTRIC_CO';

DELETE FROM Units
WHERE Type = 'UNIT_FA_CENTRAL_STATION';

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND UnitType = 'UNIT_GREAT_ADMIRAL';

INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_AIR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_ELECTRIC_CO') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 1 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');

INSERT INTO Policy_BuildingClassProductionModifiers (PolicyType, BuildingClassType, ProductionModifier)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_AIR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_ELECTRIC_CO') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_BANK') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_CENTRAL_STATION') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_WAR_ACADEMY') UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 25 WHERE EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_FA_SEA_ACADEMY');